// QuotesLang_it.swift
// Spike AI — Bundled quote translations
import Foundation
enum QuotesLang_it {
    static let quotes: [String] = [
        "Qualunque cosa tu tenga costantemente nella tua mente è esattamente ciò che sperimenterai nella vita.",
        "Miriamo al di sopra del bersaglio per colpire il bersaglio.",
        "La cosa peggiore che posso essere è uguale a tutti gli altri, detesto questo.",
        "Solo coloro che rischieranno di andare troppo lontano potranno scoprire quanto lontano si può arrivare.",
        "Salta e la rete apparirà.",
        "Una nave in porto è al sicuro, ma non è per questo che le navi sono costruite.",
        "Non preoccuparti dei fallimenti, preoccupati delle occasioni che perdi quando non ci provi nemmeno.",
        "Coloro che osano fallire miseramente possono ottenere grandi risultati.",
        "Il modo per iniziare è smettere di parlare e cominciare a fare.",
        "Possiamo incontrare molte sconfitte, ma non dobbiamo essere sconfitti.",
        "La vera misura di un uomo è come tratta qualcuno che non può essergli di alcun aiuto.",
        "Devi stare attento se non sai dove stai andando, perché potresti non arrivarci.",
        "Devi aspettarti grandi cose da te stesso prima di poterle fare.",
        "Non lasciare mai che le decisioni passate determinino i tuoi risultati futuri.",
        "Le scorciatoie causano lunghi ritardi.",
        "Nessuno può darti i tuoi obiettivi. Questo è il tuo viaggio.",
        "Il mondo è ciò che ne pensi, quindi pensalo diversamente e il tuo mondo cambierà.",
        "Il futuro appartiene a coloro che si preparano oggi.",
        "Non rinunciare a ciò che desideri di più per ciò che desideri adesso.",
        "Non dirmi quanto sei talentuoso, dimmi quanto lavori duramente.",
        "Il modo in cui pensi quando perdi determina quanto tempo passerà prima che tu vinca.",
        "Ogni volta che una persona decide di aver raggiunto il successo, il progresso si ferma.",
        "Nessun problema può resistere all'assalto di un pensiero costante.",
        "La fortuna è quando un'opportunità si presenta e tu sei preparato.",
        "Il segreto per andare avanti è iniziare.",
        "Il momento migliore per piantare un albero era 20 anni fa. Il secondo momento migliore è adesso.",
        "È difficile battere una persona che non si arrende mai.",
        "Scrivilo. Filmalo. Pubblicalo. Lavoralo all'uncinetto, saltalo in padella. Qualunque cosa, crea!",
        "Qualunque cosa tu sia, sii una buona versione.",
        "La felicità non è qualcosa di già pronto, viene dalle tue stesse azioni.",
        "Le persone intelligenti imparano da tutto e da tutti.",
        "Impossibile è solo un'opinione.",
        "La tua passione sta aspettando che il tuo coraggio la raggiunga.",
        "Le persone che si chiedono se il bicchiere è mezzo vuoto o mezzo pieno non colgono il punto. Il bicchiere è riempibile.",
        "Un giorno o il primo giorno; decidi tu.",
        "Le cose possono arrivare a chi aspetta, ma solo quelle lasciate da chi si dà da fare.",
        "Tutto arriva a chi si dà da fare mentre aspetta.",
        "Lavora come se ci fosse qualcuno che lavora 24 ore al giorno per portartelo via.",
        "Nessuno ha mai fatto la differenza essendo come tutti gli altri.",
        "Avrai momenti brutti, ma ti risveglieranno sempre alle cose belle a cui non stavi prestando attenzione.",
        "Sii una versione di prima classe di te stesso, non una versione di seconda classe di qualcun altro.",
        "Impara dagli errori degli altri. Non puoi vivere abbastanza a lungo per farli tutti tu stesso.",
        "Se sei stanco, fallo stanco.",
        "Un uomo non è finito quando viene sconfitto, è finito quando si arrende.",
        "Il mondo è cambiato dal tuo esempio, non dalla tua opinione.",
        "La vita è come andare in bicicletta. Per mantenere l'equilibrio devi continuare a muoverti.",
        "Pensando alla vita: nessuna quantità di senso di colpa può cambiare il passato, nessuna quantità di ansia può cambiare il futuro.",
        "Una mente negativa non ti darà mai una vita positiva.",
        "Tutto è difficile prima di diventare facile.",
        "Rischia, o perdi l'occasione.",
        "Non smettere mai di imparare, perché la vita non smette mai di insegnare.",
        "Chi non legge non ha alcun vantaggio rispetto a chi non sa leggere.",
        "Una persona che non ha mai commesso un errore non ha mai provato nulla di nuovo.",
        "Il modo più comune in cui le persone rinunciano al proprio potere è pensare di non averne.",
        "Sii grato per ciò che hai; finirai per avere di più. Concentrati su ciò che non hai e non ne avrai mai abbastanza.",
        "La cosa più difficile è la decisione di agire, il resto è semplicemente tenacia.",
        "Molti dei fallimenti della vita sono persone che non si sono rese conto di quanto fossero vicine quando si sono arrese.",
        "Non importa se vieni abbattuto, importa se ti rialzi.",
        "Il pessimista vede la difficoltà in ogni opportunità. L'ottimista vede l'opportunità in ogni difficoltà.",
        "La nostra gloria più grande non sta nel non cadere mai, ma nel rialzarci ogni volta che cadiamo.",
        "Non farti spingere dalle paure nella tua mente; lasciati guidare dai sogni nel tuo cuore.",
        "Quando sai cosa vuoi e lo vuoi abbastanza, troverai un modo per ottenerlo.",
        "Inizia facendo ciò che è necessario, poi fai ciò che è possibile, e improvvisamente stai facendo l'impossibile.",
        "Senza passione non hai energia, senza energia non hai niente.",
        "Non devi essere grande per iniziare, ma devi iniziare per essere grande.",
        "La forza non viene dalla capacità fisica, viene da una volontà indomabile.",
        "Nessuno è inutile in questo mondo se alleggerisce i fardelli di un altro.",
        "Chiedendo l'impossibile otteniamo il possibile.",
        "È meglio essere un leone per un giorno che una pecora per tutta la vita.",
        "La vita è troppo importante per essere presa sul serio.",
        "L'inizio è la metà di ogni azione.",
        "La pazienza infinita porta risultati immediati.",
        "Quasi tutti gli uomini muoiono dei loro rimedi e non delle loro malattie.",
        "Sono capaci, perché pensano di esserlo.",
        "L'immaginazione è più importante della conoscenza.",
        "Le persone persistenti iniziano il loro successo dove gli altri finiscono nel fallimento.",
        "Non ci sono sentieri chiari. Solo trabocchetti, fili tesi e oscurità.",
        "Un errore dimostra che qualcuno ha smesso di parlare abbastanza a lungo per fare qualcosa.",
        "Qualunque cosa valga la pena di fare, vale la pena di farla bene.",
        "Il più potente è colui che ha se stesso in suo potere.",
        "Uno studioso che coltiva l'amore per il comfort non è degno di essere chiamato studioso.",
        "La prosperità dipende più dal volere ciò che hai che dall'avere ciò che vuoi.",
        "Ogni giorno arriva portando i suoi doni, sciogli i nastri.",
        "Il successo non è mai permanente e il fallimento non è mai definitivo.",
        "Niente dura per sempre. Nemmeno i tuoi problemi.",
        "Il duro lavoro non garantisce il successo, ma ne migliora le possibilità.",
        "La pace non può essere mantenuta con la forza. Può essere raggiunta solo con la comprensione.",
        "Chi non rischia non ha fortuna.",
        "Non dire quando avrò tempo studierò, potresti non avere tempo.",
        "Chi perde la fede perde tutto.",
        "Il proprio pensiero è il proprio mondo. Ciò che una persona pensa è ciò che diventa.",
        "L'avventura non è fuori dall'uomo, è dentro.",
        "Il gioco della vita non sta tanto nel tenere buone carte, quanto nel giocare bene una mano povera.",
        "Aspro, dolce, amaro, pungente: tutto deve essere provato.",
        "Non lasciare mai che il senso del fallimento passato sconfigga il tuo prossimo passo.",
        "A meno che tu non sia ambizioso, non fai progressi.",
        "Il futuro appartiene a coloro che osano.",
        "I fatti non cessano di esistere perché vengono ignorati.",
        "Non dobbiamo mai dare per scontato ciò che è incapace di dimostrazione.",
        "Una voce forte non può competere con una voce chiara, anche se è un sussurro.",
        "Comportati come se ti aspettassi di arrivare in zona meta.",
        "La felicità è il fiore naturale del dovere.",
        "\"No\" significa semplicemente ricominciare a un livello superiore.",
        "L'entusiasmo muove il mondo.",
        "Un campione è qualcuno che si rialza quando non ce la fa.",
        "Gli ostacoli sono il costo della grandezza.",
        "La domanda non è chi mi lascerà fare, ma chi mi fermerà.",
        "Non ero lì per competere, ero lì per vincere.",
        "Smetti di lamentarti, inizia a lavorare duro.",
        "Dalle difficoltà nascono i miracoli.",
        "Non ho paura, sono nata per fare questo.",
        "Non chinare mai la testa. Tienila alta. Guarda il mondo dritto negli occhi.",
        "Fai ciò che devi fare finché non puoi fare ciò che vuoi fare.",
        "Se sei caduto ieri, alzati oggi.",
        "Fai di ogni giorno il tuo capolavoro.",
        "Sangue, sudore e rispetto. I primi due li dai, l'ultimo te lo guadagni.",
        "Sii così bravo che non possano ignorarti.",
        "Mostra al mondo quanto lotterai per il cerchio dei vincitori.",
        "Se non progetti la tua vita, è probabile che finirai nel piano di qualcun altro. Cosa hanno in programma per te? Non molto.",
        "L'unica persona che sei destinato a diventare è la persona che decidi di essere.",
        "Non aspettare che il ferro sia caldo per battere; rendilo caldo battendolo.",
        "Non posso credere che Dio ci abbia messo su questa terra per essere ordinari.",
        "Voglio che il mondo sia migliore perché io ero qui.",
        "L'abitudine della persistenza è l'abitudine della vittoria.",
        "Non aver paura di rinunciare al buono per puntare al grande.",
        "Fai il tuo dovere e un po' di più, e il futuro si prenderà cura di se stesso.",
        "La vita ha un modo di mettere alla prova la volontà di una persona. O non succede niente oppure succede tutto in una volta.",
        "Un uomo saggio si trova sempre da solo. Un uomo debole si trova sempre nella folla.",
        "Osare significa perdere l'equilibrio per un momento. Non osare significa perdere se stessi.",
        "La paura sconfigge più persone di qualsiasi altra cosa al mondo.",
        "Le parole più potenti dell'universo sono quelle che usi per parlare con te stesso.",
        "L'unica cosa che arriva a un uomo che dorme sono i sogni.",
        "Se non conquisti te stesso, sarai conquistato da te stesso.",
        "Un eroe è colui che sa resistere un minuto in più.",
        "Vai fin dove puoi vedere, quando ci arrivi potrai vedere più lontano.",
        "Non scopri il tuo posto nel mondo, te lo ricavi.",
        "I vincitori si concentrano sulla vittoria. I perdenti si concentrano sui vincitori.",
        "Il fallimento non mi supererà mai se la mia determinazione a riuscire è abbastanza forte.",
        "Ciò che viene facile non dura. Ciò che dura non viene facile.",
        "Per evitare le critiche: non dire nulla, non fare nulla, non essere nulla.",
        "L'uomo che fa più di quanto viene pagato presto sarà pagato più di quanto fa.",
        "Il genio inizia le grandi opere, solo il lavoro le porta a termine.",
        "Anche se sei sulla strada giusta, verrai investito se resti fermo.",
        "Se le cose non falliscono, non stai innovando abbastanza.",
        "Ottieni il meglio dagli altri quando dai il meglio di te stesso.",
        "La leadership è un'azione, non una posizione.",
        "Il nostro lavoro è la presentazione delle nostre capacità.",
        "Tutti i miei problemi si inchinano davanti alla mia testardaggine.",
        "Indossa il tuo fallimento come un distintivo d'onore.",
        "Siamo limitati non dalle nostre capacità, ma dalla nostra visione.",
        "Se sei stanco, impara a riposare, non a mollare.",
        "Cadere è un incidente, restare a terra è una scelta.",
        "Non osare arrenderti a questa vita. Non stasera. Non domani. Mai.",
        "Non lasciarti mai abbattere da persone o eventi.",
        "Alcune persone sognano il successo mentre altre si svegliano e lavorano duramente per raggiungerlo.",
        "La fiducia viene dall'esperienza. Le esperienze vengono dal provare, fallire e riprovare, questa volta meglio.",
        "Il tempo che porta alla maestria dipende dall'intensità della nostra concentrazione.",
        "Il successo arriva solo a coloro che osano tentare.",
        "Una chiave importante per il successo è la fiducia in sé stessi. Una chiave importante per la fiducia in sé stessi è la preparazione.",
        "Il dubbio uccide più sogni di quanto il fallimento farà mai.",
        "La vittoria è sempre possibile per la persona che rifiuta di smettere di combattere.",
        "Non cambierai mai la tua vita finché non cambierai qualcosa che fai quotidianamente.",
        "Per avere successo la tua concentrazione deve essere così intensa che gli altri pensano che tu sia pazzo.",
        "Gli ostacoli sono quelle cose spaventose che vedi quando togli gli occhi dal tuo obiettivo.",
        "Trovare un'opportunità è questione di credere che sia lì.",
        "Fissare obiettivi è il primo passo per trasformare l'invisibile in visibile.",
        "Se non rischi niente, rischi tutto.",
        "Se non puoi cambiare la tua situazione, cambia la tua mentalità.",
        "Non importa quanto duro sia stato il passato, puoi sempre ricominciare.",
        "Se non osi nulla, quando il giorno sarà finito non avrai guadagnato nulla.",
        "Molto spesso un cambiamento di sé è più necessario di un cambiamento di scena.",
        "La paura è la più grande disabilità di tutte e ti paralizzerà.",
        "Ciò che è pericoloso è non evolversi.",
        "In ogni caso troverò una via o ne creerò una.",
        "L'unico modo per far tacere tutti è vincere.",
        "Non lasciare mai che abbastanza buono sia abbastanza buono.",
        "Alla lunga colpiamo solo ciò a cui miriamo.",
        "Il miglioramento continuo è meglio della perfezione ritardata.",
        "Se lo vedi nella tua mente lo terrai nella tua mano.",
        "Oggi farò ciò che gli altri non faranno, così domani potrò fare ciò che gli altri non possono.",
        "L'eccellenza è un'arte vinta dall'allenamento e dall'abitudine.",
        "Il prossimo anno passerà sia che tu stia facendo qualcosa per la tua vita sia che no.",
        "Non fermarti quando sei stanco, fermati quando hai finito.",
        "Sei solo un allenamento lontano da un buon umore.",
        "Fai ciò che è giusto, non ciò che è facile né ciò che è popolare.",
        "Niente di grande è mai arrivato così facilmente.",
        "Senza lotta non ci può essere progresso.",
        "Le persone di successo fanno domande migliori e di conseguenza ottengono risposte migliori.",
        "Non ho talenti speciali, sono solo appassionatamente curioso.",
        "La lezione migliore che ho imparato nella vita è venuta dalla peggior sensazione che ho provato nella vita.",
        "Le sfide sono ciò che rendono la vita interessante. Superarle è ciò che le dà significato.",
        "Impara ad essere felice con l'approccio infinito di provare, fallire, imparare.",
        "Se chiudi la porta a tutti gli errori, la verità resterà fuori.",
        "Dimentica l'errore, ricorda la lezione.",
        "Se puoi fare solo ciò che sai fare, non sarai mai più di quello che sei ora.",
        "Chi è saggio? Colui che impara da tutti.",
        "Solo io posso cambiare la mia vita, nessun altro può farlo per me.",
        "La perseveranza è fallire 19 volte e riuscire alla ventesima.",
        "Attribuisco il mio successo a questo: non ho mai dato né accettato scuse.",
        "Non sono un prodotto delle mie circostanze. Sono un prodotto delle mie decisioni.",
        "Le nostre azioni ci definiscono tanto quanto noi definiamo le nostre azioni.",
        "Solo gli estremamente ignoranti o gli estremamente intelligenti possono resistere al cambiamento.",
        "L'uomo che ha fiducia in sé stesso ottiene la fiducia degli altri.",
        "Ciò che cerchi ti sta cercando.",
        "Non preoccuparti del fallimento. Devi avere ragione solo una volta.",
        "La sicurezza è per lo più una superstizione. La vita è o un'avventura audace o niente.",
        "Diventiamo ciò a cui pensiamo la maggior parte del tempo, e questo è il segreto più strano.",
        "Il modo per iniziare è smettere di parlare e cominciare a fare.",
        "Fai di ogni giorno il tuo capolavoro.",
        "Non importa quanti errori fai o quanto lentamente progredisci, sei comunque molto più avanti di chiunque non ci stia provando.",
        "È il nostro atteggiamento all'inizio di un compito difficile che, più di ogni altra cosa, ne influenzerà il buon esito.",
        "L'unica vera sicurezza che un uomo avrà in questo mondo è una riserva di conoscenza, esperienza e capacità.",
        "Ciò che fai oggi può cambiare tutti i domani della tua vita.",
        "La tua vita non migliora per caso, migliora con il cambiamento.",
        "Un sogno non diventa realtà per magia, ci vogliono sudore, determinazione e duro lavoro.",
        "La conoscenza è sapere che un pomodoro è un frutto. La saggezza è non metterlo in una macedonia.",
        "Non importa quale sia la situazione, ricordati: \"Ho una scelta\".",
        "Governa la tua mente o lei governerà te.",
        "Alcuni riescono perché sono destinati a farlo, ma la maggior parte riesce perché è determinata a farlo.",
        "Le grandi opportunità non si vedono con gli occhi, si vedono con la mente.",
        "Chi non ha il coraggio di rischiare non realizzerà nulla nella vita.",
        "Sapere non basta, dobbiamo applicare. Volere non basta, dobbiamo fare.",
        "L'ambizione è il sentiero verso il successo, la persistenza è il veicolo con cui arrivi.",
        "La chiave della vita è accettare le sfide. Quando qualcuno smette di farlo, è morto.",
        "L'impegno è ciò che trasforma una promessa in realtà.",
        "La fiducia in sé stessi è la memoria del successo.",
        "Senza fiducia in noi stessi siamo come neonati nella culla.",
        "Osa sognare, ma ancora più importante, osa mettere in azione i tuoi sogni.",
        "L'onestà è il primo capitolo nel libro della saggezza.",
        "L'eccellenza è un processo continuo e non un incidente.",
        "La speranza è essere in grado di vedere che c'è luce nonostante tutta l'oscurità.",
        "Dobbiamo accettare la delusione finita, ma non perdere mai la speranza infinita.",
        "Il vero segno dell'intelligenza non è la conoscenza, ma l'immaginazione.",
        "Diventa dipendente dal miglioramento costante e continuo di te stesso.",
        "Il genio è un per cento ispirazione e novantanove per cento sudore.",
        "Non puoi aspettare l'ispirazione, devi inseguirla con un bastone.",
        "Abbi pazienza. Tutte le cose sono difficili prima di diventare facili.",
        "Chi dice che non si può fare non dovrebbe interrompere chi lo sta facendo.",
        "La perseveranza è il duro lavoro che fai dopo che ti sei stancato di fare il duro lavoro che avevi già fatto.",
        "Un uomo saggio può imparare di più da una domanda stupida di quanto uno stupido possa imparare da una risposta saggia.",
        "Con la costante autodisciplina e l'autocontrollo puoi sviluppare grandezza di carattere.",
        "L'autocontrollo emotivo è il risultato del duro lavoro, non una capacità innata.",
        "Imparare a imparare è l'abilità più importante della vita.",
        "Non lasciare che ciò che non puoi fare ti impedisca di fare ciò che puoi.",
        "Passi sempre davanti al fallimento sulla strada del successo.",
        "Nessuno è perfetto, ecco perché le matite hanno la gomma.",
        "Non lasciare mai che le probabilità ti impediscano di fare ciò che sai nel tuo cuore che eri destinato a fare.",
        "Se guardi bene, la maggior parte dei successi improvvisi ha richiesto molto tempo.",
        "Tutto è possibile. Tutto può essere.",
        "Niente è particolarmente difficile se lo suddividi in piccoli compiti.",
        "Il segreto del successo è fare le cose comuni in modo insolitamente buono.",
        "Agisci come se ciò che fai facesse la differenza, perché la fa.",
        "Ciò che ottieni raggiungendo i tuoi obiettivi non è così importante quanto ciò che diventi raggiungendoli.",
        "La vita è come andare in bicicletta; per mantenere l'equilibrio devi continuare a muoverti.",
        "Limita i tuoi \"sempre\" e i tuoi \"mai\".",
        "Non sei mai troppo vecchio per fissare un altro obiettivo o per sognare un nuovo sogno.",
        "Non trovi la vita felice, la crei tu.",
        "La brutta notizia è che il tempo vola. La buona notizia è che tu sei il pilota.",
        "Tieni sempre il viso rivolto verso il sole e le ombre cadranno dietro di te.",
        "La differenza tra l'impossibile e il possibile sta nella determinazione di un uomo.",
        "Le medaglie d'oro non sono fatte d'oro. Sono fatte di sudore, determinazione e una lega difficile da trovare chiamata coraggio.",
        "Non sottovalutare la determinazione di un uomo tranquillo.",
        "Non dirmi in cosa credi. Osserverò come ti comporti e trarrò le mie conclusioni.",
        "Odio semplicemente perdere e questo ti dà una determinazione extra per lavorare più duramente.",
        "La determinazione a vincere è la parte migliore della vittoria.",
        "Puoi avere tutto il talento del mondo, ma senza determinazione non andrai molto lontano.",
        "La vittoria è figlia della preparazione e della determinazione.",
        "Il giovane conosce le regole, ma il vecchio conosce le eccezioni.",
        "Il pessimista si lamenta del vento, l'ottimista si aspetta che cambi, il realista regola le vele.",
        "La conoscenza non ha valore se non la metti in pratica.",
        "Preferirei rimpiangere le cose che ho fatto piuttosto che rimpiangere quelle che non ho fatto.",
        "Ci vuole saggezza per capire la saggezza. La musica non è niente se il pubblico è sordo.",
        "Il pericolo maggiore per la maggior parte di noi non sta nel porsi obiettivi troppo alti e non raggiungerli, ma nel porsi obiettivi troppo bassi e raggiungerli.",
        "In ogni passeggiata nella natura si riceve molto più di ciò che si cerca.",
        "Non seguirò dove il sentiero può portare, ma andrò dove non c'è sentiero e lascerò una traccia.",
        "La possente quercia di oggi è solo la noce di ieri che ha tenuto duro.",
        "Essere completamente onesti con se stessi è un buon esercizio.",
        "Non possiamo diventare ciò che dobbiamo essere rimanendo ciò che siamo.",
        "Imposta la tua rotta sulle stelle, non sulle luci di ogni nave di passaggio.",
        "Se non sai dove stai andando, qualsiasi strada ti porterà lì.",
        "Avrai sempre due scelte: il tuo impegno contro la tua paura.",
        "Beati coloro che danno senza ricordare e prendono senza dimenticare.",
        "Ciò che accade non è importante quanto il modo in cui reagisci a ciò che accade.",
        "Inizia con ciò che è giusto piuttosto che con ciò che è accettabile.",
        "L'uomo superiore incolpa se stesso. L'uomo inferiore incolpa gli altri.",
        "La più piccola azione è meglio delle più grandi intenzioni.",
        "Il più grande ostacolo alla scoperta non è l'ignoranza, ma l'illusione della conoscenza.",
        "Attento alla falsa conoscenza, è più pericolosa dell'ignoranza.",
        "Il modo migliore per prevedere il futuro è inventarlo.",
        "Vincere senza rischio è trionfare senza gloria.",
        "Il nostro carattere è ciò che facciamo quando pensiamo che nessuno ci stia guardando.",
        "Tutto ciò che ci irrita negli altri può portarci a una comprensione di noi stessi.",
        "L'arte di essere saggi è l'arte di sapere cosa trascurare.",
        "Dimmelo e dimentico. Insegnamelo e ricordo. Coinvolgimi e imparo.",
        "Hai il cervello nella tua testa. Hai i piedi nelle tue scarpe. Puoi guidarti in qualsiasi direzione tu scelga.",
        "In tre parole posso riassumere tutto ciò che ho imparato sulla vita: va avanti.",
        "La vita è provare cose per vedere se funzionano.",
        "Il successo di solito arriva a chi è troppo impegnato per cercarlo.",
        "Non ho fallito, ho solo trovato 10.000 modi che non funzionano.",
        "Ho fallito fino al successo.",
        "Se non ti programmi da solo, la vita ti programmerà.",
        "Non ho tempo per compatirmi. Non ho tempo per lamentarmi. Andrò avanti.",
        "Se non sei disposto a rischiare il solito, dovrai accontentarti dell'ordinario.",
        "Il successo è stato definito come la capacità di passare da un fallimento all'altro senza perdere l'entusiasmo.",
        "Tutti i nostri sogni possono diventare realtà se abbiamo il coraggio di perseguirli.",
        "Le opportunità non capitano, le crei tu.",
        "Non ho mai sognato il successo, ci ho lavorato.",
        "Non lasciare che ciò che non puoi fare interferisca con ciò che puoi fare.",
        "Oggi è l'unico giorno, ieri è andato.",
        "Le cose funzionano meglio per coloro che sanno sfruttare al meglio come vanno le cose.",
        "Se stai attraversando l'inferno, continua a camminare.",
        "Vedi solo le glorie pubbliche. Mai i sacrifici privati per raggiungerle.",
        "Se non dai valore al tuo tempo, non lo faranno nemmeno gli altri.",
        "Nessuno può farti sentire inferiore senza il tuo consenso.",
        "Un uomo di successo è colui che riesce a costruire solide fondamenta con i mattoni che gli altri gli hanno lanciato.",
        "Quelle che ci sembrano prove amare sono spesso benedizioni travestite.",
        "Niente al mondo è più comune delle persone senza successo con talento.",
        "Cerca di non diventare una persona di successo, ma piuttosto una persona di valore.",
        "Se non riesci a spiegarlo semplicemente, non lo capisci abbastanza bene.",
        "Non fallisci mai finché non smetti di provare.",
        "La conoscenza è essere consapevoli di ciò che puoi fare. La saggezza è sapere quando non farlo.",
        "La vita non consiste nel trovare te stesso. La vita consiste nel creare te stesso.",
        "Il problema non è il problema, il problema è il tuo atteggiamento riguardo al problema.",
        "Nessun capolavoro è mai stato creato da un artista pigro.",
        "La strada verso il successo e la strada verso il fallimento sono quasi esattamente la stessa.",
        "Non è ciò che guardi che conta, è ciò che vedi.",
        "Il coraggio è resistenza alla paura, dominio della paura, non assenza di paura.",
        "Trovo che più lavoro duro, più fortuna sembro avere.",
        "Il calore di un pensiero gentile vale per me più del denaro.",
        "Ogni progresso avviene al di fuori della zona di comfort.",
        "Il pensiero dovrebbe diventare il tuo capitale principale, indipendentemente dagli alti e bassi che incontri nella vita.",
        "Il successo è la somma di piccoli sforzi ripetuti giorno dopo giorno.",
        "Il guerriero di successo è l'uomo comune con una concentrazione da laser.",
        "Il successo non consiste nel non commettere mai errori, ma nel non commettere mai lo stesso errore una seconda volta.",
        "Non lasciare che la paura di perdere sia più grande dell'emozione di vincere.",
        "Il primo passo è quando ti rifiuti di essere prigioniero del tuo ambiente.",
        "Non c'è traffico lungo il miglio extra.",
        "Ogni volta che ti trovi dalla parte della maggioranza, è il momento di fermarti e riflettere.",
        "Il successo è apprezzare te stesso, apprezzare ciò che fai e apprezzare come lo fai.",
        "Un obiettivo non è sempre destinato ad essere raggiunto, spesso serve semplicemente come qualcosa a cui mirare.",
        "È meglio fallire nell'originalità che riuscire nell'imitazione.",
        "La motivazione è ciò che ti fa iniziare, l'abitudine è ciò che ti fa continuare.",
        "Devi alzarti ogni mattina con determinazione se vuoi andare a letto con soddisfazione.",
        "Devi aspettarti grandi cose da te stesso prima di poterle fare.",
        "Le vere difficoltà possono essere superate, sono solo quelle immaginarie ad essere insuperabili.",
        "Le persone raramente hanno successo a meno che non si divertano in ciò che fanno.",
        "È durante i nostri momenti più bui che dobbiamo concentrarci per vedere la luce.",
        "Il fallimento è il condimento che dà sapore al successo.",
        "Le menti sono domate e sottomesse dalla sfortuna, ma le grandi menti si elevano al di sopra di essa.",
        "Potresti dover combattere una battaglia più di una volta per vincerla.",
        "Cosa faresti se non avessi paura?",
        "Le cose buone arrivano a chi aspetta, ma le cose migliori arrivano a chi va a prendersele.",
        "Dai sempre il massimo sforzo, anche quando le probabilità sono contro di te.",
        "Non aspettare che i tuoi sentimenti cambino per agire, agisci e i tuoi sentimenti cambieranno.",
        "L'azione potrebbe non portare sempre la felicità, ma non c'è felicità senza azione.",
        "La perfezione è noiosa, migliorare è dove sta tutto il divertimento.",
        "È difficile battere una persona che non si arrende mai.",
        "La differenza tra un ostacolo e un trampolino sta in quanto in alto alzi il piede.",
        "Non arrenderti mai, perché quello è esattamente il luogo e il momento in cui la marea cambierà.",
        "A volte non ottenere ciò che vuoi è un meraviglioso colpo di fortuna.",
        "Non posso cambiare la direzione del vento, ma posso regolare le mie vele per raggiungere sempre la mia destinazione.",
        "Vai avanti. Non fermarti, non indugiare nel tuo viaggio, ma sforzati di raggiungere la meta che hai davanti.",
        "Se vuoi davvero qualcosa, non aspettarla, insegnati ad essere impaziente.",
        "A volte vinci, a volte impari.",
        "Due tipi di persone in questo mondo: quelli che vogliono fare le cose e quelli che non vogliono commettere errori.",
        "Assicurati che il tuo peggior nemico non viva tra le tue due orecchie.",
        "Ricorda sempre che sei assolutamente unico, proprio come tutti gli altri.",
        "Se hai tutto sotto controllo, non stai andando abbastanza veloce.",
        "Un modo per mantenere lo slancio è avere obiettivi costantemente più grandi.",
        "Non devi vedere tutta la scala, basta fare il primo gradino.",
        "Quelle che ci sembrano prove amare sono spesso benedizioni travestite.",
        "Due opzioni riguardo all'impegno: o sei dentro o sei fuori, non esiste la vita a metà strada.",
        "Quando vuoi qualcosa, tutto l'universo cospira per aiutarti a ottenerlo.",
        "La felicità non è qualcosa di già pronto, viene dalle tue stesse azioni.",
        "Qualunque cosa tu sia, sii una buona versione.",
        "Il dolore è inevitabile, la sofferenza è opzionale.",
        "Il talento colpisce un bersaglio che nessun altro può colpire; il genio colpisce un bersaglio che nessun altro può vedere.",
        "La mente è il suo proprio luogo e in sé può fare del cielo un inferno, o dell'inferno un cielo.",
        "Odiavo allenarmi, ma mi dicevo 'non mollare' — soffri adesso e vivi il resto della tua vita da campione.",
        "Non sono le montagne davanti a te che ti logorano, è il sassolino nella scarpa.",
        "Ciò che pensiamo, diventiamo.",
        "Qualcuno oggi è seduto all'ombra perché qualcuno ha piantato un albero molto tempo fa.",
        "Un singolo raggio di sole è sufficiente per scacciare molte ombre.",
        "Per la mente che è ferma, l'intero universo si arrende.",
        "Con l'autodisciplina quasi tutto è possibile.",
        "La migliore via d'uscita è sempre attraverso.",
        "La tua grande opportunità potrebbe essere proprio dove sei ora.",
        "Niente vale più di questo giorno.",
        "L'unico viaggio è quello interiore.",
        "Le circostanze non determinano dove puoi andare, determinano semplicemente da dove parti.",
        "La convinzione crea il fatto reale.",
        "Ciò che rende bello il deserto è che da qualche parte nasconde un pozzo.",
        "Se le porte della percezione fossero purificate, ogni cosa apparirebbe all'uomo come è, infinita.",
        "Cambia i tuoi pensieri e cambierai il tuo mondo.",
        "L'uccello è alimentato dalla sua stessa vita e dalla sua motivazione.",
        "Dai luce e le persone troveranno la strada.",
        "La migliore preparazione per domani è fare del tuo meglio oggi.",
        "Le idee plasmano il corso della storia.",
        "Non su un solo filo sono infilati tutti i gioielli della vita.",
        "Ciò che raggiungiamo interiormente cambierà la realtà esterna.",
        "La tua risoluzione personale per il successo è più importante di qualsiasi altra cosa.",
        "Sai di essere sulla strada del successo se faresti il tuo lavoro senza essere pagato.",
        "Diventi ciò in cui credi.",
        "Se vuoi raggiungere l'eccellenza, puoi arrivarci oggi. Da questo momento, smetti di fare un lavoro meno che eccellente.",
        "Se non sei disposto a rischiare il solito, dovrai accontentarti dell'ordinario.",
        "Prima di ogni altra cosa, la preparazione è la chiave del successo.",
        "Ho imparato nel corso degli anni che quando la mente è decisa, la paura diminuisce.",
        "La vita è fatta di tante separazioni, saldate insieme.",
        "Vincere non è tutto, ma voler vincere lo è.",
        "Potresti essere deluso se fallisci, ma sei condannato se non ci provi.",
        "Gli errori sono un fatto della vita, è la risposta all'errore che conta.",
        "Se non ti piace la strada che stai percorrendo, inizia a pavimentarne una nuova.",
        "Le azioni parlano più forte delle parole, e non è mai più vero che con i tuoi figli.",
        "Un diamante è un pezzo di carbone che ha fatto bene sotto pressione.",
        "Le strade difficili spesso portano a destinazioni bellissime.",
        "A volte non conoscerai mai il valore di un momento finché non diventa un ricordo.",
        "Niente può offuscare la luce che brilla dall'interno.",
        "Per avere successo nella vita servono tre cose: un osso dei desideri, una spina dorsale e il senso dell'umorismo.",
        "Quelli che non credono nella magia non la troveranno mai.",
        "Ho deciso che non posso pagare una persona per riavvolgere il tempo, quindi tanto vale andare avanti.",
        "Tutto ha un costo, cosa sei disposto a pagare per averlo?",
        "Sono cresciuta di più non dalle vittorie, ma dalle sconfitte.",
        "Sono fortunata che qualunque paura io abbia dentro di me, il mio desiderio di vincere è sempre più forte.",
        "Devi credere in te stesso quando nessun altro lo fa.",
        "Non aver paura del fallimento, questa è la strada per il successo.",
        "Mi piacciono le critiche, ti rendono forte.",
        "So che voglio sempre fare del mio meglio.",
        "Tutti quelli che ho incontrato che hanno successo sono maniaci del lavoro.",
        "Non sono mai stato competitivo con nessuno, tranne che con me stesso.",
        "Credere in se stessi e sapere chi sei, questa è la base per ogni cosa grande.",
        "Ho paura di non provarci.",
        "Il modo per riscattare il tuo passato non è fuggire da esso, ma cercare di capirlo e usarlo come fondamento per crescere.",
        "Andare sul sicuro non ti porterà niente in questo mondo.",
        "Un grande trucco è un grande trucco, ma su un mediocre semplicemente non funziona. Tutto si riduce al talento.",
        "O ti evolvi, o scompari.",
        "Il seme deve crescere, indipendentemente dal fatto che sia piantato nella pietra.",
        "Non importa quanto sia dura, tieni il petto in fuori, la testa alta, e affronta la situazione.",
        "Fai sempre del tuo meglio, non lasciare che la pressione ti faccia andare in panico.",
        "Non sai mai come o quando avrai un impatto, o quanto importante può essere il tuo esempio per qualcun altro.",
        "Fai ciò che devi fare, per fare ciò che vuoi fare.",
        "Non aspirare a guadagnarti da vivere, aspira a fare la differenza.",
        "Devi essere ciò che sei in questo mondo, qualunque cosa accada.",
        "Se hai un nemico, allora impara e conosci il tuo nemico, non essere solo arrabbiato con lui o lei.",
        "Mi sforzo di essere come le più grandi persone che siano mai vissute.",
        "Dove eccello è un'etica del lavoro ridicola, disgustosa. Sai, mentre l'altro dorme? Io lavoro.",
        "La vita si vive al limite.",
        "Essere realisti è la strada più comune verso la mediocrità.",
        "Il primo passo è dire che puoi farcela.",
        "Il mondo non può dirti chi sei, devi scoprire chi sei ed esserlo, nel bene e nel male.",
        "Dovrai affrontare i tuoi fallimenti. Dovrai abbracciarli e capire come superarli.",
        "Mio padre mi disse: fissa il tuo prezzo all'inizio. Se mai diventa più costoso del prezzo che hai fissato, vattene.",
        "Crederesti in ciò in cui credi se fossi l'unico a crederci?",
        "Non mi importa cosa pensa la gente, perché la gente non pensa.",
        "Non sono mai stato veramente bravo in niente tranne che nella capacità di imparare.",
        "La sensazione migliore al mondo è vedere i benefici e le ricompense del duro lavoro.",
        "I miei obiettivi sono così alti che non ho tempo di rilassarmi in nessun modo.",
        "La vita è troppo breve per preoccuparsi di ciò che gli altri dicono di te.",
        "Dietro ogni persona di successo c'è un branco di detrattori.",
        "Puoi fare qualcosa della tua vita, dipende solo dalla tua determinazione.",
        "Hai dei nemici? Bene, significa che hai effettivamente difeso qualcosa.",
        "Ogni successo inizia con l'autodisciplina, inizia da te.",
        "Con la determinazione e un po' di talento puoi spostare le montagne.",
        "Il fallimento non è un'opzione, è solo un passo.",
        "Il successo non arriva da un giorno all'altro, è quando ogni giorno migliori un po' rispetto al giorno prima; tutto si accumula.",
        "Quando la vita ti mette in situazioni difficili non dire 'perché a me', di' semplicemente 'provaci'.",
        "Il successo in qualsiasi cosa si riduce sempre a questo: concentrazione e impegno. E controlliamo entrambi.",
        "Una volta ho sentito un uomo saggio dire che non esistono uomini perfetti, solo intenzioni perfette.",
        "Molto spesso smetti di camminare, perché dici 'sono stanco di scalare questa collina. Non arriverò mai in cima' e sei solo a due passi dalla vetta.",
        "Sfida te stesso, è l'unico percorso che porta alla crescita.",
        "Non puoi prenderti il merito del talento, puoi solo prenderti il merito di averlo usato.",
        "Il modo migliore per garantire una sconfitta è arrendersi.",
        "Potevo guardarlo accadere o farne parte.",
        "Quando qualcosa è abbastanza importante lo fai, anche se le probabilità non sono a tuo favore.",
        "Se ti alzi al mattino e pensi che il futuro sarà migliore, è una giornata luminosa, altrimenti non lo è.",
        "Va bene mettere tutte le uova in un cestino, purché tu controlli cosa succede a quel cestino.",
        "Se fai solo cose di cui conosci già la risposta in anticipo, la tua azienda scomparirà.",
        "Devi essere disposto a essere frainteso se vuoi innovare.",
        "Non c'è mai un brutto momento per innovare.",
        "Creare opportunità significa guardare dove gli altri non guardano.",
        "Il sudore investito è il capitale più prezioso che ci sia.",
        "Viviamo in una società dove, quasi sempre, il duro lavoro viene ricompensato.",
        "L'universo non ha alcun obbligo di avere senso per te.",
        "Non c'è educazione migliore di quella che è autodiretta.",
        "Nessuno è stupido se è curioso.",
        "Non conosco nessun momento nella storia umana in cui l'ignoranza fosse meglio della conoscenza.",
        "Allenati a non prendere nulla sul personale.",
        "Un uomo può fare di sé ciò che vuole se ci crede veramente, deve essere pronto al duro lavoro e a molte delusioni.",
        "Ciò che ognuno di noi deve comprendere è che la nostra intenzione traspare sempre.",
        "Non possiamo ignorare ciò che vogliamo veramente creare.",
        "Solo tu e tu solo puoi cambiare la tua situazione.",
        "Sii grato per i momenti difficili, perché ti hanno formato.",
        "Per unirti al primo 1% devi fare ciò che il 99% non fa.",
        "Ho creato il mio percorso, era dritto e stretto. La vedevo così: o eri sulla mia strada o fuori.",
        "Tutti abbiamo dubbi su noi stessi. Non li neghi, ma non ti arrendi nemmeno. Li abbracci.",
        "Molti leader falliscono perché non hanno il coraggio di toccare quel nervo scoperto.",
        "Il momento in cui ti arrendi è il momento in cui lasci vincere qualcun altro.",
        "Se hai paura di fallire probabilmente fallirai.",
        "Ho capito che l'intimidazione non esisteva davvero, se sei nel giusto stato mentale.",
        "Questo è il momento in cui accetto che i tempi più difficili saranno sempre dietro e davanti a me.",
        "Nessuno sa di poter diventare campione — devi lavorare per arrivarci.",
        "La mia convinzione è più forte del tuo dubbio.",
        "Il successo significa essere soddisfatti di ciò che fai ogni giorno. Significa essere orgogliosi della persona migliore che stai diventando.",
        "Se vuoi avere successo devi essere disposto a usare ogni contatto che hai.",
        "Il talento non basta mai. Con poche eccezioni, i migliori giocatori sono i lavoratori più instancabili.",
        "Non arrenderti, sii amico di persone che ti aiutano a lavorare duro.",
        "Celebra la vita che hai avuto, non la vita che avresti potuto avere.",
        "Sono cresciuto povero, ma non avevo sogni poveri.",
        "Sei l'unico che può fare la differenza. Qualunque sia il tuo sogno, inseguilo.",
        "La vita non si ferma perché ti succede qualcosa.",
        "Nella vita, vincere e perdere accadranno entrambi, ciò che non è mai accettabile è arrendersi.",
        "Sapete quante volte sono stato rifiutato nella mia vita? Quante volte mi è stato detto che non potevo realizzare qualcosa?",
        "Molte volte scopro che le persone benedette dal maggior talento non sviluppano mai quell'atteggiamento. E quelle che non sono benedette in quel modo sono le più competitive e hanno il cuore più grande.",
        "Pensavo che non avrei mai avuto la possibilità di giocare, finché una volta l'ho avuta, perché ero preparato e l'opportunità si è presentata.",
        "Amo semplicemente la competizione e amo cercare di migliorare.",
        "Troppo spesso nella vita succede qualcosa e incolpiamo gli altri per il fatto di non essere felici, soddisfatti o realizzati.",
        "La tua vita sarà ciò che ne farai.",
        "Non mi arrabbierò perché qualcuno ha detto qualcosa di brutto su di me.",
        "Non puoi stare in panchina nella vita.",
        "Il mio messaggio è semplice: prendi il controllo della tua vita.",
        "Quando sei uno dei leader della squadra non ci sono giorni liberi.",
        "Non contare sugli altri. Avrai grande supporto da molte persone, certo. Ma nessuno ti regalerà nulla.",
        "Le cose non si correggono da sole; devi andare là fuori e lavorare duro per correggerle.",
        "Se non giochi per vincere, non giocare affatto.",
        "Se non credi in te stesso, perché qualcun altro dovrebbe credere in te.",
        "A volte nella vita le sfide più grandi finiscono per essere le cose migliori che ti capitano.",
        "Amo semplicemente lavorare duro.",
        "I veri competitori però sono quelli che giocano sempre per vincere.",
        "Non inseguire i soldi, insegui il sogno.",
        "Se vuoi volare devi rinunciare alle cose che ti appesantiscono.",
        "Non voglio che tu sogni, voglio che tu faccia.",
        "Chiunque voglia essere qualcuno lavorerà il più duro possibile per realizzare quel sogno.",
        "Non ho mai cercato di nascondere il fatto che la mia intenzione è diventare il migliore.",
        "Se non credi di essere il migliore, non raggiungerai mai tutto ciò di cui sei capace.",
        "Oggi ci sono opportunità che nessuno sa se si ripresenteranno in futuro.",
        "Il talento senza lavorare duro non è niente.",
        "Non mi dispiace che la gente mi odi, perché mi spinge avanti.",
        "Il talento non è tutto. Puoi averlo dalla culla, ma è necessario imparare il mestiere per essere il migliore.",
        "Sento un bisogno infinito di imparare, migliorare, evolvermi — per sentirmi soddisfatto di me stesso.",
        "Il tuo amore mi rende forte. Il tuo odio mi rende inarrestabile.",
        "Puoi superare qualsiasi cosa se e solo se ami qualcosa abbastanza.",
        "Ho successo perché ho fatto sacrifici per il successo.",
        "La mia ambizione è sempre migliorare sempre di più.",
        "Ho iniziato presto e ho finito tardi. Giorno dopo giorno, anno dopo anno, mi ci sono voluti 17 anni e 114 giorni per diventare un successo improvviso.",
        "La persona che mi impediva di essere felice ero io.",
        "Il semplice atto di prestare attenzione può portarti molto lontano.",
        "Non confondere la verità con l'opinione delle masse. Queste non sono quasi mai nemmeno lontanamente simili.",
        "C'è una differenza tra conoscere il sentiero e percorrere il sentiero.",
        "Non ho tempo per restare sveglia tutta la notte a preoccuparmi di ciò che qualcuno che non mi ama ha da dire su di me.",
        "Non puoi essere titubante riguardo a chi sei.",
        "C'è sempre qualcosa su cui lavorare, non sei mai arrivato.",
        "Voglio essere ciò che ho sempre voluto essere: dominante.",
        "Cerco solo di essere il migliore possibile e spero che sia il migliore di sempre.",
        "Non voglio diventare bravo come ero una volta, voglio diventare migliore.",
        "La mia mente è il mio più grande asset. Mi aspetto di vincere ogni torneo a cui partecipo.",
        "Quelli che controllano davvero le proprie emozioni vinceranno.",
        "Non importa quanto diventi bravo, puoi sempre migliorare, e questa è la parte entusiasmante.",
        "Per poter aiutare gli altri devi prima imparare ad aiutare te stesso.",
        "Niente di ciò che vale la pena avere arriva se non come risultato del duro lavoro.",
        "Non permetterò a nessuno di sminuire la mia anima facendomi odiare.",
        "Non puoi tenere un uomo a terra senza restare a terra con lui.",
        "È il carattere, non le circostanze, a formare l'uomo.",
        "Ci sono due modi di esercitare la propria forza: uno è spingere in basso, l'altro è tirare su.",
        "Ho fallito molte più volte di quante ho avuto successo.",
        "Faccio oggi ciò che gli altri non faranno, così potrò raggiungere domani ciò che gli altri non possono.",
        "Anche se perdi, non perdere la lezione.",
        "La cosa più facile da vendere è la verità.",
        "Non aspettare il momento perfetto, aspetterai per sempre. Approfitta sempre del tempo che ti è dato e rendilo perfetto.",
        "Puoi fare solo così tante cose alla grande, e dovresti mettere da parte tutto il resto.",
        "La vita è fragile. Non ci è garantito un domani, quindi dai tutto quello che hai.",
        "Non ho paura di fare la figura dello sciocco.",
        "Il rispetto mi motiva, non il successo.",
        "Quando hai superato la collina, è lì che prendi velocità.",
        "L'eccellenza non è un atto, è un'abitudine.",
        "Non puoi prendere un dieci se hai paura di prendere un'insufficienza.",
        "Fai i tuoi errori per imparare ad arrivare alle cose buone.",
        "Un eroe è qualcuno che volontariamente cammina verso l'ignoto.",
        "Ci sono milioni di sopravvissuti là fuori. Fai in modo che siano un milione e uno.",
        "Non arrenderti mai, perché non sai mai cosa porterà la marea il giorno dopo.",
        "Se non fosse difficile lo farebbero tutti. È la difficoltà che lo rende grande.",
        "Se fai solo scelte sicure non cresci.",
        "Mi piace fare qualcosa che mi spaventa.",
        "Il processo è la parte più bella.",
        "È facile ingannare l'occhio, ma è difficile ingannare il cuore.",
        "Non andare mai troppo in alto, non andare mai troppo in basso. Prendila giorno per giorno e continua a imparare.",
        "L'impegno non sarà mai messo in discussione.",
        "Non sperare che qualcuno ti dia un'opportunità: creane una tu stesso.",
        "Quando la gente mi diceva che non ce l'avrei mai fatta, ho ascoltato l'unica persona che ha detto che potevo: me stesso.",
        "C'è un motivo per cui si dice inseguire i propri sogni e non camminare dietro ad essi.",
        "Per avere ciò che vuoi veramente, devi prima essere chi sei veramente.",
        "Non lasciare che il passato ti perseguiti. Perché ciò che fai nel presente potrebbe perseguitare il tuo futuro, sii saggio. Ciò che fai ora o in futuro non potrà mai mascherare il tuo passato, ma questo non significa che devi lasciare che il passato ti controlli.",
        "Quel \"e se\" è una ferita che non guarisce mai.",
        "Se fosse facile non varrebbe la pena.",
        "Non meriti niente, te lo guadagni.",
        "La perfezione non è interessante, uscirne vincitori nonostante le prove dell'avversità: ecco cosa mi impressiona.",
        "Non partecipare alle Olimpiadi del \"compatiscimi\"; noi non gareggiamo in quella disciplina.",
        "Quando vuoi qualcosa, accetti il terreno che viene con essa, qualunque sia quel terreno.",
        "La vera visione è quando la tua mente è più potente di ciò che hai davanti agli occhi.",
        "Certi eventi ti faranno progredire, certi eventi faranno il contrario — così sembra. Quegli opposti sono opportunità di apprendimento che si riveleranno utili in futuro.",
        "Paga il prezzo per essere il capo o paga il prezzo del rimpianto.",
        "L'opinione degli altri su di te non deve diventare la tua realtà.",
        "Non ottieni ciò che desideri, ottieni ciò per cui lavori.",
        "L'autodisciplina inizia con la padronanza dei tuoi pensieri. Se non controlli ciò che pensi, non puoi controllare ciò che fai. Semplicemente, l'autodisciplina ti permette di pensare prima e agire dopo.",
        "Cos'è la sconfitta? Nient'altro che educazione; nient'altro che il primo passo verso qualcosa di migliore.",
        "Non è ciò che ti succede, ma come reagisci che conta.",
        "Controlla la tua rabbia. Se provi rabbia verso gli altri, loro ti controllano.",
        "La tua sfida più grande è presentarti quando la tua mente sta inventando le migliori scuse.",
        "Puoi sperimentare il dolore della disciplina o il dolore del rimpianto. La scelta è tua.",
        "Qualsiasi cosa che ti rende debole fisicamente, intellettualmente e spiritualmente; rifiutala come veleno.",
        "Suda di più in tempo di pace, sanguina di meno in tempo di guerra.",
        "Con il coraggio di iniziare e la disciplina di resistere, la vittoria diventa una questione di tempo.",
        "Un buon leader è una persona che si prende un po' più della sua parte di colpa e un po' meno della sua parte di merito.",
        "Sii forte, ma non scortese. Sii gentile, ma non debole. Sii audace, ma non prepotente. Sii umile, ma non timido. Sii orgoglioso, ma non arrogante.",
        "La pazienza è amara, ma il suo frutto è dolce.",
        "La pazienza non è passiva, al contrario; è attiva. È forza concentrata.",
        "Non c'è niente di impossibile per chi vuole provare.",
        "L'intelligenza non è la capacità di immagazzinare informazioni, ma di sapere dove trovarle.",
        "Prima è un'intenzione. Poi un comportamento. Poi un'abitudine. Poi una pratica. Poi una seconda natura. Poi è semplicemente chi sei.",
        "Qualunque cosa tu voglia fare, falla adesso. I domani sono contati.",
        "Le persone che dicono che non si può fare non dovrebbero interrompere quelli che lo stanno facendo.",
        "C'è solo un angolo dell'universo che puoi essere certo di migliorare, ed è te stesso.",
        "Lo sciocco crede di essere saggio, ma il saggio sa di essere sciocco.",
        "Il dolore può cambiarti, ma questo non significa che debba essere un cambiamento negativo. Prendi quel dolore e trasformalo in saggezza.",
        "Il tempo è davvero l'unico capitale che ogni essere umano ha, e l'unica cosa che non può permettersi di perdere.",
        "Segui il tuo percorso, non importa cosa dica la gente.",
        "Fai qualcosa. Se funziona, fanne di più. Se non funziona, fai qualcos'altro.",
        "L'apprendimento è l'unica cosa che la mente non esaurisce mai, non teme mai e non rimpiange mai.",
        "Un vincitore è un sognatore che non si arrende mai.",
        "Se non lotti per ciò che vuoi, non piangere per ciò che hai perso.",
        "Una volta che hai accettato i tuoi difetti, nessuno può usarli contro di te.",
        "Una volta che avremo imparato abbastanza sull'universo ammetteremo a noi stessi che non sapremo mai tutto.",
        "Preoccuparsi è come pagare un debito che non devi.",
        "Non puoi insegnare niente a nessuno, puoi solo fargli capire che le risposte sono già dentro di loro.",
        "Il potere dei pensieri può causarti sia malattia che guarigione.",
        "Se vuoi vedere un miracolo, sii un miracolo.",
        "Ci sono tre classi di persone: quelle che vedono, quelle che vedono quando gli viene mostrato, quelle che non vedono.",
        "Le tue più grandi paure sono create dalla tua immaginazione.",
        "Il più grande inganno che gli uomini subiscono proviene dalle loro stesse opinioni.",
        "Quando hai esaurito tutte le possibilità, ricorda questo: non le hai esaurite.",
        "Ama la mano che il destino ti distribuisce e giocala come se fosse la tua.",
        "Se due persone sono d'accordo su tutto, una di loro è superflua.",
        "La più grande competizione è quella che hai con te stesso.",
        "Quando siamo stanchi, siamo attaccati da idee che abbiamo conquistato tempo fa.",
        "Non sono ciò che mi è successo. Sono ciò che scelgo di diventare.",
        "Il fattore più importante nella sopravvivenza non è né l'intelligenza né la forza, ma l'adattabilità.",
        "La fede e la paura richiedono entrambe di credere in qualcosa che non puoi vedere. Tu scegli.",
        "Lamentandoti, dici alle persone quanto sei debole.",
        "Per ottenere ciò che ami, devi prima essere paziente con ciò che detesti.",
        "Quando tutto sembra andare contro di te, ricorda che l'aereo decolla controvento, non a favore.",
        "Riderai delle tue paure quando scoprirai chi sei veramente.",
        "La pace non si trova in una tempesta più calma, si trova in una barca migliore.",
        "Puoi ignorare la realtà, ma non puoi ignorare le conseguenze dell'aver ignorato la realtà.",
        "Nessun uomo è più infelice di chi non affronta mai le avversità. Perché non gli è permesso di mettersi alla prova.",
        "Un buon piano eseguito con violenza adesso è meglio di un piano perfetto eseguito la prossima settimana.",
        "Studiare e non pensare è inutile. Pensare e non studiare è pericoloso.",
        "La paura è una reazione. Il coraggio è una decisione.",
        "L'indipendenza è per pochissimi; è un privilegio dei forti.",
        "Ci vuole metà della vita prima di scoprire che la vita è un progetto fai da te.",
        "Recita la tua parte con onore.",
        "La preoccupazione è un uso improprio dell'immaginazione.",
        "Il ponte tra conoscenza e abilità è la pratica. Il ponte tra abilità e maestria è il tempo.",
        "Più imparo, più mi rendo conto di quanto devo ancora imparare.",
        "Se non perdi, non puoi goderti le vittorie. Quindi devo accettare entrambe le cose.",
        "Dalla vittoria impariamo poco, dalla sconfitta molto.",
        "Chi parla con deferenza ma aumenta i preparativi avanzerà. Chi parla con arroganza e avanza in fretta si ritirerà.",
        "La nostra vita è ciò che i nostri pensieri ne fanno.",
        "Non c'è davvero niente di difficile, a meno che tu non decida che è difficile. Altrimenti è solo la prossima cosa che stai capendo.",
        "Non importa la situazione, non lasciare mai che le tue emozioni sopraffacciano la tua intelligenza.",
        "Decidi che tipo di persona vuoi essere e mantienilo, sia da solo che in compagnia.",
        "Se qualcosa non va, aggiustalo se puoi. Ma allenati a non preoccuparti. Preoccuparsi non aggiusta mai niente.",
        "La vita non è questione di avere buone carte, ma di giocare bene una mano scadente.",
        "È una strada accidentata quella che porta alle vette della grandezza.",
        "Il giorno in cui un uomo diventa superiore al piacere, sarà anche superiore al dolore.",
        "Impara continuamente, c'è sempre \"una cosa in più\" da imparare.",
        "Possiamo lamentarci perché i cespugli di rose hanno spine, o gioire perché i cespugli di spine hanno rose.",
        "Sii paziente e forte; un giorno questo dolore ti sarà utile.",
        "Il fallimento è il successo in corso.",
        "Chiunque smetta di imparare è vecchio, che abbia venti o ottant'anni.",
        "Se sei governato dalla mente sei un re; se dal corpo, uno schiavo.",
        "L'orgoglio non è l'opposto della vergogna, ma la sua fonte. La vera umiltà è l'unico antidoto alla vergogna.",
        "Quando inizi a migliorare te stesso, la solitudine è il prezzo che paghi.",
        "Non sei giudicato dall'altezza a cui sei salito, ma dalla profondità da cui ti sei arrampicato.",
        "Un uomo è grande non perché non ha fallito; un uomo è grande perché il fallimento non lo ha fermato.",
        "Un uomo senza una visione è un uomo senza futuro. Un uomo senza futuro tornerà sempre al suo passato.",
        "Piuttosto fallire con onore che avere successo con la frode.",
        "Tutte le battaglie vengono prima vinte o perse nella mente.",
        "Le emozioni dell'uomo sono scosse più rapidamente dell'intelligenza dell'uomo.",
        "Chi compra ciò di cui non ha bisogno ruba a se stesso.",
        "Chi ha pazienza può avere ciò che vuole.",
        "Il sentiero del Guerriero dura tutta la vita, e la maestria è spesso semplicemente restare sul sentiero.",
        "Gli aquiloni salgono più in alto contro il vento, non con esso.",
        "Se la gente sapesse quanto duramente ho dovuto lavorare per raggiungere la mia maestria, non sembrerebbe così meravigliosa.",
        "Non andare mai a dormire senza una richiesta al tuo subconscio.",
        "Accogli gli eventi in qualsiasi modo accadano: questa è la via verso la pace.",
        "Pratica anche ciò che sembra impossibile.",
        "L'uomo che insegue due conigli non ne prende nessuno.",
        "Ce la farai, ma ti sembrerà sempre di non farcela.",
        "Pianifica ciò che è difficile mentre è facile, fai ciò che è grande mentre è piccolo.",
        "La persistenza non basta. Bisogna decidere se persistere come sofferente o come guerriero.",
        "Il livello di acutezza e disciplina necessario per raggiungere le vette che sogni è davvero semplice, solo che non è facile.",
        "Il nemico più grande non si trova all'esterno. La distruzione spesso viene da dentro.",
        "Tutti sapevano che era impossibile, finché uno stolto che non lo sapeva arrivò e lo fece.",
        "Non puoi rendere forte un uomo debole rendendo debole un uomo forte.",
        "Hai potere sulla tua mente, non sugli eventi esterni. Renditi conto di questo e troverai la forza.",
        "Un diamante è solo un pezzo di carbone che è rimasto al suo posto.",
        "Il rischio più grande è non rischiare.",
        "Se definisci correttamente il problema, hai quasi la soluzione.",
        "Il passato è nella tua testa, il futuro è nelle tue mani.",
        "La vita è piuttosto semplice. Fai delle cose. La maggior parte fallisce. Qualcosa funziona. Fai di più di ciò che funziona.",
        "Che il tuo senso del dovere prevalga su un'atmosfera di paura e sulla tendenza a rimandare le aspirazioni.",
        "Tutto ciò che hai sempre voluto è dall'altra parte della paura.",
        "La disciplina è scegliere tra ciò che vuoi adesso e ciò che vuoi di più.",
        "Il conformismo è l'ultimo rifugio dei privi di immaginazione.",
        "Un diamante è un pezzo di carbone che è rimasto al suo lavoro.",
        "Non c'è danno maggiore per l'uomo del tempo sprecato.",
        "Non rovinare ciò che hai desiderando ciò che non hai; ricorda che ciò che hai adesso era una volta tra le cose che speravi soltanto.",
        "Un uomo che è padrone della pazienza è padrone di tutto il resto.",
        "Non mettere mai la passione davanti ai principi, anche se vinci, perderai.",
        "Alcune persone vogliono che accada, altre desiderano che accada, altre lo fanno accadere.",
        "Non ci eleviamo al livello delle nostre aspettative, cadiamo al livello del nostro allenamento.",
        "È più facile trovare uomini disposti a morire volontariamente che trovare quelli disposti a sopportare il dolore con pazienza.",
        "Non puoi aspettarti di salire sul podio se non partecipi alla gara.",
        "Chi cade e si rialza è più forte di chi non ha mai provato.",
        "Brutta notizia: non ti 'adatterai' a tutti. Buona notizia: i 'Grandi' non lo fanno mai.",
        "Non sono mai stato talentuoso, sono solo bravo a non arrendermi mai.",
        "La felicità non è l'assenza di problemi, è la capacità di affrontarli.",
        "Se fai ciò che è facile la tua vita sarà difficile.",
        "Non puoi tornare indietro e cambiare l'inizio, ma puoi partire da dove sei e cambiare il finale.",
        "Si impara più dall'esempio che dalle lezioni.",
        "Chi non commette mai errori lavora per quelli di noi che ne commettono.",
        "Un'idea nuova non deve essere giudicata dai suoi risultati immediati.",
        "Non sei mai pronto per ciò che devi fare. Lo fai e basta. Questo ti rende pronto.",
        "Rischia: se vinci sarai felice; se perdi sarai saggio.",
        "Un popolo che valuta i propri privilegi al di sopra dei propri principi perderà presto entrambi.",
        "La strada più veloce verso il significato e il successo: scegli una cosa e dai tutto.",
        "Non aver paura di ricominciare da capo. Questa volta non parti da zero. Parti dall'esperienza.",
        "Non c'è niente di nobile nell'essere superiori ai propri simili; la vera nobiltà è essere superiori al proprio sé precedente.",
        "Guadagnerai il rispetto di tutti se inizierai guadagnando il rispetto di te stesso.",
        "Crea una visione di chi vuoi essere e poi vivi in quell'immagine come se fosse già vera.",
        "Il prezzo dell'eccellenza è la disciplina. Il costo della mediocrità è la delusione.",
        "Le difficoltà rafforzano la mente, come il lavoro rafforza il corpo.",
        "Non puoi sperare di fare progressi nelle aree in cui non hai intrapreso alcuna azione.",
        "Nessuna quantità di ansia fa alcuna differenza su ciò che sta per accadere.",
        "Mostrami un uomo di capacità media ma con un desiderio straordinario e ti mostrerò un vincitore ogni volta.",
        "Il modo più rapido per avere successo è iniziare adesso e capirlo strada facendo.",
        "Le persone non decidono il proprio futuro, decidono le proprie abitudini e le abitudini decidono il loro futuro.",
        "Insegna presto ai tuoi figli ciò che tu hai imparato tardi.",
        "Se dedichi 100 ore all'anno a qualsiasi disciplina (che sono solo 18 minuti al giorno) sarai migliore del 95% del mondo in quella disciplina.",
        "Il compito non è tanto vedere ciò che nessuno ha ancora visto, ma pensare ciò che nessuno ha ancora pensato riguardo a ciò che tutti vedono.",
        "Se ti irriti per ogni sfregamento, come verrà lucidato il tuo specchio?",
        "La paura è profonda solo quanto la mente lo permette.",
        "La difficoltà è ciò che risveglia il genio.",
        "Ciò che deve dare luce deve sopportare di bruciare.",
        "Ho imparato che il successo non si misura tanto dalla posizione raggiunta nella vita quanto dagli ostacoli superati nel tentativo di riuscire.",
        "Il comfort è la peggior dipendenza.",
        "Diventi ciò a cui dai la tua attenzione.",
        "Le circostanze non fanno l'uomo, lo rivelano solo a se stesso.",
        "Non sprecare più tempo a discutere su cosa dovrebbe essere un uomo buono. Sii uno.",
        "Chi vuole muovere il mondo muova prima se stesso.",
        "Tra lo stimolo e la risposta c'è uno spazio. In quello spazio c'è il nostro potere di scegliere la nostra risposta. Nella nostra risposta risiedono la nostra crescita e la nostra libertà.",
        "Non c'è niente fuori di te che possa mai permetterti di diventare migliore, più forte, più ricco, più veloce o più intelligente. Tutto è dentro. Tutto esiste. Non cercare nulla fuori di te.",
        "Sii tollerante con gli altri e severo con te stesso.",
        "Due cose ti definiscono: la tua pazienza quando non hai niente e il tuo atteggiamento quando hai tutto.",
        "Non ti svegli e diventi farfalla da un giorno all'altro.",
        "La tenacia è la capacità di resistere quando mollare sembra la scelta più attraente.",
        "Ci sono rischi e costi nell'agire. Ma sono molto inferiori ai rischi a lungo termine di una comoda inattività.",
        "Per realizzare grandi cose servono due cose: un piano e non abbastanza tempo.",
        "Il dubbio può essere rimosso solo dall'azione.",
        "Se le tue azioni ispirano gli altri a sognare di più, imparare di più, fare di più e diventare di più, sei un leader.",
        "Non si tratta di avere un record immacolato. Si tratta di imparare dalle macchie sul tuo record.",
        "Sii abbastanza coraggioso da essere scarso in qualcosa di nuovo.",
        "Vai a letto più intelligente di quando ti sei svegliato.",
        "Il successo lento costruisce il carattere, il successo rapido costruisce l'ego.",
        "Solo perché qualcuno inciampa e perde la sua strada non significa che sia perso per sempre.",
        "Ma non possiamo semplicemente sederci e fissare le nostre ferite per sempre.",
        "E ora che non devi essere perfetto, puoi essere buono.",
        "Il successo viene dall'esecuzione spietata dei fondamentali.",
        "Ci vuole molto lavoro duro per rendere qualcosa semplice.",
        "Tutti pensano a cambiare il mondo, ma nessuno pensa a cambiare se stesso.",
        "I chiusi di mente hanno bisogno che l'arte gli venga servita col cucchiaio.",
        "Fai qualcosa invece di ammazzare il tempo. Perché il tempo sta ammazzando te.",
        "Che ogni decisione sia in linea con la tua visione.",
        "Se vuoi fare qualcosa di più grande della media, non puoi cedere alla paura di essere un emarginato.",
        "Ciò che conta di più è quanto bene cammini attraverso il fuoco.",
        "Sei a una decisione di distanza da una vita completamente diversa.",
        "Se vivi per il domani, sarai sempre un giorno indietro.",
        "Fai il massimo di te stesso, perché è tutto ciò che hai.",
        "Gli occhi sono inutili quando la mente è cieca.",
        "Alla lunga gli uomini colpiscono solo ciò a cui mirano. Perciò, anche se dovessero fallire subito, farebbero meglio a mirare in alto.",
        "Chi ha un perché per vivere può sopportare quasi ogni come.",
        "Gli uomini possono essere divisi in due gruppi: uno che va avanti e realizza qualcosa, e uno che viene dopo e critica.",
        "Un brutto atteggiamento è come una gomma a terra. Non puoi andare da nessuna parte finché non la cambi.",
        "Nessun uccello vola troppo in alto se vola con le proprie ali.",
        "Risolvi il problema o lascia il problema. Non vivere con il problema.",
        "Agisci secondo i tuoi principi, non secondo il tuo umore.",
        "Coloro che non si impegnano in nulla sono distratti da tutto.",
        "Quando ci sforziamo di diventare migliori di quello che siamo, tutto intorno a noi diventa migliore.",
        "Non c'è passione da trovare nell'accontentarsi di una vita inferiore a quella di cui si è capaci.",
        "Un uomo creativo è motivato dal desiderio di realizzare, non dal desiderio di battere gli altri.",
        "La vita è una lunga preparazione per qualcosa che non accade mai.",
        "Non ascolto più ciò che la gente dice, guardo solo ciò che fa. Il comportamento non mente mai.",
        "Gli individui intelligenti imparano da ogni cosa e da tutti; le persone medie dalle loro esperienze. Gli stupidi hanno già tutte le risposte.",
        "La prima regola è mantenere uno spirito tranquillo. La seconda è guardare le cose in faccia e conoscerle per quello che sono.",
        "È sempre una lotta sollevare pesi più pesanti.",
        "Un uomo che teme la sofferenza sta già soffrendo per ciò che teme.",
        "Se un uomo non sa verso quale porto naviga, nessun vento è favorevole.",
        "Faccio sempre ciò che non so fare, per imparare a farlo.",
        "Costruisci sul fallimento. Usalo come un trampolino. Chiudi la porta al passato. Non cercare di dimenticare gli errori, ma non ci rimuginare sopra. Non lasciargli nessuna della tua energia, nessuno del tuo tempo, nessuno del tuo spazio.",
        "Il contenuto del tuo carattere è una tua scelta. Giorno dopo giorno, ciò che scegli, ciò che pensi e ciò che fai è ciò che diventi.",
        "I codardi non hanno mai iniziato e i deboli sono morti lungo la strada.",
        "Quando ti alzi al mattino, pensa a che privilegio prezioso sia essere vivo: respirare, pensare, godere, amare.",
        "Il segreto del successo è la focalizzazione dello scopo.",
        "L'unica cosa più pericolosa dell'ignoranza è l'arroganza.",
        "Noi siamo ciò che facciamo ripetutamente. L'eccellenza, dunque, non è un atto ma un'abitudine.",
        "Mentre aspettiamo la vita, la vita passa.",
        "Il successo non è altro che poche semplici discipline praticate ogni giorno.",
        "Più sa, più sarà consapevole della propria ignoranza.",
        "L'impedimento all'azione fa avanzare l'azione. Ciò che si frappone diventa la via.",
        "La nostra più grande debolezza sta nell'arrendersi. Il modo più sicuro per riuscire è provare sempre una volta in più.",
        "Una gemma non può essere lucidata senza attrito, né un uomo perfezionato senza prove.",
        "Il tuo valore consiste in ciò che sei e non in ciò che hai.",
        "Chi fa del male è più sfortunato di chi subisce il male.",
        "Una delle prove più vere di integrità è il suo netto rifiuto di essere compromessa.",
        "Dio non dà nulla a coloro che tengono le braccia incrociate.",
        "Sapere come pensare ti dà un potere che va ben oltre quello di chi sa solo cosa pensare.",
        "Se hai in programma di essere qualcosa di meno di ciò che sei capace di essere, probabilmente sarai infelice tutti i giorni della tua vita.",
        "Non c'è niente di meglio delle avversità. Ogni sconfitta, ogni dolore, ogni perdita contiene il proprio seme, la propria lezione su come migliorare la tua prestazione la prossima volta.",
        "Impara ad amare l'odio. Accoglilo. Goditelo. Te lo sei guadagnato. Ognuno ha diritto alla propria opinione e ognuno dovrebbe averne una su di te. I detrattori sono un buon problema da avere. Nessuno odia quelli bravi. Odiano quelli grandi.",
        "Accetta la tua incapacità di controllare tutte le cose. Accetta la responsabilità di tutto ciò che è sotto il tuo controllo. Accetta che esistano ostacoli interni ed esterni. Accetta di essere attrezzato per affrontarli tutti.",
        "L'esperienza è il tipo di insegnante più duro. Ti dà prima il test e la lezione dopo.",
        "Maturiamo con i danni, non con gli anni.",
        "Se sei depresso stai vivendo nel passato. Se sei ansioso stai vivendo nel futuro. Se sei in pace stai vivendo nel presente.",
        "Se pensi che non possiamo cambiare il mondo, significa solo che non sei uno di quelli che lo faranno.",
        "Forse non si tratta di un lieto fine. Forse si tratta della storia.",
        "Alcune persone portano gioia ovunque vadano, e alcune persone portano gioia ogni volta che se ne vanno.",
        "Osserva costantemente che tutte le cose avvengono per cambiamento, e abituati a considerare che la natura dell'universo non ama nulla quanto il cambiamento.",
        "Essere troppo buoni tende ad essere poco interessante.",
        "Troppo spesso godiamo del comfort dell'opinione senza il disagio del pensiero.",
        "Studiare senza pensare è vano; pensare senza studiare è pericoloso.",
        "Un uomo con una convinzione sopraffà cento che hanno solo opinioni.",
        "Gli sciocchi si moltiplicano quando i saggi tacciono.",
        "Sii pronto a rivedere qualsiasi sistema, scartare qualsiasi metodo, abbandonare qualsiasi teoria se il successo del lavoro lo richiede.",
        "Aiutare gli altri a svilupparsi e avere successo nella vita è di per sé una ricompensa e ha valore solo quando non ci si aspetta nulla in cambio.",
        "Ora non è il momento di pensare a ciò che non hai. Pensa a ciò che puoi fare con quello che c'è.",
        "Direi che sono un lavoro in corso, ma questo suggerirebbe che un giorno non sarò più un lavoro in corso.",
        "Non arrenderti. Di solito è l'ultima chiave del mazzo che apre la porta.",
        "La vita è una commedia per chi pensa, una tragedia per chi sente.",
        "Il tatto è la capacità di dire a qualcuno di andare all'inferno in modo che non veda l'ora di partire.",
        "Lascia il torto fatto da un altro là dove il torto è nato.",
        "Non turbarti immaginando tutta la tua vita in una volta. Non pensare sempre a quali sofferenze e quante potrebbero colpirti.",
        "Ogni volta che penso di sapere tutto, \"tutto\" si rivela avere un po' più di volume di quanto pensassi.",
        "La differenza tra stupidità e genio è che il genio ha i suoi limiti.",
        "È meglio essere un guerriero in un giardino che un giardiniere in una guerra.",
        "Il grande successo arriva sempre a rischio di un enorme fallimento.",
        "Il successo viene dalla curiosità, dalla concentrazione, dalla perseveranza e dall'autocritica.",
        "È il segno di una mente colta essere in grado di intrattenere un pensiero senza accettarlo.",
        "L'opinione di 10.000 persone non ha valore se nessuna di loro conosce l'argomento.",
        "Più diamo valore a cose al di fuori del nostro controllo, meno controllo abbiamo.",
        "Fai viaggi. Tentali. Non c'è nient'altro.",
        "Le origini non dovrebbero mai essere un ostacolo al successo. Un inizio modesto nella vita può essere un aiuto più che un impedimento.",
        "Non lasciare che le mancanze di un altro ti facciano venire meno.",
        "La nostra invidia dura sempre più a lungo della felicità di coloro che invidiamo.",
        "Dal nulla non verrà nulla.",
        "Le persone deboli si vendicano. Le persone forti perdonano. Le persone intelligenti ignorano.",
        "Non controllo il vento; lo studio soltanto.",
        "L'onore potrebbe non conquistare il potere, ma conquista il rispetto. E il rispetto guadagna il potere.",
        "L'arma finale è il cervello, tutto il resto è supplementare.",
        "Se non superi la tua tendenza ad arrenderti facilmente, la tua vita non porterà a nulla.",
        "L'allenamento è come spazzare il pavimento. Solo perché lo abbiamo fatto una volta non significa che il pavimento sia pulito per sempre.",
        "Ricorda che siamo noi a tormentarci, noi a crearci le difficoltà — cioè le nostre opinioni lo fanno. Cosa significa, per esempio, essere insultati? Mettiti vicino a una roccia e insultala, e cosa avrai ottenuto? Se qualcuno risponde all'insulto come una roccia, cosa ha guadagnato l'offensore con le sue ingiurie?",
        "In assenza di uno scopo, la vita diventa un viaggio infinito verso il nulla.",
        "Solo i morti hanno visto la fine della guerra.",
        "Prevenire è meglio che curare.",
        "Niente di ciò che viene insegnato con la forza resta nell'anima.",
        "Tutto ciò che esiste nella tua vita è così a causa di due cose: qualcosa che hai fatto o qualcosa che non hai fatto.",
        "Un uomo senza etica è una bestia selvaggia scatenata su questo mondo.",
        "Pensare è difficile, ecco perché la maggior parte delle persone giudica.",
        "Non trovi la forza di volontà, la crei.",
        "La parola felice perderebbe il suo significato se non fosse bilanciata dalla tristezza.",
        "Non pregare per una vita facile. Prega per la forza di sopportarne una difficile.",
        "Non sei tutto ciò che potresti essere, e lo sai.",
        "Ricordati di vivere mentre sei impegnato a sopravvivere.",
        "I piani non sono nulla, la pianificazione è tutto.",
        "Un uomo che osa sprecare un'ora di tempo non ha scoperto il valore della vita.",
        "Devi decidere chi sei e costringere il mondo a fare i conti con te, non con la sua idea di te.",
        "L'arte di vivere somiglia più alla lotta che alla danza, nella misura in cui sta pronta contro l'accidentale e l'imprevisto e non è incline a cadere.",
        "Con il passare degli anni, presto meno attenzione a ciò che gli uomini dicono. Guardo solo ciò che fanno.",
        "Mi stringerò la cintura prima di chiedere aiuto.",
        "Nessuno è fatto come te, ti sei progettato da solo.",
        "Nessun uomo ha il diritto di essere un dilettante nella formazione fisica. È una vergogna per un uomo invecchiare senza vedere la bellezza e la forza di cui il suo corpo è capace.",
        "Più un uomo si avvicina a una mente calma, più si avvicina alla forza.",
        "Ecco una regola da ricordare in futuro, quando qualcosa ti tenta a sentirti amaro: non \"Questa è sfortuna\", ma \"Sopportare questo degnamente è buona fortuna.\"",
        "Quando sei bravo in qualcosa lo dirai a tutti. Quando sei grande in qualcosa, te lo diranno loro.",
        "Prima ti ignorano. Poi ti ridicolizzano. Poi ti attaccano e vogliono bruciare te. E poi ti costruiscono monumenti.",
        "Libertà significa responsabilità. Ecco perché la maggior parte degli uomini la teme.",
        "Se dici la verità, non devi ricordare niente.",
        "Il tuo momento sta arrivando se continui ad andare avanti.",
        "Non è la morte che un uomo dovrebbe temere, ma dovrebbe temere di non iniziare mai a vivere.",
        "Le procedure di oggi sono i risultati di domani. Se riesci ad innamorarti delle procedure di oggi amerai i risultati di domani.",
        "Tutti i problemi dell'umanità derivano dall'incapacità dell'uomo di stare seduto in silenzio in una stanza da solo.",
        "Non lasciare mai che il futuro ti turbi. Lo affronterai, se necessario, con le stesse armi della ragione che oggi ti armano contro il presente.",
        "L'uomo matura attraverso il dolore, il fallimento, il rifiuto, la perdita, la mancanza di rispetto e il cuore spezzato, non attraverso l'età.",
        "Forgiamo noi stessi le catene che indossiamo nella vita.",
        "Per fare qualsiasi cosa ad alto livello, deve essere un'ossessione.",
        "Se vuoi migliorare, accontentati di essere considerato sciocco e stupido riguardo alle cose esterne.",
        "La violenza è l'ultimo rifugio dell'incompetente.",
        "La paura è come il fuoco, può essere utile se sai come usarla. Se no, ti brucerai.",
        "Per avere un grande successo, devi essere preparato a un grande fallimento. Se non riesci a fare entrambe le cose, hai un problema.",
        "Parliamo sempre di qualcuno che non ci apprezza \"senza motivo\", ma la gente ti apprezzerà anche \"senza motivo\". Quindi non dare troppo peso a nessuna delle due cose.",
        "I codardi muoiono molte volte prima della loro morte; i valorosi non assaggiano la morte che una volta sola.",
        "Niente è più difficile, e quindi più prezioso, che essere in grado di decidere.",
        "Percorri un unico sentiero, senza diventare arrogante nella vittoria né spezzato nella sconfitta, senza dimenticare la cautela quando tutto è tranquillo né spaventarti quando il pericolo minaccia.",
        "L'anima prende il colore dei propri pensieri.",
        "Non chiedo un fardello più leggero. Chiedo spalle più larghe.",
        "Non negoziare con te stesso. Dai istruzioni a te stesso.",
        "Non puoi desiderare sia un carattere forte che una vita facile.",
        "Il coraggio non è avere la forza di andare avanti — è andare avanti quando non hai la forza.",
        "La vita non ti succede, succede coinvolgendoti.",
        "È fatale entrare in una guerra senza la volontà di vincerla.",
        "Non sai mai quanto sei forte finché essere forte non è la tua unica opzione.",
        "Non puoi accontentare tutti, a volte devi agire e lasciare che tutti gli altri reagiscano.",
        "Non è una questione di \"se\", la questione è solo quando — quando sei risoluto riguardo alla missione.",
        "Per quanto tempo aspetterai prima di pretendere il meglio per te stesso?",
        "Il mondo ti promette il comfort, ma tu non sei stato fatto per il comfort. Sei stato fatto per la grandezza.",
        "L'integrità non è una strada veloce, ma è una strada sicura.",
        "Sii il tuo più grande fan, il tuo più grande sostenitore, e caricatelo sulle spalle e porta il peso.",
        "Per prima cosa dì a te stesso cosa vorresti essere; e poi fai ciò che devi fare.",
        "Temo il giorno in cui la tecnologia supererà l'interazione umana. Il mondo avrà una generazione di idioti.",
        "Non importa cosa sopporti, ma come lo sopporti.",
        "Rifiuta il tuo senso di offesa e l'offesa stessa scompare.",
        "Non fare piani piccoli. Non hanno la magia per accendere il sangue degli uomini e probabilmente non saranno mai realizzati. Fai grandi piani; mira in alto nella speranza e nel lavoro, ricordando che un diagramma nobile e logico una volta registrato non morirà mai, ma molto dopo che saremo andati via sarà una cosa viva, che si afferma con insistenza sempre crescente.",
        "Le avversità spesso preparano le persone ordinarie a un destino straordinario.",
        "Quando vuoi cambiare le cose, non puoi accontentare tutti. Se accontenti tutti, non stai facendo abbastanza progressi.",
        "Non negoziare con te stesso, dai istruzioni a te stesso.",
        "Il successo non è definitivo, il fallimento non è fatale: è il coraggio di continuare che conta.",
        "Se non è giusto non farlo; se non è vero non dirlo.",
        "I cosiddetti piaceri, quando superano un certo limite, non sono che punizioni.",
        "Se non sacrifichi per ciò che vuoi, ciò che vuoi diventa il sacrificio.",
        "Il tuo più grande nemico è la tua mente incontrollata.",
        "Impara a combattere così non dovrai mai combattere.",
        "Quando una persona non riesce a trovare un senso profondo di significato, si distrae con il piacere.",
        "Niente è permanente in questo mondo malvagio, nemmeno i nostri problemi.",
        "Lasciali avere torto su di te. Non c'è nulla da dimostrare a loro.",
        "Se vuoi che il presente sia diverso dal passato, studia il passato.",
        "Se vuoi vivere una vita felice, legala a un obiettivo, non a persone o oggetti.",
        "Non ci sono segreti, c'è solo l'informazione che hai scoperto e l'informazione che non hai ancora scoperto.",
        "Hai bisogno di motivazione per agire. Hai bisogno di informazioni per sapere su cosa agire. Hai bisogno di curiosità per ottenere le informazioni che guideranno correttamente queste azioni motivate. Quindi sii curioso.",
        "Un vincitore è solo un perdente che ha provato una volta in più.",
        "Trattiamo il corpo rigorosamente affinché non sia disobbediente alla mente.",
        "I volenterosi sono guidati dal destino, i riluttanti ne sono trascinati.",
        "L'uomo che teme la morte non farà mai nulla degno di un uomo che è vivo.",
        "Un comandante non ripone mai tanta fiducia nella pace da non prepararsi alla guerra.",
        "Non avere paura. Ce la farai, ma ti sembrerà sempre di non farcela.",
        "La costanza può sembrare molto simile alla noia, ma cos'altro pensavi che fosse essere grandi? Fortuna?",
        "Tieni sempre il viso rivolto verso il sole e le ombre cadranno dietro di te.",
        "La pena più pesante per chi rifiuta di governare è essere governato da qualcuno inferiore a te.",
        "Scava dentro. Dentro c'è la sorgente del Bene; ed è sempre pronta a sgorgare, se solo scavi.",
        "Sei ciò che fai, non ciò che dici che farai.",
        "Sbagliare a modo proprio è meglio che avere ragione a modo di qualcun altro.",
        "Un grande uomo è duro con se stesso, un uomo debole è duro con gli altri.",
        "Amare se stessi è l'inizio di una storia d'amore che dura tutta la vita.",
        "Preoccupati di ciò che pensano gli altri e sarai sempre loro prigioniero.",
        "L'uomo non è preoccupato dai problemi reali tanto quanto dalle ansie immaginarie sui problemi reali.",
        "L'uomo felice è soddisfatto della sua situazione presente, qualunque essa sia.",
        "La prima e più grande vittoria è conquistare se stessi.",
        "Per controllarmi devo prima accettarmi, assecondando la mia natura invece di contrastarla.",
        "Che gli uomini vedano, che sappiano, un vero uomo che vive come doveva vivere.",
        "Chi non sa obbedire a se stesso sarà comandato.",
        "Quando temi qualcosa, impara il più possibile su di essa. La conoscenza conquista la paura.",
        "Ho sempre pensato che fossi io contro il mondo e poi un giorno ho capito che è solo io contro me stesso.",
        "Un uomo che manca di scopo si distrae con il piacere.",
        "È difficile accettare che non tutti \"capiranno\"... ma è per questo che non è per tutti gli altri. È una cosa \"tua\".",
        "Più grande è la difficoltà, più gloria nel superarla.",
        "Ci deliziamo nella bellezza della farfalla, ma raramente ammettiamo i cambiamenti che ha attraversato per raggiungere quella bellezza.",
        "Lasciami cadere se devo cadere. Colui che sto diventando mi prenderà.",
        "Dietro un uomo che perdona tutto, c'è un uomo che conosce il peso dei propri peccati.",
        "Il tentativo di fuggire dal dolore crea più dolore.",
        "Il vero sviluppo non rispetta il comfort.",
        "Per quanto possiamo discernere, l'unico scopo dell'esistenza umana è accendere una luce di significato nell'oscurità del mero essere.",
        "Il giorno in cui pianti il seme non è il giorno in cui mangi il frutto.",
        "La verità non cambia perché è o non è creduta dalla maggioranza delle persone.",
        "Un cavaliere in armatura scintillante non ha alcun valore dimostrato. Datemi un cavaliere testato in battaglia con l'armatura provata dagli scontri con i miserabili dell'umanità.",
        "La misura dell'intelligenza è la capacità di cambiare.",
        "Non c'è raccolto senza fame.",
        "È la mente stessa che svia la mente. Della mente, non essere incurante.",
        "Non puoi sognarti un carattere; devi martellarlo e forgiarlo.",
        "Molto andrà storto prima che tutto vada bene.",
        "Viviamo solo adesso. Tutto il resto è passato o è sconosciuto.",
        "Non sarai punito per la tua rabbia, sarai punito dalla tua rabbia.",
        "Non si impara a nuotare leggendo dell'acqua.",
        "Le scelte più difficili richiedono le volontà più forti.",
        "Soprattutto, non mentire a te stesso.",
        "Il tuo corpo può sopportare quasi tutto; è la mente che devi convincere.",
        "La vita è un gioco in prima persona. Trattala come tale.",
        "I buoni leader non inventano scuse. Trovano il modo di portare a termine il lavoro.",
        "Solo perché ci hai messo più tempo degli altri non significa che hai fallito.",
        "Più conosci te stesso, meno hai bisogno dell'approvazione degli altri.",
        "Conoscere se stessi è l'inizio di ogni saggezza.",
        "Non è la taglia di un uomo che conta, ma la grandezza del suo cuore.",
        "È improbabile che tu cambi livello senza lacrime.",
        "Ari con l'aratro che hai.",
    ]
}
