// QuotesLang_tr.swift
// Spike AI — Bundled quote translations
import Foundation
enum QuotesLang_tr {
    static let quotes: [String] = [
        "Zihninizde sürekli olarak tuttuğunuz şey, hayatta tam olarak deneyimleyeceğiniz şeydir.",
        "Hedefe isabet ettirmek için hedefin üstünü nişan alırız.",
        "Olabileceğim en kötü şey herkes gibi olmaktır, bundan nefret ediyorum.",
        "Yalnızca çok ileri gitmeyi göze alanlar, ne kadar ileri gidilebileceğini keşfedebilir.",
        "Atla, ağ kendiliğinden belirecektir.",
        "Limandaki gemi güvendedir, ama gemiler bunun için inşa edilmez.",
        "Başarısızlıklar için endişelenmeyin, denemediğinizde kaçırdığınız fırsatlar için endişelenin.",
        "Sefil bir şekilde başarısız olmaya cesaret edenler büyük başarılar elde edebilir.",
        "Başlamanın yolu, konuşmayı bırakıp yapmaya başlamaktır.",
        "Birçok yenilgiyle karşılaşabiliriz, ama yenilmemeliyiz.",
        "Bir insanın gerçek ölçüsü, kendisine hiçbir faydası olmayan birine nasıl davrandığıdır.",
        "Nereye gittiğini bilmiyorsan dikkatli ol, çünkü oraya varamayabilirsin.",
        "Büyük şeyler yapabilmek için önce kendinden büyük şeyler beklemelisin.",
        "Geçmiş kararlarının gelecekteki sonuçlarını belirlemesine asla izin verme.",
        "Kestirme yollar uzun gecikmelere neden olur.",
        "Hedeflerini sana kimse veremez.. Bu senin yolculuğun.",
        "Dünya, onun hakkında ne düşündüğündür; farklı düşün ve dünyan değişecektir.",
        "Gelecek, bugünden ona hazırlananlarındır.",
        "En çok istediğin şeyi, şu an istediğin şey için feda etme.",
        "Bana ne kadar yetenekli olduğunu söyleme, ne kadar çok çalıştığını söyle.",
        "Kaybettiğinde nasıl düşündüğün, ne zaman kazanacağını belirler.",
        "Bir kişi başarıya ulaştığına karar verdiğinde ilerleme durur.",
        "Hiçbir sorun sürekli düşünmenin baskısına dayanamaz.",
        "Şans, bir fırsat geldiğinde ve sen ona hazır olduğunda ortaya çıkar.",
        "İlerlemenin sırrı başlamaktır.",
        "Ağaç dikmenin en iyi zamanı 20 yıl önceydi. İkinci en iyi zaman şimdidir.",
        "Asla pes etmeyen bir insanı yenmek zordur.",
        "Yaz. Çek. Yayınla. Ör, soté yap. Her neyse, yarat!",
        "Her ne olursan ol, iyi bir tane ol.",
        "Mutluluk hazır bir şey değildir, kendi eylemlerinizden gelir.",
        "Akıllı insanlar her şeyden ve herkesten öğrenir.",
        "İmkansız sadece bir görüştür.",
        "Tutkunuz cesaretin yetişmesini bekliyor.",
        "Bardağın yarısı boş mu dolu mu diye merak edenler meseleyi kaçırıyor. Bardak yeniden doldurulabilir.",
        "Bir gün ya da birinci gün; sen karar ver.",
        "İyi şeyler bekleyenlere gelebilir, ama sadece koşturanların bıraktığı şeyler.",
        "Her şey, beklerken koşturana gelir.",
        "Birisi günde 24 saat çalışıp onu senden almak istiyormuş gibi çalış.",
        "Hiç kimse herkes gibi olarak fark yaratmamıştır.",
        "Kötü zamanların olacak, ama bu seni her zaman dikkat etmediğin güzel şeylere uyandıracak.",
        "Kendinin birinci sınıf versiyonu ol, başka birinin ikinci sınıf versiyonu değil.",
        "Başkalarının hatalarından ders al. Hepsini kendin yapmak için yeterince uzun yaşayamazsın.",
        "Yorgunsan, yorgun olarak yap.",
        "Bir insan yenildiğinde bitmez, pes ettiğinde biter.",
        "Dünya, fikirlerinle değil, örneklerinle değişir.",
        "Hayat bisiklet sürmek gibidir. Dengenizi korumak için hareket etmeye devam etmelisiniz.",
        "Hayat hakkında düşünmek; hiçbir suçluluk geçmişi değiştiremez, hiçbir kaygı geleceği değiştiremez.",
        "Olumsuz bir zihin sana asla olumlu bir hayat vermez.",
        "Her şey kolay olmadan önce zordur.",
        "Ya risk al, ya da fırsatı kaybet.",
        "Asla öğrenmeyi bırakma, çünkü hayat asla öğretmeyi bırakmaz.",
        "Okumayan adamın, okuyamayan adama karşı hiçbir avantajı yoktur.",
        "Hiç hata yapmamış bir insan, asla yeni bir şey denememiştir.",
        "İnsanların güçlerini kaybetmelerinin en yaygın yolu, hiç güçleri olmadığını düşünmeleridir.",
        "Sahip olduğun şeyler için şükret; sonunda daha fazlasına sahip olursun. Sahip olmadıklarına odaklanırsan asla yeterince sahip olamazsın.",
        "En zor şey harekete geçme kararıdır, gerisi sadece azimdir.",
        "Hayattaki başarısızlıkların çoğu, pes ettiklerinde başarıya ne kadar yakın olduklarını fark etmeyen insanlardır.",
        "Önemli olan yere serilip serilmemen değil, ayağa kalkıp kalkmamandır.",
        "Kötümser, her fırsatta zorluk görür. İyimser, her zorlukta fırsat görür.",
        "En büyük şanımız hiç düşmemek değil, her düştüğümüzde ayağa kalkmaktır.",
        "Zihninizin korkuları tarafından itilmeyin; kalbinizdeki hayaller tarafından yönlendirilmeyin.",
        "Ne istediğini bildiğinde ve onu yeterince istediğinde, elde etmenin bir yolunu bulursun.",
        "Gerekli olanla başla, sonra mümkün olanı yap ve birden bire imkansızı yapıyorsun.",
        "Tutku olmadan enerjin olmaz, enerji olmadan hiçbir şeyin olmaz.",
        "Başlamak için harika olmak zorunda değilsin, ama harika olmak için başlamak zorundasın.",
        "Güç fiziksel kapasiteden değil, yenilmez bir iradeden gelir.",
        "Bir başkasının yükünü hafifleten hiç kimse bu dünyada işe yaramaz değildir.",
        "İmkansızı isteyerek mümkünü elde ederiz.",
        "Bir gün aslan olmak, ömür boyu koyun olmaktan iyidir.",
        "Hayat ciddiye alınamayacak kadar önemlidir.",
        "Başlangıç, her eylemin yarısıdır.",
        "Sonsuz sabır anında sonuç getirir.",
        "Neredeyse tüm insanlar hastalıklarından değil, çarelerinden ölür.",
        "Yapabilirler, çünkü yapabileceklerini düşünürler.",
        "Hayal gücü bilgiden daha önemlidir.",
        "Azimli insanlar başarılarına, başkalarının başarısızlıkla bitirdiği yerde başlar.",
        "Net yollar yoktur. Sadece tuzaklar, teller ve karanlık vardır.",
        "Bir hata, birisinin konuşmayı bırakıp bir şey yapacak kadar durduğunu kanıtlar.",
        "Yapılmaya değer olan her şey, iyi yapılmaya değerdir.",
        "En güçlü olan, kendine hakim olandır.",
        "Rahatlık sevgisini besleyen bir alim, alim sayılmaya layık değildir.",
        "Refah, sahip olduğunu istemene bağlıdır, istediğine sahip olmana değil.",
        "Her gün kendi hediyelerini getirerek gelir, kurdelelerini çöz.",
        "Başarı asla kalıcı değildir ve başarısızlık asla nihai değildir.",
        "Hiçbir şey sonsuza kadar sürmez.. Sorunların bile.",
        "Sıkı çalışma başarıyı garanti etmez, ama şansını artırır.",
        "Barış zorla sağlanamaz. Ancak anlayışla başarılabilir.",
        "Girişimde bulunmayan şans elde edemez.",
        "Boş zamanım olduğunda çalışacağım deme, boş zamanın olmayabilir.",
        "İnancını kaybeden her şeyi kaybeder.",
        "Kişinin düşüncesi onun dünyasıdır. Bir insan ne düşünürse o olur.",
        "Macera insanın dışında değil, içindedir.",
        "Hayat oyununda mesele iyi bir el tutmak değil, kötü bir eli iyi oynamaktır.",
        "Ekşi, tatlı, acı, keskin; hepsi tadılmalıdır.",
        "Geçmiş başarısızlık duygusunun bir sonraki adımını yenmesine asla izin verme.",
        "Hırslı olmadıkça ilerleme kaydedemezsin.",
        "Gelecek cesaret edenlere aittir.",
        "Gerçekler, görmezden gelindiği için var olmaktan çıkmaz.",
        "Kanıtlanamayan şeyi asla varsaymamalıyız.",
        "Yüksek bir ses, fısıltı bile olsa net bir sesle yarışamaz.",
        "Son bölgeye girecekmiş gibi davran.",
        "Mutluluk, görevin doğal çiçeğidir.",
        "\"Hayır\" basitçe bir seviye daha yüksekten yeniden başlamak demektir.",
        "Coşku dünyayı harekete geçirir.",
        "Şampiyon, kalkamadığında bile kalkan kişidir.",
        "Engeller, büyüklüğün bedelidir.",
        "Soru kimin izin vereceği değil, kimin durduracağıdır.",
        "Yarışmak için değil, kazanmak için oradaydım.",
        "Sızlanmayı bırak, çalışmaya başla.",
        "Zorluklardan mucizeler doğar.",
        "Korkmuyorum, bunun için doğdum.",
        "Asla başını eğme. Dik tut.. Dünyaya doğrudan bak.",
        "Yapmak istediğini yapabilene kadar yapman gerekeni yap.",
        "Dün düştüysen, bugün ayağa kalk.",
        "Her günü şaheserine dönüştür.",
        "Kan, ter ve saygı. İlk ikisini verirsin, sonuncusunu kazanırsın.",
        "O kadar iyi ol ki seni görmezden gelemesinler.",
        "Dünyaya, kazananlar kulübü için ne kadar savaşacağını göster.",
        "Kendi hayat planını tasarlamazsan, başka birinin planına düşme ihtimalin var. Senin için ne planladılar? Pek bir şey değil.",
        "Olman gereken tek kişi, olmaya karar verdiğin kişidir.",
        "Demir sıcakken vurmayı bekleme; vurarak onu ısıt.",
        "Tanrı'nın bizi sıradan olmak için bu dünyaya koyduğuna inanamıyorum.",
        "Dünyanın benim burada olduğum için daha iyi bir yer olmasını istiyorum.",
        "Azim alışkanlığı, zafer alışkanlığıdır.",
        "Büyük olanı yakalamak için iyiyi bırakmaktan korkma.",
        "Görevini yap ve biraz fazlasını yap, gelecek kendine bakacaktır.",
        "Hayat, insanın iradesini sınamanın bir yoluna sahiptir.. Ya hiçbir şey olmaz ya da her şey bir anda olur.",
        "Akıllı bir adam her zaman yalnız bulunabilir. Zayıf bir adam her zaman kalabalıkta bulunabilir.",
        "Cesaret etmek, bir anlığına dengesini kaybetmektir. Cesaret etmemek ise kendini kaybetmektir.",
        "Korku, dünyadaki diğer her şeyden daha fazla insanı yener.",
        "Evrendeki en güçlü kelimeler kendinle konuşmak için kullandıklarındır.",
        "Uyuyan adama gelen tek şey rüyalardır.",
        "Eğer kendini yenemezsen, kendin tarafından yenilirsin.",
        "Kahraman, bir dakika daha dayanmayı bilen kişidir.",
        "Görebildiğin kadar ileri git, oraya vardığında daha ilerisini görebileceksin.",
        "Dünyadaki yerini keşfetmezsin, onu kendin oyarsın.",
        "Kazananlar kazanmaya odaklanır. Kaybedenler kazananlara odaklanır.",
        "Başarma kararlılığım yeterince güçlüyse başarısızlık beni asla yenemez.",
        "Kolay gelen dayanmaz. Dayanan kolay gelmez.",
        "Eleştiriden kaçınmak için: hiçbir şey söyleme, hiçbir şey yapma, hiç kimse olma.",
        "Aldığından fazlasını yapan adam, yakında yaptığından fazlasını alacaktır.",
        "Deha büyük işlere başlar, yalnızca emek onları bitirir.",
        "Doğru yolda olsan bile, orada oturursun üzerinden geçerler.",
        "İşler başarısız olmuyorsa, yeterince yenilik yapmıyorsun demektir.",
        "Kendinizin en iyisini verdiğinizde başkalarından en iyisini alırsınız.",
        "Liderlik bir eylemdir, bir pozisyon değil.",
        "İşimiz, yeteneklerimizin sunumudur.",
        "Tüm sorunlarım inatçılığım karşısında eğilir.",
        "Başarısızlığını bir onur madalyası olarak taşı.",
        "Yeteneklerimizle değil, vizyonumuzla sınırlıyız.",
        "Yorulduysan, bırakmayı değil dinlenmeyi öğren.",
        "Düşmek bir kaza, kalmak bir tercihtir.",
        "Bu hayattan vazgeçmeye sakın cüret etme. Bu gece değil. Yarın değil. Asla.",
        "Kişilere ya da olaylara yenilmeye asla izin verme.",
        "Bazı insanlar başarıyı hayal eder, diğerleri uyanır ve bunun için çok çalışır.",
        "Güven deneyimden gelir. Deneyimler deneyip başarısız olup tekrar denemekten gelir - bu sefer daha iyi.",
        "Ustalığa giden süre, odaklanmamızın yoğunluğuna bağlıdır.",
        "Başarı ancak denemeye cesaret edenlere gelir.",
        "Başarının önemli bir anahtarı özgüvendir. Özgüvenin önemli bir anahtarı ise hazırlıktır.",
        "Şüphe, başarısızlıktan daha fazla hayali öldürür.",
        "Zafer, savaşmayı reddetmeyen kişi için her zaman mümkündür.",
        "Her gün yaptığın bir şeyi değiştirene kadar hayatını asla değiştiremezsin.",
        "Başarılı olmak için odağın o kadar yoğun olmalı ki başkaları seni deli sansın.",
        "Engeller, gözlerini hedefinden çektiğinde gördüğün o korkunç şeylerdir.",
        "Bir fırsat bulmak, onun orada olduğuna inanmak meselesidir.",
        "Hedef belirlemek, görünmezi görünür kılmanın ilk adımıdır.",
        "Hiçbir şeyi riske atmazsan, her şeyi riske atarsın.",
        "Durumunu değiştiremiyorsan, düşünceni değiştir.",
        "Geçmiş ne kadar zor olursa olsun, her zaman yeniden başlayabilirsin.",
        "Hiçbir şeye cesaret etmezsen, gün bittiğinde kazandığın tek şey hiçbir şey olacaktır.",
        "Çoğu zaman manzara değişikliğinden çok, benlik değişikliğine ihtiyaç vardır.",
        "Korku en büyük engeldir ve seni felç edecektir.",
        "Tehlikeli olan evrim geçirmemektir.",
        "Her halükarda ya bir yol bulurum ya da bir yol yaratırım.",
        "Herkesi susturmanın tek yolu kazanmaktır.",
        "Yeterince iyinin yeterince iyi olmasına asla izin verme.",
        "Uzun vadede sadece nişan aldığımız şeye isabet ettiririz.",
        "Sürekli iyileştirme, ertelenmiş mükemmeliyetten daha iyidir.",
        "Eğer zihninde görüyorsan, elinde tutacaksın.",
        "Bugün başkalarının yapmayacağını yapacağım, böylece yarın başkalarının yapamayacağını yapabilirim.",
        "Mükemmellik, eğitim ve alışkanlıkla kazanılan bir sanattır.",
        "Önümüzdeki yıl, hayatın hakkında bir şey yapsan da yapmasan da geçecek.",
        "Yorulduğunda durma, bitirdiğinde dur.",
        "İyi bir ruh halinden sadece bir antrenman uzaktasın.",
        "Kolay olanı değil, doğru olanı yap; popüler olanı da değil.",
        "Hiçbir büyük şey kolay gelmemiştir.",
        "Mücadele olmadan ilerleme olmaz.",
        "Başarılı insanlar daha iyi sorular sorar ve sonuç olarak daha iyi cevaplar alır.",
        "Özel yeteneklerim yok, sadece tutkuyla merak ediyorum.",
        "Hayatta öğrendiğim en iyi ders, hayatta hissettiğim en kötü duygudan geldi.",
        "Zorluklar hayatı ilginç kılan şeylerdir. Onları aşmak hayatı anlamlı kılar.",
        "Sonsuz dene, başarısız ol, öğren yaklaşımıyla mutlu olmayı öğren.",
        "Tüm hataların kapısını kapatırsan, gerçek de dışarıda kalır.",
        "Hatayı unut, dersi hatırla.",
        "Yalnızca yapabildiğini yapabilirsen, asla şu an olduğundan daha fazlası olamazsın.",
        "Akıllı olan kim? Herkesten öğrenen.",
        "Hayatımı yalnızca ben değiştirebilirim, kimse benim için yapamaz.",
        "Azim, 19 kez başarısız olup 20. seferinde başarmaktır.",
        "Başarımı şuna bağlıyorum: asla mazeret vermedim ya da kabul etmedim.",
        "Koşullarımın ürünü değilim. Kararlarımın ürünüyüm.",
        "Eylemlerimiz bizi belirlediği kadar biz de eylemlerimizi belirleriz.",
        "Yalnızca aşırı cahil ya da aşırı zeki olanlar değişime direnir.",
        "Kendine güvenen adam, başkalarının güvenini kazanır.",
        "Aradığın şey seni arıyor.",
        "Başarısızlık konusunda endişelenme. Sadece bir kez haklı olman yeterli.",
        "Güvenlik çoğunlukla bir batıl inançtır. Hayat ya cesur bir macera ya da hiçbir şeydir.",
        "Çoğu zaman ne düşündüğümüz oluruz ve bu en tuhaf sırdır.",
        "Başlamanın yolu, konuşmayı bırakıp yapmaya başlamaktır.",
        "Her günü şaheserine dönüştür.",
        "Kaç hata yaparsan yap ya da ne kadar yavaş ilerlersen ilerle, denemeyen herkesten hâlâ çok ileridsin.",
        "Zor bir görevin başlangıcındaki tavrımız, her şeyden çok başarılı sonucunu etkiler.",
        "Bu dünyada bir insanın sahip olacağı tek gerçek güvence, bilgi, deneyim ve yetenek birikimidir.",
        "Bugün yaptığın şey, hayatının tüm yarınlarını değiştirebilir.",
        "Hayatın şansla iyileşmez, değişimle iyileşir.",
        "Bir rüya sihirle gerçeğe dönüşmez; ter, kararlılık ve sıkı çalışma gerekir.",
        "Bilgi, domatesin bir meyve olduğunu bilmektir. Bilgelik, onu meyve salatasına koymamaktır.",
        "Durum ne olursa olsun, kendine hatırlat: \"Bir seçeneğim var\".",
        "Zihnine hükmet, yoksa o sana hükmeder.",
        "Bazıları kaderlerinden dolayı başarılı olur, ama çoğu kararlı oldukları için başarır.",
        "Büyük fırsatlar gözlerinle değil, zihinle görülür.",
        "Risk almaya yeterince cesur olmayan, hayatta hiçbir şey başaramaz.",
        "Bilmek yetmez, uygulamalıyız. İstemek yetmez, yapmalıyız.",
        "Hırs başarıya giden yoldur, azim ise vardığınız araçtır.",
        "Hayatın anahtarı zorlukları kabul etmektir. Birisi bunu yapmayı bıraktığında, ölmüştür.",
        "Kararlılık, bir vaadi gerçeğe dönüştüren şeydir.",
        "Özgüven, başarının hafızasıdır.",
        "Özgüven olmadan beşikteki bebekler gibiyiz.",
        "Hayal kurmaya cesaret et, ama daha da önemlisi hayallerinin arkasına eylem koymaya cesaret et.",
        "Dürüstlük, bilgelik kitabının ilk bölümüdür.",
        "Mükemmellik sürekli bir süreçtir, bir kaza değil.",
        "Umut, tüm karanlığa rağmen ışık olduğunu görebilmektir.",
        "Sınırlı hayal kırıklığını kabul etmeliyiz, ama sonsuz umudu asla kaybetmemeliyiz.",
        "Gerçek zekanın işareti bilgi değil, hayal gücüdür.",
        "Sürekli ve bitmeyen kendini geliştirmeye bağımlı ol.",
        "Deha yüzde bir ilham ve yüzde doksan dokuz terdir.",
        "İlhamın gelmesini bekleyemezsin, peşinden bir sopayla gitmelisin.",
        "Sabırlı ol. Her şey kolay olmadan önce zordur.",
        "Yapılamaz diyen kişi, yapanı bölmemelidir.",
        "Azim, zaten yaptığın zor işten yorulduktan sonra yaptığın zor iştir.",
        "Akıllı bir adam aptalca bir sorudan, bir aptalın akıllıca bir cevaptan öğrenebileceğinden daha fazlasını öğrenebilir.",
        "Sürekli öz-disiplin ve öz-kontrol ile karakter büyüklüğü geliştirebilirsin.",
        "Duygusal öz-kontrol, doğuştan gelen bir beceri değil, sıkı çalışmanın sonucudur.",
        "Nasıl öğrenileceğini öğrenmek hayatın en önemli becerisidir.",
        "Yapamadığın şeyin, yapabildiğin şeyi engellemesine izin verme.",
        "Başarıya giden yolda her zaman başarısızlığın yanından geçersin.",
        "Hiç kimse mükemmel değildir, bu yüzden kalemlerin silgisi vardır.",
        "Kalbinde yapmaya yazgılı olduğunu bildiğin şeyi yapmaktan asla vazgeçme.",
        "Gerçekten yakından bakarsanız, çoğu bir gecede gelen başarı uzun zaman almıştır.",
        "Her şey mümkün. Her şey olabilir.",
        "Küçük parçalara bölerseniz hiçbir şey özellikle zor değildir.",
        "Başarının sırrı, sıradan şeyleri olağanüstü iyi yapmaktır.",
        "Yaptığın şey fark yaratıyormuş gibi davran, çünkü yaratıyor.",
        "Hedeflerine ulaşarak elde ettiğin, hedeflerine ulaşarak olduğun kadar önemli değildir.",
        "Hayat bisiklet sürmek gibidir; dengenizi korumak için hareket etmeye devam etmelisiniz.",
        "\"Her zaman\" ve \"asla\"larını sınırla.",
        "Yeni bir hedef koymak ya da yeni bir hayal kurmak için asla yaşlı değilsiniz.",
        "Mutlu hayatı bulamazsın, onu sen yaratırsın.",
        "Kötü haber: zaman uçuyor. İyi haber: pilot sensin.",
        "Yüzünü her zaman güneşe dön, gölgeler arkanda kalacaktır.",
        "İmkansız ile mümkün arasındaki fark, insanın kararlılığında yatar.",
        "Altın madalyalar gerçekten altından yapılmaz. Terden, kararlılıktan ve cesaret denilen bulunması zor bir alaşımdan yapılır.",
        "Sessiz bir adamın kararlılığını hafife alma.",
        "Bana neye inandığını söyleme. Nasıl davrandığını gözlemleyeceğim ve kendi kararımı vereceğim.",
        "Sadece kaybetmekten nefret ediyorum ve bu sana daha çok çalışmak için ekstra bir kararlılık veriyor.",
        "Kazanma kararlılığı, kazanmanın daha iyi kısmıdır.",
        "Dünyanın tüm yeteneğine sahip olabilirsin, ama kararlılık olmadan çok ileri gidemezsin.",
        "Zafer, hazırlık ve kararlılığın çocuğudur.",
        "Genç adam kuralları bilir, ama yaşlı adam istisnaları bilir.",
        "Kötümser rüzgardan şikayet eder, iyimser değişmesini bekler, gerçekçi yelkenleri ayarlar.",
        "Bilginin uygulamaya konmadıkça değeri yoktur.",
        "Yaptıklarıma pişman olmaktansa yapmadıklarıma pişman olmayı tercih ederim.",
        "Bilgeliği anlamak için bilgelik gerekir. Dinleyici sağırsa müzik hiçbir şeydir.",
        "Çoğumuz için en büyük tehlike, hedefimizi çok yükseğe koyup ulaşamamak değil, çok alçağa koyup ulaşmaktır.",
        "Doğayla her yürüyüşte, insan aradığından çok daha fazlasını alır.",
        "Yolun götürebileceği yere gitmeyeceğim, yol olmayan yere gideceğim ve bir iz bırakacağım.",
        "Bugünün güçlü meşesi, dün yerini koruyan bir cevizden başka bir şey değildir.",
        "Kendine karşı tamamen dürüst olmak iyi bir egzersizdir.",
        "Olduğumuz şey kalarak olmamız gereken şey olamayız.",
        "Rotanı yıldızlara göre belirle, her geçen geminin ışıklarına göre değil.",
        "Nereye gittiğini bilmiyorsan, herhangi bir yol seni oraya götürür.",
        "Her zaman iki seçeneğin olacak: kararlılığın ya da korkun.",
        "Hatırlamadan verenler ve unutmadan alanlar kutsanmıştır.",
        "Olan şey, olana nasıl tepki verdiğin kadar önemli değildir.",
        "Kabul edilebilir olanla değil, doğru olanla başla.",
        "Üstün insan kendini suçlar. Aşağı insan başkalarını suçlar.",
        "En küçük eylem, en büyük niyetlerden daha iyidir.",
        "Keşfin önündeki en büyük engel cehalet değil, bilgi yanılsamasıdır.",
        "Yanlış bilgiden sakın, cehaletten daha tehlikelidir.",
        "Geleceği tahmin etmenin en iyi yolu onu icat etmektir.",
        "Risk almadan kazanmak, zafer olmadan zafer kazanmaktır.",
        "Karakterimiz, kimsenin bakmadığını düşündüğümüzde yaptığımız şeydir.",
        "Başkaları hakkında bizi rahatsız eden her şey, kendimizi anlamamıza yol açabilir.",
        "Bilge olmanın sanatı, neyi görmezden geleceğini bilme sanatıdır.",
        "Söyle bana, unuturum. Öğret bana, hatırlarım. Beni dahil et, öğrenirim.",
        "Kafanda beynin var. Ayaklarında ayakkabıların var. Kendini istediğin yöne yönlendirebilirsin.",
        "Üç kelimeyle hayat hakkında öğrendiğim her şeyi özetleyebilirim: devam ediyor.",
        "Hayat, işe yarayıp yaramadığını görmek için şeyleri denemektir.",
        "Başarı genellikle onu aramakla meşgul olanlara gelir.",
        "Başarısız olmadım, sadece işe yaramayan 10.000 yol buldum.",
        "Başarıya giden yolumu başarısızlıkla buldum.",
        "Kendini programlamazsan, hayat seni programlar.",
        "Kendime acıyacak zamanım yok.. Şikayet edecek zamanım yok.. İlerlemeye devam edeceğim.",
        "Alışılmışı riske atmaya istekli değilsen, sıradanla yetinmek zorunda kalacaksın.",
        "Başarı, coşku kaybetmeden başarısızlıktan başarısızlığa gidebilme yeteneği olarak tanımlanmıştır.",
        "Tüm hayallerimiz, onları takip etme cesaretimiz varsa gerçek olabilir.",
        "Fırsatlar kendiliğinden olmaz, sen yaratırsın.",
        "Başarıyı asla hayal etmedim, onun için çalıştım.",
        "Yapamadığın şeyin, yapabildiğin şeye müdahale etmesine izin verme.",
        "Bugün tek gündür, dün gitti.",
        "İşler, işlerin en iyisini yapanlar için en iyi sonucu verir.",
        "Cehennemden geçiyorsan, durmadan devam et.",
        "Sadece kamuya açık zaferleri görürsün.. Onlara ulaşmak için yapılan özel fedakarlıkları asla görmezsin.",
        "Zamanına değer vermezsen, başkaları da vermez.",
        "Senin izinin olmadan hiç kimse seni aşağılık hissettiremez.",
        "Başarılı bir adam, başkalarının kendisine fırlattığı tuğlalarla sağlam bir temel atabilen kişidir.",
        "Bize acı denemeler gibi görünen şeyler çoğu zaman kılık değiştirmiş nimetlerdir.",
        "Dünyada yetenekli ama başarısız insanlardan daha yaygın bir şey yoktur.",
        "Başarılı bir insan olmaya değil, değerli bir insan olmaya çalış.",
        "Basitçe açıklayamıyorsan, yeterince iyi anlamıyorsun demektir.",
        "Denemekten vazgeçene kadar asla başarısız olmazsın.",
        "Bilgi, ne yapabileceğinin farkında olmaktır. Bilgelik, ne zaman yapmaman gerektiğini bilmektir.",
        "Hayat kendini bulmakla ilgili değildir. Hayat kendini yaratmakla ilgilidir.",
        "Sorun sorun değil, sorun senin soruna karşı tavrındır.",
        "Hiçbir şaheser tembel bir sanatçı tarafından yaratılmamıştır.",
        "Başarıya giden yol ile başarısızlığa giden yol neredeyse aynıdır.",
        "Önemli olan neye baktığın değil, ne gördüğündür.",
        "Cesaret korkuya direnistir - korkunun ustası olmaktır, yokluğu değil.",
        "Ne kadar çok çalışırsam o kadar şanslı oluyorum.",
        "Sıcak bir düşüncenin parıltısı benim için paradan daha değerlidir.",
        "Tüm ilerleme, konfor alanının dışında gerçekleşir.",
        "Düşünmek, hayatta karşılaşacağın iniş çıkışlar ne olursa olsun, sermaye varlığın olmalıdır.",
        "Başarı, gün be gün tekrarlanan küçük çabaların toplamıdır.",
        "Başarılı savaşçı, lazer gibi odaklanmış sıradan bir adamdır.",
        "Başarı asla hata yapmamak değil, aynı hatayı ikinci kez yapmamaktır.",
        "Kaybetme korkusunun kazanma heyecanından büyük olmasına izin verme.",
        "İlk adım, çevrene esir olmayı reddettiğin andır.",
        "Ekstra mil boyunca trafik sıkışıklığı yoktur.",
        "Kendini çoğunluğun tarafında bulduğunda, durup düşünmenin zamanıdır.",
        "Başarı, kendini sevmek, yaptığını sevmek ve nasıl yaptığını sevmektir.",
        "Bir hedef her zaman ulaşılmak için değildir, çoğu zaman sadece nişan almak için bir şey olarak hizmet eder.",
        "Taklitte başarmaktansa özgünlükte başarısız olmak daha iyidir.",
        "Motivasyon seni başlatır, alışkanlık seni devam ettirir.",
        "Tatminle yatağa girmek istiyorsan, her sabah kararlılıkla kalkmalısın.",
        "Büyük şeyler yapabilmek için önce kendinden büyük şeyler beklemelisin.",
        "Gerçek zorluklar aşılabilir, sadece hayali olanlar yenilmezdir.",
        "İnsanlar, yaptıkları işte eğlenmezlerse nadiren başarılı olur.",
        "En karanlık anlarımızda ışığı görmek için odaklanmalıyız.",
        "Başarısızlık, başarıya tat veren baharattır.",
        "Zihinler talihsizlikle ehlileştirilir ve boyun eğdirilir, ama büyük zihinler onun üstüne yükselir.",
        "Bir savaşı kazanmak için birden fazla kez savaşmak zorunda kalabilirsin.",
        "Korkmasaydın ne yapardın?",
        "İyi şeyler bekleyenlere gelir, ama daha iyi şeyler gidip alanlaradır.",
        "Her zaman tam bir çaba göster, şans senin aleyhine bile olsa.",
        "Duygularının değişmesini bekleyip harekete geçme, harekete geç ve duyguların değişecektir.",
        "Eylem her zaman mutluluk getirmeyebilir, ama eylem olmadan mutluluk olmaz.",
        "Mükemmellik sıkıcıdır, gelişmek tüm eğlencenin olduğu yerdir.",
        "Asla pes etmeyen bir insanı yenmek zordur.",
        "Bir engel taşı ile bir basamak taşı arasındaki fark, ayağını ne kadar yükseğe kaldırdığındır.",
        "Asla pes etme, çünkü tam da o yer ve zaman akıntının döneceği andır.",
        "Bazen istediğini alamamak harika bir şans eseridir.",
        "Rüzgarın yönünü değiştiremem, ama yelkenlerimi her zaman hedefime ulaşacak şekilde ayarlayabilirim.",
        "İlerle. Durma, yolculuğunda oyalanma, önüne konmuş hedefe doğru çabala.",
        "Bir şeyi gerçekten istiyorsan bekleme, kendine sabırsız olmayı öğret.",
        "Bazen kazanırsın, bazen öğrenirsin.",
        "Bu dünyada iki tür insan var: işleri halletmek isteyenler ve hata yapmak istemeyenler.",
        "En büyük düşmanının kendi iki kulağın arasında yaşamadığından emin ol.",
        "Her zaman hatırla ki kesinlikle eşsizsin, tıpkı herkes gibi.",
        "Her şey kontrolün altındaysa yeterince hızlı gitmiyorsun demektir.",
        "İvmeyi sürdürmenin bir yolu sürekli daha büyük hedefler koymaktır.",
        "Tüm merdiveni görmek zorunda değilsin, sadece ilk adımı at.",
        "Bize acı denemeler gibi görünen şeyler çoğu zaman kılık değiştirmiş nimetlerdir.",
        "Kararlılık konusunda iki seçenek: ya içindesin ya dışında - arada diye bir hayat yoktur.",
        "Bir şeyi istediğinde tüm evren ona ulaşmanda sana yardım etmek için işbirliği yapar.",
        "Mutluluk hazır bir şey değildir, kendi eylemlerinden gelir.",
        "Her ne olursan ol, iyi bir tane ol.",
        "Acı kaçınılmazdır, ıstırap isteğe bağlıdır.",
        "Yetenek, başka kimsenin vuramayacağı bir hedefe vurur; deha, başka kimsenin göremeyeceği bir hedefe vurur.",
        "Zihin kendi başına bir yerdir ve kendi içinde cennetten cehennem, cehennemden cennet yapabilir.",
        "Antrenmandan nefret ederdim, ama 'pes etme' dedim - şimdi acı çek ve hayatının geri kalanını şampiyon olarak yaşa.",
        "Seni yıpratan tırmanılacak dağlar değil, ayakkabındaki çakıl taşıdır.",
        "Ne düşünürsek o oluruz.",
        "Bugün birisi gölgede oturuyor, çünkü birisi uzun zaman önce bir ağaç dikti.",
        "Tek bir güneş ışını birçok gölgeyi kovmaya yeter.",
        "Durağan zihne tüm evren teslim olur.",
        "Öz-disiplinle neredeyse her şey mümkündür.",
        "En iyi çıkış yolu her zaman içinden geçmektir.",
        "Büyük fırsatın tam şu an bulunduğun yerde olabilir.",
        "Hiçbir şey bugünden daha değerli değildir.",
        "Tek yolculuk, içerideki yolculuktur.",
        "Koşullar nereye gidebileceğini belirlemez, sadece nereden başladığını belirler.",
        "İnanç, gerçeği yaratır.",
        "Çölü güzel yapan şey, bir yerlerde bir kuyu saklıyor olmasıdır.",
        "Algının kapıları temizlenseydi, her şey insana olduğu gibi görünürdü: sonsuz.",
        "Düşüncelerini değiştir ve dünyayı değiştir.",
        "Kuş, kendi hayatı ve motivasyonuyla güçlenir.",
        "Işık ver ve insanlar yolunu bulacaktır.",
        "Yarın için en iyi hazırlık, bugün elinden gelenin en iyisini yapmaktır.",
        "Fikirler tarihin akışını şekillendirir.",
        "Hayatın tüm mücevherleri tek bir ipe dizilmez.",
        "İçsel olarak başardığımız şey, dış gerçekliği değiştirecektir.",
        "Başarıya ulaşma kararlılığın, diğer her şeyden daha önemlidir.",
        "Başarıya giden yolda olduğunu biliyorsun, eğer işini para almadan yapardıysan.",
        "İnandığın şey olursun.",
        "Mükemmelliğe ulaşmak istiyorsan, bugün oraya varabilirsin. Bu saniyeden itibaren, mükemmelden azını yapmayı bırak.",
        "Alışılmışı riske atmaya istekli değilsen sıradanla yetinmek zorunda kalacaksın.",
        "Her şeyden önce, hazırlık başarının anahtarıdır.",
        "Yıllar boyunca öğrendim ki, insan kararını verdiğinde korku azalır.",
        "Hayat çok sayıda ayrılıktan oluşur, birbirine kaynaklanmış.",
        "Kazanmak her şey değil, ama kazanmak istemek öyle.",
        "Başarısız olursan hayal kırıklığına uğrayabilirsin, ama denemezsen mahkumsun.",
        "Hatalar hayatın bir gerçeğidir, önemli olan hataya verdiğin tepkidir.",
        "Yürüdüğün yoldan hoşlanmıyorsan, yeni bir yol döşemeye başla.",
        "Eylemler sözlerden daha yüksek sesle konuşur, ve bu çocuklarınız söz konusu olduğunda daha da doğrudur.",
        "Elmas, baskı altında iyi iş çıkarmış bir kömür parçasıdır.",
        "Zor yollar çoğu zaman güzel yerlere çıkar.",
        "Bazen bir anın değerini, o an bir anıya dönüşene kadar asla bilemezsin.",
        "İçeriden parlayan ışığı hiçbir şey söndüremez.",
        "Hayatta başarılı olmak için üç şeye ihtiyacın var: bir dilek kemiği, bir omurga ve bir komik kemik.",
        "Sihre inanmayanlar onu asla bulamaz.",
        "Zamanı geri saracak birine para ödeyemeyeceğime karar verdim, o yüzden üstesinden gelmem gerekiyor.",
        "Her şeyin bir bedeli var, bunun için ne kadar ödemeye hazırsın?",
        "En çok zaferlerden değil, aksiliklerden büyüdüm.",
        "İçimdeki korku ne olursa olsun, kazanma arzumun her zaman daha güçlü olduğu konusunda şanslıyım.",
        "Başka kimse inanmadığında kendine inanmak zorundasın.",
        "Başarısızlıktan korkma, başarılı olmanın yolu budur.",
        "Eleştiriyi severim, seni güçlendirir.",
        "Her zaman elimden gelenin en iyisini yapmak istediğimi biliyorum.",
        "Tanıdığım her başarılı insan bir işkolik.",
        "Kendimden başka kimseyle yarışmadım hiç.",
        "Kendine inanmak ve kim olduğunu bilmek, her büyük şeyin temelidir.",
        "Denemekten korkuyorum.",
        "Geçmişini kurtarmanın yolu ondan kaçmak değil, onu anlamaya çalışmak ve büyümek için bir temel olarak kullanmaktır.",
        "Güvenli olmak sana bu dünyada hiçbir şey kazandırmaz.",
        "Harika bir numara harika bir numaradır, ama bir beceriksiz üzerinde işe yaramaz. Mesele yeteneğe gelir.",
        "Ya evrilirsin, ya da kaybolursun.",
        "Tohum, taşa dikilmiş olmasına rağmen büyümelidir.",
        "Ne kadar zor olursa olsun, göğsünü dik tut, başını yukarıda tut ve üstesinden gel.",
        "Her zaman elinden gelenin en iyisini yap, baskının seni panikletmesine izin verme.",
        "Nasıl veya ne zaman etki yaratacağını asla bilemezsin, örneğin başka biri için ne kadar önemli olabilir.",
        "Yapmak istediğini yapabilmek için yapman gerekeni yap.",
        "Geçinmek için değil, fark yaratmak için çabala.",
        "Bu dünyada kim olursan ol, öyle ol.",
        "Bir düşmanın varsa, onu öğren ve tanı, sadece ona kızma.",
        "Yaşamış en büyük insanlar gibi olmaya çabalıyorum.",
        "Beni diğerlerinden ayıran şey gülünç, hastalıklı bir iş ahlakıdır. Bilirsin, diğerleri uyurken ben çalışıyorum.",
        "Hayat uçurumun kenarında yaşanır.",
        "Gerçekçi olmak, sıradanlığa giden en çok yolculuk edilen yoldur.",
        "İlk adım, yapabileceğini söylemendir.",
        "Dünya sana kim olduğunu söyleyemez, kim olduğunu kendin bulmalı ve iyi ya da kötü orada olmalısın.",
        "Başarısızlıklarını fark etmen gerekecek. Onları kucaklaman ve nasıl üstesinden geleceğini bulman gerekecek.",
        "Babam bana dedi ki: Baştan fiyatını koy. Eğer koyduğun fiyattan daha pahalı olursa, çık oradan.",
        "Eğer tek inanan sen olsaydın, inandığın şeye inanır mıydın?",
        "İnsanların ne düşündüğü umurumda değil, çünkü insanlar düşünmüyor.",
        "Öğrenme yeteneği dışında hiçbir şeyde gerçekten iyi değildim.",
        "Dünyadaki en iyi duygu, sıkı çalışmanın faydalarını ve ödüllerini görmektir.",
        "Hedeflerim o kadar yüksek ki, hiçbir şekilde gevşemeye zamanım yok.",
        "Hayat, başkalarının senin hakkında söyledikleri hakkında endişelenmek için çok kısa.",
        "Her başarılı insanın arkasında bir sürü kıskanç insan vardır.",
        "Hayatından bir şey yapabilirsin, bu sadece azmine bağlı.",
        "Düşmanların mı var? Güzel, bu gerçekten bir şey için ayağa kalktığın anlamına gelir.",
        "Tüm başarı öz-disiplinle başlar, seninle başlar.",
        "Azim ve biraz yetenekle dağları yerinden oynatabilirsin.",
        "Başarısızlık bir seçenek değil, sadece bir adım.",
        "Başarı bir gecede gelmez, her gün bir önceki günden biraz daha iyi olduğunda gelir; hepsi birikir.",
        "Hayat seni zor durumlara soktuğunda 'neden ben' deme, sadece 'dene bakalım' de.",
        "Herhangi bir şeydeki başarı her zaman şuna bağlıdır: odak ve çaba. Ve ikisini de biz kontrol ediyoruz.",
        "Bir keresinde bilge bir adamın dediğini duydum: mükemmel insanlar yoktur, sadece mükemmel niyetler vardır.",
        "Çoğu zaman bilirsiniz, yürümeyi bırakırsınız çünkü dersiniz ki 'bu tepeyi tırmanmaktan yoruldum. Zirveye asla ulaşamayacağım' ve zirveye sadece iki adım kalmıştır.",
        "Kendine meydan oku, büyümeye giden tek yol budur.",
        "Yeteneğin için kredi alamazsın, sadece onu kullandığın için kredi alabilirsin.",
        "Bir kaybı garantilemenin en iyi yolu pes etmektir.",
        "Ya olmasını izleyebilirdim ya da bir parçası olabilirdim.",
        "Bir şey yeterince önemli olduğunda, şanslar senin lehine olmasa bile yaparsın.",
        "Sabah kalkıp geleceğin daha iyi olacağını düşünüyorsan, aydınlık bir gündür, yoksa değildir.",
        "Yumurtalarını tek sepete koymak sorun değil, yeter ki o sepete ne olacağını kontrol et.",
        "Cevabını önceden bildiğin şeyleri yapıyorsan, şirketin yok olur.",
        "Yenilik yapacaksan yanlış anlaşılmaya istekli olmalısın.",
        "Yenilik yapmanın kötü bir zamanı yoktur.",
        "Fırsat yaratmak, başkalarının bakmadığı yere bakmak demektir.",
        "Ter sermayesi, var olan en değerli sermayedir.",
        "Neredeyse her zaman, sıkı çalışmanın ödüllendirildiği bir toplumda yaşıyoruz.",
        "Evren sana mantıklı gelmek zorunda değildir.",
        "Kendi kendine yönlendirilen eğitimden daha büyük bir eğitim yoktur.",
        "Meraklı olan kimse aptal değildir.",
        "İnsan tarihinde cehaleti bilgiden daha iyi olan bir zaman bilmiyorum.",
        "Hiçbir şeyi kişisel almamak için kendini eğit.",
        "Bir adam, gerçekten inanıyorsa istediğini yapabilir, sıkı çalışmaya ve birçok kalp kırıklığına hazır olmalıdır.",
        "Her birimizin fark etmesi gereken şey, niyetimizin her zaman ortaya çıktığıdır.",
        "Gerçekten yaratmak istediğimizi görmezden gelemeyiz.",
        "Durumunu yalnızca sen ve sadece sen değiştirebilirsin.",
        "Zor zamanlara şükret, çünkü seni onlar şekillendirdi.",
        "İlk yüzde bire katılmak için yüzde doksan dokuzun yapmayacağını yapmalısın.",
        "Kendi yolumu yaratırım, dümdüz ve dardı. Şöyle baktım: ya yolumun üzerindeydin ya da yolumdan çekilmiştin.",
        "Hepimizin kendinden şüpheleri var. İnkar etmezsin, ama teslim de olmazsın. Kucaklarsın.",
        "Birçok lider başarısız olur, çünkü o sinire dokunma ya da o teli çalma cesaretleri yoktur.",
        "Pes ettiğin an, başka birinin kazanmasına izin verdiğin andır.",
        "Başarısız olmaktan korkuyorsan, muhtemelen başarısız olacaksın.",
        "Yılgınlığın gerçekten var olmadığını fark ettim, doğru zihin durumundaysan.",
        "Bu, en zorlu zamanların her zaman arkamda ve önümde olacağını kabul ettiğim andır.",
        "Kimse şampiyon olacağını bilmez - oraya ulaşmak için çalışmak zorundasın.",
        "İnancım, şüphenden daha güçlü.",
        "Başarı, her gün yaptığından memnun olmak demektir. Daha iyi bir insan olduğun için gurur duymaktır.",
        "Başarılı olmak istiyorsan, sahip olduğun her bağlantıyı kullanmaya istekli olmalısın.",
        "Yetenek asla yeterli değildir. Birkaç istisna dışında, en iyi oyuncular en çok çalışanlardır.",
        "Pes etme, sıkı çalışmana yardım eden insanlarla arkadaş ol.",
        "Sahip olabileceğin hayatı değil, yaşadığın hayatı kutla.",
        "Yoksul büyüdüm, ama yoksul hayallerim yoktu.",
        "Fark yaratabilecek tek kişi sensin. Hayalin ne olursa olsun, peşinden git.",
        "Sana bir şey oldu diye hayat durmaz.",
        "Hayatta kazanmak da kaybetmek de olacak, asla kabul edilemeyecek olan pes etmektir.",
        "Hayatımda kaç kez reddedildiğimi biliyor musunuz? Bir şeyi başaramayacağımın kaç kez söylendiğini?",
        "Çoğu zaman, en yetenekli insanların o tavrı hiç geliştirmediğini görüyorum. Ve o şekilde kutsanmayanlar en rekabetçi olanlar ve en büyük yüreğe sahip olanlar.",
        "Asla oynama fırsatı bulamayacağımı düşünüyordum, ta ki bir gün buldum, çünkü hazırdım ve fırsat kendini gösterdi.",
        "Sadece rekabeti ve gelişmeye çalışmayı seviyorum.",
        "Çoğu zaman hayatta bir şey olur ve mutlu veya tatmin olmamızdan başkalarını sorumlu tutarız.",
        "Hayatın, ne yaparsan yaparsın öyle olacak.",
        "Biri benim hakkımda kötü bir şey söyledi diye üzülmeyeceğim.",
        "Hayatta kenarda oturamazsın.",
        "Mesajım basit: hayatının kontrolünü ele al.",
        "Takımın liderlerinden biri olduğunda tatil günü yoktur.",
        "Başkalarına güvenme. Birçok insandan harika destek alacaksın, yine de. Ama kimse sana hiçbir şeyi altın tepside sunmayacak.",
        "İşler kendiliğinden düzelmez; dışarı çıkıp onları düzeltmek için sıkı çalışmalısın.",
        "Kazanmak için oynamıyorsan, hiç oynama.",
        "Kendine inanmıyorsan, başka biri neden inansın ki?",
        "Bazen hayattaki en büyük zorluklar, hayatında olan en iyi şeyler olur.",
        "Sadece sıkı çalışmayı seviyorum.",
        "Gerçek rakipler, her zaman kazanmak için oynayanlardir.",
        "Parayı kovalama, hayali kovala.",
        "Uçmak istiyorsan, seni aşağı çeken şeylerden vazgeçmelisin.",
        "Hayal kurmanı istemiyorum, yapmanı istiyorum.",
        "Biri olmak isteyen herkes, o hayali gerçekleştirmek için olabildiğince çok çalışacaktır.",
        "En iyi olma niyetim olduğu gerçeğini hiçbir zaman saklamaya çalışmadım.",
        "Eğer en iyi olduğuna inanmıyorsan, yapabileceğin her şeyi asla başaramazsın.",
        "Bugün, gelecekte tekrar gelip gelmeyeceğini kimsenin bilmediği fırsatlar var.",
        "Sıkı çalışma olmadan yetenek hiçbir şeydir.",
        "İnsanların benden nefret etmesi umurumda değil, çünkü bu beni ileriye itiyor.",
        "Yetenek her şey değildir. Beşikten sahip olabilirsin, ama en iyi olmak için mesleği öğrenmek gerekir.",
        "Kendimden memnun olmak için sonsuz bir öğrenme, gelişme, evrilme ihtiyacı hissediyorum.",
        "Sevgin beni güçlü yapar. Nefretin beni durdurulamaz yapar.",
        "Bir şeyi yeterince seversen her şeyin üstesinden gelebilirsin.",
        "Başarılıyım çünkü başarı için fedakarlık yaptım.",
        "Hırsım her zaman daha iyi ve daha iyi olmaktır.",
        "Erken başlar ve geç kalırım. Gün be gün, yıl be yıl, bir gecede başarılı olmam 17 yıl ve 114 gün sürdü.",
        "Beni mutluluktan alıkoyan kişi bendim.",
        "Basit bir dikkat etme eylemi seni çok uzağa götürebilir.",
        "Gerçeği kitlelerin görüşüyle karıştırma. Bunlar neredeyse hiçbir zaman birbirine benzemez bile.",
        "Yolu bilmekle yolda yürümek arasında fark vardır.",
        "Beni sevmeyen birinin benim hakkımda söyleyeceği şeyler için bütün gece oturup endişelenmek için zamanım yok.",
        "Kim olduğun konusunda tereddütlü olamazsın.",
        "Her zaman üzerinde çalışılacak şeyler vardır, asla orada değilsin.",
        "Her zaman olmak istediğim şey olmak istiyorum: dominant.",
        "Sadece olabileceğimin en iyisi olmaya çalışıyorum ve umarım bu gelmiş geçmiş en iyidir.",
        "Bir zamanlar olduğum kadar iyi olmak istemiyorum, daha iyi olmak istiyorum.",
        "Zihnim en büyük varlığımdır. Oynadığım her turnuvayı kazanmayı bekliyorum.",
        "Duygularını gerçekten kontrol eden adamlar kazanacak.",
        "Ne kadar iyi olursan ol, her zaman daha iyi olabilirsin ve heyecan verici olan da budur.",
        "İnsanlara yardım etmek için önce kendine nasıl yardım edeceğini öğrenmelisin.",
        "Sıkı çalışmanın sonucu olmadan hiçbir şey değerli gelmez.",
        "Hiçbir insanın benden nefret ettirerek ruhumu küçültmesine izin vermeyeceğim.",
        "Bir insanı, onunla birlikte aşağıda kalmadan aşağıda tutamazsın.",
        "İnsanı yapan koşullar değil, karakterdir.",
        "Gücünü kullanmanın iki yolu vardır: biri ezmek, diğeri yükseltmek.",
        "Başarılı olduğumdan çok daha fazla başarısız oldum.",
        "Bugün insanların yapmayacağını yapıyorum ki yarın insanların yapamayacağını başarabileyim.",
        "Kaybetsen bile, dersi kaybetme.",
        "Satılabilecek en kolay şey gerçektir.",
        "Mükemmel zamanı bekleme, sonsuza dek beklersin. Verilen zamanı her zaman değerlendir ve onu mükemmel yap.",
        "Sadece birkaç şeyi harika yapabilirsin ve geri kalan her şeyi bir kenara bırakmalısın.",
        "Hayat kırılgandır. Yarın garanti değildir, o yüzden elinden gelenin hepsini ver.",
        "Kendimi gülünç duruma düşürmekten korkmam.",
        "Beni başarı değil, saygı motive eder.",
        "Tepenin öbür tarafına geçtiğinde, hız kazanmaya başlarsın.",
        "Mükemmellik bir eylem değil, bir alışkanlıktır.",
        "\"F\" almaktan korkuyorsan \"A\" alamazsın.",
        "İyi şeylere ulaşmak için hata yaparsın.",
        "Kahraman, bilinmeyene gönüllü olarak yürüyen kişidir.",
        "Milyonlarca hayatta kalan var. Bir milyon birinci yap.",
        "Asla pes etme, çünkü yarın gelgit neyi getirecek bilemezsin.",
        "Kolay olsaydı herkes yapardı. Onu harika yapan zorluktur.",
        "Yaptığın seçimler konusunda güvende oynuyorsan büyümezsin.",
        "Korktuğum bir şey yapmayı seviyorum.",
        "Süreç en güzel kısımdır.",
        "Gözü kandırmak kolaydır, ama kalbi kandırmak zordur.",
        "Asla çok yukarıda olma, asla çok aşağıda olma. Gün be gün al ve öğrenmeye devam et.",
        "Çaba asla sorgulanmayacak.",
        "Birinin sana fırsat vermesini bekleme: kendin için bir tane yarat.",
        "İnsanlar asla başaramayacağımı söylediklerinde, yapabileceğimi söyleyen bir kişiyi dinledim: kendimi.",
        "Hayallerini kovalamak diye bir şey var, arkalarından yürümek diye değil.",
        "Gerçekten istediğine sahip olmak için, önce gerçekten kim olduğun olmalısın.",
        "Geçmişin seni rahatsız etmesine izin verme. Çünkü şimdi yaptığın gelecekte seni rahatsız edebilir, akıllı ol. Şimdi veya gelecekte yaptığın asla geçmişini maskeleyemez, ama bu geçmişin seni kontrol etmesine izin ver demek değil.",
        "O \"ya eğer\" asla iyileşmeyen bir yaradır.",
        "Kolay olsaydı, değmezdi.",
        "Hiçbir şeyi hak etmezsin, her şeyi kazanırsın.",
        "Mükemmellik ilginç değil, zorlukların üstesinden gelip zirveye çıkmak: işte beni etkileyen bu.",
        "\"Bana acıyın\" olimpiyatlarına katılma; biz o yarışmada yarışmayız.",
        "Bir şeyi istediğinde, onunla birlikte gelen araziyi de kabul edersin, o arazi ne olursa olsun.",
        "Gerçek vizyon, zihnin gözlerinin önündekinden daha güçlü olduğu zamandır.",
        "Bazı olaylar seni ilerletir, bazıları tam tersini yapar - öyle görünür. O terslikler, gelecekte işe yarayacak öğrenme fırsatlarıdır.",
        "Patron olmanın bedelini öde ya da pişmanlığın bedelini öde.",
        "Başkalarının senin hakkındaki görüşü senin gerçekliğin olmak zorunda değil.",
        "Dilediğini alamazsın, çalıştığını alırsın.",
        "Öz-disiplin düşüncelerinin ustalığıyla başlar. Ne düşündüğünü kontrol edemezsen, ne yaptığını kontrol edemezsin. Basitçe, öz-disiplin önce düşünüp sonra hareket etmeni sağlar.",
        "Yenilgi nedir? Eğitimden başka bir şey değil; daha iyi bir şeye giden ilk adım.",
        "Sana ne olduğu değil, ona nasıl tepki verdiğin önemlidir.",
        "Öfkeni kontrol et. Başkalarına karşı öfken varsa, onlar seni kontrol ediyor.",
        "En büyük zorluğun, zihnin en iyi bahaneleri ürettiğinde ortaya çıkmaktır.",
        "Ya disiplinin acısını ya da pişmanlığın acısını yaşayabilirsin. Seçim senin.",
        "Seni fiziksel, entelektüel ve ruhani olarak zayıflatan her şeyi zehir olarak reddet.",
        "Barışta daha çok terle, savaşta daha az kana.",
        "Başlama cesareti ve dayanma disipliniyle, zafer sadece bir zaman meselesi olur.",
        "İyi bir lider, suçlamanın biraz fazlasını ve kredinin biraz azını alan kişidir.",
        "Güçlü ol ama kaba olma. Nazik ol ama zayıf olma. Cesur ol ama zorbalık yapma. Alçakgönüllü ol ama utangaç olma. Gururlu ol ama kibirli olma.",
        "Sabır acıdır, ama meyvesi tatlıdır.",
        "Sabır edilgen değildir, aksine aktiftir. Yoğunlaştırılmış güçtür.",
        "Deneyecek olana imkansız diye bir şey yoktur.",
        "Zeka bilgi depolamak değil, onu nerede bulacağını bilmektir.",
        "Önce bir niyettir. Sonra bir davranış. Sonra bir alışkanlık. Sonra bir uygulama. Sonra ikinci bir doğa. Sonra sadece kim olduğundur.",
        "Ne yapmak istiyorsan, şimdi yap. Sadece bu kadar yarın var.",
        "Yapılamaz diyen insanlar, yapanları bölmemelidir.",
        "Geliştirebileceğinden emin olabileceğin evrenin tek bir köşesi var, o da kendi benliğin.",
        "Aptal, bilge olduğunu düşünür, ama bilge adam kendinin aptal olduğunu bilir.",
        "Acı seni değiştirebilir, ama bu kötü bir değişiklik olmak zorunda değil. O acıyı al ve bilgeliğe dönüştür.",
        "Zaman gerçekten herhangi bir insanın sahip olduğu tek sermayedir ve kaybetmeyi göze alamayacağı tek şeydir.",
        "İnsanlar ne derse desin kendi yolunu takip et.",
        "Bir şey yap. İşe yararsa, daha fazlasını yap. Yaramazsa, başka bir şey yap.",
        "Öğrenmek, zihnin asla tükenmediği, asla korkmadığı ve asla pişman olmadığı tek şeydir.",
        "Kazanan, asla pes etmeyen bir hayalperesttir.",
        "İstediğin için savaşmazsan, kaybettiğin için ağlama.",
        "Kusurlarını kabul ettiğinde, kimse onları sana karşı kullanamaz.",
        "Evren hakkında yeterince şey öğrendiğimizde, her şeyi asla bilemeyeceğimizi kendimize itiraf edeceğiz.",
        "Endişelenmek, borçlu olmadığın bir borcu ödemek gibidir.",
        "Kimseye hiçbir şey öğretemezsin, sadece cevapların zaten içlerinde olduğunu fark ettirirsin.",
        "Düşüncelerin gücü ya hastalığa ya da iyileşmeye neden olabilir.",
        "Bir mucize görmek istiyorsan, mucize ol.",
        "Üç sınıf insan vardır: görenler, gösterildiğinde görenler, görmeyenler.",
        "En büyük korkuların hayal gücün tarafından yaratılır.",
        "İnsanların maruz kaldığı en büyük aldanma, kendi fikirlerinden kaynaklanır.",
        "Tüm olasılıkları tükettiğinde, bunu hatırla: tüketmedin.",
        "Kaderin sana dağıttığı eli sev ve onu kendi elin olarak oyna.",
        "İki kişi her konuda aynı fikirde ise, biri gereksizdir.",
        "En büyük rekabet kendinle olan rekabettir.",
        "Yorulduğumuzda, çoktan yendiğimiz fikirler tarafından saldırıya uğrarız.",
        "Başıma gelen şey değilim. Olmayı seçtiğim şeyim.",
        "Hayatta kalmanın en önemli faktörü ne zeka ne de güçtür, uyum yeteneğidir.",
        "İnanç ve korku, ikisi de göremediğin bir şeye inanmanı ister. Sen seçersin.",
        "Şikayet ederek insanlara ne kadar zayıf olduğunu söylersin.",
        "Sevdiğine kavuşmak için önce nefret ettiğine sabretmelisin.",
        "Her şey aleyhine gidiyormuş gibi göründüğünde, uçağın rüzgara karşı kalktığını hatırla.",
        "Gerçekten kim olduğunu öğrendiğinde korkularına güleceksin.",
        "Huzur daha sakin bir fırtınada değil, daha iyi bir teknede bulunur.",
        "Gerçeği görmezden gelebilirsin, ama gerçeği görmezden gelmenin sonuçlarını görmezden gelemezsin.",
        "Hiçbir insan, asla zorlukla karşılaşmayandan daha mutsuz değildir. Çünkü kendini kanıtlamasına izin verilmez.",
        "Şiddetle uygulanan iyi bir plan, gelecek hafta uygulanan mükemmel bir plandan daha iyidir.",
        "Çalışmak ve düşünmemek boşunadır. Düşünmek ve çalışmamak tehlikelidir.",
        "Korku bir tepkidir. Cesaret bir karardır.",
        "Bağımsızlık çok az kişi içindir; güçlünün ayrıcalığıdır.",
        "Hayatın bir kendin-yap projesi olduğunu anlamak ömrünün yarısını alır.",
        "Rolünü onurla oyna.",
        "Endişe, hayal gücünün kötüye kullanılmasıdır.",
        "Bilgi ve beceri arasındaki köprü pratiktir. Beceri ve ustalık arasındaki köprü zamandır.",
        "Ne kadar çok öğrenirsem, hâlâ ne kadar çok öğrenmem gerektiğini o kadar fark ediyorum.",
        "Kaybetmezsen, zaferlerin tadını çıkaramazsın. Bu yüzden her ikisini de kabul etmeliyim.",
        "Zaferden az, yenilgiden çok öğreniriz.",
        "Saygıyla konuşan ama hazırlıklarını artıran ilerleyecektir. Saldırganca konuşan ve aceleyle ilerleyen geri çekilecektir.",
        "Hayatımız düşüncelerimizin ürünüdür.",
        "Onu zor bir şey olarak tanımlamadıkça, gerçekten zor bir şey yoktur. Aksi takdirde, sadece çözmeye çalıştığın bir sonraki şeydir.",
        "Durum ne olursa olsun, duygularının zekanı bastırmasına asla izin verme.",
        "Olmak istediğin kişi türüne karar ver ve ister yalnız ister toplulukta ona bağlı kal.",
        "Bir şey yanlışsa, yapabiliyorsan düzelt. Ama kendini endişe etmemek için eğit. Endişe hiçbir şeyi düzeltmez.",
        "Hayat iyi kartlar tutmak değil, kötü bir eli iyi oynamaktır.",
        "Büyüklüğün zirvelerine giden yol engebelidir.",
        "Bir insan zevke üstün geldiği gün, acıya da üstün gelecektir.",
        "Sürekli öğren, her zaman öğrenilecek \"bir şey daha\" vardır.",
        "Gül fidanlarının dikenleri olduğundan şikayet edebiliriz ya da diken fidanlarının gülleri olduğuna sevinebiliriz.",
        "Sabırlı ve güçlü ol; bir gün bu acı işine yarayacak.",
        "Başarısızlık, devam eden başarıdır.",
        "Öğrenmeyi bırakan yaşlıdır, ister yirmi ister seksen yaşında olsun.",
        "Zihin tarafından yönetiliyorsan kralsın; beden tarafından yönetiliyorsan kölesin.",
        "Gurur utancın zıttı değil, kaynağıdır. Gerçek alçakgönüllülük, utanca karşı tek panzehirdir.",
        "Kendini geliştirmeye başladığında, yalnızlık ödediğin bedeldir.",
        "Yükseldiğin yükseklikle değil, tırmandığın derinlikle yargılanırsın.",
        "Bir adam, başarısız olmadığı için büyük değildir; başarısızlık onu durdurmadığı için büyüktür.",
        "Vizyonu olmayan bir adam, geleceği olmayan bir adamdır. Geleceği olmayan bir adam, her zaman geçmişine döner.",
        "Hileden başarılı olmaktansa onurla başarısız olmak daha iyidir.",
        "Tüm savaşlar önce zihinde kazanılır ya da kaybedilir.",
        "İnsanın duyguları, zekasindan daha çabuk harekete geçirilir.",
        "İhtiyacı olmayan şeyi alan, kendinden çalar.",
        "Sabredebilen, istediğine sahip olabilir.",
        "Savaşçının yolu ömür boyu sürer ve ustalık çoğu zaman sadece yolda kalmaktır.",
        "Uçurtmalar rüzgarla değil, rüzgara karşı en yükseğe çıkar.",
        "İnsanlar ustalığımı kazanmak için ne kadar çok çalışmam gerektiğini bilselerdi, hiç de harika görünmezdi.",
        "Asla bilinçaltına bir istekte bulunmadan uyumaya gitme.",
        "Olayları nasıl olursa olsunlar hoş karşıla: bu, huzura giden yoldur.",
        "İmkansız görüneni bile uygula.",
        "İki tavşanı kovalayan adam, ikisini de yakalayamaz.",
        "Başaracaksın, ama her zaman başaramayacakmışsın gibi hissedeceksin.",
        "Kolay olduğunda zor olanı planla, küçük olduğunda büyük olanı yap.",
        "Azim yetmez. Kişi acı çeken mi yoksa savaşçı olarak mı devam edeceğine karar vermelidir.",
        "Hayal ettiğin zirvelere ulaşmak için gereken keskinlik ve disiplin seviyesi gerçekten basit, sadece kolay değil.",
        "En büyük düşman dışarıda bulunmaz. Yıkım çoğu zaman içeriden gelir.",
        "Herkes imkansız olduğunu biliyordu, ta ki bilmeyen bir budala gelip yapana kadar.",
        "Güçlü bir adamı zayıflatarak zayıf bir adamı güçlendiremezsin.",
        "Zihniniz üzerinde gücünüz var - dış olaylar üzerinde değil. Bunu anlayın ve güç bulacaksınız.",
        "Elmas, işine sadık kalan bir kömür parçasıdır.",
        "En büyük risk, hiç risk almamaktır.",
        "Problemi doğru tanımlarsan, neredeyse çözümün de olur.",
        "Geçmiş kafanda, gelecek ellerinde.",
        "Hayat oldukça basittir. Bir şeyler yaparsın. Çoğu başarısız olur. Bazıları işe yarar. İşe yarayanın daha fazlasını yaparsın.",
        "Görev duygun, korku atmosferini ve hedefleri erteleme eğilimini gölgede bıraksın.",
        "İstediğin her şey korkunun öbür tarafında.",
        "Disiplin, şimdi istediğin ile en çok istediğin arasında seçim yapmaktır.",
        "Uyum, hayal gücü olmayanın son sığınağıdır.",
        "Elmas, işine yapışan bir kömür parçasıdır.",
        "İnsan için boşa harcanan zamandan daha büyük bir zarar yoktur.",
        "Sahip olduğunu, sahip olmadığını arzulayarak bozma; şu an sahip olduğun şeyin bir zamanlar sadece umut ettiğin şeyler arasında olduğunu hatırla.",
        "Sabır ustası olan, her şeyin ustasıdır.",
        "Asla prensibin önüne tutkuyu koyma, kazansan bile kaybedersin.",
        "Bazı insanlar olmasını ister, bazıları olmasını diler, diğerleri ise gerçekleştirir.",
        "Beklentilerimizin seviyesine yükselmeyiz, eğitimimizin seviyesine düşeriz.",
        "Sabırla acıya katlanmaya istekli olanlardan çok, ölmeye gönüllü olanları bulmak daha kolaydır.",
        "Yarışa katılmazsan podyuma çıkmayı bekleyemezsin.",
        "Düşüp kalkan, hiç denemeyen birinden daha güçlüdür.",
        "Kötü Haber: Herkese \"uyum sağlayamayacaksın\"... İyi Haber: \"Büyükler\" asla sağlayamaz.",
        "Asla yetenekli olmadım, sadece asla pes etmemekte iyiyim.",
        "Mutluluk sorunların yokluğu değil, onlarla başa çıkma yeteneğidir.",
        "Kolayını yaparsan hayatın zor olur.",
        "Geri dönüp başlangıcı değiştiremezsin, ama bulunduğun yerden başlayıp sonunu değiştirebilirsin.",
        "Öğretilenden çok gözlemlenen öğretir.",
        "Hata yapmayanlar, hata yapanlar için çalışır.",
        "Yeni bir fikir, anında sonuçlarına göre yargılanmamalıdır.",
        "Yapman gereken şeye asla hazır olmazsın. Sadece yaparsın. Bu seni hazır kılar.",
        "Risk al: kazanırsan mutlu olursun; kaybedersen bilge olursun.",
        "Ayrıcalıklarını ilkelerinin üstünde tutan bir halk, yakında ikisini de kaybeder.",
        "Anlam ve başarıya giden en hızlı yol: bir şey seç ve tüm benliğinle ona ver.",
        "Yeniden başlamaktan korkma. Bu sefer sıfırdan başlamıyorsun. Deneyimden başlıyorsun.",
        "Hemcinsinden üstün olmakta asalet yoktur; gerçek asalet, önceki benliğinden üstün olmaktır.",
        "Önce kendine saygı kazanırsan, herkesin saygısını kazanırsın.",
        "Olmak istediğin kişinin bir vizyonunu oluştur ve sonra sanki zaten gerçekmiş gibi o resmin içinde yaşa.",
        "Mükemmelliğin bedeli disiplindir. Vasatlığın bedeli hayal kırıklığıdır.",
        "Zorluklar bedeni emek güçlendirdiği gibi zihni güçlendirir.",
        "Hiçbir eylemde bulunmadığın alanlarda ilerleme kaydetmeyi bekleyemezsin.",
        "Hiçbir kaygı, olacak olan herhangi bir şeyde bir fark yaratmaz.",
        "Bana ortalama yetenekli ama olağanüstü arzulu bir adam göster, sana her seferinde bir kazanan göstereyim.",
        "Başarıya ulaşmanın en hızlı yolu şimdi başlamak ve yol boyunca çözmektir.",
        "İnsanlar geleceklerine karar vermezler, alışkanlıklarına karar verirler ve alışkanlıkları geleceklerini belirler.",
        "Çocuklarına geç öğrendiğin şeyleri erken öğret.",
        "Herhangi bir disiplinde yılda 100 saat harcarsan (ki bu günde sadece 18 dakikadır) o disiplinde dünyanın %95'inden daha iyi olursun.",
        "Görev, kimsenin henüz görmediğini görmek değil; herkesin gördüğü hakkında kimsenin henüz düşünmediğini düşünmektir.",
        "Her sürtünmeden rahatsız olursan, aynan nasıl cilalanacak?",
        "Korku, ancak zihnin izin verdiği kadar derindir.",
        "Zorluk, dehayı uyandıran şeydir.",
        "Işık vermesi gereken, yanmaya katlanmalıdır.",
        "Başarının, hayatta ulaşılan konumla değil, başarılı olmaya çalışırken aşılan engellerle ölçülmesi gerektiğini öğrendim.",
        "Konfor en kötü bağımlılıktır.",
        "Dikkatini ne verirsen o olursun.",
        "Koşullar insanı yaratmaz, sadece onu kendisine gösterir.",
        "İyi bir adamın nasıl olması gerektiğini tartışarak daha fazla zaman harcama. Biri ol.",
        "Dünyayı hareket ettirmek isteyen, önce kendini hareket ettirsin.",
        "Uyaran ile tepki arasında bir boşluk vardır. O boşlukta tepkimizi seçme gücümüz vardır. Tepkimizde büyümemiz ve özgürlüğümüz yatar.",
        "Kendin dışında seni daha iyi, daha güçlü, daha zengin, daha hızlı veya daha akıllı yapabilecek hiçbir şey yoktur. Her şey içeridedir. Her şey var. Kendin dışında hiçbir şey arama.",
        "Başkalarına hoşgörülü, kendine katı ol.",
        "İki şey seni tanımlar: Hiçbir şeyin olmadığındaki sabrın ve her şeyin olduğundaki tavrın.",
        "Bir sabah uyanıp kelebek olmazsın.",
        "Dayanıklılık, bırakmanın en çekici göründüğü anda tutunabilme yeteneğidir.",
        "Eylem için riskler ve maliyetler vardır. Ama bunlar, rahat eylemsizliğin uzun vadeli risklerinden çok daha azdır.",
        "Büyük şeyler başarmak için iki şey gerekir: bir plan ve yeterli olmayan zaman.",
        "Şüphe ancak eylemle giderilebilir.",
        "Eylemlerin başkalarına daha fazla hayal kurmaya, öğrenmeye, yapmaya ve olmaya ilham veriyorsa, sen bir lidersin.",
        "Mesele kusursuz bir sicile sahip olmak değil. Sicilindeki kusurlardan ders çıkarmaktır.",
        "Yeni bir şeyde kötü olmaya yetecek kadar cesur ol.",
        "Uyandığından daha akıllı yat.",
        "Yavaş başarı karakter inşa eder, hızlı başarı ego inşa eder.",
        "Birisi sendeleyip yolunu kaybetti diye sonsuza dek kaybolduğu anlamına gelmez.",
        "Ama yaralarımıza sonsuza dek oturup bakamayız.",
        "Ve artık mükemmel olmak zorunda olmadığına göre, iyi olabilirsin.",
        "Başarı, temellerin acımasızca uygulanmasından gelir.",
        "Bir şeyi basit yapmak çok zor iş gerektirir.",
        "Herkes dünyayı değiştirmeyi düşünür, ama kimse kendini değiştirmeyi düşünmez.",
        "Dar kafalılar, sanatın kaşıkla ağızlarına verilmesine ihtiyaç duyar.",
        "Zamanı öldürmek yerine bir şey yap. Çünkü zaman seni öldürüyor.",
        "Her kararın vizyonunla uyumlu olsun.",
        "Ortalamanın üstünde bir şey yapmak istiyorsan, dışlanma korkusuna boyun eğemezsin.",
        "Önemli olan, ateşin içinden ne kadar iyi geçtiğindir.",
        "Tamamen farklı bir hayattan sadece bir karar uzaktasın.",
        "Yarın için yaşıyorsan, her zaman bir gün geride kalacaksın.",
        "Kendinden en iyi şekilde yararlan, çünkü sahip olduğun tek şey bu.",
        "Zihin kör olduğunda gözler işe yaramaz.",
        "Uzun vadede insanlar sadece nişan aldıkları şeye isabet ettirir. Bu yüzden, hemen başarısız olsalar bile, yüksek bir şeyi nişan almaları daha iyidir.",
        "Yaşamak için bir nedeni olan, neredeyse her nasıla katlanabilir.",
        "İnsanlar ikiye ayrılabilir: ileri gidip bir şeyler başaran ve arkadan gelip eleştiren.",
        "Kötü bir tutum, patlak bir lastik gibidir. Değiştirene kadar hiçbir yere gidemezsin.",
        "Kendi kanatlarıyla uçan hiçbir kuş çok yükseğe uçmaz.",
        "Sorunu çöz ya da sorundan ayrıl. Sorunla yaşama.",
        "Ruh haline göre değil, ilkelerine göre hareket et.",
        "Hiçbir şeye bağlanmayanlar her şeyle dikkatini dağıtır.",
        "Olduğumuzdan daha iyi olmaya çabaladığımızda, etrafımızdaki her şey de daha iyi olur.",
        "Yaşayabileceğinden daha azına razı olmakta tutkuya yer yoktur.",
        "Yaratıcı bir insan, başkalarını yenme arzusuyla değil, başarma arzusuyla motive olur.",
        "Hayat, asla gerçekleşmeyen bir şey için uzun bir hazırlıktır.",
        "Artık insanların ne söylediğini dinlemiyorum, sadece ne yaptıklarını izliyorum. Davranış asla yalan söylemez.",
        "Zeki bireyler her şeyden ve herkesten öğrenir; sıradan insanlar deneyimlerinden. Aptallar zaten tüm cevaplara sahiptir.",
        "İlk kural, huzursuz olmayan bir ruhu korumaktır. İkincisi, şeylerin yüzüne bakmak ve onları olduğu gibi tanımaktır.",
        "Daha ağır kaldırmak her zaman bir mücadeledir.",
        "Acı çekmekten korkan adam, korktuğu şeyden zaten acı çekiyordur.",
        "Bir adam hangi limana yelken açacağını bilmiyorsa, hiçbir rüzgar lehine değildir.",
        "Her zaman yapamadığım şeyi yapıyorum ki nasıl yapılacağını öğreneyim.",
        "Başarısızlık üzerine inşa edersin. Onu bir basamak taşı olarak kullanırsın. Geçmişin kapısını kapat. Hataları unutmaya çalışma, ama üzerinde durma. Hiçbir enerjini, zamanını ya da alanını ona verme.",
        "Karakterinin içeriği senin seçimin. Gün be gün, neyi seçtiğin, ne düşündüğün ve ne yaptığın, kim olduğundur.",
        "Korkaklar asla başlamadı ve zayıflar yolda öldü.",
        "Sabah kalktığında, hayatta olmanın, nefes almanın, düşünmenin, keyfini çıkarmanın, sevmenin ne kadar değerli bir ayrıcalık olduğunu düşün.",
        "Başarının sırrı amaç odağıdır.",
        "Cehaletten daha tehlikeli tek şey kibirdir.",
        "Tekrar tekrar yaptığımız şey biziz. Öyleyse mükemmellik bir eylem değil, bir alışkanlıktır.",
        "Hayatı beklerken, hayat geçer.",
        "Başarı, her gün uygulanan birkaç basit disiplinden başka bir şey değildir.",
        "Ne kadar çok bilirse, cehaletinin o kadar farkında olacaktır.",
        "Eyleme engel olan şey eylemi ilerletir. Yolda duran şey yol olur.",
        "En büyük zayıflığımız pes etmektir. Başarılı olmanın en kesin yolu, her zaman bir kez daha denemektir.",
        "Bir mücevher sürtünme olmadan cilalanmaz, bir insan da denemeler olmadan mükemmelleştirilemez.",
        "Değerin sahip olduğun şeyde değil, olduğun şeyde yatar.",
        "Haksızlık yapan, haksızlığa uğrayandan daha talihsizdir.",
        "Dürüstlüğün en doğru sınavlarından biri, taviz vermeyi kesinlikle reddetmesidir.",
        "Tanrı, kollarını kavuşturan olanlara hiçbir şey vermez.",
        "Nasıl düşüneceğini bilmek, seni sadece ne düşüneceğini bilenlerden çok daha güçlü kılar.",
        "Yapabileceğinden daha azını olmayı planlıyorsan, muhtemelen hayatının tüm günlerinde mutsuz olacaksın.",
        "Zorluktan daha iyi bir şey yoktur. Her yenilgi, her kalp kırıklığı, her kayıp, bir dahaki sefere performansını nasıl artıracağının tohumunu taşır.",
        "Nefreti sevmeyi öğren. Kucakla. Keyfini çıkar. Hak ettin. Herkesin kendi fikrine hakkı var ve herkesin senin hakkında bir fikri olmalı. Nefret edenler iyi bir sorundur. Kimse iyilerden nefret etmez. Büyüklerden nefret ederler.",
        "Her şeyi kontrol edemeyeceğini kabul et. Kontrolün altındaki her şeyin sorumluluğunu kabul et. İç ve dış engellerin var olduğunu kabul et. Hepsini aşmak için donanımlı olduğunu kabul et.",
        "Deneyim en zor öğretmen türüdür. Önce sınav verir, sonra dersi öğretir.",
        "Yıllarla değil, hasarla olgunlaşırız.",
        "Depresyondaysan geçmişte yaşıyorsun. Kaygılıysan gelecekte yaşıyorsun. Huzurluysan şimdi'de yaşıyorsun.",
        "Dünyayı değiştiremeyeceğimizi düşünüyorsan, bu sadece onu değiştirecek olanlardan biri olmadığın anlamına gelir.",
        "Belki de mesele mutlu bir son değildir. Belki mesele hikayenin kendisidir.",
        "Bazı insanlar gittikleri her yere neşe getirir, bazıları ise gittiklerinde.",
        "Sürekli gözlemle ki her şey değişimle gerçekleşir ve evrenin doğasının değişmekten daha çok hiçbir şeyi sevmediğini düşünmeye alış.",
        "Çok iyi olmak ilgi çekici olmamaya meyillidir.",
        "Çoğu zaman düşünce rahatsızlığı olmadan görüş rahatlığının keyfini çıkarırız.",
        "Düşünmeden çalışmak boşunadır; çalışmadan düşünmek tehlikelidir.",
        "İnançlı bir adam, sadece fikirleri olan yüz kişiyi ezer.",
        "Bilge adamlar sustuğunda aptallar çoğalır.",
        "Her sistemi revize etmeye, her yöntemi atmaya, işin başarısı gerektiriyorsa her teoriyi terk etmeye hazır ol.",
        "Başkalarının gelişmesine ve hayatta başarılı olmasına yardım etmek başlı başına bir ödüldür ve yalnızca karşılığında hiçbir şey beklenmediğinde değeri vardır.",
        "Şimdi sahip olmadığını düşünme zamanı değil. Elindekiyle ne yapabileceğini düşün.",
        "Devam eden bir iş olduğumu söylerdim, ama bu bir gün devam eden bir iş olmayacağımı ima ederdi.",
        "Pes etme. Normalde kapıyı açan, anahtarlıktaki son anahtardır.",
        "Hayat, düşünenler için komedi, hissedenler için trajedidir.",
        "İncelik, birine cehenneme gitmesini öyle bir şekilde söyleme yeteneğidir ki, yolculuğu dört gözle bekler.",
        "Başkasının yaptığı haksızlığı, haksızlığın doğduğu yerde bırak.",
        "Tüm hayatını bir anda hayal ederek kendini rahatsız etme. Her zaman ne kadar acı çekebileceğini ve kaç tane olabileceğini düşünme.",
        "Her seferinde her şeyi bildiğimi düşündüğümde, \"her şeyin\" sandığımdan biraz daha hacimli olduğu ortaya çıkıyor.",
        "Aptallık ile deha arasındaki fark, dehanın sınırlarının olmasıdır.",
        "Bir bahçede savaşçı olmak, bir savaşta bahçıvan olmaktan iyidir.",
        "Büyük başarı her zaman büyük başarısızlık riskiyle gelir.",
        "Başarı merak, konsantrasyon, azim ve öz-eleştiriden gelir.",
        "Bir düşünceyi kabul etmeden eğlendirebilmek, eğitimli bir zihnin işaretidir.",
        "10.000 kişinin görüşü, hiçbiri konuyu bilmiyorsa değersizdir.",
        "Kontrolümüz dışındaki şeylere ne kadar değer verirsek, o kadar az kontrolümüz olur.",
        "Yolculuklar yap. Dene. Başka bir şey yok.",
        "Kökenler asla başarının önünde engel olmamalı. Hayatta mütevazı bir başlangıç, engelden çok yardımcı olabilir.",
        "Bir başkasının eksikliğinin seni eksik bırakmasına izin verme.",
        "Kıskançlığımız her zaman kıskandığımızın mutluluğundan daha uzun sürer.",
        "Hiçlikten hiçbir şey çıkmaz.",
        "Zayıf insanlar intikam alır. Güçlü insanlar affeder. Zeki insanlar görmezden gelir.",
        "Rüzgarı kontrol etmiyorum; sadece onu inceliyorum.",
        "Onur güç kazanmayabilir, ama saygı kazanır. Ve saygı güç kazandırır.",
        "Son silah beyindir, geri kalan her şey tamamlayıcıdır.",
        "Kolayca pes etme eğilimini yenemezsen, hayatın hiçbir şeye yol açmaz.",
        "Antrenman, yeri süpürmek gibidir. Bir kez yapmış olmamız, yerin sonsuza dek temiz olduğu anlamına gelmez.",
        "Bizi kızdıran, bize zorluk yaratan biziz, yani fikirlerimizdir. Mesela hakaret edilmek ne demektir? Bir kayanın yanına dur ve onu hakaret et, ne başardın? Eğer birisi hakaret karşısında kaya gibi duruyorsa, hakaret edenin küfründen ne kazancı var?",
        "Amaç yokluğunda hayat, hiçbir yere varmayan sonsuz bir yolculuk olur.",
        "Yalnızca ölüler savaşın sonunu gördü.",
        "Önlemek, tedavi etmekten iyidir.",
        "Zorla öğretilen hiçbir şey ruhta kalmaz.",
        "Hayatında var olan her şey iki şey yüzünden var: yaptığın bir şey ya da yapmadığın bir şey.",
        "Etiği olmayan bir adam, bu dünyaya salıverilmiş vahşi bir hayvandır.",
        "Düşünmek zordur, bu yüzden çoğu insan yargılar.",
        "İrade gücünü bulamazsın, onu yaratırsın.",
        "Mutlu kelimesi, üzüntüyle dengelenmeseydi anlamını yitirirdi.",
        "Kolay bir hayat için dua etme. Zor bir hayata dayanacak güç için dua et.",
        "Olabileceğin her şey değilsin ve bunu biliyorsun.",
        "Hayatta kalmakla meşgulken yaşamayı hatırla.",
        "Planlar hiçbir şeydir, planlama her şeydir.",
        "Bir saatini boşa harcamaya cesaret eden bir adam, hayatın değerini keşfetmemiştir.",
        "Kim olduğuna karar vermeli ve dünyayı seninle başa çıkmaya zorlamalısın, senin hakkındaki fikriyle değil.",
        "Yaşama sanatı, danstan çok güreşe benzer; kazalara ve öngörülmeyenlere karşı hazır durur ve düşmeye meyilli değildir.",
        "Yaşlandıkça, insanların ne söylediğine daha az dikkat ediyorum. Sadece ne yaptıklarını izliyorum.",
        "Yardım istemektense kemerimi sıkarım.",
        "Kimse senin gibi yapılmamış, kendini sen tasarladın.",
        "Hiçbir erkeğin fiziksel eğitim konusunda amatör olma hakkı yoktur. Bir erkeğin, vücudunun yetenekli olduğu güzelliği ve gücü görmeden yaşlanması utanç vericidir.",
        "Bir insan sakin bir zihne ne kadar yaklaşırsa, güce o kadar yaklaşır.",
        "İşte gelecekte hatırlanacak bir kural, herhangi bir şey seni acı hissettirmeye teşvik ettiğinde: \"Bu talihsizlik değil\" ama \"Buna layıkıyla katlanmak iyi talih.\"",
        "Bir şeyde iyi olduğunda herkese söylersin. Bir şeyde harika olduğunda, onlar sana söyler.",
        "Önce seni görmezden gelirler. Sonra seninle alay ederler. Sonra sana saldırır ve seni yakmak isterler. Sonra sana anıtlar dikerler.",
        "Özgürlük sorumluluk demektir. Çoğu insanın ondan korkmasının sebebi budur.",
        "Doğruyu söylersen, hiçbir şeyi hatırlamak zorunda kalmazsın.",
        "Devam edersen, zamanın gelecek.",
        "Bir insanın korkması gereken ölüm değil, asla yaşamaya başlamamaktır.",
        "Bugünün prosedürleri yarının sonuçlarıdır. Bugünün prosedürlerine aşık olabilirsen, yarının sonuçlarını seveceksin.",
        "İnsanlığın tüm sorunları, insanın bir odada sessizce oturamamasından kaynaklanır.",
        "Gelecek seni asla rahatsız etmesin. Eğer gerekirse, bugün seni şimdiki zamana karşı silahlandıran aynı akıl silahlarıyla onunla yüzleşeceksin.",
        "İnsan yaş ile değil; acı, başarısızlık, reddedilme, kayıp, saygısızlık ve kalp kırıklığı ile olgunlaşır.",
        "Hayatta taktığımız zincirleri biz kendimiz döveriz.",
        "Bir şeyi üst düzeyde yapmak için, takıntı olması gerekir.",
        "Gelişmek istiyorsan, dışsal şeyler konusunda aptal ve budala sanılmaya razı ol.",
        "Şiddet, beceriksizlerin son sığınağıdır.",
        "Korku tıpkı ateş gibidir, nasıl kullanacağını bilirsen faydalı olabilir. Bilmezsen, yanarsın.",
        "Büyük başarı elde etmek için büyük başarısızlığa hazır olmalısın. Her ikisini de yapamazsan, sorunun var demektir.",
        "Hep birinin bizi \"sebepsiz yere\" sevmediğinden bahsederiz, ama insanlar seni \"sebepsiz yere\" de severler. Bu yüzden iki tarafa da çok fazla önem verme.",
        "Korkaklar ölümlerinden önce defalarca ölür; yürekli olan ölümü yalnızca bir kez tadar.",
        "Karar verebilmekten daha zor ve dolayısıyla daha değerli hiçbir şey yoktur.",
        "Zaferle böbürlenmeden, yenilgiyle kırılmadan, her şey sessizken dikkati elden bırakmadan ya da tehlike yaklaştığında korkmadan tek bir yolda yürü.",
        "Ruh, düşüncelerinin rengiyle boyanır.",
        "Daha hafif bir yük istemem. Daha geniş omuzlar isterim.",
        "Kendinle pazarlık yapma. Kendine talimat ver.",
        "Hem güçlü karakter hem de kolay hayat isteyemezsin.",
        "Cesaret, devam edecek güce sahip olmak değil - güç olmadığında devam etmektir.",
        "Hayat sana olmaz, seninle birlikte olur.",
        "Kazanma iradesi olmadan savaşa girmek ölümcüldür.",
        "Ne kadar güçlü olduğunu, güçlü olmak tek seçeneğin olana kadar asla bilemezsin.",
        "Herkesi memnun edemezsin, bazen hareket etmeli ve herkesin tepki vermesine izin vermelisin.",
        "\"Eğer\" diye bir mesele yoktur, mesele sadece ne zaman.. görev konusunda kararlı olduğunda.",
        "Ne kadar bekleyeceksin kendinden en iyisini talep etmek için?",
        "Dünya sana konfor vaat ediyor, ama sen konfor için yaratılmadın. Büyüklük için yaratıldın.",
        "Dürüstlük hızlı bir yol değildir, ama kesin bir yoldur.",
        "Kendi en büyük hayranın, kendi en büyük inananın ol ve sırtına yükle, ağırlığı taşı.",
        "Önce kendine ne olmak istediğini söyle; sonra yapman gerekeni yap.",
        "Teknolojinin insan etkileşimimizi geçeceği günden korkuyorum. Dünya bir aptallar nesline sahip olacak.",
        "Neye katlandığın değil, nasıl katlandığın önemlidir.",
        "Yaralanma hissini reddet ve yaralanmanın kendisi kaybolur.",
        "Küçük planlar yapma. İnsanların kanını kaynatacak sihirleri yoktur ve muhtemelen kendileri de gerçekleşmeyecektir. Büyük planlar yap; umut ve çalışmayla yükseği hedefle, asil, mantıklı bir diyagram bir kez kaydedildiğinde asla ölmeyeceğini, biz gittikten sonra bile giderek artan bir ısrarla kendini ortaya koyan yaşayan bir şey olacağını hatırla.",
        "Zorluklar çoğu zaman sıradan insanları olağanüstü bir kadere hazırlar.",
        "Bir şeyleri değiştirmek istediğinde herkesi memnun edemezsin. Herkesi memnun ediyorsan, yeterince ilerleme kaydetmiyorsun demektir.",
        "Kendinle pazarlık yapma, kendine talimat ver.",
        "Başarı nihai değildir, başarısızlık ölümcül değildir: önemli olan devam etme cesaretidir.",
        "Doğru değilse yapma; doğru değilse söyleme.",
        "Sözde zevkler, belirli bir sınırı aştığında cezadan başka bir şey değildir.",
        "İstediğin şey için fedakarlık yapmazsan, istediğin şey fedakarlık olur.",
        "En büyük düşmanın kontrol edilmemiş zihnindır.",
        "Asla savaşmak zorunda kalmamak için savaşmayı öğren.",
        "Bir insan derin bir anlam duygusu bulamadığında, kendini zevkle oyalar.",
        "Bu kötü dünyada hiçbir şey kalıcı değildir, sorunlarımız bile.",
        "Senin hakkında yanılmalarına izin ver. Onlara kanıtlayacak bir şeyin yok.",
        "Bugünün geçmişten farklı olmasını istiyorsan, geçmişi incele.",
        "Mutlu bir hayat yaşamak istiyorsan, onu insanlara veya nesnelere değil, bir hedefe bağla.",
        "Sır diye bir şey yoktur, sadece keşfettiğin bilgi ve henüz keşfetmediğin bilgi vardır.",
        "Harekete geçmek için motivasyona ihtiyacın var. Neye göre hareket edeceğini bilmek için bilgiye ihtiyacın var. Bu motive edilmiş eylemleri düzgün yönlendirecek istihbaratı elde etmek için merak gerekir. Yani meraklı ol.",
        "Kazanan, bir kez daha deneyen bir kaybedendir.",
        "Bedene sıkı davranırız ki zihne itaatsizlik etmesin.",
        "İstekliler kader tarafından yönlendirilir, isteksizler sürüklenir.",
        "Ölümden korkan adam, yaşayan bir adama yakışır hiçbir şey yapmayacaktır.",
        "Bir komutan, barışa öyle güvenmez ki savaşa hazırlanmayı ihmal etsin.",
        "Korkma. Başaracaksın, ama her zaman başaramayacakmışsın gibi hissedeceksin.",
        "Tutarlılık kulağa sıkıcı gelebilir, ama harika olmanın başka ne olacağını düşünüyordun? Şans mı?",
        "Yüzünü her zaman güneşe dön, gölgeler arkanda kalacaktır.",
        "Yönetmeyi reddetmenin en ağır cezası, kendinden aşağı biri tarafından yönetilmektir.",
        "İçini kaz. İçeride iyiliğin kaynağı var; ve eğer kazarsan, her zaman fışkırmaya hazırdır.",
        "Ne yaptığınsın, ne yapacağını söylediğin değil.",
        "Kendi yolunda yanlış gitmek, başkasının yolunda doğru gitmekten iyidir.",
        "Büyük bir adam kendine karşı serttir, zayıf bir adam başkalarına karşı serttir.",
        "Kendini sevmek, ömür boyu sürecek bir aşkın başlangıcıdır.",
        "Başkalarının ne düşündüğünü önemse, her zaman onların mahkumu olursun.",
        "İnsan gerçek sorunlardan çok, gerçek sorunlar hakkındaki hayali kaygılarından endişelenir.",
        "Mutlu adam, durumu ne olursa olsun mevcut durumundan memnun olandır.",
        "İlk ve en büyük zafer, kendini yenmektir.",
        "Kendimi kontrol etmek için önce kendimi kabul etmeliyim, doğama karşı değil doğamla giderek.",
        "İnsanlar görsün, bilsin; yaşaması gerektiği gibi yaşayan gerçek bir adam.",
        "Kendine itaat edemeyen, komuta edilecektir.",
        "Bir şeyden korktuğunda, onun hakkında olabildiğince çok şey öğren. Bilgi korkuyu yener.",
        "Her zaman benim dünyaya karşı olduğumu düşünürdüm ve sonra bir gün bunun sadece bana karşı ben olduğunu fark ettim.",
        "Amacı olmayan bir adam, kendini zevkle oyalar.",
        "Herkesin \"anlayamayacağını\" kabul etmek zor.. ama bu yüzden herkes için değil. Bu bir \"sen\" meselesi.",
        "Zorluk ne kadar büyükse, onu aşmanın şerefi de o kadar büyüktür.",
        "Kelebeğin güzelliğine hayranız, ama nadiren o güzelliğe ulaşmak için geçirdiği değişimleri kabul ederiz.",
        "Düşmem gerekiyorsa düşeyim. Olmakta olduğum kişi beni tutacak.",
        "Her şeyi affeden bir adamın arkasında, kendi günahlarının ağırlığını bilen bir adam vardır.",
        "Acıdan kaçma girişimi daha fazla acı yaratır.",
        "Gerçek gelişme konfora saygı göstermez.",
        "Görebildiğimiz kadarıyla, insan varlığının tek amacı salt var olmanın karanlığında bir anlam ışığı yakmaktır.",
        "Tohumu ektiğin gün, meyvesini yediğin gün değildir.",
        "Gerçek, insanların çoğunluğu tarafından inanılıp inanılmadığı için değişmez.",
        "Parlak zırhı olan bir şövalyenin kanıtlanmış bir değeri yoktur. Bana, insanlığın düşükleriyle yaşanmış savaşlardan yıpranmış zırhı olan, savaş görmüş bir şövalye verin.",
        "Zekanın ölçüsü değişebilme yeteneğidir.",
        "Açlık olmadan hasat olmaz.",
        "Zihni yoldan çıkaran, zihnin ta kendisidir. Zihin konusunda dikkatsiz olma.",
        "Kendini bir karaktere dönüştüremezsin; onu çekiçle dövüp şekillendirmelisin.",
        "Her şey yoluna girmeden önce çok şey ters gidecek.",
        "Yalnızca şimdiyi yaşıyoruz. Geri kalan her şey ya geçmiştir ya da bilinmezdir.",
        "Öfken için cezalandırılmayacaksın, öfken tarafından cezalandırılacaksın.",
        "Suyu okuyarak yüzmeyi öğrenemezsin.",
        "En zor tercihler en güçlü iradeleri gerektirir.",
        "Her şeyden önce, kendine yalan söyleme.",
        "Bedenin neredeyse her şeyin üstesinden gelebilir; ikna etmen gereken zihindir.",
        "Hayat birinci şahıs türündendir. Öyle davran.",
        "İyi liderler mazeret üretmez. Bunun yerine, işi halletmenin bir yolunu bulur.",
        "Başkalarından daha uzun sürdüğü için başarısız olduğun anlamına gelmez.",
        "Kendini ne kadar çok tanırsan, başkalarının onayına o kadar az ihtiyaç duyarsın.",
        "Kendini tanımak, tüm bilgeliğin başlangıcıdır.",
        "Önemli olan bir adamın boyutu değil, yüreğinin boyutudur.",
        "Gözyaşları olmadan kademe atlaman pek mümkün değil.",
        "Elindeki sabana ile tarla sürersin.",
    ]
}
