// QuotesLang_id.swift
// Spike AI — Bundled quote translations (Indonesian)
import Foundation
enum QuotesLang_id {
    static let quotes: [String] = [
        "Apa pun yang kamu pegang dalam pikiranmu secara konsisten adalah persis apa yang akan kamu alami dalam hidup.",
        "Kita membidik di atas sasaran, untuk mengenai sasaran.",
        "Hal terburuk yang bisa terjadi pada diriku adalah menjadi sama seperti orang lain, aku benci itu.",
        "Hanya mereka yang berani melangkah terlalu jauh yang mungkin bisa mengetahui seberapa jauh seseorang bisa melangkah.",
        "Melompatlah dan jaring akan muncul.",
        "Kapal di pelabuhan itu aman, tetapi bukan untuk itu kapal dibuat.",
        "Jangan khawatir tentang kegagalan, khawatirkan kesempatan yang kamu lewatkan ketika kamu bahkan tidak mencoba.",
        "Mereka yang berani gagal total bisa meraih pencapaian besar.",
        "Cara untuk memulai adalah berhenti bicara dan mulai bertindak.",
        "Kita mungkin menghadapi banyak kekalahan, tetapi kita tidak boleh terkalahkan.",
        "Ukuran sejati seorang manusia adalah bagaimana dia memperlakukan seseorang yang sama sekali tidak bisa memberinya keuntungan.",
        "Kamu harus berhati-hati jika kamu tidak tahu kemana tujuanmu, karena kamu mungkin tidak akan sampai di sana.",
        "Kamu harus mengharapkan hal-hal besar dari dirimu sendiri sebelum kamu bisa melakukannya.",
        "Jangan pernah biarkan keputusan masa lalumu menentukan hasil masa depanmu.",
        "Jalan pintas membuat penundaan yang panjang.",
        "Tidak ada yang bisa memberikan tujuanmu. Ini adalah perjalananmu.",
        "Dunia adalah apa yang kamu pikirkan tentangnya, jadi pikirkanlah secara berbeda dan duniamu akan berubah.",
        "Masa depan milik mereka yang mempersiapkannya, hari ini.",
        "Jangan menyerahkan apa yang paling kamu inginkan demi apa yang kamu inginkan sekarang.",
        "Jangan ceritakan betapa berbakatnya kamu, ceritakan betapa kerasnya kamu bekerja.",
        "Cara kamu berpikir saat kalah menentukan berapa lama sampai kamu menang.",
        "Setiap kali seseorang memutuskan bahwa kesuksesan telah tercapai, kemajuan berhenti.",
        "Tidak ada masalah yang bisa bertahan dari serangan pemikiran yang berkelanjutan.",
        "Keberuntungan adalah ketika sebuah kesempatan datang dan kamu siap menghadapinya.",
        "Rahasia untuk maju adalah memulai.",
        "Waktu terbaik untuk menanam pohon adalah 20 tahun yang lalu. Waktu terbaik kedua adalah sekarang.",
        "Sulit untuk mengalahkan seseorang yang tidak pernah menyerah.",
        "Tulislah. Rekam. Terbitkan. Rajut, tumis. Apa pun, berkarya!",
        "Apa pun dirimu, jadilah yang terbaik.",
        "Kebahagiaan bukanlah sesuatu yang sudah jadi, ia datang dari tindakanmu sendiri.",
        "Orang pintar belajar dari segalanya dan semua orang.",
        "Mustahil hanyalah sebuah pendapat.",
        "Hasratmu sedang menunggu keberanianmu untuk menyusul.",
        "Orang yang bertanya-tanya apakah gelas setengah kosong atau setengah penuh melewatkan intinya. Gelas itu bisa diisi ulang.",
        "Suatu hari atau hari pertama; kamu yang memutuskan.",
        "Hal-hal mungkin datang kepada mereka yang menunggu, tetapi hanya sisa dari mereka yang berjuang.",
        "Segalanya datang kepada mereka yang bekerja keras sambil menunggu.",
        "Bekerjalah seolah-olah ada seseorang yang bekerja 24 jam sehari untuk merebutnya darimu.",
        "Tidak ada yang pernah membuat perbedaan dengan menjadi sama seperti orang lain.",
        "Kamu akan punya waktu-waktu buruk, tapi itu selalu membangunkanmu pada hal-hal baik yang tidak kamu perhatikan.",
        "Jadilah versi terbaik dari dirimu sendiri, bukan versi kedua dari orang lain.",
        "Belajarlah dari kesalahan orang lain. Kamu tidak bisa hidup cukup lama untuk melakukan semuanya sendiri.",
        "Jika kamu lelah, maka lakukanlah dalam keadaan lelah.",
        "Seorang pria tidak selesai ketika dia kalah, dia selesai ketika dia menyerah.",
        "Dunia diubah oleh teladanmu, bukan oleh pendapatmu.",
        "Hidup itu seperti mengendarai sepeda. Untuk menjaga keseimbangan kamu harus terus bergerak.",
        "Berpikir tentang kehidupan; tidak ada rasa bersalah yang bisa mengubah masa lalu, tidak ada kecemasan yang bisa mengubah masa depan.",
        "Pikiran negatif tidak akan pernah memberimu kehidupan yang positif.",
        "Semuanya sulit sebelum menjadi mudah.",
        "Ambil risikonya, atau kehilangan kesempatannya.",
        "Jangan pernah berhenti belajar, karena hidup tidak pernah berhenti mengajar.",
        "Orang yang tidak membaca tidak memiliki keunggulan dibanding orang yang tidak bisa membaca.",
        "Orang yang tidak pernah melakukan kesalahan tidak pernah mencoba sesuatu yang baru.",
        "Cara paling umum orang menyerahkan kekuatan mereka adalah dengan berpikir bahwa mereka tidak memilikinya.",
        "Bersyukurlah atas apa yang kamu miliki; kamu akan berakhir dengan lebih banyak. Berkonsentrasilah pada apa yang tidak kamu miliki dan kamu tidak akan pernah merasa cukup.",
        "Yang paling sulit adalah keputusan untuk bertindak, sisanya hanyalah kegigihan.",
        "Banyak kegagalan dalam hidup adalah orang-orang yang tidak menyadari betapa dekatnya mereka saat mereka menyerah.",
        "Bukan soal apakah kamu terjatuh, tapi apakah kamu bangkit.",
        "Pesimis melihat kesulitan dalam setiap kesempatan. Optimis melihat kesempatan dalam setiap kesulitan.",
        "Kemuliaan terbesar kita bukan dalam tidak pernah jatuh, tetapi dalam bangkit setiap kali kita jatuh.",
        "Jangan didorong oleh ketakutan dalam pikiranmu; biarkan dirimu dipimpin oleh mimpi di hatimu.",
        "Ketika kamu tahu apa yang kamu inginkan dan menginginkannya dengan cukup kuat, kamu akan menemukan cara untuk mendapatkannya.",
        "Mulailah dengan melakukan yang perlu, lalu lakukan yang mungkin, dan tiba-tiba kamu melakukan yang mustahil.",
        "Tanpa hasrat kamu tidak punya energi, tanpa energi kamu tidak punya apa-apa.",
        "Kamu tidak harus menjadi hebat untuk memulai, tapi kamu harus memulai untuk menjadi hebat.",
        "Kekuatan tidak datang dari kapasitas fisik, ia datang dari kemauan yang tak tergoyahkan.",
        "Tidak ada yang sia-sia di dunia ini yang meringankan beban orang lain.",
        "Dengan meminta yang mustahil kita memperoleh yang mungkin.",
        "Lebih baik menjadi singa selama sehari daripada menjadi domba seumur hidup.",
        "Hidup terlalu penting untuk dianggap serius.",
        "Permulaan adalah setengah dari setiap tindakan.",
        "Kesabaran tanpa batas menghasilkan hasil yang segera.",
        "Hampir semua orang mati karena obatnya dan bukan karena penyakitnya.",
        "Mereka mampu, karena mereka berpikir mereka mampu.",
        "Imajinasi lebih penting daripada pengetahuan.",
        "Orang-orang yang gigih memulai keberhasilan mereka di mana orang lain berakhir dalam kegagalan.",
        "Tidak ada jalan yang jelas. Hanya jebakan dan jerat dan kegelapan.",
        "Sebuah kesalahan membuktikan bahwa seseorang berhenti bicara cukup lama untuk melakukan sesuatu.",
        "Apa pun yang layak dilakukan, layak dilakukan dengan baik.",
        "Yang paling berkuasa adalah dia yang menguasai dirinya sendiri.",
        "Seorang cendekiawan yang menyukai kenyamanan tidak layak disebut cendekiawan.",
        "Kemakmuran lebih bergantung pada menginginkan apa yang kamu miliki daripada memiliki apa yang kamu inginkan.",
        "Setiap hari datang membawa hadiahnya sendiri, lepaskan pitanya.",
        "Kesuksesan tidak pernah permanen dan kegagalan tidak pernah final.",
        "Tidak ada yang berlangsung selamanya, bahkan masalahmu.",
        "Kerja keras tidak menjamin kesuksesan, tapi meningkatkan peluangnya.",
        "Perdamaian tidak bisa dijaga dengan kekerasan. Ia hanya bisa dicapai melalui pemahaman.",
        "Siapa yang tidak berani tidak beruntung.",
        "Jangan bilang ketika aku punya waktu luang aku akan belajar, kamu mungkin tidak akan punya waktu luang.",
        "Siapa yang kehilangan keyakinan, kehilangan segalanya.",
        "Pikiran sendiri adalah dunianya sendiri. Apa yang dipikirkan seseorang adalah apa yang dia jadi.",
        "Petualangan tidak ada di luar seorang manusia, ia ada di dalamnya.",
        "Permainan kehidupan bukan tentang memegang kartu yang bagus, tapi memainkan kartu buruk dengan baik.",
        "Masam, manis, pahit, pedas; semuanya harus dicicipi.",
        "Jangan pernah biarkan perasaan kegagalan masa lalu mengalahkan langkah berikutnya.",
        "Kecuali kamu ambisius, kamu tidak membuat kemajuan.",
        "Masa depan milik mereka yang berani.",
        "Fakta tidak berhenti ada hanya karena diabaikan.",
        "Kita tidak boleh berasumsi tentang apa yang tidak bisa dibuktikan.",
        "Suara yang keras tidak bisa bersaing dengan suara yang jelas, meskipun itu hanya bisikan.",
        "Bertindaklah seolah-olah kamu mengharapkan untuk mencapai garis akhir.",
        "Kebahagiaan adalah bunga alami dari kewajiban.",
        "\"Tidak\" berarti mulai lagi di tingkat yang lebih tinggi.",
        "Antusiasme menggerakkan dunia.",
        "Seorang juara adalah seseorang yang bangkit ketika dia tidak bisa.",
        "Rintangan adalah harga dari kebesaran.",
        "Pertanyaannya bukan siapa yang akan mengizinkan saya, tapi siapa yang akan menghentikan saya.",
        "Aku tidak di sana untuk bersaing, aku di sana untuk menang.",
        "Berhenti mengeluh, mulai bekerja keras.",
        "Dari kesulitan, tumbuh keajaiban.",
        "Aku tidak takut, aku dilahirkan untuk melakukan ini.",
        "Jangan pernah menundukkan kepalamu. Angkat tinggi-tinggi. Tatap dunia langsung di matanya.",
        "Lakukan apa yang harus kamu lakukan sampai kamu bisa melakukan apa yang ingin kamu lakukan.",
        "Jika kamu jatuh kemarin, berdirilah hari ini.",
        "Jadikan setiap hari sebagai mahakarya.",
        "Darah, keringat, dan rasa hormat. Dua yang pertama kamu berikan, yang terakhir kamu peroleh.",
        "Jadilah begitu hebat sehingga mereka tidak bisa mengabaikanmu.",
        "Tunjukkan pada dunia betapa kerasnya kamu berjuang untuk lingkaran pemenang.",
        "Jika kamu tidak merancang rencana hidupmu sendiri, kemungkinan besar kamu akan masuk dalam rencana orang lain. Apa yang mereka rencanakan untukmu? Tidak banyak.",
        "Satu-satunya orang yang ditakdirkan menjadi dirimu adalah orang yang kamu putuskan untuk menjadi.",
        "Jangan tunggu sampai besi panas untuk memukul; panaskan dengan memukulnya.",
        "Aku tidak percaya Tuhan menempatkan kita di bumi ini untuk menjadi biasa.",
        "Aku ingin dunia menjadi lebih baik karena aku pernah ada di sini.",
        "Kebiasaan ketekunan adalah kebiasaan kemenangan.",
        "Jangan takut melepaskan yang baik untuk mengejar yang luar biasa.",
        "Lakukan tugasmu dan sedikit lebih, dan masa depan akan mengurus dirinya sendiri.",
        "Hidup punya cara untuk menguji kemauan seseorang, entah dengan tidak ada yang terjadi sama sekali atau semuanya terjadi sekaligus.",
        "Orang bijak selalu bisa ditemukan sendiri. Orang lemah selalu bisa ditemukan di keramaian.",
        "Berani berarti kehilangan pijakan sesaat. Tidak berani berarti kehilangan diri sendiri.",
        "Rasa takut mengalahkan lebih banyak orang daripada hal lain di dunia ini.",
        "Kata-kata paling kuat di alam semesta adalah kata-kata yang kamu gunakan untuk berbicara pada dirimu sendiri.",
        "Satu-satunya yang datang kepada orang yang tidur adalah mimpi.",
        "Jika kamu tidak menaklukkan diri sendiri, kamu akan ditaklukkan oleh diri sendiri.",
        "Seorang pahlawan adalah orang yang tahu cara bertahan satu menit lebih lama.",
        "Pergilah sejauh yang kamu bisa lihat, ketika kamu sampai di sana kamu akan bisa melihat lebih jauh.",
        "Kamu tidak menemukan tempatmu di dunia, kamu mengukir tempatmu.",
        "Pemenang fokus pada kemenangan. Pecundang fokus pada pemenang.",
        "Kegagalan tidak akan pernah mengalahkanku jika tekadku untuk berhasil cukup kuat.",
        "Apa yang datang mudah tidak akan bertahan. Apa yang bertahan tidak akan datang mudah.",
        "Untuk menghindari kritik: jangan katakan apa-apa, jangan lakukan apa-apa, jangan jadi apa-apa.",
        "Orang yang melakukan lebih dari yang dibayar akan segera dibayar lebih dari yang dia lakukan.",
        "Kejeniusan memulai karya besar, kerja keraslah yang menyelesaikannya.",
        "Bahkan jika kamu berada di jalur yang benar, kamu akan terlindas jika hanya duduk di sana.",
        "Jika hal-hal tidak gagal, kamu tidak cukup berinovasi.",
        "Kamu mendapatkan yang terbaik dari orang lain ketika kamu memberikan yang terbaik dari dirimu.",
        "Kepemimpinan adalah tindakan, bukan posisi.",
        "Pekerjaan kita adalah presentasi dari kemampuan kita.",
        "Semua masalahku tunduk di hadapan kekeraskepalaan ku.",
        "Kenakan kegagalanmu sebagai lencana kehormatan.",
        "Kita dibatasi bukan oleh kemampuan kita, tetapi oleh visi kita.",
        "Jika kamu lelah, belajarlah untuk istirahat, bukan berhenti.",
        "Jatuh adalah kecelakaan, tetap di bawah adalah pilihan.",
        "Jangan berani menyerah pada hidup ini. Tidak malam ini. Tidak besok. Tidak pernah.",
        "Jangan pernah biarkan dirimu dijatuhkan oleh orang atau kejadian.",
        "Beberapa orang bermimpi tentang kesuksesan sementara yang lain bangun dan bekerja keras untuk itu.",
        "Kepercayaan diri datang dari pengalaman. Pengalaman datang dari mencoba dan gagal dan mencoba lagi, kali ini lebih baik.",
        "Waktu yang mengarah ke penguasaan tergantung pada intensitas fokus kita.",
        "Kesuksesan hanya datang kepada mereka yang berani mencoba.",
        "Satu kunci penting untuk sukses adalah kepercayaan diri. Kunci penting untuk kepercayaan diri adalah persiapan.",
        "Keraguan membunuh lebih banyak mimpi daripada kegagalan.",
        "Kemenangan selalu mungkin bagi orang yang menolak berhenti berjuang.",
        "Kamu tidak akan pernah mengubah hidupmu sampai kamu mengubah sesuatu yang kamu lakukan setiap hari.",
        "Untuk menjadi sukses, fokusmu harus begitu intens sehingga orang lain menganggapmu gila.",
        "Rintangan adalah hal-hal menakutkan yang kamu lihat ketika kamu mengalihkan pandangan dari tujuanmu.",
        "Menemukan peluang adalah soal percaya bahwa peluang itu ada di sana.",
        "Menetapkan tujuan adalah langkah pertama dalam mengubah yang tak terlihat menjadi terlihat.",
        "Jika kamu tidak mempertaruhkan apa pun, kamu mempertaruhkan segalanya.",
        "Jika kamu tidak bisa mengubah situasimu, ubahlah pikiranmu.",
        "Tidak peduli seberapa keras masa lalu, kamu selalu bisa memulai lagi.",
        "Jika kamu tidak berani apa-apa, maka ketika hari berakhir tidak ada apa-apa yang kamu dapatkan.",
        "Sangat sering perubahan diri lebih dibutuhkan daripada perubahan suasana.",
        "Ketakutan adalah kecacatan terbesar dari semuanya dan akan melumpuhkanmu.",
        "Yang berbahaya adalah tidak berevolusi.",
        "Bagaimanapun caranya, aku akan menemukan jalan atau aku akan membuatnya.",
        "Satu-satunya cara untuk membungkam semua orang adalah menang.",
        "Jangan pernah biarkan cukup baik menjadi cukup baik.",
        "Dalam jangka panjang kita hanya mengenai apa yang kita bidik.",
        "Perbaikan terus-menerus lebih baik daripada kesempurnaan yang tertunda.",
        "Jika kamu melihatnya dalam pikiranmu, kamu akan memegangnya di tanganmu.",
        "Hari ini aku akan melakukan apa yang orang lain tidak mau, sehingga besok aku bisa melakukan apa yang orang lain tidak bisa.",
        "Keunggulan adalah seni yang dimenangkan melalui latihan dan kebiasaan.",
        "Tahun depan akan berlalu apakah kamu melakukan sesuatu tentang hidupmu atau tidak.",
        "Jangan berhenti saat kamu lelah, berhentilah saat kamu selesai.",
        "Kamu hanya satu latihan dari suasana hati yang baik.",
        "Lakukan yang benar, bukan yang mudah, bukan yang populer.",
        "Tidak ada hal besar yang pernah datang dengan mudah.",
        "Tanpa perjuangan tidak ada kemajuan.",
        "Orang sukses mengajukan pertanyaan yang lebih baik dan hasilnya mendapat jawaban yang lebih baik.",
        "Aku tidak punya bakat khusus, aku hanya sangat penasaran.",
        "Pelajaran terbaik yang aku pelajari dalam hidup datang dari perasaan terburuk yang aku rasakan.",
        "Tantangan adalah yang membuat hidup menarik. Mengatasinya adalah yang membuat hidup bermakna.",
        "Belajarlah untuk bahagia dengan pendekatan coba, gagal, belajar yang tiada henti.",
        "Jika kamu menutup pintu untuk semua kesalahan, kebenaran akan terkunci di luar.",
        "Lupakan kesalahannya, ingat pelajarannya.",
        "Jika kamu hanya bisa melakukan apa yang bisa kamu lakukan, kamu tidak akan pernah menjadi lebih dari dirimu sekarang.",
        "Siapa yang bijak? Dia yang belajar dari semua orang.",
        "Hanya aku yang bisa mengubah hidupku, tidak ada yang bisa melakukannya untukku.",
        "Ketekunan adalah gagal 19 kali dan berhasil yang ke-20.",
        "Aku menghubungkan kesuksesanku pada ini: aku tidak pernah memberi atau menerima alasan apa pun.",
        "Aku bukan produk dari keadaanku. Aku adalah produk dari keputusanku.",
        "Tindakan kita menentukan kita sebanyak kita menentukan tindakan kita.",
        "Hanya yang sangat bodoh atau sangat cerdas yang bisa menolak perubahan.",
        "Orang yang percaya pada dirinya sendiri mendapatkan kepercayaan orang lain.",
        "Apa yang kamu cari sedang mencarimu.",
        "Jangan khawatir tentang kegagalan. Kamu hanya perlu benar sekali saja.",
        "Keamanan kebanyakan hanyalah takhayul. Hidup adalah petualangan yang berani atau bukan apa-apa.",
        "Kita menjadi apa yang paling sering kita pikirkan, dan itulah rahasia yang paling aneh.",
        "Cara untuk memulai adalah berhenti bicara dan mulai bertindak.",
        "Jadikan setiap hari sebagai mahakarya.",
        "Tidak peduli berapa banyak kesalahan yang kamu buat atau seberapa lambat kemajuanmu, kamu masih jauh di depan semua orang yang tidak mencoba.",
        "Sikap kita di awal tugas yang sulit, lebih dari hal lainnya, akan mempengaruhi keberhasilannya.",
        "Satu-satunya keamanan nyata yang dimiliki seseorang di dunia ini adalah cadangan pengetahuan, pengalaman, dan kemampuan.",
        "Apa yang kamu lakukan hari ini bisa mengubah semua hari esokmu.",
        "Hidupmu tidak menjadi lebih baik secara kebetulan, ia menjadi lebih baik melalui perubahan.",
        "Mimpi tidak menjadi kenyataan melalui sihir, dibutuhkan keringat, tekad, dan kerja keras.",
        "Pengetahuan adalah mengetahui bahwa tomat adalah buah. Kebijaksanaan adalah tidak memasukkannya ke dalam salad buah.",
        "Apa pun situasinya, ingatkan dirimu: aku punya pilihan.",
        "Kuasai pikiranmu atau ia akan menguasaimu.",
        "Beberapa berhasil karena ditakdirkan, tapi kebanyakan berhasil karena bertekad.",
        "Peluang besar tidak terlihat dengan matamu, mereka terlihat dengan pikiranmu.",
        "Siapa yang tidak cukup berani mengambil risiko tidak akan mencapai apa pun dalam hidup.",
        "Mengetahui tidak cukup, kita harus menerapkan. Mau saja tidak cukup, kita harus melakukan.",
        "Ambisi adalah jalan menuju sukses, ketekunan adalah kendaraan yang membawamu sampai.",
        "Kunci kehidupan adalah menerima tantangan. Begitu seseorang berhenti melakukannya, dia sudah mati.",
        "Komitmen adalah yang mengubah janji menjadi kenyataan.",
        "Kepercayaan diri adalah ingatan akan kesuksesan.",
        "Tanpa kepercayaan diri kita seperti bayi di buaian.",
        "Beranilah bermimpi, tapi yang lebih penting lagi beranilah meletakkan aksi di balik mimpimu.",
        "Kejujuran adalah bab pertama dalam buku kebijaksanaan.",
        "Keunggulan adalah proses yang berkelanjutan dan bukan kebetulan.",
        "Harapan adalah mampu melihat bahwa ada cahaya meskipun ada semua kegelapan.",
        "Kita harus menerima kekecewaan yang terbatas, tetapi jangan pernah kehilangan harapan yang tak terbatas.",
        "Tanda sejati kecerdasan bukanlah pengetahuan, tetapi imajinasi.",
        "Jadilah kecanduan perbaikan diri yang konstan dan tiada henti.",
        "Kejeniusan adalah satu persen inspirasi dan sembilan puluh sembilan persen keringat.",
        "Kamu tidak bisa menunggu inspirasi, kamu harus mengejarnya dengan tongkat.",
        "Bersabarlah. Semua hal sulit sebelum menjadi mudah.",
        "Orang yang bilang itu tidak bisa dilakukan sebaiknya tidak menggangu orang yang sedang melakukannya.",
        "Ketekunan adalah kerja keras yang kamu lakukan setelah kamu lelah melakukan kerja keras yang sudah kamu lakukan.",
        "Orang bijak bisa belajar lebih banyak dari pertanyaan bodoh daripada orang bodoh belajar dari jawaban bijak.",
        "Dengan disiplin diri dan pengendalian diri yang konstan kamu bisa mengembangkan kebesaran karakter.",
        "Pengendalian emosi diri adalah hasil kerja keras, bukan keterampilan bawaan.",
        "Belajar cara belajar adalah keterampilan hidup yang paling penting.",
        "Jangan biarkan apa yang tidak bisa kamu lakukan menghentikanmu dari melakukan apa yang bisa kamu lakukan.",
        "Kamu selalu melewati kegagalan dalam perjalanan menuju kesuksesan.",
        "Tidak ada yang sempurna, itulah mengapa pensil punya penghapus.",
        "Jangan pernah biarkan peluang menghentikanmu dari melakukan apa yang kamu tahu di dalam hatimu memang sudah ditakdirkan untuk kamu lakukan.",
        "Jika kamu benar-benar melihat dengan teliti, kebanyakan kesuksesan dalam semalam membutuhkan waktu yang lama.",
        "Apa pun itu mungkin. Apa pun bisa terjadi.",
        "Tidak ada yang terlalu sulit jika kamu memecahnya menjadi pekerjaan-pekerjaan kecil.",
        "Rahasia sukses adalah melakukan hal-hal biasa dengan luar biasa baik.",
        "Bertindaklah seolah-olah apa yang kamu lakukan membuat perbedaan, karena memang demikian.",
        "Apa yang kamu dapatkan dengan mencapai tujuanmu tidak sepenting apa yang kamu jadi dengan mencapainya.",
        "Hidup itu seperti bersepeda; untuk menjaga keseimbangan kamu harus terus bergerak.",
        "Batasi kata \"selalu\" dan \"tidak pernah\" mu.",
        "Kamu tidak pernah terlalu tua untuk menetapkan tujuan baru atau bermimpi mimpi baru.",
        "Kamu tidak menemukan kehidupan bahagia, kamu membuatnya.",
        "Berita buruknya waktu berlalu cepat. Berita baiknya kamu pilotnya.",
        "Selalu hadapkan wajahmu ke arah sinar matahari dan bayangan akan jatuh di belakangmu.",
        "Perbedaan antara yang mustahil dan yang mungkin terletak pada tekad seseorang.",
        "Medali emas tidak benar-benar terbuat dari emas. Mereka terbuat dari keringat, tekad, dan paduan langka yang disebut keberanian.",
        "Jangan meremehkan tekad seorang pria yang pendiam.",
        "Jangan ceritakan apa yang kamu yakini. Aku akan mengamati bagaimana kamu berperilaku dan aku akan membuat kesimpulanku sendiri.",
        "Aku hanya benci kalah dan itu memberimu tekad ekstra untuk bekerja lebih keras.",
        "Tekad untuk menang adalah bagian yang lebih baik dari kemenangan.",
        "Kamu bisa punya semua bakat di dunia, tapi tanpa tekad kamu tidak akan pergi jauh.",
        "Kemenangan adalah anak dari persiapan dan tekad.",
        "Pemuda tahu aturannya, tapi orang tua tahu pengecualiannya.",
        "Pesimis mengeluh tentang angin, optimis mengharapkannya berubah, realis menyesuaikan layarnya.",
        "Pengetahuan tidak bernilai kecuali kamu mempraktikkannya.",
        "Aku lebih baik menyesal hal yang sudah kulakukan daripada menyesal hal yang tidak kulakukan.",
        "Dibutuhkan kebijaksanaan untuk memahami kebijaksanaan. Musik bukan apa-apa jika pendengarnya tuli.",
        "Bahaya yang lebih besar bagi kebanyakan kita bukan pada memasang target terlalu tinggi dan gagal, tetapi memasang target terlalu rendah dan tercapai.",
        "Dalam setiap jalan-jalan di alam seseorang menerima jauh lebih banyak dari yang dicari.",
        "Aku tidak akan mengikuti ke mana jalan menuntun, tapi aku akan pergi ke tempat yang tidak ada jalannya dan aku akan meninggalkan jejak.",
        "Pohon ek perkasa hari ini hanyalah biji kemarin yang bertahan di tempatnya.",
        "Jujur sepenuhnya pada diri sendiri adalah latihan yang baik.",
        "Kita tidak bisa menjadi apa yang kita perlu jadi dengan tetap menjadi apa adanya.",
        "Tetapkan arahmu berdasarkan bintang-bintang, bukan berdasarkan lampu setiap kapal yang lewat.",
        "Jika kamu tidak tahu ke mana kamu akan pergi, jalan mana pun akan membawamu ke sana.",
        "Kamu akan selalu punya dua pilihan: komitmenmu melawan ketakutanmu.",
        "Berbahagialah mereka yang memberi tanpa mengingat dan menerima tanpa melupakan.",
        "Apa yang terjadi tidak sepenting bagaimana kamu bereaksi terhadap apa yang terjadi.",
        "Mulailah dengan apa yang benar bukan apa yang bisa diterima.",
        "Manusia yang unggul menyalahkan dirinya sendiri. Manusia yang rendah menyalahkan orang lain.",
        "Perbuatan terkecil lebih baik daripada niat terbesar.",
        "Hambatan terbesar untuk penemuan bukan ketidaktahuan, melainkan ilusi pengetahuan.",
        "Waspadalah terhadap pengetahuan palsu, itu lebih berbahaya daripada ketidaktahuan.",
        "Cara terbaik untuk memprediksi masa depan adalah menciptakannya.",
        "Menang tanpa risiko adalah menang tanpa kemuliaan.",
        "Karakter kita adalah apa yang kita lakukan ketika kita pikir tidak ada yang melihat.",
        "Semua yang menjengkelkan kita tentang orang lain bisa menuntun kita pada pemahaman tentang diri kita sendiri.",
        "Seni menjadi bijak adalah seni mengetahui apa yang harus diabaikan.",
        "Ceritakan padaku dan aku lupa. Ajarkan aku dan aku ingat. Libatkan aku dan aku belajar.",
        "Kamu punya otak di kepalamu. Kamu punya kaki di sepatumu. Kamu bisa mengarahkan dirimu ke arah mana pun yang kamu pilih.",
        "Dalam tiga kata aku bisa merangkum semua yang kupelajari tentang kehidupan: ia terus berlanjut.",
        "Hidup adalah mencoba hal-hal untuk melihat apakah mereka berhasil.",
        "Kesuksesan biasanya datang kepada mereka yang terlalu sibuk untuk mencarinya.",
        "Aku tidak gagal, aku hanya menemukan 10.000 cara yang tidak berhasil.",
        "Aku gagal menuju kesuksesan.",
        "Jika kamu tidak memprogram dirimu sendiri, hidup akan memprogrammu.",
        "Aku tidak punya waktu untuk merasa kasihan pada diriku sendiri. Aku tidak punya waktu untuk mengeluh. Aku akan terus maju.",
        "Jika kamu tidak bersedia mengambil risiko yang biasa, kamu harus puas dengan yang biasa-biasa saja.",
        "Kesuksesan telah didefinisikan sebagai kemampuan untuk pergi dari kegagalan ke kegagalan tanpa kehilangan antusiasme.",
        "Semua mimpi kita bisa menjadi kenyataan jika kita punya keberanian untuk mengejarnya.",
        "Kesempatan tidak terjadi begitu saja, kamu menciptakannya.",
        "Aku tidak pernah bermimpi tentang kesuksesan, aku bekerja untuk itu.",
        "Jangan biarkan apa yang tidak bisa kamu lakukan mengganggu apa yang bisa kamu lakukan.",
        "Hari ini adalah satu-satunya hari, kemarin sudah berlalu.",
        "Hal-hal bekerja paling baik bagi mereka yang membuat yang terbaik dari cara hal-hal bekerja.",
        "Jika kamu sedang melewati neraka, teruslah berjalan.",
        "Kamu hanya melihat kemuliaan publik, tidak pernah pengorbanan pribadi untuk mencapainya.",
        "Jika kamu tidak menghargai waktumu, orang lain juga tidak.",
        "Tidak ada yang bisa membuatmu merasa rendah tanpa persetujuanmu.",
        "Seorang pria yang sukses adalah yang bisa membangun fondasi kokoh dengan batu bata yang dilemparkan orang lain padanya.",
        "Apa yang tampak seperti cobaan pahit sering kali adalah berkah yang tersamar.",
        "Tidak ada yang lebih umum di dunia ini daripada orang yang tidak sukses yang punya bakat.",
        "Jangan coba menjadi orang sukses, lebih baik cobalah menjadi orang yang bernilai.",
        "Jika kamu tidak bisa menjelaskannya secara sederhana, kamu belum cukup memahaminya.",
        "Kamu tidak pernah gagal sampai kamu berhenti mencoba.",
        "Pengetahuan adalah menyadari apa yang bisa kamu lakukan. Kebijaksanaan adalah mengetahui kapan tidak melakukannya.",
        "Hidup bukan tentang menemukan dirimu. Hidup adalah tentang menciptakan dirimu.",
        "Masalahnya bukan masalahnya, masalahnya adalah sikapmu terhadap masalah itu.",
        "Tidak ada mahakarya yang pernah diciptakan oleh seniman yang malas.",
        "Jalan menuju sukses dan jalan menuju kegagalan hampir persis sama.",
        "Bukan apa yang kamu lihat yang penting, tapi apa yang kamu pahami.",
        "Keberanian adalah perlawanan terhadap rasa takut, penguasaan rasa takut, bukan ketiadaan rasa takut.",
        "Aku merasa semakin keras aku bekerja semakin banyak keberuntungan yang aku miliki.",
        "Cahaya dari satu pikiran hangat bagiku lebih berharga daripada uang.",
        "Semua kemajuan terjadi di luar zona nyaman.",
        "Berpikir harus menjadi aset utamamu tidak peduli pasang surut apa yang kamu hadapi dalam hidup.",
        "Kesuksesan adalah jumlah dari usaha kecil yang diulangi hari demi hari.",
        "Pejuang yang sukses adalah orang biasa dengan fokus setajam laser.",
        "Kesuksesan bukan tentang tidak pernah membuat kesalahan, tapi tentang tidak pernah membuat kesalahan yang sama untuk kedua kalinya.",
        "Jangan biarkan rasa takut kalah lebih besar dari kegembiraan menang.",
        "Langkah pertama adalah ketika kamu menolak menjadi tawanan lingkunganmu.",
        "Tidak ada kemacetan di sepanjang jalan ekstra.",
        "Kapan pun kamu berada di sisi mayoritas, sudah waktunya untuk berhenti dan merenung.",
        "Sukses adalah menyukai dirimu sendiri, menyukai apa yang kamu lakukan, dan menyukai cara kamu melakukannya.",
        "Tujuan tidak selalu dimaksudkan untuk dicapai, sering kali ia hanya berfungsi sebagai sesuatu untuk dibidik.",
        "Lebih baik gagal dalam orisinalitas daripada sukses dalam imitasi.",
        "Motivasi adalah apa yang membuatmu memulai, kebiasaan adalah apa yang membuatmu terus berjalan.",
        "Kamu harus bangun setiap pagi dengan tekad jika kamu ingin tidur dengan kepuasan.",
        "Kamu harus mengharapkan hal-hal besar dari dirimu sebelum kamu bisa melakukannya.",
        "Kesulitan nyata bisa diatasi, hanya yang dibayangkan yang tak terkalahkan.",
        "Orang jarang berhasil kecuali mereka bersenang-senang dalam apa yang mereka lakukan.",
        "Di saat-saat tergelap kita harus fokus untuk melihat cahaya.",
        "Kegagalan adalah bumbu yang memberi rasa pada kesuksesan.",
        "Pikiran ditundukkan dan dijinakkan oleh kemalangan, tapi pikiran besar bangkit di atasnya.",
        "Kamu mungkin harus memerangi pertempuran lebih dari sekali untuk memenangkannya.",
        "Apa yang akan kamu lakukan jika kamu tidak takut?",
        "Hal baik datang kepada yang menunggu, tapi hal yang lebih baik datang kepada yang keluar dan mengambilnya.",
        "Selalu berikan usaha total, bahkan ketika peluangnya melawanmu.",
        "Jangan tunggu perasaanmu berubah untuk bertindak, bertindaklah dan perasaanmu akan berubah.",
        "Tindakan mungkin tidak selalu menghasilkan kebahagiaan, tapi tidak ada kebahagiaan tanpa tindakan.",
        "Kesempurnaan itu membosankan, menjadi lebih baik adalah tempat semua kesenangan berada.",
        "Sulit untuk mengalahkan orang yang tidak pernah menyerah.",
        "Perbedaan antara batu sandungan dan batu loncatan adalah seberapa tinggi kamu mengangkat kakimu.",
        "Jangan pernah menyerah karena mungkin di situlah dan saat itulah arus akan berbalik.",
        "Terkadang tidak mendapatkan apa yang kamu inginkan adalah keberuntungan yang luar biasa.",
        "Aku tidak bisa mengubah arah angin, tapi aku bisa menyesuaikan layarku untuk selalu mencapai tujuanku.",
        "Teruslah maju. Jangan berhenti, jangan berlama-lama dalam perjalananmu, tapi berjuanglah untuk tanda yang ditetapkan di hadapanmu.",
        "Jika kamu benar-benar menginginkan sesuatu jangan menunggunya, ajari dirimu untuk tidak sabar.",
        "Terkadang kamu menang, terkadang kamu belajar.",
        "Dua jenis orang di dunia ini: yang ingin menyelesaikan sesuatu dan yang tidak mau membuat kesalahan.",
        "Pastikan musuh terburukmu tidak tinggal di antara kedua telingamu sendiri.",
        "Selalu ingat kamu benar-benar unik, sama seperti semua orang.",
        "Jika kamu sudah mengendalikan segalanya, kamu tidak bergerak cukup cepat.",
        "Satu cara untuk menjaga momentum adalah dengan terus memiliki tujuan yang lebih besar.",
        "Kamu tidak harus melihat seluruh tangga, ambil saja langkah pertama.",
        "Apa yang tampak seperti cobaan pahit sering kali adalah berkah yang tersamar.",
        "Dua pilihan tentang komitmen: kamu ada di dalam atau di luar, tidak ada yang namanya hidup di antara keduanya.",
        "Ketika kamu menginginkan sesuatu, seluruh alam semesta bersekongkol membantumu mencapainya.",
        "Kebahagiaan bukanlah sesuatu yang sudah jadi, ia datang dari tindakanmu sendiri.",
        "Apa pun dirimu, jadilah yang terbaik.",
        "Rasa sakit tidak terelakkan, penderitaan itu opsional.",
        "Bakat mengenai target yang tidak bisa dikenai orang lain; kejeniusan mengenai target yang tidak bisa dilihat orang lain.",
        "Pikiran adalah tempatnya sendiri dan dengan sendirinya bisa menjadikan surga dari neraka atau neraka dari surga.",
        "Aku benci latihan, tapi aku berkata 'jangan menyerah' - menderita sekarang dan hidup selama sisa hidupmu sebagai juara.",
        "Bukan gunung di depan yang harus didaki yang membuatmu kelelahan, tapi kerikil di sepatumu.",
        "Apa yang kita pikirkan, itulah yang kita jadi.",
        "Seseorang duduk di tempat teduh hari ini, karena seseorang menanam pohon sejak lama.",
        "Satu sinar matahari saja cukup untuk mengusir banyak bayangan.",
        "Bagi pikiran yang tenang, seluruh alam semesta menyerah.",
        "Dengan disiplin diri hampir segala sesuatu mungkin.",
        "Jalan keluar terbaik selalu melewatinya.",
        "Peluang besarmu mungkin tepat di tempat kamu berada sekarang.",
        "Tidak ada yang lebih berharga daripada hari ini.",
        "Satu-satunya perjalanan adalah perjalanan di dalam diri.",
        "Keadaan tidak menentukan ke mana kamu bisa pergi, mereka hanya menentukan di mana kamu mulai.",
        "Keyakinan menciptakan fakta yang sesungguhnya.",
        "Yang membuat gurun indah adalah bahwa di suatu tempat ia menyembunyikan sebuah sumur.",
        "Jika pintu persepsi dibersihkan, segala sesuatu akan tampak bagi manusia sebagaimana adanya, tak terbatas.",
        "Ubah pikiranmu dan kamu mengubah duniamu.",
        "Burung ditenagai oleh kehidupannya sendiri dan oleh motivasinya.",
        "Berikan cahaya dan orang-orang akan menemukan jalannya.",
        "Persiapan terbaik untuk esok hari adalah melakukan yang terbaik hari ini.",
        "Ide-ide membentuk jalannya sejarah.",
        "Tidak pada satu untai saja semua permata kehidupan dirangkai.",
        "Apa yang kita capai secara batin akan mengubah realitas luar.",
        "Tekadmu sendiri untuk sukses lebih penting dari hal lainnya.",
        "Kamu tahu kamu berada di jalan menuju sukses jika kamu akan melakukan pekerjaanmu tanpa dibayar.",
        "Kamu menjadi apa yang kamu yakini.",
        "Jika kamu ingin mencapai keunggulan, kamu bisa sampai di sana hari ini. Mulai detik ini, berhentilah melakukan pekerjaan yang kurang dari sempurna.",
        "Jika kamu tidak bersedia mempertaruhkan yang biasa, kamu harus puas dengan yang biasa.",
        "Sebelum hal lainnya, persiapan adalah kunci kesuksesan.",
        "Aku telah belajar selama bertahun-tahun bahwa ketika pikiran seseorang sudah bulat, rasa takut berkurang.",
        "Hidup terdiri dari begitu banyak perpisahan, yang disatukan bersama.",
        "Menang bukan segalanya, tapi keinginan untuk menang adalah segalanya.",
        "Kamu mungkin kecewa jika gagal, tapi kamu pasti binasa jika tidak mencoba.",
        "Kesalahan adalah fakta kehidupan, respons terhadap kesalahan itulah yang diperhitungkan.",
        "Jika kamu tidak suka jalan yang kamu lalui, mulailah membuka jalan baru.",
        "Tindakan berbicara lebih keras daripada kata-kata, dan itu sangat benar terutama dengan anak-anakmu.",
        "Berlian adalah sepotong batu bara yang berhasil di bawah tekanan.",
        "Jalan yang sulit sering mengarah ke tujuan yang indah.",
        "Terkadang kamu tidak akan pernah tahu nilai sebuah momen sampai ia menjadi kenangan.",
        "Tidak ada yang bisa meredupkan cahaya yang bersinar dari dalam.",
        "Untuk berhasil dalam hidup kamu butuh tiga hal: tulang keinginan, tulang punggung, dan tulang humor.",
        "Mereka yang tidak percaya pada sihir tidak akan pernah menemukannya.",
        "Aku memutuskan bahwa aku tidak bisa membayar seseorang untuk memundurkan waktu, jadi lebih baik aku melewatinya.",
        "Segalanya ada harganya, berapa harga yang bersedia kamu bayar?",
        "Aku paling banyak tumbuh, bukan dari kemenangan, tapi dari kemunduran.",
        "Aku beruntung bahwa apa pun ketakutan yang kumiliki di dalam, keinginanku untuk menang selalu lebih kuat.",
        "Kamu harus percaya pada dirimu sendiri ketika tidak ada orang lain yang percaya.",
        "Jangan takut gagal, ini adalah jalan menuju sukses.",
        "Aku suka kritik, itu membuatmu kuat.",
        "Aku tahu aku ingin selalu melakukan yang terbaik.",
        "Semua orang sukses yang kutemui adalah pecandu kerja.",
        "Aku tidak pernah bersaing dengan siapa pun selain diriku sendiri.",
        "Percaya pada diri sendiri dan tahu siapa dirimu, itulah fondasi untuk segala hal besar.",
        "Aku takut untuk tidak mencoba.",
        "Cara untuk menebus masa lalumu bukan dengan melarikan diri darinya, tapi dengan mencoba memahaminya dan menggunakannya sebagai fondasi untuk bertumbuh.",
        "Bermain aman tidak akan memberimu apa pun di dunia ini.",
        "Trik hebat itu memang hebat, tapi pada orang yang membosankan itu tidak akan berhasil. Ini soal bakat.",
        "Kamu berevolusi, atau kamu menghilang.",
        "Benih harus tumbuh, terlepas dari fakta bahwa ia ditanam di batu.",
        "Tidak peduli seberapa sulit, tegakkan dadamu, angkat kepalamu, dan hadapi.",
        "Selalu lakukan yang terbaik, jangan biarkan tekanan membuatmu panik.",
        "Kamu tidak pernah tahu bagaimana atau kapan kamu memberi dampak, atau betapa pentingnya teladanmu bagi orang lain.",
        "Lakukan apa yang harus kamu lakukan, untuk melakukan apa yang ingin kamu lakukan.",
        "Jangan bercita-cita untuk mencari nafkah, bercita-citalah untuk membuat perbedaan.",
        "Jadilah dirimu di dunia ini, apa pun yang terjadi.",
        "Jika kamu punya musuh, maka pelajari dan kenali musuhmu, jangan hanya marah padanya.",
        "Aku berusaha menjadi seperti orang-orang terhebat yang pernah hidup.",
        "Di mana aku unggul adalah etos kerja yang gila-gilaan. Sementara orang lain tidur, aku bekerja.",
        "Hidup dijalani di tepian.",
        "Bersikap realistis adalah jalan yang paling umum menuju kebiasa-biasaan.",
        "Langkah pertama adalah kamu harus mengatakan bahwa kamu bisa.",
        "Dunia tidak bisa memberitahumu siapa dirimu, kamu harus mencari tahu siapa dirimu dan jadilah itu dalam suka maupun duka.",
        "Kamu harus menyadari kegagalanmu. Kamu harus merangkulnya dan mencari cara untuk mengatasinya.",
        "Ayahku berkata padaku: Sebutkan hargamu di awal. Jika harganya melebihi harga yang kamu sebutkan, pergilah dari sana.",
        "Akankah kamu percaya pada apa yang kamu yakini jika kamu satu-satunya yang meyakininya?",
        "Aku tidak peduli apa yang orang pikirkan, karena orang tidak berpikir.",
        "Aku tidak pernah benar-benar pandai dalam hal apa pun kecuali kemampuan untuk belajar.",
        "Perasaan terbaik di dunia adalah melihat manfaat dan imbalan dari kerja keras.",
        "Tujuanku begitu tinggi sehingga aku tidak punya waktu untuk bersantai dalam bentuk apa pun.",
        "Hidup terlalu singkat untuk mengkhawatirkan apa yang orang lain katakan tentangmu.",
        "Di balik setiap orang sukses bersembunyilah sekawanan pembenci.",
        "Kamu bisa membuat sesuatu dari hidupmu, itu tergantung pada doronganmu.",
        "Kamu punya musuh? Bagus, itu berarti kamu benar-benar membela sesuatu.",
        "Semua kesuksesan dimulai dengan disiplin diri, dimulai dari dirimu.",
        "Dengan dorongan dan sedikit bakat kamu bisa memindahkan gunung.",
        "Kegagalan bukan pilihan, itu hanya sebuah langkah.",
        "Kesuksesan bukan dalam semalam, itu ketika setiap hari kamu menjadi sedikit lebih baik dari hari sebelumnya; semuanya bertambah.",
        "Ketika hidup menempatkanmu dalam situasi sulit jangan katakan 'mengapa aku' cukup katakan 'coba saja aku'.",
        "Keberhasilan dalam hal apa pun selalu bermuara pada ini: fokus dan usaha. Dan kita mengendalikan keduanya.",
        "Aku pernah mendengar seorang bijak berkata bahwa tidak ada manusia sempurna, hanya niat yang sempurna.",
        "Sering kali kamu berhenti berjalan karena kamu berkata 'aku lelah mendaki bukit ini, aku tidak akan pernah sampai puncak' padahal kamu hanya dua langkah dari puncak.",
        "Tantang dirimu, itulah satu-satunya jalan menuju pertumbuhan.",
        "Kamu tidak bisa mengambil pujian untuk bakat, kamu hanya bisa mengambil pujian untuk menggunakannya.",
        "Cara terbaik untuk menjamin kekalahan adalah menyerah.",
        "Aku bisa menonton atau menjadi bagian darinya.",
        "Ketika sesuatu cukup penting kamu melakukannya, bahkan jika peluangnya tidak menguntungkanmu.",
        "Jika kamu bangun di pagi hari dan berpikir masa depan akan lebih baik, itu adalah hari yang cerah, jika tidak maka tidak.",
        "Tidak apa-apa menaruh semua telur dalam satu keranjang, selama kamu mengendalikan apa yang terjadi pada keranjang itu.",
        "Jika kamu hanya melakukan hal-hal yang jawabannya sudah kamu tahu, perusahaanmu akan menghilang.",
        "Kamu harus bersedia disalahpahami jika kamu mau berinovasi.",
        "Tidak pernah ada waktu buruk untuk berinovasi.",
        "Menciptakan peluang berarti melihat ke tempat yang tidak dilihat orang lain.",
        "Keringat adalah ekuitas paling berharga yang ada.",
        "Kita hidup di masyarakat di mana, hampir selalu, kerja keras dihargai.",
        "Alam semesta tidak berkewajiban untuk masuk akal bagimu.",
        "Tidak ada pendidikan yang lebih baik dari yang digerakkan oleh diri sendiri.",
        "Tidak ada yang bodoh yang penasaran.",
        "Aku tidak tahu kapan dalam sejarah manusia ketidaktahuan lebih baik dari pengetahuan.",
        "Latih dirimu untuk tidak mengambil apa pun secara pribadi.",
        "Seseorang bisa menjadi apa yang dia inginkan jika dia benar-benar percaya, tapi dia harus siap untuk kerja keras dan banyak patah hati.",
        "Apa yang masing-masing dari kita harus sadari adalah bahwa niat kita selalu terlihat.",
        "Kita tidak bisa mengabaikan apa yang benar-benar ingin kita ciptakan.",
        "Hanya kamu dan kamu sendiri yang bisa mengubah situasimu.",
        "Bersyukurlah untuk masa-masa sulit, karena itu yang membentukmu.",
        "Untuk bergabung dengan 1 persen teratas kamu harus melakukan apa yang 99 persen tidak mau.",
        "Aku membuat jalanku sendiri, lurus dan sempit. Aku melihatnya seperti ini: kamu ada di jalanku atau tidak.",
        "Kita semua punya keraguan diri. Kamu tidak menyangkalnya, tapi kamu juga tidak menyerah padanya. Kamu merangkulnya.",
        "Banyak pemimpin gagal, karena mereka tidak punya keberanian untuk menyentuh saraf itu atau membunyikan senar itu.",
        "Saat kamu menyerah adalah saat kamu membiarkan orang lain menang.",
        "Jika kamu takut gagal maka kamu mungkin akan gagal.",
        "Aku menyadari bahwa intimidasi tidak benar-benar ada, jika kamu dalam kerangka pikiran yang benar.",
        "Inilah saat aku menerima bahwa waktu-waktu paling menantang akan selalu ada di belakangku dan di depanku.",
        "Tidak ada yang tahu bahwa mereka akan jadi juara - kamu harus bekerja untuk sampai di sana.",
        "Keyakinanku lebih kuat dari keraguanmu.",
        "Sukses berarti puas dengan apa yang kamu lakukan setiap hari. Itu berarti bangga pada diri yang lebih baik yang sedang kamu jadi.",
        "Jika kamu ingin sukses kamu harus bersedia menggunakan setiap koneksi yang kamu punya.",
        "Bakat tidak pernah cukup. Dengan sedikit pengecualian pemain terbaik adalah pekerja terkeras.",
        "Jangan menyerah, berteman dengan orang-orang yang membantumu bekerja keras.",
        "Rayakan saja hidup yang kamu jalani, bukan hidup yang mungkin kamu jalani.",
        "Aku tumbuh miskin, tapi aku tidak punya mimpi miskin.",
        "Kamu satu-satunya yang bisa membuat perbedaan. Apa pun mimpimu, kejarlah.",
        "Hidup tidak berhenti karena sesuatu terjadi padamu.",
        "Dalam hidup, menang dan kalah akan terjadi, yang tidak pernah bisa diterima adalah menyerah.",
        "Tahukah kalian berapa kali aku ditolak dalam hidupku? Diberitahu berapa kali bahwa aku tidak bisa mencapai sesuatu?",
        "Sering kali kutemukan bahwa orang yang diberkahi bakat paling besar tidak pernah mengembangkan sikap itu. Dan yang tidak diberkahi seperti itu justru paling kompetitif dan punya hati paling besar.",
        "Kukira aku tidak akan pernah mendapat kesempatan bermain, sampai suatu kali aku mendapatkannya, karena aku siap dan kesempatan itu muncul.",
        "Aku hanya mencintai kompetisi dan aku suka mencoba untuk memperbaiki diri.",
        "Terlalu sering dalam hidup sesuatu terjadi, dan kita menyalahkan orang lain karena kita tidak bahagia atau puas.",
        "Hidupmu akan menjadi apa yang kamu buat darinya.",
        "Aku tidak akan marah karena seseorang mengatakan sesuatu yang buruk tentangku.",
        "Kamu tidak bisa duduk di pinggir lapangan dalam hidup.",
        "Pesanku sederhana: ambil kendali atas hidupmu.",
        "Ketika kamu salah satu pemimpin tim tidak ada hari libur.",
        "Jangan bergantung pada orang lain. Kamu akan punya dukungan besar dari banyak orang. Tapi tidak ada yang akan memberikanmu apa pun begitu saja.",
        "Hal-hal tidak memperbaiki diri sendiri; kamu harus keluar dan bekerja keras untuk memperbaikinya.",
        "Jika kamu tidak bermain untuk menang, jangan bermain sama sekali.",
        "Jika kamu tidak percaya pada dirimu sendiri, mengapa orang lain harus percaya padamu.",
        "Terkadang dalam hidup tantangan terbesar berakhir menjadi hal terbaik yang terjadi dalam hidupmu.",
        "Aku hanya suka bekerja keras.",
        "Pesaing sejati adalah mereka yang selalu bermain untuk menang.",
        "Jangan kejar uangnya, kejar mimpinya.",
        "Jika kamu ingin terbang kamu harus melepaskan hal-hal yang membebanmu.",
        "Aku tidak ingin kamu bermimpi, aku ingin kamu bertindak.",
        "Siapa pun yang ingin menjadi seseorang akan bekerja sekeras mungkin untuk mewujudkan mimpi itu.",
        "Aku tidak pernah mencoba menyembunyikan fakta bahwa niatku adalah menjadi yang terbaik.",
        "Jika kamu tidak percaya kamu yang terbaik, maka kamu tidak akan pernah mencapai semua yang mampu kamu capai.",
        "Hari ini ada peluang yang tidak ada yang tahu apakah akan datang lagi di masa depan.",
        "Bakat tanpa kerja keras bukan apa-apa.",
        "Aku tidak keberatan orang membenciku, karena itu mendorongku.",
        "Bakat bukan segalanya. Kamu bisa memilikinya sejak buaian, tapi perlu belajar keahlian untuk menjadi yang terbaik.",
        "Aku merasakan kebutuhan tanpa akhir untuk belajar, memperbaiki, berevolusi, untuk merasa puas dengan diriku sendiri.",
        "Cintamu membuatku kuat. Kebencianmu membuatku tak terhentikan.",
        "Kamu bisa mengatasi apa pun jika kamu cukup mencintai sesuatu.",
        "Aku sukses karena aku berkorban untuk kesuksesan.",
        "Ambisiku adalah selalu menjadi lebih baik dan lebih baik.",
        "Aku mulai pagi-pagi dan pulang larut. Hari demi hari, tahun demi tahun, butuh 17 tahun dan 114 hari untukku menjadi sukses dalam semalam.",
        "Orang yang menahanku dari kebahagiaan adalah diriku sendiri.",
        "Tindakan sederhana memperhatikan bisa membawamu jauh.",
        "Jangan bingungkan kebenaran dengan opini massa. Keduanya hampir tidak pernah mirip.",
        "Ada perbedaan antara mengetahui jalan dan berjalan di jalan itu.",
        "Aku tidak punya waktu untuk terjaga sepanjang malam mengkhawatirkan apa yang dikatakan seseorang yang tidak mencintaiku tentang diriku.",
        "Kamu tidak boleh ragu tentang siapa dirimu.",
        "Selalu ada hal yang perlu diperbaiki, kamu tidak pernah selesai.",
        "Aku ingin menjadi apa yang selalu kuinginkan: dominan.",
        "Aku hanya berusaha menjadi yang terbaik dan berharap itu adalah yang terbaik sepanjang masa.",
        "Aku tidak ingin menjadi sehebat dulu, aku ingin menjadi lebih baik.",
        "Pikiranku adalah aset terbesarku. Aku berharap menang di setiap turnamen yang kumainkan.",
        "Orang-orang yang benar-benar mengendalikan emosi mereka yang akan menang.",
        "Tidak peduli seberapa hebat kamu, kamu selalu bisa menjadi lebih baik, dan itulah bagian yang menarik.",
        "Untuk membantu orang lain kamu harus terlebih dahulu belajar membantu dirimu sendiri.",
        "Tidak ada yang berharga yang datang kepada seseorang kecuali sebagai hasil dari kerja keras.",
        "Aku tidak akan membiarkan siapa pun merendahkan jiwaku dengan membuatku membencinya.",
        "Kamu tidak bisa menahan seseorang tanpa ikut tertahan bersamanya.",
        "Karakter, bukan keadaan, yang membentuk manusia.",
        "Ada dua cara menggunakan kekuatan: yang satu mendorong ke bawah, yang lain mengangkat ke atas.",
        "Aku sudah gagal jauh lebih banyak daripada aku berhasil.",
        "Aku melakukan hari ini apa yang orang tidak mau, sehingga aku bisa mencapai besok apa yang orang tidak bisa.",
        "Bahkan jika kamu kalah, jangan kehilangan pelajarannya.",
        "Hal termudah untuk dijual adalah kebenaran.",
        "Jangan tunggu waktu yang sempurna, kamu akan menunggu selamanya. Selalu manfaatkan waktu yang kamu punya dan buatlah sempurna.",
        "Kamu hanya bisa melakukan begitu banyak hal dengan hebat, dan kamu harus menyingkirkan yang lainnya.",
        "Hidup itu rapuh. Kita tidak dijamin esok hari jadi berikan segalanya.",
        "Aku tidak takut mempermalukan diri sendiri.",
        "Rasa hormat memotivasiku, bukan kesuksesan.",
        "Ketika kamu melewati puncak, saat itulah kamu menambah kecepatan.",
        "Keunggulan bukan tindakan, itu kebiasaan.",
        "Kamu tidak bisa mendapat nilai A jika kamu takut mendapat nilai F.",
        "Kamu membuat kesalahanmu untuk belajar cara mencapai yang baik.",
        "Pahlawan adalah seseorang yang dengan sukarela melangkah ke hal yang tidak diketahui.",
        "Ada jutaan penyintas di luar sana. Jadikan satu juta satu.",
        "Jangan pernah menyerah, karena kamu tidak pernah tahu apa yang dibawa pasang esok hari.",
        "Kalau tidak sulit semua orang akan melakukannya. Kesulitannya yang membuatnya hebat.",
        "Jika kamu hanya bermain aman dalam pilihanmu, kamu tidak berkembang.",
        "Aku suka melakukan sesuatu yang kutakuti.",
        "Prosesnya adalah bagian yang paling indah.",
        "Mudah untuk mengelabui mata, tapi sulit mengelabui hati.",
        "Jangan pernah terlalu tinggi, jangan pernah terlalu rendah. Jalani hari demi hari, dan teruslah belajar.",
        "Usaha tidak akan pernah dipertanyakan.",
        "Jangan berharap seseorang memberimu kesempatan: ciptakan kesempatan untuk dirimu sendiri.",
        "Ketika orang bilang aku tidak akan berhasil, aku mendengarkan satu orang yang bilang aku bisa: diriku sendiri.",
        "Ada alasan mengapa itu disebut mengejar mimpi dan bukan berjalan mengikutinya.",
        "Untuk memiliki apa yang benar-benar kamu inginkan, kamu harus terlebih dahulu menjadi dirimu yang sebenarnya.",
        "Jangan biarkan masa lalu menghantuimu. Karena apa yang kamu lakukan di masa kini bisa menghantui masa depanmu, bijaksanalah. Apa yang kamu lakukan sekarang atau di masa depan tidak bisa menutupi masa lalumu, tapi bukan berarti biarkan masa lalu mengendalikanmu.",
        "\"Bagaimana jika\" itu adalah luka yang tidak pernah sembuh.",
        "Kalau mudah, itu tidak akan berharga.",
        "Kamu tidak berhak atas apa pun, kamu mendapatkan apa yang kamu usahakan.",
        "Kesempurnaan tidak menarik, keluar sebagai pemenang meskipun menghadapi cobaan: itulah yang membuatku terkesan.",
        "Jangan ikut olimpiade \"kasihani aku\"; kita tidak berkompetisi di situ.",
        "Ketika kamu menginginkan sesuatu, kamu menerima medannya, apa pun medannya.",
        "Visi sejati adalah ketika pikiranmu lebih kuat dari apa yang ada di depan matamu.",
        "Kejadian tertentu akan memajukanmu, kejadian tertentu akan melakukan sebaliknya, tampaknya begitu. Kebalikan itu adalah peluang belajar yang akan berguna di masa depan.",
        "Bayar harganya untuk menjadi bos atau bayar harga yang datang dengan penyesalan.",
        "Opini orang lain tentangmu tidak harus menjadi kenyataanmu.",
        "Kamu tidak mendapatkan apa yang kamu harapkan, kamu mendapatkan apa yang kamu perjuangkan.",
        "Disiplin diri dimulai dengan penguasaan pikiranmu. Jika kamu tidak mengendalikan apa yang kamu pikirkan, kamu tidak bisa mengendalikan apa yang kamu lakukan. Sederhananya, disiplin diri memungkinkanmu berpikir dulu dan bertindak kemudian.",
        "Apa itu kekalahan? Tidak lain adalah pendidikan; tidak lain adalah langkah pertama menuju sesuatu yang lebih baik.",
        "Bukan apa yang terjadi padamu, tapi bagaimana reaksimu yang penting.",
        "Kendalikan amarahmu. Jika kamu punya amarah terhadap orang lain, mereka mengendalikanmu.",
        "Tantangan terbesarmu adalah hadir ketika pikiranmu membuat alasan terbaik.",
        "Kamu bisa merasakan rasa sakit dari disiplin, atau rasa sakit dari penyesalan. Pilihannya ada padamu.",
        "Apa pun yang membuatmu lemah secara fisik, intelektual, dan spiritual; tolaklah sebagai racun.",
        "Berkeringat lebih banyak saat damai, berdarah lebih sedikit saat perang.",
        "Dengan keberanian untuk memulai dan disiplin untuk bertahan, kemenangan menjadi soal waktu.",
        "Pemimpin yang baik mengambil sedikit lebih banyak bagian kesalahan, dan sedikit lebih sedikit bagian pujian.",
        "Jadilah kuat, tapi jangan kasar. Jadilah baik, tapi jangan lemah. Jadilah berani, tapi jangan menindas. Jadilah rendah hati, tapi jangan pemalu. Jadilah bangga, tapi jangan sombong.",
        "Kesabaran itu pahit, tapi buahnya manis.",
        "Kesabaran bukan berarti pasif, sebaliknya; ia aktif. Ia adalah kekuatan yang terkonsentrasi.",
        "Tidak ada yang mustahil bagi siapa yang mau mencoba.",
        "Kecerdasan bukan kemampuan menyimpan informasi, tapi mengetahui di mana menemukannya.",
        "Pertama itu niat. Lalu perilaku. Lalu kebiasaan. Lalu praktik. Lalu sifat kedua. Lalu itu menjadi dirimu.",
        "Apa pun yang ingin kamu lakukan, lakukan sekarang. Hanya ada begitu banyak hari esok.",
        "Orang yang bilang itu tidak bisa dilakukan sebaiknya tidak mengganggu mereka yang sedang melakukannya.",
        "Hanya ada satu sudut alam semesta yang bisa kamu yakin untuk diperbaiki, dan itu adalah dirimu sendiri.",
        "Orang bodoh mengira dirinya bijak, tapi orang bijak tahu bahwa dirinya bodoh.",
        "Rasa sakit bisa mengubahmu, tapi bukan berarti harus menjadi perubahan yang buruk. Ambil rasa sakit itu dan ubah menjadi kebijaksanaan.",
        "Waktu benar-benar satu-satunya modal yang dimiliki setiap manusia, dan satu-satunya yang tidak mampu dia hilangkan.",
        "Ikuti jalanmu sendiri, apa pun kata orang.",
        "Lakukan sesuatu. Jika berhasil, lakukan lebih banyak. Jika tidak, lakukan sesuatu yang lain.",
        "Belajar adalah satu-satunya hal yang tidak pernah membuat pikiran lelah, takut, atau menyesal.",
        "Pemenang adalah pemimpi yang tidak pernah menyerah.",
        "Jika kamu tidak berjuang untuk apa yang kamu inginkan, jangan menangisi apa yang kamu kehilangan.",
        "Setelah kamu menerima kekuranganmu, tidak ada yang bisa menggunakannya melawanmu.",
        "Setelah kita cukup belajar tentang alam semesta, kita akan mengakui bahwa kita tidak akan pernah tahu segalanya.",
        "Khawatir itu seperti membayar utang yang bukan milikmu.",
        "Kamu tidak bisa mengajari siapa pun apa pun, hanya membuat mereka sadar bahwa jawabannya sudah ada di dalam diri mereka.",
        "Kekuatan pikiran bisa menyebabkan penyakit atau pemulihan.",
        "Jika kamu ingin melihat keajaiban, jadilah keajaiban.",
        "Ada tiga kelas manusia: mereka yang melihat, mereka yang melihat ketika ditunjukkan, mereka yang tidak melihat.",
        "Ketakutan terbesarmu diciptakan oleh imajinasimu.",
        "Penipuan terbesar yang diderita manusia adalah dari opini mereka sendiri.",
        "Ketika kamu telah menghabiskan semua kemungkinan, ingatlah ini: kamu belum.",
        "Cintai tangan yang diberikan takdir padamu dan mainkan sebagai milikmu sendiri.",
        "Jika dua orang setuju dalam segala hal, salah satunya tidak diperlukan.",
        "Kompetisi terbesar adalah yang kamu miliki dengan dirimu sendiri.",
        "Ketika kita lelah, kita diserang oleh ide-ide yang sudah kita kalahkan lama.",
        "Aku bukan apa yang terjadi padaku. Aku adalah apa yang aku pilih untuk menjadi.",
        "Faktor terpenting dalam bertahan hidup bukanlah kecerdasan maupun kekuatan, melainkan kemampuan beradaptasi.",
        "Iman dan ketakutan keduanya menuntutmu untuk percaya pada sesuatu yang tidak bisa kamu lihat. Kamu yang memilih.",
        "Dengan mengeluh, kamu memberitahu orang betapa lemahnya dirimu.",
        "Untuk mendapatkan apa yang kamu cintai, kamu harus terlebih dahulu bersabar dengan apa yang kamu benci.",
        "Ketika semuanya tampak melawanmu, ingatlah bahwa pesawat lepas landas melawan angin, bukan bersamanya.",
        "Kamu akan menertawakan ketakutanmu ketika kamu mengetahui siapa dirimu sebenarnya.",
        "Kedamaian tidak ditemukan dalam badai yang lebih tenang, ia ditemukan dalam perahu yang lebih baik.",
        "Kamu bisa mengabaikan kenyataan, tapi kamu tidak bisa mengabaikan konsekuensi dari mengabaikan kenyataan.",
        "Tidak ada manusia yang lebih tidak bahagia dari yang tidak pernah menghadapi kesulitan. Karena dia tidak diizinkan membuktikan dirinya.",
        "Rencana bagus yang dijalankan dengan keras sekarang lebih baik daripada rencana sempurna yang dijalankan minggu depan.",
        "Belajar dan tidak berpikir itu sia-sia. Berpikir dan tidak belajar itu berbahaya.",
        "Ketakutan adalah reaksi. Keberanian adalah keputusan.",
        "Kemandirian hanya untuk segelintir orang; itu adalah hak istimewa orang kuat.",
        "Butuh separuh hidupmu sebelum kamu menyadari bahwa hidup adalah proyek lakukan-sendiri.",
        "Mainkan peranmu dengan kehormatan.",
        "Kekhawatiran adalah penyalahgunaan imajinasi.",
        "Jembatan antara pengetahuan dan keterampilan adalah latihan. Jembatan antara keterampilan dan penguasaan adalah waktu.",
        "Semakin banyak aku belajar, semakin aku sadar betapa banyak yang masih harus kupelajari.",
        "Jika kamu tidak kalah, kamu tidak bisa menikmati kemenangan. Jadi aku harus menerima keduanya.",
        "Kita belajar sedikit dari kemenangan, banyak dari kekalahan.",
        "Yang berbicara sopan tapi meningkatkan persiapannya akan maju. Yang berbicara agresif dan maju tergesa-gesa akan mundur.",
        "Hidup kita adalah apa yang pikiran kita ciptakan.",
        "Tidak ada yang benar-benar sulit kecuali kamu memutuskannya sulit. Kalau tidak, itu hanya hal berikutnya yang kamu cari tahu.",
        "Apa pun situasinya, jangan pernah biarkan emosimu mengalahkan kecerdasanmu.",
        "Tentukan tipe orang yang ingin kamu jadi dan tetaplah begitu, baik sendirian maupun bersama orang lain.",
        "Jika ada yang salah, perbaiki jika kamu bisa. Tapi latih dirimu untuk tidak khawatir. Khawatir tidak pernah memperbaiki apa pun.",
        "Hidup bukan soal memegang kartu bagus, tapi memainkan kartu buruk dengan baik.",
        "Jalan yang kasar mengarah ke puncak kebesaran.",
        "Hari ketika seseorang menjadi lebih unggul dari kesenangan, dia juga akan lebih unggul dari rasa sakit.",
        "Teruslah belajar, selalu ada satu hal lagi untuk dipelajari.",
        "Kita bisa mengeluh karena semak mawar berduri, atau bersukacita karena semak berduri berbunga mawar.",
        "Bersabarlah dan teguhlah; suatu hari rasa sakit ini akan berguna bagimu.",
        "Kegagalan adalah kesuksesan yang sedang berjalan.",
        "Siapa pun yang berhenti belajar sudah tua, entah umur dua puluh atau delapan puluh.",
        "Jika kamu dikendalikan pikiran, kamu raja; jika oleh tubuh, kamu budak.",
        "Kebanggaan bukan kebalikan dari rasa malu, tapi sumbernya. Kerendahan hati sejati adalah satu-satunya penawar rasa malu.",
        "Ketika kamu mulai memperbaiki dirimu, kesepian adalah harga yang kamu bayar.",
        "Kamu tidak dinilai dari ketinggian yang kamu capai, tapi dari kedalaman yang kamu daki.",
        "Seorang pria bukan besar karena dia tidak pernah gagal; seorang pria besar karena kegagalan tidak menghentikannya.",
        "Pria tanpa visi adalah pria tanpa masa depan. Pria tanpa masa depan akan selalu kembali ke masa lalunya.",
        "Lebih baik gagal dengan kehormatan daripada sukses dengan penipuan.",
        "Semua pertempuran pertama-tama dimenangkan atau dikalahkan di dalam pikiran.",
        "Emosi manusia terusik lebih cepat daripada kecerdasan manusia.",
        "Siapa yang membeli apa yang tidak dibutuhkan, mencuri dari dirinya sendiri.",
        "Siapa yang bersabar bisa mendapatkan apa yang dia inginkan.",
        "Jalan sang Pejuang adalah seumur hidup, dan penguasaan sering kali hanya berarti tetap di jalan.",
        "Layang-layang terbang paling tinggi melawan angin, bukan bersamanya.",
        "Jika orang tahu betapa kerasnya aku harus bekerja untuk menguasai keahlianku, itu tidak akan tampak begitu mengagumkan.",
        "Jangan pernah tidur tanpa permintaan kepada alam bawah sadarmu.",
        "Sambut kejadian dengan cara apa pun yang terjadi: inilah jalan menuju kedamaian.",
        "Berlatihlah bahkan yang tampaknya mustahil.",
        "Pria yang mengejar dua kelinci tidak menangkap satu pun.",
        "Kamu akan berhasil, tapi rasanya selalu seolah-olah kamu tidak.",
        "Rencanakan yang sulit saat masih mudah, lakukan yang besar saat masih kecil.",
        "Ketekunan saja tidak cukup. Seseorang harus memutuskan apakah akan bertahan sebagai penderita atau sebagai pejuang.",
        "Tingkat ketajaman dan disiplin yang dibutuhkan untuk membawamu ke puncak yang kamu impikan sebenarnya sederhana, hanya saja tidak mudah.",
        "Musuh terbesar tidak ditemukan di luar. Kehancuran sering datang dari dalam.",
        "Semua orang tahu itu mustahil, sampai seorang bodoh yang tidak tahu datang dan melakukannya.",
        "Kamu tidak bisa membuat orang lemah kuat dengan membuat orang kuat lemah.",
        "Kamu punya kuasa atas pikiranmu, bukan kejadian luar. Sadari ini, dan kamu akan menemukan kekuatan.",
        "Berlian hanyalah sepotong batu bara yang tekun pada pekerjaannya.",
        "Risiko terbesar adalah tidak mengambil risiko apa pun.",
        "Jika kamu mendefinisikan masalah dengan benar, kamu hampir memiliki solusinya.",
        "Masa lalu ada di kepalamu, masa depan ada di tanganmu.",
        "Hidup cukup sederhana. Kamu melakukan beberapa hal. Kebanyakan gagal. Beberapa berhasil. Kamu lakukan lebih banyak yang berhasil.",
        "Semoga rasa kewajibanmu mengalahkan atmosfer ketakutan dan kecenderungan untuk menunda aspirasi.",
        "Segala yang pernah kamu inginkan ada di sisi lain dari ketakutan.",
        "Disiplin adalah memilih antara apa yang kamu inginkan sekarang dan apa yang paling kamu inginkan.",
        "Konformitas adalah tempat perlindungan terakhir orang yang tidak imajinatif.",
        "Berlian adalah sepotong batu bara yang tekun pada pekerjaannya.",
        "Tidak ada bahaya yang lebih besar bagi manusia daripada waktu yang terbuang.",
        "Jangan rusak apa yang kamu miliki dengan menginginkan apa yang tidak kamu miliki; ingatlah bahwa apa yang kamu miliki sekarang dulunya termasuk hal-hal yang hanya kamu harapkan.",
        "Orang yang menguasai kesabaran menguasai segalanya.",
        "Jangan pernah meletakkan gairah di depan prinsip, bahkan jika kamu menang, kamu kalah.",
        "Beberapa orang ingin itu terjadi, beberapa berharap itu terjadi, yang lain mewujudkannya.",
        "Kita tidak naik ke tingkat harapan kita, kita jatuh ke tingkat latihan kita.",
        "Lebih mudah menemukan orang yang rela mati daripada menemukan mereka yang bersedia menanggung rasa sakit dengan sabar.",
        "Kamu tidak bisa berharap naik podium jika kamu tidak ikut balapan.",
        "Yang jatuh dan bangkit lebih kuat dari yang tidak pernah mencoba.",
        "Berita Buruk: Kamu tidak akan cocok dengan semua orang. Berita Baik: Yang hebat tidak pernah cocok.",
        "Aku tidak pernah berbakat, aku hanya pandai tidak pernah menyerah.",
        "Kebahagiaan bukan ketiadaan masalah, tapi kemampuan untuk menghadapinya.",
        "Jika kamu melakukan yang mudah hidupmu akan sulit.",
        "Kamu tidak bisa kembali dan mengubah awal, tapi kamu bisa mulai dari tempatmu sekarang dan mengubah akhirnya.",
        "Lebih banyak yang ditangkap daripada yang diajarkan.",
        "Mereka yang tidak pernah membuat kesalahan bekerja untuk kita yang membuat kesalahan.",
        "Ide baru tidak boleh dinilai dari hasil langsungnya.",
        "Kamu tidak pernah siap untuk apa yang harus kamu lakukan. Kamu hanya melakukannya. Itulah yang membuatmu siap.",
        "Ambil risiko: jika kamu menang, kamu akan bahagia; jika kamu kalah, kamu akan bijak.",
        "Bangsa yang menghargai hak istimewanya di atas prinsipnya akan segera kehilangan keduanya.",
        "Jalan tercepat menuju makna dan kesuksesan: pilih satu hal dan berikan segalanya.",
        "Jangan takut untuk memulai lagi. Kali ini, kamu tidak memulai dari nol. Kamu memulai dari pengalaman.",
        "Tidak ada yang mulia dalam menjadi lebih unggul dari sesamamu; kemuliaan sejati adalah menjadi lebih unggul dari dirimu yang dulu.",
        "Kamu akan mendapat penghormatan dari semua jika kamu mulai dengan menghormati dirimu sendiri.",
        "Ciptakan visi tentang siapa yang ingin kamu jadi, lalu hiduplah dalam gambaran itu seolah-olah itu sudah benar.",
        "Harga keunggulan adalah disiplin. Biaya kebiasaan-biasaan adalah kekecewaan.",
        "Kesulitan menguatkan pikiran, sebagaimana kerja menguatkan tubuh.",
        "Kamu tidak bisa berharap membuat kemajuan di bidang di mana kamu tidak mengambil tindakan.",
        "Tidak ada kecemasan yang mengubah apa pun yang akan terjadi.",
        "Tunjukkan padaku orang dengan kemampuan rata-rata tapi keinginan luar biasa dan aku akan menunjukkan pemenang setiap saat.",
        "Cara tercepat untuk sukses adalah mulai sekarang dan cari tahu sambil jalan.",
        "Orang tidak memutuskan masa depan mereka, mereka memutuskan kebiasaan mereka dan kebiasaan mereka memutuskan masa depan mereka.",
        "Ajarkan anak-anakmu lebih awal apa yang kamu pelajari terlambat.",
        "Jika kamu menghabiskan 100 jam setahun dalam disiplin apa pun, yang hanya 18 menit sehari, kamu akan lebih baik dari 95 persen dunia dalam disiplin itu.",
        "Tugasnya bukan melihat apa yang belum dilihat siapa pun; tapi memikirkan apa yang belum dipikirkan siapa pun, tentang apa yang dilihat semua orang.",
        "Jika kamu terganggu oleh setiap gesekan, bagaimana cerminmu akan dipoles?",
        "Ketakutan hanya sedalam pikiran membolehkannya.",
        "Kesulitan adalah yang membangunkan kejeniusan.",
        "Yang harus memberikan cahaya harus tahan terhadap pembakaran.",
        "Aku telah belajar bahwa kesuksesan harus diukur bukan dari posisi yang dicapai seseorang dalam hidup melainkan dari rintangan yang dia atasi saat berusaha berhasil.",
        "Kenyamanan adalah kecanduan terburuk.",
        "Kamu menjadi apa yang kamu berikan perhatianmu.",
        "Keadaan tidak membentuk manusia, mereka hanya mengungkapkannya pada dirinya sendiri.",
        "Jangan buang waktu lagi berdebat tentang apa yang seharusnya dilakukan orang baik. Jadilah orang baik.",
        "Biarlah dia yang ingin menggerakkan dunia terlebih dahulu menggerakkan dirinya sendiri.",
        "Antara rangsangan dan respons ada ruang. Dalam ruang itu ada kekuatan kita untuk memilih respons kita. Dalam respons kita terletak pertumbuhan dan kebebasan kita.",
        "Tidak ada apa pun di luar dirimu yang bisa membuatmu lebih baik, lebih kuat, lebih kaya, lebih cepat, atau lebih pintar. Semuanya ada di dalam. Semuanya ada. Jangan cari apa pun di luar dirimu.",
        "Bersikaplah toleran pada orang lain dan ketat pada dirimu sendiri.",
        "Dua hal mendefinisikanmu: Kesabaranmu saat kamu tidak punya apa-apa dan sikapmu saat kamu punya segalanya.",
        "Kamu tidak bangun begitu saja dan menjadi kupu-kupu.",
        "Ketangguhan adalah kemampuan bertahan ketika melepaskan tampak paling menarik.",
        "Ada risiko dan biaya untuk bertindak. Tapi mereka jauh lebih kecil daripada risiko jangka panjang dari ketidakaktifan yang nyaman.",
        "Untuk mencapai hal-hal besar, dibutuhkan dua hal: rencana, dan waktu yang tidak cukup.",
        "Keraguan hanya bisa dihilangkan dengan tindakan.",
        "Jika tindakanmu menginspirasi orang lain untuk lebih bermimpi, lebih belajar, lebih berbuat, dan menjadi lebih, kamu adalah pemimpin.",
        "Ini bukan tentang memiliki catatan tanpa cela. Ini tentang belajar dari noda di catatanmu.",
        "Beranilah cukup untuk buruk dalam sesuatu yang baru.",
        "Tidurlah lebih pintar dari saat kamu bangun.",
        "Kesuksesan lambat membangun karakter, kesuksesan cepat membangun ego.",
        "Hanya karena seseorang tersandung dan kehilangan jalannya, bukan berarti mereka hilang selamanya.",
        "Tapi kita tidak bisa hanya duduk dan menatap luka kita selamanya.",
        "Dan sekarang karena kamu tidak perlu sempurna, kamu bisa menjadi baik.",
        "Kesuksesan datang dari pelaksanaan dasar-dasar yang tanpa kompromi.",
        "Butuh banyak kerja keras untuk membuat sesuatu yang sederhana.",
        "Semua orang berpikir tentang mengubah dunia, tapi tidak ada yang berpikir tentang mengubah dirinya sendiri.",
        "Yang berpikiran sempit butuh seni yang disuapi.",
        "Lakukan sesuatu daripada membuang waktu. Karena waktu sedang membunuhmu.",
        "Biarkan setiap keputusan sejalan dengan visimu.",
        "Jika kamu ingin melakukan sesuatu yang lebih besar dari rata-rata, kamu tidak bisa menyerah pada ketakutan menjadi orang buangan.",
        "Yang paling penting adalah seberapa baik kamu berjalan melewati api.",
        "Kamu hanya satu keputusan dari kehidupan yang sama sekali berbeda.",
        "Jika kamu hidup untuk hari esok, kamu akan selalu tertinggal satu hari.",
        "Jadikan dirimu yang terbaik, karena hanya itu yang ada darimu.",
        "Mata tidak berguna ketika pikiran buta.",
        "Dalam jangka panjang manusia hanya mengenai apa yang mereka bidik. Maka meskipun mereka langsung gagal, lebih baik mereka membidik sesuatu yang tinggi.",
        "Siapa yang punya alasan untuk hidup bisa menanggung hampir segala cara.",
        "Manusia bisa dibagi menjadi dua kelompok: yang maju dan mencapai sesuatu, dan yang datang kemudian dan mengkritik.",
        "Sikap buruk itu seperti ban kempes. Kamu tidak bisa ke mana-mana sampai kamu menggantinya.",
        "Tidak ada burung yang terbang terlalu tinggi jika ia terbang dengan sayapnya sendiri.",
        "Selesaikan masalahnya atau tinggalkan masalahnya. Jangan hidup dengan masalahnya.",
        "Bertindaklah sesuai prinsipmu, bukan suasana hatimu.",
        "Mereka yang tidak berkomitmen pada apa pun terganggu oleh segalanya.",
        "Ketika kita berusaha menjadi lebih baik dari diri kita, semua di sekitar kita juga menjadi lebih baik.",
        "Tidak ada gairah dalam menerima kehidupan yang kurang dari yang kamu mampu jalani.",
        "Orang kreatif dimotivasi oleh keinginan untuk mencapai, bukan oleh keinginan untuk mengalahkan orang lain.",
        "Hidup adalah persiapan panjang untuk sesuatu yang tidak pernah terjadi.",
        "Aku tidak lagi mendengarkan apa yang orang katakan, aku hanya mengamati apa yang mereka lakukan. Perilaku tidak pernah berbohong.",
        "Individu cerdas belajar dari segalanya dan semua orang; orang biasa, dari pengalamannya. Yang bodoh sudah punya semua jawaban.",
        "Aturan pertama adalah menjaga jiwa yang tenang. Kedua adalah melihat sesuatu apa adanya.",
        "Selalu ada perjuangan untuk mengangkat beban yang lebih berat.",
        "Orang yang takut menderita sudah menderita dari apa yang dia takutkan.",
        "Jika seseorang tidak tahu ke pelabuhan mana dia berlayar, tidak ada angin yang menguntungkan.",
        "Aku selalu melakukan apa yang tidak bisa kulakukan, agar aku bisa belajar cara melakukannya.",
        "Kamu membangun di atas kegagalan. Kamu menggunakannya sebagai batu loncatan. Tutup pintu masa lalu. Kamu tidak mencoba melupakan kesalahannya, tapi kamu tidak berkutat padanya. Kamu tidak membiarkannya mengambil energimu, atau waktumu, atau ruangmu.",
        "Isi karaktermu adalah pilihanmu. Hari demi hari, apa yang kamu pilih, apa yang kamu pikirkan, dan apa yang kamu lakukan adalah siapa dirimu.",
        "Para pengecut tidak pernah memulai dan yang lemah mati di sepanjang jalan.",
        "Ketika kamu bangun di pagi hari, pikirkan betapa berharganya hak istimewa menjadi hidup, bernapas, berpikir, menikmati, mencintai.",
        "Rahasia sukses adalah fokus pada tujuan.",
        "Satu-satunya hal yang lebih berbahaya dari ketidaktahuan adalah keangkuhan.",
        "Kita adalah apa yang kita lakukan berulang kali. Keunggulan, dengan demikian, bukan tindakan, melainkan kebiasaan.",
        "Sementara kita menunggu hidup, hidup berlalu.",
        "Kesuksesan hanyalah beberapa disiplin sederhana yang dipraktikkan setiap hari.",
        "Semakin banyak dia tahu semakin sadar dia akan ketidaktahuannya.",
        "Hambatan untuk bertindak memajukan tindakan. Apa yang menghalangi jalan menjadi jalan.",
        "Kelemahan terbesar kita adalah menyerah. Cara paling pasti untuk berhasil adalah selalu mencoba sekali lagi.",
        "Permata tidak bisa dipoles tanpa gesekan, begitu pula manusia tidak bisa disempurnakan tanpa ujian.",
        "Nilaimu terdiri dari siapa dirimu dan bukan apa yang kamu miliki.",
        "Pelaku kejahatan lebih malang dari korbannya.",
        "Salah satu ujian integritas yang paling benar adalah penolakannya yang tegas untuk dikompromikan.",
        "Tuhan tidak memberi apa pun kepada mereka yang menyilangkan tangan.",
        "Mengetahui cara berpikir memberdayakanmu jauh melampaui mereka yang hanya tahu apa yang harus dipikirkan.",
        "Jika kamu berencana menjadi kurang dari yang mampu kamu jadi, kamu mungkin akan tidak bahagia sepanjang hidupmu.",
        "Tidak ada yang lebih baik dari kesulitan. Setiap kekalahan, setiap patah hati, setiap kehilangan mengandung benihnya sendiri, pelajarannya sendiri tentang cara meningkatkan kinerjamu lain kali.",
        "Belajar mencintai kebencian. Rangkul. Nikmati. Kamu pantas mendapatkannya. Semua berhak punya pendapat dan semua harus punya pendapat tentangmu. Pembenci adalah masalah yang bagus. Tidak ada yang membenci yang baik. Mereka membenci yang hebat.",
        "Terima ketidakmampuanmu mengendalikan segalanya. Terima tanggung jawab atas semua yang di bawah kendalimu. Terima bahwa hambatan internal dan eksternal ada. Terima bahwa kamu dilengkapi untuk menavigasi semuanya.",
        "Pengalaman adalah jenis guru yang paling keras. Ia memberimu ujian dulu dan pelajaran kemudian.",
        "Kita dewasa karena luka, bukan karena usia.",
        "Jika kamu depresi kamu hidup di masa lalu. Jika kamu cemas kamu hidup di masa depan. Jika kamu damai kamu hidup di masa kini.",
        "Jika kamu pikir kita tidak bisa mengubah dunia, itu hanya berarti kamu bukan salah satu dari mereka yang akan melakukannya.",
        "Mungkin ini bukan tentang akhir yang bahagia. Mungkin ini tentang ceritanya.",
        "Beberapa orang membawa kegembiraan ke mana pun mereka pergi, dan beberapa orang membawa kegembiraan kapan pun mereka pergi.",
        "Amati terus-menerus bahwa segala sesuatu terjadi melalui perubahan, dan biasakan diri untuk berpikir bahwa alam semesta tidak mencintai apa pun sebanyak berubah.",
        "Terlalu baik cenderung tidak menarik.",
        "Terlalu sering kita menikmati kenyamanan opini tanpa ketidaknyamanan berpikir.",
        "Belajar tanpa berpikir itu sia-sia; berpikir tanpa belajar itu berbahaya.",
        "Satu orang dengan keyakinan akan mengatasi seratus yang hanya punya opini.",
        "Orang bodoh bertambah banyak ketika orang bijak diam.",
        "Bersedialah untuk merevisi sistem apa pun, membuang metode apa pun, meninggalkan teori apa pun jika keberhasilan pekerjaan memerlukannya.",
        "Membantu orang lain berkembang dan berhasil dalam hidup adalah imbalan tersendiri dan hanya bernilai ketika tidak ada yang diharapkan sebagai balasannya.",
        "Sekarang bukan waktunya memikirkan apa yang tidak kamu miliki. Pikirkan apa yang bisa kamu lakukan dengan apa yang ada.",
        "Aku akan bilang aku adalah pekerjaan yang sedang berjalan, tapi itu akan menyiratkan bahwa suatu hari aku tidak lagi begitu.",
        "Jangan menyerah. Biasanya kunci terakhir di gantunganlah yang membuka pintu.",
        "Hidup adalah komedi bagi mereka yang berpikir, tragedi bagi mereka yang merasakan.",
        "Kebijaksanaan adalah kemampuan menyuruh seseorang pergi ke neraka sedemikian rupa sehingga mereka menantikan perjalanannya.",
        "Tinggalkan kesalahan yang dilakukan orang lain di tempat kesalahan itu muncul.",
        "Jangan ganggu dirimu dengan membayangkan seluruh hidupmu sekaligus. Jangan selalu berpikir tentang penderitaan apa dan berapa banyak yang mungkin menimpamu.",
        "Setiap kali kupikir aku tahu segalanya, \"segalanya\" ternyata punya volume sedikit lebih banyak dari yang kuasumsikan.",
        "Perbedaan antara kebodohan dan kejeniusan adalah bahwa kejeniusan punya batasnya.",
        "Lebih baik menjadi pejuang di taman daripada tukang kebun di perang.",
        "Kesuksesan besar selalu datang dengan risiko kegagalan yang besar.",
        "Kesuksesan datang dari keingintahuan, konsentrasi, ketekunan, dan kritik diri.",
        "Ini adalah tanda pikiran yang terdidik untuk bisa menikmati sebuah pemikiran tanpa menerimanya.",
        "Opini 10.000 orang tidak bernilai jika tidak ada dari mereka yang tahu apa-apa tentang subjeknya.",
        "Semakin kita menghargai hal-hal di luar kendali kita, semakin sedikit kendali yang kita miliki.",
        "Lakukan perjalanan. Cobalah. Tidak ada yang lain.",
        "Asal usul tidak boleh menjadi penghalang kesuksesan. Awal yang sederhana bisa lebih membantu daripada menghalangi.",
        "Jangan biarkan kekurangan orang lain membuatmu jadi kurang.",
        "Iri hati kita selalu bertahan lebih lama dari kebahagiaan orang yang kita iri.",
        "Tidak ada yang berasal dari ketiadaan.",
        "Orang lemah membalas dendam. Orang kuat memaafkan. Orang cerdas mengabaikan.",
        "Aku tidak mengendalikan angin; aku hanya mempelajarinya.",
        "Kehormatan mungkin tidak memenangkan kekuasaan, tapi ia memenangkan rasa hormat. Dan rasa hormat menghasilkan kekuasaan.",
        "Senjata terakhir adalah otak, yang lainnya hanyalah pelengkap.",
        "Jika kamu tidak mengatasi kecenderunganmu untuk mudah menyerah, hidupmu tidak mengarah ke mana-mana.",
        "Latihan itu seperti menyapu lantai. Hanya karena kita sudah melakukannya sekali bukan berarti lantainya bersih selamanya.",
        "Ingatlah bahwa kitalah yang menyiksa diri, kitalah yang membuat kesulitan untuk diri kita sendiri, yaitu opini kita yang melakukannya. Apa artinya dihina, misalnya? Berdirilah di samping batu dan hinakan, apa yang kamu capai? Jika seseorang merespons hinaan seperti batu, apa yang didapat si penghina?",
        "Tanpa tujuan, hidup menjadi perjalanan tanpa akhir menuju ketiadaan.",
        "Hanya orang mati yang telah melihat akhir perang.",
        "Mencegah lebih baik daripada mengobati.",
        "Tidak ada yang diajarkan dengan paksa yang tinggal di jiwa.",
        "Semua yang ada dalam hidupmu, ada karena dua hal: sesuatu yang kamu lakukan atau sesuatu yang tidak kamu lakukan.",
        "Manusia tanpa etika adalah binatang buas yang dilepas ke dunia ini.",
        "Berpikir itu sulit, itulah mengapa kebanyakan orang menghakimi.",
        "Kamu tidak menemukan kemauan, kamu menciptakannya.",
        "Kata bahagia akan kehilangan maknanya jika tidak diimbangi oleh kesedihan.",
        "Jangan berdoa untuk hidup yang mudah. Berdoalah untuk kekuatan menahan hidup yang sulit.",
        "Kamu bukan segalanya yang bisa kamu jadi, dan kamu tahu itu.",
        "Ingatlah untuk hidup sementara kamu sibuk bertahan hidup.",
        "Rencana bukan apa-apa, perencanaan adalah segalanya.",
        "Seseorang yang berani membuang satu jam waktunya belum menemukan nilai kehidupan.",
        "Kamu harus memutuskan siapa dirimu dan memaksa dunia untuk berurusan denganmu, bukan dengan ide mereka tentangmu.",
        "Seni hidup lebih menyerupai gulat daripada menari, sejauh ia siap menghadapi yang tak terduga dan tidak mudah jatuh.",
        "Seiring bertambahnya usia, aku semakin tidak memperhatikan apa yang dikatakan orang. Aku hanya mengamati apa yang mereka lakukan.",
        "Aku akan mengencangkan ikat pinggangku sebelum aku meminta bantuan.",
        "Tidak ada yang dibuat sepertimu, kamu merancang dirimu sendiri.",
        "Tidak ada pria yang berhak menjadi amatir dalam hal latihan fisik. Memalukan bagi seorang pria untuk menua tanpa melihat keindahan dan kekuatan yang mampu dicapai tubuhnya.",
        "Semakin dekat seseorang dengan pikiran yang tenang, semakin dekat dia dengan kekuatan.",
        "Ini aturan untuk diingat di masa depan, ketika sesuatu menggodamu untuk merasa pahit: bukan \"Ini kesialan,\" tapi \"Menanggung ini dengan bermartabat adalah keberuntungan.\"",
        "Ketika kamu pandai dalam sesuatu kamu memberitahu semua orang. Ketika kamu luar biasa dalam sesuatu, mereka yang memberitahumu.",
        "Pertama mereka mengabaikanmu. Lalu mereka mengejekmu. Lalu mereka menyerangmu dan ingin membakarmu. Dan kemudian mereka membangun monumen untukmu.",
        "Kebebasan berarti tanggung jawab. Itulah mengapa kebanyakan orang menakutinya.",
        "Jika kamu mengatakan yang sebenarnya, kamu tidak perlu mengingat apa pun.",
        "Waktumu akan datang jika kamu terus melangkah.",
        "Bukan kematian yang harus ditakuti seorang pria, tapi dia harus takut tidak pernah mulai hidup.",
        "Prosedur hari ini adalah hasil hari esok. Jika kamu bisa jatuh cinta pada prosedur hari ini kamu akan mencintai hasil hari esok.",
        "Semua masalah umat manusia berasal dari ketidakmampuan manusia untuk duduk diam sendirian di sebuah ruangan.",
        "Jangan pernah biarkan masa depan mengganggumu. Kamu akan menghadapinya, jika harus, dengan senjata akal yang sama yang hari ini mempersenjataimu melawan masa kini.",
        "Pria dewasa melalui rasa sakit, kegagalan, penolakan, kehilangan, ketidakhormatan, dan patah hati, bukan melalui usia.",
        "Kita menempa rantai yang kita kenakan dalam hidup.",
        "Untuk melakukan sesuatu pada tingkat tinggi, itu harus menjadi obsesi.",
        "Jika kamu ingin memperbaiki diri, bersedialah dianggap bodoh tentang hal-hal luar.",
        "Kekerasan adalah tempat perlindungan terakhir orang yang tidak kompeten.",
        "Takut itu seperti api, bisa berguna jika kamu tahu cara menggunakannya. Kalau tidak, kamu akan terbakar.",
        "Untuk berhasil besar, kamu harus siap gagal besar. Jika kamu tidak bisa melakukan keduanya, kamu punya masalah.",
        "Kita selalu bicara tentang seseorang yang tidak menyukai kita tanpa alasan, tapi orang juga akan menyukaimu tanpa alasan. Jadi jangan terlalu menaruh bobot pada kedua sisinya.",
        "Pengecut mati berkali-kali sebelum kematiannya; yang berani hanya merasakan kematian sekali.",
        "Tidak ada yang lebih sulit, dan karena itu lebih berharga, daripada mampu memutuskan.",
        "Berjalanlah di satu jalan, jangan sombong dalam kemenangan maupun hancur dalam kekalahan, tanpa melupakan kewaspadaan saat tenang atau menjadi takut saat bahaya mengancam.",
        "Jiwa diwarnai oleh warna pikirannya.",
        "Aku tidak meminta beban yang lebih ringan. Tapi bahu yang lebih lebar.",
        "Jangan bernegosiasi dengan dirimu sendiri. Instruksikan dirimu sendiri.",
        "Kamu tidak bisa menginginkan karakter yang kuat dan kehidupan yang mudah sekaligus.",
        "Keberanian bukan memiliki kekuatan untuk melanjutkan, tapi melanjutkan saat kamu tidak punya kekuatan.",
        "Hidup tidak terjadi padamu, ia terjadi melibatkanmu.",
        "Adalah fatal memasuki perang tanpa kemauan untuk memenangkannya.",
        "Kamu tidak pernah tahu seberapa kuatmu sampai menjadi kuat adalah satu-satunya pilihanmu.",
        "Tidak bisa menyenangkan semua orang, terkadang kamu harus bertindak dan biarkan orang lain bereaksi.",
        "Tidak ada soal \"jika\", yang ada hanya soal kapan, ketika kamu bulat tentang misinya.",
        "Berapa lama lagi kamu akan menunggu sebelum kamu menuntut yang terbaik untuk dirimu sendiri?",
        "Dunia menjanjikan kenyamanan, tapi kamu tidak diciptakan untuk kenyamanan. Kamu diciptakan untuk kebesaran.",
        "Integritas bukan jalan cepat, tapi jalan yang pasti.",
        "Jadilah penggemar terbesarmu sendiri, pendukung terbesarmu sendiri, dan letakkan di punggungmu dan pikul bebannya.",
        "Pertama katakan pada dirimu apa yang ingin kamu jadi; lalu lakukan apa yang harus kamu lakukan.",
        "Aku takut hari di mana teknologi akan melampaui interaksi manusia kita. Dunia akan memiliki generasi idiot.",
        "Bukan soal apa yang kamu tanggung, tapi bagaimana kamu menanggungnya.",
        "Tolak rasa sakitmu dan sakit itu sendiri menghilang.",
        "Jangan membuat rencana kecil. Mereka tidak punya keajaiban untuk mengaduk darah dan mungkin tidak akan terwujud. Buatlah rencana besar; bidik tinggi dalam harapan dan pekerjaan, mengingat bahwa diagram yang mulia dan logis yang pernah dicatat tidak akan pernah mati.",
        "Kesulitan sering mempersiapkan orang biasa untuk takdir yang luar biasa.",
        "Ketika kamu ingin mengubah sesuatu, kamu tidak bisa menyenangkan semua orang. Jika kamu menyenangkan semua orang, kamu tidak membuat cukup kemajuan.",
        "Jangan bernegosiasi dengan dirimu sendiri, instruksikan dirimu sendiri.",
        "Kesuksesan bukan final, kegagalan bukan fatal: keberanian untuk melanjutkan itulah yang diperhitungkan.",
        "Jika itu tidak benar jangan lakukan; jika itu tidak benar jangan katakan.",
        "Kesenangan yang disebut, ketika melampaui batas tertentu, hanyalah hukuman.",
        "Jika kamu tidak berkorban untuk apa yang kamu inginkan, apa yang kamu inginkan menjadi pengorbanannya.",
        "Musuh terbesarmu adalah pikiranmu yang tidak terkendali.",
        "Belajar bertarung agar kamu tidak pernah harus bertarung.",
        "Ketika seseorang tidak bisa menemukan makna yang mendalam, mereka mengalihkan diri dengan kesenangan.",
        "Tidak ada yang permanen di dunia yang jahat ini, bahkan masalah kita.",
        "Biarkan mereka salah tentangmu. Tidak ada yang perlu dibuktikan pada mereka.",
        "Jika kamu ingin masa kini berbeda dari masa lalu, pelajarilah masa lalu.",
        "Jika kamu ingin hidup bahagia, ikatkan pada tujuan, bukan pada orang atau benda.",
        "Tidak ada rahasia, hanya ada informasi yang sudah kamu temukan dan informasi yang belum kamu temukan.",
        "Kamu butuh motivasi untuk bertindak. Kamu butuh informasi untuk tahu apa yang harus ditindak. Kamu butuh keingintahuan untuk mendapatkan intelijen yang akan memandu tindakan bermotivasi ini. Jadi, jadilah penasaran.",
        "Pemenang hanyalah pecundang yang mencoba sekali lagi.",
        "Kita memperlakukan tubuh dengan keras agar tidak membangkang pada pikiran.",
        "Yang bersedia dipimpin oleh takdir, yang enggan diseret.",
        "Pria yang takut mati tidak akan pernah melakukan sesuatu yang layak bagi pria yang hidup.",
        "Seorang komandan tidak pernah begitu percaya pada perdamaian sehingga gagal mempersiapkan perang.",
        "Jangan takut. Kamu akan berhasil, tapi rasanya selalu seolah-olah kamu tidak.",
        "Konsistensi mungkin terdengar seperti membosankan, tapi menurutmu apa lagi yang membuat seseorang hebat? Keberuntungan?",
        "Selalu hadapkan wajahmu ke arah matahari dan bayangan akan jatuh di belakangmu.",
        "Hukuman terberat untuk menolak memimpin adalah dipimpin oleh seseorang yang lebih rendah dari dirimu.",
        "Galilah ke dalam. Di dalam ada mata air Kebaikan; dan ia selalu siap mengalir, jika kamu menggali.",
        "Kamu adalah apa yang kamu lakukan, bukan apa yang kamu katakan akan kamu lakukan.",
        "Salah dengan caramu sendiri lebih baik daripada benar dengan cara orang lain.",
        "Pria besar keras pada dirinya sendiri, pria lemah keras pada orang lain.",
        "Mencintai diri sendiri adalah awal dari romansa seumur hidup.",
        "Pedulikan apa yang orang lain pikirkan, dan kamu akan selalu menjadi tawanan mereka.",
        "Manusia tidak dikhawatirkan oleh masalah nyata sebanyak oleh kecemasan yang dia bayangkan tentang masalah nyata.",
        "Orang yang bahagia puas dengan situasinya saat ini, apa pun itu.",
        "Kemenangan pertama dan terbesar adalah menaklukkan diri sendiri.",
        "Untuk mengendalikan diriku, aku harus terlebih dahulu menerima diriku dengan mengikuti dan bukan melawan kodratku.",
        "Biarkan manusia melihat, biarkan mereka tahu seorang pria sejati yang hidup sebagaimana dia dimaksudkan untuk hidup.",
        "Siapa yang tidak bisa menaati dirinya sendiri akan diperintah.",
        "Ketika kamu takut akan sesuatu, pelajari sebanyak mungkin tentangnya. Pengetahuan menaklukkan ketakutan.",
        "Aku selalu mengira itu aku melawan dunia dan suatu hari aku menyadari itu hanya aku melawan diriku sendiri.",
        "Pria yang tidak punya tujuan mengalihkan diri dengan kesenangan.",
        "Sulit menerima bahwa semua orang tidak akan mengerti, tapi itulah mengapa itu bukan untuk orang lain. Itu urusanmu.",
        "Semakin besar kesulitannya, semakin besar kemuliaan dalam mengatasinya.",
        "Kita senang dengan keindahan kupu-kupu, tapi jarang mengakui perubahan yang telah dilaluinya untuk mencapai keindahan itu.",
        "Biarkan aku jatuh jika harus. Yang sedang aku jadi akan menangkapku.",
        "Di balik pria yang memaafkan segalanya, ada pria yang tahu berat dosanya sendiri.",
        "Upaya melarikan diri dari rasa sakit menciptakan lebih banyak rasa sakit.",
        "Perkembangan sejati tidak menghormati kenyamanan.",
        "Sejauh yang bisa kita ketahui, satu-satunya tujuan keberadaan manusia adalah menyalakan cahaya makna di dalam kegelapan keberadaan belaka.",
        "Hari kamu menanam benih bukan hari kamu memakan buahnya.",
        "Kebenaran tidak berubah karena ia dipercayai atau tidak dipercayai oleh mayoritas orang.",
        "Ksatria berbaju baja berkilau tidak punya nilai yang terbukti. Berikan padaku ksatria yang teruji pertempuran dengan baju baja yang usang dari perjumpaan dengan yang terburuk dari umat manusia.",
        "Ukuran kecerdasan adalah kemampuan untuk berubah.",
        "Tidak ada panen tanpa kelaparan.",
        "Pikiran itu sendirilah yang menyesatkan pikiran. Dari pikiran, janganlah lengah.",
        "Kamu tidak bisa memimpikan dirimu menjadi berkarakter; kamu harus menempa dan membentuk dirimu sendiri.",
        "Banyak yang akan salah sebelum semuanya menjadi benar.",
        "Kita hanya hidup sekarang. Yang lain sudah berlalu atau tidak diketahui.",
        "Kamu tidak akan dihukum karena amarahmu, kamu akan dihukum oleh amarahmu.",
        "Kamu tidak belajar berenang dengan membaca tentang air.",
        "Pilihan tersulit membutuhkan kemauan terkuat.",
        "Yang terpenting, jangan berbohong pada dirimu sendiri.",
        "Tubuhmu bisa menangani hampir segalanya; pikiranmu yang harus kamu yakinkan.",
        "Hidup bergenre orang pertama. Perlakukan seperti itu.",
        "Pemimpin yang baik tidak mencari alasan. Mereka menemukan cara untuk menyelesaikannya.",
        "Hanya karena itu membutuhkan waktu lebih lama bagimu daripada orang lain bukan berarti kamu gagal.",
        "Semakin kamu mengenal dirimu, semakin sedikit kamu butuh persetujuan orang lain.",
        "Mengenal dirimu sendiri adalah awal dari semua kebijaksanaan.",
        "Bukan ukuran tubuh seseorang tapi ukuran hatinya yang penting.",
        "Kecil kemungkinannya kamu berpindah tingkat tanpa air mata.",
        "Kamu membajak dengan bajak yang kamu punya.",
    ]
}
