// QuotesLang_vi.swift
// Spike AI — Bundled quote translations
import Foundation
enum QuotesLang_vi {
    static let quotes: [String] = [
        "Bất cứ điều gì bạn giữ trong tâm trí một cách nhất quán chính là điều bạn sẽ trải nghiệm trong cuộc sống.",
        "Chúng ta nhắm trên đích để trúng đích.",
        "Điều tệ nhất mà tôi có thể trở thành là giống hệt mọi người, tôi ghét điều đó.",
        "Chỉ những ai dám đi quá xa mới có thể khám phá được mình có thể đi bao xa.",
        "Hãy nhảy và lưới sẽ xuất hiện.",
        "Một con tàu trong bến cảng thì an toàn, nhưng đó không phải là mục đích con tàu được đóng ra.",
        "Đừng lo lắng về thất bại, hãy lo lắng về những cơ hội bạn bỏ lỡ khi không thử.",
        "Những ai dám thất bại thảm hại có thể đạt được thành tựu vĩ đại.",
        "Cách để bắt đầu là ngừng nói và bắt đầu làm.",
        "Chúng ta có thể gặp nhiều thất bại, nhưng không được đầu hàng.",
        "Thước đo thực sự của một người là cách anh ta đối xử với người không thể mang lại lợi ích gì cho mình.",
        "Bạn phải cẩn thận nếu không biết mình đang đi đâu, vì có thể bạn sẽ không đến được đó.",
        "Bạn phải kỳ vọng những điều vĩ đại từ chính mình trước khi có thể thực hiện chúng.",
        "Đừng bao giờ để những quyết định trong quá khứ quyết định kết quả tương lai của bạn.",
        "Đường tắt tạo ra sự chậm trễ kéo dài.",
        "Không ai có thể cho bạn mục tiêu. Đây là hành trình của bạn.",
        "Thế giới là những gì bạn nghĩ về nó, vì vậy hãy nghĩ khác đi và thế giới của bạn sẽ thay đổi.",
        "Tương lai thuộc về những ai chuẩn bị cho nó ngay hôm nay.",
        "Đừng từ bỏ điều bạn muốn nhất vì điều bạn muốn ngay bây giờ.",
        "Đừng nói với tôi bạn tài năng thế nào, hãy nói cho tôi bạn làm việc chăm chỉ ra sao.",
        "Cách bạn suy nghĩ khi thua quyết định bao lâu nữa bạn sẽ thắng.",
        "Bất cứ khi nào một người quyết định rằng đã đạt được thành công, sự tiến bộ dừng lại.",
        "Không vấn đề nào có thể chịu được sự tấn công của tư duy bền bỉ.",
        "May mắn là khi cơ hội đến và bạn đã sẵn sàng cho nó.",
        "Bí mật để tiến về phía trước là bắt đầu.",
        "Thời điểm tốt nhất để trồng một cái cây là 20 năm trước. Thời điểm tốt nhất thứ hai là ngay bây giờ.",
        "Rất khó để đánh bại một người không bao giờ bỏ cuộc.",
        "Hãy viết nó. Quay nó. Xuất bản nó. Đan nó. Xào nó. Bất cứ điều gì, hãy tạo ra!",
        "Dù bạn là gì, hãy là một người giỏi.",
        "Hạnh phúc không phải là thứ có sẵn, nó đến từ hành động của chính bạn.",
        "Người thông minh học hỏi từ mọi thứ và mọi người.",
        "Không thể chỉ là một quan điểm.",
        "Đam mê của bạn đang chờ sự can đảm của bạn bắt kịp.",
        "Những người thắc mắc ly nước nửa đầy hay nửa vơi đã bỏ lỡ điểm chính. Ly có thể được rót đầy lại.",
        "Một ngày nào đó hay ngày thứ nhất; bạn quyết định.",
        "Mọi thứ có thể đến với người chờ đợi, nhưng chỉ là những gì còn sót lại từ người chăm chỉ.",
        "Mọi thứ đến với người chăm chỉ trong lúc chờ đợi.",
        "Làm việc như thể có người làm việc 24 giờ mỗi ngày để lấy đi thành quả của bạn.",
        "Không ai tạo ra sự khác biệt bằng cách giống hệt mọi người.",
        "Bạn sẽ có những lúc tồi tệ, nhưng nó sẽ luôn đánh thức bạn nhận ra những điều tốt đẹp mà bạn không để ý.",
        "Hãy là phiên bản hạng nhất của chính mình, không phải phiên bản hạng hai của người khác.",
        "Hãy học từ sai lầm của người khác. Bạn không sống đủ lâu để tự mắc hết tất cả.",
        "Nếu bạn mệt, hãy cứ làm khi đang mệt.",
        "Một người không kết thúc khi bị đánh bại, anh ta kết thúc khi bỏ cuộc.",
        "Thế giới thay đổi bởi tấm gương của bạn, không phải bởi ý kiến của bạn.",
        "Cuộc sống giống như đi xe đạp. Để giữ thăng bằng, bạn phải tiếp tục di chuyển.",
        "Nghĩ về cuộc sống: không có lượng tội lỗi nào thay đổi được quá khứ, không có lượng lo lắng nào thay đổi được tương lai.",
        "Một tâm trí tiêu cực sẽ không bao giờ cho bạn một cuộc sống tích cực.",
        "Mọi thứ đều khó trước khi dễ.",
        "Hãy mạo hiểm, hoặc mất cơ hội.",
        "Đừng bao giờ ngừng học hỏi, vì cuộc sống không bao giờ ngừng dạy.",
        "Người không đọc sách chẳng hơn gì người không biết đọc.",
        "Người chưa bao giờ mắc sai lầm là người chưa bao giờ thử điều gì mới.",
        "Cách phổ biến nhất mà mọi người từ bỏ quyền lực là nghĩ rằng họ không có.",
        "Hãy biết ơn những gì bạn có; bạn sẽ có thêm. Chỉ tập trung vào những gì không có, bạn sẽ không bao giờ đủ.",
        "Điều khó khăn nhất là quyết định hành động, phần còn lại chỉ là sự kiên trì.",
        "Nhiều thất bại trong cuộc sống là những người không nhận ra họ gần thành công đến nhường nào khi họ bỏ cuộc.",
        "Không phải là bạn có bị đánh ngã hay không, mà là bạn có đứng dậy hay không.",
        "Người bi quan thấy khó khăn trong mọi cơ hội. Người lạc quan thấy cơ hội trong mọi khó khăn.",
        "Vinh quang lớn nhất không phải là không bao giờ ngã, mà là đứng dậy mỗi khi ngã.",
        "Đừng bị đẩy đi bởi nỗi sợ trong tâm trí; hãy được dẫn dắt bởi ước mơ trong trái tim.",
        "Khi bạn biết mình muốn gì và muốn nó đủ mạnh, bạn sẽ tìm ra cách.",
        "Hãy bắt đầu bằng việc làm điều cần thiết, rồi làm điều có thể, và bỗng nhiên bạn đang làm điều không thể.",
        "Không có đam mê thì không có năng lượng, không có năng lượng thì không có gì cả.",
        "Bạn không cần phải giỏi để bắt đầu, nhưng bạn phải bắt đầu để trở nên giỏi.",
        "Sức mạnh không đến từ thể chất, nó đến từ ý chí bất khuất.",
        "Không ai vô dụng trên thế gian này nếu họ giảm bớt gánh nặng cho người khác.",
        "Bằng cách đòi hỏi điều không thể, chúng ta đạt được điều có thể.",
        "Thà làm sư tử một ngày còn hơn làm cừu cả đời.",
        "Cuộc sống quá quan trọng để mà nghiêm túc.",
        "Khởi đầu là nửa của mọi hành động.",
        "Kiên nhẫn vô hạn mang lại kết quả tức thì.",
        "Gần như tất cả mọi người chết vì thuốc chữa chứ không phải vì bệnh.",
        "Họ có thể, bởi vì họ nghĩ họ có thể.",
        "Trí tưởng tượng quan trọng hơn kiến thức.",
        "Người kiên trì bắt đầu thành công ở nơi người khác kết thúc trong thất bại.",
        "Không có con đường rõ ràng. Chỉ có hố bẫy, dây vấp và bóng tối.",
        "Một sai lầm chứng minh rằng ai đó đã ngừng nói đủ lâu để làm điều gì đó.",
        "Bất cứ điều gì đáng làm thì đáng làm cho tốt.",
        "Người mạnh nhất là người có quyền lực trên chính mình.",
        "Một học giả trân trọng sự thoải mái không xứng đáng được gọi là học giả.",
        "Thịnh vượng phụ thuộc vào việc muốn những gì bạn có hơn là có những gì bạn muốn.",
        "Mỗi ngày mang đến món quà riêng, hãy tháo dải ruy băng.",
        "Thành công không bao giờ vĩnh viễn và thất bại không bao giờ là cuối cùng.",
        "Không gì tồn tại mãi mãi. Kể cả những rắc rối của bạn.",
        "Làm việc chăm chỉ không đảm bảo thành công, nhưng cải thiện cơ hội.",
        "Hòa bình không thể được duy trì bằng vũ lực. Nó chỉ có thể đạt được bằng sự hiểu biết.",
        "Ai không dám mạo hiểm thì không có may mắn.",
        "Đừng nói khi nào rảnh tôi sẽ học, có thể bạn không có lúc rảnh.",
        "Ai mất niềm tin thì mất tất cả.",
        "Suy nghĩ của một người là thế giới của họ. Người ta nghĩ gì thì trở thành điều đó.",
        "Phiêu lưu không nằm bên ngoài con người, nó nằm bên trong.",
        "Trò chơi cuộc đời không phải là cầm bài tốt, mà là chơi bài xấu cho giỏi.",
        "Chua, ngọt, đắng, cay; tất cả đều phải nếm thử.",
        "Đừng bao giờ để cảm giác thất bại trong quá khứ đánh bại bước tiếp theo.",
        "Nếu không có tham vọng, bạn không tiến bộ.",
        "Tương lai thuộc về những ai dám mơ.",
        "Sự thật không ngừng tồn tại vì bị phớt lờ.",
        "Chúng ta không bao giờ nên giả định điều không thể chứng minh.",
        "Giọng to không thể cạnh tranh với giọng rõ ràng, dù chỉ là tiếng thì thầm.",
        "Hành động như thể bạn mong đợi sẽ vào vùng ghi điểm.",
        "Hạnh phúc là bông hoa tự nhiên của nghĩa vụ.",
        "\"Không\" đơn giản có nghĩa là bắt đầu lại ở cấp độ cao hơn.",
        "Sự nhiệt tình lay chuyển thế giới.",
        "Nhà vô địch là người đứng dậy khi không thể.",
        "Trở ngại là cái giá của sự vĩ đại.",
        "Câu hỏi không phải là ai sẽ cho phép tôi, mà là ai sẽ ngăn cản tôi.",
        "Tôi không ở đó để thi đấu, tôi ở đó để chiến thắng.",
        "Ngừng than vãn, bắt đầu cày cuốc.",
        "Từ khó khăn, phép màu nảy nở.",
        "Tôi không sợ, tôi sinh ra để làm điều này.",
        "Đừng bao giờ cúi đầu. Hãy ngẩng cao. Nhìn thẳng vào thế giới.",
        "Hãy làm những gì phải làm cho đến khi có thể làm những gì muốn làm.",
        "Nếu bạn ngã hôm qua, hãy đứng dậy hôm nay.",
        "Hãy biến mỗi ngày thành kiệt tác.",
        "Máu, mồ hôi và sự tôn trọng. Hai thứ đầu bạn cho đi, thứ cuối bạn phải kiếm được.",
        "Hãy giỏi đến mức họ không thể phớt lờ bạn.",
        "Hãy cho thế giới thấy bạn sẽ chiến đấu vì vòng nguyệt quế đến đâu.",
        "Nếu bạn không thiết kế kế hoạch cuộc đời mình, bạn có thể rơi vào kế hoạch của người khác. Họ lên kế hoạch gì cho bạn? Không nhiều.",
        "Người duy nhất mà bạn được định sẵn để trở thành là người mà bạn quyết định.",
        "Đừng đợi sắt nóng rồi mới đập; hãy đập cho nó nóng lên.",
        "Tôi không thể tin rằng Chúa đặt chúng ta trên trái đất này để làm người bình thường.",
        "Tôi muốn thế giới tốt đẹp hơn vì tôi đã ở đây.",
        "Thói quen kiên trì là thói quen chiến thắng.",
        "Đừng sợ từ bỏ cái tốt để theo đuổi cái vĩ đại.",
        "Hãy làm bổn phận và thêm một chút nữa, tương lai sẽ tự lo liệu.",
        "Cuộc sống có cách thử thách ý chí con người. Hoặc không có gì xảy ra, hoặc mọi thứ xảy ra cùng lúc.",
        "Người khôn ngoan luôn được tìm thấy khi ở một mình. Kẻ yếu đuối luôn được tìm thấy trong đám đông.",
        "Dám là mất chỗ đứng trong chốc lát. Không dám là mất chính mình.",
        "Nỗi sợ đánh bại nhiều người hơn bất cứ thứ gì khác trên thế giới.",
        "Những lời nói mạnh mẽ nhất trong vũ trụ là những lời bạn dùng để nói với chính mình.",
        "Thứ duy nhất đến với người ngủ là giấc mơ.",
        "Nếu bạn không chinh phục bản thân, bạn sẽ bị bản thân chinh phục.",
        "Anh hùng là người biết cách cầm cự thêm một phút nữa.",
        "Hãy đi xa nhất có thể, khi đến nơi bạn sẽ có thể nhìn xa hơn.",
        "Bạn không tìm thấy vị trí của mình trên thế giới, bạn tạo ra nó.",
        "Người thắng tập trung vào chiến thắng. Kẻ thua tập trung vào người thắng.",
        "Thất bại sẽ không bao giờ đánh bại tôi nếu quyết tâm thành công đủ mạnh.",
        "Điều đến dễ dàng không bền lâu. Điều bền lâu không đến dễ dàng.",
        "Để tránh bị chỉ trích: không nói gì, không làm gì, không là gì.",
        "Người làm nhiều hơn mức được trả sẽ sớm được trả nhiều hơn mức họ làm.",
        "Thiên tài bắt đầu những công trình vĩ đại, chỉ có lao động mới hoàn thành chúng.",
        "Ngay cả khi bạn đi đúng đường, bạn vẫn bị cán nếu ngồi yên.",
        "Nếu mọi thứ không thất bại, bạn chưa đổi mới đủ.",
        "Bạn nhận được điều tốt nhất từ người khác khi cho đi điều tốt nhất của mình.",
        "Lãnh đạo là hành động, không phải vị trí.",
        "Công việc của chúng ta là sự thể hiện năng lực của chúng ta.",
        "Mọi vấn đề của tôi đều cúi đầu trước sự bướng bỉnh của tôi.",
        "Hãy đeo thất bại như huy chương danh dự.",
        "Chúng ta bị giới hạn không phải bởi khả năng, mà bởi tầm nhìn.",
        "Nếu bạn mệt, hãy học cách nghỉ ngơi, đừng bỏ cuộc.",
        "Ngã là tai nạn, nằm yên là lựa chọn.",
        "Đừng dám bỏ cuộc sống này. Không phải đêm nay. Không phải ngày mai. Không bao giờ.",
        "Đừng bao giờ để bản thân bị quật ngã bởi con người hay sự kiện.",
        "Một số người mơ về thành công trong khi người khác thức dậy và làm việc chăm chỉ.",
        "Tự tin đến từ kinh nghiệm. Kinh nghiệm đến từ việc thử và thất bại rồi thử lại - lần này tốt hơn.",
        "Thời gian dẫn đến sự thành thạo phụ thuộc vào cường độ tập trung.",
        "Thành công chỉ đến với những ai dám thử.",
        "Chìa khóa quan trọng cho thành công là sự tự tin. Chìa khóa quan trọng cho sự tự tin là sự chuẩn bị.",
        "Sự nghi ngờ giết chết nhiều giấc mơ hơn thất bại.",
        "Chiến thắng luôn khả thi cho người từ chối ngừng chiến đấu.",
        "Bạn sẽ không bao giờ thay đổi cuộc đời cho đến khi thay đổi điều bạn làm hàng ngày.",
        "Để thành công, sự tập trung của bạn phải mãnh liệt đến mức người khác nghĩ bạn điên.",
        "Trở ngại là những thứ đáng sợ bạn nhìn thấy khi rời mắt khỏi mục tiêu.",
        "Tìm kiếm cơ hội là vấn đề của việc tin rằng nó tồn tại.",
        "Đặt mục tiêu là bước đầu tiên biến vô hình thành hữu hình.",
        "Nếu bạn không mạo hiểm gì, bạn mạo hiểm tất cả.",
        "Nếu không thể thay đổi hoàn cảnh, hãy thay đổi suy nghĩ.",
        "Dù quá khứ khó khăn thế nào, bạn luôn có thể bắt đầu lại.",
        "Nếu bạn không dám làm gì, khi ngày kết thúc, không có gì là tất cả những gì bạn đạt được.",
        "Rất thường thay đổi bản thân cần thiết hơn thay đổi khung cảnh.",
        "Sợ hãi là khuyết tật lớn nhất và sẽ làm bạn tê liệt.",
        "Điều nguy hiểm là không tiến hóa.",
        "Dù thế nào tôi cũng sẽ tìm đường hoặc tạo đường.",
        "Cách duy nhất để bịt miệng mọi người là chiến thắng.",
        "Đừng bao giờ để đủ tốt trở thành đủ tốt.",
        "Về lâu dài, chúng ta chỉ trúng thứ chúng ta nhắm.",
        "Cải thiện liên tục tốt hơn sự hoàn hảo bị trì hoãn.",
        "Nếu bạn thấy nó trong tâm trí, bạn sẽ nắm nó trong tay.",
        "Hôm nay tôi sẽ làm điều người khác không làm, để ngày mai tôi có thể làm điều người khác không thể.",
        "Sự xuất sắc là nghệ thuật được chinh phục bằng luyện tập và thói quen.",
        "Năm tới sẽ trôi qua dù bạn có làm gì với cuộc đời hay không.",
        "Đừng dừng khi mệt, hãy dừng khi xong.",
        "Bạn chỉ cách tâm trạng tốt một buổi tập luyện.",
        "Hãy làm điều đúng đắn, không phải điều dễ dàng hay phổ biến.",
        "Không điều vĩ đại nào đến dễ dàng.",
        "Không có đấu tranh thì không có tiến bộ.",
        "Người thành công hỏi những câu hỏi hay hơn và nhận được câu trả lời hay hơn.",
        "Tôi không có tài năng đặc biệt, tôi chỉ say mê tò mò.",
        "Bài học tốt nhất mà tôi học được trong đời đến từ cảm giác tồi tệ nhất tôi từng trải.",
        "Thử thách là điều làm cuộc sống thú vị. Vượt qua chúng là điều làm cuộc sống có ý nghĩa.",
        "Hãy học cách vui với cách tiếp cận thử, thất bại, học hỏi không ngừng.",
        "Nếu bạn đóng cửa trước mọi sai lầm, sự thật cũng sẽ bị khóa ngoài.",
        "Hãy quên sai lầm, nhớ bài học.",
        "Nếu bạn chỉ làm được những gì bạn có thể, bạn sẽ không bao giờ hơn những gì bạn đang là.",
        "Ai là người khôn ngoan? Người học hỏi từ mọi người.",
        "Chỉ tôi mới có thể thay đổi cuộc đời mình, không ai làm thay được.",
        "Kiên trì là thất bại 19 lần và thành công lần thứ 20.",
        "Tôi cho rằng thành công của tôi nhờ điều này: tôi không bao giờ đưa ra hay chấp nhận bất kỳ lý do nào.",
        "Tôi không phải sản phẩm của hoàn cảnh. Tôi là sản phẩm của những quyết định.",
        "Hành động của chúng ta định hình chúng ta cũng như chúng ta định hình hành động.",
        "Chỉ những người cực kỳ ngu dốt hoặc cực kỳ thông minh mới có thể chống lại sự thay đổi.",
        "Người tự tin sẽ nhận được sự tin tưởng từ người khác.",
        "Điều bạn tìm kiếm cũng đang tìm kiếm bạn.",
        "Đừng lo về thất bại. Bạn chỉ cần đúng một lần.",
        "An toàn phần lớn là mê tín. Cuộc sống hoặc là một cuộc phiêu lưu táo bạo hoặc chẳng là gì.",
        "Chúng ta trở thành những gì chúng ta nghĩ nhiều nhất và đó là bí mật kỳ lạ nhất.",
        "Cách để bắt đầu là ngừng nói và bắt đầu làm.",
        "Hãy biến mỗi ngày thành kiệt tác.",
        "Dù bạn mắc bao nhiêu sai lầm hay tiến bộ chậm thế nào, bạn vẫn đi trước những người không thử.",
        "Thái độ của chúng ta khi bắt đầu một nhiệm vụ khó khăn, hơn bất cứ điều gì khác, sẽ ảnh hưởng đến kết quả thành công.",
        "Sự an toàn thực sự duy nhất là dự trữ kiến thức, kinh nghiệm và khả năng.",
        "Những gì bạn làm hôm nay có thể thay đổi mọi ngày mai của cuộc đời.",
        "Cuộc sống không tốt hơn nhờ may mắn, nó tốt hơn nhờ thay đổi.",
        "Giấc mơ không thành hiện thực bằng phép thuật, nó cần mồ hôi, quyết tâm và làm việc chăm chỉ.",
        "Kiến thức là biết cà chua là trái cây. Trí tuệ là không cho nó vào salad trái cây.",
        "Dù tình huống thế nào, hãy nhắc nhở mình: \"Tôi có lựa chọn\".",
        "Hãy trị vì tâm trí bạn hoặc nó sẽ trị vì bạn.",
        "Một số thành công vì số phận, nhưng phần lớn thành công vì quyết tâm.",
        "Cơ hội lớn không được nhìn thấy bằng mắt, mà bằng tâm trí.",
        "Ai không đủ can đảm mạo hiểm sẽ không đạt được gì trong đời.",
        "Biết thôi không đủ, phải ứng dụng. Muốn thôi không đủ, phải hành động.",
        "Tham vọng là con đường đến thành công, kiên trì là phương tiện bạn đến nơi.",
        "Chìa khóa cuộc sống là chấp nhận thử thách. Khi ai đó ngừng làm điều này, anh ta đã chết.",
        "Cam kết là thứ biến lời hứa thành hiện thực.",
        "Tự tin là ký ức về thành công.",
        "Không có sự tự tin, chúng ta chỉ như trẻ sơ sinh trong nôi.",
        "Dám mơ, nhưng quan trọng hơn là dám hành động theo ước mơ.",
        "Trung thực là chương đầu tiên trong cuốn sách trí tuệ.",
        "Xuất sắc là một quá trình liên tục, không phải tai nạn.",
        "Hy vọng là khả năng nhìn thấy ánh sáng giữa mọi bóng tối.",
        "Chúng ta phải chấp nhận sự thất vọng hữu hạn, nhưng không bao giờ mất hy vọng vô hạn.",
        "Dấu hiệu thực sự của trí tuệ không phải kiến thức, mà là trí tưởng tượng.",
        "Hãy nghiện cải thiện bản thân liên tục và không ngừng.",
        "Thiên tài là một phần trăm cảm hứng và chín mươi chín phần trăm mồ hôi.",
        "Bạn không thể chờ cảm hứng, bạn phải đuổi theo nó bằng gậy.",
        "Hãy kiên nhẫn. Mọi thứ đều khó trước khi trở nên dễ.",
        "Người nói không thể làm được không nên ngắt lời người đang làm.",
        "Kiên trì là công việc nặng nhọc bạn làm sau khi mệt mỏi với công việc nặng nhọc đã làm.",
        "Người khôn ngoan có thể học nhiều từ câu hỏi ngốc hơn kẻ ngốc có thể học từ câu trả lời khôn.",
        "Bằng kỷ luật và tự kiểm soát liên tục, bạn có thể phát triển sự vĩ đại của tính cách.",
        "Kiểm soát cảm xúc là kết quả của làm việc chăm chỉ, không phải kỹ năng bẩm sinh.",
        "Học cách học là kỹ năng quan trọng nhất của cuộc đời.",
        "Đừng để những gì không làm được ngăn cản những gì làm được.",
        "Bạn luôn đi qua thất bại trên đường đến thành công.",
        "Không ai hoàn hảo, đó là lý do bút chì có tẩy.",
        "Đừng bao giờ để xác suất ngăn bạn làm điều bạn biết trong tim mình là điều bạn phải làm.",
        "Nếu nhìn kỹ, hầu hết thành công qua đêm mất rất lâu.",
        "Bất cứ điều gì cũng có thể. Bất cứ điều gì cũng có thể xảy ra.",
        "Không gì đặc biệt khó nếu bạn chia nhỏ thành các công việc nhỏ.",
        "Bí mật của thành công là làm những điều bình thường một cách phi thường.",
        "Hành động như thể những gì bạn làm tạo ra sự khác biệt, vì nó thực sự có.",
        "Điều bạn nhận được khi đạt mục tiêu không quan trọng bằng điều bạn trở thành khi đạt mục tiêu.",
        "Cuộc sống giống như đi xe đạp; để giữ thăng bằng bạn phải tiếp tục di chuyển.",
        "Hãy hạn chế những từ \"luôn luôn\" và \"không bao giờ\".",
        "Bạn không bao giờ quá già để đặt mục tiêu mới hay mơ giấc mơ mới.",
        "Bạn không tìm thấy cuộc sống hạnh phúc, bạn tạo ra nó.",
        "Tin xấu là thời gian trôi nhanh. Tin tốt là bạn là phi công.",
        "Hãy luôn hướng mặt về phía ánh nắng và bóng tối sẽ ngã phía sau bạn.",
        "Sự khác biệt giữa không thể và có thể nằm ở quyết tâm của con người.",
        "Huy chương vàng không thực sự làm từ vàng. Chúng làm từ mồ hôi, quyết tâm và hợp kim khó tìm gọi là lòng can đảm.",
        "Đừng đánh giá thấp quyết tâm của người trầm lặng.",
        "Đừng nói cho tôi bạn tin gì. Tôi sẽ quan sát hành vi của bạn và tự đưa ra kết luận.",
        "Tôi chỉ ghét thua và điều đó cho tôi thêm quyết tâm làm việc chăm chỉ hơn.",
        "Quyết tâm chiến thắng là phần tốt hơn của chiến thắng.",
        "Bạn có thể có tất cả tài năng trên đời, nhưng không có quyết tâm thì không đi xa.",
        "Chiến thắng là con đẻ của sự chuẩn bị và quyết tâm.",
        "Người trẻ biết luật, nhưng người già biết ngoại lệ.",
        "Người bi quan phàn nàn về gió, người lạc quan mong nó đổi, người thực tế điều chỉnh cánh buồm.",
        "Kiến thức không có giá trị nếu bạn không đưa vào thực hành.",
        "Tôi thà hối hận vì những gì đã làm hơn là hối hận vì những gì không làm.",
        "Cần có trí tuệ để hiểu trí tuệ. Âm nhạc vô nghĩa nếu khán giả điếc.",
        "Mối nguy lớn hơn cho chúng ta không phải là đặt mục tiêu quá cao rồi trượt, mà là đặt quá thấp rồi đạt được.",
        "Trong mỗi cuộc dạo bước với thiên nhiên, ta nhận được nhiều hơn ta tìm kiếm.",
        "Tôi sẽ không đi theo nơi con đường có thể dẫn, nhưng tôi sẽ đi nơi không có đường và để lại dấu vết.",
        "Cây sồi hùng vĩ hôm nay chỉ là hạt dẻ hôm qua đã kiên trì.",
        "Hoàn toàn trung thực với bản thân là một bài tập tốt.",
        "Chúng ta không thể trở thành những gì cần trở thành bằng cách giữ nguyên những gì đang là.",
        "Hãy định hướng bằng những vì sao, không phải bằng ánh đèn của mỗi con tàu đi qua.",
        "Nếu không biết đi đâu, con đường nào cũng đưa bạn đến đó.",
        "Bạn luôn có hai lựa chọn: cam kết hay nỗi sợ.",
        "Phúc cho ai cho mà không nhớ và nhận mà không quên.",
        "Điều xảy ra không quan trọng bằng cách bạn phản ứng với nó.",
        "Hãy bắt đầu với điều đúng đắn thay vì điều chấp nhận được.",
        "Người ưu việt trách bản thân. Kẻ kém cỏi trách người khác.",
        "Hành động nhỏ nhất tốt hơn ý định vĩ đại nhất.",
        "Trở ngại lớn nhất cho khám phá không phải là thiếu hiểu biết, mà là ảo tưởng về kiến thức.",
        "Cẩn thận với kiến thức giả, nó nguy hiểm hơn sự thiếu hiểu biết.",
        "Cách tốt nhất để dự đoán tương lai là sáng tạo ra nó.",
        "Thắng mà không mạo hiểm là thắng mà không vinh quang.",
        "Tính cách của chúng ta là những gì chúng ta làm khi nghĩ không ai nhìn.",
        "Mọi thứ khiến ta bực mình về người khác có thể dẫn ta đến hiểu chính mình.",
        "Nghệ thuật khôn ngoan là nghệ thuật biết bỏ qua điều gì.",
        "Nói cho tôi thì tôi quên. Dạy cho tôi thì tôi nhớ. Cho tôi tham gia thì tôi học.",
        "Bạn có bộ não trong đầu. Bạn có đôi chân trong giày. Bạn có thể lái mình đi bất cứ hướng nào bạn chọn.",
        "Bằng ba từ tôi có thể tóm tắt mọi thứ về cuộc sống: nó tiếp diễn.",
        "Cuộc sống là thử mọi thứ xem có hiệu quả không.",
        "Thành công thường đến với những người quá bận để tìm kiếm nó.",
        "Tôi không thất bại, tôi chỉ tìm ra 10.000 cách không hiệu quả.",
        "Tôi đã thất bại trên con đường đến thành công.",
        "Nếu bạn không lập trình cho mình, cuộc sống sẽ lập trình cho bạn.",
        "Tôi không có thời gian để thương hại bản thân. Tôi không có thời gian để phàn nàn. Tôi sẽ tiến về phía trước.",
        "Nếu bạn không sẵn sàng mạo hiểm cái bình thường, bạn sẽ phải chấp nhận cái tầm thường.",
        "Thành công được định nghĩa là khả năng đi từ thất bại này đến thất bại khác mà không mất nhiệt huyết.",
        "Mọi ước mơ đều có thể thành hiện thực nếu chúng ta có can đảm theo đuổi.",
        "Cơ hội không tự xảy ra, bạn tạo ra chúng.",
        "Tôi chưa bao giờ mơ về thành công, tôi làm việc vì nó.",
        "Đừng để những gì không thể cản trở những gì có thể.",
        "Hôm nay là ngày duy nhất, hôm qua đã qua.",
        "Mọi thứ tốt nhất cho người biết tận dụng tốt nhất những gì xảy ra.",
        "Nếu bạn đang đi qua địa ngục, hãy tiếp tục đi.",
        "Bạn chỉ thấy vinh quang công khai. Không bao giờ thấy những hy sinh thầm lặng để đạt được chúng.",
        "Nếu bạn không trân trọng thời gian của mình, người khác cũng sẽ không.",
        "Không ai có thể khiến bạn cảm thấy thua kém mà không có sự đồng ý của bạn.",
        "Người thành công là người có thể xây nền móng vững chắc bằng những viên gạch người khác ném vào anh ta.",
        "Điều có vẻ là thử thách cay đắng thường là phước lành trá hình.",
        "Không gì phổ biến trên thế giới hơn những người có tài nhưng không thành công.",
        "Đừng cố trở thành người thành công, mà hãy cố trở thành người có giá trị.",
        "Nếu bạn không thể giải thích đơn giản, bạn chưa hiểu đủ rõ.",
        "Bạn không bao giờ thất bại cho đến khi ngừng cố gắng.",
        "Kiến thức là biết bạn có thể làm gì. Trí tuệ là biết khi nào không nên.",
        "Cuộc sống không phải là tìm thấy bản thân. Cuộc sống là tạo ra bản thân.",
        "Vấn đề không phải là vấn đề, vấn đề là thái độ của bạn về vấn đề.",
        "Không kiệt tác nào được tạo ra bởi một nghệ sĩ lười biếng.",
        "Con đường đến thành công và con đường đến thất bại gần như giống hệt nhau.",
        "Quan trọng không phải bạn nhìn gì, mà là bạn thấy gì.",
        "Can đảm là chống lại nỗi sợ - làm chủ nỗi sợ, không phải vắng mặt nỗi sợ.",
        "Tôi thấy rằng tôi càng làm việc chăm chỉ thì càng may mắn.",
        "Sự ấm áp của một ý nghĩ tốt đẹp có giá trị hơn tiền bạc.",
        "Mọi tiến bộ diễn ra ngoài vùng thoải mái.",
        "Tư duy nên trở thành tài sản vốn của bạn, bất kể thăng trầm trong cuộc sống.",
        "Thành công là tổng hợp của những nỗ lực nhỏ được lặp đi lặp lại ngày này qua ngày khác.",
        "Chiến binh thành công là người bình thường với sự tập trung như tia laser.",
        "Thành công không phải là không bao giờ mắc sai lầm, mà là không mắc cùng một lỗi lần thứ hai.",
        "Đừng để nỗi sợ thua lớn hơn sự phấn khích khi thắng.",
        "Bước đầu tiên là khi bạn từ chối bị giam cầm bởi môi trường.",
        "Không có tắc đường trên con đường phụ thêm.",
        "Bất cứ khi nào bạn thấy mình ở phía đa số, đó là lúc nên dừng lại và suy ngẫm.",
        "Thành công là thích bản thân, thích những gì bạn làm, và thích cách bạn làm nó.",
        "Mục tiêu không phải lúc nào cũng để đạt được, nó thường chỉ là thứ để nhắm đến.",
        "Thất bại trong sự sáng tạo còn hơn thành công trong sự bắt chước.",
        "Động lực giúp bạn bắt đầu, thói quen giúp bạn tiếp tục.",
        "Bạn phải thức dậy mỗi sáng với quyết tâm nếu muốn đi ngủ với sự hài lòng.",
        "Bạn phải kỳ vọng những điều vĩ đại từ chính mình trước khi có thể thực hiện.",
        "Khó khăn thực sự có thể vượt qua, chỉ những khó khăn tưởng tượng mới bất khả chiến thắng.",
        "Người ta hiếm khi thành công nếu không vui với điều họ đang làm.",
        "Trong những khoảnh khắc đen tối nhất, chúng ta phải tập trung để nhìn thấy ánh sáng.",
        "Thất bại là gia vị tạo hương vị cho thành công.",
        "Tâm trí bị bất hạnh khuất phục, nhưng tâm trí vĩ đại vượt lên trên nó.",
        "Bạn có thể phải chiến đấu một trận nhiều hơn một lần để thắng.",
        "Bạn sẽ làm gì nếu không sợ?",
        "Điều tốt đến với người chờ đợi, nhưng điều tốt hơn đến với người ra ngoài tìm kiếm.",
        "Luôn cố gắng hết sức, ngay cả khi cơ hội chống lại bạn.",
        "Đừng chờ cảm xúc thay đổi rồi mới hành động, hãy hành động và cảm xúc sẽ thay đổi.",
        "Hành động không phải lúc nào cũng mang lại hạnh phúc, nhưng không có hạnh phúc mà không hành động.",
        "Hoàn hảo thì nhàm chán, trở nên tốt hơn mới là nơi có niềm vui.",
        "Rất khó để đánh bại một người không bao giờ bỏ cuộc.",
        "Sự khác biệt giữa hòn đá vấp ngã và bậc thang tiến lên là bạn nhấc chân cao bao nhiêu.",
        "Đừng bao giờ bỏ cuộc vì đó chính là lúc và nơi thủy triều sẽ quay.",
        "Đôi khi không đạt được điều mong muốn là một may mắn tuyệt vời.",
        "Tôi không thể thay đổi hướng gió, nhưng tôi có thể điều chỉnh cánh buồm để luôn đến đích.",
        "Tiến lên phía trước. Đừng dừng lại, đừng nấn ná, hãy nỗ lực vì mục tiêu phía trước.",
        "Nếu bạn thực sự muốn điều gì đó, đừng chờ đợi, hãy tự dạy mình thiếu kiên nhẫn.",
        "Đôi khi bạn thắng, đôi khi bạn học.",
        "Hai loại người trên đời: người muốn hoàn thành việc và người không muốn mắc sai lầm.",
        "Hãy chắc chắn kẻ thù tồi tệ nhất của bạn không sống giữa hai tai bạn.",
        "Hãy luôn nhớ bạn hoàn toàn độc đáo, giống hệt mọi người khác.",
        "Nếu bạn kiểm soát được mọi thứ, bạn chưa đi đủ nhanh.",
        "Một cách để duy trì đà là liên tục có mục tiêu lớn hơn.",
        "Bạn không cần thấy cả cầu thang, chỉ cần bước bước đầu tiên.",
        "Điều có vẻ là thử thách cay đắng thường là phước lành trá hình.",
        "Với cam kết, có hai lựa chọn: bạn ở trong hoặc ở ngoài - không có chuyện nửa vời.",
        "Khi bạn muốn điều gì đó, cả vũ trụ sẽ hợp lực giúp bạn đạt được.",
        "Hạnh phúc không phải thứ có sẵn, nó đến từ hành động của chính bạn.",
        "Dù bạn là gì, hãy là một người giỏi.",
        "Đau đớn là tất yếu, khổ đau là lựa chọn.",
        "Tài năng trúng mục tiêu không ai trúng được; thiên tài trúng mục tiêu không ai nhìn thấy.",
        "Tâm trí là nơi của riêng nó và có thể biến thiên đường thành địa ngục, hay địa ngục thành thiên đường.",
        "Tôi ghét tập luyện, nhưng tôi nói 'đừng bỏ cuộc' - chịu đau bây giờ và sống phần đời còn lại như nhà vô địch.",
        "Không phải ngọn núi phía trước khiến bạn kiệt sức, mà là viên sỏi trong giày.",
        "Chúng ta nghĩ gì, chúng ta trở thành điều đó.",
        "Có người ngồi trong bóng râm hôm nay, vì ai đó đã trồng cây từ lâu.",
        "Một tia nắng đủ để xua tan nhiều bóng tối.",
        "Với tâm trí tĩnh lặng, cả vũ trụ đều quy phục.",
        "Với kỷ luật tự thân, hầu hết mọi thứ đều có thể.",
        "Lối ra tốt nhất luôn là đi xuyên qua.",
        "Cơ hội lớn của bạn có thể ngay nơi bạn đang đứng.",
        "Không gì có giá trị hơn ngày hôm nay.",
        "Hành trình duy nhất là hành trình bên trong.",
        "Hoàn cảnh không quyết định bạn có thể đi đâu, chúng chỉ xác định bạn bắt đầu từ đâu.",
        "Niềm tin tạo ra sự thật.",
        "Điều làm sa mạc đẹp là đâu đó nó giấu một giếng nước.",
        "Nếu cánh cửa nhận thức được tẩy sạch, mọi thứ sẽ hiện ra vô tận như bản chất của nó.",
        "Hãy thay đổi suy nghĩ và bạn sẽ thay đổi thế giới.",
        "Con chim được vận hành bởi chính cuộc sống và động lực của nó.",
        "Hãy trao ánh sáng và mọi người sẽ tìm thấy đường.",
        "Sự chuẩn bị tốt nhất cho ngày mai là làm hết sức hôm nay.",
        "Ý tưởng định hình dòng chảy lịch sử.",
        "Không phải mọi viên ngọc cuộc đời đều xâu trên một sợi dây.",
        "Những gì chúng ta đạt được bên trong sẽ thay đổi thực tại bên ngoài.",
        "Quyết tâm thành công của chính bạn quan trọng hơn bất cứ điều gì khác.",
        "Bạn biết mình đang trên đường thành công nếu bạn sẽ làm công việc đó mà không được trả tiền.",
        "Bạn trở thành những gì bạn tin.",
        "Nếu muốn đạt xuất sắc, bạn có thể đạt ngay hôm nay. Từ giây phút này, ngừng làm việc dưới mức xuất sắc.",
        "Nếu bạn không sẵn sàng mạo hiểm cái bình thường, bạn sẽ phải chấp nhận cái tầm thường.",
        "Trước hết, sự chuẩn bị là chìa khóa thành công.",
        "Tôi đã học được rằng khi tâm trí đã quyết, nỗi sợ sẽ giảm đi.",
        "Cuộc sống được tạo nên từ rất nhiều cuộc chia ly, hàn lại với nhau.",
        "Chiến thắng không phải là tất cả, nhưng muốn chiến thắng mới là tất cả.",
        "Bạn có thể thất vọng nếu thất bại, nhưng bạn sẽ tiêu đời nếu không thử.",
        "Sai lầm là thực tế cuộc sống, quan trọng là phản ứng với sai lầm.",
        "Nếu không thích con đường đang đi, hãy bắt đầu mở đường mới.",
        "Hành động nói to hơn lời nói, và điều này càng đúng với con cái.",
        "Kim cương là cục than đá đã chịu đựng tốt dưới áp lực.",
        "Những con đường khó khăn thường dẫn đến đích đến tươi đẹp.",
        "Đôi khi bạn sẽ không biết giá trị của một khoảnh khắc cho đến khi nó thành ký ức.",
        "Không gì có thể dập tắt ánh sáng tỏa ra từ bên trong.",
        "Để thành công trong cuộc sống, bạn cần ba thứ: xương ước nguyện, xương sống, và xương hài hước.",
        "Những ai không tin vào phép thuật sẽ không bao giờ tìm thấy nó.",
        "Tôi quyết định rằng không thể trả tiền ai để tua lại thời gian, nên thôi bỏ qua.",
        "Mọi thứ đều có giá, bạn sẵn sàng trả bao nhiêu?",
        "Tôi trưởng thành nhất không phải từ chiến thắng, mà từ thất bại.",
        "Tôi may mắn rằng dù nỗi sợ bên trong có thế nào, khát vọng chiến thắng luôn mạnh hơn.",
        "Bạn phải tin vào chính mình khi không ai tin.",
        "Đừng sợ thất bại, đây là con đường dẫn đến thành công.",
        "Tôi thích sự chỉ trích, nó làm bạn mạnh mẽ hơn.",
        "Tôi biết tôi luôn muốn làm hết sức mình.",
        "Mọi người thành công mà tôi gặp đều là người nghiện công việc.",
        "Tôi chưa bao giờ cạnh tranh với ai, ngoại trừ chính mình.",
        "Tin vào bản thân và biết mình là ai, đó là nền tảng cho mọi điều vĩ đại.",
        "Tôi sợ không được thử.",
        "Cách chuộc lại quá khứ không phải chạy trốn nó, mà là cố hiểu nó và dùng nó làm nền tảng để phát triển.",
        "An toàn chẳng mang lại gì cho bạn trên đời này.",
        "Chiêu hay là chiêu hay, nhưng với người vô tài thì không hiệu quả. Cuối cùng vẫn là tài năng.",
        "Bạn hoặc tiến hóa, hoặc biến mất.",
        "Hạt giống phải mọc, bất kể nó được gieo trên đá.",
        "Dù khó khăn thế nào, hãy ưỡn ngực, ngẩng đầu, và xử lý nó.",
        "Luôn làm hết sức, đừng để áp lực khiến bạn hoảng loạn.",
        "Bạn không bao giờ biết khi nào hoặc thế nào bạn sẽ có tác động, hay tấm gương của bạn quan trọng với ai đó ra sao.",
        "Hãy làm những gì phải làm, để làm được những gì muốn làm.",
        "Đừng mong kiếm sống, hãy mong tạo ra sự khác biệt.",
        "Phải là chính mình trên đời này, dù thế nào đi nữa.",
        "Nếu bạn có kẻ thù, hãy tìm hiểu kẻ thù, đừng chỉ giận dữ.",
        "Tôi phấn đấu để giống những con người vĩ đại nhất từng sống.",
        "Nơi tôi vượt trội là đạo đức làm việc điên cuồng. Khi người khác ngủ, tôi làm việc.",
        "Cuộc sống sống trên bờ vực.",
        "Thực tế là con đường phổ biến nhất dẫn đến sự tầm thường.",
        "Bước đầu tiên là bạn phải nói rằng bạn có thể.",
        "Thế giới không thể nói cho bạn biết bạn là ai, bạn phải tự tìm ra và là chính mình, dù tốt hay xấu.",
        "Bạn sẽ phải nhận ra thất bại. Phải đối mặt và tìm cách vượt qua.",
        "Cha tôi nói: Hãy đặt giá từ đầu. Nếu nó trở nên đắt hơn giá bạn đặt, hãy rời đi.",
        "Bạn có tin vào điều bạn tin nếu bạn là người duy nhất tin không?",
        "Tôi không quan tâm người khác nghĩ gì, vì người ta không nghĩ.",
        "Tôi chưa bao giờ thực sự giỏi gì ngoại trừ khả năng học hỏi.",
        "Cảm giác tuyệt vời nhất thế giới là thấy lợi ích và phần thưởng từ sự chăm chỉ.",
        "Mục tiêu của tôi cao đến mức tôi không có thời gian thư giãn dưới bất kỳ hình thức nào.",
        "Đời quá ngắn để lo lắng người khác nói gì về bạn.",
        "Đằng sau mọi người thành công là một bầy kẻ ganh ghét.",
        "Bạn có thể tạo dựng cuộc đời, nó chỉ phụ thuộc vào động lực của bạn.",
        "Bạn có kẻ thù? Tốt, nghĩa là bạn đã đứng lên vì điều gì đó.",
        "Mọi thành công bắt đầu từ kỷ luật tự thân, nó bắt đầu từ bạn.",
        "Với động lực và chút tài năng, bạn có thể dời núi.",
        "Thất bại không phải lựa chọn, nó chỉ là một bước.",
        "Thành công không phải qua đêm, mà là mỗi ngày bạn tốt hơn ngày hôm trước; tất cả cộng lại.",
        "Khi cuộc sống đặt bạn vào tình huống khó khăn, đừng nói 'tại sao tôi', hãy nói 'thử tôi đi'.",
        "Thành công luôn quy về: tập trung và nỗ lực. Và chúng ta kiểm soát cả hai.",
        "Tôi từng nghe một người khôn ngoan nói không có người hoàn hảo, chỉ có ý định hoàn hảo.",
        "Rất thường bạn dừng bước vì nói 'tôi mệt leo đồi này rồi, không bao giờ lên đỉnh được' và bạn chỉ cách đỉnh hai bước.",
        "Hãy thách thức bản thân, đó là con đường duy nhất dẫn đến phát triển.",
        "Bạn không thể nhận công vì tài năng, bạn chỉ có thể nhận công vì sử dụng nó.",
        "Cách tốt nhất để đảm bảo thua là bỏ cuộc.",
        "Tôi có thể ngồi xem nó xảy ra hoặc tham gia vào.",
        "Khi điều gì đó đủ quan trọng, bạn sẽ làm, dù cơ hội không thuận lợi.",
        "Nếu bạn thức dậy buổi sáng và nghĩ tương lai sẽ tốt hơn, đó là ngày tươi sáng, nếu không thì không.",
        "Không sao khi bỏ tất cả trứng vào một giỏ, miễn là bạn kiểm soát được giỏ đó.",
        "Nếu bạn chỉ làm những thứ biết trước câu trả lời, công ty sẽ biến mất.",
        "Bạn phải sẵn sàng bị hiểu lầm nếu muốn đổi mới.",
        "Không có thời điểm tồi để đổi mới.",
        "Tạo cơ hội nghĩa là nhìn nơi người khác không nhìn.",
        "Vốn mồ hôi là loại vốn có giá trị nhất.",
        "Chúng ta sống trong xã hội mà hầu như luôn luôn, làm việc chăm chỉ được đền đáp.",
        "Vũ trụ không có nghĩa vụ phải có ý nghĩa với bạn.",
        "Không có nền giáo dục nào tốt hơn tự học.",
        "Không ai ngu nếu biết tò mò.",
        "Tôi không biết thời điểm nào trong lịch sử nhân loại mà sự thiếu hiểu biết tốt hơn kiến thức.",
        "Hãy tập để không coi gì là chuyện cá nhân.",
        "Một người có thể trở thành bất cứ gì nếu thực sự tin, nhưng phải sẵn sàng cho công việc nặng nhọc và nhiều đau khổ.",
        "Điều mà mỗi chúng ta phải nhận ra là ý định của chúng ta luôn được bộc lộ.",
        "Chúng ta không thể phớt lờ những gì thực sự muốn tạo ra.",
        "Chỉ bạn và chỉ bạn mới có thể thay đổi tình huống của mình.",
        "Hãy biết ơn những lúc khó khăn, vì chúng đã tạo nên bạn.",
        "Để gia nhập nhóm 1% hàng đầu, bạn phải làm điều 99% không chịu làm.",
        "Tôi tạo con đường riêng, nó thẳng và hẹp. Tôi nhìn nó thế này: bạn hoặc cản đường tôi hoặc tránh sang.",
        "Tất cả chúng ta đều có sự nghi ngờ bản thân. Bạn không phủ nhận nó, nhưng cũng không đầu hàng nó. Bạn ôm lấy nó.",
        "Nhiều lãnh đạo thất bại vì thiếu can đảm chạm vào dây thần kinh đó.",
        "Khoảnh khắc bạn bỏ cuộc là khoảnh khắc bạn để người khác thắng.",
        "Nếu bạn sợ thất bại thì có lẽ bạn sẽ thất bại.",
        "Tôi nhận ra rằng sự đe dọa không thực sự tồn tại, nếu bạn ở đúng trạng thái tinh thần.",
        "Đây là khoảnh khắc tôi chấp nhận rằng những thời điểm thử thách nhất sẽ luôn ở phía sau và phía trước tôi.",
        "Không ai biết họ sẽ là nhà vô địch - bạn phải làm việc để đến đó.",
        "Niềm tin của tôi mạnh hơn sự nghi ngờ của bạn.",
        "Thành công nghĩa là hài lòng với những gì bạn làm mỗi ngày. Là tự hào về con người tốt đẹp hơn mà bạn đang trở thành.",
        "Nếu muốn thành công, bạn phải sẵn sàng sử dụng mọi mối quan hệ.",
        "Tài năng không bao giờ đủ. Với vài ngoại lệ, những cầu thủ giỏi nhất là những người chăm chỉ nhất.",
        "Đừng bỏ cuộc, hãy kết bạn với người giúp bạn làm việc chăm chỉ.",
        "Chỉ cần mừng cuộc đời bạn có, không phải cuộc đời bạn có thể có.",
        "Tôi lớn lên nghèo khó, nhưng tôi không có giấc mơ nghèo khó.",
        "Bạn là người duy nhất có thể tạo ra sự khác biệt. Dù ước mơ là gì, hãy theo đuổi nó.",
        "Cuộc sống không dừng lại vì điều gì đó xảy ra với bạn.",
        "Trong cuộc sống, cả thắng và thua đều sẽ xảy ra, điều không thể chấp nhận là bỏ cuộc.",
        "Các bạn có biết tôi đã bị từ chối bao nhiêu lần trong đời không? Bị nói bao nhiêu lần rằng tôi không thể?",
        "Nhiều khi tôi thấy người có tài năng nhất không bao giờ phát triển thái độ đó. Và người không có tài lại cạnh tranh nhất và có trái tim lớn nhất.",
        "Tôi nghĩ sẽ không bao giờ có cơ hội chơi, cho đến một lần tôi đã được, vì tôi đã chuẩn bị và cơ hội đến.",
        "Tôi chỉ yêu sự cạnh tranh và yêu cố gắng cải thiện.",
        "Quá thường xuyên trong cuộc sống, điều gì đó xảy ra, và chúng ta đổ lỗi người khác vì không hạnh phúc hay thỏa mãn.",
        "Cuộc đời bạn sẽ là những gì bạn tạo ra.",
        "Tôi sẽ không buồn vì ai đó nói xấu tôi.",
        "Bạn không thể ngồi ở bên lề trong cuộc sống.",
        "Thông điệp của tôi rất đơn giản: hãy kiểm soát cuộc đời bạn.",
        "Khi bạn là một trong những người lãnh đạo đội, không có ngày nghỉ.",
        "Đừng dựa vào người khác. Bạn sẽ nhận được sự hỗ trợ tuyệt vời từ nhiều người, nhưng không ai sẽ trao cho bạn bất cứ thứ gì.",
        "Mọi thứ không tự sửa; bạn phải ra ngoài và làm việc chăm chỉ để sửa chúng.",
        "Nếu không chơi để thắng, đừng chơi.",
        "Nếu bạn không tin vào chính mình, sao người khác tin bạn được.",
        "Đôi khi trong cuộc sống, những thử thách lớn nhất lại là điều tốt nhất xảy ra.",
        "Tôi chỉ yêu làm việc chăm chỉ.",
        "Những đối thủ thực sự là người luôn chơi để thắng.",
        "Đừng đuổi theo tiền, hãy đuổi theo ước mơ.",
        "Nếu muốn bay, bạn phải buông bỏ những thứ kéo bạn xuống.",
        "Tôi không muốn bạn mơ, tôi muốn bạn hành động.",
        "Bất cứ ai muốn trở thành ai đó sẽ làm việc chăm chỉ hết mức để thực hiện ước mơ.",
        "Tôi chưa bao giờ cố giấu sự thật rằng ý định của tôi là trở thành người giỏi nhất.",
        "Nếu bạn không tin mình là giỏi nhất, bạn sẽ không bao giờ đạt được tất cả những gì có thể.",
        "Hôm nay có những cơ hội mà không ai biết liệu chúng có quay lại trong tương lai.",
        "Tài năng mà không chăm chỉ thì vô nghĩa.",
        "Tôi không ngại người ghét tôi, vì nó thúc đẩy tôi.",
        "Tài năng không phải tất cả. Bạn có thể có nó từ khi sinh ra, nhưng cần phải học nghề để trở thành giỏi nhất.",
        "Tôi cảm thấy nhu cầu không ngừng để học, cải thiện, tiến hóa - để thấy hài lòng với bản thân.",
        "Tình yêu của bạn làm tôi mạnh mẽ. Sự ghét bỏ của bạn làm tôi không thể ngăn cản.",
        "Bạn có thể vượt qua bất cứ điều gì nếu và chỉ nếu bạn yêu điều gì đó đủ mạnh.",
        "Tôi thành công vì tôi đã hy sinh cho thành công.",
        "Tham vọng của tôi luôn là ngày càng tốt hơn.",
        "Tôi bắt đầu sớm và ở lại muộn. Ngày này qua ngày khác, năm này qua năm khác, tôi mất 17 năm và 114 ngày để trở thành thành công qua đêm.",
        "Người ngăn cản hạnh phúc của tôi chính là tôi.",
        "Hành động đơn giản của sự chú ý có thể đưa bạn đi rất xa.",
        "Đừng nhầm lẫn sự thật với ý kiến đám đông. Chúng hầu như không bao giờ gần nhau.",
        "Có sự khác biệt giữa biết đường và đi đường.",
        "Tôi không có thời gian thức khuya lo lắng về những gì người không yêu tôi nói.",
        "Bạn không thể do dự về con người mình.",
        "Luôn có thứ cần cải thiện, bạn không bao giờ đến đích.",
        "Tôi muốn trở thành điều tôi luôn muốn: thống trị.",
        "Tôi chỉ cố gắng là tốt nhất có thể và hy vọng đó là tốt nhất từ trước đến nay.",
        "Tôi không muốn giỏi như trước, tôi muốn giỏi hơn.",
        "Tâm trí là tài sản lớn nhất của tôi. Tôi kỳ vọng thắng mọi giải đấu tôi tham gia.",
        "Những người thực sự kiểm soát cảm xúc mới là người chiến thắng.",
        "Dù bạn giỏi thế nào, bạn luôn có thể tốt hơn, và đó là phần thú vị.",
        "Để giúp người khác, bạn phải học cách giúp chính mình trước.",
        "Không gì có giá trị đến với người ta ngoại trừ kết quả của sự chăm chỉ.",
        "Tôi sẽ không để ai hạ thấp linh hồn mình bằng cách khiến tôi ghét họ.",
        "Bạn không thể ghì người khác xuống mà không phải ở dưới cùng họ.",
        "Tính cách, không phải hoàn cảnh, tạo nên con người.",
        "Có hai cách dùng sức: một là đè xuống, hai là kéo lên.",
        "Tôi đã thất bại nhiều hơn thành công rất nhiều.",
        "Tôi làm hôm nay điều người khác không, để đạt được ngày mai điều người khác không thể.",
        "Dù thua, đừng thua bài học.",
        "Thứ dễ bán nhất là sự thật.",
        "Đừng chờ thời điểm hoàn hảo, bạn sẽ chờ mãi. Hãy tận dụng thời gian và biến nó thành hoàn hảo.",
        "Bạn chỉ có thể làm vài thứ tuyệt vời, và nên bỏ qua mọi thứ khác.",
        "Cuộc sống mong manh. Chúng ta không được đảm bảo ngày mai nên hãy cống hiến hết mình.",
        "Tôi không sợ tự làm mình trông ngốc.",
        "Sự tôn trọng thúc đẩy tôi, không phải thành công.",
        "Khi bạn qua đỉnh đồi, đó là lúc bạn tăng tốc.",
        "Xuất sắc không phải là hành động, đó là thói quen.",
        "Bạn không thể đạt điểm A nếu sợ điểm F.",
        "Bạn mắc sai lầm để học cách đến được điều tốt đẹp.",
        "Anh hùng là người tự nguyện bước vào điều chưa biết.",
        "Có hàng triệu người sống sót ngoài kia. Hãy thêm một người nữa.",
        "Đừng bao giờ bỏ cuộc, vì bạn không biết thủy triều sẽ mang gì đến ngày mai.",
        "Nếu nó không khó thì ai cũng làm được. Chính sự khó khăn tạo nên sự vĩ đại.",
        "Nếu bạn chỉ chơi an toàn với lựa chọn, bạn không phát triển.",
        "Tôi thích làm điều mình sợ.",
        "Quá trình là phần đẹp nhất.",
        "Dễ đánh lừa mắt, nhưng khó đánh lừa trái tim.",
        "Đừng lên quá cao, đừng xuống quá thấp. Từng ngày một, và tiếp tục học hỏi.",
        "Nỗ lực sẽ không bao giờ bị đặt câu hỏi.",
        "Đừng hy vọng ai cho bạn cơ hội: hãy tự tạo cho mình.",
        "Khi mọi người nói tôi không bao giờ làm được, tôi lắng nghe người duy nhất nói tôi có thể: chính tôi.",
        "Có lý do người ta gọi là đuổi theo ước mơ chứ không phải đi bộ theo nó.",
        "Để có được điều bạn thực sự muốn, trước tiên bạn phải là con người thực sự của mình.",
        "Đừng để quá khứ ám ảnh bạn. Vì điều bạn làm ở hiện tại có thể ám ảnh tương lai, hãy khôn ngoan. Điều bạn làm bây giờ hay tương lai không thể che giấu quá khứ, nhưng đừng để quá khứ kiểm soát bạn.",
        "Câu \"giá mà\" là vết thương không bao giờ lành.",
        "Nếu nó dễ thì nó không đáng.",
        "Bạn không xứng đáng được gì, bạn phải kiếm lấy.",
        "Sự hoàn hảo không thú vị, vượt qua thử thách mới ấn tượng.",
        "Đừng tham gia thế vận hội 'thương hại tôi'; chúng tôi không thi môn đó.",
        "Khi bạn muốn điều gì, bạn chấp nhận địa hình đi kèm, bất kể là gì.",
        "Tầm nhìn thực sự là khi tâm trí bạn mạnh hơn những gì trước mắt.",
        "Một số sự kiện sẽ đẩy bạn tiến lên, một số sẽ làm ngược lại - tưởng vậy. Những điều ngược lại đó là cơ hội học hỏi sẽ hữu ích trong tương lai.",
        "Trả giá để làm chủ hoặc trả giá cho sự hối tiếc.",
        "Ý kiến của người khác về bạn không nhất thiết phải trở thành thực tại của bạn.",
        "Bạn không nhận được điều mong ước, bạn nhận được điều mình làm việc vì nó.",
        "Kỷ luật tự thân bắt đầu từ việc làm chủ suy nghĩ. Nếu không kiểm soát được nghĩ gì, bạn không kiểm soát được làm gì. Đơn giản, kỷ luật tự thân giúp bạn nghĩ trước rồi hành động sau.",
        "Thất bại là gì? Không gì ngoài giáo dục; không gì ngoài bước đầu tiên đến điều tốt hơn.",
        "Không phải chuyện gì xảy ra với bạn, mà là cách bạn phản ứng mới quan trọng.",
        "Kiểm soát cơn giận. Nếu bạn tức giận người khác, họ kiểm soát bạn.",
        "Thử thách lớn nhất là xuất hiện khi tâm trí đang tạo lý do hay nhất.",
        "Bạn có thể trải nghiệm nỗi đau của kỷ luật, hoặc nỗi đau của hối tiếc. Lựa chọn là của bạn.",
        "Bất cứ điều gì làm bạn yếu đi về thể chất, trí tuệ và tinh thần; hãy từ chối như thuốc độc.",
        "Đổ mồ hôi nhiều hơn trong hòa bình, đổ máu ít hơn trong chiến tranh.",
        "Với can đảm để bắt đầu và kỷ luật để kiên trì, chiến thắng chỉ là vấn đề thời gian.",
        "Nhà lãnh đạo giỏi là người nhận nhiều hơn phần trách nhiệm và ít hơn phần công trạng.",
        "Hãy mạnh mẽ nhưng đừng thô lỗ. Tử tế nhưng đừng yếu đuối. Táo bạo nhưng đừng bắt nạt. Khiêm tốn nhưng đừng nhút nhát. Tự hào nhưng đừng kiêu ngạo.",
        "Kiên nhẫn thì đắng, nhưng quả của nó ngọt ngào.",
        "Kiên nhẫn không phải thụ động; ngược lại, nó là sức mạnh tập trung.",
        "Không gì là không thể với người dám thử.",
        "Trí tuệ không phải khả năng lưu trữ thông tin, mà là biết tìm ở đâu.",
        "Đầu tiên là ý định. Rồi hành vi. Rồi thói quen. Rồi thực hành. Rồi bản chất thứ hai. Rồi đơn giản là con người bạn.",
        "Bất cứ điều gì bạn muốn làm, hãy làm ngay. Chỉ có giới hạn ngày mai.",
        "Người nói không thể làm không nên ngắt lời người đang làm.",
        "Chỉ có một góc vũ trụ bạn chắc chắn có thể cải thiện, và đó là chính bạn.",
        "Kẻ ngốc nghĩ mình khôn, nhưng người khôn biết mình ngốc.",
        "Đau đớn có thể thay đổi bạn, nhưng không nhất thiết là thay đổi xấu. Hãy biến nỗi đau thành trí tuệ.",
        "Thời gian thực sự là vốn duy nhất mà con người có, và là thứ duy nhất không thể để mất.",
        "Hãy đi theo con đường riêng, bất kể người ta nói gì.",
        "Hãy làm gì đó. Nếu hiệu quả, làm thêm. Nếu không, làm thứ khác.",
        "Học hỏi là thứ duy nhất tâm trí không bao giờ kiệt sức, không bao giờ sợ, và không bao giờ hối tiếc.",
        "Người chiến thắng là người mơ mà không bao giờ bỏ cuộc.",
        "Nếu bạn không chiến đấu vì điều mình muốn, đừng khóc vì điều mình mất.",
        "Khi bạn đã chấp nhận khuyết điểm, không ai có thể dùng chúng chống lại bạn.",
        "Khi chúng ta hiểu đủ về vũ trụ, chúng ta sẽ thừa nhận rằng sẽ không bao giờ biết tất cả.",
        "Lo lắng giống như trả một khoản nợ bạn không nợ.",
        "Bạn không thể dạy ai bất cứ điều gì, chỉ có thể giúp họ nhận ra câu trả lời đã có sẵn bên trong.",
        "Sức mạnh của suy nghĩ có thể gây bệnh hoặc chữa lành cho bạn.",
        "Nếu bạn muốn thấy phép màu, hãy là phép màu.",
        "Có ba loại người: người nhìn thấy, người thấy khi được chỉ cho, và người không nhìn thấy.",
        "Nỗi sợ lớn nhất của bạn được tạo ra bởi trí tưởng tượng.",
        "Sự lừa dối lớn nhất mà con người chịu đựng là từ chính ý kiến của mình.",
        "Khi bạn đã cạn kiệt mọi khả năng, hãy nhớ: bạn chưa.",
        "Hãy yêu lá bài số phận chia cho bạn và chơi nó như của riêng mình.",
        "Nếu hai người đồng ý mọi thứ, một người là thừa.",
        "Cuộc cạnh tranh vĩ đại nhất là cuộc cạnh tranh với chính mình.",
        "Khi chúng ta mệt mỏi, chúng ta bị tấn công bởi những ý tưởng mà chúng ta đã chinh phục từ lâu.",
        "Tôi không phải là những gì đã xảy ra với tôi. Tôi là những gì tôi chọn trở thành.",
        "Yếu tố quan trọng nhất trong sinh tồn không phải trí tuệ hay sức mạnh, mà là khả năng thích nghi.",
        "Niềm tin và nỗi sợ đều đòi hỏi bạn tin vào điều không thể thấy. Bạn chọn.",
        "Bằng cách phàn nàn, bạn cho người khác biết bạn yếu đuối thế nào.",
        "Để có được điều bạn yêu, trước tiên bạn phải kiên nhẫn với điều bạn ghét.",
        "Khi mọi thứ dường như chống lại bạn, hãy nhớ rằng máy bay cất cánh ngược gió, không phải xuôi gió.",
        "Bạn sẽ cười nhạo nỗi sợ của mình khi phát hiện ra mình thực sự là ai.",
        "Bình an không tìm thấy trong cơn bão êm hơn, mà trong con thuyền tốt hơn.",
        "Bạn có thể phớt lờ thực tại, nhưng không thể phớt lờ hậu quả của việc phớt lờ thực tại.",
        "Không ai bất hạnh hơn người chưa bao giờ đối mặt nghịch cảnh. Vì anh ta không được phép chứng minh bản thân.",
        "Một kế hoạch tốt thực hiện mãnh liệt ngay bây giờ tốt hơn kế hoạch hoàn hảo tuần sau.",
        "Học mà không suy nghĩ là lãng phí. Suy nghĩ mà không học là nguy hiểm.",
        "Sợ hãi là phản ứng. Can đảm là quyết định.",
        "Độc lập chỉ dành cho số ít; đó là đặc quyền của kẻ mạnh.",
        "Phải mất nửa đời người trước khi nhận ra cuộc đời là dự án tự làm.",
        "Hãy thực hiện vai trò của bạn với danh dự.",
        "Lo lắng là sử dụng trí tưởng tượng sai cách.",
        "Cầu nối giữa kiến thức và kỹ năng là luyện tập. Cầu nối giữa kỹ năng và sự thành thạo là thời gian.",
        "Tôi càng học nhiều, tôi càng nhận ra còn phải học nhiều biết bao.",
        "Nếu bạn không thua, bạn không thể tận hưởng chiến thắng. Vì vậy tôi phải chấp nhận cả hai.",
        "Chúng ta học ít từ chiến thắng, nhiều từ thất bại.",
        "Kẻ nói năng lễ phép nhưng tăng cường chuẩn bị sẽ tiến lên. Kẻ nói hung hăng và tiến nhanh sẽ rút lui.",
        "Cuộc sống của chúng ta là những gì suy nghĩ tạo nên.",
        "Thực ra không có gì khó, trừ khi bạn quyết định nó khó. Nếu không, nó chỉ là điều tiếp theo bạn đang tìm ra.",
        "Dù tình huống thế nào, đừng bao giờ để cảm xúc lấn át trí tuệ.",
        "Hãy quyết định kiểu người bạn muốn trở thành và giữ vững, dù ở một mình hay trong đám đông.",
        "Nếu có gì sai, hãy sửa nếu có thể. Nhưng hãy tập để không lo lắng. Lo lắng không sửa được gì.",
        "Cuộc sống không phải là cầm bài tốt, mà là chơi bài xấu cho hay.",
        "Con đường gập ghềnh dẫn đến đỉnh cao vĩ đại.",
        "Ngày mà con người vượt lên trên khoái lạc, anh ta cũng sẽ vượt lên trên đau khổ.",
        "Hãy liên tục học hỏi, luôn có \"thêm một điều\" để học.",
        "Chúng ta có thể phàn nàn vì bụi hồng có gai, hoặc vui mừng vì bụi gai có hoa hồng.",
        "Hãy kiên nhẫn và mạnh mẽ; ngày nào đó nỗi đau này sẽ có ích cho bạn.",
        "Thất bại là thành công đang tiến hành.",
        "Ai ngừng học là già, dù ở tuổi hai mươi hay tám mươi.",
        "Nếu tâm trí trị vì bạn, bạn là vua; nếu thân xác trị vì, bạn là nô lệ.",
        "Kiêu ngạo không phải mặt đối lập của xấu hổ, mà là nguồn gốc của nó. Khiêm tốn thực sự là liều thuốc giải duy nhất cho sự xấu hổ.",
        "Khi bạn bắt đầu cải thiện bản thân, cô đơn là cái giá phải trả.",
        "Bạn không được đánh giá bởi độ cao đã đạt, mà bởi chiều sâu đã leo lên.",
        "Một người không vĩ đại vì chưa bao giờ thất bại; vĩ đại vì thất bại không ngăn được anh ta.",
        "Người không có tầm nhìn là người không có tương lai. Người không có tương lai sẽ luôn quay về quá khứ.",
        "Thà thất bại với danh dự còn hơn thành công bằng gian lận.",
        "Mọi trận chiến đều thắng hoặc thua trong tâm trí trước.",
        "Cảm xúc con người bị khuấy động nhanh hơn trí tuệ.",
        "Ai mua thứ không cần là ăn cắp của chính mình.",
        "Ai có kiên nhẫn sẽ có được điều mình muốn.",
        "Con đường của chiến binh là suốt đời, và sự thành thạo thường chỉ đơn giản là ở trên con đường.",
        "Diều bay cao nhất khi ngược gió, không phải xuôi gió.",
        "Nếu người ta biết tôi phải làm việc chăm chỉ thế nào để đạt được sự thành thạo, nó sẽ chẳng tuyệt vời chút nào.",
        "Đừng bao giờ đi ngủ mà không gửi yêu cầu đến tiềm thức.",
        "Hãy đón nhận sự kiện dù xảy ra thế nào: đây là con đường đến bình an.",
        "Hãy luyện tập ngay cả điều tưởng chừng không thể.",
        "Người đuổi hai con thỏ chẳng bắt được con nào.",
        "Bạn sẽ vượt qua, nhưng sẽ luôn cảm thấy như không thể.",
        "Hãy lập kế hoạch cho điều khó khi nó còn dễ, làm điều vĩ đại khi nó còn nhỏ.",
        "Kiên trì thôi chưa đủ. Phải quyết định kiên trì như người chịu đau hay như chiến binh.",
        "Mức độ sắc bén và kỷ luật cần thiết để đưa bạn đến đỉnh cao mà bạn mơ thì rất đơn giản, chỉ là không dễ.",
        "Kẻ thù lớn nhất không ở bên ngoài. Sự hủy diệt thường đến từ bên trong.",
        "Mọi người đều biết nó bất khả thi, cho đến khi một kẻ ngốc không biết đến và làm được.",
        "Bạn không thể làm người yếu mạnh lên bằng cách làm người mạnh yếu đi.",
        "Bạn có quyền lực trên tâm trí - không phải trên sự kiện bên ngoài. Hãy nhận ra điều này, và bạn sẽ tìm thấy sức mạnh.",
        "Kim cương chỉ là cục than đá đã hoàn thành nhiệm vụ.",
        "Rủi ro lớn nhất là không mạo hiểm gì.",
        "Nếu bạn định nghĩa đúng vấn đề, bạn gần như đã có giải pháp.",
        "Quá khứ ở trong đầu, tương lai ở trong tay.",
        "Cuộc sống khá đơn giản. Bạn làm vài thứ. Phần lớn thất bại. Vài thứ hiệu quả. Hãy làm thêm thứ hiệu quả.",
        "Mong rằng ý thức về bổn phận của bạn vượt lên bầu không khí sợ hãi và xu hướng trì hoãn khát vọng.",
        "Mọi thứ bạn từng muốn đều ở phía bên kia của nỗi sợ.",
        "Kỷ luật là chọn giữa điều bạn muốn bây giờ và điều bạn muốn nhất.",
        "Rập khuôn là nơi trú ẩn cuối cùng của kẻ thiếu trí tưởng tượng.",
        "Kim cương là cục than đá đã bám trụ với công việc.",
        "Không có tác hại nào lớn hơn cho con người bằng thời gian lãng phí.",
        "Đừng phá hỏng những gì bạn có bằng cách khao khát những gì chưa có; hãy nhớ rằng những gì bạn có bây giờ từng là những gì bạn chỉ hy vọng.",
        "Người làm chủ sự kiên nhẫn là làm chủ mọi thứ khác.",
        "Đừng bao giờ đặt đam mê trước nguyên tắc, dù bạn có thắng, bạn vẫn thua.",
        "Một số người muốn nó xảy ra, một số ước nó xảy ra, người khác làm cho nó xảy ra.",
        "Chúng ta không vươn lên mức kỳ vọng, chúng ta tụt xuống mức huấn luyện.",
        "Dễ tìm người tình nguyện chết hơn tìm người sẵn sàng chịu đau với kiên nhẫn.",
        "Bạn không thể mong lên bục nếu không tham gia cuộc đua.",
        "Người ngã rồi đứng dậy mạnh hơn người chưa bao giờ thử.",
        "Tin xấu: Bạn sẽ không 'hợp' với mọi người. Tin tốt: Những người vĩ đại không bao giờ hợp.",
        "Tôi chưa bao giờ có tài năng, tôi chỉ giỏi không bao giờ bỏ cuộc.",
        "Hạnh phúc không phải là không có vấn đề, mà là khả năng đối phó với chúng.",
        "Nếu bạn làm điều dễ, cuộc đời sẽ khó.",
        "Bạn không thể quay lại thay đổi khởi đầu, nhưng có thể bắt đầu từ đây và thay đổi kết thúc.",
        "Được bắt chước nhiều hơn được dạy.",
        "Người không bao giờ mắc sai lầm làm việc cho những người mắc sai lầm.",
        "Một ý tưởng mới không nên bị đánh giá bởi kết quả tức thì.",
        "Bạn không bao giờ sẵn sàng cho điều phải làm. Bạn cứ làm. Điều đó khiến bạn sẵn sàng.",
        "Hãy mạo hiểm: nếu thắng, bạn sẽ hạnh phúc; nếu thua, bạn sẽ khôn ngoan.",
        "Một dân tộc coi trọng đặc quyền hơn nguyên tắc sẽ sớm mất cả hai.",
        "Con đường nhanh nhất đến ý nghĩa và thành công: chọn một thứ và dốc hết sức.",
        "Đừng sợ bắt đầu lại. Lần này, bạn không bắt đầu từ đầu. Bạn bắt đầu từ kinh nghiệm.",
        "Không có gì cao quý trong việc hơn người khác; sự cao quý thực sự là hơn chính mình ngày hôm qua.",
        "Bạn sẽ nhận được sự tôn trọng của mọi người nếu bắt đầu bằng việc tôn trọng chính mình.",
        "Hãy tạo ra hình ảnh về người bạn muốn trở thành, rồi sống theo hình ảnh đó như thể nó đã là sự thật.",
        "Giá của sự xuất sắc là kỷ luật. Cái giá của sự tầm thường là thất vọng.",
        "Khó khăn rèn luyện tâm trí, như lao động rèn luyện thân thể.",
        "Bạn không thể hy vọng tiến bộ trong lĩnh vực mà bạn không hành động.",
        "Không có lượng lo lắng nào tạo ra bất kỳ sự khác biệt nào cho điều sắp xảy ra.",
        "Cho tôi thấy người có khả năng trung bình nhưng khao khát phi thường và tôi sẽ cho bạn thấy người chiến thắng mọi lúc.",
        "Cách nhanh nhất để thành công là bắt đầu ngay và tìm ra trong lúc đi.",
        "Người ta không quyết định tương lai, họ quyết định thói quen và thói quen quyết định tương lai.",
        "Hãy dạy con sớm điều bạn học muộn.",
        "Nếu bạn dành 100 giờ mỗi năm cho bất kỳ lĩnh vực nào, chỉ 18 phút mỗi ngày, bạn sẽ giỏi hơn 95% thế giới trong lĩnh vực đó.",
        "Nhiệm vụ không phải là nhìn thấy điều chưa ai thấy, mà là nghĩ điều chưa ai nghĩ về thứ mà ai cũng thấy.",
        "Nếu bạn khó chịu với mọi va chạm, gương của bạn sẽ được đánh bóng thế nào?",
        "Nỗi sợ chỉ sâu bằng mức tâm trí cho phép.",
        "Khó khăn là thứ đánh thức thiên tài.",
        "Cái gì phải tỏa sáng thì phải chịu đựng được lửa đốt.",
        "Tôi đã học được rằng thành công không nên đo bằng vị trí đạt được, mà bằng những trở ngại đã vượt qua.",
        "Sự thoải mái là cơn nghiện tệ nhất.",
        "Bạn trở thành thứ bạn dành sự chú ý cho.",
        "Hoàn cảnh không tạo nên con người, chúng chỉ phơi bày con người trước chính mình.",
        "Đừng lãng phí thêm thời gian tranh luận người tốt nên thế nào. Hãy là người tốt đi.",
        "Ai muốn lay chuyển thế giới, hãy tự lay chuyển mình trước.",
        "Giữa kích thích và phản ứng có một khoảng trống. Trong khoảng trống đó là quyền lực chọn phản ứng. Trong phản ứng là sự trưởng thành và tự do.",
        "Không có gì bên ngoài bạn có thể giúp bạn tốt hơn, mạnh hơn, giàu hơn, nhanh hơn hay thông minh hơn. Mọi thứ ở bên trong. Mọi thứ đã tồn tại. Đừng tìm kiếm gì bên ngoài bản thân.",
        "Hãy khoan dung với người khác và nghiêm khắc với bản thân.",
        "Hai thứ định nghĩa bạn: Sự kiên nhẫn khi không có gì và thái độ khi có tất cả.",
        "Bạn không chỉ thức dậy và trở thành bướm.",
        "Sự bền bỉ là khả năng bám trụ khi buông tay có vẻ hấp dẫn nhất.",
        "Có rủi ro và chi phí cho hành động. Nhưng chúng ít hơn nhiều so với rủi ro dài hạn của sự bất động thoải mái.",
        "Để đạt được điều vĩ đại, cần hai thứ: một kế hoạch, và không đủ thời gian.",
        "Nghi ngờ chỉ có thể được loại bỏ bằng hành động.",
        "Nếu hành động của bạn truyền cảm hứng cho người khác mơ nhiều hơn, học nhiều hơn, làm nhiều hơn và trở nên nhiều hơn, bạn là nhà lãnh đạo.",
        "Không phải là có hồ sơ không tì vết. Mà là học từ những vết tì trên hồ sơ.",
        "Hãy đủ can đảm để tệ ở điều gì đó mới.",
        "Hãy đi ngủ thông minh hơn lúc thức dậy.",
        "Thành công chậm xây dựng tính cách, thành công nhanh xây dựng cái tôi.",
        "Chỉ vì ai đó vấp ngã và lạc đường, không có nghĩa họ mất mãi mãi.",
        "Nhưng chúng ta không thể ngồi nhìn vết thương mãi mãi.",
        "Và giờ khi không cần hoàn hảo, bạn có thể là người tốt.",
        "Thành công đến từ việc thực hiện các nguyên tắc cơ bản một cách nghiêm túc.",
        "Cần rất nhiều công sức để làm điều gì đó đơn giản.",
        "Ai cũng nghĩ đến thay đổi thế giới, nhưng không ai nghĩ đến thay đổi bản thân.",
        "Người đầu óc hẹp hòi cần nghệ thuật được đút cho ăn.",
        "Hãy làm gì đó thay vì giết thời gian. Vì thời gian đang giết bạn.",
        "Hãy để mọi quyết định phù hợp với tầm nhìn của bạn.",
        "Nếu muốn làm điều gì lớn lao hơn mức trung bình, bạn không thể nhượng bộ nỗi sợ bị coi là kẻ lạc lõng.",
        "Điều quan trọng nhất là bạn đi qua lửa tốt thế nào.",
        "Bạn chỉ cách một quyết định với một cuộc đời hoàn toàn khác.",
        "Nếu bạn sống cho ngày mai, bạn sẽ luôn chậm một ngày.",
        "Hãy tận dụng tối đa bản thân, vì đó là tất cả những gì bạn có.",
        "Mắt vô dụng khi tâm trí mù lòa.",
        "Về lâu dài, người ta chỉ trúng thứ họ nhắm. Vì vậy, dù thất bại ngay, họ nên nhắm cao.",
        "Ai có lý do để sống có thể chịu đựng gần như mọi cách sống.",
        "Người ta chia thành 2 nhóm: nhóm tiến lên và đạt được, và nhóm theo sau rồi chỉ trích.",
        "Thái độ tệ giống như lốp xẹp. Bạn không đi đâu được cho đến khi thay nó.",
        "Không con chim nào bay quá cao nếu bay bằng đôi cánh của mình.",
        "Giải quyết vấn đề hoặc rời bỏ vấn đề. Đừng sống với vấn đề.",
        "Hành động theo nguyên tắc, không theo tâm trạng.",
        "Ai không cam kết với điều gì sẽ bị phân tâm bởi mọi thứ.",
        "Khi chúng ta phấn đấu trở nên tốt hơn, mọi thứ xung quanh cũng tốt hơn.",
        "Không có đam mê nào trong việc chấp nhận cuộc sống thấp hơn cuộc sống bạn có khả năng sống.",
        "Người sáng tạo được thúc đẩy bởi khao khát đạt thành tựu, không phải khao khát đánh bại người khác.",
        "Cuộc sống là sự chuẩn bị dài cho điều không bao giờ xảy ra.",
        "Tôi không còn nghe người ta nói gì, tôi chỉ xem họ làm gì. Hành vi không bao giờ nói dối.",
        "Người thông minh học từ mọi thứ và mọi người; người bình thường từ kinh nghiệm. Kẻ ngu đã có sẵn mọi câu trả lời.",
        "Quy tắc đầu tiên là giữ tinh thần bình thản. Quy tắc thứ hai là nhìn mọi thứ đúng như bản chất.",
        "Luôn phải vật lộn để nâng tạ nặng hơn.",
        "Người sợ đau khổ đã đau khổ vì điều anh ta sợ.",
        "Nếu người ta không biết cảng nào để cập bến, không gió nào thuận lợi.",
        "Tôi luôn làm điều tôi chưa thể, để học cách làm nó.",
        "Bạn xây dựng trên thất bại. Dùng nó làm bậc thang. Đóng cánh cửa quá khứ. Đừng cố quên sai lầm, nhưng đừng chìm đắm. Đừng cho nó năng lượng, thời gian hay không gian của bạn.",
        "Nội dung tính cách là lựa chọn của bạn. Mỗi ngày, điều bạn chọn, điều bạn nghĩ và điều bạn làm là con người bạn trở thành.",
        "Kẻ hèn nhát không bao giờ bắt đầu và kẻ yếu đuối chết dọc đường.",
        "Khi thức dậy buổi sáng, hãy nghĩ đó là đặc quyền quý giá được sống - được thở, được suy nghĩ, được tận hưởng, được yêu.",
        "Bí mật của thành công là tập trung vào mục đích.",
        "Thứ duy nhất nguy hiểm hơn sự thiếu hiểu biết là sự kiêu ngạo.",
        "Chúng ta là những gì chúng ta lặp đi lặp lại. Xuất sắc không phải hành động, mà là thói quen.",
        "Trong khi chúng ta chờ cuộc sống, cuộc sống trôi qua.",
        "Thành công chỉ là vài kỷ luật đơn giản, thực hành mỗi ngày.",
        "Càng biết nhiều, càng nhận thức rõ sự thiếu hiểu biết của mình.",
        "Trở ngại cho hành động thúc đẩy hành động. Điều cản đường trở thành con đường.",
        "Điểm yếu lớn nhất là bỏ cuộc. Cách chắc chắn nhất để thành công là luôn thử thêm một lần nữa.",
        "Viên ngọc không thể đánh bóng mà không có ma sát, con người không hoàn thiện mà không có thử thách.",
        "Giá trị của bạn nằm ở bạn là ai, không phải bạn có gì.",
        "Kẻ làm sai bất hạnh hơn người bị hại.",
        "Một trong những thử nghiệm chân thật nhất về sự chính trực là sự từ chối thẳng thừng không bị thỏa hiệp.",
        "Chúa không ban gì cho những ai khoanh tay đứng nhìn.",
        "Biết cách suy nghĩ cho bạn sức mạnh vượt xa những người chỉ biết nghĩ gì.",
        "Nếu bạn lên kế hoạch trở thành ít hơn khả năng, bạn có lẽ sẽ bất hạnh suốt đời.",
        "Không có gì tốt hơn nghịch cảnh. Mọi thất bại, đau khổ, mất mát đều chứa hạt giống riêng, bài học riêng về cách cải thiện lần tới.",
        "Hãy học cách yêu sự ghét bỏ. Ôm lấy nó. Tận hưởng nó. Bạn xứng đáng với nó. Ai cũng có quyền có ý kiến và ai cũng nên có ý kiến về bạn. Kẻ ghét là vấn đề tốt. Không ai ghét người giỏi. Họ ghét người vĩ đại.",
        "Chấp nhận rằng bạn không thể kiểm soát mọi thứ. Chấp nhận trách nhiệm với mọi thứ trong tầm kiểm soát. Chấp nhận rào cản bên trong và bên ngoài tồn tại. Chấp nhận rằng bạn được trang bị để vượt qua tất cả.",
        "Kinh nghiệm là loại giáo viên khó nhất. Nó cho bài kiểm tra trước rồi bài học sau.",
        "Chúng ta trưởng thành nhờ tổn thương, không phải nhờ năm tháng.",
        "Nếu bạn buồn, bạn đang sống trong quá khứ. Nếu lo lắng, bạn đang sống trong tương lai. Nếu bình an, bạn đang sống trong hiện tại.",
        "Nếu bạn nghĩ chúng ta không thể thay đổi thế giới, điều đó chỉ có nghĩa bạn không phải người sẽ làm.",
        "Có lẽ không phải về kết thúc hạnh phúc. Có lẽ là về câu chuyện.",
        "Một số người mang niềm vui đến mọi nơi, và một số mang niềm vui mỗi khi họ đi.",
        "Hãy luôn quan sát rằng mọi thứ xảy ra bởi sự thay đổi, và tập cho mình thấy rằng bản chất vũ trụ yêu thay đổi nhất.",
        "Quá tốt thường không thú vị.",
        "Quá thường chúng ta tận hưởng sự thoải mái của ý kiến mà không phải chịu sự khó chịu của suy nghĩ.",
        "Học mà không suy nghĩ là vô ích; suy nghĩ mà không học là nguy hiểm.",
        "Một người có niềm tin sẽ áp đảo trăm người chỉ có ý kiến.",
        "Kẻ ngốc sinh sôi khi người khôn im lặng.",
        "Hãy sẵn sàng sửa đổi bất kỳ hệ thống nào, loại bỏ bất kỳ phương pháp nào, từ bỏ bất kỳ lý thuyết nào nếu thành công đòi hỏi.",
        "Giúp người khác phát triển và thành công trong cuộc sống là phần thưởng tự thân và chỉ có giá trị khi không mong đáp lại.",
        "Bây giờ không phải lúc nghĩ về những gì không có. Hãy nghĩ về những gì có thể làm với những gì đang có.",
        "Tôi muốn nói tôi là công trình đang dang dở, nhưng điều đó ngụ ý rằng một ngày tôi sẽ không còn dang dở.",
        "Đừng bỏ cuộc. Thông thường chìa khóa cuối cùng trên vòng chìa mới mở được cửa.",
        "Cuộc sống là hài kịch với người suy nghĩ, là bi kịch với người cảm nhận.",
        "Khéo léo là khả năng bảo ai đó xuống địa ngục theo cách mà họ mong chờ chuyến đi.",
        "Hãy để lỗi lầm người khác gây ra ở nơi nó phát sinh.",
        "Đừng quấy rầy bản thân bằng cách tưởng tượng cả cuộc đời cùng lúc. Đừng luôn nghĩ đến những khổ đau gì và bao nhiêu có thể xảy đến.",
        "Mỗi khi tôi nghĩ mình biết hết, 'hết' lại có nhiều hơn tôi tưởng.",
        "Sự khác biệt giữa ngu ngốc và thiên tài là thiên tài có giới hạn.",
        "Thà làm chiến binh trong vườn hoa, hơn làm người làm vườn trong chiến tranh.",
        "Thành công lớn luôn đi kèm nguy cơ thất bại lớn.",
        "Thành công đến từ sự tò mò, tập trung, kiên trì và tự phê bình.",
        "Dấu hiệu của một tâm trí có giáo dục là có thể suy ngẫm một ý tưởng mà không chấp nhận nó.",
        "Ý kiến của 10.000 người không có giá trị nếu không ai trong số họ hiểu biết về chủ đề.",
        "Càng coi trọng thứ ngoài tầm kiểm soát, chúng ta càng ít quyền kiểm soát.",
        "Hãy lên đường. Hãy thử. Không có gì khác.",
        "Xuất thân không bao giờ nên là rào cản thành công. Khởi đầu khiêm tốn có thể là trợ giúp hơn là cản trở.",
        "Đừng để thiếu sót của người khác làm bạn thiếu hụt.",
        "Sự đố kị của chúng ta luôn kéo dài hơn hạnh phúc của người chúng ta đố kị.",
        "Không gì sẽ đến từ không gì.",
        "Người yếu trả thù. Người mạnh tha thứ. Người thông minh phớt lờ.",
        "Tôi không kiểm soát gió; tôi chỉ nghiên cứu nó.",
        "Danh dự có thể không giành được quyền lực, nhưng giành được sự tôn trọng. Và tôn trọng đem lại quyền lực.",
        "Vũ khí cuối cùng là bộ não, mọi thứ khác chỉ là bổ sung.",
        "Nếu bạn không vượt qua xu hướng dễ bỏ cuộc, cuộc đời sẽ chẳng dẫn đến đâu.",
        "Luyện tập giống như quét nhà. Chỉ vì chúng ta đã làm một lần không có nghĩa sàn sạch mãi mãi.",
        "Hãy nhớ rằng chính chúng ta tự hành hạ mình, tự gây khó cho mình - đó là ý kiến của chúng ta. Bị sỉ nhục nghĩa là gì? Đứng cạnh tảng đá và sỉ nhục nó, bạn đạt được gì? Nếu ai đó phản ứng với sự sỉ nhục như tảng đá, kẻ xúc phạm được gì?",
        "Khi không có mục đích, cuộc sống trở thành hành trình bất tận đến hư vô.",
        "Chỉ có người chết mới thấy hết chiến tranh.",
        "Phòng bệnh hơn chữa bệnh.",
        "Không gì được dạy bằng cưỡng ép sẽ ở lại trong tâm hồn.",
        "Mọi thứ tồn tại trong cuộc đời bạn là vì hai điều: điều bạn đã làm hoặc điều bạn không làm.",
        "Người không có đạo đức là con thú hoang được thả ra thế giới.",
        "Suy nghĩ thì khó, đó là lý do hầu hết người ta phán xét.",
        "Bạn không tìm thấy ý chí, bạn tạo ra nó.",
        "Từ hạnh phúc sẽ mất ý nghĩa nếu không được cân bằng bởi nỗi buồn.",
        "Đừng cầu nguyện cho cuộc sống dễ dàng. Hãy cầu nguyện cho sức mạnh chịu đựng cuộc sống khó khăn.",
        "Bạn không phải là tất cả những gì bạn có thể trở thành, và bạn biết điều đó.",
        "Hãy nhớ sống trong khi bạn bận sinh tồn.",
        "Kế hoạch chẳng là gì, việc lập kế hoạch mới là tất cả.",
        "Người dám lãng phí một giờ chưa khám phá ra giá trị cuộc sống.",
        "Bạn phải quyết định mình là ai và buộc thế giới đối mặt với bạn, không phải với ý tưởng của họ về bạn.",
        "Nghệ thuật sống giống đấu vật hơn nhảy múa, ở chỗ nó sẵn sàng với bất ngờ và không dễ ngã.",
        "Khi lớn tuổi hơn, tôi ít chú ý đến lời người ta nói. Tôi chỉ xem họ làm gì.",
        "Tôi sẽ thắt lưng buộc bụng trước khi xin giúp đỡ.",
        "Không ai được tạo ra giống bạn, bạn tự thiết kế bản thân.",
        "Không ai có quyền là tay nghiệp dư trong luyện tập thể chất. Thật xấu hổ khi người ta già đi mà không thấy vẻ đẹp và sức mạnh cơ thể mình có khả năng.",
        "Người càng gần tâm trí bình tĩnh, càng gần sức mạnh.",
        "Đây là quy tắc cần nhớ: khi điều gì cám dỗ bạn cay đắng: không phải \"Đây là bất hạnh\" mà \"Chịu đựng điều này xứng đáng là may mắn.\"",
        "Khi bạn giỏi, bạn sẽ nói với mọi người. Khi bạn vĩ đại, họ sẽ nói với bạn.",
        "Đầu tiên họ phớt lờ bạn. Rồi chế nhạo. Rồi tấn công và muốn đốt bạn. Rồi họ dựng tượng đài cho bạn.",
        "Tự do có nghĩa là trách nhiệm. Đó là lý do hầu hết người ta sợ nó.",
        "Nếu bạn nói sự thật, bạn không phải nhớ gì cả.",
        "Thời của bạn sẽ đến nếu bạn tiếp tục bước.",
        "Không phải cái chết mà con người nên sợ, mà nên sợ không bao giờ bắt đầu sống.",
        "Quy trình hôm nay là kết quả ngày mai. Nếu bạn yêu quy trình hôm nay, bạn sẽ yêu kết quả ngày mai.",
        "Mọi vấn đề của nhân loại bắt nguồn từ việc con người không thể ngồi yên lặng trong phòng một mình.",
        "Đừng bao giờ để tương lai quấy rầy bạn. Bạn sẽ gặp nó, nếu phải, với cùng vũ khí lý trí bảo vệ bạn trước hiện tại.",
        "Đàn ông trưởng thành qua đau đớn, thất bại, bị từ chối, mất mát, bị coi thường và đau khổ, không phải qua tuổi tác.",
        "Chúng ta rèn những sợi xích mà chúng ta đeo trong đời.",
        "Để làm bất cứ điều gì ở mức cao, nó phải là nỗi ám ảnh.",
        "Nếu muốn cải thiện, hãy bằng lòng bị coi là ngốc và ngu về những thứ bên ngoài.",
        "Bạo lực là nơi trú ẩn cuối cùng của kẻ bất tài.",
        "Sợ hãi giống như lửa, nó có thể hữu ích nếu bạn biết dùng. Nếu không, bạn sẽ bị bỏng.",
        "Để thành công lớn, bạn phải sẵn sàng thất bại lớn. Nếu không làm được cả hai, bạn có vấn đề.",
        "Chúng ta luôn nói về ai đó không thích mình 'vô cớ', nhưng người ta cũng sẽ thích bạn 'vô cớ'. Vì vậy đừng quá coi trọng cả hai phía.",
        "Kẻ hèn nhát chết nhiều lần trước khi chết; người dũng cảm chỉ nếm cái chết một lần.",
        "Không gì khó hơn, và do đó quý hơn, khả năng ra quyết định.",
        "Hãy đi trên một con đường, không kiêu khi thắng, không gục khi thua, không quên cẩn thận khi yên bình, không hoảng sợ khi nguy hiểm.",
        "Linh hồn nhuốm màu suy nghĩ.",
        "Tôi không xin gánh nhẹ hơn. Mà xin đôi vai rộng hơn.",
        "Đừng thương lượng với bản thân. Hãy ra lệnh cho bản thân.",
        "Bạn không thể cầu xin cả tính cách mạnh mẽ lẫn cuộc sống dễ dàng.",
        "Can đảm không phải có sức để đi tiếp - mà là đi tiếp khi không có sức.",
        "Cuộc sống không xảy ra với bạn, nó xảy ra có bạn tham gia.",
        "Bước vào chiến tranh mà không có ý chí chiến thắng là chết chắc.",
        "Bạn không bao giờ biết mình mạnh thế nào cho đến khi mạnh mẽ là lựa chọn duy nhất.",
        "Không thể làm hài lòng tất cả, đôi khi phải hành động và để người khác phản ứng.",
        "Không có chuyện 'nếu', chỉ có chuyện 'khi nào'.. khi bạn quyết tâm với sứ mệnh.",
        "Bạn sẽ còn chờ bao lâu trước khi đòi hỏi điều tốt nhất cho mình?",
        "Thế giới hứa hẹn sự thoải mái, nhưng bạn không được sinh ra cho sự thoải mái. Bạn được sinh ra cho sự vĩ đại.",
        "Chính trực không phải con đường nhanh, nhưng là con đường chắc chắn.",
        "Hãy là fan hâm mộ lớn nhất của chính mình, người tin tưởng lớn nhất, vác nó lên lưng và gánh lấy.",
        "Trước tiên hãy nói bạn muốn trở thành gì; rồi làm điều phải làm.",
        "Tôi sợ ngày mà công nghệ sẽ vượt qua tương tác con người. Thế giới sẽ có một thế hệ ngốc.",
        "Không phải bạn chịu đựng gì, mà là cách bạn chịu đựng.",
        "Từ chối cảm giác bị tổn thương và bản thân tổn thương sẽ biến mất.",
        "Đừng làm kế hoạch nhỏ. Chúng không có phép thuật khuấy động máu người và có lẽ sẽ không thành hiện thực. Hãy làm kế hoạch lớn; nhắm cao trong hy vọng và công việc, nhớ rằng sơ đồ cao quý và logic một khi được ghi lại sẽ không bao giờ chết, mà sống mãi, tự khẳng định với sự cấp bách ngày càng tăng.",
        "Khó khăn thường chuẩn bị cho người bình thường một số phận phi thường.",
        "Khi bạn muốn thay đổi, bạn không thể làm hài lòng tất cả. Nếu bạn hài lòng tất cả, bạn chưa tiến bộ đủ.",
        "Đừng thương lượng với bản thân, hãy ra lệnh cho bản thân.",
        "Thành công không phải là cuối cùng, thất bại không phải là chết: can đảm tiếp tục mới là điều quan trọng.",
        "Nếu không đúng đừng làm; nếu không thật đừng nói.",
        "Cái gọi là khoái lạc, khi vượt quá giới hạn, chỉ là hình phạt.",
        "Nếu bạn không hy sinh cho điều mình muốn, điều mình muốn sẽ trở thành vật hy sinh.",
        "Kẻ thù lớn nhất của bạn là tâm trí không được kiểm soát.",
        "Học chiến đấu để không bao giờ phải chiến đấu.",
        "Khi người ta không tìm thấy ý nghĩa sâu sắc, họ đánh lạc hướng bằng khoái lạc.",
        "Không có gì vĩnh viễn trong thế giới tàn nhẫn này, kể cả rắc rối.",
        "Hãy để họ sai về bạn. Không có gì phải chứng minh.",
        "Nếu bạn muốn hiện tại khác quá khứ, hãy nghiên cứu quá khứ.",
        "Nếu muốn sống hạnh phúc, hãy gắn nó với mục tiêu, không phải con người hay đồ vật.",
        "Không có bí mật, chỉ có thông tin bạn đã khám phá và thông tin chưa khám phá.",
        "Bạn cần động lực để hành động. Thông tin để biết hành động gì. Sự tò mò để thu thập thông tin dẫn đường cho hành động. Vì vậy hãy tò mò.",
        "Người chiến thắng chỉ là người thua đã thử thêm một lần.",
        "Chúng ta rèn cơ thể nghiêm khắc để nó không bất tuân tâm trí.",
        "Người sẵn lòng được dẫn dắt bởi số phận, kẻ miễn cưỡng bị kéo lê.",
        "Người sợ chết sẽ không bao giờ làm điều xứng đáng với người đang sống.",
        "Tướng quân không bao giờ tin tưởng hòa bình đến mức thất bại trong chuẩn bị chiến tranh.",
        "Đừng sợ. Bạn sẽ vượt qua, nhưng sẽ luôn cảm thấy như không thể.",
        "Nhất quán nghe có vẻ nhàm chán, nhưng bạn nghĩ sự vĩ đại là gì? May mắn?",
        "Hãy luôn hướng mặt về phía ánh nắng và bóng tối sẽ ngã phía sau.",
        "Hình phạt nặng nhất cho việc từ chối cai trị là bị cai trị bởi kẻ kém hơn.",
        "Hãy đào bên trong. Bên trong là suối nguồn Thiện; nó luôn sẵn sàng tuôn trào, nếu bạn chỉ cần đào.",
        "Bạn là những gì bạn làm, không phải những gì bạn nói sẽ làm.",
        "Sai theo cách riêng tốt hơn đúng theo cách người khác.",
        "Người vĩ đại khắt khe với bản thân, kẻ yếu khắt khe với người khác.",
        "Yêu bản thân là khởi đầu của mối tình suốt đời.",
        "Quan tâm người khác nghĩ gì, bạn sẽ mãi mãi là tù nhân của họ.",
        "Con người không lo về vấn đề thực sự bằng những lo lắng tưởng tượng về vấn đề thực sự.",
        "Người hạnh phúc là người hài lòng với tình huống hiện tại, dù là gì.",
        "Chiến thắng đầu tiên và vĩ đại nhất là chinh phục bản thân.",
        "Để kiểm soát bản thân, tôi phải chấp nhận bản thân trước, đi theo chứ không chống lại bản chất.",
        "Hãy để người ta thấy, để người ta biết một người thực sống đúng như cách được sinh ra để sống.",
        "Ai không thể tự tuân lệnh sẽ bị ra lệnh.",
        "Khi bạn sợ điều gì, hãy học về nó nhiều nhất có thể. Kiến thức chinh phục nỗi sợ.",
        "Tôi luôn nghĩ tôi chống lại cả thế giới, rồi một ngày tôi nhận ra chỉ là tôi chống lại tôi.",
        "Người thiếu mục đích sẽ đánh lạc hướng bản thân bằng khoái lạc.",
        "Khó chấp nhận rằng không phải ai cũng 'hiểu'.. nhưng đó là lý do nó không dành cho người khác. Đó là việc của 'bạn'.",
        "Khó khăn càng lớn, vinh quang vượt qua nó càng nhiều.",
        "Chúng ta thích thú vẻ đẹp con bướm, nhưng hiếm khi thừa nhận những thay đổi nó đã trải qua để đạt được vẻ đẹp đó.",
        "Hãy để tôi ngã nếu phải ngã. Người tôi đang trở thành sẽ đỡ lấy tôi.",
        "Đằng sau người tha thứ mọi thứ là người biết sức nặng tội lỗi của chính mình.",
        "Nỗ lực trốn thoát đau khổ tạo ra thêm đau khổ.",
        "Sự phát triển thực sự không tôn trọng sự thoải mái.",
        "Theo như chúng ta có thể nhận biết, mục đích duy nhất của sự tồn tại con người là thắp lên ngọn lửa ý nghĩa trong bóng tối của sự hiện hữu đơn thuần.",
        "Ngày bạn gieo hạt không phải ngày bạn hái quả.",
        "Sự thật không thay đổi vì nó được hay không được tin bởi đa số.",
        "Hiệp sĩ trong bộ giáp sáng bóng không có giá trị đã được chứng minh. Hãy cho tôi hiệp sĩ đã trải trận, với bộ giáp sờn từ những cuộc chạm trán với phần tồi tệ của nhân loại.",
        "Thước đo trí tuệ là khả năng thay đổi.",
        "Không có mùa gặt nào mà không có đói khát.",
        "Chính tâm trí dẫn dắt tâm trí lạc lối. Về tâm trí, đừng bất cẩn.",
        "Bạn không thể mơ mà thành nhân cách; bạn phải rèn đúc bản thân.",
        "Nhiều thứ sẽ sai trước khi mọi thứ đúng.",
        "Chúng ta chỉ sống ở hiện tại. Mọi thứ khác đã qua hoặc chưa biết.",
        "Bạn sẽ không bị trừng phạt vì cơn giận, bạn sẽ bị trừng phạt bởi cơn giận.",
        "Bạn không học bơi bằng cách đọc về nước.",
        "Những lựa chọn khó nhất đòi hỏi ý chí mạnh nhất.",
        "Trên hết, đừng tự dối mình.",
        "Cơ thể bạn có thể chịu đựng gần như mọi thứ; tâm trí mới là thứ bạn phải thuyết phục.",
        "Cuộc sống thuộc thể loại ngôi thứ nhất. Hãy đối xử với nó như vậy.",
        "Lãnh đạo giỏi không viện cớ. Thay vào đó, họ tìm cách hoàn thành.",
        "Chỉ vì bạn mất nhiều thời gian hơn người khác không có nghĩa bạn thất bại.",
        "Bạn càng hiểu mình, bạn càng ít cần sự chấp thuận của người khác.",
        "Biết mình là khởi đầu của mọi trí tuệ.",
        "Không phải kích cỡ con người mà là kích cỡ trái tim mới quan trọng.",
        "Khó có thể đổi cấp bậc mà không có nước mắt.",
        "Bạn cày với chiếc cày mình có.",
    ]
}
