// QuotesLang_pt.swift
// Spike AI — Bundled quote translations
import Foundation
enum QuotesLang_pt {
    static let quotes: [String] = [
        "O que quer que você mantenha em sua mente de forma consistente é exatamente o que você experimentará na vida.",
        "Miramos acima do alvo para acertar o alvo.",
        "A pior coisa que posso ser é igual a todo mundo – eu odeio isso.",
        "Apenas aqueles que arriscam ir longe demais podem descobrir o quão longe se pode ir.",
        "Salte e a rede aparecerá.",
        "Um navio no porto está seguro, mas não é para isso que os navios são construídos.",
        "Não se preocupe com fracassos – preocupe-se com as chances que você perde quando nem tenta.",
        "Aqueles que ousam fracassar miseravelmente podem alcançar grandes feitos.",
        "O caminho para começar é parar de falar e começar a fazer.",
        "Podemos encontrar muitas derrotas, mas não devemos ser derrotados.",
        "A verdadeira medida de um homem é como ele trata alguém que não pode lhe fazer absolutamente nenhum bem.",
        "Tenha cuidado se você não sabe para onde está indo, porque pode não chegar lá.",
        "Você deve esperar grandes coisas de si mesmo antes de poder fazê-las.",
        "Nunca deixe suas decisões passadas determinarem seu resultado futuro.",
        "Atalhos causam longos atrasos.",
        "Ninguém pode te dar seus objetivos. Esta é a sua jornada.",
        "O mundo é o que você pensa dele – então pense de forma diferente, e seu mundo mudará.",
        "O futuro pertence àqueles que se preparam para ele hoje.",
        "Não desista do que você mais quer pelo que quer agora.",
        "Não me diga o quão talentoso você é – me diga o quão duro você trabalha.",
        "A forma como você pensa quando perde determina quanto tempo levará até você vencer.",
        "Sempre que uma pessoa decide que o sucesso foi alcançado, o progresso para.",
        "Nenhum problema pode resistir ao ataque do pensamento persistente.",
        "Sorte é quando uma oportunidade aparece e você está preparado para ela.",
        "O segredo para progredir é começar.",
        "O melhor momento para plantar uma árvore foi há 20 anos. O segundo melhor momento é agora.",
        "É difícil vencer uma pessoa que nunca desiste.",
        "Escreva. Filme. Publique. Tricote, refogue. Não importa – crie!",
        "Seja lá o que você for, seja bom nisso.",
        "A felicidade não é algo pronto – ela vem das suas próprias ações.",
        "Pessoas inteligentes aprendem com tudo e com todos.",
        "Impossível é apenas uma opinião.",
        "Sua paixão está esperando sua coragem alcançá-la.",
        "Pessoas que se perguntam se o copo está meio vazio ou meio cheio perdem o ponto. O copo é recarregável.",
        "Um dia ou dia um – você decide.",
        "As coisas podem vir para aqueles que esperam, mas apenas as coisas deixadas por aqueles que se esforçam.",
        "Tudo vem para aquele que se esforça enquanto espera.",
        "Trabalhe como se alguém estivesse trabalhando 24 horas por dia para tirá-lo de você.",
        "Ninguém jamais fez a diferença sendo como todo mundo.",
        "Você terá tempos difíceis, mas eles sempre vão te despertar para as coisas boas às quais você não estava prestando atenção.",
        "Seja uma versão de primeira classe de si mesmo, não uma versão de segunda classe de outra pessoa.",
        "Aprenda com os erros dos outros. Você não pode viver tempo suficiente para cometê-los todos sozinho.",
        "Se você está cansado, então faça cansado.",
        "Um homem não está acabado quando é derrotado – está acabado quando desiste.",
        "O mundo é mudado pelo seu exemplo, não pela sua opinião.",
        "A vida é como andar de bicicleta. Para manter o equilíbrio, você precisa continuar se movendo.",
        "Pensando sobre a vida: nenhuma quantidade de culpa pode mudar o passado, nenhuma quantidade de ansiedade pode mudar o futuro.",
        "Uma mente negativa nunca lhe dará uma vida positiva.",
        "Tudo é difícil antes de ser fácil.",
        "Assuma o risco ou perca a chance.",
        "Nunca pare de aprender, porque a vida nunca para de ensinar.",
        "O homem que não lê não tem vantagem sobre o homem que não sabe ler.",
        "Uma pessoa que nunca cometeu um erro nunca tentou nada novo.",
        "A maneira mais comum de as pessoas abrirem mão do seu poder é pensando que não têm nenhum.",
        "Seja grato pelo que tem; você acabará tendo mais. Concentre-se no que não tem e nunca terá o suficiente.",
        "A coisa mais difícil é a decisão de agir – o resto é meramente tenacidade.",
        "Muitos dos fracassos da vida são de pessoas que não perceberam o quão perto estavam quando desistiram.",
        "Não importa se você é derrubado – o que importa é se você se levanta.",
        "O pessimista vê dificuldade em cada oportunidade. O otimista vê oportunidade em cada dificuldade.",
        "Nossa maior glória não está em nunca cair, mas em nos levantarmos toda vez que caímos.",
        "Não se deixe empurrar pelos medos em sua mente; seja guiado pelos sonhos em seu coração.",
        "Quando você sabe o que quer e quer o suficiente, encontrará um jeito de conseguir.",
        "Comece fazendo o necessário, depois faça o possível, e de repente você estará fazendo o impossível.",
        "Sem paixão você não tem energia, sem energia você não tem nada.",
        "Você não precisa ser ótimo para começar, mas precisa começar para ser ótimo.",
        "A força não vem da capacidade física – ela vem de uma vontade indomável.",
        "Ninguém neste mundo é inútil se alivia o fardo de outro.",
        "Ao pedir o impossível, obtemos o possível.",
        "É melhor ser um leão por um dia do que uma ovelha a vida toda.",
        "A vida é importante demais para ser levada a sério.",
        "O começo é a metade de toda ação.",
        "Paciência infinita traz resultados imediatos.",
        "Quase todos os homens morrem dos seus remédios e não das suas doenças.",
        "Eles podem, porque acreditam que podem.",
        "A imaginação é mais importante que o conhecimento.",
        "Pessoas persistentes começam seu sucesso onde outros terminam em fracasso.",
        "Não há caminhos claros. Apenas armadilhas, obstáculos e escuridão.",
        "Um erro prova que alguém parou de falar tempo suficiente para fazer algo.",
        "O que quer que valha a pena ser feito, vale a pena ser bem feito.",
        "Mais poderoso é aquele que tem a si mesmo em seu poder.",
        "Um estudioso que cultiva o amor pelo conforto não é digno de ser chamado de estudioso.",
        "A prosperidade depende mais de querer o que você tem do que de ter o que quer.",
        "Cada dia traz seus próprios presentes – desamarre as fitas.",
        "O sucesso nunca é permanente e o fracasso nunca é definitivo.",
        "Nada dura para sempre – nem mesmo seus problemas.",
        "Trabalho duro não garante sucesso, mas melhora suas chances.",
        "A paz não pode ser mantida pela força. Só pode ser alcançada pela compreensão.",
        "Quem não arrisca não tem sorte.",
        "Não diga: quando tiver tempo livre estudarei – talvez você não tenha tempo livre.",
        "Quem perde a fé perde tudo.",
        "O próprio pensamento de alguém é o seu mundo. O que uma pessoa pensa é o que ela se torna.",
        "A aventura não está fora do homem, ela está dentro dele.",
        "O jogo da vida não consiste tanto em ter boas cartas, mas em jogar bem uma mão ruim.",
        "Azedo, doce, amargo, picante – tudo deve ser provado.",
        "Nunca deixe a sensação de fracasso passado derrotar seu próximo passo.",
        "A menos que você seja ambicioso, não fará progresso.",
        "O futuro pertence àqueles que ousam.",
        "Os fatos não deixam de existir porque são ignorados.",
        "Nunca devemos assumir o que é incapaz de ser provado.",
        "Uma voz alta não pode competir com uma voz clara, mesmo que seja um sussurro.",
        "Aja como se esperasse chegar à zona final.",
        "A felicidade é a flor natural do dever.",
        "\"Não\" simplesmente significa começar de novo em um nível mais alto.",
        "O entusiasmo move o mundo.",
        "Um campeão é alguém que se levanta quando não consegue.",
        "Obstáculos são o preço da grandeza.",
        "A questão não é quem vai me deixar – a questão é quem vai me impedir.",
        "Eu não estava lá para competir – eu estava lá para vencer.",
        "Pare de reclamar, comece a trabalhar.",
        "Das dificuldades crescem milagres.",
        "Não tenho medo – nasci para fazer isso.",
        "Nunca abaixe a cabeça. Mantenha-a erguida. Olhe o mundo direto nos olhos.",
        "Faça o que você tem que fazer até poder fazer o que quer fazer.",
        "Se você caiu ontem, levante-se hoje.",
        "Faça de cada dia sua obra-prima.",
        "Sangue, suor e respeito. Os dois primeiros você dá, o último você conquista.",
        "Seja tão bom que não possam te ignorar.",
        "Mostre ao mundo o quanto você lutará pelo círculo dos vencedores.",
        "Se você não projeta seu próprio plano de vida, provavelmente cairá no plano de outra pessoa. O que eles planejaram para você? Não muito.",
        "A única pessoa que você está destinado a se tornar é a pessoa que você decide ser.",
        "Não espere até que o ferro esteja quente para golpear – aqueça-o golpeando.",
        "Não acredito que Deus nos colocou nesta terra para sermos comuns.",
        "Eu quero que o mundo seja melhor porque eu estive aqui.",
        "O hábito da persistência é o hábito da vitória.",
        "Não tenha medo de abrir mão do bom para buscar o ótimo.",
        "Faça seu dever e um pouco mais, e o futuro cuidará de si mesmo.",
        "A vida tem um jeito de testar a vontade de uma pessoa – ou nada acontece ou tudo acontece de uma vez.",
        "Um homem sábio pode sempre ser encontrado sozinho. Um homem fraco pode sempre ser encontrado numa multidão.",
        "Ousar é perder o equilíbrio momentaneamente. Não ousar é perder a si mesmo.",
        "O medo derrota mais pessoas do que qualquer outra coisa no mundo.",
        "As palavras mais poderosas do universo são as que você usa para falar consigo mesmo.",
        "A única coisa que vem para um homem dormindo são sonhos.",
        "Se você não conquistar a si mesmo, será conquistado por si mesmo.",
        "Um herói é alguém que sabe como aguentar mais um minuto.",
        "Vá até onde puder ver – quando chegar lá, poderá ver mais longe.",
        "Você não descobre seu lugar no mundo, você o esculpe.",
        "Vencedores focam em vencer. Perdedores focam em vencedores.",
        "O fracasso nunca me alcançará se minha determinação para ter sucesso for forte o suficiente.",
        "O que vem fácil não dura. O que dura não vem fácil.",
        "Para evitar críticas: não diga nada, não faça nada, não seja nada.",
        "O homem que faz mais do que é pago logo será pago por mais do que faz.",
        "O gênio começa grandes obras, o trabalho sozinho as termina.",
        "Mesmo se estiver no caminho certo, será atropelado se ficar parado.",
        "Se as coisas não estão falhando, você não está inovando o suficiente.",
        "Você tira o melhor dos outros quando dá o melhor de si.",
        "Liderança é uma ação, não uma posição.",
        "Nosso trabalho é a apresentação das nossas capacidades.",
        "Todos os meus problemas se curvam diante da minha teimosia.",
        "Use seu fracasso como uma medalha de honra.",
        "Somos limitados não pelas nossas habilidades, mas pela nossa visão.",
        "Se estiver cansado, aprenda a descansar, não a desistir.",
        "Cair é um acidente, ficar no chão é uma escolha.",
        "Não ouse desistir desta vida. Não esta noite. Não amanhã. Nunca.",
        "Nunca se deixe abater por pessoas ou eventos.",
        "Algumas pessoas sonham com o sucesso enquanto outras acordam e trabalham duro por ele.",
        "A confiança vem da experiência. A experiência vem de tentar, falhar e tentar de novo – desta vez melhor.",
        "O tempo que leva à maestria depende da intensidade do nosso foco.",
        "O sucesso só vem para aqueles que ousam tentar.",
        "Uma chave importante para o sucesso é a autoconfiança. Uma chave importante para a autoconfiança é a preparação.",
        "A dúvida mata mais sonhos do que o fracasso jamais matará.",
        "A vitória é sempre possível para quem se recusa a parar de lutar.",
        "Você nunca mudará sua vida até mudar algo que faz diariamente.",
        "Para ter sucesso, seu foco tem que ser tão intenso que os outros pensem que você é louco.",
        "Obstáculos são aquelas coisas assustadoras que você vê quando tira os olhos do seu objetivo.",
        "Encontrar uma oportunidade é uma questão de acreditar que ela está lá.",
        "Definir metas é o primeiro passo para transformar o invisível em visível.",
        "Se você não arriscar nada, arrisca tudo.",
        "Se não pode mudar sua situação, mude sua mentalidade.",
        "Não importa quão difícil o passado tenha sido, você sempre pode começar de novo.",
        "Se você não ousar nada, quando o dia acabar, nada será tudo o que terá ganho.",
        "Muitas vezes é preciso mais uma mudança em si mesmo do que uma mudança de cenário.",
        "O medo é a maior deficiência de todas e vai te paralisar.",
        "O que é perigoso é não evoluir.",
        "De qualquer forma, encontrarei um caminho ou criarei um.",
        "A única forma de calar todo mundo é vencer.",
        "Nunca permita que bom o suficiente seja bom o suficiente.",
        "A longo prazo, só acertamos aquilo em que miramos.",
        "A melhoria contínua é melhor do que a perfeição adiada.",
        "Se você vê na sua mente, vai segurá-lo na sua mão.",
        "Hoje farei o que os outros não fazem, para amanhã poder fazer o que os outros não podem.",
        "A excelência é uma arte conquistada pelo treino e pela habituação.",
        "O próximo ano vai passar, esteja você fazendo algo pela sua vida ou não.",
        "Não pare quando estiver cansado – pare quando estiver terminado.",
        "Você está a apenas um treino de distância de um bom humor.",
        "Faça o que é certo, não o que é fácil ou popular.",
        "Nada de grandioso veio tão fácil.",
        "Sem luta não pode haver progresso.",
        "Pessoas bem-sucedidas fazem perguntas melhores e, como resultado, obtêm respostas melhores.",
        "Não tenho talentos especiais – sou apenas apaixonadamente curioso.",
        "A melhor lição que aprendi na vida veio do pior sentimento que tive na vida.",
        "Desafios são o que tornam a vida interessante. Superá-los é o que torna a vida significativa.",
        "Aprenda a ser feliz com a abordagem interminável de tentar, falhar e aprender.",
        "Se você fechar a porta para todos os erros, a verdade ficará trancada do lado de fora.",
        "Esqueça o erro, lembre-se da lição.",
        "Se você só pode fazer o que já sabe fazer, nunca será mais do que já é.",
        "Quem é sábio? Aquele que aprende com todos.",
        "Só eu posso mudar minha vida, ninguém pode fazer isso por mim.",
        "Perseverança é falhar 19 vezes e ter sucesso na 20ª.",
        "Atribuo meu sucesso a isto: nunca dei nem aceitei nenhuma desculpa.",
        "Não sou um produto das minhas circunstâncias. Sou um produto das minhas decisões.",
        "Nossos atos nos determinam tanto quanto determinamos nossos atos.",
        "Apenas os extremamente ignorantes ou extremamente inteligentes podem resistir à mudança.",
        "O homem que tem confiança em si mesmo ganha a confiança dos outros.",
        "O que você procura também está procurando você.",
        "Não se preocupe com o fracasso. Você só precisa acertar uma vez.",
        "A segurança é em grande parte uma superstição. A vida é uma aventura ousada ou não é nada.",
        "Nós nos tornamos aquilo em que pensamos a maior parte do tempo, e esse é o segredo mais estranho.",
        "O caminho para começar é parar de falar e começar a fazer.",
        "Faça de cada dia sua obra-prima.",
        "Não importa quantos erros você cometa ou quão lento seja seu progresso, você ainda está muito à frente de todos que não estão tentando.",
        "É a nossa atitude no início de uma tarefa difícil que, mais do que qualquer outra coisa, afetará seu resultado bem-sucedido.",
        "A única segurança real que um homem terá neste mundo é uma reserva de conhecimento, experiência e habilidade.",
        "O que você faz hoje pode mudar todos os amanhãs da sua vida.",
        "Sua vida não melhora por acaso – ela melhora por mudança.",
        "Um sonho não se torna realidade por magia – é preciso suor, determinação e trabalho duro.",
        "Conhecimento é saber que o tomate é uma fruta. Sabedoria é não colocá-lo numa salada de frutas.",
        "Não importa a situação, lembre-se: eu tenho uma escolha.",
        "Domine sua mente ou ela dominará você.",
        "Alguns têm sucesso porque estão destinados a isso, mas a maioria tem sucesso porque está determinada.",
        "Grandes oportunidades não são vistas com os olhos – são vistas com a mente.",
        "Quem não é corajoso o suficiente para assumir riscos não realizará nada na vida.",
        "Saber não é suficiente, devemos aplicar. Querer não é suficiente, devemos fazer.",
        "A ambição é o caminho para o sucesso, a persistência é o veículo em que você chega.",
        "A chave da vida é aceitar desafios. Uma vez que alguém para de fazer isso, está morto.",
        "Compromisso é o que transforma uma promessa em realidade.",
        "A autoconfiança é a memória do sucesso.",
        "Sem autoconfiança somos como bebês num berço.",
        "Ouse sonhar, mas ainda mais importante – ouse colocar ação por trás dos seus sonhos.",
        "A honestidade é o primeiro capítulo no livro da sabedoria.",
        "A excelência é um processo contínuo e não um acidente.",
        "Esperança é ser capaz de ver que há luz apesar de toda a escuridão.",
        "Devemos aceitar a decepção finita, mas nunca perder a esperança infinita.",
        "O verdadeiro sinal de inteligência não é o conhecimento, mas a imaginação.",
        "Torne-se viciado em autoaperfeiçoamento constante e incessante.",
        "O gênio é um por cento inspiração e noventa e nove por cento transpiração.",
        "Você não pode esperar pela inspiração – tem que ir atrás dela com um porrete.",
        "Tenha paciência. Todas as coisas são difíceis antes de se tornarem fáceis.",
        "A pessoa que diz que algo não pode ser feito não deveria interromper a pessoa que está fazendo.",
        "Perseverança é o trabalho duro que você faz depois de ficar cansado do trabalho duro que já fez.",
        "Um homem sábio pode aprender mais de uma pergunta tola do que um tolo pode aprender de uma resposta sábia.",
        "Pela autodisciplina e autocontrole constantes, você pode desenvolver grandeza de caráter.",
        "O autocontrole emocional é resultado de trabalho duro, não uma habilidade inata.",
        "Aprender a aprender é a habilidade mais importante da vida.",
        "Não deixe que o que não pode fazer impeça o que pode fazer.",
        "Você sempre passa pelo fracasso no caminho para o sucesso.",
        "Ninguém é perfeito – é por isso que os lápis têm borrachas.",
        "Nunca deixe que as probabilidades o impeçam de fazer o que sabe em seu coração que foi destinado a fazer.",
        "Se você olhar de perto, a maioria dos sucessos da noite para o dia levou muito tempo.",
        "Qualquer coisa é possível. Qualquer coisa pode ser.",
        "Nada é particularmente difícil se você dividir em pequenas tarefas.",
        "O segredo do sucesso é fazer as coisas comuns incomumente bem.",
        "Aja como se o que você faz fizesse diferença – porque faz.",
        "O que você obtém ao alcançar seus objetivos não é tão importante quanto o que você se torna ao alcançá-los.",
        "A vida é como andar de bicicleta – para manter o equilíbrio, é preciso continuar se movendo.",
        "Limite seus \"sempre\" e \"nunca\".",
        "Você nunca é velho demais para definir outro objetivo ou sonhar um novo sonho.",
        "Você não encontra a vida feliz, você a constrói.",
        "A má notícia é que o tempo voa. A boa notícia é que você é o piloto.",
        "Mantenha seu rosto sempre voltado para o sol e as sombras ficarão atrás de você.",
        "A diferença entre o impossível e o possível está na determinação de uma pessoa.",
        "Medalhas de ouro não são feitas de ouro. São feitas de suor, determinação e uma liga difícil de encontrar chamada coragem.",
        "Não subestime a determinação de um homem tranquilo.",
        "Não me diga no que acredita. Vou observar como você se comporta e farei minha própria avaliação.",
        "Eu simplesmente odeio perder, e isso te dá uma determinação extra para trabalhar mais duro.",
        "A determinação de vencer é a melhor parte de vencer.",
        "Você pode ter todo o talento do mundo, mas sem determinação não irá muito longe.",
        "A vitória é filha da preparação e da determinação.",
        "O jovem conhece as regras, mas o velho conhece as exceções.",
        "O pessimista reclama do vento, o otimista espera que ele mude, o realista ajusta as velas.",
        "O conhecimento não tem valor a menos que você o ponha em prática.",
        "Prefiro me arrepender das coisas que fiz do que das coisas que não fiz.",
        "É preciso sabedoria para entender a sabedoria. A música não é nada se o público for surdo.",
        "O maior perigo para a maioria de nós não está em mirar alto demais e ficar aquém, mas em mirar baixo demais e atingir o alvo.",
        "Em cada caminhada na natureza, recebemos muito mais do que buscamos.",
        "Não seguirei por onde o caminho pode levar, mas irei aonde não há caminho e deixarei uma trilha.",
        "O poderoso carvalho de hoje é apenas a noz de ontem que aguentou firme.",
        "Ser inteiramente honesto consigo mesmo é um bom exercício.",
        "Não podemos nos tornar o que precisamos ser permanecendo o que somos.",
        "Defina seu curso pelas estrelas, não pelas luzes de cada navio que passa.",
        "Se você não sabe para onde está indo, qualquer estrada o levará até lá.",
        "Você sempre terá duas escolhas: seu compromisso versus seu medo.",
        "Abençoados são aqueles que dão sem se lembrar e recebem sem esquecer.",
        "O que acontece não é tão importante quanto como você reage ao que acontece.",
        "Comece com o que é certo em vez do que é aceitável.",
        "O homem superior culpa a si mesmo. O homem inferior culpa os outros.",
        "A menor ação é melhor que as maiores intenções.",
        "O maior obstáculo para a descoberta não é a ignorância – é a ilusão do conhecimento.",
        "Cuidado com o falso conhecimento – é mais perigoso que a ignorância.",
        "A melhor forma de prever o futuro é inventá-lo.",
        "Vencer sem risco é triunfar sem glória.",
        "Nosso caráter é o que fazemos quando achamos que ninguém está olhando.",
        "Tudo que nos irrita nos outros pode nos levar a uma compreensão de nós mesmos.",
        "A arte de ser sábio é a arte de saber o que ignorar.",
        "Diga-me e eu esqueço. Ensine-me e eu lembro. Envolva-me e eu aprendo.",
        "Você tem o cérebro na sua cabeça. Você tem os pés nos seus sapatos. Você pode se dirigir para qualquer direção que escolher.",
        "Em três palavras posso resumir tudo que aprendi sobre a vida: ela continua.",
        "A vida consiste em experimentar coisas para ver se funcionam.",
        "O sucesso geralmente vem para aqueles que estão ocupados demais para procurá-lo.",
        "Eu não falhei – apenas encontrei 10.000 maneiras que não funcionam.",
        "Eu falhei meu caminho até o sucesso.",
        "Se você não se programar, a vida vai te programar.",
        "Não tenho tempo para sentir pena de mim mesmo. Não tenho tempo para reclamar. Vou seguir em frente.",
        "Se você não está disposto a arriscar o habitual, terá que se contentar com o comum.",
        "O sucesso foi definido como a capacidade de ir de fracasso em fracasso sem perder o entusiasmo.",
        "Todos os nossos sonhos podem se tornar realidade se tivermos a coragem de persegui-los.",
        "As oportunidades não acontecem – você as cria.",
        "Nunca sonhei com o sucesso, trabalhei por ele.",
        "Não deixe que o que você não pode fazer interfira no que pode fazer.",
        "Hoje é o único dia, ontem já se foi.",
        "As coisas funcionam melhor para aqueles que fazem o melhor do que as coisas oferecem.",
        "Se você está passando pelo inferno, continue andando.",
        "Você só vê as glórias públicas – nunca os sacrifícios privados para alcançá-las.",
        "Se você não valoriza seu tempo, os outros também não vão.",
        "Ninguém pode fazer você se sentir inferior sem o seu consentimento.",
        "Um homem bem-sucedido é aquele que consegue construir uma base sólida com os tijolos que os outros jogaram nele.",
        "O que nos parece provações amargas são frequentemente bênçãos disfarçadas.",
        "Nada no mundo é mais comum do que pessoas sem sucesso com talento.",
        "Não tente se tornar uma pessoa de sucesso, mas sim uma pessoa de valor.",
        "Se você não consegue explicar algo de forma simples, você não entende o suficiente.",
        "Você nunca falha até parar de tentar.",
        "Conhecimento é saber o que você pode fazer. Sabedoria é saber quando não fazê-lo.",
        "A vida não é sobre encontrar a si mesmo. A vida é sobre criar a si mesmo.",
        "O problema não é o problema – o problema é sua atitude em relação ao problema.",
        "Nenhuma obra-prima foi criada por um artista preguiçoso.",
        "O caminho para o sucesso e o caminho para o fracasso são quase exatamente iguais.",
        "Não é o que você olha que importa – é o que você vê.",
        "Coragem é resistência ao medo – domínio do medo, não ausência de medo.",
        "Descubro que quanto mais trabalho, mais sorte pareço ter.",
        "O brilho de um pensamento caloroso vale mais para mim do que dinheiro.",
        "Todo progresso acontece fora da zona de conforto.",
        "O pensamento deve se tornar seu ativo de capital, não importa quais altos e baixos você enfrente na vida.",
        "O sucesso é a soma de pequenos esforços repetidos dia após dia.",
        "O guerreiro bem-sucedido é o homem comum com foco de laser.",
        "O sucesso não consiste em nunca errar, mas em nunca cometer o mesmo erro pela segunda vez.",
        "Não deixe que o medo de perder seja maior que a empolgação de vencer.",
        "O primeiro passo é quando você se recusa a ser prisioneiro do seu ambiente.",
        "Não há congestionamento na milha extra.",
        "Sempre que você se encontrar do lado da maioria, é hora de parar e refletir.",
        "Sucesso é gostar de si mesmo, gostar do que faz e gostar de como faz.",
        "Um objetivo nem sempre é feito para ser alcançado – muitas vezes serve simplesmente como algo em que mirar.",
        "É melhor fracassar na originalidade do que ter sucesso na imitação.",
        "Motivação é o que te faz começar, hábito é o que te mantém.",
        "Você tem que se levantar toda manhã com determinação se quiser ir para a cama com satisfação.",
        "Você deve esperar grandes coisas de si mesmo antes de poder fazê-las.",
        "Dificuldades reais podem ser superadas – são apenas as imaginárias que são invencíveis.",
        "As pessoas raramente têm sucesso a menos que se divirtam com o que estão fazendo.",
        "É durante nossos momentos mais sombrios que devemos nos concentrar para ver a luz.",
        "O fracasso é o tempero que dá sabor ao sucesso.",
        "Mentes comuns são domadas e subjugadas pela adversidade, mas grandes mentes se erguem acima dela.",
        "Talvez você tenha que travar uma batalha mais de uma vez para vencê-la.",
        "O que você faria se não tivesse medo?",
        "Coisas boas vêm para quem espera, mas coisas melhores vêm para quem vai e as busca.",
        "Sempre dê o seu melhor, mesmo quando as chances estão contra você.",
        "Não espere seus sentimentos mudarem para agir – aja e seus sentimentos mudarão.",
        "A ação nem sempre traz felicidade, mas não há felicidade sem ação.",
        "A perfeição é entediante – melhorar é onde está toda a diversão.",
        "É difícil vencer alguém que nunca desiste.",
        "A diferença entre uma pedra de tropeço e um degrau é o quão alto você levanta o pé.",
        "Nunca desista, pois é exatamente ali e então que a maré vai virar.",
        "Às vezes, não conseguir o que quer é um maravilhoso golpe de sorte.",
        "Não posso mudar a direção do vento, mas posso ajustar minhas velas para sempre alcançar meu destino.",
        "Siga em frente. Não pare, não demore na sua jornada, mas lute pela meta que está diante de você.",
        "Se você realmente quer algo, não espere por isso – ensine-se a ser impaciente.",
        "Às vezes você vence, às vezes você aprende.",
        "Dois tipos de pessoas neste mundo: as que querem fazer as coisas e as que não querem cometer erros.",
        "Certifique-se de que seu pior inimigo não mora entre suas próprias orelhas.",
        "Lembre-se sempre de que você é absolutamente único – assim como todo mundo.",
        "Se você tem tudo sob controle, não está se movendo rápido o suficiente.",
        "Uma forma de manter o impulso é ter objetivos constantemente maiores.",
        "Você não precisa ver toda a escada – apenas dê o primeiro passo.",
        "O que nos parece provações amargas são frequentemente bênçãos disfarçadas.",
        "Duas opções quanto ao compromisso: ou você está dentro ou está fora – não existe vida no meio-termo.",
        "Quando você quer algo, todo o universo conspira para te ajudar a alcançá-lo.",
        "A felicidade não é algo pronto – ela vem das suas próprias ações.",
        "Seja lá o que você for, seja bom nisso.",
        "A dor é inevitável, o sofrimento é opcional.",
        "O talento acerta um alvo que ninguém mais pode acertar; o gênio acerta um alvo que ninguém mais pode ver.",
        "A mente é seu próprio lugar e em si mesma pode fazer um céu do inferno ou um inferno do céu.",
        "Eu odiava treinar, mas me disse: não desista – sofra agora e viva o resto da sua vida como campeão.",
        "Não são as montanhas à frente que te esgotam – é a pedra no seu sapato.",
        "O que pensamos, nos tornamos.",
        "Alguém está sentado na sombra hoje porque alguém plantou uma árvore muito tempo atrás.",
        "Um único raio de sol é suficiente para afastar muitas sombras.",
        "Para a mente que está quieta, todo o universo se rende.",
        "Com autodisciplina, quase tudo é possível.",
        "A melhor saída é sempre através.",
        "Sua grande oportunidade pode estar exatamente onde você está agora.",
        "Nada vale mais do que este dia.",
        "A única jornada é a interior.",
        "As circunstâncias não determinam aonde você pode ir – apenas determinam de onde você começa.",
        "A crença cria o fato real.",
        "O que torna o deserto bonito é que em algum lugar ele esconde um poço.",
        "Se as portas da percepção fossem purificadas, tudo apareceria ao homem como realmente é: infinito.",
        "Mude seus pensamentos e você muda seu mundo.",
        "O pássaro é impulsionado pela sua própria vida e pela sua motivação.",
        "Dê luz e as pessoas encontrarão o caminho.",
        "A melhor preparação para amanhã é fazer o seu melhor hoje.",
        "As ideias moldam o curso da história.",
        "Nem em um único fio estão enfileiradas todas as joias da vida.",
        "O que alcançamos interiormente mudará a realidade exterior.",
        "Sua própria determinação para o sucesso é mais importante do que qualquer outra coisa.",
        "Você sabe que está no caminho do sucesso se faria seu trabalho mesmo sem ser pago.",
        "Você se torna aquilo em que acredita.",
        "Se quer alcançar a excelência, pode começar hoje. A partir deste segundo, pare de fazer trabalho inferior.",
        "Se não está disposto a arriscar o habitual, terá que se contentar com o comum.",
        "Antes de qualquer coisa, a preparação é a chave do sucesso.",
        "Aprendi ao longo dos anos que, quando a mente está decidida, isso diminui o medo.",
        "A vida é feita de tantas despedidas soldadas juntas.",
        "Vencer não é tudo, mas querer vencer é.",
        "Você pode ficar desapontado se falhar, mas está condenado se não tentar.",
        "Erros são um fato da vida – é a resposta ao erro que conta.",
        "Se não gosta do caminho que está percorrendo, comece a pavimentar um novo.",
        "Ações falam mais alto que palavras, e isso é especialmente verdade com seus filhos.",
        "Um diamante é um pedaço de carvão que se saiu bem sob pressão.",
        "Caminhos difíceis frequentemente levam a destinos bonitos.",
        "Às vezes você nunca saberá o valor de um momento até que ele se torne uma memória.",
        "Nada pode apagar a luz que brilha de dentro.",
        "Para ter sucesso na vida, você precisa de três coisas: um osso dos desejos, uma espinha dorsal e senso de humor.",
        "Aqueles que não acreditam em magia nunca a encontrarão.",
        "Decidi que não posso pagar alguém para voltar no tempo, então é melhor superar isso.",
        "Tudo tem um preço – a questão é o que você está disposto a pagar por isso.",
        "Cresci mais, não com as vitórias, mas com os reveses.",
        "Tenho sorte de que qualquer medo que eu tenha dentro de mim, meu desejo de vencer é sempre mais forte.",
        "Você tem que acreditar em si mesmo quando ninguém mais acredita.",
        "Não tenha medo do fracasso – esse é o caminho para o sucesso.",
        "Eu gosto de críticas – elas te fortalecem.",
        "Sei que quero sempre dar o meu melhor.",
        "Todos que conheci que são bem-sucedidos são workaholics.",
        "Nunca fui competitivo com ninguém, apenas comigo mesmo.",
        "A crença em si mesmo e saber quem você é – essa é a base para tudo de grandioso.",
        "Tenho medo de não tentar.",
        "O caminho para redimir seu passado não é fugir dele, mas tentar entendê-lo e usá-lo como base para crescer.",
        "Jogar pelo seguro não vai te trazer nada neste mundo.",
        "Um grande truque é um grande truque, mas num fracassado simplesmente não funciona. Tudo se resume ao talento.",
        "Ou você evolui, ou desaparece.",
        "A semente deve crescer, independentemente do fato de estar plantada em pedra.",
        "Não importa quão difícil fique – peito para fora, cabeça erguida e lide com isso.",
        "Sempre dê o seu melhor, não deixe a pressão te fazer entrar em pânico.",
        "Você nunca sabe como ou quando terá impacto, ou quão importante seu exemplo pode ser para outra pessoa.",
        "Faça o que tem que fazer para fazer o que quer fazer.",
        "Não aspire ganhar a vida – aspire fazer a diferença.",
        "Tem que ser quem você é neste mundo, não importa o quê.",
        "Se você tem um inimigo, então aprenda e conheça seu inimigo – não fique apenas com raiva.",
        "Eu me esforço para ser como as maiores pessoas que já viveram.",
        "Onde eu me destaco é na ética de trabalho ridícula e doentia. Sabe, enquanto o outro está dormindo? Eu estou trabalhando.",
        "A vida é vivida no limite.",
        "Ser realista é o caminho mais percorrido para a mediocridade.",
        "O primeiro passo é dizer que você pode.",
        "O mundo não pode te dizer quem você é – você tem que descobrir quem é e ser assim para o bem ou para o mal.",
        "Você vai ter que reconhecer seus fracassos. Vai ter que abraçá-los e descobrir como superá-los.",
        "Meu pai me disse: nomeie seu preço no começo. Se algum dia ficar mais caro do que o preço que você nomeou, vá embora.",
        "Você acreditaria no que acredita se fosse o único que acreditasse nisso?",
        "Não me importo com o que as pessoas pensam, porque as pessoas não pensam.",
        "Nunca fui realmente bom em nada, exceto na capacidade de aprender.",
        "O melhor sentimento do mundo é ver os benefícios e recompensas do trabalho duro.",
        "Meus objetivos são tão altos que não tenho tempo para relaxar de forma alguma.",
        "A vida é curta demais para se preocupar com o que os outros dizem sobre você.",
        "Atrás de toda pessoa de sucesso há uma matilha de invejosos.",
        "Você pode fazer algo da sua vida – só depende da sua garra.",
        "Você tem inimigos? Bom – isso significa que você realmente defendeu algo.",
        "Todo sucesso começa com autodisciplina – começa com você.",
        "Com garra e um pouco de talento, você pode mover montanhas.",
        "O fracasso não é uma opção – é apenas um degrau.",
        "O sucesso não vem da noite para o dia – é quando você melhora um pouco a cada dia; tudo se soma.",
        "Quando a vida te coloca em situações difíceis, não diga \"por que eu\" – apenas diga \"tente comigo\".",
        "Sucesso em qualquer coisa sempre se resume a isso: foco e esforço. E controlamos ambos.",
        "Uma vez ouvi um sábio dizer que não existem homens perfeitos, apenas intenções perfeitas.",
        "Muitas vezes você para de andar porque diz: estou cansado de subir esta colina, nunca chegarei ao topo – e está a apenas dois passos do topo.",
        "Desafie-se – é o único caminho que leva ao crescimento.",
        "Você não pode se dar crédito pelo talento – só pode se dar crédito por usá-lo.",
        "A melhor forma de garantir uma derrota é desistir.",
        "Eu poderia ou assistir acontecer ou fazer parte disso.",
        "Quando algo é importante o suficiente, você faz, mesmo que as chances não estejam a seu favor.",
        "Se você se levanta de manhã e pensa que o futuro vai ser melhor, é um dia brilhante – caso contrário, não é.",
        "Está tudo bem ter todos os ovos numa cesta só, desde que você controle o que acontece com essa cesta.",
        "Se você só faz coisas nas quais já sabe a resposta de antemão, sua empresa desaparece.",
        "Você tem que estar disposto a ser mal interpretado se quiser inovar.",
        "Não existe hora ruim para inovar.",
        "Criar oportunidades significa olhar onde os outros não estão olhando.",
        "O capital de suor é o capital mais valioso que existe.",
        "Vivemos numa sociedade onde, quase sempre, o trabalho duro é recompensado.",
        "O universo não tem obrigação de fazer sentido para você.",
        "Não há educação maior do que aquela que é autodirigida.",
        "Ninguém é burro se é curioso.",
        "Não conheço nenhum momento na história humana em que a ignorância foi melhor que o conhecimento.",
        "Treine-se para não levar nada para o lado pessoal.",
        "Um homem pode fazer de si o que quiser se realmente acreditar nisso – deve estar pronto para trabalho duro e muitas desilusões.",
        "O que cada um de nós deve perceber é que nossa intenção sempre transparece.",
        "Não podemos ignorar o que realmente queremos criar.",
        "Só você e somente você pode mudar sua situação.",
        "Seja grato pelos tempos difíceis, pois eles te moldaram.",
        "Para se juntar aos 1% do topo, você tem que fazer o que os 99% não fazem.",
        "Eu crio meu próprio caminho – era reto e estreito. Eu via assim: você estava no meu caminho ou fora dele.",
        "Todos temos dúvidas de nós mesmos. Você não as nega, mas também não se rende a elas. Você as abraça.",
        "Muitos líderes falham porque não têm a coragem de tocar naquele nervo ou acertar aquela nota.",
        "O momento em que você desiste é o momento em que deixa outra pessoa vencer.",
        "Se você tem medo de falhar, provavelmente vai falhar.",
        "Percebi que a intimidação não existe realmente quando você está no estado de espírito certo.",
        "Este é o momento em que aceito que os tempos mais desafiadores sempre estarão atrás de mim e à minha frente.",
        "Ninguém sabe que vai ser campeão – você tem que trabalhar para chegar lá.",
        "Minha crença é mais forte que sua dúvida.",
        "Sucesso significa estar satisfeito com o que você faz todos os dias. É ter orgulho da pessoa melhor que você está se tornando.",
        "Se quer ter sucesso, tem que estar disposto a usar cada conexão que tem.",
        "Talento nunca é suficiente. Com poucas exceções, os melhores jogadores são os que mais trabalham.",
        "Não desista – faça amizade com pessoas que te ajudam a trabalhar duro.",
        "Apenas celebre a vida que teve, não a vida que poderia ter tido.",
        "Eu cresci pobre, mas não tinha sonhos pobres.",
        "Você é o único que pode fazer a diferença. Seja qual for seu sonho, vá atrás dele.",
        "A vida não para porque algo acontece com você.",
        "Na vida, ganhar e perder vão acontecer – o que nunca é aceitável é desistir.",
        "Vocês sabem quantas vezes fui rejeitado na minha vida? Quantas vezes me disseram que eu não conseguiria?",
        "Muitas vezes descubro que pessoas abençoadas com mais talento nunca desenvolvem aquela atitude. E as que não são tão abençoadas são as mais competitivas e têm o maior coração.",
        "Achei que nunca teria chance de jogar, até que um dia tive – porque estava preparado e a oportunidade se apresentou.",
        "Simplesmente amo a competição e amo tentar melhorar.",
        "Frequentemente algo acontece na vida e culpamos os outros por não sermos felizes, satisfeitos ou realizados.",
        "Sua vida será o que você fizer dela.",
        "Não vou me chatear porque alguém disse algo ruim sobre mim.",
        "Você não pode ficar de fora na vida.",
        "Minha mensagem é simples: assuma o controle da sua vida.",
        "Quando você é um dos líderes do time, não há dias de folga.",
        "Não dependa dos outros. Você terá grande apoio de muitas pessoas. Mas ninguém vai te dar nada de mão beijada.",
        "As coisas não se corrigem sozinhas – você tem que ir lá e trabalhar duro para corrigi-las.",
        "Se você não joga para ganhar, não jogue.",
        "Se você não acredita em si mesmo, por que alguém mais vai acreditar em você?",
        "Às vezes na vida, os maiores desafios acabam sendo as melhores coisas que acontecem.",
        "Simplesmente amo trabalhar duro.",
        "Os verdadeiros competidores são aqueles que sempre jogam para ganhar.",
        "Não persiga o dinheiro – persiga o sonho.",
        "Se quer voar, tem que largar as coisas que te puxam para baixo.",
        "Não quero que você sonhe – quero que você faça.",
        "Qualquer pessoa que queira ser alguém vai trabalhar o máximo que puder para realizar esse sonho.",
        "Nunca tentei esconder o fato de que minha intenção é me tornar o melhor.",
        "Se você não acredita que é o melhor, nunca alcançará tudo de que é capaz.",
        "Hoje existem oportunidades que ninguém sabe se voltarão no futuro.",
        "Talento sem trabalho duro não é nada.",
        "Não me importo que as pessoas me odeiem, porque isso me impulsiona.",
        "Talento não é tudo. Você pode tê-lo desde o berço, mas é preciso aprender o ofício para ser o melhor.",
        "Sinto uma necessidade infinita de aprender, de melhorar, de evoluir – para me sentir satisfeito comigo mesmo.",
        "Seu amor me fortalece. Seu ódio me torna imparável.",
        "Você pode superar qualquer coisa se amar algo o suficiente.",
        "Sou bem-sucedido porque fiz sacrifícios pelo sucesso.",
        "Minha ambição é sempre ficar melhor e melhor.",
        "Começo cedo e fico até tarde. Dia após dia, ano após ano – foram 17 anos e 114 dias para me tornar um sucesso da noite para o dia.",
        "A pessoa que me impedia de ser feliz era eu mesmo.",
        "O simples ato de prestar atenção pode te levar longe.",
        "Não confunda a verdade com a opinião das massas. Essas quase nunca são nem remotamente semelhantes.",
        "Há uma diferença entre conhecer o caminho e percorrer o caminho.",
        "Não tenho tempo para ficar acordada a noite toda me preocupando com o que alguém que não me ama tem a dizer sobre mim.",
        "Você não pode hesitar sobre quem você é.",
        "Sempre tem coisa para melhorar – você nunca chega lá.",
        "Quero ser o que sempre quis ser: dominante.",
        "Apenas tento ser o melhor que posso e espero que seja o melhor de todos os tempos.",
        "Não quero me tornar tão bom quanto já fui – quero me tornar melhor.",
        "Minha mente é meu maior ativo. Espero vencer cada torneio de que participo.",
        "Os caras que estão realmente controlando suas emoções são os que vão vencer.",
        "Não importa quão bom você seja, sempre pode melhorar – e essa é a parte empolgante.",
        "Para ajudar as pessoas, você primeiro precisa aprender a ajudar a si mesmo.",
        "Nada de valor vem a alguém sem ser como resultado de trabalho duro.",
        "Não permitirei que nenhum homem diminua minha alma fazendo-me odiá-lo.",
        "Você não pode manter um homem no chão sem ficar lá com ele.",
        "O caráter, não as circunstâncias, faz o homem.",
        "Há duas formas de exercer a força: uma é empurrar para baixo, a outra é puxar para cima.",
        "Falhei muito mais do que tive sucesso.",
        "Faço hoje o que os outros não fazem, para poder alcançar amanhã o que os outros não podem.",
        "Mesmo se perder, não perca a lição.",
        "A coisa mais fácil de vender é a verdade.",
        "Não espere o momento perfeito – você vai esperar para sempre. Sempre aproveite o tempo que tem e torne-o perfeito.",
        "Você só pode fazer poucas coisas de forma excelente – deixe todo o resto de lado.",
        "A vida é frágil. Não temos garantia de amanhã, então dê tudo de si.",
        "Não tenho medo de fazer papel de bobo.",
        "O respeito me motiva, não o sucesso.",
        "Quando você passa do auge, é aí que ganha velocidade.",
        "Excelência não é um ato – é um hábito.",
        "Você não pode tirar um 10 se tem medo de tirar zero.",
        "Você comete seus erros para aprender como chegar ao que é bom.",
        "Um herói é alguém que voluntariamente caminha para o desconhecido.",
        "Há milhões de sobreviventes por aí. Faça ser um milhão e um.",
        "Nunca desista, pois você nunca sabe o que a maré trará no próximo dia.",
        "Se não fosse difícil, todo mundo faria. É a dificuldade que torna grandioso.",
        "Se você só faz escolhas seguras, não cresce.",
        "Gosto de fazer algo que temo.",
        "O processo é a parte mais bonita.",
        "É fácil enganar o olho, mas é difícil enganar o coração.",
        "Nunca fique eufórico demais, nunca fique abatido demais. Leve dia a dia e continue aprendendo.",
        "O esforço nunca será questionado.",
        "Não espere que alguém te dê uma oportunidade – crie uma para si mesmo.",
        "Quando as pessoas me diziam que eu nunca conseguiria, eu ouvi a única pessoa que disse que eu podia: eu mesmo.",
        "Há uma razão pela qual se chama perseguir seus sonhos e não caminhar atrás deles.",
        "Para ter o que realmente quer, você deve primeiro ser quem realmente é.",
        "Não deixe o passado te assombrar. Porque o que você faz no presente pode assombrar seu futuro – seja sábio. O que você faz agora ou no futuro nunca vai mascarar seu passado, mas isso não significa deixar o passado te controlar.",
        "Aquele \"e se\" é uma ferida que nunca cicatriza.",
        "Se fosse fácil, não valeria a pena.",
        "Você não merece nada de graça – você conquista.",
        "A perfeição não é interessante – superar as adversidades e sair por cima: isso é o que me impressiona.",
        "Não participe das Olimpíadas do \"tenha pena de mim\" – não competimos nisso.",
        "Quando você quer algo, aceita o terreno que vem junto, seja qual for.",
        "A verdadeira visão é quando sua mente é mais poderosa do que o que está diante dos seus olhos.",
        "Certos acontecimentos vão te fazer progredir, certos acontecimentos farão o oposto – assim parece. Esses opostos são oportunidades de aprendizado que se provarão úteis no futuro.",
        "Pague o preço para ser o chefe ou pague o preço que vem com o arrependimento.",
        "A opinião dos outros sobre você não precisa se tornar sua realidade.",
        "Você não recebe o que deseja, recebe pelo que trabalha.",
        "A autodisciplina começa com o domínio dos seus pensamentos. Se não controla o que pensa, não pode controlar o que faz. Simplesmente, a autodisciplina permite pensar primeiro e agir depois.",
        "O que é derrota? Nada além de educação; nada além do primeiro passo para algo melhor.",
        "Não é o que acontece com você, mas como você reage que importa.",
        "Controle sua raiva. Se você tem raiva dos outros, eles controlam você.",
        "Seu maior desafio é aparecer quando sua mente está criando as melhores desculpas.",
        "Você pode experimentar a dor da disciplina ou a dor do arrependimento. A escolha é sua.",
        "Tudo que te enfraquece física, intelectual e espiritualmente – rejeite como veneno.",
        "Sue mais na paz, sangre menos na guerra.",
        "Com a coragem de começar e a disciplina de persistir, a vitória se torna questão de tempo.",
        "Um bom líder é alguém que assume um pouco mais que sua parte da culpa e um pouco menos que sua parte do crédito.",
        "Seja forte, mas não rude. Seja gentil, mas não fraco. Seja ousado, mas não intimidador. Seja humilde, mas não tímido. Seja orgulhoso, mas não arrogante.",
        "A paciência é amarga, mas seu fruto é doce.",
        "A paciência não é passiva – pelo contrário, é ativa. É força concentrada.",
        "Não há nada impossível para aquele que tenta.",
        "Inteligência não é a capacidade de armazenar informação, mas de saber onde encontrá-la.",
        "Primeiro é uma intenção. Depois um comportamento. Depois um hábito. Depois uma prática. Depois uma segunda natureza. Depois é simplesmente quem você é.",
        "O que quer que queira fazer, faça agora. Só existem tantos amanhãs.",
        "Pessoas que dizem que não pode ser feito não deveriam interromper aqueles que estão fazendo.",
        "Só existe um canto do universo que você pode ter certeza de melhorar – você mesmo.",
        "O tolo pensa que é sábio, mas o sábio sabe que é tolo.",
        "A dor pode te mudar, mas isso não precisa ser uma mudança ruim. Pegue essa dor e transforme-a em sabedoria.",
        "O tempo é realmente o único capital que qualquer ser humano possui, e a única coisa que não pode se dar ao luxo de perder.",
        "Siga seu próprio caminho, não importa o que as pessoas digam.",
        "Faça algo. Se funcionar, faça mais. Se não, faça outra coisa.",
        "Aprender é a única coisa que a mente nunca esgota, nunca teme e nunca se arrepende.",
        "Um vencedor é um sonhador que nunca desiste.",
        "Se não luta pelo que quer, não chore pelo que perdeu.",
        "Uma vez que aceitar seus defeitos, ninguém pode usá-los contra você.",
        "Uma vez que tivermos aprendido o suficiente sobre o universo, admitiremos que nunca saberemos tudo.",
        "Preocupar-se é como pagar uma dívida que você não deve.",
        "Você não pode ensinar ninguém – só pode fazê-los perceber que as respostas já estão dentro deles.",
        "O poder dos pensamentos pode causar tanto doença quanto recuperação.",
        "Se quer ver um milagre, seja um milagre.",
        "Há três classes de pessoas: as que veem, as que veem quando lhes mostram, e as que não veem.",
        "Seus maiores medos são criados pela sua imaginação.",
        "O maior engano de que os homens sofrem vem de suas próprias opiniões.",
        "Quando você esgotou todas as possibilidades, lembre-se: você não esgotou.",
        "Ame a mão que o destino te deu e jogue-a como se fosse sua.",
        "Se duas pessoas concordam em tudo, uma delas é desnecessária.",
        "A maior competição é aquela que você tem consigo mesmo.",
        "Quando estamos cansados, somos atacados por ideias que conquistamos há muito tempo.",
        "Não sou o que me aconteceu. Sou o que escolho me tornar.",
        "O fator mais importante para a sobrevivência não é inteligência nem força, mas adaptabilidade.",
        "Fé e medo exigem que você acredite em algo que não pode ver. Você escolhe.",
        "Ao reclamar, você diz às pessoas o quão fraco é.",
        "Para conseguir o que ama, primeiro deve ser paciente com o que odeia.",
        "Quando tudo parece estar contra você, lembre-se de que o avião decola contra o vento, não a favor.",
        "Você vai rir dos seus medos quando descobrir quem realmente é.",
        "A paz não é encontrada numa tempestade mais calma – é encontrada num barco melhor.",
        "Você pode ignorar a realidade, mas não pode ignorar as consequências de ignorar essa realidade.",
        "Nenhum homem é mais infeliz do que aquele que nunca enfrenta adversidade. Pois não lhe é permitido provar a si mesmo.",
        "Um bom plano executado com vigor agora é melhor que um plano perfeito executado na semana que vem.",
        "Estudar e não pensar é desperdício. Pensar e não estudar é perigoso.",
        "O medo é uma reação. A coragem é uma decisão.",
        "A independência é para pouquíssimos; é um privilégio dos fortes.",
        "Leva metade da vida para descobrir que a vida é um projeto faça-você-mesmo.",
        "Desempenhe seu papel com honra.",
        "A preocupação é um mau uso da imaginação.",
        "A ponte entre o conhecimento e a habilidade é a prática. A ponte entre a habilidade e a maestria é o tempo.",
        "Quanto mais aprendo, mais percebo o quanto ainda tenho para aprender.",
        "Se você não perde, não pode apreciar as vitórias. Então tenho que aceitar ambas.",
        "Da vitória aprendemos pouco, da derrota muito.",
        "Quem fala com deferência mas aumenta seus preparativos avançará. Quem fala belicosamente e avança apressadamente recuará.",
        "Nossa vida é o que nossos pensamentos fazem dela.",
        "Não existe realmente algo difícil, a menos que você decida que é difícil. Caso contrário, é só a próxima coisa que você está resolvendo.",
        "Não importa a situação – nunca deixe suas emoções dominarem sua inteligência.",
        "Decida o tipo de pessoa que quer ser e mantenha-se assim – esteja sozinho ou em companhia.",
        "Se algo está errado, conserte se puder. Mas treine-se para não se preocupar. A preocupação nunca consertou nada.",
        "A vida não é questão de ter boas cartas, mas de jogar bem uma mão ruim.",
        "É um caminho áspero que leva às alturas da grandeza.",
        "No dia em que um homem se tornar superior ao prazer, também será superior à dor.",
        "Aprenda continuamente – sempre há mais uma coisa para aprender.",
        "Podemos reclamar que as roseiras têm espinhos, ou nos alegrar que os espinheiros têm rosas.",
        "Seja paciente e forte; um dia essa dor será útil para você.",
        "O fracasso é sucesso em andamento.",
        "Qualquer pessoa que para de aprender é velha, seja aos vinte ou aos oitenta.",
        "Se é governado pela mente, é um rei; se pelo corpo, um escravo.",
        "O orgulho não é o oposto da vergonha, mas sua fonte. A verdadeira humildade é o único antídoto para a vergonha.",
        "Quando você começa a se melhorar, a solidão é o preço que paga.",
        "Você não é julgado pela altura que alcançou, mas pela profundidade de onde subiu.",
        "Um homem não é grande porque nunca falhou; um homem é grande porque o fracasso não o deteve.",
        "Um homem sem visão é um homem sem futuro. Um homem sem futuro sempre voltará ao seu passado.",
        "Melhor fracassar com honra do que ter sucesso por fraude.",
        "Todas as batalhas são primeiro vencidas ou perdidas na mente.",
        "As emoções do homem são provocadas mais rapidamente que sua inteligência.",
        "Quem compra o que não precisa rouba de si mesmo.",
        "Quem tem paciência pode ter o que quiser.",
        "O caminho do guerreiro é para toda a vida, e a maestria muitas vezes é simplesmente permanecer no caminho.",
        "As pipas sobem mais alto contra o vento, não com ele.",
        "Se as pessoas soubessem o quão duro tive que trabalhar para ganhar minha maestria, não pareceria tão maravilhoso.",
        "Nunca vá dormir sem um pedido ao seu subconsciente.",
        "Acolha os eventos de qualquer forma que aconteçam – esse é o caminho para a paz.",
        "Pratique até o que parece impossível.",
        "O homem que persegue dois coelhos não pega nenhum.",
        "Você vai conseguir, mas vai sempre parecer que não vai.",
        "Planeje o que é difícil enquanto é fácil, faça o que é grande enquanto é pequeno.",
        "A persistência sozinha não é suficiente. É preciso decidir se persistir como sofredor ou como guerreiro.",
        "O nível de precisão e disciplina necessário para te levar às alturas que sonha é realmente simples – só não é fácil.",
        "O maior inimigo não está do lado de fora. A destruição muitas vezes vem de dentro.",
        "Todos sabiam que era impossível – até que um tolo que não sabia veio e fez.",
        "Você não pode fortalecer um homem fraco enfraquecendo um homem forte.",
        "Você tem poder sobre sua mente – não sobre eventos externos. Perceba isso e encontrará força.",
        "Um diamante é apenas um pedaço de carvão que se manteve firme no trabalho.",
        "O maior risco é não correr nenhum risco.",
        "Se você definir o problema corretamente, quase terá a solução.",
        "O passado está na sua cabeça, o futuro está nas suas mãos.",
        "A vida é bem simples. Você faz umas coisas. A maioria falha. Algumas funcionam. Você faz mais do que funciona.",
        "Que seu senso de dever supere uma atmosfera de medo e a tendência de adiar aspirações.",
        "Tudo que você sempre quis está do outro lado do medo.",
        "Disciplina é escolher entre o que você quer agora e o que você mais quer.",
        "A conformidade é o último refúgio dos sem imaginação.",
        "Um diamante é um pedaço de carvão que se manteve firme no trabalho.",
        "Não há dano maior ao homem do que o tempo desperdiçado.",
        "Não estrague o que tem desejando o que não tem; lembre-se de que o que agora possui já esteve entre as coisas que apenas esperava ter.",
        "Um homem que é mestre da paciência é mestre de tudo o mais.",
        "Nunca coloque a paixão na frente dos princípios – mesmo se vencer, perderá.",
        "Alguns querem que aconteça, alguns desejam que aconteça, outros fazem acontecer.",
        "Não subimos ao nível das nossas expectativas – caímos ao nível do nosso treino.",
        "É mais fácil encontrar homens que se voluntariem para morrer do que aqueles dispostos a suportar dor com paciência.",
        "Não pode esperar subir ao pódio se não participa da corrida.",
        "Aquele que cai e se levanta é mais forte que aquele que nunca tentou.",
        "Má notícia: você não vai se encaixar com todo mundo. Boa notícia: os grandes nunca se encaixam.",
        "Nunca fui talentoso – só sou bom em nunca desistir.",
        "A felicidade não é a ausência de problemas – é a capacidade de lidar com eles.",
        "Se você faz o que é fácil, sua vida será difícil.",
        "Você não pode voltar e mudar o começo, mas pode começar de onde está e mudar o final.",
        "Mais se aprende por observação do que por instrução.",
        "Quem nunca comete erros trabalha para os que cometem.",
        "Uma nova ideia não deve ser julgada por seus resultados imediatos.",
        "Você nunca está pronto para o que tem que fazer. Você simplesmente faz. Isso te torna pronto.",
        "Corra riscos: se ganhar, será feliz; se perder, será sábio.",
        "Um povo que valoriza seus privilégios acima de seus princípios logo perde ambos.",
        "O caminho mais rápido para significado e sucesso: escolha uma coisa e vá com tudo.",
        "Não tenha medo de recomeçar. Desta vez, você não está começando do zero – está começando da experiência.",
        "Não há nada nobre em ser superior ao seu semelhante; a verdadeira nobreza é ser superior ao seu antigo eu.",
        "Você ganhará o respeito de todos se começar ganhando o respeito de si mesmo.",
        "Crie uma visão de quem quer ser e viva dentro dessa imagem como se já fosse verdade.",
        "O preço da excelência é a disciplina. O custo da mediocridade é a decepção.",
        "As dificuldades fortalecem a mente, assim como o trabalho fortalece o corpo.",
        "Você não pode esperar progredir em áreas onde não tomou nenhuma ação.",
        "Nenhuma quantidade de ansiedade faz qualquer diferença no que vai acontecer.",
        "Mostre-me um homem de habilidade média mas desejo extraordinário e eu lhe mostrarei um vencedor todas as vezes.",
        "O caminho mais rápido para o sucesso é começar agora e ir descobrindo pelo caminho.",
        "As pessoas não decidem seus futuros – decidem seus hábitos, e seus hábitos decidem seus futuros.",
        "Ensine seus filhos cedo o que você aprendeu tarde.",
        "Se você investir 100 horas por ano em qualquer disciplina (apenas 18 minutos por dia), será melhor que 95% do mundo nessa disciplina.",
        "A tarefa não é tanto ver o que ninguém ainda viu, mas pensar o que ninguém ainda pensou sobre aquilo que todos veem.",
        "Se cada atrito te irrita, como seu espelho será polido?",
        "O medo é tão profundo quanto a mente permite.",
        "A dificuldade é o que desperta o gênio.",
        "O que deve dar luz deve suportar o fogo.",
        "Aprendi que o sucesso não deve ser medido tanto pela posição que alguém alcançou na vida, mas pelos obstáculos que superou ao tentar ter sucesso.",
        "O conforto é o pior vício.",
        "Você se torna aquilo a que dá atenção.",
        "As circunstâncias não fazem o homem – apenas o revelam a si mesmo.",
        "Não perca mais tempo discutindo o que um homem bom deveria ser. Seja um.",
        "Que aquele que quer mover o mundo primeiro mova a si mesmo.",
        "Entre o estímulo e a resposta há um espaço. Nesse espaço está nosso poder de escolher nossa resposta. Em nossa resposta está nosso crescimento e nossa liberdade.",
        "Não há nada fora de você que possa te permitir ficar melhor, mais forte, mais rico, mais rápido ou mais inteligente. Tudo está dentro. Tudo existe. Não busque nada fora de si mesmo.",
        "Seja tolerante com os outros e rigoroso consigo mesmo.",
        "Duas coisas te definem: sua paciência quando não tem nada e sua atitude quando tem tudo.",
        "Você não simplesmente acorda e se torna a borboleta.",
        "Tenacidade é a capacidade de segurar firme quando soltar parece mais atraente.",
        "Há riscos e custos na ação. Mas são muito menores que os riscos de longo prazo da inação confortável.",
        "Para alcançar grandes coisas, duas coisas são necessárias: um plano e não tempo suficiente.",
        "A dúvida só pode ser removida pela ação.",
        "Se suas ações inspiram outros a sonhar mais, aprender mais, fazer mais e se tornar mais, você é um líder.",
        "Não se trata de ter um histórico impecável. Trata-se de aprender com as imperfeições do seu histórico.",
        "Seja corajoso o suficiente para ser ruim em algo novo.",
        "Vá para a cama mais inteligente do que quando acordou.",
        "Sucesso lento constrói caráter, sucesso rápido constrói ego.",
        "Só porque alguém tropeça e perde o caminho não significa que está perdido para sempre.",
        "Mas não podemos simplesmente sentar e encarar nossas feridas para sempre.",
        "E agora que você não precisa ser perfeito, pode ser bom.",
        "O sucesso vem da execução implacável dos fundamentos.",
        "É preciso muito trabalho duro para tornar algo simples.",
        "Todo mundo pensa em mudar o mundo, mas ninguém pensa em mudar a si mesmo.",
        "Os de mente fechada precisam que a arte lhes seja dada de colher na boca.",
        "Faça algo em vez de matar o tempo. Porque o tempo está te matando.",
        "Que cada decisão esteja alinhada com sua visão.",
        "Se quer fazer algo maior que a média, não pode ceder ao medo de ser um pária.",
        "O que mais importa é quão bem você caminha pelo fogo.",
        "Você está a uma decisão de uma vida completamente diferente.",
        "Se está vivendo para amanhã, estará sempre um dia atrás.",
        "Faça o máximo de si, pois isso é tudo que existe de você.",
        "Olhos são inúteis quando a mente é cega.",
        "A longo prazo, os homens só acertam aquilo em que miram. Portanto, mesmo que falhem imediatamente, é melhor mirar em algo alto.",
        "Quem tem um porquê para viver pode suportar quase qualquer como.",
        "Os homens podem ser divididos em 2 grupos: um que avança e realiza algo, e outro que vem depois e critica.",
        "Uma atitude ruim é como um pneu furado. Você não vai a lugar nenhum até trocá-lo.",
        "Nenhum pássaro voa alto demais se voa com suas próprias asas.",
        "Resolva o problema ou abandone o problema. Não conviva com o problema.",
        "Aja de acordo com seus princípios, não com seu humor.",
        "Aqueles que não se comprometem com nada são distraídos por tudo.",
        "Quando nos esforçamos para nos tornar melhores do que somos, tudo ao nosso redor também melhora.",
        "Não há paixão em se contentar com uma vida inferior àquela de que é capaz.",
        "Uma pessoa criativa é motivada pelo desejo de realizar, não pelo desejo de vencer outros.",
        "A vida é uma longa preparação para algo que nunca acontece.",
        "Não escuto mais o que as pessoas dizem – apenas observo o que fazem. O comportamento nunca mente.",
        "Pessoas inteligentes aprendem com tudo e todos; pessoas comuns, com suas experiências. Os estúpidos já têm todas as respostas.",
        "A primeira regra é manter um espírito tranquilo. A segunda é olhar as coisas de frente e reconhecê-las pelo que são.",
        "É sempre uma luta levantar peso maior.",
        "Um homem que teme o sofrimento já está sofrendo pelo que teme.",
        "Se um homem não sabe a que porto navega, nenhum vento é favorável.",
        "Estou sempre fazendo aquilo que não sei fazer, para poder aprender como se faz.",
        "Você constrói sobre o fracasso. Usa-o como degrau. Feche a porta para o passado. Não tente esquecer os erros, mas não fique remoendo. Não deixe que tomem sua energia, seu tempo ou seu espaço.",
        "O conteúdo do seu caráter é sua escolha. Dia a dia, o que você escolhe, pensa e faz é quem você se torna.",
        "Os covardes nunca começaram e os fracos morreram pelo caminho.",
        "Quando você acorda pela manhã, pense em que privilégio precioso é estar vivo – respirar, pensar, aproveitar, amar.",
        "O segredo do sucesso é a concentração no objetivo.",
        "A única coisa mais perigosa que a ignorância é a arrogância.",
        "Somos o que fazemos repetidamente. A excelência, portanto, não é um ato, mas um hábito.",
        "Enquanto esperamos pela vida, a vida passa.",
        "Sucesso não é nada mais que algumas disciplinas simples praticadas todos os dias.",
        "Quanto mais ele sabe, mais consciente fica de sua ignorância.",
        "O impedimento à ação avança a ação. O que está no caminho se torna o caminho.",
        "Nossa maior fraqueza está em desistir. A maneira mais certa de ter sucesso é sempre tentar mais uma vez.",
        "Uma joia não pode ser polida sem atrito, nem um homem aperfeiçoado sem provações.",
        "Seu valor consiste no que você é e não no que você tem.",
        "O malfeitor é mais infeliz que aquele a quem se fez mal.",
        "Um dos mais verdadeiros testes de integridade é sua recusa categórica em ser comprometida.",
        "Deus nada dá àqueles que mantêm os braços cruzados.",
        "Saber como pensar te capacita muito mais do que aqueles que só sabem o que pensar.",
        "Se planeja ser menos do que é capaz, provavelmente será infeliz todos os dias da sua vida.",
        "Não há nada melhor que a adversidade. Cada derrota, cada desilusão, cada perda contém sua própria semente, sua própria lição de como melhorar seu desempenho na próxima vez.",
        "Aprenda a amar o ódio. Abrace-o. Aproveite-o. Você o mereceu. Todos têm direito à sua opinião e todos deveriam ter uma sobre você. Odiadores são um bom problema. Ninguém odeia os bons. Odeiam os grandes.",
        "Aceite sua incapacidade de controlar todas as coisas. Aceite a responsabilidade por tudo sob seu controle. Aceite que obstáculos internos e externos existem. Aceite que você está equipado para navegar por todos eles.",
        "A experiência é o tipo mais difícil de professor. Ela te dá o teste primeiro e a lição depois.",
        "Amadurecemos com os danos, não com os anos.",
        "Se está deprimido, está vivendo no passado. Se está ansioso, está vivendo no futuro. Se está em paz, está vivendo no presente.",
        "Se você acha que não podemos mudar o mundo, isso só significa que você não é um dos que vão mudá-lo.",
        "Talvez não seja sobre um final feliz. Talvez seja sobre a história.",
        "Algumas pessoas trazem alegria aonde vão, e outras trazem alegria quando vão.",
        "Observe constantemente que todas as coisas acontecem por mudança, e acostume-se a considerar que a natureza do universo nada ama tanto quanto a mudança.",
        "Ser bom demais tende a ser desinteressante.",
        "Com muita frequência desfrutamos do conforto da opinião sem o desconforto do pensamento.",
        "Estudo sem pensamento é vão; pensamento sem estudo é perigoso.",
        "Um homem com convicção sobrepujará cem que têm apenas opiniões.",
        "Os tolos se multiplicam quando os sábios se calam.",
        "Esteja pronto para revisar qualquer sistema, descartar qualquer método, abandonar qualquer teoria se o sucesso do trabalho exigir.",
        "Ajudar outros a se desenvolver e ter sucesso na vida é uma recompensa em si e só tem valor quando nada é esperado em troca.",
        "Agora não é hora de pensar no que não tem. Pense no que pode fazer com o que há.",
        "Eu diria que sou uma obra em progresso, mas isso sugeriria que um dia eu não seria mais uma obra em progresso.",
        "Não desista. Normalmente é a última chave do chaveiro que abre a porta.",
        "A vida é uma comédia para quem pensa, uma tragédia para quem sente.",
        "Tato é a capacidade de mandar alguém para o inferno de tal forma que a pessoa fique ansiosa pela viagem.",
        "Deixe o mal feito por outro onde o mal surgiu.",
        "Não se perturbe imaginando toda a sua vida de uma vez. Não fique sempre pensando em que sofrimentos, e quantos, poderiam te acometer.",
        "Toda vez que penso que sei tudo, \"tudo\" se revela ter um pouco mais de volume do que eu supunha.",
        "A diferença entre estupidez e gênio é que o gênio tem seus limites.",
        "É melhor ser um guerreiro num jardim do que um jardineiro numa guerra.",
        "Grande sucesso sempre vem com o risco de fracasso enorme.",
        "O sucesso vem da curiosidade, concentração, perseverança e autocrítica.",
        "É a marca de uma mente educada ser capaz de entreter um pensamento sem aceitá-lo.",
        "A opinião de 10.000 pessoas não tem valor se nenhuma delas sabe algo sobre o assunto.",
        "Quanto mais valorizamos coisas fora do nosso controle, menos controle temos.",
        "Faça viagens. Tente-as. Não há nada mais.",
        "As origens nunca devem ser uma barreira para o sucesso. Um começo modesto na vida pode ser mais uma ajuda do que um obstáculo.",
        "Não deixe que as deficiências de outro façam você ficar aquém.",
        "Nossa inveja sempre dura mais do que a felicidade daqueles que invejamos.",
        "Do nada, nada virá.",
        "Pessoas fracas se vingam. Pessoas fortes perdoam. Pessoas inteligentes ignoram.",
        "Eu não controlo o vento; eu apenas o estudo.",
        "A honra pode não conquistar poder, mas conquista respeito. E respeito conquista poder.",
        "A arma final é o cérebro – todo o resto é suplementar.",
        "Se não superar sua tendência de desistir facilmente, sua vida não levará a nada.",
        "Treinar é como varrer o chão. Só porque fizemos uma vez não significa que o chão está limpo para sempre.",
        "Lembre-se de que somos nós que nos atormentamos, nós que criamos dificuldades – isto é, nossas opiniões. O que significa, por exemplo, ser insultado? Fique ao lado de uma pedra e insulte-a – o que você conseguiu? Se alguém responde a um insulto como uma pedra, o que o agressor ganhou com sua ofensa?",
        "Na ausência de propósito, a vida se torna uma jornada sem fim para lugar nenhum.",
        "Só os mortos viram o fim da guerra.",
        "Prevenir é melhor do que remediar.",
        "Nada ensinado à força permanece na alma.",
        "Tudo que existe na sua vida existe por causa de duas coisas: algo que você fez ou algo que não fez.",
        "Um homem sem ética é uma fera selvagem solta neste mundo.",
        "Pensar é difícil – é por isso que a maioria das pessoas julga.",
        "Você não encontra força de vontade – você a cria.",
        "A palavra feliz perderia seu significado se não fosse equilibrada pela tristeza.",
        "Não reze por uma vida fácil. Reze pela força de suportar uma vida difícil.",
        "Você não é tudo que poderia ser, e você sabe disso.",
        "Lembre-se de viver enquanto está ocupado sobrevivendo.",
        "Planos não são nada, planejar é tudo.",
        "Um homem que ousa desperdiçar uma hora do seu tempo não descobriu o valor da vida.",
        "Você tem que decidir quem é e forçar o mundo a lidar com você, não com a ideia que ele tem de você.",
        "A arte de viver se assemelha mais à luta que à dança, na medida em que se mantém firme contra o acidental e o imprevisto, e não é propensa a cair.",
        "Conforme envelheço, presto menos atenção ao que os homens dizem. Apenas observo o que fazem.",
        "Aperto o cinto antes de pedir ajuda.",
        "Ninguém é construído como você – você se projetou.",
        "Nenhum homem tem o direito de ser um amador em matéria de treinamento físico. É uma vergonha para um homem envelhecer sem ver a beleza e a força de que seu corpo é capaz.",
        "Quanto mais perto um homem chega de uma mente calma, mais perto está da força.",
        "Aqui está uma regra para lembrar no futuro, quando algo te tentar a se sentir amargo: não \"Isso é infortúnio\", mas \"Suportar isso com dignidade é boa sorte\".",
        "Quando você é bom em algo, vai contar a todo mundo. Quando é ótimo em algo, eles vão te contar.",
        "Primeiro eles te ignoram. Depois te ridicularizam. Depois te atacam e querem te queimar. E depois constroem monumentos para você.",
        "Liberdade significa responsabilidade. É por isso que a maioria dos homens a teme.",
        "Se você diz a verdade, não precisa se lembrar de nada.",
        "Seu momento está chegando se você continuar.",
        "Não é a morte que um homem deve temer, mas deve temer nunca começar a viver.",
        "Os procedimentos de hoje são os resultados de amanhã. Se conseguir se apaixonar pelos procedimentos de hoje, amará os resultados de amanhã.",
        "Todos os problemas da humanidade decorrem da incapacidade do homem de se sentar quieto num quarto sozinho.",
        "Nunca deixe o futuro te perturbar. Você o enfrentará, se precisar, com as mesmas armas da razão que hoje te armam contra o presente.",
        "O homem amadurece através da dor, fracasso, rejeição, perda, desrespeito e desilusão amorosa – não pela idade.",
        "Forjamos as correntes que usamos na vida.",
        "Para fazer qualquer coisa em alto nível, tem que ser uma obsessão.",
        "Se quer melhorar, contente-se em ser considerado tolo e estúpido no que diz respeito a coisas externas.",
        "A violência é o último refúgio do incompetente.",
        "O medo é como fogo – pode ser útil se você souber usá-lo. Se não, vai se queimar.",
        "Para ter grande sucesso, você tem que estar preparado para falhar grandemente. Se não consegue ambos, tem um problema.",
        "Sempre falamos de alguém nos odiar \"sem razão\", mas as pessoas vão gostar de você \"sem razão\" também. Então não dê tanto peso a nenhum dos lados.",
        "Os covardes morrem muitas vezes antes de suas mortes; os valentes só provam a morte uma vez.",
        "Nada é mais difícil, e portanto mais precioso, do que ser capaz de decidir.",
        "Caminhe por um único caminho, sem ficar arrogante com a vitória nem abatido pela derrota, sem esquecer a cautela quando tudo está tranquilo nem se amedrontar quando o perigo ameaça.",
        "A alma se tinge com a cor dos seus pensamentos.",
        "Não peço um fardo mais leve, mas ombros mais largos.",
        "Não negocie consigo mesmo. Instrua-se.",
        "Você não pode desejar ao mesmo tempo caráter forte e uma vida fácil.",
        "Coragem não é ter a força para continuar – é continuar quando não se tem força.",
        "A vida não acontece com você – acontece envolvendo você.",
        "É fatal entrar numa guerra sem a vontade de vencê-la.",
        "Você nunca sabe o quão forte é até que ser forte é sua única opção.",
        "Não dá para agradar a todos – às vezes você tem que agir e deixar os outros reagirem.",
        "Não há questão de \"se\" – a questão é apenas quando, quando você está resoluto sobre a missão.",
        "Quanto tempo vai esperar antes de exigir o melhor para si mesmo?",
        "O mundo te promete conforto, mas você não foi feito para o conforto. Você foi feito para a grandeza.",
        "Integridade não é um caminho rápido, mas é um caminho seguro.",
        "Seja seu próprio maior fã, seu próprio maior crente, e carregue o peso nas suas costas.",
        "Primeiro diga a si mesmo o que quer ser; e depois faça o que tem que fazer.",
        "Temo o dia em que a tecnologia ultrapassará a interação humana. O mundo terá uma geração de idiotas.",
        "Não importa o que você suporta, mas como você suporta.",
        "Rejeite sua sensação de ofensa e a própria ofensa desaparece.",
        "Não faça planos pequenos. Eles não têm a magia de agitar o sangue dos homens e provavelmente não serão realizados. Faça grandes planos; mire alto em esperança e trabalho, lembrando que um diagrama nobre e lógico, uma vez registrado, nunca morrerá, mas muito depois de termos ido será uma coisa viva, afirmando-se com insistência cada vez maior.",
        "As dificuldades frequentemente preparam pessoas comuns para um destino extraordinário.",
        "Quando quer mudar as coisas, não pode agradar a todos. Se agrada a todos, não está fazendo progresso suficiente.",
        "Não negocie consigo mesmo, instrua-se.",
        "O sucesso não é definitivo, o fracasso não é fatal: é a coragem de continuar que conta.",
        "Se não é certo, não faça; se não é verdade, não diga.",
        "Os chamados prazeres, quando ultrapassam certo limite, não passam de punições.",
        "Se não sacrifica pelo que quer, o que quer se torna o sacrifício.",
        "Seu maior inimigo é sua mente descontrolada.",
        "Aprenda a lutar para nunca ter que lutar.",
        "Quando uma pessoa não consegue encontrar um senso profundo de significado, distrai-se com prazer.",
        "Nada é permanente neste mundo perverso, nem mesmo nossos problemas.",
        "Deixe que estejam errados sobre você. Não há nada a provar.",
        "Se quer que o presente seja diferente do passado, estude o passado.",
        "Se quer viver uma vida feliz, amarre-a a um objetivo, não a pessoas ou coisas.",
        "Não existem segredos – existem apenas as informações que você descobriu e as que ainda não descobriu.",
        "Você precisa de motivação para agir. Precisa de informação para saber como agir. Precisa de curiosidade para obter inteligência que pilote adequadamente esses atos motivados. Então seja curioso.",
        "Um vencedor é apenas um perdedor que tentou mais uma vez.",
        "Tratamos o corpo rigorosamente para que não seja desobediente à mente.",
        "Os dispostos são guiados pelo destino, os relutantes são arrastados.",
        "O homem que teme a morte nunca fará nada digno de um homem que está vivo.",
        "Um comandante nunca deposita tanta confiança na paz a ponto de não se preparar para a guerra.",
        "Não tenha medo. Você vai conseguir, mas vai sempre parecer que não vai.",
        "Consistência pode soar muito como entediante, mas o que mais você achava que ser ótimo era? Sorte?",
        "Mantenha seu rosto sempre voltado para o sol e as sombras ficarão atrás de você.",
        "A penalidade mais pesada por recusar governar é ser governado por alguém inferior a você.",
        "Cave dentro de si. Dentro está a fonte do Bem; e está sempre pronta a brotar, se você apenas cavar.",
        "Você é o que faz, não o que diz que vai fazer.",
        "Errar à sua própria maneira é melhor do que acertar à maneira de outro.",
        "Um grande homem é duro consigo mesmo, um homem fraco é duro com os outros.",
        "Amar a si mesmo é o início de um romance para toda a vida.",
        "Preocupe-se com o que os outros pensam e será sempre prisioneiro deles.",
        "O homem não é perturbado por problemas reais tanto quanto pelas ansiedades que imagina sobre problemas reais.",
        "O homem feliz está satisfeito com sua situação presente, não importa qual seja.",
        "A primeira e maior vitória é conquistar a si mesmo.",
        "Para me controlar, devo primeiro me aceitar, indo com minha natureza e não contra ela.",
        "Que os homens vejam, que conheçam um homem real que vive como deveria viver.",
        "Quem não pode obedecer a si mesmo será comandado.",
        "Quando temer algo, aprenda o máximo sobre isso. O conhecimento conquista o medo.",
        "Sempre achei que era eu contra o mundo, até que um dia percebi que é apenas eu contra mim.",
        "Um homem sem propósito se distrai com prazer.",
        "É difícil aceitar que nem todos vão entender – mas é por isso que não é para todos. É algo seu.",
        "Quanto maior a dificuldade, mais glória em superá-la.",
        "Nos deleitamos com a beleza da borboleta, mas raramente admitimos as mudanças pelas quais ela passou para alcançar essa beleza.",
        "Deixe-me cair se devo cair. Aquele em que estou me tornando vai me pegar.",
        "Por trás de um homem que perdoa tudo está um homem que conhece o peso dos seus próprios pecados.",
        "A tentativa de escapar da dor cria mais dor.",
        "O verdadeiro desenvolvimento não respeita o conforto.",
        "Até onde podemos discernir, o único propósito da existência humana é acender uma luz de significado na escuridão do mero existir.",
        "O dia em que você planta a semente não é o dia em que come o fruto.",
        "A verdade não muda porque é ou não acreditada pela maioria das pessoas.",
        "Um cavaleiro de armadura reluzente não tem valor comprovado. Dê-me um cavaleiro testado em batalha com armadura surrada de encontros com os desprezíveis da humanidade.",
        "A medida da inteligência é a capacidade de mudar.",
        "Não há colheita sem fome.",
        "É a própria mente que conduz a mente ao erro. Da mente, não seja descuidado.",
        "Você não pode sonhar e se transformar em um personagem; deve martelar e forjar um para si.",
        "Muito vai dar errado antes de tudo dar certo.",
        "Vivemos apenas agora. Todo o resto ou já passou ou é desconhecido.",
        "Você não será punido pela sua raiva – será punido por sua raiva.",
        "Você não aprende a nadar lendo sobre água.",
        "As escolhas mais difíceis exigem as vontades mais fortes.",
        "Acima de tudo, não minta para si mesmo.",
        "Seu corpo aguenta quase tudo; é a mente que você precisa convencer.",
        "A vida é do gênero primeira pessoa. Trate-a como tal.",
        "Bons líderes não dão desculpas. Em vez disso, encontram um jeito de fazer acontecer.",
        "Só porque demorou mais que os outros não significa que você fracassou.",
        "Quanto mais você se conhece, menos precisa da aprovação dos outros.",
        "Conhecer a si mesmo é o começo de toda sabedoria.",
        "Não é o tamanho do homem, mas o tamanho do seu coração que importa.",
        "É improvável que você mude de nível sem lágrimas.",
        "Você ara com o arado que tem.",
    ]
}
