// QuotesLang_nl.swift
// Spike AI — Bundled quote translations
import Foundation
enum QuotesLang_nl {
    static let quotes: [String] = [
        "Wat je consequent in je gedachten houdt, is precies wat je in het leven zult ervaren.",
        "We mikken boven het doel om het doel te raken.",
        "Het ergste wat ik kan zijn is hetzelfde als iedereen, daar heb ik een hekel aan.",
        "Alleen degenen die het risico nemen om te ver te gaan, kunnen ontdekken hoe ver men kan gaan.",
        "Spring en het net zal verschijnen.",
        "Een schip in de haven is veilig, maar daar zijn schepen niet voor gebouwd.",
        "Maak je geen zorgen over mislukkingen, maak je zorgen over de kansen die je mist als je het niet eens probeert.",
        "Wie durft jammerlijk te falen, kan groot succes behalen.",
        "De manier om te beginnen is te stoppen met praten en te beginnen met doen.",
        "We kunnen veel nederlagen tegenkomen, maar we mogen ons niet laten verslaan.",
        "De ware maat van een mens is hoe hij iemand behandelt die hem absoluut niets kan opleveren.",
        "Wees voorzichtig als je niet weet waar je naartoe gaat, want je komt er misschien niet.",
        "Je moet grote dingen van jezelf verwachten voordat je ze kunt doen.",
        "Laat je vroegere beslissingen nooit je toekomstige resultaat bepalen.",
        "Afkortingen veroorzaken lange vertragingen.",
        "Niemand kan je je doelen geven.. Dit is jouw reis.",
        "De wereld is wat je ervan denkt, dus denk er anders over en je wereld zal veranderen.",
        "De toekomst behoort toe aan degenen die zich er vandaag op voorbereiden.",
        "Geef niet op wat je het meest wilt voor wat je nu wilt.",
        "Vertel me niet hoe getalenteerd je bent, vertel me hoe hard je werkt.",
        "Hoe je denkt als je verliest, bepaalt hoe lang het duurt voordat je wint.",
        "Wanneer iemand besluit dat succes is bereikt, stopt de vooruitgang.",
        "Geen enkel probleem kan de aanval van aanhoudend denken weerstaan.",
        "Geluk is wanneer er een kans voorbijkomt en je er klaar voor bent.",
        "Het geheim van vooruitgang is beginnen.",
        "De beste tijd om een boom te planten was 20 jaar geleden. De op één na beste tijd is nu.",
        "Het is moeilijk om iemand te verslaan die nooit opgeeft.",
        "Schrijf het. Film het. Publiceer het. Haak het, bak het. Wat dan ook, maak!",
        "Wat je ook bent, wees een goede.",
        "Geluk is niet iets kant-en-klaars, het komt voort uit je eigen acties.",
        "Slimme mensen leren van alles en iedereen.",
        "Onmogelijk is slechts een mening.",
        "Je passie wacht tot je moed inhaalt.",
        "Mensen die zich afvragen of het glas halfleeg of halfvol is, missen het punt. Het glas is hervulbaar.",
        "Op een dag of dag één; jij beslist.",
        "Goede dingen komen naar degenen die wachten, maar alleen de dingen die achtergelaten zijn door degenen die hard werken.",
        "Alles komt naar degene die hard werkt terwijl hij wacht.",
        "Werk alsof er iemand 24 uur per dag werkt om het van je af te pakken.",
        "Niemand heeft ooit een verschil gemaakt door net als iedereen te zijn.",
        "Je zult slechte tijden hebben, maar het zal je altijd wakker schudden voor de goede dingen waar je geen aandacht aan besteedde.",
        "Wees een eersteklas versie van jezelf, niet een tweederangs versie van iemand anders.",
        "Leer van de fouten van anderen. Je kunt niet lang genoeg leven om ze allemaal zelf te maken.",
        "Als je moe bent, doe het dan moe.",
        "Een man is niet verslagen wanneer hij verliest, hij is verslagen wanneer hij opgeeft.",
        "De wereld wordt veranderd door je voorbeeld, niet door je mening.",
        "Het leven is als fietsen. Om je evenwicht te bewaren moet je blijven bewegen.",
        "Nadenken over het leven; geen hoeveelheid schuld kan het verleden veranderen, geen hoeveelheid angst kan de toekomst veranderen.",
        "Een negatieve geest zal je nooit een positief leven geven.",
        "Alles is moeilijk voordat het makkelijk is.",
        "Neem het risico, of verlies de kans.",
        "Stop nooit met leren, want het leven stopt nooit met onderwijzen.",
        "De man die niet leest heeft geen voordeel ten opzichte van de man die niet kan lezen.",
        "Iemand die nooit een fout heeft gemaakt, heeft nooit iets nieuws geprobeerd.",
        "De meest voorkomende manier waarop mensen hun macht opgeven is door te denken dat ze die niet hebben.",
        "Wees dankbaar voor wat je hebt; je zult er meer van krijgen. Concentreer je op wat je niet hebt en je zult nooit genoeg hebben.",
        "Het moeilijkste is de beslissing om te handelen, de rest is slechts doorzettingsvermogen.",
        "Veel van de mislukkingen in het leven zijn mensen die niet beseften hoe dicht ze bij succes waren toen ze opgaven.",
        "Het gaat er niet om of je neergeslagen wordt, maar of je weer opstaat.",
        "De pessimist ziet moeilijkheid in elke kans. De optimist ziet kansen in elke moeilijkheid.",
        "Onze grootste glorie is niet in het nooit vallen, maar in het opstaan elke keer dat we vallen.",
        "Laat je niet rondduwen door de angsten in je hoofd; laat je leiden door de dromen in je hart.",
        "Als je weet wat je wilt en het genoeg wilt, vind je een manier om het te krijgen.",
        "Begin met wat noodzakelijk is, doe dan wat mogelijk is, en plotseling doe je het onmogelijke.",
        "Zonder passie heb je geen energie, zonder energie heb je niets.",
        "Je hoeft niet geweldig te zijn om te beginnen, maar je moet beginnen om geweldig te worden.",
        "Kracht komt niet van fysieke capaciteit, het komt van een ontembare wil.",
        "Niemand is nutteloos in deze wereld die de lasten van een ander verlicht.",
        "Door het onmogelijke te vragen, verkrijgen we het mogelijke.",
        "Het is beter om een dag een leeuw te zijn dan een heel leven een schaap.",
        "Het leven is te belangrijk om serieus genomen te worden.",
        "Het begin is de helft van elke actie.",
        "Oneindig geduld brengt onmiddellijke resultaten.",
        "Bijna alle mensen sterven aan hun geneesmiddelen en niet aan hun ziekten.",
        "Ze kunnen het, omdat ze denken dat ze het kunnen.",
        "Verbeelding is belangrijker dan kennis.",
        "Volhardende mensen beginnen hun succes waar anderen eindigen in mislukking.",
        "Er zijn geen duidelijke paden. Alleen valkuilen, struikeldraden en duisternis.",
        "Een fout bewijst dat iemand lang genoeg gestopt is met praten om iets te doen.",
        "Wat het waard is om te doen, is het waard om goed te doen.",
        "Het machtigst is hij die zichzelf in zijn macht heeft.",
        "Een geleerde die de liefde voor comfort koestert, is het niet waard om als geleerde beschouwd te worden.",
        "Welvaart hangt meer af van het willen van wat je hebt dan van het hebben van wat je wilt.",
        "Elke dag komt met zijn eigen geschenken, maak de linten los.",
        "Succes is nooit permanent en mislukking is nooit definitief.",
        "Niets duurt voor eeuwig.. Zelfs je problemen niet.",
        "Hard werken garandeert geen succes, maar vergroot de kansen.",
        "Vrede kan niet met geweld gehandhaafd worden. Het kan alleen bereikt worden door begrip.",
        "Wie niet waagt, die niet wint.",
        "Zeg niet: als ik vrije tijd heb zal ik studeren; je hebt misschien geen vrije tijd.",
        "Wie het geloof verliest, verliest alles.",
        "Iemands eigen gedachte is zijn wereld. Wat een mens denkt, wordt hij.",
        "Avontuur zit niet buiten de mens, het zit erin.",
        "Het levensspel gaat niet zozeer om het vasthouden van een goede hand, maar om het goed spelen van een slechte hand.",
        "Zuur, zoet, bitter, scherp; alles moet geproefd worden.",
        "Laat het gevoel van eerdere mislukking nooit je volgende stap verslaan.",
        "Tenzij je ambitieus bent, maak je geen vooruitgang.",
        "De toekomst behoort toe aan degenen die durven.",
        "Feiten houden niet op te bestaan omdat ze genegeerd worden.",
        "We moeten nooit aannemen wat niet bewezen kan worden.",
        "Een luide stem kan niet concurreren met een heldere stem, zelfs als het een fluistering is.",
        "Gedraag je alsof je verwacht de eindzone te bereiken.",
        "Geluk is de natuurlijke bloem van plicht.",
        "\"Nee\" betekent simpelweg opnieuw beginnen op een hoger niveau.",
        "Enthousiasme beweegt de wereld.",
        "Een kampioen is iemand die opstaat wanneer hij niet kan.",
        "Obstakels zijn de prijs van grootheid.",
        "De vraag is niet wie mij gaat toestaan, maar wie mij gaat tegenhouden.",
        "Ik was er niet om te strijden, ik was er om te winnen.",
        "Stop met klagen, begin met werken.",
        "Uit moeilijkheden groeien wonderen.",
        "Ik ben niet bang, ik ben geboren om dit te doen.",
        "Buig nooit je hoofd. Houd het hoog.. Kijk de wereld recht in de ogen.",
        "Doe wat je moet doen totdat je kunt doen wat je wilt doen.",
        "Als je gisteren gevallen bent, sta vandaag op.",
        "Maak van elke dag je meesterwerk.",
        "Bloed, zweet en respect. De eerste twee geef je, de laatste verdien je.",
        "Wees zo goed dat ze je niet kunnen negeren.",
        "Laat de wereld zien hoeveel je vecht voor de winnaarskring.",
        "Als je niet je eigen levensplan ontwerpt, is de kans groot dat je in iemand anders zijn plan valt. Wat hebben zij voor je gepland? Niet veel.",
        "De enige persoon die je bestemd bent te worden, is de persoon die je besluit te zijn.",
        "Wacht niet om te slaan tot het ijzer heet is; maak het heet door te slaan.",
        "Ik kan niet geloven dat God ons op deze aarde heeft gezet om gewoon te zijn.",
        "Ik wil dat de wereld beter is omdat ik hier was.",
        "De gewoonte van volharding is de gewoonte van overwinning.",
        "Wees niet bang om het goede op te geven om voor het geweldige te gaan.",
        "Doe je plicht en een beetje meer, en de toekomst zorgt voor zichzelf.",
        "Het leven heeft een manier om iemands wil te testen.. Of er gebeurt helemaal niets, of alles gebeurt tegelijk.",
        "Een wijs man is altijd alleen te vinden. Een zwak man is altijd in een menigte te vinden.",
        "Durven is tijdelijk je evenwicht verliezen. Niet durven is jezelf verliezen.",
        "Angst verslaat meer mensen dan wat dan ook ter wereld.",
        "De krachtigste woorden in het universum zijn degene die je gebruikt om tegen jezelf te praten.",
        "Het enige dat naar een slapende man komt, zijn dromen.",
        "Als je jezelf niet overwint, word je door jezelf overwonnen.",
        "Een held is iemand die weet hoe hij nog een minuut langer moet volhouden.",
        "Ga zo ver als je kunt zien, en als je daar bent, kun je verder zien.",
        "Je ontdekt je plek in de wereld niet, je hakt hem eruit.",
        "Winnaars focussen op winnen. Verliezers focussen op winnaars.",
        "Mislukking zal me nooit inhalen als mijn vastberadenheid om te slagen sterk genoeg is.",
        "Wat makkelijk komt, duurt niet lang. Wat lang duurt, komt niet makkelijk.",
        "Om kritiek te vermijden: zeg niets, doe niets, wees niets.",
        "De man die meer doet dan waarvoor hij betaald wordt, zal spoedig betaald worden voor meer dan hij doet.",
        "Genialiteit begint grote werken, alleen arbeid voltooit ze.",
        "Zelfs als je op het juiste spoor zit, word je overreden als je blijft zitten.",
        "Als dingen niet mislukken, innoveer je niet genoeg.",
        "Je haalt het beste uit anderen als je het beste van jezelf geeft.",
        "Leiderschap is een actie, geen positie.",
        "Ons werk is de presentatie van onze capaciteiten.",
        "Al mijn problemen buigen voor mijn koppigheid.",
        "Draag je mislukking als een ereteken.",
        "We worden niet beperkt door onze vaardigheden, maar door onze visie.",
        "Als je moe bent, leer dan te rusten, niet te stoppen.",
        "Vallen is een ongeluk, blijven liggen is een keuze.",
        "Waag het niet om dit leven op te geven. Niet vanavond. Niet morgen. Nooit.",
        "Laat je nooit neerslaan door personen of gebeurtenissen.",
        "Sommige mensen dromen van succes terwijl anderen wakker worden en er hard voor werken.",
        "Vertrouwen komt van ervaring. Ervaringen komen van proberen en falen en opnieuw proberen - dit keer beter.",
        "De tijd die leidt tot meesterschap is afhankelijk van de intensiteit van onze focus.",
        "Succes komt alleen naar degenen die durven te proberen.",
        "Een belangrijke sleutel tot succes is zelfvertrouwen. Een belangrijke sleutel tot zelfvertrouwen is voorbereiding.",
        "Twijfel doodt meer dromen dan mislukking ooit zal doen.",
        "Overwinning is altijd mogelijk voor degene die weigert te stoppen met vechten.",
        "Je zult je leven nooit veranderen totdat je iets verandert dat je dagelijks doet.",
        "Om succesvol te zijn moet je focus zo intens zijn dat anderen denken dat je gek bent.",
        "Obstakels zijn die angstaanjagende dingen die je ziet wanneer je je ogen van je doel afwendt.",
        "Een kans vinden is een kwestie van geloven dat die er is.",
        "Doelen stellen is de eerste stap in het omzetten van het onzichtbare in het zichtbare.",
        "Als je niets riskeert, riskeer je alles.",
        "Als je je situatie niet kunt veranderen, verander dan je gedachten.",
        "Het maakt niet uit hoe moeilijk het verleden is, je kunt altijd opnieuw beginnen.",
        "Als je niets durft, dan is niets alles wat je hebt gewonnen wanneer de dag voorbij is.",
        "Heel vaak is een verandering van zelf meer nodig dan een verandering van omgeving.",
        "Angst is de grootste handicap en zal je verlammen.",
        "Wat gevaarlijk is, is niet evolueren.",
        "Hoe dan ook, ik zal een weg vinden of er een maken.",
        "De enige manier om iedereen de mond te snoeren is winnen.",
        "Laat goed genoeg nooit goed genoeg zijn.",
        "Op de lange termijn raken we alleen wat we mikken.",
        "Continue verbetering is beter dan uitgestelde perfectie.",
        "Als je het in je gedachten ziet, zul je het in je hand houden.",
        "Vandaag doe ik wat anderen niet willen, zodat ik morgen kan doen wat anderen niet kunnen.",
        "Uitmuntendheid is een kunst gewonnen door training en gewenning.",
        "Het komende jaar gaat voorbij, of je nu iets aan je leven doet of niet.",
        "Stop niet als je moe bent, stop als je klaar bent.",
        "Je bent maar één training verwijderd van een goed humeur.",
        "Doe wat juist is, niet wat makkelijk is, noch wat populair is.",
        "Niets groots kwam ooit makkelijk.",
        "Zonder strijd kan er geen vooruitgang zijn.",
        "Succesvolle mensen stellen betere vragen en als resultaat krijgen ze betere antwoorden.",
        "Ik heb geen speciale talenten, ik ben alleen hartstochtelijk nieuwsgierig.",
        "De beste les die ik in het leven heb geleerd, kwam van het slechtste gevoel dat ik in het leven heb gevoeld.",
        "Uitdagingen zijn wat het leven interessant maken. Ze overwinnen is wat het leven betekenisvol maakt.",
        "Leer gelukkig te zijn met de eindeloze probeer-, faal-, leer-benadering.",
        "Als je de deur sluit voor alle fouten, zal de waarheid buitengesloten worden.",
        "Vergeet de fout, onthoud de les.",
        "Als je alleen kunt doen wat je kunt doen, zul je nooit meer zijn dan je nu bent.",
        "Wie is wijs? Degene die van iedereen leert.",
        "Alleen ik kan mijn leven veranderen, niemand kan het voor mij doen.",
        "Doorzettingsvermogen is 19 keer falen en de 20e keer slagen.",
        "Ik schrijf mijn succes toe aan dit: ik heb nooit een excuus gegeven of geaccepteerd.",
        "Ik ben geen product van mijn omstandigheden. Ik ben een product van mijn beslissingen.",
        "Onze daden bepalen ons evenzeer als wij onze daden bepalen.",
        "Alleen de extreem onwetenden of extreem intelligenten kunnen verandering weerstaan.",
        "De man die vertrouwen in zichzelf heeft, wint het vertrouwen van anderen.",
        "Wat je zoekt, zoekt jou.",
        "Maak je geen zorgen over mislukking. Je hoeft maar één keer gelijk te hebben.",
        "Veiligheid is meestal bijgeloof. Het leven is een gedurfd avontuur of niets.",
        "We worden wat we het meest denken en dat is het vreemdste geheim.",
        "De manier om te beginnen is te stoppen met praten en te beginnen met doen.",
        "Maak van elke dag je meesterwerk.",
        "Hoe veel fouten je ook maakt of hoe langzaam je ook vordert, je bent nog steeds ver voor op iedereen die het niet probeert.",
        "Het is onze houding aan het begin van een moeilijke taak die, meer dan wat dan ook, het succesvolle resultaat beïnvloedt.",
        "De enige echte zekerheid die een mens in deze wereld heeft, is een reserve aan kennis, ervaring en vaardigheid.",
        "Wat je vandaag doet kan alle morgendagen van je leven veranderen.",
        "Je leven wordt niet beter door toeval, het wordt beter door verandering.",
        "Een droom wordt geen werkelijkheid door magie; het kost zweet, vastberadenheid en hard werken.",
        "Kennis is weten dat een tomaat een vrucht is. Wijsheid is het niet in een fruitsalade doen.",
        "Wat de situatie ook is, herinner jezelf eraan: \"Ik heb een keuze\".",
        "Beheers je geest of hij zal jou beheersen.",
        "Sommigen slagen omdat ze voorbestemd zijn, maar de meesten slagen omdat ze vastberaden zijn.",
        "Grote kansen worden niet met je ogen gezien, ze worden met je geest gezien.",
        "Wie niet moedig genoeg is om risico's te nemen, zal niets bereiken in het leven.",
        "Weten is niet genoeg, we moeten toepassen. Willen is niet genoeg, we moeten doen.",
        "Ambitie is de weg naar succes, doorzettingsvermogen is het voertuig waarmee je aankomt.",
        "De sleutel tot het leven is uitdagingen accepteren. Zodra iemand daarmee stopt, is hij dood.",
        "Toewijding is wat een belofte omzet in werkelijkheid.",
        "Zelfvertrouwen is de herinnering aan succes.",
        "Zonder zelfvertrouwen zijn we als baby's in een wieg.",
        "Durf te dromen, maar nog belangrijker, durf actie achter je dromen te zetten.",
        "Eerlijkheid is het eerste hoofdstuk in het boek der wijsheid.",
        "Uitmuntendheid is een continu proces en geen toeval.",
        "Hoop is in staat zijn om te zien dat er licht is ondanks alle duisternis.",
        "We moeten eindige teleurstelling accepteren, maar nooit oneindige hoop verliezen.",
        "Het ware teken van intelligentie is niet kennis, maar verbeelding.",
        "Word verslaafd aan constante en nooit eindigende zelfverbetering.",
        "Genialiteit is één procent inspiratie en negenennegentig procent transpiratie.",
        "Je kunt niet wachten op inspiratie, je moet erachteraan met een knuppel.",
        "Heb geduld. Alle dingen zijn moeilijk voordat ze makkelijk worden.",
        "De persoon die zegt dat het niet kan, mag de persoon die het doet niet onderbreken.",
        "Doorzettingsvermogen is het harde werk dat je doet nadat je moe bent van het harde werk dat je al deed.",
        "Een wijs man kan meer leren van een dwaze vraag dan een dwaas kan leren van een wijs antwoord.",
        "Door constante zelfdiscipline en zelfbeheersing kun je grootheid van karakter ontwikkelen.",
        "Emotionele zelfbeheersing is het resultaat van hard werken, geen aangeboren vaardigheid.",
        "Leren hoe je leert is de belangrijkste vaardigheid in het leven.",
        "Laat wat je niet kunt doen je niet weerhouden van wat je wel kunt doen.",
        "Je passeert altijd mislukking op weg naar succes.",
        "Niemand is perfect, daarom hebben potloden gummetjes.",
        "Laat de kansen je er nooit van weerhouden te doen waarvan je in je hart weet dat je ervoor bestemd was.",
        "Als je echt goed kijkt, heeft de meeste overnight successen een lange tijd gekost.",
        "Alles is mogelijk. Alles kan zijn.",
        "Niets is bijzonder moeilijk als je het opdeelt in kleine taken.",
        "Het geheim van succes is het gewone ongewoon goed doen.",
        "Doe alsof wat je doet een verschil maakt, want dat doet het.",
        "Wat je krijgt door je doelen te bereiken is niet zo belangrijk als wat je wordt door je doelen te bereiken.",
        "Het leven is als fietsen; om je evenwicht te bewaren moet je blijven bewegen.",
        "Beperk je \"altijds\" en \"nooits\".",
        "Je bent nooit te oud om een nieuw doel te stellen of een nieuwe droom te dromen.",
        "Je vindt het gelukkige leven niet, je maakt het.",
        "Het slechte nieuws is dat de tijd vliegt. Het goede nieuws is dat jij de piloot bent.",
        "Hou je gezicht altijd naar de zon en schaduwen zullen achter je vallen.",
        "Het verschil tussen het onmogelijke en het mogelijke ligt in iemands vastberadenheid.",
        "Gouden medailles zijn niet echt van goud gemaakt. Ze zijn gemaakt van zweet, vastberadenheid en een moeilijk te vinden legering genaamd lef.",
        "Onderschat niet de vastberadenheid van een stille man.",
        "Vertel me niet wat je gelooft. Ik observeer hoe je je gedraagt en trek mijn eigen conclusie.",
        "Ik haat gewoon verliezen en dat geeft je extra vastberadenheid om harder te werken.",
        "De vastberadenheid om te winnen is het betere deel van het winnen.",
        "Je kunt al het talent van de wereld hebben, maar zonder vastberadenheid kom je niet ver.",
        "Overwinning is het kind van voorbereiding en vastberadenheid.",
        "De jonge man kent de regels, maar de oude man kent de uitzonderingen.",
        "De pessimist klaagt over de wind, de optimist verwacht dat die verandert, de realist past de zeilen aan.",
        "Kennis heeft geen waarde tenzij je het in praktijk brengt.",
        "Ik heb liever spijt van de dingen die ik heb gedaan dan van de dingen die ik niet heb gedaan.",
        "Het vereist wijsheid om wijsheid te begrijpen. De muziek is niets als het publiek doof is.",
        "Het grootste gevaar voor de meesten van ons is niet dat ons doel te hoog is en we het missen, maar dat het te laag is en we het bereiken.",
        "In elke wandeling met de natuur ontvangt men veel meer dan men zoekt.",
        "Ik zal niet volgen waar het pad zou kunnen leiden, maar ik zal gaan waar geen pad is en een spoor achterlaten.",
        "De machtige eik van vandaag is slechts de noot van gisteren die standvastig bleef.",
        "Volledig eerlijk zijn tegen jezelf is een goede oefening.",
        "We kunnen niet worden wat we moeten zijn door te blijven wat we zijn.",
        "Bepaal je koers op de sterren, niet op de lichten van elk passerend schip.",
        "Als je niet weet waar je heen gaat, brengt elke weg je daar.",
        "Je zult altijd twee keuzes hebben: je toewijding versus je angst.",
        "Gezegend zijn zij die geven zonder te herinneren en nemen zonder te vergeten.",
        "Wat er gebeurt is niet zo belangrijk als hoe je reageert op wat er gebeurt.",
        "Begin met wat juist is in plaats van wat acceptabel is.",
        "De superieure man geeft zichzelf de schuld. De inferieure man geeft anderen de schuld.",
        "De kleinste daad is beter dan de grootste intenties.",
        "Het grootste obstakel voor ontdekking is niet onwetendheid, het is de illusie van kennis.",
        "Pas op voor valse kennis, het is gevaarlijker dan onwetendheid.",
        "De beste manier om de toekomst te voorspellen is hem uit te vinden.",
        "Winnen zonder risico is triomferen zonder glorie.",
        "Ons karakter is wat we doen als we denken dat niemand kijkt.",
        "Alles wat ons irriteert aan anderen kan ons leiden tot begrip van onszelf.",
        "De kunst van wijs zijn is de kunst van weten wat je moet negeren.",
        "Vertel het me en ik vergeet het. Leer het me en ik onthoud het. Betrek me erbij en ik leer het.",
        "Je hebt de hersenen in je hoofd. Je hebt de voeten in je schoenen. Je kunt jezelf in elke richting sturen die je kiest.",
        "In drie woorden kan ik samenvatten wat ik over het leven heb geleerd: het gaat door.",
        "Het leven is dingen uitproberen om te zien of ze werken.",
        "Succes komt meestal naar degenen die te druk zijn om ernaar te zoeken.",
        "Ik heb niet gefaald, ik heb alleen 10.000 manieren gevonden die niet werken.",
        "Ik heb mijn weg naar succes gefaald.",
        "Als je jezelf niet programmeert, programmeert het leven je.",
        "Ik heb geen tijd om medelijden met mezelf te hebben.. Ik heb geen tijd om te klagen.. Ik ga door.",
        "Als je niet bereid bent het gebruikelijke te riskeren, moet je genoegen nemen met het gewone.",
        "Succes is gedefinieerd als het vermogen om van mislukking naar mislukking te gaan zonder enthousiasme te verliezen.",
        "Al onze dromen kunnen werkelijkheid worden als we de moed hebben om ze na te jagen.",
        "Kansen ontstaan niet vanzelf, je creëert ze.",
        "Ik heb nooit gedroomd van succes, ik heb ervoor gewerkt.",
        "Laat wat je niet kunt doen niet in de weg staan van wat je wel kunt doen.",
        "Vandaag is de enige dag, gisteren is voorbij.",
        "Dingen werken het best voor degenen die het beste maken van hoe dingen uitpakken.",
        "Als je door de hel gaat, blijf dan lopen.",
        "Je ziet alleen de publieke glorie.. Nooit de privé-offers om ze te bereiken.",
        "Als je je tijd niet waardeert, zullen anderen dat ook niet doen.",
        "Niemand kan je een minderwaardig gevoel geven zonder jouw toestemming.",
        "Een succesvol man is iemand die een stevig fundament kan leggen met de stenen die anderen naar hem hebben gegooid.",
        "Wat ons als bittere beproevingen lijkt, zijn vaak vermomd als zegeningen.",
        "Niets ter wereld is gewoner dan onsuccesvolle mensen met talent.",
        "Probeer niet een persoon van succes te worden, maar probeer een persoon van waarde te worden.",
        "Als je het niet eenvoudig kunt uitleggen, begrijp je het niet goed genoeg.",
        "Je faalt nooit totdat je stopt met proberen.",
        "Kennis is weten wat je kunt doen. Wijsheid is weten wanneer je het niet moet doen.",
        "Het leven gaat niet over het vinden van jezelf. Het leven gaat over het creëren van jezelf.",
        "Het probleem is niet het probleem, het probleem is je houding ten opzichte van het probleem.",
        "Geen meesterwerk is ooit gemaakt door een luie kunstenaar.",
        "De weg naar succes en de weg naar mislukking zijn bijna precies hetzelfde.",
        "Het gaat niet om waar je naar kijkt, het gaat om wat je ziet.",
        "Moed is weerstand tegen angst - beheersing van angst, niet afwezigheid van angst.",
        "Ik merk dat hoe harder ik werk, hoe meer geluk ik schijn te hebben.",
        "De gloed van één warme gedachte is voor mij meer waard dan geld.",
        "Alle vooruitgang vindt plaats buiten de comfortzone.",
        "Denken moet je grootste kapitaal zijn, ongeacht de ups en downs die je in het leven tegenkomt.",
        "Succes is de som van kleine inspanningen, dag in dag uit herhaald.",
        "De succesvolle strijder is de gewone man met laserscgerpe focus.",
        "Succes bestaat niet uit het nooit maken van fouten, maar uit het nooit twee keer dezelfde maken.",
        "Laat de angst om te verliezen niet groter zijn dan de opwinding van het winnen.",
        "De eerste stap is wanneer je weigert gevangen te zijn door je omgeving.",
        "Er is geen file op de extra mijl.",
        "Wanneer je je aan de kant van de meerderheid bevindt, is het tijd om te pauzeren en na te denken.",
        "Succes is van jezelf houden, houden van wat je doet, en houden van hoe je het doet.",
        "Een doel is niet altijd bedoeld om bereikt te worden, het dient vaak eenvoudigweg als iets om op te richten.",
        "Het is beter te falen in originaliteit dan te slagen in imitatie.",
        "Motivatie is wat je op gang brengt, gewoonte is wat je gaande houdt.",
        "Je moet elke ochtend met vastberadenheid opstaan als je met voldoening naar bed wilt gaan.",
        "Je moet grote dingen van jezelf verwachten voordat je ze kunt doen.",
        "Echte moeilijkheden kunnen overwonnen worden, alleen de denkbeeldige zijn onoverwinnelijk.",
        "Mensen slagen zelden tenzij ze plezier hebben in wat ze doen.",
        "Het is tijdens onze donkerste momenten dat we ons moeten concentreren om het licht te zien.",
        "Mislukking is het kruid dat succes zijn smaak geeft.",
        "Geesten worden getemd en onderworpen door tegenspoed, maar grote geesten rijzen erboven uit.",
        "Je moet misschien meer dan eens een strijd voeren om hem te winnen.",
        "Wat zou je doen als je niet bang was?",
        "Goede dingen komen naar mensen die wachten, maar betere dingen komen naar degenen die eropuit gaan en ze halen.",
        "Doe altijd je uiterste best, zelfs als de kansen tegen je zijn.",
        "Wacht niet tot je gevoelens veranderen om actie te ondernemen, onderneem actie en je gevoelens zullen veranderen.",
        "Actie brengt misschien niet altijd geluk, maar er is geen geluk zonder actie.",
        "Perfectie is saai, beter worden is waar alle lol zit.",
        "Het is moeilijk om iemand te verslaan die nooit opgeeft.",
        "Het verschil tussen een struikelblok en een opstapje is hoe hoog je je voet optilt.",
        "Geef nooit op, want dat is precies de plek en het moment waarop het tij zal keren.",
        "Soms is niet krijgen wat je wilt een geweldige gelukstreffer.",
        "Ik kan de richting van de wind niet veranderen, maar ik kan mijn zeilen aanpassen om altijd mijn bestemming te bereiken.",
        "Ga vooruit. Stop niet, draal niet op je reis, maar streef naar het doel dat voor je is gesteld.",
        "Als je echt iets wilt, wacht er dan niet op, leer jezelf ongeduldig te zijn.",
        "Soms win je, soms leer je.",
        "Twee soorten mensen in deze wereld: degenen die dingen gedaan willen krijgen en degenen die geen fouten willen maken.",
        "Zorg ervoor dat je ergste vijand niet tussen je eigen twee oren leeft.",
        "Onthoud altijd dat je absoluut uniek bent, net als iedereen.",
        "Als je alles onder controle hebt, ga je niet snel genoeg.",
        "Een manier om het momentum gaande te houden is door steeds grotere doelen te hebben.",
        "Je hoeft niet de hele trap te zien, neem gewoon de eerste stap.",
        "Wat ons als bittere beproevingen lijkt, zijn vaak vermomd als zegeningen.",
        "Twee opties met betrekking tot toewijding: je bent erin of eruit - er is geen leven ertussenin.",
        "Als je iets wilt, werkt het hele universum samen om je te helpen het te bereiken.",
        "Geluk is niet iets kant-en-klaars, het komt voort uit je eigen acties.",
        "Wat je ook bent, wees een goede.",
        "Pijn is onvermijdelijk, lijden is optioneel.",
        "Talent raakt een doel dat niemand anders kan raken; genialiteit raakt een doel dat niemand anders kan zien.",
        "De geest is een eigen plek en kan op zichzelf een hemel van de hel maken, of een hel van de hemel.",
        "Ik haatte trainen, maar ik zei 'geef niet op' - lijd nu en leef de rest van je leven als kampioen.",
        "Het zijn niet de bergen die je moet beklimmen die je uitputten, het is het steentje in je schoen.",
        "Wat we denken, worden we.",
        "Iemand zit vandaag in de schaduw, omdat iemand lang geleden een boom heeft geplant.",
        "Een enkele zonnestraal is genoeg om veel schaduwen te verdrijven.",
        "Aan de geest die stil is, geeft het hele universum zich over.",
        "Met zelfdiscipline is bijna alles mogelijk.",
        "De beste uitweg is er altijd doorheen.",
        "Je grote kans is misschien precies waar je nu bent.",
        "Niets is meer waard dan deze dag.",
        "De enige reis is die naar binnen.",
        "Omstandigheden bepalen niet waar je heen kunt, ze bepalen slechts waar je begint.",
        "Geloof creëert het werkelijke feit.",
        "Wat de woestijn mooi maakt, is dat hij ergens een bron verbergt.",
        "Als de deuren van waarneming gezuiverd zouden worden, zou alles aan de mens verschijnen zoals het is, oneindig.",
        "Verander je gedachten en je verandert je wereld.",
        "De vogel wordt aangedreven door zijn eigen leven en motivatie.",
        "Geef licht en mensen zullen de weg vinden.",
        "De beste voorbereiding op morgen is vandaag je best doen.",
        "Ideeën vormen de loop van de geschiedenis.",
        "Niet aan één draad zijn alle juwelen van het leven geregen.",
        "Wat we innerlijk bereiken, zal de uiterlijke werkelijkheid veranderen.",
        "Je eigen vastberadenheid om te slagen is belangrijker dan wat dan ook.",
        "Je weet dat je op de weg naar succes bent als je je werk zou doen zonder ervoor betaald te worden.",
        "Je wordt wat je gelooft.",
        "Als je uitmuntendheid wilt bereiken, kun je daar vandaag geraken. Stop vanaf deze seconde met minder dan uitstekend werk leveren.",
        "Als je niet bereid bent het gebruikelijke te riskeren, moet je genoegen nemen met het gewone.",
        "Vóór alles is voorbereiding de sleutel tot succes.",
        "Ik heb door de jaren heen geleerd dat wanneer je besluit hebt genomen, de angst vermindert.",
        "Het leven bestaat uit heel veel afscheiden, aan elkaar gelast.",
        "Winnen is niet alles, maar willen winnen wel.",
        "Je kunt teleurgesteld zijn als je faalt, maar je bent gedoemd als je het niet probeert.",
        "Fouten zijn een feit van het leven, het is de reactie op de fout die telt.",
        "Als je de weg die je bewandelt niet leuk vindt, begin dan een nieuwe te plaveien.",
        "Daden spreken luider dan woorden, en dat geldt des te meer voor je kinderen.",
        "Een diamant is een stuk steenkool dat het goed deed onder druk.",
        "Moeilijke wegen leiden vaak naar mooie bestemmingen.",
        "Soms weet je nooit de waarde van een moment totdat het een herinnering wordt.",
        "Niets kan het licht dimmen dat van binnenuit schijnt.",
        "Om in het leven te slagen heb je drie dingen nodig: een wensbot, een ruggengraat en een grappig bot.",
        "Degenen die niet in magie geloven, zullen het nooit vinden.",
        "Ik besloot dat ik niemand kan betalen om de tijd terug te draaien, dus kan ik er maar beter overheen komen.",
        "Alles heeft een prijs, wat ben je bereid ervoor te betalen?",
        "Ik ben het meest gegroeid, niet door overwinningen, maar door tegenslagen.",
        "Ik heb het geluk dat welke angst ik ook vanbinnen heb, mijn verlangen om te winnen altijd sterker is.",
        "Je moet in jezelf geloven als niemand anders dat doet.",
        "Wees niet bang om te falen, dit is de weg naar succes.",
        "Ik hou van kritiek, het maakt je sterk.",
        "Ik weet dat ik altijd mijn best wil doen.",
        "Iedereen die ik heb ontmoet die succesvol is, is een werkverslaafde.",
        "Ik heb nooit met iemand anders geconcurreerd dan met mezelf.",
        "Geloof in jezelf en weten wie je bent, dat is de basis voor alles groots.",
        "Ik ben bang om niet te proberen.",
        "De manier om je verleden te redden is er niet voor weg te rennen, maar te proberen het te begrijpen en als fundament te gebruiken om te groeien.",
        "Veilig spelen levert je niets op in deze wereld.",
        "Een geweldige truc is een geweldige truc, maar op een nietsnut werkt het gewoon niet. Het draait om talent.",
        "Je evolueert, of je verdwijnt.",
        "Het zaad moet groeien, ongeacht het feit dat het in steen is geplant.",
        "Het maakt niet uit hoe moeilijk het wordt, steek je borst vooruit, houd je hoofd omhoog en handel het af.",
        "Doe altijd je best, laat de druk je niet in paniek brengen.",
        "Je weet nooit hoe of wanneer je een impact zult hebben, of hoe belangrijk jouw voorbeeld voor iemand anders kan zijn.",
        "Doe wat je moet doen, om te doen wat je wilt doen.",
        "Streef er niet naar om rond te komen, streef ernaar om een verschil te maken.",
        "Wees wie je bent in deze wereld, wat er ook gebeurt.",
        "Als je een vijand hebt, leer en ken dan je vijand, wees niet zomaar boos op hem of haar.",
        "Ik streef ernaar om te zijn als de grootste mensen die ooit hebben geleefd.",
        "Waarin ik uitblink is belachelijk, ziekelijk arbeidsethos. Weet je, terwijl de ander slaapt? Werk ik.",
        "Het leven wordt geleefd op de rand.",
        "Realistisch zijn is de meest bewandelde weg naar middelmatigheid.",
        "De eerste stap is dat je moet zeggen dat je het kunt.",
        "De wereld kan je niet vertellen wie je bent, je moet zelf uitzoeken wie je bent en er zijn, in voor- en tegenspoed.",
        "Je zult je mislukkingen moeten accepteren. Je zult ze moeten omarmen en uitzoeken hoe je ze kunt overwinnen.",
        "Mijn vader vertelde me: noem je prijs in het begin. Als het ooit duurder wordt dan de prijs die je noemt, ga er dan weg.",
        "Zou je geloven in wat je gelooft als je de enige was die het geloofde?",
        "Het kan me niet schelen wat mensen denken, want mensen denken niet.",
        "Ik was eigenlijk nooit ergens goed in, behalve het vermogen om te leren.",
        "Het beste gevoel ter wereld is de voordelen en beloningen van hard werken zien.",
        "Mijn doelen zijn zo hoog dat ik geen tijd heb om op welke manier dan ook te ontspannen.",
        "Het leven is te kort om je zorgen te maken over wat anderen over je zeggen.",
        "Achter elk succesvol persoon schuilt een groep haters.",
        "Je kunt iets van je leven maken, het hangt alleen af van je motivatie.",
        "Heb je vijanden? Goed, dat betekent dat je werkelijk ergens voor bent opgestaan.",
        "Alle succes begint met zelfdiscipline, het begint bij jou.",
        "Met drive en een beetje talent kun je bergen verzetten.",
        "Falen is geen optie, het is gewoon een stap.",
        "Succes is niet van de ene op de andere dag, het is wanneer je elke dag een beetje beter wordt dan de dag ervoor; het telt allemaal op.",
        "Als het leven je in moeilijke situaties plaatst, zeg niet 'waarom ik', zeg gewoon 'probeer maar'.",
        "Succes in wat dan ook komt altijd neer op dit: focus en inspanning. En we beheersen ze allebei.",
        "Ik hoorde eens een wijs man zeggen: er zijn geen perfecte mannen, alleen perfecte intenties.",
        "Heel vaak, weet je, stop je met lopen, want je zegt 'ik ben moe van het beklimmen van deze heuvel. Ik zal nooit de top bereiken' en je bent maar twee stappen van de top.",
        "Daag jezelf uit, het is de enige weg die naar groei leidt.",
        "Je kunt geen eer opeisen voor talent, je kunt alleen eer opeisen voor het gebruiken ervan.",
        "De beste manier om een verlies te garanderen is opgeven.",
        "Ik kon het ofwel gadeslaan of er deel van uitmaken.",
        "Als iets belangrijk genoeg is, doe je het, zelfs als de kansen niet in je voordeel zijn.",
        "Als je 's ochtends opstaat en denkt dat de toekomst beter zal zijn, is het een mooie dag, anders niet.",
        "Het is oké om al je eieren in één mandje te leggen, zolang je maar controleert wat er met dat mandje gebeurt.",
        "Als je alleen dingen doet waarvan je het antwoord al weet, gaat je bedrijf ten onder.",
        "Je moet bereid zijn verkeerd begrepen te worden als je wilt innoveren.",
        "Er is geen slecht moment om te innoveren.",
        "Kansen creëren betekent kijken waar anderen niet kijken.",
        "Zweet-aandelen zijn de meest waardevolle aandelen die er zijn.",
        "We leven in een maatschappij waar bijna altijd hard werken beloond wordt.",
        "Het universum is niet verplicht om logisch voor jou te zijn.",
        "Er is geen grotere opleiding dan die welke zelfgestuurd is.",
        "Niemand die nieuwsgierig is, is dom.",
        "Ik ken geen tijd in de menselijke geschiedenis waarin onwetendheid beter was dan kennis.",
        "Train jezelf om niets persoonlijk te nemen.",
        "Een man kan van zichzelf maken wat hij wil als hij daar echt in gelooft, hij moet klaar zijn voor hard werken en veel hartzeer.",
        "Wat ieder van ons moet beseffen is dat onze intentie er altijd doorheen komt.",
        "We kunnen niet negeren wat we werkelijk willen creëren.",
        "Alleen jij en jij alleen kunt je situatie veranderen.",
        "Wees dankbaar voor de moeilijke tijden, want zij hebben je gevormd.",
        "Om bij de top 1% te horen, moet je doen wat de 99% niet wil doen.",
        "Ik creëer mijn eigen pad, het was recht en smal. Ik bekeek het zo: je stond of in mijn weg of erbuiten.",
        "We hebben allemaal twijfels over onszelf. Je ontkent het niet, maar je geeft er ook niet aan toe. Je omarmt het.",
        "Veel leiders falen, omdat ze niet de moed hebben om die zenuw te raken of dat snaar te bespelen.",
        "Het moment dat je opgeeft is het moment dat je iemand anders laat winnen.",
        "Als je bang bent om te falen, ga je waarschijnlijk falen.",
        "Ik realiseerde me dat intimidatie niet echt bestond, als je in de juiste gemoedstoestand bent.",
        "Dit is het moment dat ik accepteer dat de meest uitdagende tijden altijd achter me en voor me zullen zijn.",
        "Niemand weet dat ze kampioen gaan worden - je moet hard werken om daar te komen.",
        "Mijn geloof is sterker dan jouw twijfel.",
        "Succes betekent tevreden zijn met wat je elke dag doet. Het is trots zijn op de betere persoon die je aan het worden bent.",
        "Als je succesvol wilt zijn, moet je bereid zijn elke connectie die je hebt te gebruiken.",
        "Talent is nooit genoeg. Op enkele uitzonderingen na zijn de beste spelers de hardste werkers.",
        "Geef niet op, wees vrienden met mensen die je helpen hard te werken.",
        "Vier gewoon het leven dat je had, niet het leven dat je had kunnen hebben.",
        "Ik groeide op in armoede, maar ik had geen arme dromen.",
        "Jij bent de enige die het verschil kan maken. Wat je droom ook is, ga ervoor.",
        "Het leven stopt niet omdat er iets met je gebeurt.",
        "In het leven zul je winnen en verliezen, wat nooit acceptabel is, is opgeven.",
        "Weten jullie hoe vaak ik in mijn leven ben afgewezen? Hoe vaak mij verteld is dat ik iets niet kon bereiken?",
        "Vaak merk ik dat mensen die met het meeste talent gezegend zijn, die houding nooit ontwikkelen. En degenen die niet op die manier gezegend zijn, zijn het meest competitief en hebben het grootste hart.",
        "Ik dacht dat ik nooit een kans zou krijgen om te spelen, totdat ik op een dag die kans kreeg, omdat ik voorbereid was en de kans zich aandiende.",
        "Ik hou gewoon van de competitie en ik hou ervan om te proberen te verbeteren.",
        "Te vaak in het leven gebeurt er iets en geven we anderen de schuld dat we niet gelukkig of tevreden zijn.",
        "Je leven wordt wat je ervan maakt.",
        "Ik ga niet van streek raken omdat iemand iets slechts over me heeft gezegd.",
        "Je kunt niet aan de zijlijn van het leven zitten.",
        "Mijn boodschap is eenvoudig: neem de controle over je leven.",
        "Als je een van de leiders van het team bent, zijn er geen vrije dagen.",
        "Vertrouw niet op anderen. Je zult geweldige steun krijgen van veel mensen. Maar niemand gaat je iets op een presenteerblaadje geven.",
        "Dingen corrigeren zichzelf niet; je moet eropuit gaan en hard werken om ze te corrigeren.",
        "Als je niet speelt om te winnen, speel dan helemaal niet.",
        "Als je niet in jezelf gelooft, waarom zou iemand anders dat dan doen.",
        "Soms worden de grootste uitdagingen in het leven de beste dingen die je overkomen.",
        "Ik hou gewoon van hard werken.",
        "De echte concurrenten zijn degenen die altijd spelen om te winnen.",
        "Jaag niet op het geld, jaag op de droom.",
        "Als je wilt vliegen, moet je de dingen opgeven die je naar beneden trekken.",
        "Ik wil niet dat je droomt, ik wil dat je doet.",
        "Iedereen die iemand wil worden, gaat zo hard werken als hij kan om die droom waar te maken.",
        "Ik heb nooit geprobeerd te verbergen dat het mijn bedoeling is om de beste te worden.",
        "Als je niet gelooft dat je de beste bent, zul je nooit bereiken waartoe je in staat bent.",
        "Vandaag zijn er kansen waarvan niemand weet of ze in de toekomst terugkomen.",
        "Talent zonder hard werken is niets.",
        "Het kan me niet schelen dat mensen op me haten, want het drijft me voort.",
        "Talent is niet alles. Je kunt het van de wieg af hebben, maar het is noodzakelijk om het vak te leren om de beste te zijn.",
        "Ik voel een eindeloze behoefte om te leren, te verbeteren, te evolueren - om tevreden te zijn met mezelf.",
        "Je liefde maakt me sterk. Je haat maakt me onstopbaar.",
        "Je kunt alles overwinnen als je maar genoeg van iets houdt.",
        "Ik ben succesvol omdat ik offers heb gebracht voor succes.",
        "Mijn ambitie is om altijd beter en beter te worden.",
        "Ik begin vroeg en ik blijf laat. Dag na dag, jaar na jaar, het kostte me 17 jaar en 114 dagen om een overnight succes te worden.",
        "De persoon die me tegenhield van geluk was ikzelf.",
        "De simpele daad van aandacht besteden kan je een heel eind brengen.",
        "Verwar de waarheid niet met de mening van de massa. Deze zijn bijna nooit ook maar vergelijkbaar.",
        "Er is een verschil tussen het pad kennen en het pad bewandelen.",
        "Ik heb geen tijd om de hele nacht op te zitten en me zorgen te maken over wat iemand die niet van me houdt over me te zeggen heeft.",
        "Je kunt niet aarzelen over wie je bent.",
        "Er is altijd stof om aan te werken, je bent er nooit.",
        "Ik wil zijn wat ik altijd al wilde zijn: dominant.",
        "Ik probeer gewoon de beste te zijn die ik kan zijn en hoop dat het de beste ooit is.",
        "Ik wil niet zo goed worden als ik ooit was, ik wil beter worden.",
        "Mijn geest is mijn grootste troef. Ik verwacht elk toernooi dat ik speel te winnen.",
        "De mannen die echt hun emoties beheersen, gaan winnen.",
        "Hoe goed je ook wordt, je kunt altijd beter worden, en dat is het opwindende deel.",
        "Om anderen te helpen moet je eerst leren hoe je jezelf kunt helpen.",
        "Niets dat de moeite waard is, komt ooit zonder hard werken.",
        "Ik zal geen mens mijn ziel laten verkleinen door mij hem te laten haten.",
        "Je kunt een man niet neerdrukken zonder bij hem te blijven.",
        "Karakter, niet omstandigheden, maakt de man.",
        "Er zijn twee manieren om je kracht uit te oefenen: de ene is neerdrukken, de andere is optillen.",
        "Ik heb veel vaker gefaald dan dat ik geslaagd ben.",
        "Ik doe vandaag wat mensen niet willen, zodat ik morgen kan bereiken wat mensen niet kunnen.",
        "Zelfs als je verliest, verlies de les niet.",
        "Het makkelijkste om te verkopen is de waarheid.",
        "Wacht niet op het perfecte moment, je zult eeuwig wachten. Maak altijd gebruik van de tijd die je krijgt en maak het perfect.",
        "Je kunt maar een beperkt aantal dingen geweldig doen, en je moet al het andere terzijde schuiven.",
        "Het leven is kwetsbaar. We hebben geen gegarandeerd morgen, dus geef alles wat je hebt.",
        "Ik ben niet bang om mezelf voor gek te zetten.",
        "Respect motiveert mij, niet succes.",
        "Als je over de heuvel heen bent, is dat wanneer je vaart krijgt.",
        "Uitmuntendheid is geen daad, het is een gewoonte.",
        "Je kunt geen 'A' krijgen als je bang bent voor een 'F'.",
        "Je maakt fouten om te leren hoe je bij de goede dingen komt.",
        "Een held is iemand die vrijwillig het onbekende in loopt.",
        "Er zijn miljoenen overlevenden. Maak er één miljoen en één van.",
        "Geef nooit op, want je weet nooit wat het tij de volgende dag brengt.",
        "Als het niet moeilijk was, zou iedereen het doen. Het moeilijke maakt het geweldig.",
        "Als je alleen maar veilige keuzes maakt, groei je niet.",
        "Ik doe graag iets waar ik bang voor ben.",
        "Het proces is het mooiste deel.",
        "Het is makkelijk om het oog te bedriegen, maar het is moeilijk om het hart te bedriegen.",
        "Word nooit te hoog, word nooit te laag. Neem het dag voor dag en blijf leren.",
        "Inspanning zal nooit in twijfel worden getrokken.",
        "Hoop niet dat iemand je een kans geeft: creëer er zelf een.",
        "Toen mensen me vertelden dat ik het nooit zou maken, luisterde ik naar de ene persoon die zei dat ik het kon: mezelf.",
        "Er is een reden dat ze het het najagen van je dromen noemen en niet het erachteraan wandelen.",
        "Om te hebben wat je echt wilt, moet je eerst zijn wie je echt bent.",
        "Laat het verleden je niet achtervolgen. Want wat je in het heden doet, kan je toekomst achtervolgen, wees wijs. Wat je nu of in de toekomst doet kan je verleden nooit maskeren, maar dat betekent niet dat je het verleden je moet laten controleren.",
        "Dat \"wat als\" is een wond die nooit heelt.",
        "Als het makkelijk was, zou het het niet waard zijn.",
        "Je verdient niets, je verdient het door ervoor te werken.",
        "Perfectie is niet interessant, ondanks de beproevingen bovenuit komen: dat is wat indruk op mij maakt.",
        "Doe niet mee aan de \"heb medelijden met mij\" Olympische Spelen; daar doen wij niet aan mee.",
        "Als je iets wilt, neem je het terrein dat erbij hoort, wat dat terrein ook is.",
        "Echte visie is wanneer je geest krachtiger is dan wat voor je ogen staat.",
        "Bepaalde gebeurtenissen zullen je vooruit helpen, bepaalde zullen het tegenovergestelde doen – zo lijkt het. Die tegenovergestelde zijn leermomenten die in de toekomst nuttig zullen blijken.",
        "Betaal de prijs om de baas te zijn of betaal de prijs die hoort bij spijt.",
        "De mening van anderen over jou hoeft niet jouw werkelijkheid te worden.",
        "Je krijgt niet wat je wenst, je krijgt waarvoor je werkt.",
        "Zelfdiscipline begint met het beheersen van je gedachten. Als je niet kunt beheersen wat je denkt, kun je niet beheersen wat je doet. Simpelweg, zelfdiscipline stelt je in staat om eerst te denken en daarna te handelen.",
        "Wat is nederlaag? Niets anders dan opleiding; niets anders dan de eerste stap naar iets beters.",
        "Het gaat niet om wat je overkomt, maar hoe je erop reageert.",
        "Beheers je woede. Als je woede hebt jegens anderen, beheersen zij jou.",
        "Je grootste uitdaging is om op te komen dagen wanneer je geest de beste excuses maakt.",
        "Je kunt ofwel de pijn van discipline ervaren, ofwel de pijn van spijt. De keuze is aan jou.",
        "Alles wat je fysiek, intellectueel en spiritueel verzwakt; verwerp het als vergif.",
        "Zweet meer in vredestijd, bloed minder in oorlogstijd.",
        "Met de moed om te beginnen en de discipline om vol te houden, wordt overwinning een kwestie van tijd.",
        "Een goede leider is iemand die iets meer dan zijn deel van de schuld op zich neemt, en iets minder dan zijn deel van de eer.",
        "Wees sterk, maar niet onbeleefd. Wees aardig, maar niet zwak. Wees moedig, maar pest niet. Wees bescheiden, maar niet verlegen. Wees trots, maar niet arrogant.",
        "Geduld is bitter, maar de vruchten zijn zoet.",
        "Geduld is niet passief, integendeel; het is actief. Het is geconcentreerde kracht.",
        "Er is niets onmogelijk voor wie het wil proberen.",
        "Intelligentie is niet het vermogen om informatie op te slaan, maar om te weten waar je die kunt vinden.",
        "Eerst is het een intentie. Dan een gedrag. Dan een gewoonte. Dan een praktijk. Dan een tweede natuur. Dan is het simpelweg wie je bent.",
        "Wat je ook wilt doen, doe het nu. Er zijn maar zoveel morgendagen.",
        "Mensen die zeggen dat het niet kan, moeten degenen die het doen niet onderbreken.",
        "Er is maar één hoek van het universum waarvan je zeker kunt zijn dat je die kunt verbeteren, en dat is je eigen zelf.",
        "De dwaas denkt dat hij wijs is, maar de wijze man weet dat hij een dwaas is.",
        "Pijn kan je veranderen, maar dat hoeft geen slechte verandering te zijn. Neem die pijn en verander het in wijsheid.",
        "Tijd is werkelijk het enige kapitaal dat een mens heeft, en het enige dat hij zich niet kan veroorloven te verliezen.",
        "Volg je eigen pad, wat mensen ook zeggen.",
        "Doe iets. Als het werkt, doe er meer van. Als het niet werkt, doe iets anders.",
        "Leren is het enige dat de geest nooit uitput, nooit vreest en nooit betreurt.",
        "Een winnaar is een dromer die nooit opgeeft.",
        "Als je niet vecht voor wat je wilt, huil dan niet om wat je hebt verloren.",
        "Als je eenmaal je fouten hebt geaccepteerd, kan niemand ze tegen je gebruiken.",
        "Als we eenmaal genoeg over het universum hebben geleerd, zullen we toegeven dat we nooit alles zullen weten.",
        "Zorgen maken is als een schuld betalen die je niet verschuldigd bent.",
        "Je kunt niemand iets leren, je kunt ze alleen laten beseffen dat de antwoorden al in hen zitten.",
        "De kracht van gedachten kan je ofwel ziekte of herstel bezorgen.",
        "Als je een wonder wilt zien, wees dan een wonder.",
        "Er zijn drie klassen mensen: degenen die zien, degenen die zien wanneer het hen getoond wordt, degenen die niet zien.",
        "Je grootste angsten worden gecreëerd door je verbeelding.",
        "Het grootste bedrog dat mensen ondergaan, komt voort uit hun eigen meningen.",
        "Als je alle mogelijkheden hebt uitgeput, onthoud dit: dat heb je niet.",
        "Houd van de hand die het lot je toebedeelt en speel hem als je eigen.",
        "Als twee mensen het over alles eens zijn, is een van hen overbodig.",
        "De grootste competitie is die welke je met jezelf hebt.",
        "Als we moe zijn, worden we aangevallen door ideeën die we lang geleden overwonnen hebben.",
        "Ik ben niet wat mij overkomen is. Ik ben wat ik kies te worden.",
        "De belangrijkste factor in overleving is noch intelligentie noch kracht, maar aanpassingsvermogen.",
        "Geloof en angst vragen allebei dat je gelooft in iets dat je niet kunt zien. Jij kiest.",
        "Door te klagen vertel je mensen hoe zwak je bent.",
        "Om te krijgen wat je liefhebt, moet je eerst geduldig zijn met wat je haat.",
        "Als alles tegen je lijkt te gaan, onthoud dan dat het vliegtuig opstijgt tegen de wind in, niet mee.",
        "Je zult lachen om je angsten als je ontdekt wie je werkelijk bent.",
        "Vrede wordt niet gevonden in een kalmere storm, het wordt gevonden in een betere boot.",
        "Je kunt de werkelijkheid negeren, maar je kunt de gevolgen van het negeren van die werkelijkheid niet negeren.",
        "Geen man is ongelukkiger dan hij die nooit tegenslag onder ogen ziet. Want hem wordt niet toegestaan zichzelf te bewijzen.",
        "Een goed plan dat nu krachtig wordt uitgevoerd, is beter dan een perfect plan dat volgende week wordt uitgevoerd.",
        "Studeren zonder na te denken is zinloos. Nadenken zonder te studeren is gevaarlijk.",
        "Angst is een reactie. Moed is een beslissing.",
        "Onafhankelijkheid is voor zeer weinigen; het is een voorrecht van de sterken.",
        "Het kost de helft van je leven voordat je ontdekt dat het leven een doe-het-zelf project is.",
        "Speel je rol met eer.",
        "Zorgen maken is misbruik van de verbeelding.",
        "De brug tussen kennis en vaardigheid is oefening. De brug tussen vaardigheid en meesterschap is tijd.",
        "Hoe meer ik leer, hoe meer ik besef hoeveel ik nog te leren heb.",
        "Als je niet verliest, kun je niet genieten van de overwinningen. Dus ik moet beide accepteren.",
        "We leren weinig van overwinning, veel van nederlaag.",
        "Wie respectvol spreekt maar zijn voorbereidingen vergroot, zal vooruitgang boeken. Wie oorlogszuchtig spreekt en haastig oprukt, zal terugdeinzen.",
        "Ons leven is wat onze gedachten ervan maken.",
        "Er is echt niets moeilijks, tenzij je besluit dat het moeilijk is. Anders is het gewoon het volgende dat je uitzoekt.",
        "Wat de situatie ook is, laat je emoties nooit je intelligentie overheersen.",
        "Beslis welk type persoon je wilt zijn en houd je daaraan, of je nu alleen bent of in gezelschap.",
        "Als er iets mis is, repareer het als je kunt. Maar train jezelf om je geen zorgen te maken. Zorgen maken repareert nooit iets.",
        "Het leven is niet een kwestie van goede kaarten vasthouden, maar van een slechte hand goed spelen.",
        "Het is een ruwe weg die naar de hoogten van grootheid leidt.",
        "De dag dat een mens superieur wordt aan genot, zal hij ook superieur zijn aan pijn.",
        "Leer voortdurend, er is altijd \"nog één ding\" te leren.",
        "We kunnen klagen dat rozenstruiken doornen hebben, of we kunnen ons verheugen dat doornstruiken rozen hebben.",
        "Wees geduldig en sterk; op een dag zal deze pijn je van nut zijn.",
        "Mislukking is succes in wording.",
        "Wie stopt met leren is oud, of hij nu twintig of tachtig is.",
        "Als je geregeerd wordt door de geest ben je een koning; als door het lichaam, een slaaf.",
        "Trots is niet het tegenovergestelde van schaamte, maar de bron ervan. Ware nederigheid is het enige tegengif voor schaamte.",
        "Wanneer je jezelf begint te verbeteren, is eenzaamheid de prijs die je betaalt.",
        "Je wordt niet beoordeeld op de hoogte waartoe je bent gestegen, maar op de diepte waaruit je bent geklommen.",
        "Een man is niet groot omdat hij niet heeft gefaald; een man is groot omdat mislukking hem niet heeft gestopt.",
        "Een man zonder visie is een man zonder toekomst. Een man zonder toekomst keert altijd terug naar zijn verleden.",
        "Liever falen met eer dan slagen door bedrog.",
        "Alle veldslagen worden eerst in de geest gewonnen of verloren.",
        "De emoties van de mens worden sneller geroerd dan zijn intelligentie.",
        "Wie koopt wat hij niet nodig heeft, steelt van zichzelf.",
        "Wie geduld kan hebben, kan krijgen wat hij wil.",
        "Het pad van de krijger duurt levenslang, en meesterschap is vaak simpelweg op het pad blijven.",
        "Vliegers stijgen het hoogst tegen de wind in, niet mee.",
        "Als mensen wisten hoe hard ik moest werken om mijn meesterschap te verwerven, zou het helemaal niet zo wonderbaarlijk lijken.",
        "Ga nooit slapen zonder een verzoek aan je onderbewustzijn.",
        "Verwelkom gebeurtenissen op welke manier ze ook plaatsvinden: dit is het pad naar vrede.",
        "Oefen zelfs wat onmogelijk lijkt.",
        "De man die twee konijnen najaagt, vangt er geen een.",
        "Je gaat het redden, maar het zal altijd voelen alsof dat niet zo is.",
        "Plan wat moeilijk is terwijl het makkelijk is, doe wat groot is terwijl het klein is.",
        "Volharding is niet genoeg. Men moet beslissen of men als lijder of als strijder wil volharden.",
        "Het niveau van scherpte en discipline dat nodig is om je naar de hoogten te brengen waar je van droomt, is eigenlijk simpel, het is alleen niet makkelijk.",
        "De grootste vijand wordt niet aan de buitenkant gevonden. Vernietiging komt vaak van binnenuit.",
        "Iedereen wist dat het onmogelijk was, totdat een dwaas die het niet wist langskwam en het deed.",
        "Je kunt een zwakke man niet sterk maken door een sterke man zwak te maken.",
        "Je hebt macht over je geest - niet over externe gebeurtenissen. Realiseer je dit, en je zult kracht vinden.",
        "Een diamant is gewoon een stuk steenkool dat trouw bleef aan zijn werk.",
        "Het grootste risico is geen enkel risico nemen.",
        "Als je het probleem correct definieert, heb je bijna de oplossing.",
        "Het verleden zit in je hoofd, de toekomst ligt in je handen.",
        "Het leven is vrij simpel. Je doet wat dingen. Het meeste mislukt. Sommige dingen werken. Je doet meer van wat werkt.",
        "Moge je plichtgevoel de sfeer van angst en de neiging om ambities uit te stellen overschaduwen.",
        "Alles wat je ooit hebt gewild bevindt zich aan de andere kant van angst.",
        "Discipline is kiezen tussen wat je nu wilt en wat je het meest wilt.",
        "Conformiteit is de laatste toevlucht van de fantasieloze.",
        "Een diamant is een stuk steenkool dat trouw bleef aan de klus.",
        "Er is geen grotere schade voor de mens dan die van verspilde tijd.",
        "Bederf niet wat je hebt door te verlangen naar wat je niet hebt; onthoud dat wat je nu hebt ooit behoorde tot de dingen waar je alleen maar op hoopte.",
        "Een man die meester is van geduld is meester van al het andere.",
        "Zet nooit passie voor principes, zelfs als je wint, verlies je.",
        "Sommige mensen willen dat het gebeurt, sommigen wensen dat het zou gebeuren, anderen maken het waar.",
        "We stijgen niet naar het niveau van onze verwachtingen, we dalen naar het niveau van onze training.",
        "Het is makkelijker om mannen te vinden die vrijwillig willen sterven, dan om degenen te vinden die bereid zijn pijn met geduld te verdragen.",
        "Je kunt niet verwachten op het podium te staan als je niet deelneemt aan de race.",
        "Degene die valt en opstaat is sterker dan degene die het nooit heeft geprobeerd.",
        "Slecht Nieuws: Je gaat niet bij iedereen 'passen'... Goed Nieuws: De 'Groten' doen dat nooit.",
        "Ik ben nooit getalenteerd geweest, ik ben gewoon goed in nooit opgeven.",
        "Geluk is niet de afwezigheid van problemen, het is het vermogen om ermee om te gaan.",
        "Als je doet wat makkelijk is, zal je leven moeilijk zijn.",
        "Je kunt niet teruggaan en het begin veranderen, maar je kunt beginnen waar je bent en het einde veranderen.",
        "Er wordt meer geleerd door wat men ziet dan door wat men verteld wordt.",
        "Degenen die nooit fouten maken, werken voor degenen onder ons die dat wel doen.",
        "Een nieuw idee moet niet beoordeeld worden op zijn directe resultaten.",
        "Je bent nooit klaar voor wat je moet doen. Je doet het gewoon. Dat maakt je klaar.",
        "Neem risico's: als je wint, zul je gelukkig zijn; als je verliest, zul je wijs zijn.",
        "Een volk dat zijn privileges boven zijn principes stelt, verliest spoedig beide.",
        "De snelste weg naar betekenis en succes: kies één ding en ga er volledig voor.",
        "Wees niet bang om opnieuw te beginnen. Deze keer begin je niet vanuit het niets. Je begint vanuit ervaring.",
        "Er is niets nobels in superieur zijn aan je medemens; ware adeldom is superieur zijn aan je vroegere zelf.",
        "Je zult het respect van iedereen verdienen als je begint met het respect voor jezelf te verdienen.",
        "Creëer een visie van wie je wilt zijn, en leef dan in dat beeld alsof het al waar is.",
        "De prijs van uitmuntendheid is discipline. De kosten van middelmatigheid zijn teleurstelling.",
        "Moeilijkheden versterken de geest, zoals arbeid het lichaam doet.",
        "Je kunt niet hopen vooruitgang te boeken op gebieden waar je geen actie hebt ondernomen.",
        "Geen enkele hoeveelheid angst maakt enig verschil voor iets dat gaat gebeuren.",
        "Toon mij een man van gemiddeld vermogen maar buitengewoon verlangen en ik toon u elke keer een winnaar.",
        "De snelste manier om te slagen is nu te beginnen en het gaandeweg uit te zoeken.",
        "Mensen beslissen niet hun toekomst, ze beslissen hun gewoonten en hun gewoonten beslissen hun toekomst.",
        "Leer je kinderen vroeg wat je laat hebt geleerd.",
        "Als je 100 uur per jaar besteedt aan een discipline (wat slechts 18 minuten per dag is) zul je beter zijn dan 95% van de wereld in die discipline.",
        "De taak is niet zozeer om te zien wat niemand nog heeft gezien; maar om te denken wat niemand nog heeft gedacht, over dat wat iedereen ziet.",
        "Als je geïrriteerd bent door elke wrijving, hoe zal je spiegel dan gepolijst worden?",
        "Angst is slechts zo diep als de geest toestaat.",
        "Moeilijkheid is wat het genie wakker maakt.",
        "Wat licht moet geven, moet het branden verduren.",
        "Ik heb geleerd dat succes niet zozeer gemeten moet worden aan de positie die men in het leven heeft bereikt, maar aan de obstakels die men heeft overwonnen terwijl men probeerde te slagen.",
        "Comfort is de ergste verslaving.",
        "Je wordt wat je je aandacht geeft.",
        "Omstandigheden maken de man niet, ze onthullen hem alleen aan zichzelf.",
        "Verspil geen tijd meer met discussiëren over wat een goed mens zou moeten zijn. Wees er een.",
        "Laat hij die de wereld wil bewegen, eerst zichzelf bewegen.",
        "Tussen prikkel en reactie is er een ruimte. In die ruimte ligt onze kracht om onze reactie te kiezen. In onze reactie liggen onze groei en onze vrijheid.",
        "Er is niets buiten jezelf dat je ooit in staat kan stellen beter, sterker, rijker, sneller of slimmer te worden. Alles is vanbinnen. Alles bestaat. Zoek niets buiten jezelf.",
        "Wees tolerant met anderen en streng met jezelf.",
        "Twee dingen definiëren je: je geduld wanneer je niets hebt en je houding wanneer je alles hebt.",
        "Je wordt niet zomaar wakker en bent de vlinder.",
        "Vasthoudendheid is het vermogen om vast te houden wanneer loslaten het meest aantrekkelijk lijkt.",
        "Er zijn risico's en kosten verbonden aan actie. Maar ze zijn veel minder dan de langetermijnrisico's van comfortabele inactiviteit.",
        "Om grote dingen te bereiken zijn twee dingen nodig: een plan, en niet helemaal genoeg tijd.",
        "Twijfel kan alleen worden weggenomen door actie.",
        "Als je acties anderen inspireren om meer te dromen, meer te leren, meer te doen en meer te worden, ben je een leider.",
        "Het gaat niet om een vlekkeloos dossier. Het gaat om leren van de vlekken op je dossier.",
        "Wees dapper genoeg om slecht te zijn in iets nieuws.",
        "Ga slimmer naar bed dan toen je wakker werd.",
        "Langzaam succes bouwt karakter, snel succes bouwt ego.",
        "Alleen omdat iemand struikelt en zijn pad verliest, betekent niet dat hij voor altijd verloren is.",
        "Maar we kunnen niet simpelweg voor altijd naar onze wonden zitten staren.",
        "En nu je niet perfect hoeft te zijn, kun je goed zijn.",
        "Succes komt van meedogenloze uitvoering van de basis.",
        "Het kost veel hard werken om iets eenvoudigs te maken.",
        "Iedereen denkt aan het veranderen van de wereld, maar niemand denkt aan het veranderen van zichzelf.",
        "Bekrompen mensen hebben hun kunst nodig op een lepeltje.",
        "Doe iets in plaats van tijd te doden. Want de tijd doodt jou.",
        "Laat elke beslissing in lijn zijn met je visie.",
        "Als je iets groters dan gemiddeld wilt doen, kun je niet zwichten voor de angst om een buitenstaander te zijn.",
        "Wat het meest telt is hoe goed je door het vuur loopt.",
        "Je bent één beslissing verwijderd van een compleet ander leven.",
        "Als je leeft voor morgen, loop je altijd een dag achter.",
        "Haal het meeste uit jezelf, want dat is alles wat er is.",
        "Ogen zijn nutteloos wanneer de geest blind is.",
        "Op de lange termijn raken mannen alleen wat ze mikken. Daarom, zelfs als ze meteen falen, kunnen ze maar beter op iets hoogs mikken.",
        "Wie een reden heeft om te leven, kan bijna elk hoe verdragen.",
        "Mannen kunnen in twee groepen worden verdeeld: een die vooruit gaat en iets bereikt, en een die erna komt en kritiek levert.",
        "Een slechte houding is als een lekke band. Je kunt nergens heen totdat je hem verwisselt.",
        "Geen vogel vliegt te hoog als hij vliegt met zijn eigen vleugels.",
        "Los het probleem op of verlaat het probleem. Leef niet met het probleem.",
        "Handel volgens je principes, niet je stemming.",
        "Zij die zich nergens aan committeren, worden afgeleid door alles.",
        "Wanneer we ernaar streven beter te worden dan we zijn, wordt alles om ons heen ook beter.",
        "Er is geen passie te vinden in het genoegen nemen met een leven dat minder is dan waartoe je in staat bent.",
        "Een creatief mens wordt gemotiveerd door het verlangen om te bereiken, niet door het verlangen om anderen te verslaan.",
        "Het leven is een lange voorbereiding op iets dat nooit gebeurt.",
        "Ik luister niet meer naar wat mensen zeggen, ik kijk alleen naar wat ze doen. Gedrag liegt nooit.",
        "Intelligente individuen leren van alles en iedereen; gemiddelde mensen van hun ervaringen. De dommen hebben al alle antwoorden.",
        "De eerste regel is om een onverstoorde geest te bewaren. De tweede is om dingen in het gezicht te kijken en ze te kennen voor wat ze zijn.",
        "Het is altijd een strijd om zwaarder gewicht te tillen.",
        "Een man die bang is voor lijden, lijdt al aan wat hij vreest.",
        "Als een man niet weet naar welke haven hij zeilt, is geen wind gunstig.",
        "Ik doe altijd dat wat ik niet kan, om te leren hoe het moet.",
        "Je bouwt op mislukking. Je gebruikt het als opstapje. Sluit de deur naar het verleden. Probeer de fouten niet te vergeten, maar blijf er niet bij stilstaan. Laat het niets van je energie, tijd of ruimte hebben.",
        "De inhoud van je karakter is jouw keuze. Dag na dag, wat je kiest, wat je denkt en wat je doet, is wie je wordt.",
        "De lafaards zijn nooit begonnen en de zwakken stierven onderweg.",
        "Wanneer je 's ochtends opstaat, bedenk dan wat een kostbaar voorrecht het is om in leven te zijn - om te ademen, te denken, te genieten, lief te hebben.",
        "Het geheim van succes is doelgerichtheid.",
        "Het enige dat gevaarlijker is dan onwetendheid is arrogantie.",
        "Wij zijn wat we herhaaldelijk doen. Uitmuntendheid is dan geen handeling, maar een gewoonte.",
        "Terwijl we wachten op het leven, gaat het leven voorbij.",
        "Succes is niets meer dan een paar simpele disciplines, elke dag toegepast.",
        "Hoe meer hij weet, hoe meer hij zich bewust zal zijn van zijn onwetendheid.",
        "Het obstakel voor actie bevordert actie. Wat in de weg staat, wordt de weg.",
        "Onze grootste zwakte ligt in het opgeven. De meest zekere manier om te slagen is altijd om het nog één keer te proberen.",
        "Een edelsteen kan niet gepolijst worden zonder wrijving, noch een mens vervolmaakt zonder beproevingen.",
        "Je waarde bestaat uit wat je bent en niet uit wat je hebt.",
        "De boosdoener is ongelukkiger dan de man die onrecht is aangedaan.",
        "Een van de waarste tests van integriteit is de botweg weigering om compromissen te sluiten.",
        "God geeft niets aan degenen die hun armen gekruist houden.",
        "Weten hoe je moet denken geeft je veel meer macht dan degenen die alleen weten wát ze moeten denken.",
        "Als je van plan bent iets minder te zijn dan waartoe je in staat bent, zul je waarschijnlijk alle dagen van je leven ongelukkig zijn.",
        "Er is niets beters dan tegenspoed. Elke nederlaag, elk hartzeer, elk verlies, bevat zijn eigen zaad, zijn eigen les over hoe je de volgende keer beter kunt presteren.",
        "Leer om van de haat te houden. Omarm het. Geniet ervan. Je hebt het verdiend. Iedereen heeft recht op zijn eigen mening en iedereen zou er een over jou moeten hebben. Haters zijn een goed probleem om te hebben. Niemand haat de goeden. Ze haten de groten.",
        "Accepteer dat je niet alles kunt beheersen. Accepteer de verantwoordelijkheid voor alles wat onder jouw controle valt. Accepteer dat interne en externe obstakels bestaan. Accepteer dat je uitgerust bent om ze allemaal te navigeren.",
        "Ervaring is de moeilijkste soort leraar. Het geeft je eerst de test en daarna de les.",
        "We rijpen met de schade, niet met de jaren.",
        "Als je depressief bent leef je in het verleden. Als je angstig bent leef je in de toekomst. Als je in vrede bent leef je in het heden.",
        "Als je denkt dat we de wereld niet kunnen veranderen, betekent het alleen dat jij niet een van degenen bent die dat zal doen.",
        "Misschien gaat het niet om een gelukkig einde. Misschien gaat het om het verhaal.",
        "Sommige mensen brengen vreugde waar ze ook gaan, en sommige mensen brengen vreugde wanneer ze gaan.",
        "Observeer voortdurend dat alle dingen plaatsvinden door verandering, en wen jezelf eraan te bedenken dat de natuur van het universum niets zozeer liefheeft als veranderen.",
        "Te goed zijn is geneigd oninteressant te zijn.",
        "Te vaak genieten we van het comfort van een mening zonder het ongemak van het denken.",
        "Studeren zonder na te denken is zinloos; nadenken zonder te studeren is gevaarlijk.",
        "Eén man met overtuiging zal honderd overweldigen die slechts meningen hebben.",
        "Dwazen vermenigvuldigen zich wanneer wijze mannen zwijgen.",
        "Wees bereid elk systeem te herzien, elke methode te schrappen, elke theorie te verlaten als het succes van de taak dat vereist.",
        "Anderen helpen om zich te ontwikkelen en te slagen in het leven is op zich een beloning en heeft alleen waarde wanneer er niets voor terug verwacht wordt.",
        "Nu is geen tijd om na te denken over wat je niet hebt. Denk na over wat je kunt doen met wat er is.",
        "Ik zou zeggen dat ik een werk in uitvoering ben, maar dat zou suggereren dat ik op een dag geen werk in uitvoering meer zal zijn.",
        "Geef niet op. Normaal is het de laatste sleutel aan de ring die de deur opent.",
        "Het leven is een komedie voor degenen die denken, een tragedie voor degenen die voelen.",
        "Tact is het vermogen om iemand naar de hel te sturen op zo'n manier dat hij uitkijkt naar de reis.",
        "Laat het onrecht dat een ander doet daar waar het onrecht is ontstaan.",
        "Verontrust jezelf niet door je hele leven in één keer voor te stellen. Denk niet altijd aan welke vormen van lijden en hoeveel je mogelijk zou kunnen overkomen.",
        "Elke keer dat ik denk dat ik alles weet, blijkt \"alles\" een beetje meer volume te hebben dan ik aannam.",
        "Het verschil tussen domheid en genialiteit is dat genialiteit zijn grenzen heeft.",
        "Het is beter een krijger te zijn in een tuin, dan een tuinman in een oorlog.",
        "Groot succes komt altijd met het risico van enorm falen.",
        "Succes komt voort uit nieuwsgierigheid, concentratie, doorzettingsvermogen en zelfkritiek.",
        "Het is het kenmerk van een geschoolde geest om een gedachte te kunnen overwegen zonder deze te accepteren.",
        "De mening van 10.000 mensen heeft geen waarde als geen van hen iets van het onderwerp afweet.",
        "Hoe meer we dingen buiten onze controle waarderen, hoe minder controle we hebben.",
        "Maak reizen. Probeer ze. Er is niets anders.",
        "Afkomst mag nooit een barrière voor succes zijn. Een bescheiden start in het leven kan meer hulp dan hinder zijn.",
        "Laat de tekortkomingen van een ander je niet tekort laten schieten.",
        "Onze afgunst duurt altijd langer dan het geluk van degenen die we benijden.",
        "Uit niets komt niets voort.",
        "Zwakke mensen nemen wraak. Sterke mensen vergeven. Intelligente mensen negeren.",
        "Ik beheers de wind niet; ik bestudeer hem alleen.",
        "Eer wint misschien geen macht, maar het wint respect. En respect verdient macht.",
        "Het uiteindelijke wapen is het brein, al het andere is aanvullend.",
        "Als je je neiging om makkelijk op te geven niet overwint, leidt je leven tot niets.",
        "Trainen is als de vloer vegen. Alleen omdat we het een keer hebben gedaan, betekent niet dat de vloer voor altijd schoon is.",
        "Bedenk dat wij het zijn die kwellen, wij die moeilijkheden voor onszelf creëren – dat wil zeggen, onze meningen. Wat betekent het bijvoorbeeld om beledigd te worden? Sta naast een rots en beledig die, wat heb je bereikt? Als iemand op een belediging reageert als een rots, wat heeft de belager dan gewonnen met zijn scheldwoorden?",
        "Bij afwezigheid van doel wordt het leven een eindeloze reis naar nergens.",
        "Alleen de doden hebben het einde van de oorlog gezien.",
        "Voorkomen is beter dan genezen.",
        "Niets dat met geweld wordt onderwezen, blijft in de ziel.",
        "Alles wat in je leven bestaat, bestaat vanwege twee dingen: iets wat je deed of iets wat je niet deed.",
        "Een man zonder ethiek is een wild beest losgelaten op deze wereld.",
        "Denken is moeilijk, daarom oordelen de meeste mensen.",
        "Je vindt geen wilskracht, je creëert het.",
        "Het woord gelukkig zou zijn betekenis verliezen als het niet in evenwicht werd gehouden door verdriet.",
        "Bid niet om een makkelijk leven. Bid om de kracht om een moeilijk leven te doorstaan.",
        "Je bent niet alles wat je zou kunnen zijn, en dat weet je.",
        "Vergeet niet te leven terwijl je bezig bent met overleven.",
        "Plannen zijn niets, planning is alles.",
        "Een man die het waagt één uur tijd te verspillen, heeft de waarde van het leven niet ontdekt.",
        "Je moet beslissen wie je bent en de wereld dwingen met jou om te gaan, niet met haar idee van jou.",
        "De kunst van het leven lijkt meer op worstelen dan op dansen, in zoverre dat het klaarstaat tegen het toevallige en het onvoorziene, en niet geneigd is te vallen.",
        "Naarmate ik ouder word, besteed ik minder aandacht aan wat mannen zeggen. Ik kijk gewoon naar wat ze doen.",
        "Ik zal mijn riem aanhalen voordat ik om hulp vraag.",
        "Niemand is gebouwd zoals jij, jij hebt jezelf ontworpen.",
        "Geen man heeft het recht een amateur te zijn in lichamelijke training. Het is een schande voor een man om oud te worden zonder de schoonheid en kracht te zien waartoe zijn lichaam in staat is.",
        "Hoe dichter een man bij een kalme geest komt, hoe dichter hij bij kracht is.",
        "Hier is een regel om in de toekomst te onthouden, wanneer iets je verleidt bitter te voelen: niet \"Dit is ongeluk\", maar \"Dit waardig te dragen is geluk.\"",
        "Als je ergens goed in bent, vertel je het aan iedereen. Als je ergens geweldig in bent, vertellen zij het jou.",
        "Eerst negeren ze je. Dan bespotten ze je. En dan vallen ze je aan en willen je verbranden. En dan bouwen ze monumenten voor je.",
        "Vrijheid betekent verantwoordelijkheid. Dat is waarom de meeste mensen er bang voor zijn.",
        "Als je de waarheid vertelt, hoef je niets te onthouden.",
        "Je tijd komt als je blijft doorgaan.",
        "Het is niet de dood die een mens zou moeten vrezen, maar hij zou moeten vrezen nooit te beginnen met leven.",
        "De procedures van vandaag zijn de resultaten van morgen. Als je verliefd kunt worden op de procedures van vandaag, zul je van de resultaten van morgen houden.",
        "Alle problemen van de mensheid komen voort uit het onvermogen van de mens om stil in een kamer alleen te zitten.",
        "Laat de toekomst je nooit verontrusten. Je zult haar ontmoeten, als het moet, met dezelfde wapens van de rede die je vandaag tegen het heden bewapenen.",
        "De mens rijpt door pijn, mislukking, afwijzing, verlies, disrespect en hartzeer, niet door leeftijd.",
        "Wij smeden de ketenen die we in het leven dragen.",
        "Om iets op hoog niveau te doen, moet het een obsessie zijn.",
        "Als je wilt verbeteren, wees dan tevreden om als dwaas en dom beschouwd te worden met betrekking tot uiterlijke zaken.",
        "Geweld is de laatste toevlucht van de incompetent.",
        "Angst is net als vuur, het kan nuttig zijn als je weet hoe je het moet gebruiken. Zo niet, dan word je verbrand.",
        "Om enorm te slagen, moet je bereid zijn enorm te falen. Als je beide niet kunt, heb je een probleem.",
        "We praten altijd over iemand die ons \"zonder reden\" niet mag, maar mensen zullen je ook \"zonder reden\" mogen. Dus hecht niet te veel waarde aan beide kanten.",
        "Lafaards sterven vele malen voor hun dood; de dappere proeft de dood slechts eenmaal.",
        "Niets is moeilijker, en daarom kostbaarder, dan in staat zijn te beslissen.",
        "Bewandel een enkel pad, word niet verwaand door overwinning noch gebroken door nederlaag, vergeet geen voorzichtigheid wanneer alles rustig is en word niet bang wanneer gevaar dreigt.",
        "De ziel wordt geverfd met de kleur van haar gedachten.",
        "Ik vraag niet om een lichtere last. Maar om bredere schouders.",
        "Onderhandel niet met jezelf. Geef jezelf instructies.",
        "Je kunt niet zowel een sterk karakter als een makkelijk leven wensen.",
        "Moed is niet de kracht hebben om door te gaan - het is doorgaan wanneer je geen kracht hebt.",
        "Het leven overkomt je niet, het gebeurt met jou erbij.",
        "Het is fataal om een oorlog in te gaan zonder de wil om hem te winnen.",
        "Je weet nooit hoe sterk je bent totdat sterk zijn je enige optie is.",
        "Je kunt niet iedereen tevreden stellen, soms moet je handelen en iedereen laten reageren.",
        "Er is geen kwestie van \"als\", de kwestie is alleen wanneer.. wanneer je vastberaden bent over de missie.",
        "Hoe lang ga je nog wachten voordat je het beste voor jezelf eist?",
        "De wereld belooft je comfort, maar je bent niet gemaakt voor comfort. Je bent gemaakt voor grootheid.",
        "Integriteit is geen snelle route, maar het is een zekere route.",
        "Wees je eigen grootste fan, je eigen grootste gelovige, en leg het op je rug en draag het gewicht.",
        "Zeg eerst tegen jezelf wat je wilt zijn; en doe dan wat je moet doen.",
        "Ik vrees de dag dat technologie onze menselijke interactie zal overtreffen. De wereld zal een generatie idioten hebben.",
        "Het maakt niet uit wat je draagt, maar hoe je het draagt.",
        "Verwerp je gevoel van onrecht en het onrecht zelf verdwijnt.",
        "Maak geen kleine plannen. Ze hebben geen magie om het bloed van mannen te roeren en zullen waarschijnlijk zelf niet gerealiseerd worden. Maak grote plannen; mik hoog in hoop en werk, onthoudend dat een nobel, logisch diagram eenmaal vastgelegd nooit zal sterven, maar lang nadat wij weg zijn een levend ding zal zijn, dat zichzelf met steeds groter aandringen doet gelden.",
        "Moeilijkheden bereiden gewone mensen vaak voor op een buitengewone bestemming.",
        "Als je dingen wilt veranderen, kun je niet iedereen tevreden stellen. Als je wel iedereen tevreden stelt, maak je niet genoeg vooruitgang.",
        "Onderhandel niet met jezelf, geef jezelf instructies.",
        "Succes is niet definitief, mislukking is niet fataal: het is de moed om door te gaan die telt.",
        "Als het niet juist is, doe het niet; als het niet waar is, zeg het niet.",
        "Zogenaamde genoegens, wanneer ze een bepaalde grens overschrijden, zijn slechts straffen.",
        "Als je niet opoffert voor wat je wilt, wordt wat je wilt het offer.",
        "Je grootste vijand is je ongecontroleerde geest.",
        "Leer te vechten zodat je nooit hoeft te vechten.",
        "Wanneer een persoon geen diep gevoel van betekenis kan vinden, leidt hij zichzelf af met plezier.",
        "Niets is permanent in deze slechte wereld, zelfs onze problemen niet.",
        "Laat ze maar verkeerd over je denken. Er is niets om aan hen te bewijzen.",
        "Als je wilt dat het heden anders is dan het verleden, bestudeer dan het verleden.",
        "Als je een gelukkig leven wilt leiden, bind het dan aan een doel, niet aan mensen of objecten.",
        "Er zijn geen geheimen, er is alleen informatie die je hebt ontdekt en informatie die je nog niet hebt ontdekt.",
        "Je hebt motivatie nodig om te handelen. Je hebt informatie nodig om te weten waarop je moet handelen. Je hebt nieuwsgierigheid nodig om informatie te verkrijgen die deze gemotiveerde handelingen goed zal sturen. Dus wees nieuwsgierig.",
        "Een winnaar is gewoon een verliezer die het nog één keer probeerde.",
        "We behandelen het lichaam streng zodat het niet ongehoorzaam is aan de geest.",
        "De gewilligen worden geleid door het lot, de onwilligen worden gesleept.",
        "De man die de dood vreest, zal nooit iets doen dat een man die leeft waardig is.",
        "Een commandant vertrouwt nooit zo op vrede dat hij nalaat zich op oorlog voor te bereiden.",
        "Wees niet bang. Je gaat het redden, maar het zal altijd voelen alsof dat niet zo is.",
        "Consistentie klinkt misschien als saai, maar wat dacht je dan dat geweldig zijn was? Geluk?",
        "Hou je gezicht altijd naar de zon en schaduwen zullen achter je vallen.",
        "De zwaarste straf voor het weigeren te regeren is geregeerd worden door iemand die minder is dan jijzelf.",
        "Graaf van binnen. Vanbinnen is de bron van het Goede; en het is altijd klaar om op te borrelen, als je maar graaft.",
        "Je bent wat je doet, niet wat je zegt dat je zult doen.",
        "Op je eigen manier verkeerd gaan is beter dan op andermans manier goed gaan.",
        "Een groot man is streng voor zichzelf, een zwak man is streng voor anderen.",
        "Van jezelf houden is het begin van een levenslange romance.",
        "Geef om wat andere mensen denken, en je zult altijd hun gevangene zijn.",
        "De mens maakt zich niet zozeer zorgen over echte problemen als over zijn ingebeelde angsten over echte problemen.",
        "De gelukkige man is tevreden met zijn huidige situatie, wat die ook is.",
        "De eerste en grootste overwinning is het overwinnen van jezelf.",
        "Om mezelf te beheersen moet ik eerst mezelf accepteren door mee te gaan met mijn natuur in plaats van ertegen.",
        "Laat mannen zien, laat hen weten: een echte man die leeft zoals hij bedoeld was te leven.",
        "Wie zichzelf niet kan gehoorzamen, zal gecommandeerd worden.",
        "Wanneer je iets vreest, leer er dan zoveel mogelijk over. Kennis overwint angst.",
        "Ik dacht altijd dat het ik tegen de wereld was en toen realiseerde ik me op een dag dat het gewoon ik tegen mij was.",
        "Een man die een doel mist, leidt zichzelf af met plezier.",
        "Het is moeilijk om te accepteren dat niet iedereen het \"snapt\".. maar daarom is het niet voor iedereen. Het is een \"jij\" ding.",
        "Hoe groter de moeilijkheid, hoe meer glorie in het overwinnen ervan.",
        "We zijn verrukt over de schoonheid van de vlinder, maar geven zelden toe welke veranderingen hij heeft doorgemaakt om die schoonheid te bereiken.",
        "Laat me vallen als ik moet vallen. Degene die ik aan het worden ben, zal me opvangen.",
        "Achter een man die alles vergeeft, staat een man die het gewicht van zijn eigen zonden kent.",
        "De poging om aan pijn te ontsnappen creëert meer pijn.",
        "Echte ontwikkeling respecteert comfort niet.",
        "Voor zover we kunnen onderscheiden, is het enige doel van het menselijk bestaan een licht van betekenis te ontsteken in de duisternis van louter bestaan.",
        "De dag dat je het zaad plant is niet de dag dat je de vrucht eet.",
        "De waarheid verandert niet omdat zij wel of niet geloofd wordt door de meerderheid van de mensen.",
        "Een ridder in een glanzend harnas heeft geen bewezen waarde. Geef mij een door strijd geteste ridder met bewerkt harnas van ontmoetingen met het slechtste van de mensheid.",
        "De maat van intelligentie is het vermogen om te veranderen.",
        "Er is geen oogst zonder honger.",
        "Het is de geest zelf die de geest op een dwaalspoor brengt. Wees niet onoplettend met de geest.",
        "Je kunt jezelf niet in een karakter dromen; je moet jezelf hameren en smeden.",
        "Er zal veel misgaan voordat alles goed gaat.",
        "We leven alleen nu. Al het andere is voorbij of onbekend.",
        "Je zult niet gestraft worden voor je woede, je zult gestraft worden door je woede.",
        "Je leert niet zwemmen door over water te lezen.",
        "De moeilijkste keuzes vereisen de sterkste wil.",
        "Boven alles, lieg niet tegen jezelf.",
        "Je lichaam kan bijna alles aan; het is de geest die je moet overtuigen.",
        "Het leven is van het eerste-persoongenre. Behandel het als zodanig.",
        "Goede leiders maken geen excuses. In plaats daarvan vinden ze een manier om het gedaan te krijgen.",
        "Alleen omdat het langer duurde dan bij anderen, betekent niet dat je hebt gefaald.",
        "Hoe meer je jezelf kent, hoe minder je de goedkeuring van anderen nodig hebt.",
        "Jezelf kennen is het begin van alle wijsheid.",
        "Het gaat niet om de grootte van een man, maar om de grootte van zijn hart.",
        "Het is onwaarschijnlijk dat je zonder tranen van niveau verandert.",
        "Je harkt met de ploeg die je hebt.",
    ]
}
