// QuotesLang_uz.swift
// Spike AI — Bundled quote translations
import Foundation
enum QuotesLang_uz {
    static let quotes: [String] = [
        "Ongingizda doimiy ravishda ushlab turgan narsa aynan hayotingizda boshdan kechiradigan narsadir.",
        "Biz nishonga tegish uchun nishondan yuqoriroqqa mo'ljallaymiz.",
        "Men uchun eng yomon narsa — boshqalar bilan bir xil bo'lish, men buni yomon ko'raman.",
        "Faqat juda uzoqqa borishga jur'at etganlar qanchalik uzoqqa borish mumkinligini bilishlari mumkin.",
        "Sakra, va to'r paydo bo'ladi.",
        "Bandargohda turgan kema xavfsiz, lekin kemalar buning uchun qurilmagan.",
        "Muvaffaqiyatsizliklar haqida emas, sinab ko'rmasangiz boy beradigan imkoniyatlar haqida tashvislaning.",
        "Dahshatli tarzda muvaffaqiyatsizlikka uchrashga jur'at etganlar buyuk yutuqlarga erishishlari mumkin.",
        "Boshlashning yo'li — gapirb yotishni to'xtatib, ish boshlashdir.",
        "Biz ko'p mag'lubiyatlarga duch kelishimiz mumkin, lekin yengilmasligimiz kerak.",
        "Insonning haqiqiy o'lchovi — unga mutlaqo foyda keltira olmaydigan odamga qanday munosabatda bo'lishidir.",
        "Qayerga ketayotganingizni bilmasangiz, ehtiyot bo'ling, chunki u yerga yetib bormasligingiz mumkin.",
        "Buyuk ishlarni qilishdan oldin o'zingizdan buyuk narsalarni kutishingiz kerak.",
        "O'tgan qarorlaringiz kelajak natijalaringizni belgilamasligiga yo'l qo'ymang.",
        "Yorliqlar uzoq kechikishlarga olib keladi.",
        "Hech kim sizga maqsadlaringizni bera olmaydi. Bu sizning sayohatingiz.",
        "Dunyo siz o'ylagan narsadir, shuning uchun boshqacha o'ylang va dunyoingiz o'zgaradi.",
        "Kelajak bugunga tayyorgarlik ko'rganlarga tegishli.",
        "Hozir xohlagan narsangiz uchun eng ko'p xohlagan narsangizdan voz kechmang.",
        "Menga qanchalik iqtidorli ekaningizni aytmang, qanchalik qattiq ishlashingizni ayting.",
        "Yutqazganingizda qanday fikr yuritishingiz g'alaba qozonguningizgacha qancha vaqt ketishini belgilaydi.",
        "Inson muvaffaqiyatga erishildi deb qaror qilganda, taraqqiyot to'xtaydi.",
        "Hech qanday muammo doimiy fikrlash hujumiga bardosh bera olmaydi.",
        "Omad — bu imkoniyat kelib, siz unga tayyor bo'lganingizda yuzaga keladi.",
        "Oldinga o'tishning siri — boshlashdir.",
        "Daraxt ekishning eng yaxshi vaqti 20 yil oldin edi. Ikkinchi eng yaxshi vaqt — hozir.",
        "Hech qachon taslim bo'lmaydigan odamni yengish qiyin.",
        "Yozing. Suring. Nashr qiling. To'qing, qovuring. Nima bo'lsa, yarating!",
        "Nima bo'lsangiz, yaxshi bo'ling.",
        "Baxt tayyor narsa emas, u sizning o'z harakatlaringizdan kelib chiqadi.",
        "Aqlli odamlar hamma narsadan va hamma kishidan o'rganadi.",
        "Imkonsiz — bu faqat fikr.",
        "Sizning ehtimosingiz jasoratingiz yetib kelishini kutmoqda.",
        "Stakan yarim bo'shmi yoki to'lami deb o'ylaydiganlar asosiy narsani tushunmaydi. Stakan qayta to'ldirilishi mumkin.",
        "Bir kun yoki birinchi kun; siz hal qilasiz.",
        "Kutganlarga narsalar kelishi mumkin, lekin faqat harakatlanganlar qoldirgan narsalar.",
        "Kutib turgan paytda harakatlanayotganga hamma narsa keladi.",
        "Xuddi kimdir uni sizdan tortib olish uchun kuniga 24 soat ishlayotgandek ishlang.",
        "Boshqalar bilan bir xil bo'lib, hech kim farq yaratmagan.",
        "Sizda yomon kunlar bo'ladi, lekin bu sizni e'tibor bermayotgan yaxshi narsalarga uyg'otadi.",
        "O'zingizning birinchi darajali versiyangiz bo'ling, boshqa birovning ikkinchi darajali versiyasi emas.",
        "Boshqalarning xatolaridan o'rganing. Hammasini o'zingiz qilishga umringiz yetmaydi.",
        "Agar charchagan bo'lsangiz, charchagan holda bajaring.",
        "Inson yengilganda emas, taslim bo'lganda tugaydi.",
        "Dunyo sizning fikringiz bilan emas, namunangiz bilan o'zgaradi.",
        "Hayot velosiped minishga o'xshaydi. Muvozanatni saqlash uchun harakatda bo'lishingiz kerak.",
        "Hayot haqida o'ylab: hech qanday aybdorlik hissi o'tmishni o'zgartira olmaydi, hech qanday xavotir kelajakni o'zgartira olmaydi.",
        "Salbiy fikr sizga ijobiy hayot bermaydi.",
        "Oson bo'lishidan oldin hamma narsa qiyin.",
        "Tavakkal qiling yoki imkoniyatni boy bering.",
        "Hech qachon o'rganishni to'xtatmang, chunki hayot hech qachon o'rgatishni to'xtatmaydi.",
        "O'qimaydigan odam o'qiy olmaydigan odamdan afzallikka ega emas.",
        "Hech qachon xato qilmagan odam hech qachon yangi narsa sinab ko'rmagan.",
        "Odamlar o'z kuchlarini yo'qotishning eng keng tarqalgan usuli — ularda kuch yo'q deb o'ylashdir.",
        "Borligingiz uchun minnatdor bo'ling; ko'proq narsaga ega bo'lasiz. Yo'q narsangizga e'tibor bersangiz, hech qachon yetarli bo'lmaydi.",
        "Eng qiyin narsa — harakat qilish qarori, qolgani faqat qat'iyatdir.",
        "Hayotdagi ko'plab muvaffaqiyatsizliklar — voz kechganlarida muvaffaqiyatga qanchalik yaqin ekanliklarini tushunmagan odamlar.",
        "Muhim narsa yiqilishingiz emas, o'rningizdan turishingizdir.",
        "Pessimist har bir imkoniyatda qiyinchilikni ko'radi. Optimist har bir qiyinchilikda imkoniyatni ko'radi.",
        "Bizning eng buyuk shon-sharafimiz hech qachon yiqilmasligimizda emas, balki har safar yiqilganimizda o'rnimizdan turishimizda.",
        "Ongingizlagi qo'rquvlar boshqarmasin; yuragingizagi orzular yetaklasin.",
        "Nimani xohlashingizni va uni qanchalik kuchli xohlashingizni bilsangiz, unga erishish yo'lini topasiz.",
        "Zaruriy narsadan boshlang, keyin imkon bo'lgan narsani qiling, va birdan siz imkonsiz narsani qilyapsiz.",
        "Ehtirossiz energiyangiz yo'q, energiyasiz hech narsangiz yo'q.",
        "Boshlash uchun buyuk bo'lishingiz shart emas, lekin buyuk bo'lish uchun boshlashingiz kerak.",
        "Kuch jismoniy qobiliyatdan emas, yengilmas irodadan keladi.",
        "Bu dunyoda boshqaning yukini yengillashtirgan hech kim behuda emas.",
        "Imkonsiz narsani so'rab, biz mumkin bo'lgan narsaga erishamiz.",
        "Butun umr qo'y bo'lgandan ko'ra, bir kun sher bo'lgan yaxshi.",
        "Hayot jiddiy qabul qilinish uchun juda muhim.",
        "Har bir ishning boshlanishi uning yarmidir.",
        "Cheksiz sabr tezkor natijalar beradi.",
        "Deyarli barcha odamlar kasalliklaridan emas, davolash usullaridan nobud bo'ladi.",
        "Ular qodir, chunki o'zlarini qodir deb hisoblaydilar.",
        "Tasavvur bilimdan muhimroqdir.",
        "Qat'iyatli odamlar muvaffaqiyatlarini boshqalar muvaffaqiyatsizlik bilan tugatgan joydan boshlaydi.",
        "Aniq yo'llar yo'q. Faqat tuzoqlar, to'siqlar va zulmat bor.",
        "Xato kimdir gapirshni to'xtatib, biror narsa qilganini isbotlaydi.",
        "Umuman qilishga arziydiganni yaxshi qilishga arziydi.",
        "Eng kuchli — o'zini o'z qo'lida ushlab turgan kishi.",
        "Qulaylikni sevadigan olim, olim deb hisoblashga loyiq emas.",
        "Farovonlik sizda boridan ko'proq ko'ra, sizda bor narsani xohlashga ko'proq bog'liq.",
        "Har bir kun o'z sovg'alarini olib keladi, lentalarni yeching.",
        "Muvaffaqiyat hech qachon abadiy emas va muvaffaqiyatsizlik hech qachon yakuniy emas.",
        "Hech narsa abadiy emas, hatto muammolaringiz ham.",
        "Qattiq mehnat muvaffaqiyatni kafolatlamaydi, lekin uning imkoniyatlarini oshiradi.",
        "Tinchlikni kuch bilan saqlash mumkin emas. Unga faqat tushunish orqali erishish mumkin.",
        "Tavakkal qilmagan omadsiz bo'ladi.",
        "Bo'sh vaqtim bo'lganda o'qiyman dema, bo'sh vaqting bo'lmasligi mumkin.",
        "Ishonchini yo'qotgan hamma narsani yo'qotadi.",
        "Insonning fikri uning dunyosidir. Inson nima o'ylasa, shunday bo'ladi.",
        "Sarguzasht odamning tashqarisida emas, ichkarisida.",
        "Hayot o'yini yaxshi qo'l ushlab turishda emas, balki yomon qo'lni yaxshi o'ynashda.",
        "Nordon, shirin, achchiq, o'tkir; hammasini tatib ko'rish kerak.",
        "O'tmishdagi muvaffaqiyatsizlik hissi keyingi qadamingizni yengmasin.",
        "Agar ambitsiyali bo'lmasangiz, taraqqiy qilmaysiz.",
        "Kelajak jur'at etganlarga tegishli.",
        "Faktlar e'tiborsiz qoldirilganligi uchun yo'q bo'lib ketmaydi.",
        "Biz hech qachon isbotlab bo'lmaydigan narsani taxmin qilmasligimiz kerak.",
        "Baland ovoz, hatto shivirlaganida ham, aniq ovoz bilan raqobatlasha olmaydi.",
        "Xuddi oxirgi hududga kirishni kutganday harakat qiling.",
        "Baxt — bu burchning tabiiy guli.",
        "\"Yo'q\" shunchaki bir daraja yuqoridan boshdan boshlashni anglatadi.",
        "Ishtiyoq dunyoni harakatga keltiradi.",
        "Chempion — bu tura olmaganida ham o'rnidan turadigan kishi.",
        "To'siqlar buyuklikning narxidir.",
        "Savol kimga ruxsat berishida emas, kim to'xtatishida.",
        "Men raqobat qilish uchun emas, g'alaba qozonish uchun kelgandim.",
        "Nolishshni to'xtat, mehnat qilishni boshla.",
        "Qiyinchiliklardan mo'jizalar paydo bo'ladi.",
        "Men qo'rqmayman, men buning uchun tug'ilganman.",
        "Hech qachon boshingizni egmang. Baland tuting. Dunyoga to'g'ri qarang.",
        "Xohlagan narsangizni qila olguncha, qilishingiz kerak bo'lgan narsani qiling.",
        "Kecha yiqilgan bo'lsangiz, bugun o'rningizdan turing.",
        "Har bir kuningizni shoh asaringizga aylantiring.",
        "Qon, ter va hurmat. Birinchi ikkitasini berasiz, oxirgisini topasiz.",
        "Shunchalik yaxshi bo'lingki, sizni e'tiborsiz qoldirib bo'lmasin.",
        "Dunyoga g'oliblar doirasi uchun qanchalik kurashasiz, ko'rsating.",
        "Agar o'z hayot rejangizni loyihalamagan bo'lsangiz, boshqa birovning rejasiga tushib qolish ehtimoli bor. Ular siz uchun nima rejalashtirgan? Ko'p narsa emas.",
        "Siz bo'lishga mo'ljallangan yagona shaxs — bo'lishga qaror qilgan shaxsingizdir.",
        "Temir qizig'uncha urishni kutmang; uni urib qizdiring.",
        "Men Xudo bizni oddiy bo'lish uchun yer yuziga qo'ygan deb ishona olmayman.",
        "Men dunyoning mening tufayli yaxshiroq bo'lishini istayman.",
        "Qat'iyat odati g'alaba odatidir.",
        "Yaxshidan voz kechib, buyukka intilishdan qo'rqmang.",
        "Burchingizni va undan biroz ko'proqni bajaring, kelajak o'zi g'amxo'rlik qiladi.",
        "Hayot insonning irodasini sinashning yo'lini topadi — yoki hech narsa sodir bo'lmaydi yoki hamma narsa birdaniga sodir bo'ladi.",
        "Dono odam har doim yolg'iz topiladi. Zaif odam har doim olomonda topiladi.",
        "Jur'at etish — bir lahzaga oyoq osti qilishdir. Jur'at etmaslik — o'zini yo'qotishdir.",
        "Qo'rquv dunyodagi boshqa har qanday narsadan ko'ra ko'proq odamlarni mag'lub etadi.",
        "Koinotdagi eng kuchli so'zlar o'zingiz bilan gaplashish uchun ishlatadigan so'zlardir.",
        "Uxlab yotgan odamga keladigan yagona narsa — orzulardir.",
        "Agar o'zingizni engmasangiz, o'zingizga engilasiz.",
        "Qahramon — yana bir daqiqa bardosh berishni biladigan kishi.",
        "Ko'rganingizcha boring, u yerga yetganingizda yanada uzoqroqni ko'ra olasiz.",
        "Siz o'z o'rningizni dunyoda topmasangiz, uni o'yib yasaysiz.",
        "G'oliblar g'alaba qozonishga e'tibor qaratadi. Mag'lublar g'oliblarga e'tibor qaratadi.",
        "Agar muvaffaqiyatga erishish azimim yetarlicha kuchli bo'lsa, muvaffaqiyatsizlik hech qachon meni engolmaydi.",
        "Oson keladigan narsa uzoq davom etmaydi. Uzoq davom etadigan narsa oson kelmaydi.",
        "Tanqiddan qochish uchun: hech narsa demang, hech narsa qilmang, hech narsa bo'lmang.",
        "Olganidan ko'proq ishlaydigan odam tez orada qilganidan ko'proq oladi.",
        "Dahiylik buyuk ishlarni boshlaydi, faqat mehnat ularni tugatadi.",
        "Hatto to'g'ri yo'lda bo'lsangiz ham, o'sha yerda o'tirsangiz bosib ketishadi.",
        "Agar narsalar muvaffaqiyatsiz bo'lmasa, siz yetarlicha innovatsiya qilmayapsiz.",
        "Boshqalarga eng yaxshisini berganingizda, boshqalardan eng yaxshisini olasiz.",
        "Yetakchilik — bu lavozim emas, harakatdir.",
        "Bizning ishimiz imkoniyatlarimizning namoyishidir.",
        "Barcha muammolarim qaysarligim oldida bosh egadi.",
        "Muvaffaqiyatsizligingizni faxr nishoni sifatida taqing.",
        "Biz qobiliyatlarimiz bilan emas, ko'rishimiz bilan cheklanganmiz.",
        "Agar charchagan bo'lsangiz, to'xtashni emas, dam olishni o'rganing.",
        "Yiqilish — tasodif, qolish — tanlov.",
        "Bu hayotdan voz kechishga jur'at etmang. Na bugun kecha, na ertaga, na hech qachon.",
        "Hech qachon o'zingizni shaxslarga yoki hodisalarga yenilishiga yo'l qo'ymang.",
        "Ba'zilar muvaffaqiyat haqida orzu qiladi, boshqalari uyg'onib, qattiq ishlaydi.",
        "Ishonch tajribadan keladi. Tajribalar sinash, muvaffaqiyatsizlik va qayta sinashdan keladi — bu safar yaxshiroq.",
        "Mahoratga olib boradigan vaqt diqqatimiz qanchalik kuchli ekanligiga bog'liq.",
        "Muvaffaqiyat faqat sinab ko'rishga jur'at etganlarga keladi.",
        "Muvaffaqiyatning muhim kalitlaridan biri o'ziga ishonchdir. O'ziga ishonchning muhim kaliti tayyorgarlikdir.",
        "Shubha muvaffaqiyatsizlikdan ko'ra ko'proq orzularni o'ldiradi.",
        "G'alaba kurashdan voz kechmaydigan inson uchun har doim mumkin.",
        "Har kuni qiladigan biror narsangizni o'zgartirmaguningizcha hayotingizni hech qachon o'zgartira olmaysiz.",
        "Muvaffaqiyatli bo'lish uchun diqqatingiz shunchalik kuchli bo'lishi kerakki, boshqalar sizni aqldan ozgan deb o'ylasin.",
        "To'siqlar — maqsadingizdan ko'z uzganingizda ko'radigan dahshatli narsalardir.",
        "Imkoniyatni topish — uning borligiga ishonish masalasidir.",
        "Maqsadlar qo'yish — ko'rinmasni ko'rinadigan qilishning birinchi qadamidir.",
        "Hech narsaga tavakkal qilmasangiz, hamma narsaga tavakkal qilasiz.",
        "Vaziyatingizni o'zgartira olmasangiz, fikringizni o'zgartiring.",
        "O'tmish qanchalik qiyin bo'lmasin, har doim qaytadan boshlash mumkin.",
        "Hech narsaga jur'at etmasangiz, kun tugaganda erishgan narsangiz hech narsa bo'ladi.",
        "Ko'pincha manzara o'zgartirish emas, o'zini o'zgartirish kerak bo'ladi.",
        "Qo'rquv eng katta nogironlik bo'lib, sizni falaj qiladi.",
        "Rivojlanmaslik xavfli.",
        "Qanday bo'lmasin, yo'l topaman yoki yarataman.",
        "Hammani jim qilishning yagona yo'li — g'alaba qozonish.",
        "Hech qachon yetarli bo'lgan narsani yetarli deb qabul qilmang.",
        "Uzoq muddatda biz faqat mo'ljallagan narsaga tegiramiz.",
        "Doimiy yaxshilanish kechiktirilgan mukammallikdan yaxshiroq.",
        "Agar miyangizda ko'rsangiz, qo'lingizda ushlaysiz.",
        "Bugun men boshqalar qilmaydigan narsani qilaman, shuning uchun ertaga boshqalar qila olmaydigan narsani qila olaman.",
        "Mukammallik mashq va odatlantirish orqali qo'lga kiritilgan san'atdir.",
        "Keyingi yil hayotingiz haqida biror narsa qilyapsizmi yoki yo'qmi, baribir o'tib ketadi.",
        "Charchaganda to'xtamang, ishni tugatganda to'xtang.",
        "Siz yaxshi kayfiyatdan faqat bitta mashq narisiz.",
        "To'g'ri narsani qiling, oson yoki mashhur narsani emas.",
        "Oson kelgan hech qanday buyuk narsa yo'q.",
        "Kurashsiz taraqqiyot bo'lmaydi.",
        "Muvaffaqiyatli odamlar yaxshiroq savollar beradi va natijada yaxshiroq javoblar oladi.",
        "Menda maxsus iqtidor yo'q, men faqat ehtirosli ravishda qiziquvchanman.",
        "Hayotda olgan eng yaxshi darsim hayotda his qilgan eng yomon hissiyotdan keldi.",
        "Qiyinchiliklar hayotni qiziqarli qiladi. Ularni yengish hayotni mazmunli qiladi.",
        "Cheksiz sinash, muvaffaqiyatsizlik, o'rganish yondashuvidan xursand bo'lishni o'rganing.",
        "Barcha xatolarga eshikni yopsangiz, haqiqat ham tashqarida qoladi.",
        "Xatoni unuting, darsni eslang.",
        "Agar faqat qila olganingizni qilsangiz, hech qachon hozirgi holatdan oshib ketolmaysiz.",
        "Dono kim? Hamma kishidan o'rganadigan kishi.",
        "Faqat men o'z hayotimni o'zgartira olaman, hech kim buni men uchun qila olmaydi.",
        "Sabr-toqat — bu 19 marta muvaffaqiyatsizlikka uchrash va 20-chi marta muvaffaqiyatga erishish.",
        "Men muvaffaqiyatimni shunga bog'layman: men hech qachon bahona bermadim va qabul qilmadim.",
        "Men sharoitlarimning mahsuli emasman. Men qarorlarimning mahsuliman.",
        "Ishlarimiz bizni xuddi biz ularni belgilagandek belgilaydi.",
        "Faqat juda johil yoki juda aqlli odamlar o'zgarishga qarshilik ko'rsata oladi.",
        "O'ziga ishongan odam boshqalarning ishonchini qozonadi.",
        "Siz izlayotgan narsa ham sizni izlayapti.",
        "Muvaffaqiyatsizlik haqida tashvishlanmang. Siz faqat bir marta to'g'ri bo'lishingiz kerak.",
        "Xavfsizlik asosan xurofotdir. Hayot yoki jasur sarguzasht yoki hech narsadir.",
        "Biz ko'p vaqt nima haqida o'ylasak, shunday bo'lamiz va bu eng g'alati sir.",
        "Boshlashning yo'li — gapirb yotishni to'xtatib, ish boshlashdir.",
        "Har bir kuningizni shoh asaringizga aylantiring.",
        "Qancha xato qilishingiz yoki qanchalik sekin rivojlanishingiz muhim emas, siz sinab ko'rmayotganlardan ancha oldinda turibsiz.",
        "Qiyin ishning boshidagi munosabatimiz, boshqa har qanday narsadan ko'ra, uning muvaffaqiyatli natijasiga ta'sir qiladi.",
        "Insonning bu dunyoda egallagan yagona haqiqiy xavfsizligi — bilim, tajriba va qobiliyat zahirasidir.",
        "Bugun qilgan ishingiz hayotingizning barcha ertalaringizni o'zgartirishi mumkin.",
        "Hayotingiz tasodif bilan emas, o'zgarish bilan yaxshilanadi.",
        "Orzu sehrgarlik orqali haqiqatga aylanmaydi, u ter, qat'iyat va qattiq mehnat talab qiladi.",
        "Bilim — pomidorning meva ekanligini bilish. Donolik — uni mevali salatga solmaslikdir.",
        "Vaziyat qanday bo'lishidan qat'i nazar, o'zingizga eslatib turing: \"Mening tanlovim bor\".",
        "Ongingizni boshqaring yoki u sizni boshqaradi.",
        "Ba'zilar muvaffaqiyatga taqdir tufayli erishadi, lekin ko'pchiligi qat'iyat tufayli erishadi.",
        "Buyuk imkoniyatlar ko'zlar bilan emas, aql bilan ko'riladi.",
        "Tavakkal qilish jasoratiga ega bo'lmagan kishi hayotda hech narsaga erisha olmaydi.",
        "Bilish yetarli emas, biz qo'llashimiz kerak. Xohlash yetarli emas, biz qilishimiz kerak.",
        "Ambitsiya muvaffaqiyatga yo'ldir, qat'iyat siz keladigan transport vositasidir.",
        "Hayotning kaliti — qiyinchiliklarni qabul qilishdir. Inson buni to'xtatganda, u o'ladi.",
        "Va'd berish va'dani haqiqatga aylantiradi.",
        "O'ziga ishonch — muvaffaqiyat xotirasi.",
        "O'ziga ishonchsiz biz beshikdagi chaqaloqlardek bo'lamiz.",
        "Orzu ko'rishga jur'at eting, lekin bundan ham muhimi — orzularingiz ortiga harakat qo'yishga jur'at eting.",
        "Halollik donolik kitobining birinchi bobidir.",
        "Mukammallik uzluksiz jarayon bo'lib, tasodif emas.",
        "Umid — bu barcha zulmatga qaramay nur borligini ko'ra bilishdir.",
        "Biz cheklangan umidsizlikni qabul qilishimiz kerak, lekin cheksiz umidni hech qachon yo'qotmasligimiz kerak.",
        "Aql-zakovatning haqiqiy belgisi bilim emas, tasavvurdir.",
        "Doimiy va to'xtovsiz o'z-o'zini takomillashtirishga mubtalo bo'ling.",
        "Dahiylik bir foiz ilhom va to'qson to'qqiz foiz terdir.",
        "Ilhomni kuta olmaysiz, uni tayoq bilan quvishingiz kerak.",
        "Sabr qiling. Barcha narsalar oson bo'lishdan oldin qiyin.",
        "Bu mumkin emas deydigankishi, uni qilayotgan kishini to'xtatmasligi kerak.",
        "Sabr-toqat — allaqachon qilgan qattiq ishingizdan charchagandan keyin qiladigan qattiq ishdir.",
        "Dono odam ahmoqona savoldan ko'p o'rganishi mumkin, ahmoq esa dono javobdan kam o'rganadi.",
        "Doimiy o'z-o'zini intizom va o'z-o'zini nazorat orqali siz xarakter buyukligini rivojlantira olasiz.",
        "Hissiy o'z-o'zini boshqarish qattiq mehnat natijasi, tug'ma mahorat emas.",
        "O'rganishni o'rganish hayotning eng muhim ko'nikmasi.",
        "Qila olmaydigan narsangiz qila oladigan narsangizga to'sqinlik qilishiga yo'l qo'ymang.",
        "Siz har doim muvaffaqiyat yo'lida muvaffaqiyatsizlikdan o'tasiz.",
        "Hech kim mukammal emas, shuning uchun qalamlarning o'chirgichlari bor.",
        "Hech qachon yuragingizda qilish uchun yaratilganligingizni bilgan narsangizdan ehtimollar to'sqinlik qilsin.",
        "Agar yaqindan qarasangiz, ko'pchilik bir kechada muvaffaqiyatlar uzoq vaqt talab qilgan.",
        "Hamma narsa mumkin. Hamma narsa bo'lishi mumkin.",
        "Hech narsa kichik ishlarga bo'lsangiz qiyin emas.",
        "Muvaffaqiyatning siri — oddiy narsalarni favqulodda yaxshi qilishdir.",
        "Qilgan ishingiz muhim deb harakat qiling, chunki u haqiqatan ham muhim.",
        "Maqsadlaringizga erishish orqali olgan narsangiz, maqsadlaringizga erishish orqali bo'lgan narsangiz kabi muhim emas.",
        "Hayot velosiped minishga o'xshaydi; muvozanatni saqlash uchun harakatda bo'lishingiz kerak.",
        "\"Har doim\" va \"hech qachon\" so'zlaringizni cheklang.",
        "Siz yangi maqsad qo'yish yoki yangi orzu ko'rish uchun hech qachon keksa emassiz.",
        "Siz baxtli hayotni topasiz emas, uni yaratasiz.",
        "Yomon xabar shuki, vaqt uchib ketadi. Yaxshi xabar shuki, uchuvchi sizsiz.",
        "Yuzingizni har doim quyoshga qarating va soyalar ortingizga tushadi.",
        "Imkonsiz va mumkin o'rtasidagi farq insonning qat'iyatidadir.",
        "Oltin medallar haqiqatan ham oltindan yasalmagan. Ular ter, qat'iyat va jasorat degan topish qiyin qotishmadan yasalgan.",
        "Sokin odamning qat'iyatini hech qachon kam baholamang.",
        "Nimaga ishonishingizni menga aytmang. Qanday harakat qilishingizni kuzataman va o'zim xulosa chiqaraman.",
        "Men yutqazishni yomon ko'raman va bu sizga qattiq ishlash uchun qo'shimcha azim beradi.",
        "G'alaba qozonish azmi g'alaba qozonishning eng yaxshi qismidir.",
        "Sizda dunyodagi barcha iqtidor bo'lishi mumkin, lekin qat'iyatsiz uzoqqa bora olmaysiz.",
        "G'alaba tayyorgarlik va qat'iyatning farzandidir.",
        "Yosh odam qoidalarni biladi, lekin keksa odam istisnolarni biladi.",
        "Pessimist shamoldan shikoyat qiladi, optimist uning o'zgarishini kutadi, realist yelkanlarni sozlaydi.",
        "Bilimning amaliyotga qo'yilmasa, hech qanday qiymati yo'q.",
        "Men qilgan narsalarimga afsuslanganim yaxshi, qilmaganlarimga afsuslanganidan ko'ra.",
        "Donolikni tushunish uchun donolik kerak. Tomoshabinlar kar bo'lsa musiqa hech narsa emas.",
        "Ko'pchiligimiz uchun katta xavf maqsadimizni juda yuqori qo'yib, erisha olmasligimizda emas, balki juda past qo'yib, erishishimizda.",
        "Tabiat bilan har bir sayrda inson izlaganidan ancha ko'proq oladi.",
        "Men yo'l olib boradigan joyga emas, yo'l bo'lmagan joyga boraman va iz qoldiraman.",
        "Bugungi ulkan eman daraxti kecha o'z joyini tashlamagan yong'oqdir.",
        "O'z-o'zi bilan to'liq halol bo'lish yaxshi mashq.",
        "Kim bo'lishimiz kerak bo'lsa, biz kimligimizda qolish orqali bo'la olmaymiz.",
        "Yo'lingizni har o'tayotgan kemaning chiroqlari bilan emas, yulduzlar bilan belgilang.",
        "Qayerga ketayotganingizni bilmasangiz, har qanday yo'l sizni u yerga olib boradi.",
        "Sizda har doim ikkita tanlov bo'ladi: sadoqatingiz va qo'rquvingiz.",
        "Eslamasdan beradigan va unutmasdan oladigan odamlar baxtli.",
        "Nima sodir bo'lganligi emas, nima sodir bo'lganiga qanday munosabat bildirishingiz muhim.",
        "Maqbul narsadan emas, to'g'ri narsadan boshlang.",
        "Buyuk odam o'zini ayblaydi. Kichik odam boshqalarni ayblaydi.",
        "Eng kichik ish eng buyuk niyatlardan yaxshiroq.",
        "Kashfiyotning eng katta to'sig'i johillik emas, bilim illuziyasidir.",
        "Yolg'on bilimdan ehtiyot bo'ling, u johillikdan xavfliroq.",
        "Kelajakni bashorat qilishning eng yaxshi usuli — uni ixtiro qilish.",
        "Xavfsiz g'alaba qozonish — shon-sharafhisz tantana qilish.",
        "Bizning xarakterimiz — hech kim qaramayapti deb o'ylaganimizda qilgan ishimiz.",
        "Boshqalar haqida bizni bezovta qilgan hamma narsa o'zimizni tushunishga olib kelishi mumkin.",
        "Dono bo'lish san'ati — nimaga e'tibor bermaslikni bilish san'ati.",
        "Menga ayt va men unutaman. Menga o'rgat va men eslayman. Meni jalb qil va men o'rganaman.",
        "Boshingizda miyangiz bor. Oyoqlaringizda poyabzalingiz bor. Siz o'zingizni xohlagan yo'nalishga boshqara olasiz.",
        "Hayot haqida o'rgangan hamma narsani uch so'z bilan ifodalay olaman: u davom etadi.",
        "Hayot — narsalarni ishlashini bilish uchun sinab ko'rishdir.",
        "Muvaffaqiyat odatda uni izlashga juda band bo'lganlarga keladi.",
        "Men muvaffaqiyatsizlikka uchramadim, men ishlamaydigan 10 000 usulni topdim.",
        "Men muvaffaqiyatsizlik orqali muvaffaqiyatga erishdim.",
        "Agar o'zingizni dasturlashtirmasangiz, hayot sizni dasturlaydi.",
        "Menda o'zimga achinishga vaqtim yo'q. Shikoyat qilishga vaqtim yo'q. Men oldinga boraman.",
        "Odatiy narsaga tavakkal qilishga tayyor bo'lmasangiz, oddiy narsaga rozi bo'lishingiz kerak.",
        "Muvaffaqiyat — bu ishtiyoqni yo'qotmasdan muvaffaqiyatsizlikdan muvaffaqiyatsizlikka o'tish qobiliyati deb ta'riflangan.",
        "Barcha orzularimiz, ularni amalga oshirish jasoratimiz bo'lsa, haqiqatga aylanishi mumkin.",
        "Imkoniyatlar o'z-o'zidan sodir bo'lmaydi, siz ularni yaratasiz.",
        "Men muvaffaqiyat haqida orzu qilmadim, men buning uchun ishladim.",
        "Qila olmaydigan narsangiz qila oladigan narsangizga xalaqit bermasin.",
        "Bugun yagona kun, kecha o'tib ketdi.",
        "Narsalar qanday ishlashidan eng yaxshi foyda oladigan odamlar uchun ishlar eng yaxshi ishlaydi.",
        "Agar do'zax ichidan o'tayotgan bo'lsangiz, davom eting.",
        "Siz faqat jamoatchilik shon-sharafini ko'rasiz, ularga erishish uchun qilingan shaxsiy qurbonliklarni emas.",
        "Agar o'z vaqtingizni qadrlamasangiz, boshqalar ham qadlamaydi.",
        "Sizning roziligingiz bo'lmasa, hech kim sizni o'zingizni kamsitgan his qila olmaydi.",
        "Muvaffaqiyatli odam boshqalar unga otgan g'ishtlardan mustahkam poydevor quradigan odamdir.",
        "Bizga achchiq sinovdek tuyulgan narsa ko'pincha niqobdagi ne'matdir.",
        "Dunyoda iqtidorli, lekin muvaffaqiyatsiz odamlardan ko'p narsa yo'q.",
        "Muvaffaqiyatli odam bo'lishga emas, qiymatli odam bo'lishga harakat qiling.",
        "Oddiy so'zlar bilan tushuntira olmasangiz, yetarlicha tushunamysiz.",
        "Sinashni to'xtatmaguningizcha, hech qachon muvaffaqiyatsiz bo'lmaysiz.",
        "Bilim — nima qila olishingizni bilishdir. Donolik — qachon qilmaslik kerakligini bilishdir.",
        "Hayot o'zingizni topish haqida emas. Hayot o'zingizni yaratish haqida.",
        "Muammo muammoning o'zi emas, muammo — muammo haqidagi munosabatingiz.",
        "Hech bir shoh asar dangasa rassom tomonidan yaratilmagan.",
        "Muvaffaqiyat yo'li va muvaffaqiyatsizlik yo'li deyarli bir xil.",
        "Muhim narsa nimaga qarayotganingiz emas, nimani ko'rayotganingiz.",
        "Jasorat — qo'rquvga qarshilik, qo'rquvni engish, qo'rquvning yo'qligi emas.",
        "Qanchalik ko'p ishlasam, omadim shunchalik ko'p bo'ladi.",
        "Bitta iliq fikrning nuri men uchun puldan qimmatroq.",
        "Barcha taraqqiyot konfort zonasidan tashqarida sodir bo'ladi.",
        "Fikrlash kapital boyligingiz bo'lishi kerak, hayotda qanday ko'tarilish va tushishlarni boshdan kechirishingizdan qat'i nazar.",
        "Muvaffaqiyat — har kuni takrorlanadigan kichik harakatlarning yig'indisi.",
        "Muvaffaqiyatli jangchi — lazer kabi diqqatga ega oddiy odam.",
        "Muvaffaqiyat hech qachon xato qilmaslikda emas, bir xil xatoni ikkinchi marta qilmaslikda.",
        "Yutqazish qo'rquvini g'alaba qozonish hayajonidan kattaroq bo'lishiga yo'l qo'ymang.",
        "Birinchi qadam — o'z muhitingizning asiri bo'lishdan bosh tortganingiz.",
        "Qo'shimcha mil bo'ylab tirbandlik yo'q.",
        "O'zingizni ko'pchilikning tomonida topsangiz, to'xtab o'ylash vaqti keldi.",
        "Muvaffaqiyat — o'zingizni, qilgan ishingizni va uni qanday qilishingizni yoqtirish.",
        "Maqsad har doim erishish uchun emas, ko'pincha mo'ljalga olish uchun xizmat qiladi.",
        "Originallikda muvaffaqiyatsiz bo'lish taqlid bilan muvaffaqiyatga erishishdan yaxshi.",
        "Motivatsiya sizni boshlaydi, odat sizni davom ettiradi.",
        "Agar qoniqish bilan yotmoqchi bo'lsangiz, har kuni ertalab qat'iyat bilan turish kerak.",
        "Buyuk ishlarni qilishdan oldin o'zingizdan buyuk narsalarni kutishingiz kerak.",
        "Haqiqiy qiyinchiliklarni yengish mumkin, faqat xayoliy qiyinchiliklar yengilmasdir.",
        "Odamlar qilayotgan ishlaridan zavq olmasa, kamdan-kam muvaffaqiyatga erishadi.",
        "Eng qorong'u lahzalarimizda biz nurni ko'rish uchun diqqatni jamlashimiz kerak.",
        "Muvaffaqiyatsizlik — muvaffaqiyatga lazzat beradigan ziravordir.",
        "Baxtsizlik oddiy aqllarni bostiradi, lekin buyuk aqllar undan ustun turadi.",
        "Siz g'alaba qozonish uchun jangni bir necha marta jang qilishingiz kerak bo'lishi mumkin.",
        "Agar qo'rqmasangiz nima qilar edingiz?",
        "Yaxshi narsalar kutadigan odamlarga keladi, lekin yaxshiroq narsalar chiqib, ularni olib keladiganlarga keladi.",
        "Har doim to'liq kuch sarflang, ehtimollar sizga qarshi bo'lsa ham.",
        "Hissiyotlaringiz o'zgarishini kutib harakat qilmang, harakat qiling va hissiyotlaringiz o'zgaradi.",
        "Harakat har doim baxt keltirmasligi mumkin, lekin harakatsiz baxt yo'q.",
        "Mukammallik zerikarli, yaxshilanish — barcha qiziqarli narsa shu yerda.",
        "Hech qachon taslim bo'lmaydigan odamni yengish qiyin.",
        "To'siq va zinpoya o'rtasidagi farq — oyog'ingizni qanchalik baland ko'tarishingiz.",
        "Hech qachon taslim bo'lmang, chunki aynan shu joy va vaqt oqim yo'nalishi o'zgaradi.",
        "Ba'zan xohlagan narsangizni olmaslik ajoyib omad zarbasidir.",
        "Men shamol yo'nalishini o'zgartira olmayman, lekin manzilimga har doim yetib borish uchun yelkanlarimni sozlay olaman.",
        "Oldinga boring. To'xtamang, sayohatingizda sekinlamang, balki oldingizga qo'yilgan maqsadga intiling.",
        "Agar chindan ham biror narsa istasangiz, kutmang, o'zingizni sabrsiz bo'lishga o'rgating.",
        "Ba'zan g'alaba qozonasiz, ba'zan o'rganasiz.",
        "Bu dunyoda ikki xil odam bor: ishlarni bajarmoqchi bo'lganlar va xato qilishni istamaydiganlar.",
        "Eng yomon dushmaningiz ikki qulog'ingiz orasida yashamasligiga ishonch hosil qiling.",
        "Har doim esda tuting — siz mutlaqo noyob ekansiz, xuddi boshqa hamma kabi.",
        "Agar hamma narsani nazorat ostida tutgan bo'lsangiz, yetarlicha tez harakat qilmayapsiz.",
        "Tezlikni saqlashning bir yo'li — doimiy ravishda kattaroq maqsadlarga ega bo'lish.",
        "Butun zinapoyani ko'rishingiz shart emas, faqat birinchi qadamni qo'ying.",
        "Bizga achchiq sinovdek tuyulgan narsa ko'pincha niqobdagi ne'matdir.",
        "Sadoqat haqida ikkita variant: siz yoki ichida yoki tashqaridasiz — o'rtasida hayot degan narsa yo'q.",
        "Biror narsani xohlasangiz, butun koinot sizga unga erishishga yordam beradi.",
        "Baxt tayyor narsa emas, u sizning o'z harakatlaringizdan kelib chiqadi.",
        "Nima bo'lsangiz, yaxshi bo'ling.",
        "Og'riq muqarrar, azob ixtiyoriy.",
        "Iqtidor hech kim ura olmaydigan nishonga uradi; dahiylik hech kim ko'ra olmaydigan nishonga uradi.",
        "Aql o'z joyida bo'lib, jannatdan do'zax yoki do'zaxdan jannat yarata oladi.",
        "Men mashqni yomon ko'rardim, lekin 'taslim bo'lma' dedim — hozir azob chek va qolgan umringni chempion sifatida yasha.",
        "Sizni charchatadigan oldindagi tog'lar emas, poyabzalingizdagi tosh.",
        "Biz nima o'ylasak, shunday bo'lamiz.",
        "Kimdir bugun soyada o'tiribdi, chunki kimdir ancha oldin daraxt ekkan.",
        "Bitta quyosh nuri ko'p soyalarni haydash uchun yetarli.",
        "Sokin aqlga butun koinot bo'ysunadi.",
        "O'z-o'zini intizom bilan deyarli hamma narsa mumkin.",
        "Eng yaxshi chiqish yo'li har doim ichkaridan o'tish.",
        "Sizning buyuk imkoniyatingiz hozir turgan joyingizda bo'lishi mumkin.",
        "Bu kundan qimmatroq hech narsa yo'q.",
        "Yagona sayohat — ichkaridagi sayohat.",
        "Sharoitlar qayerga borish mumkinligini emas, faqat qayerdan boshlashingizni belgilaydi.",
        "E'tiqod haqiqiy faktni yaratadi.",
        "Cho'lni go'zal qiladigan narsa shuki, u qayerdadir quduqni yashiradi.",
        "Agar idrokning eshiklari tozalansa, hamma narsa insonga bo'lganicha, cheksiz ko'rinadi.",
        "Fikrlaringizni o'zgartiring va dunyoingizni o'zgartiring.",
        "Qush o'z hayoti va motivatsiyasi bilan uchadi.",
        "Nur bering va odamlar yo'l topadilar.",
        "Ertangi kunga eng yaxshi tayyorgarlik — bugun eng yaxshi ishingizni qilish.",
        "G'oyalar tarix yo'nalishini belgilaydi.",
        "Hayotning barcha javohirlari bitta ipga tizilmagan.",
        "Ichki dunyomizda erishgan narsalarimiz tashqi haqiqatni o'zgartiradi.",
        "Muvaffaqiyatga erishishga bo'lgan o'z qaroringiz boshqa har qanday narsadan muhimroq.",
        "Agar ish haqi olmasangiz ham ishingizni qilgan bo'lsangiz, muvaffaqiyat yo'lida ekanlgingizni bilasiz.",
        "Siz nimaga ishonsangiz, shunday bo'lasiz.",
        "Agar mukammallikka erishmoqchi bo'lsangiz, bugundan boshlab mukammallikdan past ish qilishni to'xtating.",
        "Agar odatiy narsaga tavakkal qilishga tayyor bo'lmasangiz, oddiy narsaga rozi bo'lishingiz kerak.",
        "Hamma narsadan oldin, tayyorgarlik muvaffaqiyatning kalitidir.",
        "Yillar davomida o'rgandim — inson qaror qilganda, qo'rquv kamayadi.",
        "Hayot juda ko'p ajralishlardan iborat, birga payvandlangan.",
        "G'alaba qozonish hamma narsa emas, lekin g'alaba qozonishni xohlash — shunday.",
        "Muvaffaqiyatsiz bo'lsangiz hafsalangiz pir bo'lishi mumkin, lekin sinab ko'rmasangiz halok bo'lasiz.",
        "Xatolar hayotning bir qismidir, muhim narsa xatoga javob berishdir.",
        "Yurgan yo'lingiz yoqmasa, yangi yo'l boshlang.",
        "Harakatlar so'zlardan balandroq gapiradi, va bu bolalaringiz bilan haqiqatdan ham shunday.",
        "Olmos — bosim ostida yaxshi natija ko'rsatgan ko'mir bo'lagidir.",
        "Qiyin yo'llar ko'pincha go'zal manzillarga olib boradi.",
        "Ba'zan siz bir lahzaning qiymatini u xotiraga aylanmaguncha bilmaysiz.",
        "Ichdan porlab turgan nurni hech narsa o'chira olmaydi.",
        "Hayotda muvaffaqiyatga erishish uchun sizga uchta narsa kerak: istak suyagi, orqa suyagi va hazil suyagi.",
        "Sehrga ishonmaydiganlar uni hech qachon topa olmaydi.",
        "Vaqtni orqaga qaytarish uchun hech kimga pul to'lay olmasligimni tushundim, shuning uchun undan o'tish yaxshiroq.",
        "Hamma narsa narxga ega, siz uning uchun nima to'lashga tayyorsiz?",
        "Men eng ko'p g'alabalardan emas, muvaffaqiyatsizliklardan o'sdim.",
        "Men omadliman, chunki ichimdagi qo'rquv qanday bo'lishidan qat'i nazar, g'alaba qozonish istakim har doim kuchliroq.",
        "Hech kim sizga ishonmaganida o'zingizga ishonishingiz kerak.",
        "Muvaffaqiyatsizlikdan qo'rqmang, muvaffaqiyatga erishishning yo'li shu.",
        "Tanqidni yaxshi ko'raman, u sizni kuchli qiladi.",
        "Men har doim qo'limdan kelganini eng yaxshisini qilishni xohlayman.",
        "Men uchragan har bir muvaffaqiyatli odam ishkolib.",
        "Men hech qachon hech kim bilan raqobatlashmaganman, faqat o'zim bilan.",
        "O'ziga ishonch va kim ekanligingizni bilish — bu har bir buyuk narsa uchun asos.",
        "Men sinab ko'rmaslikdan qo'rqaman.",
        "O'tmishingizni qutqarishning yo'li undan qochish emas, balki uni tushunishga va undan o'sish uchun asos sifatida foydalanishga harakat qilishdir.",
        "Xavfsizlik sizga bu dunyoda hech narsa bermaydi.",
        "Ajoyib hiyla ajoyib hiyla, lekin zerikarli odamda u ishlamaydi. Gap iqtidor haqida.",
        "Siz rivojlanasiz yoki yo'q bo'lasiz.",
        "Urug' toshga ekilgan bo'lsa ham o'sishi kerak.",
        "Qanchalik qiyin bo'lmasin, ko'ksingizni kerib, boshingizni baland tuting va bajaring.",
        "Har doim eng yaxshisini qiling, bosim sizni vahimaga solishiga yo'l qo'ymang.",
        "Qachon va qanday ta'sir qilishingizni hech qachon bilmaysiz, yoki namunangiz boshqa birov uchun qanchalik muhim bo'lishi mumkinligini.",
        "Xohlagan narsangizni qilish uchun qilishingiz kerak bo'lganni qiling.",
        "Tirikchilik qilishga emas, farq yaratishga intiling.",
        "Bu dunyoda kim ekaningiz bo'ling, nima bo'lishidan qat'i nazar.",
        "Agar dushmaningiz bo'lsa, uni o'rganing va biling, faqat unga g'azablanmang.",
        "Men yashagan eng buyuk odamlarga o'xshashga intilaman.",
        "Men ustunlik qiladigan joy — bu kulgili, kasallikka tushiradigan ish axloqi. Boshqalar uxlab yotganda, men ishlayapman.",
        "Hayot chekkada yashaladi.",
        "Realitst bo'lish — o'rtamiyonalikka eng ko'p sayohat qilinadigan yo'l.",
        "Birinchi qadam — siz qila olaman deyishingiz kerak.",
        "Dunyo sizga kim ekanligingizni aytolmaydi, siz kim ekanligingizni o'zingiz aniqlashingiz va yaxshisi ham, yomoni ham shu bo'lishingiz kerak.",
        "Muvaffaqiyatsizliklaringizni tushunishingiz kerak. Ularni qabul qilib, qanday engishni aniqlashingiz kerak.",
        "Otam menga dedi: boshidan narxingizni belgilang. Agar u narxdan oshib ketsa, u yerdan keting.",
        "Agar yagona ishongan odam siz bo'lsangiz ham, ishonganingizga ishonarmidingiz?",
        "Men odamlarning fikrlariga ahamiyat bermayman, chunki odamlar o'ylamaydi.",
        "Men hech qachon biror narsada yaxshi bo'lmaganman, faqat o'rganish qobiliyatiga ega bo'lganman.",
        "Dunyodagi eng yaxshi his — qattiq mehnatning foydasi va mukofotini ko'rish.",
        "Maqsadlarim shunchalik yuqoriki, hech qanday tarzda dam olishga vaqtim yo'q.",
        "Hayot boshqalar siz haqingizda nima deyishi haqida tashvishlanish uchun juda qisqa.",
        "Har bir muvaffaqiyatli odamning ortida yoqtirmaydigan odamlar to'dasi bor.",
        "Siz hayotingizdan biror narsa qilishingiz mumkin, bu faqat harakatingizga bog'liq.",
        "Dushmanlaring bormi? Yaxshi, demak siz haqiqatan ham biror narsa uchun turganingiz.",
        "Barcha muvaffaqiyat o'z-o'zini intizom bilan boshlanadi, u sizdan boshlanadi.",
        "Harakatchanlik va biroz iqtidor bilan siz tog'larni qo'zg'ata olasiz.",
        "Muvaffaqiyatsizlik variant emas, u faqat bir qadam.",
        "Muvaffaqiyat bir kechada emas, har kuni oldingi kundan biroz yaxshiroq bo'lganingizda; hammasi qo'shiladi.",
        "Hayot sizni qiyin vaziyatlarga qo'yganda 'nega men' demang, 'sinab ko'r' deng.",
        "Muvaffaqiyat har qanday narsada har doim shunga bog'liq: diqqat va harakat. Va biz ikkalasini ham nazorat qilamiz.",
        "Bir marta dono bir odam degan edi: mukammal odamlar yo'q, faqat mukammal niyatlar bor.",
        "Ko'pincha bilasiz, yurashni to'xtatasiz, chunki 'bu tepalikni ko'tarishdan charchadim, hech qachon cho'qqiga chiqa olmayman' deysiz va cho'qqidan faqat ikki qadam narida bo'lasiz.",
        "O'zingizni sinovdan o'tkazing, bu o'sishga olib keladigan yagona yo'l.",
        "Iqtidorni tan olish uchun xizmat qila olmaysiz, uni ishlatganingiz uchun xizmat qila olasiz.",
        "Yutqazishni kafolatlashning eng yaxshi usuli — taslim bo'lish.",
        "Men uni kuzatib o'tirardim yoki uning bir qismi bo'lardim.",
        "Biror narsa yetarlicha muhim bo'lganda, ehtimollar sizning foydangizga bo'lmasa ham, uni qilasiz.",
        "Agar ertalab turib, kelajak yaxshiroq bo'ladi deb o'ylasangiz, bu yorug' kundir, aks holda emas.",
        "Tuxumlaringiz bitta savatda bo'lishi mumkin, agar siz o'sha savatga nima bo'lishini nazorat qilsangiz.",
        "Agar faqat javobini oldindan bilgan narsalarni qilsangiz, kompaniyangiz yo'q bo'lib ketadi.",
        "Agar innovatsiya qilmoqchi bo'lsangiz, noto'g'ri tushunilishga tayyor bo'lishingiz kerak.",
        "Innovatsiya uchun yomon vaqt yo'q.",
        "Imkoniyatlar yaratish — boshqalar qaramayotgan joyga qarash demak.",
        "Ter ulushi eng qimmatli ulush.",
        "Biz deyarli har doim mehnat mukofotlangan jamiyatda yashaymiz.",
        "Koinot sizga mantiqiy bo'lish majburiyati ostida emas.",
        "O'z-o'zini rivojlantirishdan kuchliroq ta'lim yo'q.",
        "Qiziquvchan hech kim ahmoq emas.",
        "Inson tarixida johillik bilimdan yaxshiroq bo'lgan vaqtni bilmayman.",
        "O'zingizni hech narsani shaxsiy qabul qilmaslikka o'rgating.",
        "Inson haqiqatan ham bunga ishonsa, xohlagan narsani qila oladi, lekin qattiq mehnat va ko'p hafsala pir bo'lishga tayyor bo'lishi kerak.",
        "Har birimiz tushunishimiz kerak bo'lgan narsa shuki, bizning niyatimiz har doim namoyon bo'ladi.",
        "Biz haqiqatan ham yaratmoqchi bo'lgan narsani e'tiborsiz qoldirolmaymiz.",
        "Faqat siz va faqat siz vaziyatingizni o'zgartira olasiz.",
        "Qiyin kunlar uchun minnatdor bo'ling, chunki ular sizni yaratdi.",
        "Eng yuqori 1 foizga qo'shilish uchun 99 foiz qilmaydigan narsani qilishingiz kerak.",
        "Men o'z yo'limni yaratdim, u to'g'ri va tor edi. Men shunday qaradim: siz yo yoki yo'limdan bo'lardingiz yoki yo'limdan ketardingiz.",
        "Hammamizda o'ziga shubha bor. Siz buni inkor qilmaysiz, lekin unga bo'ysunmaysiz ham. Siz uni qabul qilasiz.",
        "Ko'plab yetakchilar muvaffaqiyatsizlikka uchraydi, chunki ularda o'sha asabga tegish yoki o'sha torga urish jasarati yo'q.",
        "Voz kechgan lahzangiz — boshqa birovga g'alaba qozonishga imkon bergan lahzangiz.",
        "Agar muvaffaqiyatsizlikdan qo'rqsangiz, ehtimol muvaffaqiyatsiz bo'lasiz.",
        "Qo'rqinch haqiqatan ham mavjud emasligini tushundim, agar siz to'g'ri ruhiy holatda bo'lsangiz.",
        "Bu men eng qiyin vaqtlar har doim ortimda va oldimda bo'lishini qabul qilgan lahza.",
        "Hech kim chempion bo'lishini bilmaydi — bunga erishish uchun ishlash kerak.",
        "Mening e'tiqodim sizning shubhangizdan kuchli.",
        "Muvaffaqiyat — bu har kuni qilayotgan ishingizdan qoniqish. Bu yaxshiroq odam bo'layotganingiz bilan faxrlanish.",
        "Agar muvaffaqiyatli bo'lmoqchi bo'lsangiz, har bir aloqangizdan foydalanishga tayyor bo'lishingiz kerak.",
        "Iqtidor hech qachon yetarli emas. Kam istisno bilan, eng yaxshi o'yinchilar eng qattiq ishlaydigan o'yinchilar.",
        "Taslim bo'lmang, qattiq ishlashingizga yordam beradigan odamlar bilan do'st bo'ling.",
        "Bor hayotingizni nishonlang, bo'lishi mumkin bo'lgan hayotni emas.",
        "Men kambag'al o'sdim, lekin kambag'al orzularim yo'q edi.",
        "Siz farq yarata oladigan yagona odam sizligingiz. Orzungiz nima bo'lsa, unga intiling.",
        "Biror narsa yuz berdi deb hayot to'xtamaydi.",
        "Hayotda g'alaba qozonish va yutqazish ikkalasi ham sodir bo'ladi, hech qachon qabul qilinmaydigan narsa — taslim bo'lish.",
        "Hayotimda qancha marta rad etilganimni bilasizmi? Qancha marta menga biror narsaga erishishim mumkin emasligini aytishgan?",
        "Ko'pincha men shuni ko'rdim: eng iqtidorli odamlar o'sha munosabatni rivojlantirmaydi. Bunday ne'matga ega bo'lmaganlar esa eng raqobatbardosh va eng katta yurakka ega.",
        "Men hech qachon o'ynash imkoniyatim bo'lmaydi deb o'ylagandim, bir kuni bo'ldi, chunki men tayyor edim va imkoniyat o'zini ko'rsatdi.",
        "Men shunchaki raqobatni va yaxshilanishga harakat qilishni yaxshi ko'raman.",
        "Hayotda ko'pincha biror narsa sodir bo'ladi va biz boshqalarni baxtli, qanoatlanmagan yoki to'liq bo'lmasligimiz uchun ayblayimiz.",
        "Hayotingiz sizning qilganingiz bo'ladi.",
        "Birov men haqimda yomon narsa aytdi deb hafsalam pir bo'lmaydi.",
        "Hayotda chetda o'tira olmaysiz.",
        "Mening xabarim oddiy: hayotingizni nazorat qiling.",
        "Jamoaning yetakchilaridan biri bo'lganingizda dam olish kunlari yo'q.",
        "Boshqalarga tayanmang. Siz ko'p odamlardan katta yordam olasiz, baribir. Lekin hech kim sizga hech narsani berib qo'ymaydi.",
        "Narsalar o'z-o'zidan tuzatilmaydi; siz chiqib, ularni tuzatish uchun qattiq ishlashingiz kerak.",
        "Agar g'alaba qozonish uchun o'ynamasangiz, umuman o'ynamang.",
        "Agar o'zingizga ishonmasangiz, boshqa birov nima uchun sizga ishonadi.",
        "Ba'zan hayotdagi eng katta sinovlar hayotingizda sodir bo'lgan eng yaxshi narsalar bo'ladi.",
        "Men shunchaki qattiq ishlashni yaxshi ko'raman.",
        "Haqiqiy raqobatchilar esa har doim g'alaba qozonish uchun o'ynaydi.",
        "Pulning ortidan quvmang, orzuning ortidan quving.",
        "Agar uchmoqchi bo'lsangiz, sizni bosib turgan narsalardan voz kechishingiz kerak.",
        "Men orzu ko'rishingizni xohlamayman, men qilishingizni xohlayman.",
        "Kimdir bo'lishni xohlagan har bir odam imkoniyatidan kelib chiqib qattiq ishlaydi.",
        "Men hech qachon eng yaxshi bo'lish niyatim ekanligini yashirishga urinmaganman.",
        "Agar o'zingizni eng yaxshi deb ishonmasangiz, qodir bo'lgan hamma narsangizga hech qachon erisholmaysiz.",
        "Bugun kelajakda qaytib keladimi yoki yo'qmi hech kim bilmaydigan imkoniyatlar bor.",
        "Qattiq mehnatsiz iqtidor hech narsa.",
        "Odamlarning meni yoqtirmasligiga e'tibor bermayman, chunki bu meni ilgari suradi.",
        "Iqtidor hamma narsa emas. Siz uni beshikdan olishingiz mumkin, lekin eng yaxshi bo'lish uchun kasbni o'rganish kerak.",
        "Men cheksiz o'rganish, yaxshilanish, rivojlanish zaruriyatini his qilaman — o'zimdan qoniqish his qilish uchun.",
        "Sevgingiz meni kuchli qiladi. Nafrtingiz meni to'xtatib bo'lmas qiladi.",
        "Agar biror narsani yetarlicha sevsangiz, hamma narsani yengishingiz mumkin.",
        "Men muvaffaqiyatliman, chunki muvaffaqiyat uchun qurbonlik qildim.",
        "Mening ambitsiyam har doim yaxshiroq va yaxshiroq bo'lish.",
        "Men erta boshlayman va kech qolaman. Kundan kunga, yildan yilga, bir kechalik muvaffaqiyatga aylanishim uchun 17 yil va 114 kun kerak bo'ldi.",
        "Meni baxtdan uzoq tutgan odam men o'zim edim.",
        "E'tibor berishning oddiy harakati sizni juda uzoqqa olib borishi mumkin.",
        "Haqiqatni ommaning fikri bilan aralashtirib yubormang. Bular deyarli hech qachon o'xshash ham emas.",
        "Yo'lni bilish va yo'lda yurish orasida farq bor.",
        "Meni sevmaydigan odam men haqimda nima deyishi haqida tashvishlanib, tun bo'yi o'tirmayman.",
        "Kim ekanligingiz haqida ikkilanib bo'lmaydi.",
        "Har doim ishlash kerak bo'lgan narsalar bor, siz hech qachon u yerda bo'lmaysiz.",
        "Men o'zim bo'lishni xohlagan narsam bo'lishni xohlayman: hukmron.",
        "Men shunchaki eng yaxshi bo'lishga harakat qilaman va bu eng yaxshi bo'lishini umid qilaman.",
        "Men bir paytlar bo'lganimdek yaxshi bo'lishni emas, undan ham yaxshiroq bo'lishni xohlayman.",
        "Aqlim mening eng katta boyligim. Men har bir turnirda g'alaba qozonishni kutaman.",
        "Hissiyotlarini nazorat qiladigan yigitlar g'alaba qozonadi.",
        "Qanchalik yaxshi bo'lsangiz ham, har doim yaxshiroq bo'lishingiz mumkin va bu hayajonli qism.",
        "Boshqalarga yordam berish uchun avval o'zingizga yordam berishni o'rganishingiz kerak.",
        "Qattiq mehnatsiz qiymatli hech narsa kelmaydi.",
        "Men hech bir odamga meni yomon ko'rishga majburlab ruhimni kamsitishiga yo'l qo'ymayman.",
        "Siz odamni bostirib, o'zingiz bostirilib qolmasdan ushlab tura olmaysiz.",
        "Xarakter, sharoit emas, odamni yaratadi.",
        "Kuchni ishlatishning ikki yo'li bor: biri bosish, ikkinchisi ko'tarish.",
        "Men muvaffaqiyatga erishganidan ko'ra ko'proq muvaffaqiyatsizlikka uchraganman.",
        "Men bugun odamlar qilmaydigan narsani qilaman, shuning uchun ertaga odamlar qilolmaydigan narsaga erishaman.",
        "Yutqazsangiz ham, darsni yo'qotmang.",
        "Sotishning eng oson yo'li — haqiqatni sotish.",
        "Mukammal vaqtni kutmang, abadiy kutasiz. Har doim berilgan vaqtdan foydalaning va uni mukammal qiling.",
        "Siz faqat shuncha narsani ajoyib qila olasiz, qolgan hamma narsani chetga surishingiz kerak.",
        "Hayot mo'rt. Bizga ertangi kun kafolatlanmagan, shuning uchun qo'lingizdagini bering.",
        "Men o'zimni ahmoq qilishdan qo'rqmayman.",
        "Meni muvaffaqiyat emas, hurmat rag'batlantiradi.",
        "Tepalikdan oshganingizda tezlikni oshirasiz.",
        "Mukammallik harakat emas, odatdir.",
        "Agar 'F' olishdan qo'rqsangiz, 'A' ololmaysiz.",
        "Siz xatolaringizni yaxshi narsalarga qanday erishishni o'rganish uchun qilasiz.",
        "Qahramon — bu ixtiyoriy ravishda noma'lumga kiradigan kishi.",
        "U yerda millionlab omon qolganlar bor. Uni million va bitta qiling.",
        "Hech qachon taslim bo'lmang, chunki siz ertasi kuni to'lqin nima olib kelishini hech qachon bilmaysiz.",
        "Agar qiyin bo'lmaganida, hamma qilardi. Qiyinligi uni buyuk qiladi.",
        "Agar tanlovlaringiz haqida ehtiyot bo'lsangiz, o'smasangiz.",
        "Men qo'rqadigan narsani qilishni yaxshi ko'raman.",
        "Jarayon eng go'zal qism.",
        "Ko'zni aldash oson, lekin yurakni aldash qiyin.",
        "Hech qachon juda balandga ko'tarilmang, hech qachon juda pastga tushmang. Har kuni qabul qiling va o'rganishni davom ettiring.",
        "Mehnatga hech qachon shubha bo'lmaydi.",
        "Birov sizga imkoniyat berishini umid qilmang: o'zingiz uchun yarating.",
        "Odamlar menga hech qachon erisha olmayman deyishganda, men qila olaman degan bir kishini — o'zimni — tingladim.",
        "Orzularingizni quvlash degan sabab bilan uni yurish deyishmaydi.",
        "Haqiqatan ham xohlagan narsangizga ega bo'lish uchun avval haqiqatan ham kim ekanligingiz bo'lishingiz kerak.",
        "O'tmish sizni ta'qib qilishiga yo'l qo'ymang. Chunki hozir yoki kelajakda qilgan ishingiz o'tmishingizni yashira olmaydi, lekin bu o'tmishning sizni boshqarishiga yo'l qo'ying degani emas.",
        "O'sha \"agar bo'lganida-chi\" — bu hech qachon bitmaydigan yara.",
        "Agar oson bo'lganida, bunga arzimasdi.",
        "Siz hech narsaga loyiq emassiz, siz hamma narsani topasiz.",
        "Mukammallik qiziq emas, sinov-sinovlardan g'olib chiqish — meni hayratga soladigan narsa shu.",
        "\"Menga achining\" Olimpiadasida qatnashmang; biz bunda raqobatlashmaymiz.",
        "Biror narsani xohlasangiz, u bilan birga keladigan sharoitni qabul qilasiz, qanday sharoit bo'lishidan qat'i nazar.",
        "Haqiqiy ko'rish — bu ongingiz ko'zlaringiz oldidagidan kuchliroq bo'lganda.",
        "Ba'zi voqealar sizni rivojlantiradi, ba'zilari aksini qiladi — ko'rinishiga qarab. O'sha aksilari kelajakda foydali bo'ladigan o'rganish imkoniyatlari.",
        "Xo'jayin bo'lish narxini to'lang yoki afsus narxini to'lang.",
        "Boshqa odamlarning siz haqingizdagi fikri sizning haqiqatingizga aylanishi shart emas.",
        "Siz xohlagan narsani emas, ishlagan narsani olasiz.",
        "O'z-o'zini intizom fikrlaringizni boshqarishdan boshlanadi. Nima o'ylashingizni nazorat qilmasangiz, nima qilishingizni nazorat qila olmaysiz.",
        "Mag'lubiyat nima? Hech narsa emas, faqat ta'lim; faqat yaxshiroq narsaga birinchi qadam.",
        "Sizga nima sodir bo'lganligi emas, unga qanday munosabat bildirishingiz muhim.",
        "G'azabingizni boshqaring. Boshqalarga g'azab qilsangiz, ular sizni boshqaradi.",
        "Eng katta sinovingiz — ongingiz eng yaxshi baholalarni ishlab chiqayotganida paydo bo'lish.",
        "Siz intizom og'rig'ini yoki afsus og'rig'ini boshdan kechirishingiz mumkin. Tanlov sizniki.",
        "Sizni jismonan, aqliy va ruhan zaiflashtirgan har qanday narsani zahar sifatida rad eting.",
        "Tinchlik paytida ko'proq terla, urush paytida kam qon to'k.",
        "Boshlash jasarati va bardosh berish intizomi bilan g'alaba vaqt masalasiga aylanadi.",
        "Yaxshi yetakchi — aybning o'z ulushidan ko'proqini va xizmatning o'z ulushidan kamroqni oladigan shaxs.",
        "Kuchli bo'ling, lekin qo'pol bo'lmang. Mehribon bo'ling, lekin zaif bo'lmang. Jasur bo'ling, lekin zo'ravon bo'lmang. Kamtar bo'ling, lekin uyatchan bo'lmang. Faxrlaning, lekin takabbur bo'lmang.",
        "Sabr achchiq, lekin mevasi shirin.",
        "Sabr passiv emas, aksincha; u faol. Bu to'plangan kuchdir.",
        "Sinab ko'radigan odam uchun imkonsiz hech narsa yo'q.",
        "Aql-zakovat ma'lumotni saqlash qobiliyati emas, balki uni qayerdan topishni bilishdir.",
        "Avvaliga u niyat. Keyin xulq-atvor. Keyin odat. Keyin amaliyot. Keyin ikkinchi tabiat. Keyin bu oddiygina siz bo'lgan narsadir.",
        "Xohlagan narsangizni qiling, hozir qiling. Faqat shuncha ertalar bor.",
        "Buni qilib bo'lmaydi deydiganlar, qilayotganlarni to'xtatmasligi kerak.",
        "Yaxshilashtirishga ishonchingiz bo'lgan koinotning yagona burchagi — bu o'zingiz.",
        "Ahmoq o'zini dono deb o'ylaydi, lekin dono odam o'zini ahmoq ekanini biladi.",
        "Og'riq sizni o'zgartirishi mumkin, lekin bu yomon o'zgarish bo'lishi shart emas. O'sha og'riqni oling va donolikka aylantiring.",
        "Vaqt — har qanday insonning yagona kapitali va yo'qotishga toqat qilib bo'lmaydigan yagona narsa.",
        "Odamlar nima deyishidan qat'i nazar, o'z yo'lingizdan boring.",
        "Biror narsa qiling. Agar ishlasa, ko'proq qiling. Agar ishlamasa, boshqa narsa qiling.",
        "O'rganish — aqlni hech qachon charchatmaydigan, hech qachon qo'rqitmaydigan va hech qachon afsusga solingmaydigan yagona narsa.",
        "G'olib — hech qachon taslim bo'lmaydigan orzumand.",
        "Xohlagan narsangiz uchun kurashmasangiz, yo'qotganingiz uchun yig'lamang.",
        "Kamchiliklaringizni qabul qilganingizda, hech kim ularni sizga qarshi ishlata olmaydi.",
        "Koinot haqida yetarlicha o'rganganimizda, hamma narsani hech qachon bilmasligimizni o'zimizga tan olamiz.",
        "Tashvishlanish — siz qarzli bo'lmagan qarzni to'lash kabi.",
        "Siz hech kimga hech narsani o'rgata olmaysiz, faqat javoblar allaqachon ichlarida ekanligini tushuntirishingiz mumkin.",
        "Fikrlarning kuchi sizga kasallik yoki tuzalishni keltirishishi mumkin.",
        "Agar mo'jiza ko'rmoqchi bo'lsangiz, mo'jiza bo'ling.",
        "Uch xil odamlar bor: ko'radiganlar, ko'rsatilganda ko'radiganlar, ko'rmaydifanlar.",
        "Eng katta qo'rquvlaringiz tasavvuringiz tomonidan yaratilgan.",
        "Odamlar duchar bo'ladigan eng katta aldov — o'z fikrlaridan kelib chiqadi.",
        "Barcha imkoniyatlarni tugatganingizda, buni eslab qoling: siz tugatmagansiz.",
        "Taqdir sizga bergan qo'lni seving va uni o'zingizniki deb o'ynang.",
        "Agar ikki kishi hamma narsada kelishsa, ulardan biri keraksiz.",
        "Eng katta raqobat — o'zingiz bilan bo'lgan raqobat.",
        "Charchaganimizda, biz allaqachon yengilgan g'oyalar bizga hujum qiladi.",
        "Men boshimga tushgan narsa emasman. Men bo'lishni tanlagan narsamanman.",
        "Omon qolishning eng muhim omili aql-zakovat ham, kuch ham emas, balki moslashuvchanlikdir.",
        "Ishonch va qo'rquv ikkalasi ham ko'ra olmaydigan narsangizga ishonishni talab qiladi. Siz tanlaysiz.",
        "Shikoyat qilish bilan odamlarga qanchalik zaif ekanligingizni aytasiz.",
        "Sevgan narsangizga ega bo'lish uchun avval yomon ko'rgan narsangizga sabrli bo'lishingiz kerak.",
        "Hamma narsa sizga qarshi bo'lib tuyulganda, esda tutingki, samolyot shamolga qarshi uchib ko'tariladi, u bilan emas.",
        "Haqiqatan kim ekanligingizni bilganingizda, qo'rquvlaringizga kulasiz.",
        "Tinchlik sokinroq bo'ronda emas, yaxshiroq qayiqda topiladi.",
        "Haqiqatni e'tiborsiz qoldirishingiz mumkin, lekin haqiqatni e'tiborsiz qoldirishning oqibatlarini e'tiborsiz qoldira olmaysiz.",
        "Hech qachon baxtsizlikka duch kelmagan odamdan baxtsizroq odam yo'q. Chunki unga o'zini isbotlashga ruxsat berilmagan.",
        "Hozir shiddatli ravishda amalga oshirilgan yaxshi reja keyingi hafta amalga oshiriladigan mukammal rejadan yaxshiroq.",
        "O'rganib, lekin o'ylamaslik — behuda. O'ylab, lekin o'rganmaslik — xavfli.",
        "Qo'rquv — reaktsiya. Jasorat — qaror.",
        "Mustaqillik juda kam odamlar uchun; bu kuchlillarning imtiyozi.",
        "Hayotning yarmi, hayot \"o'zing qil\" loyiha ekanini tushunishdan oldin o'tadi.",
        "Rolingizni sharaf bilan o'ynang.",
        "Tashvish — tasavvurning noto'g'ri ishlatilishi.",
        "Bilim va mahorat o'rtasidagi ko'prik amaliyot. Mahorat va mahorat o'rtasidagi ko'prik vaqt.",
        "Qanchalik ko'p o'rgansam, hali qancha o'rganishim kerakligini shunchalik ko'proq tushunaman.",
        "Agar yutqazmasangiz, g'alabalardan zavqlana olmaysiz. Shuning uchun men ikkalasini ham qabul qilishim kerak.",
        "Biz g'alabadan kam, mag'lubiyatdan ko'p o'rganamiz.",
        "Muloyimlik bilan gapirib, tayyorgarlikni kuchaytiradigan odam oldinga boradi. Tajovuzkorlik bilan gapirib, shoshiladigan odam chekinadi.",
        "Bizning hayotimiz fikrlarimiz qilgan narsadir.",
        "Haqiqatan qiyin narsa yo'q, agar siz uni qiyin deb qaror qilmasangiz. Aks holda, bu faqat siz hal qilayotgan keyingi narsa.",
        "Vaziyat qanday bo'lmasin, hech qachon hissiyotlaringiz aql-zakoatingizdan ustun bo'lishiga yo'l qo'ymang.",
        "Bo'lmoqchi bo'lgan shaxs turini belgilang va unga yolg'iz bo'lsangiz ham, odamlar orasida ham amal qiling.",
        "Agar biror narsa noto'g'ri bo'lsa, imkoningiz bo'lsa tuzating. Lekin o'zingizni tashvishlantirmaslikka o'rgating. Tashvish hech narsani tuzatmaydi.",
        "Hayot yaxshi qo'llarni ushlab turish emas, balki yomon qo'lni yaxshi o'ynash haqida.",
        "Bu buyuklik cho'qqilariga olib boradigan qo'pol yo'l.",
        "Inson lazzatdan ustun bo'lgan kuni, u og'riqdan ham ustun bo'ladi.",
        "Doimiy o'rganing, har doim yana bitta o'rganadigan narsa bor.",
        "Biz atirgullarda tikan borligidan shikoyat qilishimiz yoki tikan butalarida atirgul borligidan xursand bo'lishimiz mumkin.",
        "Sabr qiling va kuchli bo'ling; bir kun bu og'riq sizga foydali bo'ladi.",
        "Muvaffaqiyatsizlik — bu rivojlanayotgan muvaffaqiyat.",
        "O'rganishni to'xtatgan har bir kishi qari, u yigirma yoshda bo'lsin yoki sakson.",
        "Agar aql tomonidan boshqarilsangiz, siz podshodsiz; agar tana tomonidan, qulingiz.",
        "G'urur uyatning qarama-qarshisi emas, uning manbai. Haqiqiy kamtarlik uyatga yagona davo.",
        "O'zingizni yaxshilashga kirishganingizda, yolg'izlik to'laydigan narxdir.",
        "Siz erishgan balandlik bilan emas, chiqqan chuqurlik bilan baholanasiz.",
        "Odam muvaffaqiyatsizlikka uchramoganligi uchun buyuk emas; muvaffaqiyatsizlik uni to'xtata olmaganligi uchun buyuk.",
        "Ko'rishi bo'lmagan odam kelajaksiz odam. Kelajagi yo'q odam har doim o'tmishiga qaytadi.",
        "Sharaf bilan muvaffaqiyatsiz bo'lish, firibgarlik bilan muvaffaqiyatga erishishdan yaxshiroq.",
        "Barcha janglar avval aqlda g'alaba qozoniladi yoki yutqaziladi.",
        "Insonning hissiyotlari aqlidan tezroq qo'zg'aladi.",
        "Kerak bo'lmagan narsani sotib olgan odam o'zidan o'g'irlaydi.",
        "Sabr-toqatli bo'lgan odam xohlagan narsasiga ega bo'ladi.",
        "Jangchining yo'li umr bo'yi davom etadi va mahorat ko'pincha shunchaki yo'lda qolishdir.",
        "Uçurtmalar shamolga qarshi eng balandga ko'tariladi, u bilan emas.",
        "Agar odamlar mahoratimga erishish uchun qanchalik qattiq ishlashim kerak bo'lganini bilsalar, bu unchalik ajoyib tuyulmasdi.",
        "Hech qachon ong ostingizga so'rov qilmasdan uxlamang.",
        "Voqealarni qanday sodir bo'lishidan qat'i nazar qabul qiling: bu tinchlik yo'li.",
        "Imkonsiz tuyulgan narsani ham mashq qiling.",
        "Ikki quyonning ortidan quvgan odam hech birini tutolmaydi.",
        "Siz muvaffaqiyatga erishasiz, lekin har doim erishmayotgandek tuyuladi.",
        "Oson bo'lganda qiyin narsani rejalashtiring, kichik bo'lganda buyuk narsani qiling.",
        "Qat'iyat yetarli emas. Azob chekuvchi sifatida yoki jangchi sifatida davom etishni hal qilish kerak.",
        "Orzu qilgan cho'qqilarga ko'tarilish uchun zarur bo'lgan o'tkirlik va intizom darajasi juda oddiy, faqat oson emas.",
        "Eng katta dushman tashqarida topilmaydi. Halokat ko'pincha ichkaridan keladi.",
        "Hamma buni imkonsiz deb bilardi, bilmaydigan bir ahmoq kelib, qilib qo'ydi.",
        "Kuchli odamni zaiflashtirish bilan zaif odamni kuchli qilib bo'lmaydi.",
        "Ongingiz ustidan hokimiyatingiz bor — tashqi voqealar ustidan emas. Buni anglang va kuch topasiz.",
        "Olmos — o'z ishiga sodiq bo'lgan ko'mir bo'lagidir.",
        "Eng katta xavf — hech qanday xavf qilmaslik.",
        "Agar muammoni to'g'ri aniqlasangiz, deyarli yechimga egasiz.",
        "O'tmish boshingizda, kelajak qo'llaringizda.",
        "Hayot juda oddiy. Siz biror narsa qilasiz. Ko'pchiligi muvaffaqiyatsiz bo'ladi. Ba'zilari ishlaydi. Ishlaganidan ko'proq qilasiz.",
        "Burch hissingiz qo'rquv muhiti va intilishlarni kechiktirish tendensiyasidan ustun bo'lsin.",
        "Xohlagan hamma narsangiz qo'rquvning narigi tomonida.",
        "Intizom — hozir xohlagan narsangiz va eng ko'p xohlagan narsangiz o'rtasida tanlash.",
        "Moslashuvchanlik — tasavvursizlarning oxirgi panohgohidir.",
        "Olmos — o'z ishiga yopishib olgan ko'mir bo'lagi.",
        "Inson uchun behuda sarflangan vaqtdan kattaroq zarar yo'q.",
        "Siz ega bo'lmagan narsani xohlash bilan borligingizni buzmasdan; esda tutingki, hozir siz ega bo'lgan narsa bir paytlar faqat umid qilgan narsalar orasida edi.",
        "Sabr ustasi — hamma narsaning ustosidir.",
        "Hech qachon ehtirosni printsipdan oldinga qo'ymang, hatto g'alaba qozsangiz ham, yutqazasiz.",
        "Ba'zilar buni xohlaydi, ba'zilar orzu qiladi, boshqalari buni amalga oshiradi.",
        "Biz kutganlarimiz darajasiga ko'tarilmaymiz, mashqlarimiz darajasiga tushamiz.",
        "O'lishga ko'ngilli bo'lgan erkaklar topish sabr bilan og'riqqa chidaydigan erkaklar topishdan osonroq.",
        "Agar poygada qatnashmasangiz, podiumga ko'tarilishni kutolmaysiz.",
        "Yiqilib, o'rnidan turgan odam hech qachon sinab ko'rmagan odamdan kuchliroq.",
        "Yomon xabar: Siz hamma bilan mos kelolmaysiz. Yaxshi xabar: Buyuklar hech qachon mos kelmagan.",
        "Men hech qachon iqtidorli bo'lmaganman, men faqat taslim bo'lmaslikda yaxshiman.",
        "Baxt — muammolarning yo'qligi emas, ular bilan kurasha bilishdir.",
        "Agar oson narsani qilsangiz, hayotingiz qiyin bo'ladi.",
        "Orqaga qaytib, boshini o'zgartira olmaysiz, lekin turgan joyingizdan boshlab, oxirini o'zgartirishingiz mumkin.",
        "Ko'proq narsa o'rgatilgandan ko'ra ko'proq narsa ushlanib olinadi.",
        "Hech qachon xato qilmaydigan odamlar xato qiladigan biz uchun ishlaydi.",
        "Yangi g'oyani darhol natijalari bilan baholamaslik kerak.",
        "Siz qilishingiz kerak bo'lgan narsa uchun hech qachon tayyor emassiz. Siz faqat qilasiz. Bu sizni tayyor qiladi.",
        "Tavakkal qiling: agar yutasangiz, baxtli bo'lasiz; agar yutqazsangiz, dono bo'lasiz.",
        "Imtiyozlarini printsiplardan yuqori qo'yadigan xalq tez orada ikkalasini ham yo'qotadi.",
        "Mazmun va muvaffaqiyatga eng tez yo'l: bitta narsani tanlang va to'liq kiriting.",
        "Qaytadan boshlashdan qo'rqmang. Bu safar siz noldan emas, tajribadan boshlayapsiz.",
        "Insondan ustun bo'lishda hech qanday sharaf yo'q; haqiqiy sharaf — avvalgi o'zingizdan ustun bo'lish.",
        "Agar o'zingizga hurmatni qozona boshlasangiz, hammaning hurmatini qozonasiz.",
        "Kim bo'lishni xohlayotganingiz haqida tasavvur yarating, so'ng xuddi u allaqachon haqiqat bo'lgandek yashang.",
        "Mukammallikning narxi intizom. O'rtamiyonalikining narxi hafsala pir bo'lish.",
        "Qiyinchiliklar aqlni kuchaytiradi, xuddi mehnat tanani kuchaytirgandek.",
        "Siz harakat qilmagan sohalarda taraqqiyotga umid qila olmaysiz.",
        "Hech qanday xavotir sodir bo'ladigan narsaga hech qanday ta'sir qilmaydi.",
        "Menga o'rtacha qobiliyatli, lekin favqulodda istaklarli odamni ko'rsating va men sizga har safar g'olibni ko'rsataman.",
        "Muvaffaqiyatga erishishning eng tez yo'li — hozir boshlash va yo'l-yo'lakay tushunib olish.",
        "Odamlar kelajaklarini hal qilmaydi, odatlarini hal qiladi va odatlari kelajaklarini hal qiladi.",
        "Bolalaringizga kech o'rgangan narsangizni erta o'rgating.",
        "Agar har qanday fanda yiliga 100 soat sarflasangiz (bu kuniga atigi 18 daqiqa), dunyodagi 95 foiz odamlardan yaxshiroq bo'lasiz.",
        "Vazifa — hali hech kim ko'rmagan narsani ko'rish emas; balki hamma ko'rgan narsa haqida hali hech kim o'ylamagan narsani o'ylash.",
        "Agar har bir ishqalanishdan asabiylanib tursangiz, oynangiz qanday sayqallanadi?",
        "Qo'rquv faqat aql ruxsat bergancha chuqur.",
        "Qiyinchilik dahiylikni uyg'otadi.",
        "Nur berishi kerak bo'lgan narsa yonishga chidashi kerak.",
        "Muvaffaqiyat hayotda erishilgan mavqe bilan emas, muvaffaqiyatga erishishga harakat qilganida yengilgan to'siqlar bilan o'lchanishi kerakligini o'rgandim.",
        "Qulaylik — eng yomon mubtalolik.",
        "Siz e'tiboringizni nimaga bersangiz, shunday bo'lasiz.",
        "Sharoitlar odamni yaratmaydi, ular uni faqat o'ziga ochib beradi.",
        "Yaxshi odam qanday bo'lishi kerakligi haqida bahslashib vaqt o'tkazmang. Shunday odam bo'ling.",
        "Dunyoni o'zgartirmoqchi bo'lgan odam avval o'zini o'zgartirsin.",
        "Ta'sir va javob o'rtasida bo'shliq bor. O'sha bo'shliqda javobimizni tanlash kuchimiz bor. Javobimizda o'sishimiz va erkinligimiz yotadi.",
        "O'zingizdan tashqarida sizni yaxshiroq, kuchliroq, boyroq, tezroq yoki aqlliroq qila oladigan hech narsa yo'q. Hamma narsa ichkarida. Hamma narsa mavjud. O'zingizdan tashqarida hech narsa izlamang.",
        "Boshqalarga bag'rikeng, o'zingizga qattiqqo'l bo'ling.",
        "Ikkita narsa sizni belgilaydi: hech narsangiz yo'q bo'lgandagi sabringiz va hamma narsangiz bo'lgandagi munosabatingiz.",
        "Siz shunchaki uyg'onib, kapalakka aylanmaysiz.",
        "Chidamlilik — qo'yib yuborish eng jozibali ko'ringanida ushlab turishdir.",
        "Harakat qilishning xatarlari va xarajatlari bor. Lekin ular qulay harakatsizlikning uzoq muddatli xatarlaridan ancha kam.",
        "Buyuk ishlarga erishish uchun ikkita narsa kerak: reja va yetarlicha vaqt bo'lmasligi.",
        "Shubhani faqat harakat yo'q qila oladi.",
        "Agar harakatlaringiz boshqalarni ko'proq orzu qilishga, ko'proq o'rganishga, ko'proq qilishga va ko'proq bo'lishga ilhomlantirsa, siz yetakchisiz.",
        "Muhim narsa benuqson rekord emas. Muhim narsa rekordingizdagi nuqsonlardan o'rganishdir.",
        "Yangi narsada yomon bo'lishga jasur bo'ling.",
        "Uyg'onganingizdan aqlliroq uxlashga boring.",
        "Sekin muvaffaqiyat xarakter shakllantiradi, tez muvaffaqiyat ego shakllantiradi.",
        "Kimdir qoqilib, yo'lini yo'qotganligi uchun abadiy yo'qotilgan degani emas.",
        "Lekin biz yaralarimizga abadiy qarab o'tira olmaymiz.",
        "Va endi mukammal bo'lish shart bo'lmagach, yaxshi bo'lishingiz mumkin.",
        "Muvaffaqiyat asoslarning shafqatsiz bajarilishidan keladi.",
        "Biror narsani sodda qilish uchun ko'p qattiq mehnat kerak.",
        "Hamma dunyoni o'zgartirish haqida o'ylaydi, lekin hech kim o'zini o'zgartirish haqida o'ylamaydi.",
        "Yopiq fikirlilar san'atni qoshiq bilan ovqatlantirdilishni talab qilishadi.",
        "Vaqtni o'ldirish o'rniga biror narsa qiling. Chunki vaqt sizni o'ldirmoqda.",
        "Har bir qaroringiz ko'rishingiz bilan bir yo'nalishda bo'lsin.",
        "Agar o'rtachadan buyukroq biror narsa qilmoqchi bo'lsangiz, begona bo'lish qo'rquviga bo'ysunib bo'lmaydi.",
        "Eng muhim narsa olov ichidan qanchalik yaxshi o'tishingiz.",
        "Siz butunlay boshqa hayotdan bitta qaror naridasz.",
        "Agar ertaga uchun yashasangiz, har doim bir kun ortda qolasiz.",
        "O'zingizdan eng yaxshisini qiling, chunki sizning barchasiz shundan iborat.",
        "Aql ko'r bo'lganda ko'zlar foydasiz.",
        "Uzoq muddatda odamlar faqat mo'ljallagan narsalariga urishadi. Shuning uchun, darhol muvaffaqiyatsiz bo'lsa ham, baland narsani mo'ljallaganlar yaxshiroq.",
        "Yashash sababi bo'lgan odam deyarli har qanday qiyinchilikka bardosh bera oladi.",
        "Odamlarni ikki guruhga bo'lish mumkin: biri oldinga boradi va biror narsaga erishadi, ikkinchisi orqadan keladi va tanqid qiladi.",
        "Yomon munosabat tekis shinaga o'xshaydi. Uni o'zgartirmaguningizcha hech qayerga bora olmaysiz.",
        "Hech qanday qush o'z qanotlari bilan uchsa juda balandga uchmasdi.",
        "Muammoni hal qiling yoki muammoni tark eting. Muammo bilan yashamang.",
        "Kayfiyatingizga emas, tamoyillaringizga ko'ra harakat qiling.",
        "Hech narsaga sodiq bo'lmaganlar hamma narsadan chalg'iydi.",
        "Biz avvalgidan yaxshiroq bo'lishga intilsak, atrofimizdagi hamma narsa ham yaxshiroq bo'ladi.",
        "Qodir bo'lgan hayotdan past hayotga rozi bo'lishda hech qanday ehtirom yo'q.",
        "Ijodiy odam boshqalarni yengish uchun emas, erishish uchun harakat qiladi.",
        "Hayot hech qachon sodir bo'lmaydigan narsaga uzoq tayyorgarlikdir.",
        "Men endi odamlar nima deyishini tinglamayman, faqat nima qilishini kuzataman. Xulq-atvor hech qachon yolg'on gapirmaydi.",
        "Aqlli kishilar hamma narsadan va hamma kishidan o'rganadi; o'rtacha kishilar tajribalaridan. Ahmoqlar allaqachon barcha javoblarga ega.",
        "Birinchi qoida — bezovta bo'lmagan ruhni saqlash. Ikkinchisi — narsalarga yuzma-yuz qarab, ularni nima ekanini bilish.",
        "Kattaroq og'irlikni ko'tarish har doim kurash.",
        "Azob chekishdan qo'rqadigan odam allaqachon qo'rqayotgan narsasidan azob chekmoqda.",
        "Agar odam qaysi portga suzayotganini bilmasa, hech qanday shamol qulay emas.",
        "Men har doim qila olmaydigan narsani qilaman, uni qanday qilishni o'rganish uchun.",
        "Siz muvaffaqiyatsizlik ustiga qurasiz. Uni zinpoya sifatida ishlatasiz. O'tmishga eshikni yoping. Xatolarni unutishga urinmang, lekin ularga e'tibor bermang. Ularga energiyangizning, vaqtingizning yoki bo'shlig'ingizning hech qanday qismini bermang.",
        "Xarakteringizning mazmuni sizning tanlovingiz. Kundan kunga nimani tanlashingiz, nima o'ylashingiz va nima qilishingiz — bu kim bo'lishingiz.",
        "Qo'rqoqlar hech qachon boshlamadi va zaiflar yo'lda halok bo'ldi.",
        "Ertalab uyg'onganingizda, tirik bo'lish — nafas olish, o'ylash, zavq olish, sevish — qanday qimmatbaho imtiyoz ekanligini o'ylang.",
        "Muvaffaqiyatning siri — maqsadga diqqatni jamlash.",
        "Johillikdan xavfliroq yagona narsa — takabburlik.",
        "Biz takror-takror qilgan narsamiz. Mukammallik, demak, harakat emas, odatdir.",
        "Biz hayotni kutib turganda, hayot o'tib ketadi.",
        "Muvaffaqiyat — har kuni qilinadigan bir nechta oddiy intizomlardan boshqa narsa emas.",
        "Qanchalik ko'p bilsa, johilligidan shunchalik ko'proq xabardor bo'ladi.",
        "Harakatga to'siq harakatni ilgari suradi. Yo'lda turgan narsa yo'lga aylanadi.",
        "Bizning eng katta zaifligimiz taslim bo'lishda. Muvaffaqiyatga erishishning eng ishonchli yo'li har doim yana bir marta sinab ko'rishdir.",
        "Gavharni ishqalanmasdan sayqallash mumkin emas, odamni sinov-sinovlarsiz mukammallashtirish mumkin emas.",
        "Sizning qadringiz nimaga ega ekanligingizda emas, kim ekanligingizda.",
        "Noto'g'ri ish qilgan odam noto'g'rilikka uchragan odamdan baxtsizroq.",
        "Halollikning eng haqiqiy sinovlaridan biri — uning murosaga kelishdan qat'iy bosh tortishidir.",
        "Xudo qo'llarini kavushtirib turganlaarga hech narsa bermaydi.",
        "Qanday o'ylashni bilish sizga faqat nima o'ylashni bilganlardan ancha ustun qiladi.",
        "Agar qodir bo'lgandan kamroq bo'lishni rejalashtirsangiz, ehtimol umringizning barcha kunlarida baxtsiz bo'lasiz.",
        "Baxtsizlikdan yaxshiroq narsa yo'q. Har bir mag'lubiyat, har bir yurak yorilishi, har bir yo'qotish o'z ichiga — keyingi safar qanday yaxshiroq ishlashning urug'ini va darsini oladi.",
        "Nafratni sevishni o'rganing. Uni quchoqlang. Undan zavqlaning. Siz uni topganingiz. Hamma o'z fikrini bildirish huquqiga ega va hamma sizning haqingizda fikrga ega bo'lishi kerak. Nafratchilar — yaxshi muammo. Hech kim yaxshilarni yomon ko'rmaydi. Ular buyuklarni yomon ko'radi.",
        "Barcha narsalarni nazorat qila olmasligingizni qabul qiling. Nazorat ostingizdagi hamma narsa uchun javobgarlikni qabul qiling. Ichki va tashqi to'siqlar borligini qabul qiling. Ularning barchasini engishga qodir ekanligingizni qabul qiling.",
        "Tajriba — eng qiyin o'qituvchi. U avval imtihon beradi, keyin dars beradi.",
        "Biz yillar bilan emas, shikast bilan pishib boramiz.",
        "Agar tushkun bo'lsangiz, o'tmishda yashayapsiz. Agar xavotirda bo'lsangiz, kelajakda yashayapsiz. Agar tinch bo'lsangiz, hozirda yashayapsiz.",
        "Agar dunyoni o'zgartira olmaymiz desangiz, bu shunchaki siz o'zgartiradigan odamlardan emasligingizni anglatadi.",
        "Balki bu baxtli oxir haqida emas. Balki bu hikoya haqida.",
        "Ba'zi odamlar qayerga borsalar quvonch olib boradilar, ba'zi odamlar qachon ketsalar quvonch olib boradilar.",
        "Doimiy kuzating, hamma narsa o'zgarish bilan sodir bo'lishini va koinot tabiati o'zgartirishni eng ko'p sevishini o'ylab ko'ring.",
        "Juda yaxshi bo'lish zerikarli bo'lishi mumkin.",
        "Ko'pincha biz fikr qulayligidan foydalanib, fikrlash noqulayligisiz qolamiz.",
        "O'rganish fikrsiz — behuda; fikr o'rganishsiz — xavfli.",
        "Ishonchi bo'lgan bitta odam faqat fikrlari bo'lgan yuzta odamni engadi.",
        "Donolar jimirganida ahmoqlar ko'payadi.",
        "Har qanday tizimni qayta ko'rib chiqishga, har qanday usulni bekor qilishga, ishning muvaffaqiyati talab qilsa har qanday nazariyani tark etishga tayyor bo'ling.",
        "Boshqalarga rivojlanishga va hayotda muvaffaqiyatga erishishga yordam berish o'z-o'zidan mukofotdir va faqat evaziga hech narsa kutilmaganda qiymatga ega.",
        "Hozir sizda yo'q narsa haqida o'ylamang. Boringiz bilan nima qilishingiz mumkinligini o'ylang.",
        "Men hali taraqqiyotdaman, desam bo'lardi, lekin bu bir kun men endi taraqqiyotda bo'lmasligimni bildiradi.",
        "Taslim bo'lmang. Odatda eshikni ochadigan kalit halqadagi oxirgi kalit bo'ladi.",
        "Hayot o'ylaydiganlarga komediya, his qiladiganlarga tragediya.",
        "Diplomatiya — bu odamga do'zaxga borishni shunday aytish san'atiki, u sayohatni kutib qoladi.",
        "Boshqasi tomonidan qilingan noto'g'ri ishni qilingan joyida qoldiring.",
        "Butun hayotingizni birdaniga tasavvur qilib o'zingizni bezovta qilmang. Qanday azob-uqubatlar yuz berishi mumkinligini har doim o'ylamang.",
        "Har safar hamma narsani bilaman deb o'ylaganimda, \"hamma narsa\" men o'ylagandan biroz kattaroq hajmda bo'lib chiqadi.",
        "Ahmoqlik va dahiylik o'rtasidagi farq shuki, dahiylikning chegaralari bor.",
        "Bog'da jangchi bo'lish urushda bog'bon bo'lishdan yaxshiroq.",
        "Buyuk muvaffaqiyat har doim ulkan muvaffaqiyatsizlik xavfi bilan birga keladi.",
        "Muvaffaqiyat qiziquvchanlik, diqqat, qat'iyat va o'z-o'zini tanqiddan keladi.",
        "Ta'lim olgan aqlning belgisi — fikrni qabul qilmasdan o'ylash qobiliyati.",
        "Agar ular haqida hech biri hech narsa bilmasa, 10 000 odamning fikri qiymatsiz.",
        "Nazoratimizdan tashqaridagi narsalarni qanchalik ko'p qadrlantirsak, nazoratimiz shunchalik kam.",
        "Sayohatlar qiling. Sinab ko'ring. Boshqa hech narsa yo'q.",
        "Kelib chiqish muvaffaqiyatga to'siq bo'lmasligi kerak. Hayotda kamtar boshlash yordamdan ko'ra ko'proq yordam berishi mumkin.",
        "Boshqaning kamchiligi sizni kamchilikka solmasligiga yo'l qo'ymang.",
        "Bizning hasadimiz har doim hasad qilganlarimizning baxtidan uzoqroq davom etadi.",
        "Hech narsadan hech narsa chiqmaydi.",
        "Zaif odamlar qasos oladi. Kuchli odamlar kechiadi. Aqlli odamlar e'tibor bermaydi.",
        "Men shamolni boshqarmayman; men uni faqat o'rganaman.",
        "Sharaf hokimiyatni qo'lga kiritmasligi mumkin, lekin u hurmatni qozonadi. Va hurmat hokimiyat qozonadi.",
        "Yakuniy qurol — bu miya, qolganlarining barchasi qo'shimcha.",
        "Agar tez taslim bo'lish odatingizni yengmasangiz, hayotingiz hech narsaga olib kelmaydi.",
        "Mashq xuddi polni supurishga o'xshaydi. Bir marta qilganingiz uchun pol abadiy toza degan emas.",
        "Esda tutingki, azob chektiradigan biz o'zimizmiz, qiyinchilik yaratadigan biz o'zimizmiz — ya'ni fikrlarimiz. Haqoratlanishning ma'nosi nima? Toshning yoniga borib, uni haqoralang, nima erishdingiz?",
        "Maqsad bo'lmaganda, hayot hech qayerga olib bormaydigan cheksiz sayohatga aylanadi.",
        "Faqat o'lganlar urushning oxirini ko'rgan.",
        "Oldini olish davolashdan yaxshiroq.",
        "Kuch bilan o'rgatilgan hech narsa jonda qolmaydi.",
        "Hayotingizda mavjud bo'lgan hamma narsa ikkita narsa tufayli mavjud: siz qilgan narsa yoki siz qilmagan narsa.",
        "Axloqsiz odam — bu dunyoga qo'yib yuborilgan yovvoyi hayvon.",
        "O'ylash qiyin, shuning uchun ko'pchilik hukm chiqaradi.",
        "Siz irodani topmaysiz, uni yaratasiz.",
        "\"Baxtli\" so'zi g'amginlik bilan muvozanatlashtirilmaganda ma'nosini yo'qotadi.",
        "Oson hayot uchun duo qilmang. Qiyiniga bardosh berish uchun kuch so'rang.",
        "Siz bo'lishingiz mumkin bo'lgan hamma narsa emassiz va buni bilasiz.",
        "Omon qolishga band bo'lganingizda yashashni esda tuting.",
        "Rejalar hech narsa emas, rejalashtirish hamma narsa.",
        "Hayotning bir soatini behuda sarflashga jur'at etgan odam hayotning qiymatini kashf etmagan.",
        "Siz kim ekanligingizni hal qilishingiz va dunyoni o'zingiz bilan emas, sizning g'oyangiz bilan kurashishga majbur qilishingiz kerak.",
        "Yashash san'ati raqs qilishdan ko'ra ko'proq kurashga o'xshaydi, chunki u tasodifiy va kutilmagan narsalarga tayyor turadi va tushib ketishga moyil emas.",
        "Yoshim ulg'aygan sayin, odamlar nima deyishiga kam e'tibor beraman. Men faqat nima qilishlarini kuzataman.",
        "Yordam so'rashdan oldin kamarimni siqaman.",
        "Hech kim siz kabi qurilmagan, siz o'zingizni loyihalaganisiz.",
        "Jismoniy mashq masalasida hech bir erkak havaskor bo'lish huquqiga ega emas. Inson tanasi qodir bo'lgan go'zallik va kuchni ko'rmasdan qartayish uyat.",
        "Inson sokin aqlga qanchalik yaqin bo'lsa, u kuchga shunchalik yaqin.",
        "Bu kelajak uchun eslab qolish qoidasi: biror narsa sizni achchig'ingizni keltirsa, \"Bu baxtsizlik\" emas, balki \"Buni munosib tarzda ko'tarish — omad\" deb o'ylang.",
        "Biror narsada yaxshi bo'lganingizda hammaga aytasiz. Biror narsada buyuk bo'lganingizda, ular sizga aytadi.",
        "Avval sizni e'tiborsiz qoldirishadi. Keyin ustingizdan kulishadi. Keyin sizga hujum qilishadi va yondirmoqchi bo'lishadi. Keyin sizga haykallar qurishadi.",
        "Erkinlik javobgarlikni anglatadi. Shuning uchun ko'pchilik undan qo'rqadi.",
        "Haqiqatni aytsangiz, hech narsani eslab turishingiz shart emas.",
        "Vaqtingiz keladi, agar davom etsangiz.",
        "Inson qo'rqishi kerak bo'lgan narsa o'lim emas, balki hech qachon yashashni boshlamaslikdan qo'rqishi kerak.",
        "Bugungi protseduralar ertangi natijalar. Agar bugungi protseduralarni sevsangiz, ertangi natijalarni ham sevarsiz.",
        "Insoniyatning barcha muammolari odamning yolg'iz xonada jimgina o'tira olmasligidan kelib chiqadi.",
        "Hech qachon kelajak sizni bezovta qilmasin. Agar majbur bo'lsangiz, bugungi kunni himoya qilayotgan aql qurollari bilan unga duch kelasiz.",
        "Erkak yosh bilan emas, og'riq, muvaffaqiyatsizlik, rad etish, yo'qotish, hurmatisizlik va yurak yorilishi bilan pishadi.",
        "Biz hayotda taqib yurgan zanjirlarni o'zimiz yasaymiz.",
        "Biror narsani yuqori darajada qilish uchun, bu obsessiya bo'lishi kerak.",
        "Agar yaxshilanmoqchi bo'lsangiz, tashqi narsalar haqida ahmoq va nodon deb hisoblashga rozi bo'ling.",
        "Zo'ravonlik — nolayoqlarning oxirgi panohgohidir.",
        "Qo'rquv xuddi olovga o'xshaydi, agar qanday ishlatishni bilsangiz, foydali bo'lishi mumkin. Aks holda, kuyasiz.",
        "Katta muvaffaqiyatga erishish uchun katta muvaffaqiyatsizlikga tayyor bo'lishingiz kerak. Agar ikkalasini ham qila olmasangiz, muammongiz bor.",
        "Biz har doim kimdir bizni \"sabababsiz\" yoqtirmasligi haqida gapiramiz, lekin odamlar sizni \"sabababsiz\" ham yoqtiradi. Shuning uchun ikki tomondan ham ko'p hisoblamang.",
        "Qo'rqoqlar o'limidan oldin ko'p marta o'ladi; jasurlar o'limni faqat bir marta tatib ko'radi.",
        "Qaror qabul qilishdan qiyinroq, shuning uchun qimmatroq hech narsa yo'q.",
        "Bir yo'lda yuring, g'alaba bilan kibrlmang, mag'lubiyat bilan sinmang, hamma jim bo'lganda ehtiyotkorlikni unutmang va xavf tahdid qilganda qo'rqmang.",
        "Jon o'z fikrlarining rangiga bo'yaladi.",
        "Yengilroq yuk emas, kengroq yelkalar so'rayman.",
        "O'zingiz bilan muzoakara qilmang. O'zingizga ko'rsatma bering.",
        "Kuchli xarakter ham oson hayot ham xohlash mumkin emas.",
        "Jasorat — davom etish kuchi bo'lish emas, kuchingiz bo'lmaganda davom etishdir.",
        "Hayot sizga sodir bo'lmaydi, u siz ishtirokingiz bilan sodir bo'ladi.",
        "Uni g'alaba qozonish irodasi bo'lmagan urushga kirish o'limga olib keladi.",
        "Hech qachon qanchalik kuchli ekanligingizni bilmaysiz, kuchli bo'lish yagona tanlovingiz bo'lmaguncha.",
        "Hammani qoniqtira olmaysiz, ba'zan harakat qilishingiz va hamma boshqasining munosabat bildirishi kerak.",
        "\"Agar\" degan masala yo'q, masala faqat \"qachon\" — missiya haqida qat'iy bo'lganingizda.",
        "Siz o'zingiz uchun eng yaxshisini talab qilishdan oldin yana qancha kutmoqchisiz?",
        "Dunyo sizga qulaylik va'da qiladi, lekin siz qulaylik uchun emas, buyuklik uchun yaratilgansiz.",
        "Halollik tez yo'l emas, lekin ishonchli yo'l.",
        "O'zingizning eng katta muxlisigiz, eng katta ishonuvchingiz bo'ling va orqangizga yuklab, og'irlikni ko'taring.",
        "Avval o'zingizga nima bo'lishingizni ayting; keyin qilishingiz kerak bo'lgan narsani qiling.",
        "Men texnologiya inson muloqotidan oshib ketadigan kundan qo'rqaman. Dunyoda ahmoqlar avlodi paydo bo'ladi.",
        "Nimani ko'tarishingiz muhim emas, qanday ko'tarishingiz muhim.",
        "Shikastlanganlik hissingizni rad eting va shikastlanish o'zi yo'q bo'lib ketadi.",
        "Kichik rejalar tuzmang. Ularda odamlarning qonini qaynatadigan sehr yo'q va ehtimol ular o'zlari amalga oshmaydi. Katta rejalar tuzing; baland umid va ishlarda nishonga oling, esda tutingki, bir marta qayd etilgan olijanob, mantiqiy sxema hech qachon o'lmaydi, biz ketgandan keyin ham uzoq yashab, tobora ko'proq ta'kidlab turadi.",
        "Qiyinchiliklar ko'pincha oddiy odamlarni favqulodda taqdirga tayyorlaydi.",
        "Narsalarni o'zgartirmoqchi bo'lganingizda, hammani qoniqtira olmaysiz. Agar hammani qoniqtirsangiz, yetarlicha taraqqiy etmayapsiz.",
        "O'zingiz bilan muzoakara qilmang, o'zingizga ko'rsatma bering.",
        "Muvaffaqiyat yakuniy emas, muvaffaqiyatsizlik o'limga olib kelmaydi: muhim narsa davom etish jasoratidir.",
        "Agar to'g'ri bo'lmasa, qilmang; agar haqiqat bo'lmasa, aytmang.",
        "Lazzatlar ma'lum chegaradan oshganda, jazo bo'lib qoladi.",
        "Agar xohlagan narsangiz uchun qurbonlik qilmasangiz, xohlagan narsangiz qurbonlikka aylanadi.",
        "Eng katta dushmaningiz boshqarilmagan ongingiz.",
        "Hech qachon jang qilmaslik uchun jang qilishni o'rganing.",
        "Inson chuqur ma'no topa olmaganda, o'zini lazzat bilan chalg'itadi.",
        "Bu yovuz dunyoda hech narsa abadiy emas, hatto muammolarimiz ham.",
        "Ularga siz haqingizda noto'g'ri fikrda bo'lishlariga ruxsat bering. Ularga isbotlash uchun hech narsa yo'q.",
        "Agar hozirni o'tmishdan farqli qilmoqchi bo'lsangiz, o'tmishni o'rganing.",
        "Agar baxtli hayot yashashni istasangiz, uni maqsadga bog'lang, odamlarga yoki narsalarga emas.",
        "Hech qanday sir yo'q, faqat siz kashf etgan ma'lumot va hali kashf etmagan ma'lumot bor.",
        "Siz harakat qilish uchun motivatsiyaga muhtojsiz. Nimaga harakat qilishni bilish uchun ma'lumotga muhtojsiz. Motivatsiyalangan harakatlarni to'g'ri boshqaradigan ma'lumotni olish uchun qiziquvchanlikka muhtojsiz. Shuning uchun qiziquvchan bo'ling.",
        "G'olib — yana bir marta sinab ko'rgan mag'lub.",
        "Biz tanani qattiqqo'l muomala qilamiz, toki u aqlga bo'ysunmasin.",
        "Ixtiyoriylar taqdir tomonidan yetaklanadi, istaksizlar sudraladi.",
        "O'limdan qo'rqadigan odam tirik odamga munosib hech narsa qilmaydi.",
        "Qo'mondon tinchlikka shunchalik ishonmasligiki, urushga tayyorgarlikni tashlab qo'yadi.",
        "Qo'rqmang. Siz muvaffaqiyatga erishasiz, lekin har doim erishmayotgandek tuyuladi.",
        "Doimiylik zerikarliga o'xshashi mumkin, lekin buyuk bo'lish boshqa nima deb o'yladingiz? Omadmi?",
        "Yuzingizni har doim quyoshga qarating va soyalar ortingizga tushadi.",
        "Boshqarishni rad etganlarning eng og'ir jazosi — o'zidan pastroq kishi tomonidan boshqarilishdir.",
        "Ichingizni qazib oling. Ichkarida Yaxshilik manbai bor; va agar qazisangiz, u har doim qaynashga tayyor.",
        "Siz nima qilsangiz shusiz, nima qilaman deb aytsangiz o'sha emassiz.",
        "O'z yo'lida noto'g'ri yo'l tutish boshqa birovnikida to'g'ri yo'l tutishdan yaxshiroq.",
        "Buyuk odam o'ziga qattiq, zaif odam boshqalarga qattiq.",
        "O'z-o'zini sevish — umr bo'yi davom etadigan ishqiy munosabatning boshlanishi.",
        "Boshqalar nima deydi deb tashvishlanish — bu abadiy mahbuslik.",
        "Inson haqiqiy muammolardan ko'ra, haqiqiy muammolar haqidagi xayoliy xavotirlari tufayli ko'proq tashvishlanadi.",
        "Baxtli odam hozirgi vaziyatidan qoniqgan odam, nima bo'lishidan qat'i nazar.",
        "Birinchi va eng buyuk g'alaba — o'zini engish.",
        "O'zimni boshqarish uchun avval o'zimni qabul qilishim kerak, tabiatimga qarshi emas, u bilan birga harakat qilib.",
        "Odamlar ko'rsin, real odam qanday yashashi kerak bo'lganidek yashashini bilsin.",
        "O'ziga bo'ysunmaydigan odamga buyruq beriladi.",
        "Biror narsadan qo'rqsangiz, u haqida imkon qadar ko'p bilib oling. Bilim qo'rquvni yengadi.",
        "Men har doim men dunyoga qarshi deb o'ylardim, bir kun tushundim — bu faqat men o'zimga qarshi.",
        "Maqsadi bo'lmagan odam lazzat bilan chalg'iydi.",
        "Hammaning \"tushunishini\" qabul qilish qiyin, lekin shuning uchun u boshqalar uchun emas. Bu \"sizning\" ishingiz.",
        "Qiyinchilik qanchalik katta bo'lsa, uni yengishda shunchalik ko'p shon-sharaf.",
        "Biz kapalak go'zalligidan zavq olamiz, lekin kamdan-kam holda u go'zallikka erishish uchun o'tgan o'zgarishlarni tan olamiz.",
        "Agar yiqilishim kerak bo'lsa, yiqilaman. Bo'layotgan men — meni ushlaydi.",
        "Hamma narsani kechiradigan odamning ortida o'z gunohlarining og'irligini biladigan odam bor.",
        "Og'riqdan qochishga urinish ko'proq og'riq yaratadi.",
        "Haqiqiy rivojlanish qulaylikni hurmat qilmaydi.",
        "Biz bilishimiz mumkin bo'lganidan, inson mavjudligining yagona maqsadi — faqat mavjud bo'lishning zulmatida ma'no nurini yoqish.",
        "Urug' ekgan kun meva yegan kun emas.",
        "Haqiqat ko'pchilik ishonadi yoki ishonmaganligi uchun o'zgarmaydi.",
        "Yaltiroq sovutda jangchi isbotlanmagan. Menga insoniyatning yovuzlari bilan janglardan ezilgan sovutdagi jangda sinigan jangchini bering.",
        "Aql-zakovatning o'lchovi — o'zgartirish qobiliyatidir.",
        "Ochliksiz hosil yo'q.",
        "Bu aqlning o'zi aqlni yo'ldan uradiki. Aqldan bexabar bo'lmang.",
        "Siz o'zingizni xaraktarga orzu qilib bo'lmaysiz; siz uni bolg'alab, yasashingiz kerak.",
        "Hamma narsa to'g'ri bo'lishidan oldin ko'p narsa noto'g'ri bo'ladi.",
        "Biz faqat hozir yashaymiz. Qolgan hamma narsa yoki o'tib ketgan yoki noma'lum.",
        "Siz g'azabingiz uchun jazolanmaysiz, g'azabingiz tomonidan jazolanasiz.",
        "Siz suzishni suv haqida o'qib o'rganmaysiz.",
        "Eng qiyin tanlovlar eng kuchli irodani talab qiladi.",
        "Eng avvalo, o'zingizga yolg'on gapirmang.",
        "Tanangiz deyarli hamma narsaga bardosh bera oladi; ishontirish kerak bo'lgan aqldir.",
        "Hayot birinchi shaxs janridadir. Unga shunday munosabatda bo'ling.",
        "Yaxshi yetakchilar bahona qilmaydi. Buning o'rniga ular buni qanday qilish kerakligini aniqlaydi.",
        "Boshqalardan ko'ra ko'proq vaqt ketganligi muvaffaqiyatsiz bo'ldingiz degani emas.",
        "O'zingizni qanchalik ko'p bilsangiz, boshqalarning ma'qullashiga shunchalik kam muhtojsiz.",
        "O'zini bilish — barcha donolikning boshlanishi.",
        "Muhim narsa odamning kattaligi emas, balki yuragining kattaligi.",
        "Ko'z yoshlarsiz daraja o'zgartirish qiyin.",
        "Mavjud omoch bilan haydaysiz.",
    ]
}
