// QuotesLang_fr.swift
// Spike AI — Bundled quote translations
import Foundation
enum QuotesLang_fr {
    static let quotes: [String] = [
        "Ce que vous maintenez dans votre esprit de manière constante est exactement ce que vous vivrez dans la vie.",
        "Nous visons au-dessus de la cible pour atteindre la cible.",
        "Le pire que je puisse être, c'est être comme tout le monde, je déteste ça.",
        "Seuls ceux qui osent aller trop loin peuvent découvrir jusqu'où on peut aller.",
        "Saute et le filet apparaîtra.",
        "Un navire au port est en sécurité, mais ce n'est pas pour cela que les navires sont construits.",
        "Ne t'inquiète pas des échecs, inquiète-toi des chances que tu rates quand tu n'essaies même pas.",
        "Ceux qui osent échouer lamentablement peuvent accomplir de grandes choses.",
        "La façon de commencer est d'arrêter de parler et de se mettre à agir.",
        "Nous pouvons rencontrer de nombreuses défaites, mais nous ne devons pas être vaincus.",
        "La vraie mesure d'un homme est la façon dont il traite quelqu'un qui ne peut absolument rien pour lui.",
        "Il faut faire attention si tu ne sais pas où tu vas, parce que tu pourrais ne pas y arriver.",
        "Tu dois attendre de grandes choses de toi-même avant de pouvoir les accomplir.",
        "Ne laisse jamais tes décisions passées déterminer ton résultat futur.",
        "Les raccourcis causent de longs retards.",
        "Personne ne peut te donner tes objectifs. C'est ton voyage.",
        "Le monde est ce que tu en penses, alors penses-y différemment et ton monde changera.",
        "L'avenir appartient à ceux qui s'y préparent aujourd'hui.",
        "Ne renonce pas à ce que tu veux le plus pour ce que tu veux maintenant.",
        "Ne me dis pas à quel point tu es talentueux, dis-moi à quel point tu travailles dur.",
        "La façon dont tu penses quand tu perds détermine combien de temps il te faudra pour gagner.",
        "Chaque fois qu'une personne décide qu'elle a atteint le succès, le progrès s'arrête.",
        "Aucun problème ne peut résister à l'assaut d'une réflexion soutenue.",
        "La chance, c'est quand une opportunité se présente et que vous y êtes préparé.",
        "Le secret pour avancer, c'est de commencer.",
        "Le meilleur moment pour planter un arbre, c'était il y a 20 ans. Le deuxième meilleur moment, c'est maintenant.",
        "C'est difficile de battre une personne qui n'abandonne jamais.",
        "Écris-le. Filme-le. Publie-le. Tricote-le, fais-le sauter. Peu importe, crée !",
        "Quoi que tu sois, sois-le bien.",
        "Le bonheur n'est pas quelque chose de tout fait, il vient de tes propres actions.",
        "Les gens intelligents apprennent de tout et de tout le monde.",
        "Impossible n'est qu'une opinion.",
        "Ta passion attend que ton courage la rattrape.",
        "Les gens qui se demandent si le verre est à moitié vide ou plein passent à côté de l'essentiel. Le verre est rechargeable.",
        "Un jour ou le jour un ; tu décides.",
        "Les choses peuvent venir à ceux qui attendent, mais seulement celles laissées par ceux qui se démènent.",
        "Tout vient à celui qui travaille en attendant.",
        "Travaille comme si quelqu'un travaillait 24 heures sur 24 pour te l'enlever.",
        "Personne n'a fait de différence en étant comme tout le monde.",
        "Tu auras des mauvais moments, mais ils te réveilleront toujours aux bonnes choses auxquelles tu ne prêtais pas attention.",
        "Sois une version de première classe de toi-même, pas une version de seconde classe de quelqu'un d'autre.",
        "Apprends des erreurs des autres. Tu ne peux pas vivre assez longtemps pour les commettre toutes toi-même.",
        "Si tu es fatigué, alors fais-le fatigué.",
        "Un homme n'est pas fini quand il est vaincu, il est fini quand il abandonne.",
        "Le monde est changé par ton exemple, pas par ton opinion.",
        "La vie, c'est comme faire du vélo. Pour garder l'équilibre, il faut continuer à avancer.",
        "En pensant à la vie : aucune quantité de culpabilité ne peut changer le passé, aucune quantité d'anxiété ne peut changer l'avenir.",
        "Un esprit négatif ne te donnera jamais une vie positive.",
        "Tout est difficile avant d'être facile.",
        "Prends le risque ou perds la chance.",
        "N'arrête jamais d'apprendre, car la vie n'arrête jamais d'enseigner.",
        "L'homme qui ne lit pas n'a aucun avantage sur celui qui ne sait pas lire.",
        "Une personne qui n'a jamais fait d'erreur n'a jamais rien tenté de nouveau.",
        "La façon la plus courante dont les gens renoncent à leur pouvoir est de penser qu'ils n'en ont pas.",
        "Sois reconnaissant pour ce que tu as ; tu finiras par en avoir plus. Concentre-toi sur ce que tu n'as pas et tu n'en auras jamais assez.",
        "La chose la plus difficile est la décision d'agir, le reste n'est que de la ténacité.",
        "Beaucoup d'échecs dans la vie sont le fait de personnes qui ne réalisaient pas à quel point elles étaient proches quand elles ont abandonné.",
        "Ce n'est pas de savoir si on te met à terre, c'est de savoir si tu te relèves.",
        "Le pessimiste voit la difficulté dans chaque opportunité. L'optimiste voit l'opportunité dans chaque difficulté.",
        "Notre plus grande gloire n'est pas de ne jamais tomber, mais de nous relever à chaque chute.",
        "Ne te laisse pas pousser par les peurs dans ton esprit ; laisse-toi guider par les rêves dans ton cœur.",
        "Quand tu sais ce que tu veux et que tu le veux assez fort, tu trouveras un moyen de l'obtenir.",
        "Commence par faire le nécessaire, puis fais le possible, et soudain tu fais l'impossible.",
        "Sans passion tu n'as pas d'énergie, sans énergie tu n'as rien.",
        "Tu n'as pas besoin d'être grand pour commencer, mais tu dois commencer pour devenir grand.",
        "La force ne vient pas de la capacité physique, elle vient d'une volonté indomptable.",
        "Personne n'est inutile dans ce monde s'il allège le fardeau d'un autre.",
        "En demandant l'impossible, nous obtenons le possible.",
        "Mieux vaut être lion un jour que mouton toute sa vie.",
        "La vie est trop importante pour être prise au sérieux.",
        "Le commencement est la moitié de toute action.",
        "La patience infinie produit des résultats immédiats.",
        "Presque tous les hommes meurent de leurs remèdes et non de leurs maladies.",
        "Ils sont capables, parce qu'ils croient qu'ils sont capables.",
        "L'imagination est plus importante que le savoir.",
        "Les personnes persévérantes commencent leur succès là où les autres terminent en échec.",
        "Il n'y a pas de chemins clairs. Seulement des pièges, des fils-pièges et de l'obscurité.",
        "Une erreur prouve que quelqu'un a arrêté de parler assez longtemps pour faire quelque chose.",
        "Ce qui vaut la peine d'être fait mérite d'être bien fait.",
        "Le plus puissant est celui qui a pouvoir sur lui-même.",
        "Un érudit qui chérit l'amour du confort n'est pas digne d'être appelé érudit.",
        "La prospérité dépend davantage de vouloir ce que l'on a que d'avoir ce que l'on veut.",
        "Chaque jour vient avec ses propres cadeaux, dénoue les rubans.",
        "Le succès n'est jamais permanent et l'échec n'est jamais définitif.",
        "Rien ne dure éternellement, pas même tes problèmes.",
        "Le travail acharné ne garantit pas le succès, mais en améliore les chances.",
        "La paix ne peut être maintenue par la force. Elle ne peut être atteinte que par la compréhension.",
        "Qui ne se risque pas n'a pas de chance.",
        "Ne dis pas quand j'aurai du temps libre j'étudierai, tu pourrais ne pas avoir de temps libre.",
        "Celui qui perd la foi perd tout.",
        "Sa propre pensée est son monde. Ce qu'une personne pense, c'est ce qu'elle devient.",
        "L'aventure n'est pas en dehors de l'homme, elle est en lui.",
        "Le jeu de la vie ne consiste pas tant à avoir une bonne main qu'à bien jouer une mauvaise main.",
        "Aigre, doux, amer, piquant ; tout doit être goûté.",
        "Ne laisse jamais le sentiment d'un échec passé vaincre ton prochain pas.",
        "À moins d'être ambitieux, on ne progresse pas.",
        "L'avenir appartient à ceux qui osent.",
        "Les faits ne cessent pas d'exister parce qu'on les ignore.",
        "Nous ne devons jamais supposer ce qui est incapable de preuve.",
        "Une voix forte ne peut rivaliser avec une voix claire, même si c'est un murmure.",
        "Agis comme si tu t'attendais à atteindre la zone d'en-but.",
        "Le bonheur est la fleur naturelle du devoir.",
        "\"Non\" signifie simplement recommencer à un niveau supérieur.",
        "L'enthousiasme fait bouger le monde.",
        "Un champion est quelqu'un qui se relève quand il ne peut plus.",
        "Les obstacles sont le prix de la grandeur.",
        "La question n'est pas qui va me laisser faire, c'est qui va m'arrêter.",
        "Je n'étais pas là pour participer, j'étais là pour gagner.",
        "Arrête de te plaindre, commence à travailler dur.",
        "Des difficultés naissent les miracles.",
        "Je n'ai pas peur, je suis née pour faire cela.",
        "Ne baisse jamais la tête. Tiens-la haute. Regarde le monde droit dans les yeux.",
        "Fais ce que tu dois faire jusqu'à ce que tu puisses faire ce que tu veux faire.",
        "Si tu es tombé hier, relève-toi aujourd'hui.",
        "Fais de chaque jour ton chef-d'œuvre.",
        "Du sang, de la sueur et du respect. Les deux premiers, tu les donnes, le dernier, tu le gagnes.",
        "Sois si bon qu'ils ne puissent pas t'ignorer.",
        "Montre au monde à quel point tu te battras pour le cercle des gagnants.",
        "Si tu ne conçois pas ton propre plan de vie, tu risques de tomber dans celui de quelqu'un d'autre. Qu'est-ce qu'ils ont prévu pour toi ? Pas grand-chose.",
        "La seule personne que tu es destiné à devenir est celle que tu décides d'être.",
        "N'attends pas que le fer soit chaud pour frapper ; rends-le chaud en frappant.",
        "Je ne peux pas croire que Dieu nous a mis sur cette terre pour être ordinaires.",
        "Je veux que le monde soit meilleur parce que j'ai été là.",
        "L'habitude de la persévérance est l'habitude de la victoire.",
        "N'aie pas peur d'abandonner le bien pour viser le grandiose.",
        "Fais ton devoir et un peu plus, et l'avenir prendra soin de lui-même.",
        "La vie a une façon de tester la volonté d'une personne, soit parce que rien ne se passe, soit parce que tout arrive en même temps.",
        "Un homme sage peut toujours être trouvé seul. Un homme faible peut toujours être trouvé dans une foule.",
        "Oser, c'est perdre pied momentanément. Ne pas oser, c'est se perdre soi-même.",
        "La peur vainc plus de gens que n'importe quoi d'autre au monde.",
        "Les mots les plus puissants de l'univers sont ceux que tu utilises pour te parler à toi-même.",
        "La seule chose qui vient à un homme endormi, ce sont les rêves.",
        "Si tu ne te conquiers pas toi-même, tu seras conquis par toi-même.",
        "Un héros est celui qui sait tenir bon une minute de plus.",
        "Va aussi loin que tu peux voir, quand tu y seras tu pourras voir plus loin.",
        "Tu ne découvres pas ta place dans le monde, tu la tailles.",
        "Les gagnants se concentrent sur la victoire. Les perdants se concentrent sur les gagnants.",
        "L'échec ne me rattrapera jamais si ma détermination à réussir est assez forte.",
        "Ce qui vient facilement ne dure pas. Ce qui dure ne vient pas facilement.",
        "Pour éviter la critique : ne dis rien, ne fais rien, ne sois rien.",
        "L'homme qui fait plus que ce pour quoi il est payé sera bientôt payé pour plus qu'il ne fait.",
        "Le génie commence les grandes œuvres, seul le travail les achève.",
        "Même si tu es sur la bonne voie, tu te feras écraser si tu restes assis là.",
        "Si les choses n'échouent pas, tu n'innoves pas assez.",
        "Tu obtiens le meilleur des autres quand tu donnes le meilleur de toi-même.",
        "Le leadership est une action, pas une position.",
        "Notre travail est la présentation de nos capacités.",
        "Tous mes problèmes s'inclinent devant mon entêtement.",
        "Porte ton échec comme un insigne d'honneur.",
        "Nous sommes limités non par nos capacités, mais par notre vision.",
        "Si tu es fatigué, apprends à te reposer, pas à abandonner.",
        "Tomber est un accident, rester à terre est un choix.",
        "N'ose pas abandonner cette vie. Pas ce soir. Pas demain. Jamais.",
        "Ne te laisse jamais abattre par des personnes ou des événements.",
        "Certains rêvent de succès tandis que d'autres se réveillent et travaillent dur pour y parvenir.",
        "La confiance vient de l'expérience. Les expériences viennent d'essayer, d'échouer et de réessayer, cette fois en mieux.",
        "Le temps qui mène à la maîtrise dépend de l'intensité de notre concentration.",
        "Le succès ne vient qu'à ceux qui osent tenter.",
        "Une clé importante du succès est la confiance en soi. Une clé importante de la confiance en soi est la préparation.",
        "Le doute tue plus de rêves que l'échec n'en tuera jamais.",
        "La victoire est toujours possible pour celui qui refuse de cesser de se battre.",
        "Tu ne changeras jamais ta vie tant que tu ne changeras pas quelque chose que tu fais quotidiennement.",
        "Pour réussir, ta concentration doit être si intense que les autres te croient fou.",
        "Les obstacles sont ces choses effrayantes que tu vois quand tu détournes les yeux de ton objectif.",
        "Trouver une opportunité est une question de croire qu'elle est là.",
        "Se fixer des objectifs est la première étape pour transformer l'invisible en visible.",
        "Si tu ne risques rien, tu risques tout.",
        "Si tu ne peux pas changer ta situation, change ta mentalité.",
        "Peu importe à quel point le passé a été difficile, tu peux toujours recommencer.",
        "Si tu n'oses rien, alors quand la journée sera finie, rien sera tout ce que tu auras gagné.",
        "Bien souvent, un changement de soi est plus nécessaire qu'un changement de décor.",
        "La peur est le plus grand handicap de tous et elle te paralysera.",
        "Ce qui est dangereux, c'est de ne pas évoluer.",
        "D'une façon ou d'une autre, je trouverai un chemin ou j'en créerai un.",
        "Le seul moyen de faire taire tout le monde, c'est de gagner.",
        "Ne laisse jamais l'acceptable être suffisant.",
        "À long terme, on n'atteint que ce que l'on vise.",
        "L'amélioration continue vaut mieux que la perfection retardée.",
        "Si tu le vois dans ton esprit, tu le tiendras dans ta main.",
        "Aujourd'hui, je ferai ce que les autres ne feront pas, pour que demain je puisse faire ce que les autres ne peuvent pas.",
        "L'excellence est un art gagné par l'entraînement et l'habitude.",
        "L'année prochaine va passer que tu fasses quelque chose de ta vie ou non.",
        "Ne t'arrête pas quand tu es fatigué, arrête-toi quand tu as fini.",
        "Tu n'es qu'à un entraînement d'une bonne humeur.",
        "Fais ce qui est juste, pas ce qui est facile ni ce qui est populaire.",
        "Rien de grand n'est jamais venu facilement.",
        "Sans lutte, il ne peut y avoir de progrès.",
        "Les personnes qui réussissent posent de meilleures questions et obtiennent de meilleures réponses.",
        "Je n'ai pas de talents spéciaux, je suis seulement passionnément curieux.",
        "La meilleure leçon que j'ai apprise dans la vie est venue du pire sentiment que j'ai ressenti.",
        "Les défis sont ce qui rend la vie intéressante. Les surmonter est ce qui lui donne un sens.",
        "Apprends à être heureux avec l'approche sans fin d'essayer, échouer et apprendre.",
        "Si tu fermes la porte à toutes les erreurs, la vérité sera exclue.",
        "Oublie l'erreur, retiens la leçon.",
        "Si tu ne peux faire que ce que tu sais déjà faire, tu ne seras jamais plus que ce que tu es maintenant.",
        "Qui est sage ? Celui qui apprend de tous.",
        "Seul moi peux changer ma vie, personne ne peut le faire pour moi.",
        "La persévérance, c'est échouer 19 fois et réussir la 20e.",
        "J'attribue mon succès à ceci : je n'ai jamais donné ni accepté d'excuse.",
        "Je ne suis pas le produit de mes circonstances. Je suis le produit de mes décisions.",
        "Nos actes nous déterminent autant que nous déterminons nos actes.",
        "Seuls les extrêmement ignorants ou les extrêmement intelligents peuvent résister au changement.",
        "L'homme qui a confiance en lui gagne la confiance des autres.",
        "Ce que tu cherches te cherche aussi.",
        "Ne t'inquiète pas de l'échec. Tu n'as besoin d'avoir raison qu'une seule fois.",
        "La sécurité est principalement une superstition. La vie est soit une aventure audacieuse, soit rien.",
        "Nous devenons ce à quoi nous pensons le plus souvent, et c'est le secret le plus étrange.",
        "La façon de commencer est d'arrêter de parler et de se mettre à agir.",
        "Fais de chaque jour ton chef-d'œuvre.",
        "Peu importe combien d'erreurs tu fais ou la lenteur de tes progrès, tu es toujours bien en avance sur tous ceux qui n'essaient pas.",
        "C'est notre attitude au début d'une tâche difficile qui, plus que tout, affectera son résultat.",
        "La seule vraie sécurité qu'un homme aura dans ce monde est une réserve de savoir, d'expérience et de compétence.",
        "Ce que tu fais aujourd'hui peut changer tous les lendemains de ta vie.",
        "Ta vie ne s'améliore pas par hasard, elle s'améliore par le changement.",
        "Un rêve ne devient pas réalité par magie, il faut de la sueur, de la détermination et du travail acharné.",
        "Le savoir, c'est savoir qu'une tomate est un fruit. La sagesse, c'est ne pas la mettre dans une salade de fruits.",
        "Quelle que soit la situation, rappelle-toi : \"J'ai le choix\".",
        "Maîtrise ton esprit ou il te maîtrisera.",
        "Certains réussissent parce qu'ils y sont destinés, mais la plupart réussissent parce qu'ils y sont déterminés.",
        "Les grandes opportunités ne se voient pas avec les yeux, elles se voient avec l'esprit.",
        "Celui qui n'a pas le courage de prendre des risques n'accomplira rien dans la vie.",
        "Savoir ne suffit pas, nous devons appliquer. Vouloir ne suffit pas, nous devons agir.",
        "L'ambition est le chemin vers le succès, la persévérance est le véhicule dans lequel tu arrives.",
        "La clé de la vie est d'accepter les défis. Quand on cesse de le faire, on est mort.",
        "L'engagement est ce qui transforme une promesse en réalité.",
        "La confiance en soi est la mémoire du succès.",
        "Sans confiance en soi, nous sommes comme des bébés dans un berceau.",
        "Ose rêver, mais plus important encore, ose mettre de l'action derrière tes rêves.",
        "L'honnêteté est le premier chapitre du livre de la sagesse.",
        "L'excellence est un processus continu et non un accident.",
        "L'espoir, c'est pouvoir voir qu'il y a de la lumière malgré toute l'obscurité.",
        "Nous devons accepter une déception finie, mais ne jamais perdre un espoir infini.",
        "Le vrai signe de l'intelligence n'est pas le savoir, mais l'imagination.",
        "Deviens accro à l'amélioration constante et sans fin de toi-même.",
        "Le génie, c'est un pour cent d'inspiration et quatre-vingt-dix-neuf pour cent de transpiration.",
        "Tu ne peux pas attendre l'inspiration, il faut la poursuivre avec un gourdin.",
        "Aie patience. Toutes les choses sont difficiles avant de devenir faciles.",
        "La personne qui dit que ça ne peut pas être fait ne devrait pas interrompre celle qui est en train de le faire.",
        "La persévérance est le travail dur que tu fais après t'être fatigué du travail dur que tu as déjà fait.",
        "Un homme sage peut apprendre plus d'une question bête qu'un fou d'une réponse sage.",
        "Par l'autodiscipline et la maîtrise de soi constantes, tu peux développer la grandeur de caractère.",
        "La maîtrise émotionnelle de soi est le résultat d'un travail acharné, pas une compétence innée.",
        "Apprendre à apprendre est la compétence la plus importante de la vie.",
        "Ne laisse pas ce que tu ne peux pas faire t'empêcher de faire ce que tu peux.",
        "Tu passes toujours par l'échec en chemin vers le succès.",
        "Personne n'est parfait, c'est pourquoi les crayons ont des gommes.",
        "Ne laisse jamais les probabilités t'empêcher de faire ce que tu sais dans ton cœur que tu étais destiné à faire.",
        "Si tu regardes vraiment de près, la plupart des succès du jour au lendemain ont pris beaucoup de temps.",
        "Tout est possible. Tout peut être.",
        "Rien n'est particulièrement difficile si tu le décomposes en petites tâches.",
        "Le secret du succès est de faire les choses ordinaires extraordinairement bien.",
        "Agis comme si ce que tu fais fait une différence, car c'est le cas.",
        "Ce que tu obtiens en atteignant tes objectifs n'est pas aussi important que ce que tu deviens en les atteignant.",
        "La vie est comme faire du vélo ; pour garder l'équilibre, tu dois continuer à avancer.",
        "Limite tes \"toujours\" et tes \"jamais\".",
        "Tu n'es jamais trop vieux pour te fixer un nouvel objectif ou rêver un nouveau rêve.",
        "Tu ne trouves pas la vie heureuse, tu la crées.",
        "La mauvaise nouvelle, c'est que le temps file. La bonne nouvelle, c'est que tu es le pilote.",
        "Garde toujours ton visage tourné vers le soleil et les ombres tomberont derrière toi.",
        "La différence entre l'impossible et le possible réside dans la détermination d'un homme.",
        "Les médailles d'or ne sont pas vraiment faites d'or. Elles sont faites de sueur, de détermination et d'un alliage rare appelé courage.",
        "Ne sous-estime pas la détermination d'un homme tranquille.",
        "Ne me dis pas en quoi tu crois. J'observerai comment tu te comportes et je tirerai mes propres conclusions.",
        "Je déteste simplement perdre et cela te donne une détermination supplémentaire pour travailler plus dur.",
        "La détermination de gagner est la meilleure partie de la victoire.",
        "Tu peux avoir tout le talent du monde, mais sans détermination tu n'iras pas très loin.",
        "La victoire est l'enfant de la préparation et de la détermination.",
        "Le jeune homme connaît les règles, mais le vieil homme connaît les exceptions.",
        "Le pessimiste se plaint du vent, l'optimiste espère qu'il changera, le réaliste ajuste les voiles.",
        "Le savoir n'a aucune valeur si tu ne le mets pas en pratique.",
        "Je préfère regretter les choses que j'ai faites que regretter celles que je n'ai pas faites.",
        "Il faut de la sagesse pour comprendre la sagesse. La musique n'est rien si l'auditoire est sourd.",
        "Le plus grand danger pour la plupart d'entre nous n'est pas que notre objectif soit trop élevé et que nous le manquions, mais qu'il soit trop bas et que nous l'atteignions.",
        "Dans chaque promenade avec la nature, on reçoit bien plus que ce que l'on cherche.",
        "Je ne suivrai pas là où le chemin peut mener, j'irai là où il n'y a pas de chemin et je laisserai une trace.",
        "Le puissant chêne d'aujourd'hui n'est que la noix d'hier qui a tenu bon.",
        "Être entièrement honnête avec soi-même est un bon exercice.",
        "Nous ne pouvons pas devenir ce que nous devons être en restant ce que nous sommes.",
        "Fixe ton cap sur les étoiles, pas sur les lumières de chaque navire qui passe.",
        "Si tu ne sais pas où tu vas, n'importe quel chemin t'y mènera.",
        "Tu auras toujours deux choix : ton engagement ou ta peur.",
        "Bénis soient ceux qui donnent sans se souvenir et reçoivent sans oublier.",
        "Ce qui arrive n'est pas aussi important que la façon dont tu réagis à ce qui arrive.",
        "Commence par ce qui est juste plutôt que par ce qui est acceptable.",
        "L'homme supérieur se blâme lui-même. L'homme inférieur blâme les autres.",
        "La plus petite action vaut mieux que la plus grande intention.",
        "Le plus grand obstacle à la découverte n'est pas l'ignorance, c'est l'illusion de la connaissance.",
        "Méfie-toi du faux savoir, il est plus dangereux que l'ignorance.",
        "La meilleure façon de prédire l'avenir est de l'inventer.",
        "Vaincre sans risque, c'est triompher sans gloire.",
        "Notre caractère, c'est ce que nous faisons quand nous pensons que personne ne regarde.",
        "Tout ce qui nous irrite chez les autres peut nous amener à nous comprendre nous-mêmes.",
        "L'art d'être sage est l'art de savoir quoi ignorer.",
        "Dis-moi et j'oublie. Enseigne-moi et je me souviens. Implique-moi et j'apprends.",
        "Tu as un cerveau dans ta tête. Tu as des pieds dans tes chaussures. Tu peux te diriger dans n'importe quelle direction que tu choisis.",
        "En trois mots, je peux résumer tout ce que j'ai appris sur la vie : elle continue.",
        "La vie, c'est essayer des choses pour voir si elles marchent.",
        "Le succès vient généralement à ceux qui sont trop occupés pour le chercher.",
        "Je n'ai pas échoué, j'ai simplement trouvé 10 000 façons qui ne marchent pas.",
        "J'ai échoué mon chemin vers le succès.",
        "Si tu ne te programmes pas toi-même, la vie te programmera.",
        "Je n'ai pas le temps de m'apitoyer sur moi-même. Je n'ai pas le temps de me plaindre. Je vais continuer à avancer.",
        "Si tu n'es pas prêt à risquer l'habituel, tu devras te contenter de l'ordinaire.",
        "Le succès a été défini comme la capacité d'aller d'échec en échec sans perdre son enthousiasme.",
        "Tous nos rêves peuvent se réaliser si nous avons le courage de les poursuivre.",
        "Les opportunités ne se présentent pas, tu les crées.",
        "Je n'ai jamais rêvé de succès, j'ai travaillé pour l'obtenir.",
        "Ne laisse pas ce que tu ne peux pas faire interférer avec ce que tu peux faire.",
        "Aujourd'hui est le seul jour, hier est parti.",
        "Les choses marchent mieux pour ceux qui tirent le meilleur parti de la façon dont les choses marchent.",
        "Si tu traverses l'enfer, continue d'avancer.",
        "Tu ne vois que les gloires publiques, jamais les sacrifices privés pour les atteindre.",
        "Si tu ne valorises pas ton temps, les autres non plus.",
        "Personne ne peut te faire sentir inférieur sans ton consentement.",
        "Un homme qui réussit est celui qui peut construire des fondations solides avec les briques que les autres lui ont lancées.",
        "Ce qui nous semble une épreuve amère est souvent une bénédiction déguisée.",
        "Rien au monde n'est plus commun que des gens sans succès qui ont du talent.",
        "N'essaie pas de devenir une personne de succès, mais plutôt une personne de valeur.",
        "Si tu ne peux pas l'expliquer simplement, tu ne le comprends pas assez bien.",
        "Tu n'échoues jamais tant que tu n'arrêtes pas d'essayer.",
        "Le savoir, c'est être conscient de ce que tu peux faire. La sagesse, c'est savoir quand ne pas le faire.",
        "La vie ne consiste pas à se trouver. La vie consiste à se créer.",
        "Le problème n'est pas le problème, le problème c'est ton attitude face au problème.",
        "Aucun chef-d'œuvre n'a jamais été créé par un artiste paresseux.",
        "Le chemin du succès et le chemin de l'échec sont presque exactement les mêmes.",
        "Ce n'est pas ce que tu regardes qui compte, c'est ce que tu vois.",
        "Le courage est la résistance à la peur, la maîtrise de la peur, pas l'absence de peur.",
        "Je trouve que plus je travaille dur, plus j'ai de chance.",
        "L'éclat d'une pensée chaleureuse vaut plus pour moi que de l'argent.",
        "Tout progrès se fait en dehors de la zone de confort.",
        "La pensée devrait devenir ton principal atout, quels que soient les hauts et les bas que tu rencontres dans la vie.",
        "Le succès est la somme de petits efforts répétés jour après jour.",
        "Le guerrier qui réussit est l'homme moyen avec une concentration de laser.",
        "Le succès ne consiste pas à ne jamais faire d'erreurs, mais à ne jamais faire la même une seconde fois.",
        "Ne laisse pas la peur de perdre être plus grande que l'excitation de gagner.",
        "Le premier pas, c'est quand tu refuses d'être captif de ton environnement.",
        "Il n'y a pas d'embouteillage sur le kilomètre supplémentaire.",
        "Chaque fois que tu te retrouves du côté de la majorité, il est temps de faire une pause et de réfléchir.",
        "Le succès, c'est s'aimer soi-même, aimer ce qu'on fait, et aimer la façon dont on le fait.",
        "Un objectif n'est pas toujours destiné à être atteint, il sert souvent simplement de point de mire.",
        "Mieux vaut échouer dans l'originalité que réussir dans l'imitation.",
        "La motivation est ce qui te fait commencer, l'habitude est ce qui te fait continuer.",
        "Tu dois te lever chaque matin avec détermination si tu veux te coucher avec satisfaction.",
        "Tu dois attendre de grandes choses de toi-même avant de pouvoir les accomplir.",
        "Les vraies difficultés peuvent être surmontées, seules les imaginaires sont invincibles.",
        "Les gens réussissent rarement s'ils ne s'amusent pas dans ce qu'ils font.",
        "C'est dans nos moments les plus sombres que nous devons nous concentrer pour voir la lumière.",
        "L'échec est le condiment qui donne sa saveur au succès.",
        "Les esprits sont domptés et soumis par le malheur, mais les grands esprits s'élèvent au-dessus.",
        "Tu devras peut-être livrer une bataille plus d'une fois pour la gagner.",
        "Que ferais-tu si tu n'avais pas peur ?",
        "Les bonnes choses viennent à ceux qui attendent, mais les meilleures viennent à ceux qui vont les chercher.",
        "Fais toujours un effort total, même quand les chances sont contre toi.",
        "N'attends pas que tes sentiments changent pour agir, agis et tes sentiments changeront.",
        "L'action ne mène pas toujours au bonheur, mais il n'y a pas de bonheur sans action.",
        "La perfection est ennuyeuse, s'améliorer est là où se trouve tout le plaisir.",
        "C'est difficile de battre une personne qui n'abandonne jamais.",
        "La différence entre un obstacle et un tremplin, c'est la hauteur à laquelle tu lèves le pied.",
        "N'abandonne jamais car c'est justement le moment et l'endroit où la marée va tourner.",
        "Parfois, ne pas obtenir ce que tu veux est un merveilleux coup de chance.",
        "Je ne peux pas changer la direction du vent, mais je peux ajuster mes voiles pour toujours atteindre ma destination.",
        "Avance. Ne t'arrête pas, ne t'attarde pas dans ton voyage, mais lutte pour la marque fixée devant toi.",
        "Si tu veux vraiment quelque chose, ne l'attends pas, apprends-toi à être impatient.",
        "Parfois tu gagnes, parfois tu apprends.",
        "Deux types de personnes dans ce monde : celles qui veulent faire avancer les choses et celles qui ne veulent pas faire d'erreurs.",
        "Assure-toi que ton pire ennemi ne vit pas entre tes deux oreilles.",
        "Rappelle-toi toujours que tu es absolument unique, tout comme tout le monde.",
        "Si tu as tout sous contrôle, tu ne vas pas assez vite.",
        "Un moyen de maintenir l'élan est d'avoir des objectifs constamment plus grands.",
        "Tu n'as pas besoin de voir tout l'escalier, fais juste le premier pas.",
        "Ce qui nous semble une épreuve amère est souvent une bénédiction déguisée.",
        "Deux options concernant l'engagement : tu es dedans ou tu es dehors, il n'y a pas de vie entre les deux.",
        "Quand tu veux quelque chose, tout l'univers conspire à t'aider à l'obtenir.",
        "Le bonheur n'est pas quelque chose de tout fait, il vient de tes propres actions.",
        "Quoi que tu sois, sois-le bien.",
        "La douleur est inévitable, la souffrance est optionnelle.",
        "Le talent atteint une cible que personne d'autre ne peut atteindre ; le génie atteint une cible que personne d'autre ne peut voir.",
        "L'esprit est son propre lieu et en lui-même peut faire un ciel de l'enfer ou un enfer du ciel.",
        "Je détestais l'entraînement, mais je me suis dit \"n'abandonne pas\" : souffre maintenant et vis le reste de ta vie en champion.",
        "Ce ne sont pas les montagnes à gravir qui t'épuisent, c'est le caillou dans ta chaussure.",
        "Ce que nous pensons, nous le devenons.",
        "Quelqu'un est assis à l'ombre aujourd'hui parce que quelqu'un a planté un arbre il y a longtemps.",
        "Un seul rayon de soleil suffit à chasser bien des ombres.",
        "Pour l'esprit qui est calme, tout l'univers se rend.",
        "Avec l'autodiscipline, presque tout est possible.",
        "La meilleure sortie passe toujours par le milieu.",
        "Ta grande opportunité est peut-être juste là où tu es maintenant.",
        "Rien ne vaut plus que ce jour.",
        "Le seul voyage est celui qui est intérieur.",
        "Les circonstances ne déterminent pas où tu peux aller, elles déterminent simplement d'où tu pars.",
        "La croyance crée le fait réel.",
        "Ce qui rend le désert beau, c'est qu'il cache un puits quelque part.",
        "Si les portes de la perception étaient nettoyées, tout apparaîtrait à l'homme tel qu'il est : infini.",
        "Change tes pensées et tu changeras ton monde.",
        "L'oiseau est propulsé par sa propre vie et par sa motivation.",
        "Donne de la lumière et les gens trouveront le chemin.",
        "La meilleure préparation pour demain est de faire de ton mieux aujourd'hui.",
        "Les idées façonnent le cours de l'histoire.",
        "Ce n'est pas sur un seul fil que sont enfilés tous les joyaux de la vie.",
        "Ce que nous accomplissons intérieurement changera la réalité extérieure.",
        "Ta propre résolution vers le succès est plus importante que toute autre chose.",
        "Tu sais que tu es sur la voie du succès si tu ferais ton travail même sans être payé.",
        "Tu deviens ce que tu crois.",
        "Si tu veux atteindre l'excellence, tu peux y arriver aujourd'hui. À partir de cette seconde, arrête de faire un travail de qualité inférieure.",
        "Si tu n'es pas prêt à risquer l'habituel, tu devras te contenter de l'ordinaire.",
        "Avant tout, la préparation est la clé du succès.",
        "J'ai appris au fil des années que lorsqu'on a l'esprit décidé, la peur diminue.",
        "La vie est faite de très nombreuses séparations soudées ensemble.",
        "Gagner n'est pas tout, mais vouloir gagner l'est.",
        "Tu peux être déçu si tu échoues, mais tu es condamné si tu n'essaies pas.",
        "Les erreurs font partie de la vie, c'est la réponse à l'erreur qui compte.",
        "Si tu n'aimes pas le chemin que tu empruntes, commence à en paver un nouveau.",
        "Les actes parlent plus fort que les mots, et c'est d'autant plus vrai avec tes enfants.",
        "Un diamant est un morceau de charbon qui a bien résisté sous la pression.",
        "Les chemins difficiles mènent souvent à de belles destinations.",
        "Parfois, tu ne connaîtras jamais la valeur d'un moment jusqu'à ce qu'il devienne un souvenir.",
        "Rien ne peut éteindre la lumière qui brille de l'intérieur.",
        "Pour réussir dans la vie, tu as besoin de trois choses : un os de chance, une colonne vertébrale et un os de rire.",
        "Ceux qui ne croient pas en la magie ne la trouveront jamais.",
        "J'ai décidé que je ne peux pas payer quelqu'un pour rembobiner le temps, alors autant passer à autre chose.",
        "Tout a un coût, que es-tu prêt à payer pour l'obtenir ?",
        "J'ai le plus grandi non pas grâce aux victoires, mais grâce aux revers.",
        "J'ai la chance que quelle que soit la peur que j'ai en moi, mon désir de gagner est toujours plus fort.",
        "Tu dois croire en toi-même quand personne d'autre ne le fait.",
        "N'aie pas peur de l'échec, c'est le chemin vers le succès.",
        "J'aime la critique, ça te rend plus fort.",
        "Je sais que je veux toujours donner le meilleur de moi-même.",
        "Tous ceux que j'ai rencontrés qui réussissent sont des bourreaux de travail.",
        "Je n'ai jamais été en compétition avec personne d'autre que moi-même.",
        "Croire en soi et savoir qui on est, c'est le fondement de toute grandeur.",
        "J'ai peur de ne pas essayer.",
        "La façon de racheter ton passé n'est pas de le fuir, mais d'essayer de le comprendre et de l'utiliser comme base pour grandir.",
        "Jouer la sécurité ne te rapportera rien dans ce monde.",
        "Un grand numéro est un grand numéro, mais sur quelqu'un sans talent, ça ne marche tout simplement pas. Tout se résume au talent.",
        "Tu évolues ou tu disparais.",
        "La graine doit pousser, peu importe qu'elle soit plantée dans la pierre.",
        "Peu importe la difficulté, bombe le torse, garde la tête haute et gère ça.",
        "Donne toujours le meilleur de toi-même, ne laisse pas la pression te faire paniquer.",
        "Tu ne sais jamais comment ni quand tu auras un impact, ou combien ton exemple peut être important pour quelqu'un d'autre.",
        "Fais ce que tu as à faire pour pouvoir faire ce que tu veux faire.",
        "N'aspire pas à gagner ta vie, aspire à faire une différence.",
        "Tu dois être qui tu es dans ce monde, quoi qu'il arrive.",
        "Si tu as un ennemi, alors apprends et connais ton ennemi, ne sois pas simplement en colère contre lui ou elle.",
        "Je m'efforce d'être comme les plus grandes personnes qui aient jamais vécu.",
        "Là où j'excelle, c'est dans une éthique de travail ridicule et maladive. Pendant que l'autre dort, je travaille.",
        "La vie se vit à la limite.",
        "Être réaliste est le chemin le plus emprunté vers la médiocrité.",
        "La première étape est de te dire que tu peux.",
        "Le monde ne peut pas te dire qui tu es, c'est à toi de découvrir qui tu es et de l'être pour le meilleur ou pour le pire.",
        "Tu vas devoir reconnaître tes échecs. Tu vas devoir les accepter et trouver comment les surmonter.",
        "Mon père m'a dit : fixe ton prix dès le début. Si ça devient plus cher que le prix que tu as fixé, sors de là.",
        "Croirais-tu en ce en quoi tu crois si tu étais le seul à y croire ?",
        "Ce que les gens pensent m'est égal, parce que les gens ne pensent pas.",
        "Je n'ai jamais été vraiment bon en quoi que ce soit, sauf dans la capacité d'apprendre.",
        "Le meilleur sentiment au monde est de voir les bénéfices et les récompenses du travail acharné.",
        "Mes objectifs sont si élevés que je n'ai pas le temps de me détendre de quelque manière que ce soit.",
        "La vie est trop courte pour s'inquiéter de ce que les autres disent de toi.",
        "Derrière chaque personne qui réussit se cache une meute de détracteurs.",
        "Tu peux faire quelque chose de ta vie, tout dépend de ta motivation.",
        "Tu as des ennemis ? Bien, ça veut dire que tu as vraiment défendu quelque chose.",
        "Tout succès commence par l'autodiscipline, ça commence par toi.",
        "Avec de la motivation et un peu de talent, tu peux déplacer des montagnes.",
        "L'échec n'est pas une option, c'est juste une étape.",
        "Le succès n'arrive pas du jour au lendemain, c'est quand chaque jour tu t'améliores un peu plus que la veille ; tout s'accumule.",
        "Quand la vie te met dans des situations difficiles, ne dis pas \"pourquoi moi\", dis simplement \"essaie-moi\".",
        "Le succès en toute chose se résume toujours à ceci : concentration et effort. Et nous contrôlons les deux.",
        "J'ai un jour entendu un homme sage dire qu'il n'y a pas d'hommes parfaits, seulement des intentions parfaites.",
        "Très souvent tu t'arrêtes de marcher parce que tu dis \"j'en ai marre de gravir cette colline, je n'atteindrai jamais le sommet\" et tu n'es qu'à deux pas du sommet.",
        "Défie-toi toi-même, c'est le seul chemin qui mène à la croissance.",
        "Tu ne peux pas t'attribuer le mérite du talent, tu ne peux t'attribuer que le mérite de l'utiliser.",
        "La meilleure façon de garantir une défaite est d'abandonner.",
        "Je pouvais soit regarder ça se produire, soit en faire partie.",
        "Quand quelque chose est assez important, tu le fais, même si les chances ne sont pas en ta faveur.",
        "Si tu te lèves le matin en pensant que l'avenir sera meilleur, c'est une journée radieuse ; sinon, ça ne l'est pas.",
        "C'est bien de mettre tous ses œufs dans le même panier, tant que tu contrôles ce qui arrive à ce panier.",
        "Si tu ne fais que des choses dont tu connais la réponse à l'avance, ton entreprise disparaît.",
        "Tu dois être prêt à être mal compris si tu veux innover.",
        "Il n'y a pas de mauvais moment pour innover.",
        "Créer des opportunités signifie regarder là où les autres ne regardent pas.",
        "Le capital de sueur est le capital le plus précieux qui soit.",
        "Nous vivons dans une société où, presque toujours, le travail acharné est récompensé.",
        "L'univers n'a aucune obligation de faire sens pour toi.",
        "Il n'y a pas de meilleure éducation que celle qui est autodidacte.",
        "Personne n'est bête s'il est curieux.",
        "Je ne connais aucun moment dans l'histoire humaine où l'ignorance valait mieux que la connaissance.",
        "Entraîne-toi à ne rien prendre personnellement.",
        "Un homme peut faire de lui-même ce qu'il veut s'il y croit vraiment, mais il doit être prêt à travailler dur et à encaisser beaucoup de déceptions.",
        "Ce que chacun de nous doit comprendre, c'est que notre intention transparaît toujours.",
        "Nous ne pouvons pas ignorer ce que nous voulons vraiment créer.",
        "Toi seul et toi seul peux changer ta situation.",
        "Sois reconnaissant pour les moments difficiles, car ils t'ont façonné.",
        "Pour rejoindre le 1% du sommet, tu dois faire ce que les 99% ne feront pas.",
        "Je crée mon propre chemin, il était droit et étroit. Je le voyais ainsi : tu étais soit sur mon chemin, soit en dehors.",
        "Nous avons tous des doutes sur nous-mêmes. Tu ne les nies pas, mais tu ne capitules pas non plus. Tu les acceptes.",
        "Beaucoup de leaders échouent parce qu'ils n'ont pas le courage de toucher ce nerf ou de frapper cette corde.",
        "Le moment où tu abandonnes est le moment où tu laisses quelqu'un d'autre gagner.",
        "Si tu as peur d'échouer, tu vas probablement échouer.",
        "J'ai réalisé que l'intimidation n'existait pas vraiment, si tu es dans le bon état d'esprit.",
        "C'est le moment où j'accepte que les temps les plus difficiles seront toujours derrière moi et devant moi.",
        "Personne ne sait qu'il va devenir champion ; il faut travailler pour y arriver.",
        "Ma croyance est plus forte que ton doute.",
        "Le succès signifie être satisfait de ce que tu fais chaque jour. C'est être fier de la meilleure personne que tu deviens.",
        "Si tu veux réussir, tu dois être prêt à utiliser chaque connexion que tu as.",
        "Le talent ne suffit jamais. À quelques exceptions près, les meilleurs joueurs sont les plus travailleurs.",
        "N'abandonne pas, sois ami avec des gens qui t'aident à travailler dur.",
        "Célèbre simplement la vie que tu as eue, pas la vie que tu aurais pu avoir.",
        "J'ai grandi pauvre, mais je n'avais pas de rêves pauvres.",
        "Tu es le seul qui peut faire la différence. Quel que soit ton rêve, fonce.",
        "La vie ne s'arrête pas parce que quelque chose t'arrive.",
        "Dans la vie, gagner et perdre arriveront tous les deux, ce qui n'est jamais acceptable c'est d'abandonner.",
        "Savez-vous combien de fois j'ai été refusé dans ma vie ? Combien de fois on m'a dit que je ne pouvais pas accomplir quelque chose ?",
        "Je trouve souvent que les personnes bénies du plus grand talent ne développent jamais cette attitude. Et ceux qui n'ont pas cette bénédiction sont les plus compétitifs et ont le plus grand cœur.",
        "Je pensais que je n'aurais jamais la chance de jouer, jusqu'au jour où je l'ai eue, parce que j'étais préparé et l'opportunité s'est présentée.",
        "J'aime simplement la compétition et j'aime essayer de m'améliorer.",
        "Trop souvent dans la vie, quelque chose arrive et nous blâmons les autres de ne pas être heureux, satisfaits ou accomplis.",
        "Ta vie sera ce que tu en feras.",
        "Je ne vais pas m'énerver parce que quelqu'un a dit quelque chose de mal à mon sujet.",
        "Tu ne peux pas rester sur la touche dans la vie.",
        "Mon message est simple : prends le contrôle de ta vie.",
        "Quand tu es l'un des leaders de l'équipe, il n'y a pas de jours de repos.",
        "Ne compte pas sur les autres. Tu auras un grand soutien de beaucoup de monde, quand même. Mais personne ne va te donner quoi que ce soit.",
        "Les choses ne se corrigent pas toutes seules ; tu dois sortir et travailler dur pour les corriger.",
        "Si tu ne joues pas pour gagner, ne joue pas du tout.",
        "Si tu ne crois pas en toi-même, pourquoi quelqu'un d'autre croirait-il en toi ?",
        "Parfois dans la vie, les plus grands défis finissent par être les meilleures choses qui t'arrivent.",
        "J'aime tout simplement travailler dur.",
        "Les vrais compétiteurs sont ceux qui jouent toujours pour gagner.",
        "Ne cours pas après l'argent, cours après le rêve.",
        "Si tu veux voler, tu dois abandonner les choses qui te tirent vers le bas.",
        "Je ne veux pas que tu rêves, je veux que tu agisses.",
        "Quiconque veut devenir quelqu'un travaillera aussi dur que possible pour réaliser ce rêve.",
        "Je n'ai jamais essayé de cacher que mon intention est de devenir le meilleur.",
        "Si tu ne crois pas que tu es le meilleur, tu n'atteindras jamais tout ce dont tu es capable.",
        "Aujourd'hui il y a des opportunités que personne ne sait si elles reviendront à l'avenir.",
        "Le talent sans travail acharné n'est rien.",
        "Ça ne me dérange pas que les gens me détestent, parce que ça me pousse.",
        "Le talent n'est pas tout. Tu peux l'avoir depuis le berceau, mais il faut apprendre le métier pour être le meilleur.",
        "Je ressens un besoin infini d'apprendre, de m'améliorer, d'évoluer, pour me sentir satisfait de moi-même.",
        "Ton amour me rend fort. Ta haine me rend imparable.",
        "Tu peux surmonter n'importe quoi si et seulement si tu aimes quelque chose assez fort.",
        "Je réussis parce que j'ai fait des sacrifices pour le succès.",
        "Mon ambition est de toujours m'améliorer.",
        "Je commence tôt et je finis tard. Jour après jour, année après année, il m'a fallu 17 ans et 114 jours pour devenir un succès du jour au lendemain.",
        "La personne qui m'empêchait d'être heureux, c'était moi.",
        "Le simple acte de prêter attention peut te mener très loin.",
        "Ne confonds pas la vérité avec l'opinion des masses. Celles-ci ne sont presque jamais même vaguement similaires.",
        "Il y a une différence entre connaître le chemin et parcourir le chemin.",
        "Je n'ai pas de temps à rester éveillée toute la nuit à m'inquiéter de ce que quelqu'un qui ne m'aime pas a à dire sur moi.",
        "Tu ne peux pas hésiter sur qui tu es.",
        "Il y a toujours des choses sur lesquelles travailler, tu n'y arrives jamais complètement.",
        "Je veux être ce que j'ai toujours voulu être : dominant.",
        "J'essaie juste d'être le meilleur possible et j'espère que c'est le meilleur de tous les temps.",
        "Je ne veux pas redevenir aussi bon qu'avant, je veux devenir meilleur.",
        "Mon esprit est mon plus grand atout. Je m'attends à gagner chaque tournoi auquel je participe.",
        "Les gars qui contrôlent vraiment leurs émotions sont ceux qui vont gagner.",
        "Peu importe à quel point tu es bon, tu peux toujours être meilleur, et c'est ça la partie excitante.",
        "Pour pouvoir aider les autres, tu dois d'abord apprendre à t'aider toi-même.",
        "Rien de ce qui en vaut la peine ne vient à quelqu'un autrement que par le travail acharné.",
        "Je ne permettrai à aucun homme de rapetisser mon âme en me faisant le haïr.",
        "Tu ne peux pas maintenir quelqu'un à terre sans rester à terre avec lui.",
        "Le caractère, pas les circonstances, fait l'homme.",
        "Il y a deux façons d'exercer sa force : l'une pousse vers le bas, l'autre tire vers le haut.",
        "J'ai échoué bien plus que j'ai réussi.",
        "Aujourd'hui je fais ce que les gens ne feront pas, pour pouvoir accomplir demain ce que les gens ne peuvent pas.",
        "Même si tu perds, ne perds pas la leçon.",
        "La chose la plus facile à vendre, c'est la vérité.",
        "N'attends pas le moment parfait, tu attendras éternellement. Profite toujours du temps dont tu disposes et rends-le parfait.",
        "Tu ne peux faire qu'un nombre limité de choses avec excellence, et tu devrais mettre de côté tout le reste.",
        "La vie est fragile. Un lendemain n'est pas garanti, alors donne tout ce que tu as.",
        "Je n'ai pas peur de me ridiculiser.",
        "Le respect me motive, pas le succès.",
        "Quand tu passes le sommet de la colline, c'est là que tu prends de la vitesse.",
        "L'excellence n'est pas un acte, c'est une habitude.",
        "Tu ne peux pas avoir un \"A\" si tu as peur d'avoir un \"F\".",
        "Tu fais tes erreurs pour apprendre comment arriver aux bonnes choses.",
        "Un héros est quelqu'un qui marche volontairement vers l'inconnu.",
        "Il y a des millions de survivants là-dehors. Fais-en un million et un.",
        "N'abandonne jamais, parce que tu ne sais jamais ce que la marée apportera le lendemain.",
        "Si ce n'était pas difficile, tout le monde le ferait. C'est la difficulté qui rend la chose grandiose.",
        "Si tu joues la sécurité dans tes choix, tu ne grandis pas.",
        "J'aime faire quelque chose qui me fait peur.",
        "Le processus est la plus belle partie.",
        "C'est facile de tromper l'œil, mais c'est difficile de tromper le cœur.",
        "Ne monte jamais trop haut, ne descends jamais trop bas. Prends-le jour par jour et continue simplement à apprendre.",
        "L'effort ne sera jamais remis en question.",
        "N'espère pas que quelqu'un te donne une opportunité : crée-en une pour toi-même.",
        "Quand les gens me disaient que je n'y arriverais jamais, j'ai écouté la seule personne qui disait que je pouvais : moi.",
        "Il y a une raison pour laquelle on dit poursuivre ses rêves et non marcher après eux.",
        "Pour avoir ce que tu veux vraiment, tu dois d'abord être qui tu es vraiment.",
        "Ne laisse pas le passé te hanter. Parce que ce que tu fais dans le présent pourrait hanter ton avenir, sois sage. Ce que tu fais maintenant ou à l'avenir ne pourra jamais masquer ton passé, mais cela ne veut pas dire que tu doives laisser le passé te contrôler.",
        "Ce \"et si\" est une blessure qui ne guérit jamais.",
        "Si c'était facile, ça n'en vaudrait pas la peine.",
        "Tu ne mérites rien, tu gagnes tout.",
        "La perfection n'est pas intéressante, s'en sortir malgré les épreuves de l'adversité : voilà ce qui m'impressionne.",
        "Ne participe pas aux Olympiades de \"j'ai pitié de moi\" ; nous ne concourons pas là-dedans.",
        "Quand tu veux quelque chose, tu acceptes le terrain qui va avec, quel qu'il soit.",
        "La vraie vision, c'est quand ton esprit est plus puissant que ce qui est devant tes yeux.",
        "Certains événements te feront progresser, certains feront le contraire, en apparence. Ces contraires sont des opportunités d'apprentissage qui s'avéreront utiles à l'avenir.",
        "Paie le prix pour être le patron ou paie le prix du regret.",
        "L'opinion des autres sur toi n'a pas à devenir ta réalité.",
        "Tu n'obtiens pas ce que tu souhaites, tu obtiens ce pour quoi tu travailles.",
        "L'autodiscipline commence par la maîtrise de tes pensées. Si tu ne contrôles pas ce que tu penses, tu ne peux pas contrôler ce que tu fais. L'autodiscipline te permet simplement de penser d'abord et d'agir ensuite.",
        "Qu'est-ce que la défaite ? Rien d'autre que de l'éducation ; rien d'autre que le premier pas vers quelque chose de mieux.",
        "Ce n'est pas ce qui t'arrive, mais comment tu y réagis qui compte.",
        "Contrôle ta colère. Si tu es en colère contre les autres, ils te contrôlent.",
        "Ton plus grand défi est de te présenter quand ton esprit fabrique les meilleures excuses.",
        "Tu peux soit éprouver la douleur de la discipline, soit la douleur du regret. Le choix est le tien.",
        "Tout ce qui t'affaiblit physiquement, intellectuellement et spirituellement, rejette-le comme du poison.",
        "Sue plus pendant la paix, saigne moins pendant la guerre.",
        "Avec le courage de commencer et la discipline d'endurer, la victoire devient une question de temps.",
        "Un bon leader est une personne qui prend un peu plus que sa part de blâme et un peu moins que sa part de crédit.",
        "Sois fort, mais pas grossier. Sois gentil, mais pas faible. Sois audacieux, mais ne brutalise pas. Sois humble, mais pas timide. Sois fier, mais pas arrogant.",
        "La patience est amère, mais son fruit est doux.",
        "La patience n'est pas passive, au contraire ; elle est active. C'est de la force concentrée.",
        "Rien n'est impossible à celui qui veut essayer.",
        "L'intelligence n'est pas la capacité de stocker de l'information, mais de savoir où la trouver.",
        "D'abord c'est une intention. Puis un comportement. Puis une habitude. Puis une pratique. Puis une seconde nature. Puis c'est simplement qui tu es.",
        "Ce que tu veux faire, fais-le maintenant. Il n'y a qu'un nombre limité de lendemains.",
        "Les gens qui disent que ça ne peut pas être fait ne devraient pas interrompre ceux qui sont en train de le faire.",
        "Il n'y a qu'un seul coin de l'univers que tu peux être certain d'améliorer, et c'est toi-même.",
        "Le fou se croit sage, mais le sage se sait fou.",
        "La douleur peut te changer, mais cela ne signifie pas que ce doit être un mauvais changement. Prends cette douleur et transforme-la en sagesse.",
        "Le temps est vraiment le seul capital que tout être humain possède, et la seule chose qu'il ne peut pas se permettre de perdre.",
        "Suis ton propre chemin, peu importe ce que les gens disent.",
        "Fais quelque chose. Si ça marche, fais-en davantage. Si ça ne marche pas, fais autre chose.",
        "Apprendre est la seule chose que l'esprit n'épuise jamais, ne craint jamais et ne regrette jamais.",
        "Un gagnant est un rêveur qui n'abandonne jamais.",
        "Si tu ne te bats pas pour ce que tu veux, ne pleure pas pour ce que tu as perdu.",
        "Une fois que tu as accepté tes défauts, personne ne peut les utiliser contre toi.",
        "Une fois que nous en aurons appris assez sur l'univers, nous admettrons que nous ne saurons jamais tout.",
        "S'inquiéter, c'est comme payer une dette que tu ne dois pas.",
        "Tu ne peux rien enseigner à personne, seulement les amener à réaliser que les réponses sont déjà en eux.",
        "Le pouvoir des pensées peut te causer soit la maladie, soit la guérison.",
        "Si tu veux voir un miracle, sois un miracle.",
        "Il y a trois classes de personnes : ceux qui voient, ceux qui voient quand on leur montre, et ceux qui ne voient pas.",
        "Tes plus grandes peurs sont créées par ton imagination.",
        "La plus grande tromperie dont les hommes souffrent vient de leurs propres opinions.",
        "Quand tu as épuisé toutes les possibilités, souviens-toi : ce n'est pas le cas.",
        "Aime la main que le destin te distribue et joue-la comme si c'était la tienne.",
        "Si deux personnes sont d'accord sur tout, l'une d'elles est inutile.",
        "La plus grande compétition est celle que tu as avec toi-même.",
        "Quand nous sommes fatigués, nous sommes attaqués par des idées que nous avions vaincues depuis longtemps.",
        "Je ne suis pas ce qui m'est arrivé. Je suis ce que je choisis de devenir.",
        "Le facteur le plus important dans la survie n'est ni l'intelligence ni la force, mais l'adaptabilité.",
        "La foi et la peur exigent toutes deux que tu croies en quelque chose que tu ne peux pas voir. Tu choisis.",
        "En te plaignant, tu dis aux gens à quel point tu es faible.",
        "Pour obtenir ce que tu aimes, tu dois d'abord être patient avec ce que tu détestes.",
        "Quand tout semble aller contre toi, rappelle-toi que l'avion décolle face au vent, pas avec lui.",
        "Tu riras de tes peurs quand tu découvriras qui tu es vraiment.",
        "La paix ne se trouve pas dans une tempête plus calme, elle se trouve dans un meilleur bateau.",
        "Tu peux ignorer la réalité, mais tu ne peux pas ignorer les conséquences d'ignorer cette réalité.",
        "Aucun homme n'est plus malheureux que celui qui ne fait jamais face à l'adversité. Car il ne lui est pas permis de se prouver.",
        "Un bon plan exécuté violemment maintenant vaut mieux qu'un plan parfait exécuté la semaine prochaine.",
        "Étudier sans penser est vain. Penser sans étudier est dangereux.",
        "La peur est une réaction. Le courage est une décision.",
        "L'indépendance est pour très peu ; c'est un privilège des forts.",
        "Il faut la moitié de ta vie avant de découvrir que la vie est un projet à faire soi-même.",
        "Joue ton rôle avec honneur.",
        "L'inquiétude est un mauvais usage de l'imagination.",
        "Le pont entre le savoir et la compétence, c'est la pratique. Le pont entre la compétence et la maîtrise, c'est le temps.",
        "Plus j'apprends, plus je réalise combien il me reste à apprendre.",
        "Si tu ne perds pas, tu ne peux pas savourer les victoires. Alors je dois accepter les deux.",
        "Nous apprenons peu de la victoire, beaucoup de la défaite.",
        "Celui qui parle avec déférence mais augmente ses préparatifs avancera. Celui qui parle avec agressivité et avance précipitamment reculera.",
        "Notre vie est ce que nos pensées en font.",
        "Il n'y a vraiment rien de difficile à moins que tu ne décides que c'est difficile. Sinon, c'est juste la prochaine chose que tu résous.",
        "Quelle que soit la situation, ne laisse jamais tes émotions surpasser ton intelligence.",
        "Décide du type de personne que tu veux être et tiens-y, que tu sois seul ou en compagnie.",
        "Si quelque chose ne va pas, corrige-le si tu peux. Mais entraîne-toi à ne pas t'inquiéter. L'inquiétude ne corrige jamais rien.",
        "La vie n'est pas une question d'avoir de bonnes cartes, mais de bien jouer une mauvaise main.",
        "C'est un chemin rude qui mène aux sommets de la grandeur.",
        "Le jour où un homme devient supérieur au plaisir, il sera aussi supérieur à la douleur.",
        "Apprends continuellement, il y a toujours \"encore une chose\" à apprendre.",
        "Nous pouvons nous plaindre que les rosiers aient des épines, ou nous réjouir que les buissons d'épines aient des roses.",
        "Sois patient et fort ; un jour cette douleur te sera utile.",
        "L'échec est le succès en cours.",
        "Quiconque cesse d'apprendre est vieux, que ce soit à vingt ou quatre-vingts ans.",
        "Si tu es gouverné par l'esprit, tu es un roi ; si par le corps, un esclave.",
        "L'orgueil n'est pas le contraire de la honte, mais sa source. La vraie humilité est le seul antidote à la honte.",
        "Quand tu commences à t'améliorer, la solitude est le prix que tu paies.",
        "Tu n'es pas jugé par la hauteur à laquelle tu t'es élevé, mais par la profondeur d'où tu as grimpé.",
        "Un homme n'est pas grand parce qu'il n'a pas échoué ; un homme est grand parce que l'échec ne l'a pas arrêté.",
        "Un homme sans vision est un homme sans avenir. Un homme sans avenir retournera toujours à son passé.",
        "Mieux vaut échouer avec honneur que réussir par la fraude.",
        "Toutes les batailles sont d'abord gagnées ou perdues dans l'esprit.",
        "Les émotions de l'homme sont remuées plus vite que son intelligence.",
        "Celui qui achète ce dont il n'a pas besoin se vole lui-même.",
        "Celui qui a de la patience peut avoir ce qu'il veut.",
        "Le chemin du guerrier est pour la vie, et la maîtrise consiste souvent simplement à rester sur le chemin.",
        "Les cerfs-volants s'élèvent le plus haut face au vent, pas avec lui.",
        "Si les gens savaient combien j'ai dû travailler dur pour acquérir ma maîtrise, cela ne leur semblerait pas si merveilleux.",
        "Ne va jamais dormir sans une requête à ton subconscient.",
        "Accueille les événements de quelque manière qu'ils surviennent : c'est le chemin vers la paix.",
        "Pratique même ce qui semble impossible.",
        "L'homme qui poursuit deux lièvres n'en attrape aucun.",
        "Tu vas y arriver, mais tu auras toujours l'impression de ne pas y arriver.",
        "Planifie ce qui est difficile pendant que c'est facile, fais ce qui est grand pendant que c'est petit.",
        "La persistance ne suffit pas. Il faut décider si l'on persiste en tant que victime ou en tant que guerrier.",
        "Le niveau de finesse et de discipline nécessaire pour t'amener aux sommets dont tu rêves est vraiment simple, mais pas facile.",
        "Le plus grand ennemi ne se trouve pas à l'extérieur. La destruction vient souvent de l'intérieur.",
        "Tout le monde savait que c'était impossible, jusqu'à ce qu'un fou qui ne le savait pas vienne et le fasse.",
        "Tu ne peux pas rendre un homme faible fort en rendant un homme fort faible.",
        "Tu as du pouvoir sur ton esprit, pas sur les événements extérieurs. Réalise cela et tu trouveras la force.",
        "Un diamant n'est qu'un morceau de charbon qui est resté à son poste.",
        "Le plus grand risque est de ne prendre aucun risque.",
        "Si tu définis le problème correctement, tu as presque la solution.",
        "Le passé est dans ta tête, l'avenir est dans tes mains.",
        "La vie est assez simple. Tu fais des choses. La plupart échouent. Certaines marchent. Tu fais plus de ce qui marche.",
        "Que ton sens du devoir surpasse une atmosphère de peur et la tendance à repousser les aspirations.",
        "Tout ce que tu as toujours voulu se trouve de l'autre côté de la peur.",
        "La discipline, c'est choisir entre ce que tu veux maintenant et ce que tu veux le plus.",
        "Le conformisme est le dernier refuge des sans-imagination.",
        "Un diamant est un morceau de charbon qui est resté au travail.",
        "Il n'y a pas de plus grand tort fait à l'homme que le temps gaspillé.",
        "Ne gâche pas ce que tu as en désirant ce que tu n'as pas ; souviens-toi que ce que tu as maintenant faisait jadis partie des choses que tu espérais seulement.",
        "Un homme maître de la patience est maître de tout le reste.",
        "Ne mets jamais la passion avant le principe, même si tu gagnes, tu perdras.",
        "Certains veulent que ça arrive, d'autres souhaitent que ça arrive, d'autres encore font en sorte que ça arrive.",
        "Nous ne nous élevons pas au niveau de nos attentes, nous tombons au niveau de notre entraînement.",
        "Il est plus facile de trouver des hommes qui se portent volontaires pour mourir que de trouver ceux qui sont prêts à endurer la douleur avec patience.",
        "Tu ne peux pas t'attendre à monter sur le podium si tu ne participes pas à la course.",
        "Celui qui tombe et se relève est plus fort que celui qui n'a jamais essayé.",
        "Mauvaise nouvelle : tu ne vas pas \"t'intégrer\" partout. Bonne nouvelle : les grands ne le font jamais.",
        "Je n'ai jamais été talentueux, je suis juste bon pour ne jamais abandonner.",
        "Le bonheur n'est pas l'absence de problèmes, c'est la capacité de les gérer.",
        "Si tu fais ce qui est facile, ta vie sera difficile.",
        "Tu ne peux pas revenir en arrière et changer le début, mais tu peux commencer là où tu es et changer la fin.",
        "On apprend plus en observant qu'en écoutant.",
        "Ceux qui ne font jamais d'erreurs travaillent pour ceux d'entre nous qui en font.",
        "Une nouvelle idée ne doit pas être jugée par ses résultats immédiats.",
        "Tu n'es jamais prêt pour ce que tu dois faire. Tu le fais simplement. C'est ça qui te rend prêt.",
        "Prends des risques : si tu gagnes, tu seras heureux ; si tu perds, tu seras sage.",
        "Un peuple qui valorise ses privilèges au-dessus de ses principes perd bientôt les deux.",
        "Le chemin le plus rapide vers le sens et le succès : choisis une chose et donne tout.",
        "N'aie pas peur de repartir à zéro. Cette fois, tu ne pars pas de rien. Tu pars de l'expérience.",
        "Il n'y a rien de noble à être supérieur à son prochain ; la vraie noblesse est d'être supérieur à son ancien soi.",
        "Tu gagneras le respect de tous si tu commences par gagner le respect de toi-même.",
        "Crée une vision de qui tu veux être, puis vis cette image comme si c'était déjà vrai.",
        "Le prix de l'excellence est la discipline. Le coût de la médiocrité est la déception.",
        "Les difficultés fortifient l'esprit, comme le travail fortifie le corps.",
        "Tu ne peux pas espérer progresser dans des domaines où tu n'as pris aucune action.",
        "Aucune quantité d'anxiété ne change quoi que ce soit à ce qui va arriver.",
        "Montre-moi un homme de capacité moyenne mais de désir extraordinaire et je te montrerai un gagnant à chaque fois.",
        "Le moyen le plus rapide de réussir est de commencer maintenant et de comprendre en cours de route.",
        "Les gens ne décident pas de leur avenir, ils décident de leurs habitudes et leurs habitudes décident de leur avenir.",
        "Enseigne tôt à tes enfants ce que tu as appris tard.",
        "Si tu consacres 100 heures par an à n'importe quelle discipline, soit seulement 18 minutes par jour, tu seras meilleur que 95% du monde dans cette discipline.",
        "La tâche n'est pas tant de voir ce que personne n'a encore vu ; mais de penser ce que personne n'a encore pensé à propos de ce que tout le monde voit.",
        "Si chaque frottement t'irrite, comment ton miroir sera-t-il poli ?",
        "La peur n'est profonde qu'autant que l'esprit le permet.",
        "La difficulté est ce qui réveille le génie.",
        "Ce qui doit donner la lumière doit endurer de brûler.",
        "J'ai appris que le succès ne se mesure pas tant par la position atteinte dans la vie que par les obstacles surmontés en essayant de réussir.",
        "Le confort est la pire des addictions.",
        "Tu deviens ce à quoi tu prêtes attention.",
        "Les circonstances ne font pas l'homme, elles ne font que le révéler à lui-même.",
        "Ne perds plus de temps à discuter de ce que devrait être un homme bon. Sois-en un.",
        "Que celui qui veut bouger le monde commence par se bouger lui-même.",
        "Entre le stimulus et la réponse, il y a un espace. Dans cet espace se trouve notre pouvoir de choisir notre réponse. Dans notre réponse se trouvent notre croissance et notre liberté.",
        "Il n'y a rien en dehors de toi-même qui puisse t'aider à devenir meilleur, plus fort, plus riche, plus rapide ou plus intelligent. Tout est à l'intérieur. Tout existe. Ne cherche rien en dehors de toi-même.",
        "Sois tolérant avec les autres et strict avec toi-même.",
        "Deux choses te définissent : ta patience quand tu n'as rien et ton attitude quand tu as tout.",
        "Tu ne te réveilles pas un matin pour te transformer en papillon.",
        "La ténacité est la capacité de tenir bon quand lâcher prise semble le plus séduisant.",
        "Il y a des risques et des coûts à l'action. Mais ils sont bien moindres que les risques à long terme de l'inaction confortable.",
        "Pour accomplir de grandes choses, deux éléments sont nécessaires : un plan et pas tout à fait assez de temps.",
        "Le doute ne peut être dissipé que par l'action.",
        "Si tes actions inspirent les autres à rêver plus, apprendre plus, faire plus et devenir plus, tu es un leader.",
        "Il ne s'agit pas d'avoir un parcours sans tache. Il s'agit d'apprendre des imperfections de ton parcours.",
        "Sois assez courageux pour être mauvais dans quelque chose de nouveau.",
        "Couche-toi plus intelligent que quand tu t'es réveillé.",
        "Le succès lent construit le caractère, le succès rapide construit l'ego.",
        "Ce n'est pas parce que quelqu'un trébuche et perd son chemin qu'il est perdu pour toujours.",
        "Mais nous ne pouvons pas simplement nous asseoir et fixer nos blessures éternellement.",
        "Et maintenant que tu n'as pas besoin d'être parfait, tu peux être bon.",
        "Le succès vient de l'exécution impitoyable des fondamentaux.",
        "Il faut beaucoup de travail pour rendre quelque chose simple.",
        "Tout le monde pense à changer le monde, mais personne ne pense à se changer soi-même.",
        "Les esprits fermés ont besoin qu'on leur donne l'art à la cuillère.",
        "Fais quelque chose au lieu de tuer le temps. Parce que le temps est en train de te tuer.",
        "Que chaque décision soit en accord avec ta vision.",
        "Si tu veux faire quelque chose de plus grand que la moyenne, tu ne peux pas céder à la peur d'être un marginal.",
        "Ce qui compte le plus, c'est à quel point tu marches bien à travers le feu.",
        "Tu es à une seule décision d'une vie complètement différente.",
        "Si tu vis pour demain, tu seras toujours en retard d'un jour.",
        "Tire le meilleur de toi-même, car c'est tout ce qu'il y a de toi.",
        "Les yeux sont inutiles quand l'esprit est aveugle.",
        "À long terme, les hommes n'atteignent que ce qu'ils visent. Par conséquent, même s'ils échouent immédiatement, ils feraient mieux de viser haut.",
        "Celui qui a une raison de vivre peut supporter presque n'importe quel comment.",
        "Les hommes peuvent être divisés en 2 groupes : celui qui avance et accomplit quelque chose, et celui qui vient après et critique.",
        "Une mauvaise attitude est comme un pneu crevé. Tu ne peux aller nulle part tant que tu ne le changes pas.",
        "Aucun oiseau ne vole trop haut s'il vole de ses propres ailes.",
        "Résous le problème ou quitte le problème. Ne vis pas avec le problème.",
        "Agis selon tes principes, pas selon ton humeur.",
        "Ceux qui ne s'engagent en rien sont distraits par tout.",
        "Quand nous nous efforçons de devenir meilleurs que nous sommes, tout autour de nous devient meilleur aussi.",
        "Il n'y a aucune passion à trouver dans le fait de se contenter d'une vie inférieure à celle dont tu es capable.",
        "Un homme créatif est motivé par le désir d'accomplir, pas par le désir de battre les autres.",
        "La vie est une longue préparation pour quelque chose qui n'arrive jamais.",
        "Je n'écoute plus ce que les gens disent, j'observe simplement ce qu'ils font. Le comportement ne ment jamais.",
        "Les gens intelligents apprennent de tout et de tout le monde ; les gens moyens, de leurs expériences. Les stupides ont déjà toutes les réponses.",
        "La première règle est de maintenir un esprit serein. La seconde est de regarder les choses en face et de les connaître pour ce qu'elles sont.",
        "C'est toujours un combat de soulever un poids plus lourd.",
        "Un homme qui craint de souffrir souffre déjà de ce qu'il craint.",
        "Si un homme ne sait pas vers quel port il navigue, aucun vent ne lui est favorable.",
        "Je fais toujours ce que je ne sais pas faire, afin d'apprendre à le faire.",
        "Tu construis sur l'échec. Tu l'utilises comme un tremplin. Ferme la porte sur le passé. Tu n'essaies pas d'oublier les erreurs, mais tu ne t'y attardes pas. Tu ne leur donnes ni ton énergie, ni ton temps, ni ton espace.",
        "Le contenu de ton caractère est ton choix. Jour après jour, ce que tu choisis, ce que tu penses et ce que tu fais, c'est ce que tu deviens.",
        "Les lâches n'ont jamais commencé et les faibles sont morts en chemin.",
        "Quand tu te lèves le matin, pense à quel précieux privilège c'est d'être en vie : respirer, penser, profiter, aimer.",
        "Le secret du succès est la concentration sur un objectif.",
        "La seule chose plus dangereuse que l'ignorance est l'arrogance.",
        "Nous sommes ce que nous faisons de manière répétée. L'excellence n'est donc pas un acte, mais une habitude.",
        "Pendant que nous attendons la vie, la vie passe.",
        "Le succès n'est rien de plus que quelques disciplines simples, pratiquées chaque jour.",
        "Plus il sait, plus il sera conscient de son ignorance.",
        "L'obstacle à l'action fait avancer l'action. Ce qui se dresse sur le chemin devient le chemin.",
        "Notre plus grande faiblesse réside dans l'abandon. Le moyen le plus sûr de réussir est toujours d'essayer une fois de plus.",
        "Une gemme ne peut être polie sans friction, ni un homme perfectionné sans épreuves.",
        "Ta valeur réside dans ce que tu es, pas dans ce que tu as.",
        "Celui qui fait le mal est plus malheureux que celui qui le subit.",
        "L'une des plus vraies épreuves de l'intégrité est son refus catégorique d'être compromise.",
        "Dieu ne donne rien à ceux qui gardent les bras croisés.",
        "Savoir comment penser t'habilite bien au-delà de ceux qui ne savent que quoi penser.",
        "Si tu prévois d'être quelque chose de moins que ce dont tu es capable, tu seras probablement malheureux tous les jours de ta vie.",
        "Il n'y a rien de mieux que l'adversité. Chaque défaite, chaque chagrin, chaque perte contient sa propre graine, sa propre leçon sur comment améliorer ta performance la prochaine fois.",
        "Apprends à aimer la haine. Accepte-la. Savoure-la. Tu l'as méritée. Chacun a droit à sa propre opinion et tout le monde devrait en avoir une sur toi. Les détracteurs sont un bon problème à avoir. Personne ne déteste les bons. Ils détestent les grands.",
        "Accepte ton incapacité à tout contrôler. Accepte la responsabilité de tout ce qui est sous ton contrôle. Accepte que des obstacles internes et externes existent. Accepte que tu es équipé pour tous les surmonter.",
        "L'expérience est le genre de professeur le plus dur. Elle te donne l'examen d'abord et la leçon après.",
        "Nous mûrissons avec les blessures, pas avec les années.",
        "Si tu es déprimé, tu vis dans le passé. Si tu es anxieux, tu vis dans l'avenir. Si tu es en paix, tu vis dans le présent.",
        "Si tu penses que nous ne pouvons pas changer le monde, cela signifie simplement que tu n'es pas l'un de ceux qui le feront.",
        "Peut-être que ce n'est pas une question de fin heureuse. Peut-être que c'est une question d'histoire.",
        "Certaines personnes apportent de la joie partout où elles vont, et d'autres apportent de la joie quand elles s'en vont.",
        "Observe constamment que toutes les choses se produisent par le changement, et habitue-toi à considérer que la nature de l'univers n'aime rien tant que changer.",
        "Être trop bon tend à être inintéressant.",
        "Trop souvent nous apprécions le confort de l'opinion sans l'inconfort de la pensée.",
        "Étudier sans réfléchir est vain ; réfléchir sans étudier est dangereux.",
        "Un homme avec une conviction en surpassera cent qui n'ont que des opinions.",
        "Les fous se multiplient quand les sages se taisent.",
        "Sois prêt à réviser tout système, à abandonner toute méthode, à rejeter toute théorie si le succès du travail l'exige.",
        "Aider les autres à se développer et à réussir dans la vie est une récompense en soi et n'a de valeur que lorsque rien n'est attendu en retour.",
        "Ce n'est pas le moment de penser à ce que tu n'as pas. Pense à ce que tu peux faire avec ce qu'il y a.",
        "Je dirais que je suis un travail en cours, mais cela suggérerait qu'un jour je ne serai plus un travail en cours.",
        "N'abandonne pas. Normalement c'est la dernière clé du trousseau qui ouvre la porte.",
        "La vie est une comédie pour ceux qui pensent, une tragédie pour ceux qui ressentent.",
        "Le tact est la capacité de dire à quelqu'un d'aller en enfer de telle manière qu'il ait hâte d'y aller.",
        "Laisse le mal fait par un autre là où le mal est né.",
        "Ne te perturbe pas en imaginant toute ta vie d'un coup. Ne pense pas toujours aux souffrances, et combien, qui pourraient te frapper.",
        "Chaque fois que je crois tout savoir, il s'avère que \"tout\" a un peu plus de volume que ce que j'avais supposé.",
        "La différence entre la stupidité et le génie, c'est que le génie a ses limites.",
        "Mieux vaut être un guerrier dans un jardin qu'un jardinier dans une guerre.",
        "Le grand succès vient toujours au risque d'un échec énorme.",
        "Le succès vient de la curiosité, de la concentration, de la persévérance et de l'autocritique.",
        "C'est la marque d'un esprit cultivé d'être capable d'examiner une idée sans l'accepter.",
        "L'opinion de 10 000 personnes n'a aucune valeur si aucune d'entre elles ne connaît le sujet.",
        "Plus nous valorisons des choses hors de notre contrôle, moins nous avons de contrôle.",
        "Fais des voyages. Tente-les. Il n'y a rien d'autre.",
        "Les origines ne devraient jamais être un obstacle au succès. Un début modeste dans la vie peut être plus une aide qu'un handicap.",
        "Ne laisse pas les défauts d'un autre te faire défaut.",
        "Notre envie dure toujours plus longtemps que le bonheur de ceux que nous envions.",
        "Rien ne viendra de rien.",
        "Les faibles se vengent. Les forts pardonnent. Les intelligents ignorent.",
        "Je ne contrôle pas le vent ; je ne fais que l'étudier.",
        "L'honneur ne gagne peut-être pas le pouvoir, mais il gagne le respect. Et le respect gagne le pouvoir.",
        "L'arme ultime est le cerveau, tout le reste est secondaire.",
        "Si tu ne surmontes pas ta tendance à abandonner facilement, ta vie ne mène nulle part.",
        "L'entraînement, c'est comme balayer le sol. Ce n'est pas parce qu'on l'a fait une fois que le sol est propre pour toujours.",
        "Souviens-toi que c'est nous qui nous tourmentons, nous qui nous créons des difficultés, c'est-à-dire nos opinions. Que signifie, par exemple, être insulté ? Tiens-toi près d'un rocher et insulte-le, qu'as-tu accompli ? Si quelqu'un répond à l'insulte comme un rocher, qu'a gagné l'offenseur avec son invective ?",
        "En l'absence de but, la vie devient un voyage sans fin vers nulle part.",
        "Seuls les morts ont vu la fin de la guerre.",
        "Mieux vaut prévenir que guérir.",
        "Rien de ce qui est enseigné par la force ne reste dans l'âme.",
        "Tout ce qui existe dans ta vie existe à cause de deux choses : quelque chose que tu as fait ou quelque chose que tu n'as pas fait.",
        "Un homme sans éthique est une bête sauvage lâchée dans ce monde.",
        "Penser est difficile, c'est pourquoi la plupart des gens jugent.",
        "Tu ne trouves pas la volonté, tu la crées.",
        "Le mot heureux perdrait son sens s'il n'était pas équilibré par la tristesse.",
        "Ne prie pas pour une vie facile. Prie pour la force d'endurer une vie difficile.",
        "Tu n'es pas tout ce que tu pourrais être, et tu le sais.",
        "N'oublie pas de vivre pendant que tu es occupé à survivre.",
        "Les plans ne sont rien, la planification est tout.",
        "Un homme qui ose gaspiller une heure de temps n'a pas découvert la valeur de la vie.",
        "Tu dois décider qui tu es et forcer le monde à composer avec toi, pas avec l'idée qu'il se fait de toi.",
        "L'art de vivre ressemble plus à la lutte qu'à la danse, en ce qu'il se tient prêt face à l'accidentel et l'imprévu, et n'est pas enclin à tomber.",
        "En vieillissant, je prête moins attention à ce que les hommes disent. J'observe simplement ce qu'ils font.",
        "Je serrerai ma ceinture avant de demander de l'aide.",
        "Personne n'est fait comme toi, tu t'es conçu toi-même.",
        "Aucun homme n'a le droit d'être un amateur en matière d'entraînement physique. C'est une honte pour un homme de vieillir sans voir la beauté et la force dont son corps est capable.",
        "Plus un homme s'approche d'un esprit calme, plus il est proche de la force.",
        "Voici une règle à retenir à l'avenir, quand quelque chose te tente de ressentir de l'amertume : non pas \"c'est un malheur\", mais \"supporter cela dignement est une chance\".",
        "Quand tu es bon dans quelque chose, tu le dis à tout le monde. Quand tu es excellent dans quelque chose, ce sont eux qui te le disent.",
        "D'abord ils t'ignorent. Puis ils se moquent de toi. Puis ils t'attaquent et veulent te brûler. Et puis ils te construisent des monuments.",
        "La liberté signifie responsabilité. C'est pourquoi la plupart des hommes la redoutent.",
        "Si tu dis la vérité, tu n'as rien à retenir.",
        "Ton heure viendra si tu continues d'avancer.",
        "Ce n'est pas la mort qu'un homme devrait craindre, mais il devrait craindre de n'avoir jamais commencé à vivre.",
        "Les procédures d'aujourd'hui sont les résultats de demain. Si tu peux tomber amoureux des procédures d'aujourd'hui, tu aimeras les résultats de demain.",
        "Tous les problèmes de l'humanité proviennent de l'incapacité de l'homme à rester tranquillement assis dans une pièce seul.",
        "Ne laisse jamais l'avenir te troubler. Tu l'affronteras, si nécessaire, avec les mêmes armes de raison qui t'arment aujourd'hui contre le présent.",
        "L'homme mûrit à travers la douleur, l'échec, le rejet, la perte, le manque de respect et le chagrin d'amour, pas à travers l'âge.",
        "Nous forgeons les chaînes que nous portons dans la vie.",
        "Pour faire quoi que ce soit à un haut niveau, cela doit être une obsession.",
        "Si tu veux t'améliorer, accepte qu'on te considère comme insensé et ignorant en ce qui concerne les choses extérieures.",
        "La violence est le dernier refuge de l'incompétent.",
        "La peur est comme le feu, elle peut être utile si tu sais comment l'utiliser. Sinon, tu te brûleras.",
        "Pour réussir grandement, tu dois être prêt à échouer grandement. Si tu ne peux pas faire les deux, tu as un problème.",
        "On parle toujours de quelqu'un qui ne nous aime pas \"sans raison\", mais les gens t'aimeront aussi \"sans raison\". Alors n'accorde pas trop d'importance à l'un ou l'autre.",
        "Les lâches meurent plusieurs fois avant leur mort ; les vaillants ne goûtent la mort qu'une seule fois.",
        "Rien n'est plus difficile, et donc plus précieux, que d'être capable de décider.",
        "Marche sur un seul sentier, sans devenir arrogant dans la victoire ni brisé dans la défaite, sans oublier la prudence quand tout est calme ni s'effrayer quand le danger menace.",
        "L'âme prend la couleur de ses pensées.",
        "Je ne demande pas un fardeau plus léger. Mais des épaules plus larges.",
        "Ne négocie pas avec toi-même. Donne-toi des instructions.",
        "Tu ne peux pas souhaiter à la fois un caractère fort et une vie facile.",
        "Le courage, ce n'est pas avoir la force de continuer ; c'est continuer quand tu n'as plus de force.",
        "La vie ne t'arrive pas, elle se produit en t'impliquant.",
        "Il est fatal d'entrer en guerre sans la volonté de la gagner.",
        "Tu ne sais jamais à quel point tu es fort jusqu'à ce qu'être fort soit ta seule option.",
        "Tu ne peux pas plaire à tout le monde, parfois tu dois agir et laisser tous les autres réagir.",
        "Il n'y a pas de question de \"si\", la question n'est que de quand, quand tu es résolu dans ta mission.",
        "Combien de temps vas-tu attendre avant d'exiger le meilleur pour toi-même ?",
        "Le monde te promet le confort, mais tu n'as pas été fait pour le confort. Tu as été fait pour la grandeur.",
        "L'intégrité n'est pas un chemin rapide, mais c'est un chemin sûr.",
        "Sois ton plus grand fan, ton plus grand croyant, et porte-le sur ton dos et supporte le poids.",
        "Dis-toi d'abord ce que tu voudrais être ; puis fais ce que tu as à faire.",
        "Je crains le jour où la technologie dépassera nos interactions humaines. Le monde aura une génération d'idiots.",
        "Ce n'est pas ce que tu supportes qui importe, mais comment tu le supportes.",
        "Rejette ton sentiment d'offense et l'offense elle-même disparaît.",
        "Ne fais pas de petits plans. Ils n'ont aucune magie pour remuer le sang des hommes et ne se réaliseront probablement pas. Fais de grands plans ; vise haut dans l'espoir et le travail, en te souvenant qu'un diagramme noble et logique, une fois enregistré, ne mourra jamais, mais longtemps après notre départ sera une chose vivante, s'affirmant avec une insistance croissante.",
        "Les épreuves préparent souvent des gens ordinaires à un destin extraordinaire.",
        "Quand tu veux changer les choses, tu ne peux pas plaire à tout le monde. Si tu plais à tout le monde, tu ne progresses pas assez.",
        "Ne négocie pas avec toi-même, donne-toi des instructions.",
        "Le succès n'est pas final, l'échec n'est pas fatal : c'est le courage de continuer qui compte.",
        "Si ce n'est pas juste, ne le fais pas ; si ce n'est pas vrai, ne le dis pas.",
        "Les soi-disant plaisirs, quand ils dépassent une certaine limite, ne sont que des punitions.",
        "Si tu ne sacrifies pas pour ce que tu veux, ce que tu veux devient le sacrifice.",
        "Ton plus grand ennemi est ton esprit incontrôlé.",
        "Apprends à te battre pour n'avoir jamais à te battre.",
        "Quand une personne ne trouve pas de sens profond à la vie, elle se distrait avec le plaisir.",
        "Rien n'est permanent dans ce monde cruel, pas même nos problèmes.",
        "Laisse-les se tromper sur toi. Il n'y a rien à leur prouver.",
        "Si tu veux que le présent soit différent du passé, étudie le passé.",
        "Si tu veux vivre une vie heureuse, attache-la à un objectif, pas à des personnes ou des objets.",
        "Il n'y a pas de secrets, il n'y a que l'information que tu as découverte et l'information que tu n'as pas encore découverte.",
        "Tu as besoin de motivation pour agir. Tu as besoin d'information pour savoir sur quoi agir. Tu as besoin de curiosité pour obtenir des renseignements qui piloteront correctement ces actes motivés. Alors sois curieux.",
        "Un gagnant n'est qu'un perdant qui a essayé une fois de plus.",
        "Nous traitons le corps rigoureusement pour qu'il ne désobéisse pas à l'esprit.",
        "Les consentants sont guidés par le destin, les réticents sont traînés.",
        "L'homme qui craint la mort ne fera jamais rien de digne d'un homme vivant.",
        "Un commandant ne met jamais tant de confiance dans la paix qu'il néglige de se préparer à la guerre.",
        "N'aie pas peur. Tu vas y arriver, mais tu auras toujours l'impression de ne pas y arriver.",
        "La régularité peut sembler ennuyeuse, mais que penserais-tu d'autre qu'être grand soit ? De la chance ?",
        "Garde toujours ton visage tourné vers le soleil et les ombres tomberont derrière toi.",
        "La peine la plus lourde pour refuser de gouverner est d'être gouverné par quelqu'un d'inférieur à soi.",
        "Creuse en toi. À l'intérieur se trouve la source du Bien ; et elle est toujours prête à jaillir, si tu creuses.",
        "Tu es ce que tu fais, pas ce que tu dis que tu feras.",
        "Se tromper à sa propre manière vaut mieux qu'avoir raison à la manière d'un autre.",
        "Un grand homme est dur envers lui-même, un homme faible est dur envers les autres.",
        "S'aimer soi-même est le début d'une romance qui dure toute la vie.",
        "Soucie-toi de ce que pensent les autres et tu seras toujours leur prisonnier.",
        "L'homme n'est pas inquiété par les vrais problèmes autant que par ses anxiétés imaginées concernant les vrais problèmes.",
        "L'homme heureux est satisfait de sa situation présente, quelle qu'elle soit.",
        "La première et la plus grande victoire est de se vaincre soi-même.",
        "Pour me contrôler, je dois d'abord m'accepter en allant avec ma nature et non contre elle.",
        "Que les hommes voient, qu'ils sachent qu'il y a un vrai homme qui vit comme il était destiné à vivre.",
        "Celui qui ne peut pas s'obéir sera commandé.",
        "Quand tu crains quelque chose, apprends-en le plus possible à ce sujet. La connaissance vainc la peur.",
        "J'ai toujours pensé que c'était moi contre le monde, et puis un jour j'ai réalisé que c'est juste moi contre moi.",
        "Un homme qui manque de but se distrait avec le plaisir.",
        "C'est difficile d'accepter que tout le monde ne va pas \"comprendre\", mais c'est pour ça que ce n'est pas pour tout le monde. C'est un truc à toi.",
        "Plus la difficulté est grande, plus il y a de gloire à la surmonter.",
        "Nous nous délectons de la beauté du papillon, mais admettons rarement les changements qu'il a traversés pour atteindre cette beauté.",
        "Laisse-moi tomber si je dois tomber. Celui que je deviens me rattrapera.",
        "Derrière un homme qui pardonne tout, il y a un homme qui connaît le poids de ses propres péchés.",
        "La tentative d'échapper à la douleur crée plus de douleur.",
        "Le vrai développement ne respecte pas le confort.",
        "Pour autant que nous puissions discerner, le seul but de l'existence humaine est d'allumer une lumière de sens dans l'obscurité du simple être.",
        "Le jour où tu plantes la graine n'est pas le jour où tu manges le fruit.",
        "La vérité ne change pas parce qu'elle est ou n'est pas crue par la majorité des gens.",
        "Un chevalier en armure étincelante n'a pas de valeur prouvée. Donne-moi un chevalier éprouvé au combat, avec une armure usée par les rencontres avec les misérables de l'humanité.",
        "La mesure de l'intelligence est la capacité de changer.",
        "Il n'y a pas de récolte sans faim.",
        "C'est l'esprit lui-même qui égare l'esprit. De l'esprit, ne sois pas inattentif.",
        "Tu ne peux pas te rêver un caractère ; tu dois t'en forger un à coups de marteau.",
        "Beaucoup de choses iront mal avant que tout aille bien.",
        "Nous ne vivons que maintenant. Tout le reste est soit passé, soit inconnu.",
        "Tu ne seras pas puni pour ta colère, tu seras puni par ta colère.",
        "Tu n'apprends pas à nager en lisant sur l'eau.",
        "Les choix les plus difficiles exigent les volontés les plus fortes.",
        "Par-dessus tout, ne te mens pas à toi-même.",
        "Ton corps peut supporter presque tout ; c'est l'esprit que tu dois convaincre.",
        "La vie est du genre à la première personne. Traite-la comme telle.",
        "Les bons leaders ne font pas d'excuses. À la place, ils trouvent un moyen de faire avancer les choses.",
        "Ce n'est pas parce que ça t'a pris plus longtemps que les autres que tu as échoué.",
        "Plus tu te connais toi-même, moins tu as besoin de l'approbation des autres.",
        "Se connaître soi-même est le commencement de toute sagesse.",
        "Ce n'est pas la taille d'un homme mais la taille de son cœur qui compte.",
        "Il est peu probable que tu changes de niveau sans larmes.",
        "Tu laboures avec la charrue que tu as.",
    ]
}
