// QuotesLang_pl.swift
// Spike AI — Bundled quote translations
import Foundation
enum QuotesLang_pl {
    static let quotes: [String] = [
        "Cokolwiek konsekwentnie trzymasz w swoim umyśle, jest dokładnie tym, czego doświadczysz w życiu.",
        "Celujemy powyżej celu, aby trafić w cel.",
        "Najgorszą rzeczą, jaką mogę być, to być taki sam jak wszyscy inni, nienawidzę tego.",
        "Tylko ci, którzy zaryzykują pójście za daleko, mogą odkryć, jak daleko można zajść.",
        "Skocz, a siatka się pojawi.",
        "Statek w porcie jest bezpieczny, ale nie po to buduje się statki.",
        "Nie martw się porażkami, martw się szansami, które tracisz, gdy nawet nie próbujesz.",
        "Ci, którzy odważą się ponieść sromotną porażkę, mogą osiągnąć wielkie rzeczy.",
        "Sposób na to, żeby zacząć, to przestać mówić i zacząć działać.",
        "Możemy napotkać wiele porażek, ale nie możemy dać się pokonać.",
        "Prawdziwą miarą człowieka jest to, jak traktuje kogoś, kto nie może mu się w żaden sposób przydać.",
        "Musisz uważać, jeśli nie wiesz, dokąd zmierzasz, bo możesz tam nie dotrzeć.",
        "Musisz oczekiwać od siebie wielkich rzeczy, zanim będziesz mógł je osiągnąć.",
        "Nigdy nie pozwól, aby przeszłe decyzje determinowały twoje przyszłe wyniki.",
        "Skróty powodują długie opóźnienia.",
        "Nikt nie może dać ci twoich celów. To jest twoja podróż.",
        "Świat jest tym, co o nim myślisz, więc pomyśl o nim inaczej, a twój świat się zmieni.",
        "Przyszłość należy do tych, którzy przygotowują się do niej dzisiaj.",
        "Nie rezygnuj z tego, czego pragniesz najbardziej, dla tego, czego chcesz teraz.",
        "Nie mów mi, jak bardzo jesteś utalentowany, powiedz mi, jak ciężko pracujesz.",
        "To, jak myślisz, kiedy przegrywasz, określa, jak długo będziesz czekał na wygraną.",
        "Za każdym razem, gdy ktoś uznaje, że osiągnął sukces, postęp się zatrzymuje.",
        "Żaden problem nie jest w stanie oprzeć się natarciu nieustannego myślenia.",
        "Szczęście to moment, gdy nadchodzi okazja, a ty jesteś na nią przygotowany.",
        "Sekret sukcesu polega na tym, żeby zacząć.",
        "Najlepszy czas na posadzenie drzewa był 20 lat temu. Drugi najlepszy czas jest teraz.",
        "Trudno pokonać człowieka, który nigdy się nie poddaje.",
        "Napisz to. Nakręć to. Opublikuj to. Zrób na szydełku, podsmaż. Cokolwiek, twórz!",
        "Czymkolwiek jesteś, bądź dobry.",
        "Szczęście nie jest czymś gotowym, pochodzi z twoich własnych działań.",
        "Mądrzy ludzie uczą się od wszystkiego i od wszystkich.",
        "Niemożliwe to tylko opinia.",
        "Twoja pasja czeka, aż twoja odwaga ją dogoni.",
        "Ludzie, którzy zastanawiają się, czy szklanka jest do połowy pusta, czy do połowy pełna, nie rozumieją istoty. Szklankę można napełnić ponownie.",
        "Pewnego dnia albo pierwszy dzień; ty decydujesz.",
        "Rzeczy mogą przyjść do tych, którzy czekają, ale tylko te pozostawione przez tych, którzy działają.",
        "Wszystko przychodzi do tego, kto się stara, czekając.",
        "Pracuj tak, jakby ktoś pracował 24 godziny na dobę, żeby ci to odebrać.",
        "Nikt nigdy nie zrobił różnicy, będąc jak wszyscy inni.",
        "Będziesz miał złe chwile, ale zawsze obudzą cię na dobre rzeczy, na które nie zwracałeś uwagi.",
        "Bądź pierwszorzędną wersją siebie, nie drugorzędną wersją kogoś innego.",
        "Ucz się na błędach innych. Nie żyjesz wystarczająco długo, żeby popełnić je wszystkie sam.",
        "Jeśli jesteś zmęczony, rób to zmęczony.",
        "Człowiek nie jest skończony, kiedy zostaje pokonany, jest skończony, kiedy się poddaje.",
        "Świat zmienia się dzięki twojemu przykładowi, nie twojej opinii.",
        "Życie jest jak jazda na rowerze. Żeby utrzymać równowagę, musisz się poruszać.",
        "Myśląc o życiu: żadna ilość poczucia winy nie zmieni przeszłości, żadna ilość niepokoju nie zmieni przyszłości.",
        "Negatywny umysł nigdy nie da ci pozytywnego życia.",
        "Wszystko jest trudne, zanim stanie się łatwe.",
        "Zaryzykuj albo strać szansę.",
        "Nigdy nie przestawaj się uczyć, bo życie nigdy nie przestaje uczyć.",
        "Człowiek, który nie czyta, nie ma żadnej przewagi nad człowiekiem, który nie umie czytać.",
        "Człowiek, który nigdy nie popełnił błędu, nigdy nie próbował niczego nowego.",
        "Najczęstszym sposobem, w jaki ludzie rezygnują ze swojej mocy, jest myślenie, że jej nie mają.",
        "Bądź wdzięczny za to, co masz; skończysz z większą ilością. Koncentruj się na tym, czego nie masz, a nigdy nie będziesz miał dość.",
        "Najtrudniejszą rzeczą jest decyzja o działaniu, reszta to jedynie wytrwałość.",
        "Wiele porażek życiowych to ludzie, którzy nie zdawali sobie sprawy, jak blisko byli, gdy się poddali.",
        "Nie chodzi o to, czy zostaniesz powalony, ale o to, czy wstaniesz.",
        "Pesymista widzi trudność w każdej okazji. Optymista widzi okazję w każdej trudności.",
        "Nasza największa chwała nie polega na tym, że nigdy nie upadamy, ale na tym, że wstajemy za każdym razem, gdy upadniemy.",
        "Nie daj się popychać lękom w swoim umyśle; pozwól się prowadzić marzeniom w swoim sercu.",
        "Kiedy wiesz, czego chcesz, i chcesz tego wystarczająco mocno, znajdziesz sposób, żeby to zdobyć.",
        "Zacznij od tego, co konieczne, potem rób to, co możliwe, i nagle robisz rzeczy niemożliwe.",
        "Bez pasji nie masz energii, bez energii nie masz niczego.",
        "Nie musisz być wielki, żeby zacząć, ale musisz zacząć, żeby być wielkim.",
        "Siła nie pochodzi z fizycznych zdolności, pochodzi z niezłomnej woli.",
        "Nikt nie jest bezużyteczny na tym świecie, kto ulży ciężarowi drugiego człowieka.",
        "Prosząc o niemożliwe, otrzymujemy to, co możliwe.",
        "Lepiej być lwem przez jeden dzień niż owcą przez całe życie.",
        "Życie jest zbyt ważne, żeby je traktować poważnie.",
        "Początek jest połową każdego działania.",
        "Nieskończona cierpliwość przynosi natychmiastowe rezultaty.",
        "Prawie wszyscy ludzie umierają z powodu swoich lekarstw, a nie chorób.",
        "Są zdolni, bo myślą, że są zdolni.",
        "Wyobraźnia jest ważniejsza niż wiedza.",
        "Wytrwali ludzie zaczynają swój sukces tam, gdzie inni kończą w porażce.",
        "Nie ma jasnych ścieżek. Są tylko pułapki, sidła i ciemność.",
        "Błąd dowodzi, że ktoś przestał mówić na tyle długo, żeby coś zrobić.",
        "Cokolwiek warte jest robienia, warte jest robienia dobrze.",
        "Najpotężniejszy jest ten, kto panuje nad sobą.",
        "Uczony, który pielęgnuje umiłowanie wygody, nie zasługuje na miano uczonego.",
        "Dobrobyt bardziej zależy od pragnienia tego, co masz, niż od posiadania tego, czego pragniesz.",
        "Każdy dzień przynosi swoje dary, rozwiąż wstążki.",
        "Sukces nigdy nie jest trwały, a porażka nigdy nie jest ostateczna.",
        "Nic nie trwa wiecznie. Nawet twoje kłopoty.",
        "Ciężka praca nie gwarantuje sukcesu, ale zwiększa jego szanse.",
        "Pokoju nie można utrzymać siłą. Można go osiągnąć jedynie przez zrozumienie.",
        "Kto nie ryzykuje, ten nie ma szczęścia.",
        "Nie mów, że gdy będziesz miał czas wolny, będziesz się uczył; możesz nie mieć czasu wolnego.",
        "Kto traci wiarę, traci wszystko.",
        "Myśl człowieka jest jego światem. To, co człowiek myśli, tym się staje.",
        "Przygoda nie jest poza człowiekiem, jest w nim.",
        "W grze życia nie chodzi o to, żeby mieć dobre karty, ale o to, żeby dobrze zagrać słabą ręką.",
        "Kwaśne, słodkie, gorzkie, ostre; wszystko trzeba spróbować.",
        "Nigdy nie pozwól, by poczucie przeszłej porażki pokonało twój następny krok.",
        "Jeśli nie jesteś ambitny, nie robisz postępów.",
        "Przyszłość należy do tych, którzy się odważą.",
        "Fakty nie przestają istnieć, ponieważ są ignorowane.",
        "Nigdy nie powinniśmy zakładać tego, czego nie da się udowodnić.",
        "Głośny głos nie może konkurować z jasnym głosem, nawet jeśli to szept.",
        "Zachowuj się tak, jakbyś spodziewał się dotrzeć do strefy końcowej.",
        "Szczęście jest naturalnym kwiatem obowiązku.",
        "\"Nie\" oznacza po prostu zacząć od nowa na wyższym poziomie.",
        "Entuzjazm porusza świat.",
        "Mistrz to ktoś, kto wstaje, kiedy nie może.",
        "Przeszkody są ceną wielkości.",
        "Pytanie nie brzmi, kto mi pozwoli, ale kto mnie powstrzyma.",
        "Nie byłem tam, żeby rywalizować, byłem tam, żeby wygrać.",
        "Przestań narzekać, zacznij harować.",
        "Z trudności rosną cuda.",
        "Nie boję się, urodziłam się, żeby to robić.",
        "Nigdy nie pochylaj głowy. Trzymaj ją wysoko. Patrz światu prosto w oczy.",
        "Rób to, co musisz robić, dopóki nie będziesz mógł robić tego, co chcesz.",
        "Jeśli wczoraj upadłeś, dziś wstań.",
        "Niech każdy dzień będzie twoim arcydziełem.",
        "Krew, pot i szacunek. Pierwsze dwa dajesz, ostatni zdobywasz.",
        "Bądź tak dobry, żeby nie mogli cię zignorować.",
        "Pokaż światu, jak bardzo będziesz walczyć o krąg zwycięzców.",
        "Jeśli nie zaprojektujesz swojego własnego planu życia, prawdopodobnie wpadniesz w czyjś inny plan. Co oni dla ciebie zaplanowali? Niewiele.",
        "Jedyną osobą, którą masz się stać, jest osoba, którą zdecydujesz się być.",
        "Nie czekaj, aż żelazo się rozgrzeje; rozgrzej je, uderzając.",
        "Nie mogę uwierzyć, że Bóg umieścił nas na tej ziemi, żebyśmy byli przeciętni.",
        "Chcę, żeby świat był lepszy, dlatego że tu byłem.",
        "Nawyk wytrwałości jest nawykiem zwycięstwa.",
        "Nie bój się zrezygnować z dobrego, żeby sięgnąć po wspaniałe.",
        "Rób swój obowiązek i trochę więcej, a przyszłość sama o siebie zadba.",
        "Życie ma sposób na testowanie woli człowieka. Albo nic się nie dzieje, albo wszystko dzieje się naraz.",
        "Mądry człowiek zawsze może być znaleziony sam. Słaby człowiek zawsze może być znaleziony w tłumie.",
        "Odważyć się to stracić równowagę na chwilę. Nie odważyć się to stracić siebie.",
        "Strach pokonuje więcej ludzi niż cokolwiek innego na świecie.",
        "Najpotężniejsze słowa we wszechświecie to te, których używasz, rozmawiając ze sobą.",
        "Jedyne, co przychodzi do śpiącego człowieka, to sny.",
        "Jeśli nie pokonasz siebie, zostaniesz pokonany przez siebie.",
        "Bohater to ktoś, kto potrafi wytrzymać o jedną minutę dłużej.",
        "Idź tak daleko, jak widzisz, gdy tam dotrzesz, będziesz mógł zobaczyć dalej.",
        "Nie odkrywasz swojego miejsca na świecie, sam je sobie wykuwasz.",
        "Zwycięzcy skupiają się na wygrywaniu. Przegrani skupiają się na zwycięzcach.",
        "Porażka nigdy mnie nie pokona, jeśli moja determinacja do sukcesu jest wystarczająco silna.",
        "To, co przychodzi łatwo, nie trwa. To, co trwa, nie przychodzi łatwo.",
        "Aby uniknąć krytyki: nic nie mów, nic nie rób, bądź nikim.",
        "Człowiek, który robi więcej, niż mu płacą, wkrótce będzie otrzymywał więcej, niż robi.",
        "Geniusz rozpoczyna wielkie dzieła, sam trud je kończy.",
        "Nawet jeśli jesteś na właściwej drodze, zostaniesz przejechany, jeśli będziesz tam po prostu siedzieć.",
        "Jeśli rzeczy nie zawodzą, nie innowujesz wystarczająco.",
        "Wyciągasz z innych to, co najlepsze, kiedy dajesz z siebie to, co najlepsze.",
        "Przywództwo to działanie, nie stanowisko.",
        "Nasza praca jest prezentacją naszych możliwości.",
        "Wszystkie moje problemy kłaniają się przed moim uporem.",
        "Noś swoją porażkę jak odznakę honoru.",
        "Jesteśmy ograniczeni nie przez nasze zdolności, ale przez naszą wizję.",
        "Jeśli jesteś zmęczony, naucz się odpoczywać, a nie rezygnować.",
        "Upadek to wypadek, pozostanie na ziemi to wybór.",
        "Nie waż się poddawać w tym życiu. Nie dziś. Nie jutro. Nigdy.",
        "Nigdy nie daj się złamać osobom ani wydarzeniom.",
        "Niektórzy ludzie marzą o sukcesie, a inni budzą się i ciężko na niego pracują.",
        "Pewność siebie pochodzi z doświadczenia. Doświadczenie pochodzi z prób, porażek i ponownych prób — tym razem lepszych.",
        "Czas prowadzący do mistrzostwa zależy od intensywności naszego skupienia.",
        "Sukces przychodzi tylko do tych, którzy odważą się spróbować.",
        "Jednym z ważnych kluczy do sukcesu jest pewność siebie. Ważnym kluczem do pewności siebie jest przygotowanie.",
        "Wątpliwości zabijają więcej marzeń niż porażka kiedykolwiek.",
        "Zwycięstwo jest zawsze możliwe dla osoby, która odmawia zaprzestania walki.",
        "Nigdy nie zmienisz swojego życia, dopóki nie zmienisz czegoś, co robisz codziennie.",
        "Żeby odnieść sukces, twoje skupienie musi być tak intensywne, że inni myślą, że jesteś szalony.",
        "Przeszkody to te przerażające rzeczy, które widzisz, kiedy odwracasz wzrok od celu.",
        "Znalezienie okazji to kwestia wiary, że ona istnieje.",
        "Wyznaczanie celów to pierwszy krok w zamienianiu niewidzialnego w widzialne.",
        "Jeśli niczym nie ryzykujesz, ryzykujesz wszystkim.",
        "Jeśli nie możesz zmienić swojej sytuacji, zmień swoje nastawienie.",
        "Nieważne jak trudna była przeszłość, zawsze możesz zacząć od nowa.",
        "Jeśli nie odważysz się na nic, to gdy dzień się skończy, nic jest wszystkim, co zyskasz.",
        "Bardzo często zmiana siebie jest bardziej potrzebna niż zmiana otoczenia.",
        "Strach jest największą niepełnosprawnością i sparaliżuje cię.",
        "To, co jest niebezpieczne, to brak ewolucji.",
        "Tak czy inaczej znajdę drogę lub ją stworzę.",
        "Jedyny sposób, żeby uciszyć wszystkich, to wygrać.",
        "Nigdy nie pozwól, żeby wystarczająco dobre było wystarczająco dobre.",
        "Na dłuższą metę trafiamy tylko w to, w co celujemy.",
        "Ciągłe doskonalenie jest lepsze niż opóźniona perfekcja.",
        "Jeśli widzisz to w swoim umyśle, będziesz to trzymał w swojej ręce.",
        "Dziś zrobię to, czego inni nie zrobią, żeby jutro móc robić to, czego inni nie mogą.",
        "Doskonałość to sztuka zdobyta przez trening i nawyk.",
        "Następny rok i tak minie, niezależnie od tego, czy robisz coś ze swoim życiem, czy nie.",
        "Nie zatrzymuj się, kiedy jesteś zmęczony, zatrzymaj się, kiedy skończysz.",
        "Jesteś tylko jeden trening od dobrego nastroju.",
        "Rób to, co słuszne, nie to, co łatwe, ani to, co popularne.",
        "Nic wielkiego nigdy nie przychodziło łatwo.",
        "Bez walki nie ma postępu.",
        "Ludzie sukcesu zadają lepsze pytania i w rezultacie otrzymują lepsze odpowiedzi.",
        "Nie mam specjalnych talentów, jestem jedynie namiętnie ciekawy.",
        "Najlepszą lekcję, jaką dostałem w życiu, dało mi najgorsze uczucie, jakie przeżyłem.",
        "Wyzwania sprawiają, że życie jest interesujące. Pokonywanie ich sprawia, że ma sens.",
        "Naucz się być szczęśliwym z nieskończonego podejścia prób, porażek i nauki.",
        "Jeśli zamkniesz drzwi na wszystkie błędy, prawda zostanie zamknięta na zewnątrz.",
        "Zapomnij o błędzie, zapamiętaj lekcję.",
        "Jeśli możesz robić tylko to, co potrafisz, nigdy nie będziesz kimś więcej niż teraz.",
        "Kto jest mądry? Ten, kto uczy się od każdego.",
        "Tylko ja mogę zmienić swoje życie, nikt nie może zrobić tego za mnie.",
        "Wytrwałość to porażka 19 razy i sukces za 20. razem.",
        "Swój sukces przypisuję temu: nigdy nie dawałam ani nie przyjmowałam wymówek.",
        "Nie jestem produktem moich okoliczności. Jestem produktem moich decyzji.",
        "Nasze czyny definiują nas tak samo, jak my definiujemy nasze czyny.",
        "Tylko skrajnie ignoranccy lub skrajnie inteligentni mogą oprzeć się zmianom.",
        "Człowiek, który ma pewność siebie, zdobywa pewność innych.",
        "To, czego szukasz, szuka ciebie.",
        "Nie martw się porażką. Musisz mieć rację tylko raz.",
        "Bezpieczeństwo jest w większości przesądem. Życie jest albo śmiałą przygodą, albo niczym.",
        "Stajemy się tym, o czym myślimy przez większość czasu, i to jest najdziwniejszy sekret.",
        "Sposób na to, żeby zacząć, to przestać mówić i zacząć działać.",
        "Niech każdy dzień będzie twoim arcydziełem.",
        "Nieważne ile błędów popełniasz lub jak wolno postępujesz, wciąż jesteś daleko przed każdym, kto nie próbuje.",
        "To nasz stosunek na początku trudnego zadania, który bardziej niż cokolwiek innego wpłynie na jego pomyślny wynik.",
        "Jedynym prawdziwym zabezpieczeniem, jakie człowiek będzie miał na tym świecie, jest zasób wiedzy, doświadczenia i umiejętności.",
        "To, co robisz dzisiaj, może zmienić wszystkie jutrzejsze dni twojego życia.",
        "Twoje życie nie poprawia się przez przypadek, poprawia się przez zmianę.",
        "Marzenie nie staje się rzeczywistością przez magię, wymaga potu, determinacji i ciężkiej pracy.",
        "Wiedza to świadomość, że pomidor jest owocem. Mądrość to niewkładanie go do sałatki owocowej.",
        "Nieważne jaka jest sytuacja, przypomnij sobie: \"Mam wybór\".",
        "Rządź swoim umysłem, albo on będzie rządził tobą.",
        "Niektórzy odnoszą sukces, bo są do tego przeznaczeni, ale większość odnosi sukces, bo jest do tego zdeterminowana.",
        "Wielkie możliwości nie są widoczne oczami, są widoczne umysłem.",
        "Kto nie jest wystarczająco odważny, by podejmować ryzyko, niczego w życiu nie osiągnie.",
        "Wiedzieć nie wystarczy, musimy stosować. Chcieć nie wystarczy, musimy działać.",
        "Ambicja jest drogą do sukcesu, wytrwałość jest pojazdem, w którym przybywasz.",
        "Kluczem do życia jest przyjmowanie wyzwań. Kiedy ktoś z tym przestaje, jest martwy.",
        "Zaangażowanie to to, co zamienia obietnicę w rzeczywistość.",
        "Pewność siebie jest pamięcią sukcesu.",
        "Bez pewności siebie jesteśmy jak niemowlęta w kołysce.",
        "Odważ się marzyć, ale jeszcze ważniejsze, odważ się działać zgodnie z marzeniami.",
        "Uczciwość jest pierwszym rozdziałem w księdze mądrości.",
        "Doskonałość to ciągły proces, a nie wypadek.",
        "Nadzieja to umiejętność dostrzegania, że jest światło pomimo całej ciemności.",
        "Musimy zaakceptować skończone rozczarowanie, ale nigdy nie tracić nieskończonej nadziei.",
        "Prawdziwym znakiem inteligencji nie jest wiedza, ale wyobraźnia.",
        "Uzależnij się od stałego i nieustannego samodoskonalenia.",
        "Geniusz to jeden procent inspiracji i dziewięćdziesiąt dziewięć procent wysiłku.",
        "Nie możesz czekać na inspirację, musisz za nią biec z maczugą.",
        "Miej cierpliwość. Wszystkie rzeczy są trudne, zanim staną się łatwe.",
        "Osoba, która mówi, że czegoś nie da się zrobić, nie powinna przerywać osobie, która to robi.",
        "Wytrwałość to ciężka praca, którą wykonujesz po tym, jak zmęczyłeś się ciężką pracą, którą już wykonałeś.",
        "Mądry człowiek może nauczyć się więcej z głupiego pytania niż głupiec z mądrej odpowiedzi.",
        "Dzięki stałej samodyscyplinie i samokontroli możesz rozwinąć wielkość charakteru.",
        "Emocjonalna samokontrola jest wynikiem ciężkiej pracy, a nie wrodzoną umiejętnością.",
        "Umiejętność uczenia się jest najważniejszą umiejętnością w życiu.",
        "Nie pozwól, żeby to, czego nie możesz zrobić, powstrzymywało cię od robienia tego, co możesz.",
        "Na drodze do sukcesu zawsze mijasz porażkę.",
        "Nikt nie jest doskonały, dlatego ołówki mają gumki.",
        "Nigdy nie pozwól, żeby szanse powstrzymały cię od robienia tego, co wiesz w sercu, że miałeś robić.",
        "Jeśli przyjrzysz się uważnie, większość sukcesów z dnia na dzień zajęła dużo czasu.",
        "Wszystko jest możliwe. Wszystko może się zdarzyć.",
        "Nic nie jest szczególnie trudne, jeśli rozłożysz to na małe zadania.",
        "Sekret sukcesu to robienie zwykłych rzeczy nadzwyczaj dobrze.",
        "Działaj tak, jakby to, co robisz, miało znaczenie, bo ma.",
        "To, co zyskujesz, osiągając swoje cele, nie jest tak ważne jak to, kim się stajesz, je osiągając.",
        "Życie jest jak jazda na rowerze; żeby utrzymać równowagę, musisz się poruszać.",
        "Ogranicz swoje \"zawsze\" i \"nigdy\".",
        "Nigdy nie jesteś za stary, żeby wyznaczyć kolejny cel lub wyśnić nowe marzenie.",
        "Nie znajdujesz szczęśliwego życia, tworzysz je.",
        "Zła wiadomość jest taka, że czas leci. Dobra wiadomość jest taka, że ty jesteś pilotem.",
        "Trzymaj twarz zawsze zwróconą ku słońcu, a cienie spadną za tobą.",
        "Różnica między niemożliwym a możliwym leży w determinacji człowieka.",
        "Złote medale tak naprawdę nie są zrobione ze złota. Są zrobione z potu, determinacji i trudnego do znalezienia stopu zwanego odwagą.",
        "Nie lekceważ determinacji spokojnego człowieka.",
        "Nie mów mi, w co wierzysz. Będę obserwował, jak się zachowujesz, i wyciągnę własne wnioski.",
        "Po prostu nienawidzę przegrywać i to daje ci dodatkową determinację do cięższej pracy.",
        "Determinacja do wygrania jest najlepszą częścią wygrywania.",
        "Możesz mieć cały talent świata, ale bez determinacji nie zajdziesz daleko.",
        "Zwycięstwo jest dzieckiem przygotowania i determinacji.",
        "Młody człowiek zna zasady, ale stary człowiek zna wyjątki.",
        "Pesymista narzeka na wiatr, optymista oczekuje, że się zmieni, realista dostosowuje żagle.",
        "Wiedza nie ma wartości, jeśli nie zastosujesz jej w praktyce.",
        "Wolałbym żałować rzeczy, które zrobiłem, niż żałować tych, których nie zrobiłem.",
        "Zrozumienie mądrości wymaga mądrości. Muzyka jest niczym, jeśli publiczność jest głucha.",
        "Większe niebezpieczeństwo dla większości z nas nie polega na wyznaczaniu zbyt wysokich celów i ich nieosiągnięciu, ale w wyznaczaniu zbyt niskich celów i ich osiągnięciu.",
        "W każdym spacerze z naturą otrzymujemy o wiele więcej niż szukamy.",
        "Nie pójdę tam, dokąd prowadzi ścieżka, ale pójdę tam, gdzie nie ma ścieżki, i zostawię ślad.",
        "Dzisiejszy potężny dąb to wczorajszy orzech, który wytrwał.",
        "Bycie całkowicie szczerym z samym sobą jest dobrym ćwiczeniem.",
        "Nie możemy stać się tym, czym musimy być, pozostając tym, czym jesteśmy.",
        "Wyznacz swój kurs według gwiazd, nie według świateł każdego mijającego statku.",
        "Jeśli nie wiesz, dokąd zmierzasz, każda droga cię tam zaprowadzi.",
        "Zawsze będziesz miał dwa wybory: twoje zaangażowanie kontra twój strach.",
        "Błogosławieni ci, którzy dają, nie pamiętając, i biorą, nie zapominając.",
        "To, co się dzieje, nie jest tak ważne jak to, jak reagujesz na to, co się dzieje.",
        "Zacznij od tego, co słuszne, a nie od tego, co akceptowalne.",
        "Człowiek wyższy obwinia siebie. Człowiek niższy obwinia innych.",
        "Najmniejszy czyn jest lepszy niż największe zamiary.",
        "Największą przeszkodą w odkryciu nie jest ignorancja, lecz iluzja wiedzy.",
        "Strzeż się fałszywej wiedzy, jest bardziej niebezpieczna niż ignorancja.",
        "Najlepszym sposobem na przewidzenie przyszłości jest jej wynalezienie.",
        "Wygrywać bez ryzyka to triumfować bez chwały.",
        "Nasz charakter to to, co robimy, kiedy myślimy, że nikt nie patrzy.",
        "Wszystko, co nas irytuje u innych, może prowadzić do zrozumienia nas samych.",
        "Sztuka bycia mądrym to sztuka wiedzieć, co pominąć.",
        "Powiedz mi, a zapomnę. Naucz mnie, a zapamiętam. Zaangażuj mnie, a się nauczę.",
        "Masz mózg w głowie. Masz stopy w butach. Możesz skierować się w dowolnym kierunku, jaki wybierzesz.",
        "W trzech słowach mogę podsumować wszystko, czego nauczyłem się o życiu: toczy się dalej.",
        "Życie polega na próbowaniu rzeczy, żeby zobaczyć, czy działają.",
        "Sukces zwykle przychodzi do tych, którzy są zbyt zajęci, żeby go szukać.",
        "Nie poniosłem porażki, po prostu znalazłem 10 000 sposobów, które nie działają.",
        "Porażkami doszedłem do sukcesu.",
        "Jeśli sam się nie zaprogramujesz, życie cię zaprogramuje.",
        "Nie mam czasu, żeby się nad sobą użalać. Nie mam czasu na narzekanie. Będę szedł dalej.",
        "Jeśli nie jesteś gotów zaryzykować tego, co zwykłe, będziesz musiał zadowolić się tym, co przeciętne.",
        "Sukces został zdefiniowany jako zdolność przechodzenia od porażki do porażki bez utraty entuzjazmu.",
        "Wszystkie nasze marzenia mogą się spełnić, jeśli mamy odwagę ich realizować.",
        "Okazje nie zdarzają się same, to ty je tworzysz.",
        "Nigdy nie marzyłam o sukcesie, pracowałam na niego.",
        "Nie pozwól, żeby to, czego nie możesz zrobić, przeszkadzało w tym, co możesz.",
        "Dziś jest jedyny dzień, wczoraj minął.",
        "Rzeczy układają się najlepiej dla tych, którzy potrafią jak najlepiej wykorzystać to, jak się układają.",
        "Jeśli przechodzisz przez piekło, idź dalej.",
        "Widzisz tylko publiczną chwałę. Nigdy prywatnych poświęceń, żeby do niej dotrzeć.",
        "Jeśli nie cenisz swojego czasu, inni też nie będą.",
        "Nikt nie może sprawić, żebyś czuł się gorszy bez twojej zgody.",
        "Człowiek sukcesu to taki, który potrafi zbudować solidne fundamenty z cegieł, które inni w niego rzucili.",
        "To, co wydaje się nam gorzkimi próbami, jest często ukrytym błogosławieństwem.",
        "Nie ma nic bardziej powszechnego na świecie niż ludzie bez sukcesu z talentem.",
        "Staraj się nie być osobą sukcesu, ale raczej osobą wartościową.",
        "Jeśli nie potrafisz czegoś wytłumaczyć prosto, nie rozumiesz tego wystarczająco dobrze.",
        "Nigdy nie przegrywasz, dopóki nie przestajesz próbować.",
        "Wiedza to świadomość tego, co możesz zrobić. Mądrość to wiedzieć, kiedy tego nie robić.",
        "Życie nie polega na znajdowaniu siebie. Życie polega na tworzeniu siebie.",
        "Problem to nie problem, problemem jest twoje podejście do problemu.",
        "Żadne arcydzieło nie zostało stworzone przez leniwego artystę.",
        "Droga do sukcesu i droga do porażki są prawie dokładnie takie same.",
        "Nie chodzi o to, na co patrzysz, ale o to, co widzisz.",
        "Odwaga to opór wobec strachu — opanowanie strachu, nie jego brak.",
        "Odkrywam, że im ciężej pracuję, tym więcej szczęścia wydaję się mieć.",
        "Ciepło jednej dobrej myśli jest dla mnie warte więcej niż pieniądze.",
        "Wszelki postęp odbywa się poza strefą komfortu.",
        "Myślenie powinno stać się twoim głównym kapitałem, niezależnie od wzlotów i upadków w życiu.",
        "Sukces to suma małych wysiłków powtarzanych dzień po dniu.",
        "Zwycięski wojownik to przeciętny człowiek z laserowym skupieniem.",
        "Sukces nie polega na tym, żeby nigdy nie popełniać błędów, ale żeby nigdy nie popełnić tego samego błędu po raz drugi.",
        "Nie pozwól, żeby strach przed przegraną był większy niż ekscytacja wygraną.",
        "Pierwszy krok to odmówienie bycia więźniem swojego otoczenia.",
        "Na dodatkowej mili nie ma korków.",
        "Kiedy znajdujesz się po stronie większości, czas się zatrzymać i zastanowić.",
        "Sukces to lubienie siebie, lubienie tego, co robisz, i lubienie tego, jak to robisz.",
        "Cel nie zawsze musi być osiągnięty, często służy po prostu jako coś, do czego się celuje.",
        "Lepiej ponieść porażkę w oryginalności niż odnieść sukces w naśladownictwie.",
        "Motywacja sprawia, że zaczynasz, nawyk sprawia, że kontynuujesz.",
        "Musisz wstawać każdego ranka z determinacją, jeśli chcesz kłaść się spać z satysfakcją.",
        "Musisz oczekiwać od siebie wielkich rzeczy, zanim będziesz mógł je osiągnąć.",
        "Prawdziwe trudności mogą być pokonane, tylko te wyimaginowane są nie do pokonania.",
        "Ludzie rzadko odnoszą sukcesy, jeśli nie bawią się tym, co robią.",
        "To w naszych najciemniejszych chwilach musimy się skupić, żeby zobaczyć światło.",
        "Porażka jest przyprawą, która nadaje smak sukcesowi.",
        "Umysły są okiełznane i ujarzmianie przez nieszczęście, ale wielkie umysły wzrastają ponad nie.",
        "Być może będziesz musiał stoczyć bitwę więcej niż raz, żeby ją wygrać.",
        "Co byś zrobił, gdybyś się nie bał?",
        "Dobre rzeczy przychodzą do tych, którzy czekają, ale lepsze rzeczy przychodzą do tych, którzy idą i je zdobywają.",
        "Zawsze dawaj z siebie wszystko, nawet gdy szanse są przeciwko tobie.",
        "Nie czekaj, aż twoje uczucia się zmienią, żeby działać, podejmij działanie, a twoje uczucia się zmienią.",
        "Działanie nie zawsze przynosi szczęście, ale nie ma szczęścia bez działania.",
        "Perfekcja jest nudna, stawanie się lepszym to miejsce, gdzie jest cała zabawa.",
        "Trudno pokonać człowieka, który nigdy się nie poddaje.",
        "Różnica między kamieniem potknięcia a kamieniem milowym zależy od tego, jak wysoko podniesiesz stopę.",
        "Nigdy się nie poddawaj, bo to jest właśnie to miejsce i czas, kiedy przypływ się zmieni.",
        "Czasem nie dostanie tego, czego chcesz, jest cudownym zrządzeniem losu.",
        "Nie mogę zmienić kierunku wiatru, ale mogę dostosować żagle, żeby zawsze dotrzeć do celu.",
        "Idź naprzód. Nie zatrzymuj się, nie zwlekaj w swojej podróży, ale dąż do celu wyznaczonego przed tobą.",
        "Jeśli naprawdę czegoś chcesz, nie czekaj na to, naucz się być niecierpliwym.",
        "Czasem wygrywasz, czasem się uczysz.",
        "Dwa rodzaje ludzi na tym świecie: ci, którzy chcą coś zrobić, i ci, którzy nie chcą popełniać błędów.",
        "Upewnij się, że twój najgorszy wróg nie mieszka między twoimi uszami.",
        "Zawsze pamiętaj, że jesteś absolutnie wyjątkowy, tak jak wszyscy inni.",
        "Jeśli masz wszystko pod kontrolą, nie poruszasz się wystarczająco szybko.",
        "Jednym ze sposobów na utrzymanie rozpędu jest posiadanie stale większych celów.",
        "Nie musisz widzieć całych schodów, po prostu zrób pierwszy krok.",
        "To, co wydaje się nam gorzkimi próbami, jest często ukrytym błogosławieństwem.",
        "Dwie opcje dotyczące zaangażowania: albo jesteś w grze, albo poza nią — nie ma czegoś takiego jak życie pomiędzy.",
        "Kiedy czegoś chcesz, cały wszechświat sprzysięga się, żeby ci pomóc to osiągnąć.",
        "Szczęście nie jest czymś gotowym, pochodzi z twoich własnych działań.",
        "Czymkolwiek jesteś, bądź dobry.",
        "Ból jest nieunikniony, cierpienie jest opcjonalne.",
        "Talent trafia w cel, w który nikt inny nie potrafi trafić; geniusz trafia w cel, którego nikt inny nie potrafi zobaczyć.",
        "Umysł jest swoim własnym miejscem i sam w sobie może uczynić niebo z piekła lub piekło z nieba.",
        "Nienawidziłem trenować, ale powiedziałem sobie 'nie rezygnuj' — cierp teraz i żyj resztę życia jako mistrz.",
        "To nie góry przed tobą cię wyczerpują, to kamyk w bucie.",
        "To, co myślimy, tym się stajemy.",
        "Ktoś dzisiaj siedzi w cieniu, bo ktoś dawno temu posadził drzewo.",
        "Jeden promień słońca wystarczy, żeby rozproszyć wiele cieni.",
        "Dla umysłu, który jest spokojny, cały wszechświat się poddaje.",
        "Dzięki samodyscyplinie prawie wszystko jest możliwe.",
        "Najlepsza droga wyjścia zawsze prowadzi przez.",
        "Twoja wielka szansa może być właśnie tam, gdzie teraz jesteś.",
        "Nic nie jest warte więcej niż ten dzień.",
        "Jedyną podróżą jest ta wewnętrzna.",
        "Okoliczności nie determinują, dokąd możesz dotrzeć, jedynie wyznaczają punkt startowy.",
        "Przekonanie tworzy rzeczywisty fakt.",
        "To, co czyni pustynię piękną, to że gdzieś ukrywa studnię.",
        "Gdyby drzwi percepcji zostały oczyszczone, wszystko ukazałoby się człowiekowi takim, jakim jest — nieskończonym.",
        "Zmień swoje myśli, a zmienisz swój świat.",
        "Ptak jest napędzany własnym życiem i swoją motywacją.",
        "Daj światło, a ludzie znajdą drogę.",
        "Najlepszym przygotowaniem na jutro jest robienie dziś jak najlepiej.",
        "Idee kształtują bieg historii.",
        "Nie na jednej nici nawleczone są wszystkie klejnoty życia.",
        "To, co osiągamy wewnętrznie, zmieni zewnętrzną rzeczywistość.",
        "Twoja własna determinacja do sukcesu jest ważniejsza niż cokolwiek innego.",
        "Wiesz, że jesteś na drodze do sukcesu, kiedy robiłbyś swoją pracę za darmo.",
        "Stajesz się tym, w co wierzysz.",
        "Jeśli chcesz osiągnąć doskonałość, możesz tam dotrzeć dziś. Od tej sekundy przestań wykonywać pracę gorszą niż doskonała.",
        "Jeśli nie jesteś gotów ryzykować tego, co zwykłe, będziesz musiał zadowolić się tym, co przeciętne.",
        "Przed wszystkim innym przygotowanie jest kluczem do sukcesu.",
        "Nauczyłam się przez lata, że kiedy umysł jest zdecydowany, strach maleje.",
        "Życie składa się z wielu rozstań, zespawanych ze sobą.",
        "Wygrywanie nie jest wszystkim, ale chęć wygrywania jest.",
        "Możesz być rozczarowany, jeśli poniesiesz porażkę, ale jesteś skazany na porażkę, jeśli nie spróbujesz.",
        "Błędy są faktem życia, liczy się reakcja na błąd.",
        "Jeśli nie podoba ci się droga, którą idziesz, zacznij budować nową.",
        "Czyny mówią głośniej niż słowa, i nie jest to bardziej prawdziwe niż w przypadku twoich dzieci.",
        "Diament to kawałek węgla, który dobrze poradził sobie pod presją.",
        "Trudne drogi często prowadzą do pięknych miejsc.",
        "Czasami nigdy nie poznasz wartości chwili, dopóki nie stanie się wspomnieniem.",
        "Nic nie może przyćmić światła, które świeci od wewnątrz.",
        "Żeby odnieść sukces w życiu, potrzebujesz trzech rzeczy: kości do życzeń, kręgosłupa i poczucia humoru.",
        "Ci, którzy nie wierzą w magię, nigdy jej nie znajdą.",
        "Zdecydowałam, że nie mogę zapłacić komuś za cofnięcie czasu, więc równie dobrze mogę to zostawić.",
        "Wszystko ma swoją cenę, za ile jesteś gotów zapłacić?",
        "Najbardziej rozwinęłam się nie z powodu zwycięstw, ale porażek.",
        "Mam szczęście, że jakikolwiek strach noszę w sobie, moja chęć wygrywania jest zawsze silniejsza.",
        "Musisz wierzyć w siebie, kiedy nikt inny nie wierzy.",
        "Nie bój się porażki, to jest droga do sukcesu.",
        "Lubię krytykę, sprawia, że stajesz się silniejszy.",
        "Wiem, że chcę zawsze dawać z siebie to, co najlepsze.",
        "Każdy, kogo spotkałem, kto odniósł sukces, jest pracoholikiem.",
        "Nigdy nie rywalizowałem z nikim oprócz siebie.",
        "Wiara w siebie i wiedza o tym, kim jesteś — to fundament wszystkiego, co wielkie.",
        "Boję się nie próbować.",
        "Sposób na odkupienie przeszłości to nie uciekanie od niej, ale próba zrozumienia jej i wykorzystania jako fundamentu do rozwoju.",
        "Bezpieczeństwo nie da ci niczego na tym świecie.",
        "Świetny chwyt to świetny chwyt, ale na marnym wykonawcy po prostu nie działa. Wszystko sprowadza się do talentu.",
        "Albo się rozwijasz, albo znikasz.",
        "Ziarno musi rosnąć, niezależnie od tego, że jest zasadzone w kamieniu.",
        "Nieważne jak ciężko jest, wypiąć pierś, głowę do góry i daj sobie radę.",
        "Zawsze rób wszystko jak najlepiej, nie pozwól, żeby presja wpędzała cię w panikę.",
        "Nigdy nie wiesz, jak i kiedy będziesz miał wpływ na kogoś lub jak ważny może być twój przykład dla kogoś innego.",
        "Rób to, co musisz robić, żeby robić to, co chcesz robić.",
        "Nie aspiruj do zarabiania na życie, aspiruj do robienia różnicy.",
        "Musisz być tym, kim jesteś na tym świecie, bez względu na wszystko.",
        "Jeśli masz wroga, to ucz się i poznaj swojego wroga, nie bądź tylko na niego zły.",
        "Staram się być jak najwspanialsi ludzie, jacy kiedykolwiek żyli.",
        "Tam, gdzie się wyróżniam, to absurdalna, chorobliwa etyka pracy. Wiesz, kiedy inny facet śpi? Ja pracuję.",
        "Życie żyje się na krawędzi.",
        "Bycie realistą to najczęściej podążana droga do przeciętności.",
        "Pierwszy krok to powiedzieć sobie, że potrafisz.",
        "Świat nie może ci powiedzieć, kim jesteś, musisz sam odkryć, kim jesteś, i być sobą na dobre i na złe.",
        "Będziesz musiał zmierzyć się ze swoimi porażkami. Będziesz musiał je zaakceptować i wymyślić, jak je pokonać.",
        "Mój ojciec powiedział mi: ustal swoją cenę na początku. Jeśli kiedykolwiek stanie się to droższe niż cena, którą ustaliłeś, odejdź stamtąd.",
        "Czy wierzyłbyś w to, w co wierzysz, gdybyś był jedynym, który w to wierzy?",
        "Nie obchodzi mnie, co myślą ludzie, bo ludzie nie myślą.",
        "Nigdy nie byłem naprawdę dobry w niczym oprócz zdolności uczenia się.",
        "Najlepsze uczucie na świecie to widzieć korzyści i nagrody ciężkiej pracy.",
        "Moje cele są tak wysokie, że nie mam czasu na relaks w żadnej formie.",
        "Życie jest za krótkie, żeby martwić się tym, co inni mówią o tobie.",
        "Za każdą odnoszącą sukcesy osobą stoi stado hejterów.",
        "Możesz coś zrobić ze swoim życiem, zależy to tylko od twojej determinacji.",
        "Masz wrogów? Dobrze, to znaczy, że faktycznie stanąłeś w obronie czegoś.",
        "Każdy sukces zaczyna się od samodyscypliny, zaczyna się od ciebie.",
        "Z determinacją i odrobiną talentu możesz przenosić góry.",
        "Porażka nie wchodzi w grę, to tylko krok.",
        "Sukces nie przychodzi z dnia na dzień, to jest wtedy, gdy każdego dnia stajesz się trochę lepszy niż dnia poprzedniego; to się wszystko sumuje.",
        "Kiedy życie stawia cię w trudnych sytuacjach, nie mów 'dlaczego ja', powiedz po prostu 'spróbuj mnie'.",
        "Sukces w czymkolwiek zawsze sprowadza się do tego: skupienia i wysiłku. A nad oboma mamy kontrolę.",
        "Kiedyś słyszałem, jak mądry człowiek mówił, że nie ma doskonałych ludzi, są tylko doskonałe intencje.",
        "Bardzo często przestajesz iść, bo mówisz 'jestem zmęczony wspinaniem się na to wzgórze. Nigdy nie dotrzę na szczyt', a jesteś tylko dwa kroki od szczytu.",
        "Rzuć sobie wyzwanie, to jedyna ścieżka prowadząca do rozwoju.",
        "Nie możesz przypisać sobie zasługi za talent, możesz przypisać sobie zasługi jedynie za jego wykorzystanie.",
        "Najlepszym sposobem na zagwarantowanie przegranej jest rezygnacja.",
        "Mogłem patrzeć, jak to się dzieje, albo wziąć w tym udział.",
        "Kiedy coś jest wystarczająco ważne, robisz to, nawet jeśli szanse nie są po twojej stronie.",
        "Jeśli wstajesz rano i myślisz, że przyszłość będzie lepsza, to jest jasny dzień, w przeciwnym razie nie jest.",
        "Można trzymać wszystkie jajka w jednym koszyku, o ile kontrolujesz to, co dzieje się z tym koszykiem.",
        "Jeśli robisz tylko rzeczy, na które znasz odpowiedź z góry, twoja firma zniknie.",
        "Musisz być gotów na niezrozumienie, jeśli chcesz wprowadzać innowacje.",
        "Nie ma złego czasu na innowacje.",
        "Tworzenie okazji oznacza patrzenie tam, gdzie inni nie patrzą.",
        "Wkład w postaci potu jest najcenniejszym kapitałem, jaki istnieje.",
        "Żyjemy w społeczeństwie, w którym prawie zawsze ciężka praca jest nagradzana.",
        "Wszechświat nie ma obowiązku mieć dla ciebie sensu.",
        "Nie ma lepszej edukacji niż ta, która pochodzi z własnej inicjatywy.",
        "Nikt nie jest głupi, kto jest ciekawy.",
        "Nie znam żadnego momentu w historii ludzkości, w którym ignorancja była lepsza od wiedzy.",
        "Wyćwicz się, żeby nie brać niczego do siebie.",
        "Człowiek może zrobić z siebie to, co chce, jeśli naprawdę w to wierzy, musi być gotowy na ciężką pracę i wiele rozczarowań.",
        "To, co każdy z nas musi zrozumieć, to fakt, że nasze intencje zawsze są widoczne.",
        "Nie możemy ignorować tego, co naprawdę chcemy stworzyć.",
        "Tylko ty i ty sam możesz zmienić swoją sytuację.",
        "Bądź wdzięczny za trudne chwile, bo to one cię ukształtowały.",
        "Żeby dołączyć do górnego 1%, musisz robić to, czego 99% nie zrobi.",
        "Stworzyłem swoją własną ścieżkę, była prosta i wąska. Widziałem to tak: albo byłeś na mojej drodze, albo poza nią.",
        "Wszyscy mamy wątpliwości co do siebie. Nie zaprzeczasz im, ale też się im nie poddajesz. Przyjmujesz je.",
        "Wielu liderów ponosi porażkę, bo nie mają odwagi dotknąć tego nerwu.",
        "Moment, w którym się poddajesz, jest momentem, w którym pozwalasz komuś innemu wygrać.",
        "Jeśli boisz się porażki, to prawdopodobnie poniesiesz porażkę.",
        "Zrozumiałem, że zastraszanie tak naprawdę nie istnieje, jeśli jesteś we właściwym stanie umysłu.",
        "To jest moment, w którym akceptuję, że najtrudniejsze czasy zawsze będą za mną i przede mną.",
        "Nikt nie wie, że zostanie mistrzem — musisz na to pracować.",
        "Moje przekonanie jest silniejsze niż twoje wątpliwości.",
        "Sukces oznacza bycie zadowolonym z tego, co robisz każdego dnia. Oznacza bycie dumnym z lepszej osoby, którą się stajesz.",
        "Jeśli chcesz odnieść sukces, musisz być gotowy wykorzystać każdy kontakt, jaki masz.",
        "Talent nigdy nie wystarczy. Z nielicznymi wyjątkami najlepsi gracze są najciężej pracującymi.",
        "Nie poddawaj się, bądź przyjacielem ludzi, którzy pomagają ci ciężko pracować.",
        "Celebruj życie, które miałeś, nie życie, które mogłeś mieć.",
        "Wychowałem się w biedzie, ale nie miałem biednych marzeń.",
        "Jesteś jedynym, który może zrobić różnicę. Jakikolwiek jest twój sen, realizuj go.",
        "Życie nie zatrzymuje się, bo coś ci się przydarzy.",
        "W życiu wygrywanie i przegrywanie będą się zdarzać, ale poddanie się jest nigdy nie do zaakceptowania.",
        "Czy wiecie, ile razy w życiu zostałem odrzucony? Ile razy powiedziano mi, że nie mogę czegoś osiągnąć?",
        "Wielokrotnie odkrywam, że ludzie obdarzeni największym talentem nigdy nie rozwijają tego nastawienia. A ci, którzy nie są tak obdarzeni, są najbardziej rywalizujący i mają największe serce.",
        "Myślałem, że nigdy nie dostanę szansy na grę, aż pewnego razu ją dostałem, bo byłem przygotowany i okazja się pojawiła.",
        "Po prostu uwielbiam rywalizację i próby doskonalenia się.",
        "Zbyt często w życiu coś się dzieje i obwiniamy innych za to, że nie jesteśmy szczęśliwi, spełnieni czy usatysfakcjonowani.",
        "Twoje życie będzie tym, co z niego zrobisz.",
        "Nie zamierzam się denerwować, bo ktoś powiedział o mnie coś złego.",
        "Nie możesz siedzieć na ławce rezerwowych w życiu.",
        "Moje przesłanie jest proste: przejmij kontrolę nad swoim życiem.",
        "Kiedy jesteś jednym z liderów zespołu, nie ma dni wolnych.",
        "Nie polegaj na innych. Będziesz miał wielkie wsparcie od wielu ludzi, oczywiście. Ale nikt ci niczego nie podaruje.",
        "Rzeczy nie poprawiają się same; musisz wyjść i ciężko pracować, żeby je naprawić.",
        "Jeśli nie grasz, żeby wygrać, nie graj wcale.",
        "Jeśli nie wierzysz w siebie, dlaczego ktokolwiek inny miałby w ciebie wierzyć.",
        "Czasem w życiu największe wyzwania okazują się najlepszymi rzeczami, jakie ci się przydarzyły.",
        "Po prostu uwielbiam ciężko pracować.",
        "Prawdziwi konkurenci to ci, którzy zawsze grają, żeby wygrać.",
        "Nie gań się za pieniędzmi, gań się za marzeniem.",
        "Jeśli chcesz latać, musisz pozbyć się rzeczy, które cię ciągną w dół.",
        "Nie chcę, żebyś marzył, chcę, żebyś działał.",
        "Każdy, kto chce być kimś, będzie pracował tak ciężko, jak to możliwe, żeby spełnić to marzenie.",
        "Nigdy nie próbowałem ukryć faktu, że moim zamiarem jest stać się najlepszym.",
        "Jeśli nie wierzysz, że jesteś najlepszy, to nigdy nie osiągniesz wszystkiego, do czego jesteś zdolny.",
        "Dzisiaj są okazje, o których nikt nie wie, czy pojawią się ponownie w przyszłości.",
        "Talent bez ciężkiej pracy jest niczym.",
        "Nie przeszkadza mi, że ludzie mnie nienawidzą, bo to mnie napędza.",
        "Talent to nie wszystko. Możesz go mieć od kołyski, ale konieczna jest nauka rzemiosła, żeby być najlepszym.",
        "Czuję nieskończoną potrzebę uczenia się, doskonalenia, ewolucji — żeby czuć się z siebie zadowolonym.",
        "Twoja miłość czyni mnie silnym. Twoja nienawiść czyni mnie nie do zatrzymania.",
        "Możesz pokonać wszystko, jeśli i tylko jeśli kochasz coś wystarczająco mocno.",
        "Odnoszę sukces, bo poświęciłem się dla sukcesu.",
        "Moją ambicją jest zawsze stawać się coraz lepszym.",
        "Zaczynam wcześnie i kończę późno. Dzień po dniu, rok po roku, zajęło mi 17 lat i 114 dni, żeby stać się sukcesem z dnia na dzień.",
        "Osobą, która mnie powstrzymywała od szczęścia, byłem ja sam.",
        "Prosty akt zwracania uwagi może cię zaprowadzić bardzo daleko.",
        "Nie myl prawdy z opinią mas. Te prawie nigdy nie są nawet zdalnie podobne.",
        "Jest różnica między znaniem drogi a podążaniem nią.",
        "Nie mam czasu na siedzenie całą noc i martwienie się o to, co ktoś, kto mnie nie kocha, ma do powiedzenia o mnie.",
        "Nie możesz wahać się co do tego, kim jesteś.",
        "Zawsze jest nad czym pracować, nigdy tam nie docierasz.",
        "Chcę być tym, czym zawsze chciałem być: dominującym.",
        "Po prostu staram się być najlepszy, jak mogę, i mam nadzieję, że to jest najlepszy wynik w historii.",
        "Nie chcę być tak dobry, jak kiedyś byłem, chcę być lepszy.",
        "Mój umysł jest moim największym atutem. Spodziewam się wygrać każdy turniej, w którym gram.",
        "Ci, którzy naprawdę kontrolują swoje emocje, wygrają.",
        "Nieważne jak dobry się staniesz, zawsze możesz być lepszy, i to jest ekscytująca część.",
        "Żeby pomagać innym, musisz najpierw nauczyć się pomagać sobie.",
        "Nic wartościowego nie przychodzi, jeśli nie jest wynikiem ciężkiej pracy.",
        "Nie pozwolę nikomu poniżyć mojej duszy, zmuszając mnie do nienawiści.",
        "Nie możesz trzymać człowieka na dole, nie będąc na dole razem z nim.",
        "To charakter, nie okoliczności, kształtuje człowieka.",
        "Są dwa sposoby na używanie swojej siły: jeden to pchanie w dół, drugi to ciągnięcie w górę.",
        "Poniosłem porażkę o wiele więcej razy, niż odniosłem sukces.",
        "Robię dziś to, czego inni nie zrobią, żeby jutro osiągnąć to, czego inni nie mogą.",
        "Nawet jeśli przegrasz, nie trać lekcji.",
        "Najłatwiej sprzedać prawdę.",
        "Nie czekaj na idealny moment, będziesz czekać wiecznie. Zawsze wykorzystuj czas, który ci dano, i zrób go idealnym.",
        "Możesz robić tylko tyle rzeczy świetnie i powinieneś odrzucić wszystko inne.",
        "Życie jest kruche. Nie mamy zagwarantowanego jutra, więc daj z siebie wszystko.",
        "Nie boję się zrobić z siebie głupca.",
        "Szacunek mnie motywuje, nie sukces.",
        "Kiedy przejdziesz przez szczyt, wtedy nabierasz prędkości.",
        "Doskonałość to nie akt, to nawyk.",
        "Nie dostaniesz szóstki, jeśli boisz się dostać jedynkę.",
        "Popełniasz błędy, żeby nauczyć się dochodzić do dobrych rzeczy.",
        "Bohater to ktoś, kto dobrowolnie wkracza w nieznane.",
        "Są miliony ocalałych. Niech będzie milion i jeden.",
        "Nigdy się nie poddawaj, bo nigdy nie wiesz, co przyniesie przypływ następnego dnia.",
        "Gdyby to było łatwe, każdy by to robił. To trudność czyni to wielkim.",
        "Jeśli dokonujesz tylko bezpiecznych wyborów, nie rozwijasz się.",
        "Lubię robić coś, czego się boję.",
        "Proces jest najpiękniejszą częścią.",
        "Łatwo oszukać oko, ale trudno oszukać serce.",
        "Nigdy nie bądź za wysoko, nigdy nie bądź za nisko. Bierz to dzień po dniu i po prostu ucz się dalej.",
        "Wysiłek nigdy nie będzie kwestionowany.",
        "Nie licz na to, że ktoś da ci szansę: stwórz ją sobie sam.",
        "Kiedy ludzie mówili mi, że nigdy mi się nie uda, słuchałem jedynej osoby, która mówiła, że mogę: mnie.",
        "Jest powód, dla którego mówi się gonić za marzeniami, a nie spacerować za nimi.",
        "Żeby mieć to, czego naprawdę chcesz, musisz najpierw być tym, kim naprawdę jesteś.",
        "Nie pozwól, żeby przeszłość cię prześladowała. Bo to, co robisz w teraźniejszości, może prześladować twoją przyszłość, bądź mądry. To, co robisz teraz lub w przyszłości, nigdy nie zamaskuje twojej przeszłości, ale to nie znaczy, że masz pozwolić przeszłości sobą rządzić.",
        "To \"a co jeśli\" to rana, która nigdy się nie goi.",
        "Gdyby to było łatwe, nie byłoby tego warte.",
        "Nie zasługujesz na nic, zarabiasz na to.",
        "Perfekcja nie jest interesująca, wyjście na prowadzenie mimo prób losu: to mnie imponuje.",
        "Nie bierz udziału w olimpiadzie \"współczujcie mi\"; w tym nie startujemy.",
        "Kiedy czegoś chcesz, akceptujesz teren, który z tym idzie, jakikolwiek by nie był.",
        "Prawdziwa wizja jest wtedy, gdy twój umysł jest potężniejszy niż to, co masz przed oczami.",
        "Pewne wydarzenia cię rozwiną, pewne wydarzenia zrobią coś przeciwnego — jak się wydaje. Te przeciwności są okazjami do nauki, które okażą się przydatne w przyszłości.",
        "Zapłać cenę za bycie szefem albo zapłać cenę, jaką niesie żal.",
        "Opinia innych ludzi o tobie nie musi stać się twoją rzeczywistością.",
        "Nie dostajesz tego, czego sobie życzysz, dostajesz to, na co pracujesz.",
        "Samodyscyplina zaczyna się od opanowania myśli. Jeśli nie kontrolujesz tego, co myślisz, nie możesz kontrolować tego, co robisz. Mówiąc wprost, samodyscyplina pozwala najpierw myśleć, a potem działać.",
        "Czym jest porażka? Niczym innym jak edukacją; niczym innym jak pierwszym krokiem ku czemuś lepszemu.",
        "Nie chodzi o to, co ci się przydarza, ale o to, jak na to reagujesz.",
        "Kontroluj swój gniew. Jeśli odczuwasz gniew wobec innych, to oni cię kontrolują.",
        "Twoim największym wyzwaniem jest pojawiać się, kiedy twój umysł wymyśla najlepsze wymówki.",
        "Możesz doświadczyć bólu dyscypliny lub bólu żalu. Wybór należy do ciebie.",
        "Wszystko, co czyni cię słabym fizycznie, intelektualnie i duchowo, odrzuć jak truciznę.",
        "Więcej potu w czasie pokoju, mniej krwi w czasie wojny.",
        "Z odwagą, żeby zacząć, i dyscypliną, żeby wytrwać, zwycięstwo staje się kwestią czasu.",
        "Dobry lider to osoba, która bierze na siebie trochę więcej winy i trochę mniej zasług.",
        "Bądź silny, ale nie brutalny. Bądź uprzejmy, ale nie słaby. Bądź odważny, ale nie tyranizuj. Bądź pokorny, ale nie nieśmiały. Bądź dumny, ale nie arogancki.",
        "Cierpliwość jest gorzka, ale jej owoc jest słodki.",
        "Cierpliwość nie jest biernością, wręcz przeciwnie; jest aktywna. Jest skoncentrowaną siłą.",
        "Nie ma nic niemożliwego dla tego, kto chce spróbować.",
        "Inteligencja to nie zdolność przechowywania informacji, ale wiedza, gdzie je znaleźć.",
        "Najpierw to jest intencja. Potem zachowanie. Potem nawyk. Potem praktyka. Potem druga natura. Potem to po prostu to, kim jesteś.",
        "Cokolwiek chcesz zrobić, zrób to teraz. Jest tylko tyle jutrzejszych dni.",
        "Ludzie, którzy mówią, że czegoś nie da się zrobić, nie powinni przerywać tym, którzy to robią.",
        "Jest tylko jeden kąt wszechświata, który na pewno możesz poprawić, i to ty sam.",
        "Głupiec myśli, że jest mądry, ale mądry człowiek wie, że jest głupcem.",
        "Ból może cię zmienić, ale to nie musi być zła zmiana. Weź ten ból i zamień go w mądrość.",
        "Czas to naprawdę jedyny kapitał, jaki ma każdy człowiek, i jedyna rzecz, której nie może sobie pozwolić stracić.",
        "Podążaj własną ścieżką, nieważne co mówią ludzie.",
        "Rób coś. Jeśli działa, rób tego więcej. Jeśli nie, rób coś innego.",
        "Uczenie się jest jedyną rzeczą, której umysł nigdy nie wyczerpie, nigdy się nie boi i nigdy nie żałuje.",
        "Zwycięzca to marzyciel, który nigdy się nie poddaje.",
        "Jeśli nie walczysz o to, czego chcesz, nie płacz nad tym, co straciłeś.",
        "Kiedy zaakceptujesz swoje wady, nikt nie może ich użyć przeciwko tobie.",
        "Kiedy nauczymy się wystarczająco dużo o wszechświecie, przyznamy się sami przed sobą, że nigdy nie będziemy wiedzieć wszystkiego.",
        "Martwienie się jest jak płacenie długu, którego nie jesteś winien.",
        "Nikogo nie możesz niczego nauczyć, możesz tylko sprawić, żeby zdał sobie sprawę, że odpowiedzi są już w nim.",
        "Moc myśli może spowodować zarówno chorobę, jak i uzdrowienie.",
        "Jeśli chcesz zobaczyć cud, bądź cudem.",
        "Istnieją trzy klasy ludzi: ci, którzy widzą, ci, którzy widzą, gdy im się pokaże, i ci, którzy nie widzą.",
        "Twoje największe lęki są stworzone przez twoją wyobraźnię.",
        "Największym oszustwem, jakiemu ulegają ludzie, jest ich własna opinia.",
        "Kiedy wyczerpiesz wszystkie możliwości, pamiętaj: nie wyczerpałeś ich.",
        "Kochaj rękę, jaką los ci rozdał, i graj nią jak swoją własną.",
        "Jeśli dwóch ludzi zgadza się we wszystkim, jeden z nich jest zbędny.",
        "Największą konkurencją jest ta, którą masz z samym sobą.",
        "Kiedy jesteśmy zmęczeni, atakują nas idee, które dawno pokonaliśmy.",
        "Nie jestem tym, co mi się przydarzyło. Jestem tym, czym wybieram się stać.",
        "Najważniejszym czynnikiem przetrwania nie jest ani inteligencja, ani siła, lecz zdolność adaptacji.",
        "Wiara i strach wymagają, żebyś wierzył w coś, czego nie widzisz. Ty wybierasz.",
        "Narzekając, mówisz ludziom, jak słaby jesteś.",
        "Aby zdobyć to, co kochasz, musisz najpierw być cierpliwy wobec tego, czego nienawidzisz.",
        "Kiedy wszystko wydaje się iść przeciwko tobie, pamiętaj, że samolot startuje pod wiatr, a nie z wiatrem.",
        "Będziesz się śmiać ze swoich lęków, kiedy odkryjesz, kim naprawdę jesteś.",
        "Pokój nie leży w spokojniejszej burzy, leży w lepszej łodzi.",
        "Możesz ignorować rzeczywistość, ale nie możesz ignorować konsekwencji ignorowania tej rzeczywistości.",
        "Nikt nie jest bardziej nieszczęśliwy niż ten, kto nigdy nie staje w obliczu przeciwności. Bo nie pozwolono mu się sprawdzić.",
        "Dobry plan brutalnie wykonany teraz jest lepszy niż doskonały plan wykonany za tydzień.",
        "Uczyć się i nie myśleć to marnotrawstwo. Myśleć i nie uczyć się jest niebezpieczne.",
        "Strach jest reakcją. Odwaga jest decyzją.",
        "Niezależność jest dla nielicznych; to przywilej silnych.",
        "Potrzeba połowy życia, zanim odkryjesz, że życie jest projektem do samodzielnej realizacji.",
        "Odgrywaj swoją rolę z honorem.",
        "Martwienie się to niewłaściwe wykorzystanie wyobraźni.",
        "Mostem między wiedzą a umiejętnością jest praktyka. Mostem między umiejętnością a mistrzostwem jest czas.",
        "Im więcej się uczę, tym bardziej uświadamiam sobie, ile jeszcze muszę się nauczyć.",
        "Jeśli nie przegrywasz, nie możesz cieszyć się zwycięstwami. Więc muszę zaakceptować obie rzeczy.",
        "Z zwycięstwa uczymy się mało, z porażki dużo.",
        "Kto mówi z szacunkiem, ale zwiększa swoje przygotowania, ten awansuje. Kto mówi wojowniczo i szybko naciera, ten się wycofa.",
        "Nasze życie jest tym, co nasze myśli z niego czynią.",
        "Tak naprawdę nie ma nic trudnego, chyba że zdecydujesz, że coś jest trudne. W przeciwnym razie to po prostu kolejna rzecz, którą rozgryzasz.",
        "Nieważne jaka jest sytuacja, nigdy nie pozwól, żeby twoje emocje wzięły górę nad twoją inteligencją.",
        "Zdecyduj, jakim typem człowieka chcesz być, i trzymaj się tego, zarówno sam, jak i w towarzystwie.",
        "Jeśli coś jest nie tak, napraw to, jeśli możesz. Ale naucz się nie martwić. Martwienie się nigdy niczego nie naprawia.",
        "Życie to nie kwestia trzymania dobrych kart, ale dobrego grania słabą ręką.",
        "To nierówna droga prowadzi do szczytów wielkości.",
        "W dniu, w którym człowiek staje się wyższy od przyjemności, będzie też wyższy od bólu.",
        "Ucz się ciągle, zawsze jest \"jeszcze jedna rzecz\" do nauczenia się.",
        "Możemy narzekać, że krzewy róż mają ciernie, albo cieszyć się, że krzewy cierniowe mają róże.",
        "Bądź cierpliwy i wytrzymały; pewnego dnia ten ból będzie ci przydatny.",
        "Porażka to sukces w toku.",
        "Każdy, kto przestaje się uczyć, jest stary, czy to w wieku dwudziestu, czy osiemdziesięciu lat.",
        "Jeśli rządzi tobą umysł, jesteś królem; jeśli ciało — niewolnikiem.",
        "Duma nie jest przeciwieństwem wstydu, lecz jego źródłem. Prawdziwa pokora jest jedynym antidotum na wstyd.",
        "Kiedy zaczynasz się doskonalić, samotność jest ceną, jaką płacisz.",
        "Nie jesteś oceniany po wysokości, na jaką się wspiąłeś, ale po głębokości, z jakiej się wdrapałeś.",
        "Człowiek jest wielki nie dlatego, że nie zaznał porażki; jest wielki, bo porażka go nie powstrzymała.",
        "Człowiek bez wizji jest człowiekiem bez przyszłości. Człowiek bez przyszłości zawsze wraca do swojej przeszłości.",
        "Lepiej ponieść porażkę z honorem niż odnieść sukces przez oszustwo.",
        "Wszystkie bitwy są najpierw wygrywane lub przegrywane w umyśle.",
        "Emocje człowieka są poruszane szybciej niż jego inteligencja.",
        "Kto kupuje to, czego nie potrzebuje, okrada samego siebie.",
        "Kto ma cierpliwość, może mieć, co chce.",
        "Ścieżka Wojownika trwa całe życie, a mistrzostwo to często po prostu pozostawanie na ścieżce.",
        "Latawce wznoszą się najwyżej pod wiatr, a nie z wiatrem.",
        "Gdyby ludzie wiedzieli, jak ciężko musiałem pracować, żeby zdobyć swoje mistrzostwo, nie wydawałoby się to takie cudowne.",
        "Nigdy nie idź spać bez prośby do swojej podświadomości.",
        "Witaj wydarzenia, jakkolwiek się zdarzają: to droga do pokoju.",
        "Ćwicz nawet to, co wydaje się niemożliwe.",
        "Człowiek, który goni dwa zające, nie złapie żadnego.",
        "Dasz radę, ale zawsze będziesz czuć, jakbyś sobie nie radził.",
        "Planuj to, co trudne, kiedy jest łatwe; rób to, co wielkie, kiedy jest małe.",
        "Wytrwałość nie wystarczy. Trzeba zdecydować, czy wytrwać jako cierpiący, czy jako wojownik.",
        "Poziom ostrości i dyscypliny potrzebny do osiągnięcia szczytów, o których marzysz, jest naprawdę prosty, tylko nie jest łatwy.",
        "Największy wróg nie znajduje się na zewnątrz. Zniszczenie często przychodzi od wewnątrz.",
        "Wszyscy wiedzieli, że to niemożliwe, aż pojawił się głupiec, który tego nie wiedział, i to zrobił.",
        "Nie możesz wzmocnić słabego człowieka, osłabiając silnego.",
        "Masz władzę nad swoim umysłem — nie nad zewnętrznymi wydarzeniami. Uświadom to sobie, a znajdziesz siłę.",
        "Diament to tylko kawałek węgla, który wytrwał na swoim miejscu.",
        "Największym ryzykiem jest niepodejmowanie żadnego ryzyka.",
        "Jeśli prawidłowo zdefiniujesz problem, prawie masz rozwiązanie.",
        "Przeszłość jest w twojej głowie, przyszłość jest w twoich rękach.",
        "Życie jest dość proste. Robisz różne rzeczy. Większość nie wychodzi. Część wychodzi. Robisz więcej tego, co wychodzi.",
        "Niech twoje poczucie obowiązku przezwycięży atmosferę strachu i tendencję do odkładania aspiracji.",
        "Wszystko, czego zawsze chciałeś, jest po drugiej stronie strachu.",
        "Dyscyplina to wybór między tym, czego chcesz teraz, a tym, czego chcesz najbardziej.",
        "Konformizm jest ostatnim schronieniem ludzi pozbawionych wyobraźni.",
        "Diament to kawałek węgla, który wytrwał w swojej pracy.",
        "Nie ma większej szkody dla człowieka niż zmarnowany czas.",
        "Nie psuj tego, co masz, pragnąc tego, czego nie masz; pamiętaj, że to, co teraz masz, kiedyś było tym, na co tylko miałeś nadzieję.",
        "Człowiek, który jest mistrzem cierpliwości, jest mistrzem wszystkiego innego.",
        "Nigdy nie stawiaj pasji przed zasadami, nawet jeśli wygrasz, przegrasz.",
        "Niektórzy ludzie chcą, żeby się to stało, niektórzy życzą sobie, żeby się to stało, inni sprawiają, że się to dzieje.",
        "Nie wznosimy się do poziomu naszych oczekiwań, spadamy do poziomu naszego treningu.",
        "Łatwiej znaleźć ludzi, którzy dobrowolnie zgodzą się umrzeć, niż tych, którzy są gotowi znosić ból z cierpliwością.",
        "Nie możesz liczyć na podium, jeśli nie bierzesz udziału w wyścigu.",
        "Ten, kto upada i wstaje, jest silniejszy od tego, kto nigdy nie próbował.",
        "Zła wiadomość: nie będziesz 'pasował' do wszystkich. Dobra wiadomość: 'Wielcy' nigdy nie pasują.",
        "Nigdy nie byłem utalentowany, po prostu jestem dobry w nigdy się nie poddawaniu.",
        "Szczęście to nie brak problemów, to zdolność radzenia sobie z nimi.",
        "Jeśli robisz to, co łatwe, twoje życie będzie trudne.",
        "Nie możesz cofnąć się i zmienić początku, ale możesz zacząć od tego, gdzie jesteś, i zmienić zakończenie.",
        "Więcej wyciąga się z przykładu niż z nauki.",
        "Ci, którzy nigdy nie popełniają błędów, pracują dla tych z nas, którzy je popełniają.",
        "Nowy pomysł nie powinien być oceniany po natychmiastowych wynikach.",
        "Nigdy nie jesteś gotowy na to, co musisz zrobić. Po prostu to robisz. I to czyni cię gotowym.",
        "Podejmij ryzyko: jeśli wygrasz, będziesz szczęśliwy; jeśli przegrasz, będziesz mądrzejszy.",
        "Naród, który ceni swoje przywileje wyżej niż swoje zasady, wkrótce straci jedno i drugie.",
        "Najszybsza droga do sensu i sukcesu: wybierz jedną rzecz i daj z siebie wszystko.",
        "Nie bój się zaczynać od nowa. Tym razem nie zaczynasz od zera. Zaczynasz od doświadczenia.",
        "Nie ma nic szlachetnego w byciu lepszym od swojego bliźniego; prawdziwa szlachetność to bycie lepszym od swojego dawnego ja.",
        "Zdobędziesz szacunek wszystkich, jeśli zaczniesz od zdobycia szacunku dla siebie.",
        "Stwórz wizję tego, kim chcesz być, a potem żyj tak, jakby to już było prawdą.",
        "Ceną doskonałości jest dyscyplina. Kosztem przeciętności jest rozczarowanie.",
        "Trudności wzmacniają umysł, tak jak praca wzmacnia ciało.",
        "Nie możesz liczyć na postęp w obszarach, w których nie podjąłeś żadnych działań.",
        "Żadna ilość niepokoju nie zmieni tego, co ma się wydarzyć.",
        "Pokaż mi człowieka o przeciętnych zdolnościach, ale nadzwyczajnym pragnieniu, a pokażę ci zwycięzcę za każdym razem.",
        "Najszybszym sposobem na sukces jest zacząć teraz i rozwiązywać problemy po drodze.",
        "Ludzie nie decydują o swojej przyszłości, decydują o swoich nawykach, a nawyki decydują o ich przyszłości.",
        "Naucz swoje dzieci wcześnie tego, czego sam nauczyłeś się późno.",
        "Jeśli poświęcisz 100 godzin rocznie na jakąkolwiek dyscyplinę (to tylko 18 minut dziennie), będziesz lepszy niż 95% świata w tej dyscyplinie.",
        "Zadanie nie polega na tym, żeby zobaczyć to, czego nikt jeszcze nie widział, ale żeby pomyśleć to, czego nikt jeszcze nie pomyślał o tym, co wszyscy widzą.",
        "Jeśli drażni cię każde otarcie, jak twoje lustro zostanie wypolerowane?",
        "Strach jest głęboki tylko na tyle, na ile pozwala umysł.",
        "Trudność budzi geniusza.",
        "To, co ma dawać światło, musi znosić płomienie.",
        "Nauczyłem się, że sukces nie powinien być mierzony pozycją, jaką ktoś osiągnął w życiu, ale przeszkodami, jakie pokonał, próbując odnieść sukces.",
        "Komfort to najgorsza zależność.",
        "Stajesz się tym, czemu poświęcasz swoją uwagę.",
        "Okoliczności nie tworzą człowieka, jedynie go odsłaniają przed samym sobą.",
        "Nie marnuj więcej czasu na dyskutowanie o tym, jaki powinien być dobry człowiek. Bądź nim.",
        "Kto chce poruszyć świat, niech najpierw poruszy siebie.",
        "Między bodźcem a reakcją jest przestrzeń. W tej przestrzeni jest nasza moc wyboru reakcji. W naszej reakcji leży nasz rozwój i nasza wolność.",
        "Nie ma niczego na zewnątrz ciebie, co mogłoby ci pozwolić stać się lepszym, silniejszym, bogatszym, szybszym czy mądrzejszym. Wszystko jest wewnątrz. Wszystko istnieje. Nie szukaj niczego poza sobą.",
        "Bądź tolerancyjny wobec innych i surowy wobec siebie.",
        "Dwie rzeczy cię definiują: twoja cierpliwość, kiedy nie masz nic, i twoje podejście, kiedy masz wszystko.",
        "Nie budzisz się po prostu i nie stajesz się motylem.",
        "Wytrwałość to zdolność trzymania się, kiedy odpuszczenie wydaje się najbardziej kuszące.",
        "Działanie wiąże się z ryzykiem i kosztami. Ale są one o wiele mniejsze niż długoterminowe ryzyko wygodnej bezczynności.",
        "Żeby osiągnąć wielkie rzeczy, potrzebne są dwie rzeczy: plan i nie do końca wystarczająco dużo czasu.",
        "Wątpliwości mogą być usunięte tylko przez działanie.",
        "Jeśli twoje działania inspirują innych do marzenia więcej, uczenia się więcej, robienia więcej i stawania się kimś więcej, jesteś liderem.",
        "Nie chodzi o posiadanie nienagannego rekordu. Chodzi o uczenie się na blemach w twoim rekordzie.",
        "Bądź wystarczająco odważny, żeby być kiepskim w czymś nowym.",
        "Kładź się spać mądrzejszy niż kiedy się budziłeś.",
        "Powolny sukces buduje charakter, szybki sukces buduje ego.",
        "Tylko dlatego, że ktoś się potknął i zgubił drogę, nie znaczy, że jest zgubiony na zawsze.",
        "Ale nie możemy po prostu siedzieć i wpatrywać się w nasze rany wiecznie.",
        "A teraz, kiedy nie musisz być doskonały, możesz być dobry.",
        "Sukces pochodzi z bezwzględnego wykonywania podstaw.",
        "Potrzeba dużo ciężkiej pracy, żeby uczynić coś prostym.",
        "Każdy myśli o zmienianiu świata, ale nikt nie myśli o zmienianiu siebie.",
        "Zamknięci umysłowo potrzebują, żeby sztuka była im serwowana łyżeczką.",
        "Rób coś zamiast zabijać czas. Bo czas zabija ciebie.",
        "Niech każda decyzja będzie zgodna z twoją wizją.",
        "Jeśli chcesz zrobić coś większego niż przeciętne, nie możesz ulec strachowi przed byciem outsiderem.",
        "To, co liczy się najbardziej, to jak dobrze przechodzisz przez ogień.",
        "Jesteś jedną decyzją od zupełnie innego życia.",
        "Jeśli żyjesz dla jutra, zawsze będziesz dzień w tyle.",
        "Zrób z siebie jak najwięcej, bo to jest wszystko, co masz.",
        "Oczy są bezużyteczne, kiedy umysł jest ślepy.",
        "Na dłuższą metę ludzie trafiają tylko w to, w co celują. Dlatego, choćby mieli od razu ponieść porażkę, lepiej niech celują wysoko.",
        "Kto ma powód, by żyć, może znieść prawie każde jak.",
        "Ludzi można podzielić na dwie grupy: jedni idą naprzód i coś osiągają, a drudzy przychodzą potem i krytykują.",
        "Złe podejście jest jak pusta opona. Nigdzie nie pojedziesz, dopóki go nie zmienisz.",
        "Żaden ptak nie lata zbyt wysoko, jeśli lata własnymi skrzydłami.",
        "Rozwiąż problem albo zostaw problem. Nie żyj z problemem.",
        "Działaj zgodnie ze swoimi zasadami, nie ze swoim nastrojem.",
        "Ci, którzy nie angażują się w nic, są rozpraszani przez wszystko.",
        "Kiedy staramy się stać lepsi niż jesteśmy, wszystko wokół nas również staje się lepsze.",
        "Nie ma pasji w godzeniu się na życie mniejsze niż to, do którego jesteś zdolny.",
        "Człowiek twórczy jest motywowany pragnieniem osiągnięcia, nie pragnieniem pokonania innych.",
        "Życie jest długim przygotowaniem do czegoś, co nigdy się nie zdarza.",
        "Nie słucham już, co ludzie mówią, po prostu obserwuję, co robią. Zachowanie nigdy nie kłamie.",
        "Inteligentne jednostki uczą się od wszystkiego i od wszystkich; przeciętni ludzie od swoich doświadczeń. Głupi mają już wszystkie odpowiedzi.",
        "Pierwsza zasada to zachować spokojnego ducha. Druga to patrzeć rzeczom w twarz i znać je takimi, jakie są.",
        "To zawsze jest walka, żeby podnieść cięższy ciężar.",
        "Człowiek, który boi się cierpienia, już cierpi z powodu tego, czego się boi.",
        "Jeśli człowiek nie wie, do jakiego portu płynie, żaden wiatr nie jest korzystny.",
        "Zawsze robię to, czego nie potrafię, żeby nauczyć się, jak to robić.",
        "Budujesz na porażce. Używasz jej jako kamienia milowego. Zamykasz drzwi na przeszłość. Nie próbujesz zapomnieć o błędach, ale nie rozpamiętujsz ich. Nie dajesz im żadnej swojej energii, czasu ani przestrzeni.",
        "Treść twojego charakteru jest twoim wyborem. Dzień po dniu, to co wybierasz, co myślisz i co robisz, staje się tym, kim się stajesz.",
        "Tchórze nigdy nie rozpoczęli, a słabi zginęli po drodze.",
        "Kiedy wstajesz rano, pomyśl, jakim cennym przywilejem jest być żywym — oddychać, myśleć, cieszyć się, kochać.",
        "Sekret sukcesu to skupienie na celu.",
        "Jedyne, co jest bardziej niebezpieczne od ignorancji, to arogancja.",
        "Jesteśmy tym, co powtarzamy. Doskonałość zatem nie jest aktem, lecz nawykiem.",
        "Podczas gdy czekamy na życie, życie mija.",
        "Sukces to nic innego jak kilka prostych dyscyplin, praktykowanych codziennie.",
        "Im więcej wie, tym bardziej jest świadomy swojej ignorancji.",
        "Przeszkoda w działaniu napędza działanie. To, co stoi na drodze, staje się drogą.",
        "Naszą największą słabością jest poddawanie się. Najpewniejszym sposobem na sukces jest zawsze próbować jeszcze raz.",
        "Klejnot nie może być wypolerowany bez tarcia, a człowiek udoskonalony bez prób.",
        "Twoja wartość polega na tym, kim jesteś, a nie na tym, co masz.",
        "Kto czyni zło, jest bardziej nieszczęśliwy od tego, kto zło ponosi.",
        "Jedną z najprawdziwszych prób uczciwości jest jej stanowcza odmowa kompromisu.",
        "Bóg nic nie daje tym, którzy siedzą z założonymi rękami.",
        "Wiedza o tym, jak myśleć, daje ci potęgę daleko wykraczającą poza tych, którzy wiedzą jedynie, co myśleć.",
        "Jeśli planujesz być czymś mniej niż to, do czego jesteś zdolny, prawdopodobnie będziesz nieszczęśliwy przez całe życie.",
        "Nie ma nic lepszego niż przeciwności losu. Każda porażka, każde złamane serce, każda strata zawiera własne ziarno, własną lekcję, jak poprawić swoje wyniki następnym razem.",
        "Naucz się kochać nienawiść. Przyjmij ją. Ciesz się nią. Zasłużyłeś na nią. Każdy ma prawo do swojej opinii i każdy powinien mieć jedną o tobie. Hejterzy to dobry problem. Nikt nie nienawidzi dobrych. Nienawidzą wielkich.",
        "Zaakceptuj swoją niezdolność do kontrolowania wszystkiego. Zaakceptuj odpowiedzialność za wszystko, co jest pod twoją kontrolą. Zaakceptuj, że istnieją wewnętrzne i zewnętrzne przeszkody. Zaakceptuj, że jesteś wyposażony, by je wszystkie pokonać.",
        "Doświadczenie to najtrudniejszy rodzaj nauczyciela. Najpierw daje ci test, a potem lekcję.",
        "Dojrzewamy dzięki uszkodzeniom, nie dzięki latom.",
        "Jeśli jesteś w depresji, żyjesz w przeszłości. Jeśli jesteś niespokojny, żyjesz w przyszłości. Jeśli jesteś w pokoju, żyjesz w teraźniejszości.",
        "Jeśli myślisz, że nie możemy zmienić świata, to znaczy, że nie jesteś jednym z tych, którzy to zrobią.",
        "Może nie chodzi o szczęśliwe zakończenie. Może chodzi o historię.",
        "Niektórzy ludzie wnoszą radość, gdziekolwiek się pojawią, a inni wnoszą radość, kiedy odchodzą.",
        "Obserwuj stale, że wszystkie rzeczy zachodzą przez zmianę, i przyzwyczaj się do tego, że natura wszechświata nie kocha niczego tak bardzo jak zmiany.",
        "Bycie zbyt dobrym bywa nieinteresujące.",
        "Zbyt często cieszymy się komfortem opinii bez dyskomfortu myślenia.",
        "Studiować bez myślenia to próżność; myśleć bez studiowania to niebezpieczeństwo.",
        "Jeden człowiek z przekonaniem przewyższy setkę, która ma tylko opinie.",
        "Głupcy mnożą się, kiedy mądrzy milczą.",
        "Bądź gotowy zrewidować każdy system, porzucić każdą metodę, odrzucić każdą teorię, jeśli sukces zadania tego wymaga.",
        "Pomaganie innym w rozwoju i sukcesie jest samo w sobie nagrodą i ma wartość tylko wtedy, gdy nie oczekuje się niczego w zamian.",
        "Teraz nie czas myśleć o tym, czego nie masz. Pomyśl o tym, co możesz zrobić z tym, co jest.",
        "Powiedziałbym, że jestem w trakcie ciągłego rozwoju, ale to sugerowałoby, że pewnego dnia przestanę się rozwijać.",
        "Nie poddawaj się. Zazwyczaj to ostatni klucz na pęku otwiera drzwi.",
        "Życie jest komedią dla tych, którzy myślą, tragedią dla tych, którzy czują.",
        "Takt to umiejętność powiedzenia komuś, żeby szedł do piekła, w taki sposób, że nie może się doczekać podróży.",
        "Zostaw krzywdę wyrządzoną przez innego tam, gdzie krzywda powstała.",
        "Nie niepokój się, wyobrażając sobie całe swoje życie naraz. Nie myśl ciągle, jakie cierpienia i ile ich może cię spotkać.",
        "Za każdym razem, gdy myślę, że wiem wszystko, okazuje się, że \"wszystko\" ma trochę większą objętość, niż zakładałem.",
        "Różnica między głupotą a geniuszem polega na tym, że geniusz ma swoje granice.",
        "Lepiej być wojownikiem w ogrodzie niż ogrodnikiem na wojnie.",
        "Wielki sukces zawsze wiąże się z ryzykiem ogromnej porażki.",
        "Sukces pochodzi z ciekawości, koncentracji, wytrwałości i samokrytyki.",
        "Oznaką wykształconego umysłu jest zdolność do rozważania myśli bez jej akceptowania.",
        "Opinia 10 000 ludzi nie ma wartości, jeśli żaden z nich nie zna się na temacie.",
        "Im bardziej cenimy rzeczy poza naszą kontrolą, tym mniej kontroli mamy.",
        "Podróżuj. Próbuj. Nie ma nic innego.",
        "Pochodzenie nigdy nie powinno być barierą dla sukcesu. Skromny start w życiu może być bardziej pomocą niż przeszkodą.",
        "Nie pozwól, żeby niedociągnięcia kogoś innego sprawiły, że sam zaniżysz standardy.",
        "Nasza zazdrość trwa zawsze dłużej niż szczęście tych, którym zazdrościmy.",
        "Z niczego nic nie powstanie.",
        "Słabi ludzie się mszczą. Silni ludzie wybaczają. Inteligentni ludzie ignorują.",
        "Nie kontroluję wiatru; jedynie go studiuję.",
        "Honor może nie zdobyć władzy, ale zdobywa szacunek. A szacunek przynosi władzę.",
        "Ostateczną bronią jest mózg, cała reszta jest uzupełnieniem.",
        "Jeśli nie pokonasz swojej skłonności do łatwego poddawania się, twoje życie nie będzie prowadzić do niczego.",
        "Trening jest jak zamiatanie podłogi. To, że zrobiliśmy to raz, nie oznacza, że podłoga jest czysta na zawsze.",
        "Pamiętaj, że to my siebie dręczymy, to my tworzymy sobie trudności — a raczej nasze opinie to robią. Co na przykład znaczy być znieważonym? Stań przy skale i obraź ją, i co osiągnąłeś? Jeśli ktoś reaguje na obelgę jak skała, co zyskał obraźca swoimi inwektywami?",
        "W braku celu życie staje się niekończącą się podróżą donikąd.",
        "Tylko umarli zobaczyli koniec wojny.",
        "Zapobieganie jest lepsze niż leczenie.",
        "Nic, czego uczy się siłą, nie pozostaje w duszy.",
        "Wszystko, co istnieje w twoim życiu, istnieje z powodu dwóch rzeczy: czegoś, co zrobiłeś, lub czegoś, czego nie zrobiłeś.",
        "Człowiek bez etyki jest dzikim zwierzęciem wypuszczonym na ten świat.",
        "Myślenie jest trudne, dlatego większość ludzi osądza.",
        "Nie znajdujesz silnej woli, tworzysz ją.",
        "Słowo szczęście straciłoby swoje znaczenie, gdyby nie było zrównoważone smutkiem.",
        "Nie módl się o łatwe życie. Módl się o siłę, żeby wytrzymać trudne.",
        "Nie jesteś wszystkim, czym mógłbyś być, i wiesz o tym.",
        "Pamiętaj, żeby żyć, kiedy jesteś zajęty przetrwaniem.",
        "Plany to nic, planowanie to wszystko.",
        "Człowiek, który odważy się zmarnować godzinę czasu, nie odkrył wartości życia.",
        "Musisz zdecydować, kim jesteś, i zmusić świat do radzenia sobie z tobą, a nie z jego wyobrażeniem o tobie.",
        "Sztuka życia bardziej przypomina zapasy niż taniec, o tyle że jest gotowa na to, co przypadkowe i nieprzewidziane, i nie jest skłonna do upadku.",
        "Z wiekiem coraz mniej uwagi poświęcam temu, co ludzie mówią. Po prostu patrzę, co robią.",
        "Wolę zacisnąć pasek niż prosić o pomoc.",
        "Nikt nie jest zbudowany tak jak ty, sam się zaprojektowałeś.",
        "Żaden człowiek nie ma prawa być amatorem w sprawach treningu fizycznego. To wstyd, gdy człowiek starzeje się, nie widząc piękna i siły, do których jego ciało jest zdolne.",
        "Im bliżej człowiek jest spokojnego umysłu, tym bliżej jest siły.",
        "Oto zasada do zapamiętania na przyszłość, gdy cokolwiek kusi cię do goryczy: nie \"To jest nieszczęście\", ale \"Znosić to godnie jest szczęściem.\"",
        "Kiedy jesteś w czymś dobry, powiesz o tym każdemu. Kiedy jesteś w czymś wielki, powiedzą ci o tym inni.",
        "Najpierw cię ignorują. Potem wyśmiewają. Potem atakują i chcą spalić. A potem budują ci pomniki.",
        "Wolność oznacza odpowiedzialność. Dlatego większość ludzi się jej boi.",
        "Jeśli mówisz prawdę, nie musisz niczego pamiętać.",
        "Twój czas nadchodzi, jeśli dalej idziesz naprzód.",
        "Nie śmierci powinien bać się człowiek, ale tego, że nigdy nie zacznie żyć.",
        "Dzisiejsze procedury to jutrzejsze wyniki. Jeśli pokochasz dzisiejsze procedury, pokochasz jutrzejsze wyniki.",
        "Wszystkie problemy ludzkości wynikają z niezdolności człowieka do siedzenia spokojnie w pokoju samemu.",
        "Nigdy nie pozwól, żeby przyszłość cię niepokoiła. Spotkasz ją, jeśli będziesz musiał, z tymi samymi narzędziami rozumu, które dziś zbrojnie cię chronią przed teraźniejszością.",
        "Mężczyzna dojrzewa przez ból, porażkę, odrzucenie, stratę, brak szacunku i złamane serce, nie przez wiek.",
        "Sami kujemy łańcuchy, które nosimy w życiu.",
        "Żeby robić cokolwiek na wysokim poziomie, musi to być obsesją.",
        "Jeśli chcesz się poprawić, pogódź się z byciem uważanym za głupiego i durnego w sprawach zewnętrznych.",
        "Przemoc jest ostatnim schronieniem niekompetentnych.",
        "Strach jest jak ogień, może być pomocny, jeśli wiesz, jak go używać. Jeśli nie, to się sparzysz.",
        "Żeby odnieść wielki sukces, musisz być przygotowany na wielką porażkę. Jeśli nie potrafisz obu, masz problem.",
        "Zawsze mówimy o kimś, kto nas nie lubi \"bez powodu\", ale ludzie będą cię też lubić \"bez powodu\". Więc nie przywiązuj zbyt dużej wagi do żadnej ze stron.",
        "Tchórze umierają wiele razy przed śmiercią; dzielni smakują śmierci tylko raz.",
        "Nic nie jest trudniejsze, a zatem cenniejsze, niż umiejętność podejmowania decyzji.",
        "Podążaj jedną ścieżką, nie stając się zarozumiałym ze zwycięstwa ani złamanym porażką, nie zapominając o ostrożności, gdy jest spokojnie, ani nie przerażając się, gdy grozi niebezpieczeństwo.",
        "Dusza przybiera kolor swoich myśli.",
        "Nie proszę o lżejszy ciężar, ale o szersze ramiona.",
        "Nie negocjuj z sobą. Wydawaj sobie polecenia.",
        "Nie możesz pragnąć jednocześnie silnego charakteru i łatwego życia.",
        "Odwaga to nie posiadanie siły, żeby iść dalej — to iść dalej, kiedy nie masz siły.",
        "Życie nie przydarza się tobie, życie dzieje się z twoim udziałem.",
        "Fatalne jest wchodzenie w wojnę bez woli jej wygrania.",
        "Nigdy nie wiesz, jak silny jesteś, dopóki bycie silnym nie jest twoją jedyną opcją.",
        "Nie da się zadowolić wszystkich, czasem musisz po prostu działać i pozwolić reszcie reagować.",
        "Nie ma kwestii \"czy\", jest kwestia tylko \"kiedy\" — kiedy jesteś zdecydowany w swojej misji.",
        "Jak długo zamierzasz czekać, zanim zażądasz od siebie tego, co najlepsze?",
        "Świat obiecuje ci wygodę, ale nie zostałeś stworzony do wygody. Zostałeś stworzony do wielkości.",
        "Uczciwość to nie szybka droga, ale pewna droga.",
        "Bądź swoim największym fanem, swoim największym zwolennikiem, wrzuć to na swoje plecy i dźwigaj ciężar.",
        "Najpierw powiedz sobie, kim chciałbyś być; a potem rób to, co musisz.",
        "Obawiam się dnia, w którym technologia przewyższy naszą interakcję międzyludzką. Świat będzie miał pokolenie idiotów.",
        "Nie chodzi o to, co znosisz, ale o to, jak to znosisz.",
        "Odrzuć swoje poczucie krzywdy, a sama krzywda znika.",
        "Nie rób małych planów. Nie mają magii, żeby poruszyć krew ludzi i prawdopodobnie same się nie zrealizują. Rób wielkie plany; celuj wysoko w nadziei i pracy, pamiętając, że szlachetny, logiczny diagram raz zapisany nigdy nie umrze, lecz długo po nas będzie żywą rzeczą, narzucającą się z coraz większą siłą.",
        "Przeciwności losu często przygotowują zwykłych ludzi na nadzwyczajne przeznaczenie.",
        "Kiedy chcesz zmieniać rzeczy, nie możesz zadowolić wszystkich. Jeśli zadowalasz wszystkich, nie robisz wystarczających postępów.",
        "Nie negocjuj z sobą, wydawaj sobie polecenia.",
        "Sukces nie jest ostateczny, porażka nie jest fatalna: to odwaga, żeby kontynuować, się liczy.",
        "Jeśli to nie jest słuszne, nie rób tego; jeśli to nie jest prawda, nie mów tego.",
        "Tak zwane przyjemności, kiedy przekraczają pewną granicę, są niczym innym jak karami.",
        "Jeśli nie poświęcasz się dla tego, czego chcesz, to czego chcesz staje się poświęceniem.",
        "Twoim największym wrogiem jest twój niekontrolowany umysł.",
        "Naucz się walczyć, żebyś nigdy nie musiał walczyć.",
        "Kiedy człowiek nie może znaleźć głębokiego poczucia sensu, rozprasza się przyjemnością.",
        "Nic nie jest trwałe na tym niegodziwym świecie, nawet nasze kłopoty.",
        "Niech się mylą w kwestii ciebie. Nie masz im nic do udowodnienia.",
        "Jeśli chcesz, żeby teraźniejszość była inna niż przeszłość, studiuj przeszłość.",
        "Jeśli chcesz żyć szczęśliwym życiem, przywiąż je do celu, nie do ludzi czy przedmiotów.",
        "Nie ma tajemnic, jest tylko informacja, którą odkryłeś, i ta, której jeszcze nie odkryłeś.",
        "Potrzebujesz motywacji do działania. Potrzebujesz informacji, żeby wiedzieć, w co działać. Potrzebujesz ciekawości, żeby zdobyć wiedzę, która będzie poprawnie pilotować te zmotywowane działania. Więc bądź ciekawy.",
        "Zwycięzca to po prostu przegrany, który spróbował jeszcze jeden raz.",
        "Traktujemy ciało rygorystycznie, aby nie było nieposłuszne umysłowi.",
        "Chętni są prowadzeni przez los, niechętni są ciągnięci.",
        "Człowiek, który boi się śmierci, nigdy nie zrobi niczego godnego żywego człowieka.",
        "Dowódca nigdy nie pokłada takiego zaufania w pokoju, żeby nie przygotować się na wojnę.",
        "Nie bój się. Dasz radę, ale zawsze będziesz czuć, jakbyś sobie nie radził.",
        "Konsekwencja może brzmieć bardzo jak nuda, ale co innego myślałeś, że znaczy bycie wielkim? Szczęście?",
        "Trzymaj twarz zawsze zwróconą ku słońcu, a cienie spadną za tobą.",
        "Najcięższą karą za odmowę rządzenia jest bycie rządzonym przez kogoś gorszego od siebie.",
        "Kop w głąb siebie. Wewnątrz jest źródło dobra; i jest zawsze gotowe trysnąć, jeśli tylko będziesz kopać.",
        "Jesteś tym, co robisz, nie tym, co mówisz, że zrobisz.",
        "Błądzić na swój sposób jest lepsze niż mieć rację na czyjś sposób.",
        "Wielki człowiek jest wymagający wobec siebie, słaby człowiek jest wymagający wobec innych.",
        "Kochanie siebie to początek romansu na całe życie.",
        "Przejmuj się tym, co myślą inni, a zawsze będziesz ich więźniem.",
        "Człowiek nie martwi się tak bardzo prawdziwymi problemami, jak swoimi wyobrażonymi lękami o prawdziwe problemy.",
        "Szczęśliwy człowiek jest zadowolony ze swojej obecnej sytuacji, nieważne jaka ona jest.",
        "Pierwszym i największym zwycięstwem jest pokonanie samego siebie.",
        "Żeby się kontrolować, muszę najpierw siebie zaakceptować, idąc z własną naturą, a nie przeciwko niej.",
        "Niech ludzie widzą, niech wiedzą, prawdziwego człowieka, który żyje tak, jak miał żyć.",
        "Kto nie potrafi być posłuszny samemu sobie, będzie dowodzony.",
        "Kiedy czegoś się boisz, dowiedz się o tym jak najwięcej. Wiedza pokonuje strach.",
        "Zawsze myślałem, że to ja przeciwko światu, a potem pewnego dnia zdałem sobie sprawę, że to tylko ja przeciwko sobie.",
        "Człowiek pozbawiony celu rozprasza się przyjemnością.",
        "Trudno zaakceptować, że nie wszyscy \"zrozumieją\"... ale właśnie dlatego to nie jest dla wszystkich. To jest \"twoja\" sprawa.",
        "Im większa trudność, tym więcej chwały w jej pokonaniu.",
        "Zachwycamy się pięknem motyla, ale rzadko przyznajemy się do zmian, przez które przeszedł, aby osiągnąć to piękno.",
        "Pozwól mi upaść, jeśli muszę upaść. Ten, kim się staję, mnie złapie.",
        "Za człowiekiem, który wybacza wszystko, stoi człowiek, który zna ciężar własnych grzechów.",
        "Próba ucieczki od bólu tworzy więcej bólu.",
        "Prawdziwy rozwój nie szanuje komfortu.",
        "Na ile możemy to stwierdzić, jedynym celem ludzkiego istnienia jest rozpalenie światła sensu w ciemności samego istnienia.",
        "Dzień, w którym sadzisz ziarno, nie jest dniem, w którym jesz owoc.",
        "Prawda nie zmienia się, ponieważ jest lub nie jest wierzona przez większość ludzi.",
        "Rycerz w lśniącej zbroi nie ma udowodnionej wartości. Dajcie mi rycerza wypróbowanego w walce, z zbroją obdartą ze spotkań z nikczemnikami ludzkości.",
        "Miarą inteligencji jest zdolność do zmiany.",
        "Nie ma żniw bez głodu.",
        "To sam umysł sprowadza umysł na manowce. Wobec umysłu nie bądź nierozważny.",
        "Nie możesz wyśnić sobie charakteru; musisz go wykuć i ukształtować.",
        "Wiele pójdzie nie tak, zanim wszystko pójdzie dobrze.",
        "Żyjemy tylko teraz. Cała reszta albo minęła, albo jest nieznana.",
        "Nie zostaniesz ukarany za swój gniew, zostaniesz ukarany przez swój gniew.",
        "Nie uczysz się pływać, czytając o wodzie.",
        "Najtrudniejsze wybory wymagają najsilniejszej woli.",
        "Przede wszystkim nie okłamuj samego siebie.",
        "Twoje ciało zniesie prawie wszystko; to umysł musisz przekonać.",
        "Życie jest w gatunku pierwszoosobowym. Traktuj je jako takie.",
        "Dobrzy liderzy nie wymyślają wymówek. Zamiast tego znajdują sposób, żeby to zrobić.",
        "To, że zajęło ci to więcej czasu niż innym, nie znaczy, że poniosłeś porażkę.",
        "Im lepiej znasz siebie, tym mniej potrzebujesz akceptacji innych.",
        "Poznanie siebie jest początkiem wszelkiej mądrości.",
        "Nie wielkość człowieka się liczy, lecz wielkość jego serca.",
        "Jest mało prawdopodobne, żebyś zmienił poziom bez łez.",
        "Orzesz pługiem, który masz.",
    ]
}
