// QuotesLang_sv.swift
// Spike AI — Bundled quote translations (Swedish)
import Foundation
enum QuotesLang_sv {
    static let quotes: [String] = [
        "Vad du än håller i ditt sinne på ett konsekvent sätt är exakt vad du kommer att uppleva i livet.",
        "Vi siktar ovanför målet för att träffa målet.",
        "Det värsta jag kan vara är att vara som alla andra, jag hatar det.",
        "Bara de som vågar gå för långt kan möjligen ta reda på hur långt man kan gå.",
        "Hoppa och nätet kommer att visa sig.",
        "Ett skepp i hamn är säkert, men det är inte det som skepp är byggda för.",
        "Oroa dig inte för misslyckanden, oroa dig för de chanser du missar när du inte ens försöker.",
        "De som vågar misslyckas kan uppnå stordåd.",
        "Sättet att komma igång är att sluta prata och börja göra.",
        "Vi kan möta många nederlag, men vi får inte låta oss besegras.",
        "Det sanna måttet på en människa är hur han behandlar någon som inte kan göra honom det minsta gott.",
        "Man ska vara försiktig om man inte vet vart man är på väg, för man kanske inte kommer dit.",
        "Du måste förvänta dig stora saker av dig själv innan du kan göra dem.",
        "Låt aldrig dina tidigare beslut avgöra ditt framtida resultat.",
        "Genvägar skapar långa förseningar.",
        "Ingen kan ge dig dina mål. Det här är din resa.",
        "Världen är vad du tänker om den, så tänk annorlunda och din värld kommer att förändras.",
        "Framtiden tillhör dem som förbereder sig för den, idag.",
        "Ge inte upp det du vill mest för det du vill just nu.",
        "Berätta inte för mig hur talangfull du är, berätta hur hårt du arbetar.",
        "Hur du tänker när du förlorar avgör hur lång tid det tar innan du vinner.",
        "Närhelst en person bestämmer att framgång har uppnåtts stannar framstegen.",
        "Inget problem kan motstå angreppet av ihållande tänkande.",
        "Tur är när ett tillfälle dyker upp och du är förberedd för det.",
        "Hemligheten med att komma framåt är att komma igång.",
        "Den bästa tiden att plantera ett träd var för 20 år sedan. Den näst bästa tiden är nu.",
        "Det är svårt att slå en person som aldrig ger upp.",
        "Skriv det. Filma det. Publicera det. Virka det, sautera det. Vad som helst, skapa!",
        "Vad du än är, var en bra sådan.",
        "Lycka är inte något färdiggjort, den kommer från dina egna handlingar.",
        "Kloka människor lär sig av allt och alla.",
        "Omöjligt är bara en åsikt.",
        "Din passion väntar på att ditt mod ska komma ikapp.",
        "Människor som undrar om glaset är halvtomt eller halvfullt missar poängen. Glaset kan fyllas på.",
        "En dag eller dag ett; du bestämmer.",
        "Saker kan komma till dem som väntar, men bara det som lämnats av dem som kämpar.",
        "Allt kommer till den som arbetar hårt medan han väntar.",
        "Arbeta som om det finns någon som arbetar 24 timmar om dygnet för att ta det ifrån dig.",
        "Ingen har någonsin gjort skillnad genom att vara som alla andra.",
        "Du kommer att ha dåliga tider, men det väcker dig alltid till det goda du inte uppmärksammade.",
        "Var en förstklassig version av dig själv, inte en andraklassig version av någon annan.",
        "Lär dig av andras misstag. Du kan inte leva tillräckligt länge för att göra dem alla själv.",
        "Om du är trött, gör det ändå trött.",
        "En man är inte färdig när han är besegrad, han är färdig när han ger upp.",
        "Världen förändras av ditt exempel, inte av din åsikt.",
        "Livet är som att cykla. För att hålla balansen måste du fortsätta röra dig.",
        "Tänk på livet: ingen mängd skuld kan ändra det förflutna, ingen mängd ångest kan ändra framtiden.",
        "Ett negativt sinne ger dig aldrig ett positivt liv.",
        "Allt är svårt innan det blir lätt.",
        "Ta risken, eller missa chansen.",
        "Sluta aldrig att lära dig, för livet slutar aldrig att lära ut.",
        "Den som inte läser har ingen fördel jämfört med den som inte kan läsa.",
        "En person som aldrig gjort ett misstag har aldrig provat något nytt.",
        "Det vanligaste sättet människor ger bort sin makt är genom att tro att de inte har någon.",
        "Var tacksam för det du har; du kommer att sluta med mer. Koncentrera dig på det du inte har och du kommer aldrig att ha tillräckligt.",
        "Det svåraste är beslutet att agera, resten är bara envishet.",
        "Många av livets misslyckanden är människor som inte insåg hur nära de var när de gav upp.",
        "Det handlar inte om huruvida du blir nedslagen, utan om du reser dig upp.",
        "Pessimisten ser svårigheter i varje möjlighet. Optimisten ser möjligheter i varje svårighet.",
        "Vår största ära ligger inte i att aldrig falla, utan i att resa oss varje gång vi faller.",
        "Låt dig inte drivas av rädslan i ditt sinne; låt dig ledas av drömmarna i ditt hjärta.",
        "När du vet vad du vill och vill ha det tillräckligt mycket hittar du ett sätt att få det.",
        "Börja med att göra det nödvändiga, gör sedan det möjliga, och plötsligt gör du det omöjliga.",
        "Utan passion har du ingen energi, utan energi har du ingenting.",
        "Du behöver inte vara stor för att börja, men du måste börja för att bli stor.",
        "Styrka kommer inte från fysisk kapacitet, den kommer från en okuvlig vilja.",
        "Ingen är onödig i denna värld som lättar någon annans bördor.",
        "Genom att be om det omöjliga får vi det möjliga.",
        "Det är bättre att vara ett lejon för en dag än ett får hela livet.",
        "Livet är för viktigt för att tas på allvar.",
        "Början är hälften av varje handling.",
        "Oändligt tålamod ger omedelbara resultat.",
        "Nästan alla människor dör av sina botemedel och inte av sina sjukdomar.",
        "De kan, eftersom de tror att de kan.",
        "Fantasi är viktigare än kunskap.",
        "Ihärdiga människor börjar sin framgång där andra slutar i misslyckande.",
        "Det finns inga tydliga vägar. Bara fallgropar och snubbeltrådar och mörker.",
        "Ett misstag bevisar att någon slutade prata tillräckligt länge för att göra något.",
        "Vad som än är värt att göra överhuvudtaget är värt att göra väl.",
        "Mäktigast är den som har sig själv i sin makt.",
        "En lärd som värdesätter bekvämlighet är inte värdig att kallas lärd.",
        "Välstånd beror mer på att vilja det man har än att ha det man vill.",
        "Varje dag kommer med sina egna gåvor, knyt upp banden.",
        "Framgång är aldrig permanent och misslyckande är aldrig slutgiltigt.",
        "Ingenting varar för evigt, inte ens dina problem.",
        "Hårt arbete garanterar inte framgång, men förbättrar dess chanser.",
        "Fred kan inte upprätthållas med våld. Den kan bara uppnås genom förståelse.",
        "Den som inte vågar har ingen tur.",
        "Säg inte att du ska studera när du har tid, du kanske aldrig får tid.",
        "Den som förlorar tron förlorar allt.",
        "Ens egen tanke är ens värld. Vad en person tänker är vad han blir.",
        "Äventyr finns inte utanför en människa, det finns inom henne.",
        "Livets spel handlar inte så mycket om att ha bra kort, utan om att spela dåliga kort väl.",
        "Surt, sött, bittert, skarpt; allt måste provas.",
        "Låt aldrig känslan av tidigare misslyckanden besegra ditt nästa steg.",
        "Om du inte är ambitiös gör du inga framsteg.",
        "Framtiden tillhör dem som vågar.",
        "Fakta upphör inte att existera bara för att de ignoreras.",
        "Vi får aldrig anta det som inte kan bevisas.",
        "En hög röst kan inte tävla med en tydlig röst, även om den är en viskning.",
        "Agera som om du förväntar dig att nå slutzonen.",
        "Lycka är den naturliga blomman av plikt.",
        "\"Nej\" betyder helt enkelt att börja om på en nivå högre.",
        "Entusiasm driver världen.",
        "En mästare är någon som reser sig när han inte kan.",
        "Hinder är kostnaden för storhet.",
        "Frågan är inte vem som ska låta mig, utan vem som ska stoppa mig.",
        "Jag var inte där för att tävla, jag var där för att vinna.",
        "Sluta gnälla, börja kämpa.",
        "Ur svårigheter växer mirakel.",
        "Jag är inte rädd, jag föddes för att göra detta.",
        "Böj aldrig ditt huvud. Håll det högt. Se världen rakt i ögonen.",
        "Gör det du måste göra tills du kan göra det du vill göra.",
        "Om du föll igår, res dig idag.",
        "Gör varje dag till ditt mästerverk.",
        "Blod, svett och respekt. De första två ger du, den sista förtjänar du.",
        "Var så bra att de inte kan ignorera dig.",
        "Visa världen hur mycket du kämpar för vinnarcirkeln.",
        "Om du inte utformar din egen livsplan är chansen stor att du hamnar i någon annans plan. Vad har de planerat för dig? Inte mycket.",
        "Den enda personen du är ämnad att bli är den person du bestämmer dig för att vara.",
        "Vänta inte med att slå tills järnet är varmt; gör det varmt genom att slå.",
        "Jag kan inte tro att Gud satte oss på denna jord för att vara vanliga.",
        "Jag vill att världen ska bli bättre för att jag var här.",
        "Vanan av uthållighet är vanan av seger.",
        "Var inte rädd för att ge upp det goda för att gå efter det fantastiska.",
        "Gör din plikt och lite till, så tar framtiden hand om sig själv.",
        "Livet har ett sätt att testa en persons vilja, antingen genom att ingenting händer alls eller att allt händer på en gång.",
        "En vis man kan alltid hittas ensam. En svag man kan alltid hittas i en folkmassa.",
        "Att våga är att tillfälligt förlora fotfästet. Att inte våga är att förlora sig själv.",
        "Rädsla besegrar fler människor än något annat i världen.",
        "De mest kraftfulla orden i universum är de du använder för att prata med dig själv.",
        "Det enda som kommer till en sovande man är drömmar.",
        "Om du inte besegrar dig själv kommer du att besegras av dig själv.",
        "En hjälte är en som vet hur man håller ut en minut till.",
        "Gå så långt du kan se, när du kommer dit kan du se längre.",
        "Du upptäcker inte din plats i världen, du skapar den.",
        "Vinnare fokuserar på att vinna. Förlorare fokuserar på vinnare.",
        "Misslyckande kommer aldrig att besegra mig om min beslutsamhet att lyckas är tillräckligt stark.",
        "Det som kommer lätt varar inte. Det som varar kommer inte lätt.",
        "För att undvika kritik: säg ingenting, gör ingenting, var ingenting.",
        "Den som gör mer än han får betalt för kommer snart att få betalt för mer än han gör.",
        "Genialitet påbörjar stora verk, bara arbete fulländar dem.",
        "Även om du är på rätt spår blir du överkörd om du bara sitter där.",
        "Om saker inte misslyckas är du inte tillräckligt innovativ.",
        "Du får det bästa av andra när du ger det bästa av dig själv.",
        "Ledarskap är en handling, inte en position.",
        "Vårt arbete är presentationen av våra förmågor.",
        "Alla mina problem böjer sig inför min envishet.",
        "Bär ditt misslyckande som en hedersmedalj.",
        "Vi begränsas inte av våra förmågor, utan av vår vision.",
        "Om du blir trött, lär dig att vila, inte att sluta.",
        "Att falla ner är en olycka, att stanna kvar är ett val.",
        "Våga inte ge upp detta liv. Inte ikväll. Inte imorgon. Aldrig.",
        "Låt aldrig någon slå ner dig, varken personer eller händelser.",
        "Vissa drömmer om framgång medan andra vaknar upp och arbetar hårt för den.",
        "Självförtroende kommer från erfarenhet. Erfarenhet kommer från att försöka och misslyckas och försöka igen, den här gången bättre.",
        "Tiden som leder till mästerskap beror på intensiteten i vårt fokus.",
        "Framgång kommer bara till dem som vågar försöka.",
        "En viktig nyckel till framgång är självförtroende. En viktig nyckel till självförtroende är förberedelse.",
        "Tvivel dödar fler drömmar än misslyckande någonsin gör.",
        "Seger är alltid möjlig för den som vägrar att sluta kämpa.",
        "Du kommer aldrig att förändra ditt liv förrän du förändrar något du gör dagligen.",
        "För att vara framgångsrik måste ditt fokus vara så intensivt att andra tror att du är galen.",
        "Hinder är de skrämmande saker du ser när du tar blicken från ditt mål.",
        "Att hitta en möjlighet är en fråga om att tro att den finns där.",
        "Att sätta mål är det första steget i att göra det osynliga synligt.",
        "Om du inte riskerar något, riskerar du allt.",
        "Om du inte kan ändra din situation, ändra ditt sinne.",
        "Oavsett hur svårt det förflutna är kan du alltid börja om.",
        "Om du inte vågar något, så när dagen är slut är ingenting allt du har vunnit.",
        "Mycket ofta behövs en förändring av jaget mer än en förändring av miljön.",
        "Rädsla är det största handikappet av alla och kommer att förlama dig.",
        "Det som är farligt är att inte utvecklas.",
        "Hur som helst kommer jag att hitta en väg eller skapa en.",
        "Det enda sättet att tysta alla är att vinna.",
        "Låt aldrig tillräckligt bra vara tillräckligt bra.",
        "I det långa loppet träffar vi bara det vi siktar på.",
        "Ständig förbättring är bättre än fördröjd perfektion.",
        "Om du ser det i ditt sinne kommer du att hålla det i din hand.",
        "Idag gör jag det andra inte vill, så imorgon kan jag göra det andra inte kan.",
        "Excellens är en konst som vinns genom träning och vana.",
        "Nästa år kommer att gå oavsett om du gör något åt ditt liv eller inte.",
        "Sluta inte när du är trött, sluta när du är klar.",
        "Du är bara ett träningspass från ett bra humör.",
        "Gör det som är rätt, inte det som är lätt eller populärt.",
        "Inget stort har någonsin kommit så lätt.",
        "Utan kamp kan det inte finnas framsteg.",
        "Framgångsrika människor ställer bättre frågor och får därmed bättre svar.",
        "Jag har inga speciella talanger, jag är bara passionerat nyfiken.",
        "Den bästa läxan jag lärt mig i livet kom från den värsta känslan jag upplevde.",
        "Utmaningar är det som gör livet intressant. Att övervinna dem är det som gör livet meningsfullt.",
        "Lär dig att vara glad med det ändlösa försöka, misslyckas, lära-tillvägagångssättet.",
        "Om du stänger dörren för alla fel kommer sanningen att stängas ute.",
        "Glöm misstaget, kom ihåg läxan.",
        "Om du bara kan göra det du kan göra, kommer du aldrig att bli mer än du är nu.",
        "Vem är vis? Den som lär sig av alla.",
        "Bara jag kan förändra mitt liv, ingen kan göra det åt mig.",
        "Uthållighet är att misslyckas 19 gånger och lyckas den 20:e.",
        "Jag tillskriver min framgång detta: jag gav eller tog aldrig någon ursäkt.",
        "Jag är inte en produkt av mina omständigheter. Jag är en produkt av mina beslut.",
        "Våra handlingar bestämmer oss lika mycket som vi bestämmer våra handlingar.",
        "Bara de extremt okunniga eller extremt intelligenta kan motstå förändring.",
        "Den som har förtroende för sig själv vinner andras förtroende.",
        "Det du söker söker dig.",
        "Oroa dig inte för misslyckande. Du behöver bara ha rätt en gång.",
        "Trygghet är mestadels en vidskepelse. Livet är antingen ett vågat äventyr eller ingenting.",
        "Vi blir det vi tänker på mest av tiden, och det är den märkligaste hemligheten.",
        "Sättet att komma igång är att sluta prata och börja göra.",
        "Gör varje dag till ditt mästerverk.",
        "Oavsett hur många misstag du gör eller hur långsamt du framskrider, är du fortfarande långt före alla som inte försöker.",
        "Det är vår attityd i början av en svår uppgift som, mer än något annat, påverkar dess framgångsrika utgång.",
        "Den enda verkliga tryggheten en människa har i denna värld är en reserv av kunskap, erfarenhet och förmåga.",
        "Vad du gör idag kan förändra alla dina morgondagar.",
        "Ditt liv blir inte bättre av slumpen, det blir bättre av förändring.",
        "En dröm blir inte verklighet genom magi, det krävs svett, beslutsamhet och hårt arbete.",
        "Kunskap är att veta att en tomat är en frukt. Visdom är att inte lägga den i en fruktsallad.",
        "Oavsett situation, påminn dig själv: jag har ett val.",
        "Styr ditt sinne eller så styr det dig.",
        "Vissa lyckas för att de är ämnade att göra det, men de flesta lyckas för att de är beslutsamma.",
        "Stora möjligheter ses inte med ögonen, de ses med sinnet.",
        "Den som inte är modig nog att ta risker kommer inte att åstadkomma något i livet.",
        "Att veta räcker inte, vi måste tillämpa. Att vilja räcker inte, vi måste göra.",
        "Ambition är vägen till framgång, uthållighet är fordonet du anländer i.",
        "Nyckeln till livet är att acceptera utmaningar. När någon slutar med det är han död.",
        "Engagemang är det som förvandlar ett löfte till verklighet.",
        "Självförtroende är minnet av framgång.",
        "Utan självförtroende är vi som spädbarn i en vagga.",
        "Våga drömma, men ännu viktigare, våga sätta handling bakom dina drömmar.",
        "Ärlighet är det första kapitlet i visdomens bok.",
        "Excellens är en kontinuerlig process och inte en slump.",
        "Hopp är att kunna se att det finns ljus trots allt mörker.",
        "Vi måste acceptera ändlig besvikelse, men aldrig förlora oändligt hopp.",
        "Det sanna tecknet på intelligens är inte kunskap, utan fantasi.",
        "Bli beroende av ständig och outtröttlig självförbättring.",
        "Genialitet är en procent inspiration och nittionio procent transpiration.",
        "Du kan inte vänta på inspiration, du måste jaga den med en klubba.",
        "Ha tålamod. Alla saker är svåra innan de blir lätta.",
        "Den som säger att det inte kan göras bör inte avbryta den som gör det.",
        "Uthållighet är det hårda arbete du gör efter att du blivit trött på det hårda arbete du redan gjort.",
        "En vis man kan lära mer av en dum fråga än en dåre kan lära av ett klokt svar.",
        "Genom ständig självdisciplin och självkontroll kan du utveckla karaktärens storhet.",
        "Emotionell självkontroll är resultatet av hårt arbete, inte en medfödd färdighet.",
        "Att lära sig att lära är livets viktigaste färdighet.",
        "Låt inte det du inte kan göra hindra dig från att göra det du kan göra.",
        "Du passerar alltid misslyckande på vägen till framgång.",
        "Ingen är perfekt, det är därför pennor har suddgummin.",
        "Låt aldrig oddsen hindra dig från att göra det du i ditt hjärta vet att du var ämnad att göra.",
        "Om du verkligen tittar noga tog de flesta framgångar över natten lång tid.",
        "Allting är möjligt. Allting kan ske.",
        "Inget är särskilt svårt om du bryter ner det i små uppgifter.",
        "Hemligheten till framgång är att göra de vanliga sakerna ovanligt bra.",
        "Agera som om det du gör gör skillnad, det gör det.",
        "Vad du får genom att nå dina mål är inte lika viktigt som vad du blir genom att nå dem.",
        "Livet är som att cykla; för att hålla balansen måste du fortsätta röra dig.",
        "Begränsa dina \"alltid\" och \"aldrig\".",
        "Du är aldrig för gammal för att sätta ett nytt mål eller drömma en ny dröm.",
        "Du hittar inte det lyckliga livet, du skapar det.",
        "Den dåliga nyheten är att tiden flyger. Den goda nyheten är att du är piloten.",
        "Håll alltid ansiktet mot solskenet så faller skuggorna bakom dig.",
        "Skillnaden mellan det omöjliga och det möjliga ligger i en människas beslutsamhet.",
        "Guldmedaljer är inte gjorda av guld. De är gjorda av svett, beslutsamhet och en svårfunnen legering som kallas mod.",
        "Underskatta inte beslutsamheten hos en tyst man.",
        "Berätta inte vad du tror på. Jag ska observera hur du beter dig och dra mina egna slutsatser.",
        "Jag hatar bara att förlora, och det ger dig en extra beslutsamhet att arbeta hårdare.",
        "Beslutsamheten att vinna är den bättre delen av att vinna.",
        "Du kan ha all talang i världen, men utan beslutsamhet kommer du inte långt.",
        "Seger är barnet av förberedelse och beslutsamhet.",
        "Den unge mannen känner reglerna, men den gamle mannen känner undantagen.",
        "Pessimisten klagar på vinden, optimisten förväntar sig att den ska ändras, realisten justerar seglen.",
        "Kunskap har inget värde om du inte omsätter den i praktiken.",
        "Jag hade hellre ångrat det jag gjort än ångrat det jag inte gjort.",
        "Det krävs visdom för att förstå visdom. Musiken är ingenting om publiken är döv.",
        "Den större faran för de flesta av oss ligger inte i att sikta för högt och missa, utan i att sikta för lågt och träffa.",
        "I varje promenad med naturen får man långt mer än man söker.",
        "Jag vill inte följa dit vägen leder, utan jag vill gå dit det inte finns någon väg och lämna ett spår.",
        "Dagens mäktiga ek är bara gårdagens nöt som höll sin mark.",
        "Att vara helt ärlig mot sig själv är en bra övning.",
        "Vi kan inte bli det vi behöver vara genom att förbli det vi är.",
        "Styr din kurs efter stjärnorna, inte efter ljusen från varje passerande skepp.",
        "Om du inte vet vart du ska tar vilken väg som helst dig dit.",
        "Du kommer alltid att ha två val: ditt engagemang mot din rädsla.",
        "Välsignade är de som ger utan att minnas och tar utan att glömma.",
        "Vad som händer är inte lika viktigt som hur du reagerar på det som händer.",
        "Börja med det som är rätt snarare än det som är acceptabelt.",
        "Den överlägsna mannen klandrar sig själv. Den underlägsna mannen klandrar andra.",
        "Den minsta handlingen är bättre än de största intentionerna.",
        "Det största hindret för upptäckt är inte okunnighet, utan illusionen av kunskap.",
        "Akta dig för falsk kunskap, den är farligare än okunnighet.",
        "Det bästa sättet att förutse framtiden är att uppfinna den.",
        "Att vinna utan risk är att triumfera utan ära.",
        "Vår karaktär är vad vi gör när vi tror att ingen ser.",
        "Allt som irriterar oss hos andra kan leda oss till en förståelse av oss själva.",
        "Konsten att vara vis är konsten att veta vad man ska förbise.",
        "Berätta för mig och jag glömmer. Lär mig och jag minns. Involvera mig och jag lär mig.",
        "Du har hjärnan i ditt huvud. Du har fötterna i dina skor. Du kan styra dig själv i vilken riktning du väljer.",
        "Med tre ord kan jag sammanfatta allt jag lärt mig om livet: det fortsätter.",
        "Livet handlar om att prova saker för att se om de fungerar.",
        "Framgång kommer vanligtvis till dem som är för upptagna för att leta efter den.",
        "Jag har inte misslyckats, jag har bara hittat 10 000 sätt som inte fungerar.",
        "Jag misslyckades mig fram till framgång.",
        "Om du inte programmerar dig själv kommer livet att programmera dig.",
        "Jag har inte tid att tycka synd om mig själv. Jag har inte tid att klaga. Jag ska fortsätta framåt.",
        "Om du inte är villig att riskera det vanliga måste du nöja dig med det ordinära.",
        "Framgång har definierats som förmågan att gå från misslyckande till misslyckande utan att förlora entusiasmen.",
        "Alla våra drömmar kan bli verklighet om vi har modet att förfölja dem.",
        "Möjligheter bara händer inte, du skapar dem.",
        "Jag drömde aldrig om framgång, jag arbetade för den.",
        "Låt inte det du inte kan göra påverka det du kan göra.",
        "Idag är den enda dagen, igår är borta.",
        "Saker fungerar bäst för dem som gör det bästa av hur saker fungerar.",
        "Om du går igenom helvetet, fortsätt gå.",
        "Du ser bara de offentliga framgångarna, aldrig de privata uppoffringarna för att nå dem.",
        "Om du inte värdesätter din tid gör ingen annan det heller.",
        "Ingen kan få dig att känna dig underlägsen utan ditt samtycke.",
        "En framgångsrik man är en som kan lägga en fast grund med de stenar andra kastat på honom.",
        "Det som verkar vara bittra prövningar är ofta förklädda välsignelser.",
        "Inget i världen är vanligare än misslyckade människor med talang.",
        "Försök inte bli en framgångsrik person, försök istället bli en person av värde.",
        "Om du inte kan förklara det enkelt förstår du det inte tillräckligt bra.",
        "Du misslyckas aldrig förrän du slutar försöka.",
        "Kunskap är att vara medveten om vad du kan göra. Visdom är att veta när du inte ska göra det.",
        "Livet handlar inte om att hitta sig själv. Livet handlar om att skapa sig själv.",
        "Problemet är inte problemet, problemet är din attityd till problemet.",
        "Inget mästerverk skapades någonsin av en lat konstnär.",
        "Vägen till framgång och vägen till misslyckande är nästan exakt desamma.",
        "Det är inte vad du tittar på som spelar roll, det är vad du ser.",
        "Mod är motstånd mot rädsla, behärskning av rädsla, inte frånvaro av rädsla.",
        "Jag finner att ju hårdare jag arbetar desto mer tur verkar jag ha.",
        "Glöden av en varm tanke är för mig värd mer än pengar.",
        "Alla framsteg sker utanför komfortzonen.",
        "Tänkande bör bli din främsta tillgång oavsett vilka upp- och nedgångar du möter i livet.",
        "Framgång är summan av små ansträngningar som upprepas dag efter dag.",
        "Den framgångsrika krigaren är den vanliga mannen med laserfokuserat fokus.",
        "Framgång består inte i att aldrig göra misstag, utan i att aldrig göra samma misstag en andra gång.",
        "Låt inte rädslan att förlora vara större än spänningen att vinna.",
        "Första steget är när du vägrar att vara fånge i din omgivning.",
        "Det finns ingen trafikstockning på den extra milen.",
        "Närhelst du befinner dig på majoritetens sida är det dags att pausa och reflektera.",
        "Framgång är att gilla dig själv, gilla det du gör och gilla hur du gör det.",
        "Ett mål är inte alltid menat att nås, det tjänar ofta helt enkelt som något att sikta mot.",
        "Det är bättre att misslyckas i originalitet än att lyckas i imitation.",
        "Motivation är det som får dig igång, vana är det som håller dig igång.",
        "Du måste gå upp varje morgon med beslutsamhet om du ska gå till sängs med tillfredsställelse.",
        "Du måste förvänta dig stora saker av dig själv innan du kan göra dem.",
        "Verkliga svårigheter kan övervinnas, det är bara de inbillade som är oövervinnerliga.",
        "Människor lyckas sällan om de inte har roligt med det de gör.",
        "Det är under våra mörkaste stunder som vi måste fokusera för att se ljuset.",
        "Misslyckande är kryddan som ger framgång dess smak.",
        "Sinnen tyglas och underkuvas av olycka, men stora sinnen reser sig över det.",
        "Du kan behöva utkämpa en strid mer än en gång för att vinna den.",
        "Vad skulle du göra om du inte var rädd?",
        "Bra saker kommer till dem som väntar, men bättre saker kommer till dem som går ut och hämtar dem.",
        "Ge alltid maximal insats, även när oddsen är emot dig.",
        "Vänta inte på att dina känslor ska förändras för att agera; agera och dina känslor kommer att förändras.",
        "Handling kanske inte alltid ger lycka, men det finns ingen lycka utan handling.",
        "Perfektion är tråkigt, att bli bättre är där allt roligt finns.",
        "Det är svårt att slå en person som aldrig ger upp.",
        "Skillnaden mellan en stötesten och ett trappsteg är hur högt du lyfter foten.",
        "Ge aldrig upp för det kan vara just den plats och tid då tidvattnet vänder.",
        "Ibland är det att inte få det du vill ha ett underbart lyckokast.",
        "Jag kan inte ändra vindens riktning, men jag kan justera mina segel för att alltid nå min destination.",
        "Fortsätt framåt. Stanna inte, dröj inte på din resa, utan sträva efter det mål som satts framför dig.",
        "Om du genuint vill ha något, vänta inte på det, lär dig att vara otålig.",
        "Ibland vinner du, ibland lär du dig.",
        "Två sorters människor i denna värld: de som vill få saker gjorda och de som inte vill göra misstag.",
        "Se till att din värsta fiende inte bor mellan dina egna öron.",
        "Kom alltid ihåg att du är absolut unik, precis som alla andra.",
        "Om du har allt under kontroll rör du dig inte tillräckligt snabbt.",
        "Ett sätt att hålla farten uppe är att ständigt ha större mål.",
        "Du behöver inte se hela trappan, ta bara det första steget.",
        "Det som verkar vara bittra prövningar är ofta förklädda välsignelser.",
        "Två alternativ gällande engagemang: antingen är du med eller inte, det finns inget mellanting i livet.",
        "När du vill ha något konspirerar hela universum för att hjälpa dig uppnå det.",
        "Lycka är inte något färdiggjort, den kommer från dina egna handlingar.",
        "Vad du än är, var en bra sådan.",
        "Smärta är oundviklig, lidande är valfritt.",
        "Talang träffar ett mål som ingen annan kan träffa; genialitet träffar ett mål som ingen annan kan se.",
        "Sinnet är sin egen plats och kan i sig göra ett himmelrike av helvetet eller ett helvete av himmelriket.",
        "Jag hatade att träna, men jag sa 'ge inte upp' – lid nu och lev resten av livet som en mästare.",
        "Det är inte bergen framför dig att bestiga som sliter ut dig, det är stenen i din sko.",
        "Det vi tänker, det blir vi.",
        "Någon sitter i skuggan idag, för att någon planterade ett träd för länge sedan.",
        "En enda solstråle räcker för att jaga bort många skuggor.",
        "För det sinne som är stilla överlämnar sig hela universum.",
        "Med självdisciplin är det mesta möjligt.",
        "Den bästa vägen ut är alltid genom.",
        "Din stora möjlighet kan vara precis där du är nu.",
        "Ingenting är värt mer än denna dag.",
        "Den enda resan är den inre.",
        "Omständigheter avgör inte vart du kan gå, de avgör bara var du börjar.",
        "Tro skapar det faktiska faktum.",
        "Det som gör öknen vacker är att den någonstans gömmer en brunn.",
        "Om varseblivningens dörrar rensades skulle allt framstå för människan som det är, oändligt.",
        "Förändra dina tankar och du förändrar din värld.",
        "Fågeln drivs av sitt eget liv och sin motivation.",
        "Ge ljus och människor kommer att hitta vägen.",
        "Den bästa förberedelsen för morgondagen är att göra ditt bästa idag.",
        "Idéer formar historiens gång.",
        "Inte på en enda sträng är alla livets juveler trädda.",
        "Det vi uppnår inombords kommer att förändra den yttre verkligheten.",
        "Din egen beslutsamhet att lyckas är viktigare än något annat.",
        "Du vet att du är på väg mot framgång om du skulle göra ditt jobb utan att få betalt för det.",
        "Du blir det du tror.",
        "Om du vill uppnå excellens kan du nå dit idag. Från och med nu, sluta göra mindre än utmärkt arbete.",
        "Om du inte är villig att riskera det vanliga måste du nöja dig med det ordinära.",
        "Före allt annat är förberedelse nyckeln till framgång.",
        "Jag har lärt mig genom åren att när ens sinne är bestämt minskar rädslan.",
        "Livet är gjort av oerhört många avsked, sammansvetsade.",
        "Att vinna är inte allt, men att vilja vinna är det.",
        "Du kan bli besviken om du misslyckas, men du är dömd om du inte försöker.",
        "Misstag är en del av livet, det är reaktionen på misstaget som räknas.",
        "Om du inte gillar vägen du går, börja bana en ny.",
        "Handlingar talar högre än ord, och det gäller inte minst med dina barn.",
        "En diamant är en kolbit som klarade sig bra under tryck.",
        "Svåra vägar leder ofta till vackra destinationer.",
        "Ibland vet du aldrig värdet av ett ögonblick förrän det blir ett minne.",
        "Inget kan dämpa ljuset som lyser inifrån.",
        "För att lyckas i livet behöver du tre saker: ett önskebone, en ryggrad och ett skrattben.",
        "De som inte tror på magi kommer aldrig att hitta den.",
        "Jag bestämde mig för att jag inte kan betala någon för att spola tillbaka tiden, så jag kan lika gärna komma över det.",
        "Allt kommer till en kostnad, vad är du villig att betala för det?",
        "Jag har vuxit mest, inte av segrar, utan av motgångar.",
        "Jag har tur att oavsett vilken rädsla jag har inombords, är min vilja att vinna alltid starkare.",
        "Du måste tro på dig själv när ingen annan gör det.",
        "Var inte rädd för misslyckande, det är vägen till framgång.",
        "Jag gillar kritik, det gör dig stark.",
        "Jag vet att jag alltid vill göra det bästa jag kan.",
        "Alla jag mött som är framgångsrika är arbetsnarkomaner.",
        "Jag har aldrig tävlat med någon annan än mig själv.",
        "Att tro på sig själv och veta vem du är, det är grunden för allt stort.",
        "Jag är rädd för att inte försöka.",
        "Sättet att återlösa ditt förflutna är inte att fly från det, utan att försöka förstå det och använda det som grund för att växa.",
        "Att spela det säkra ger dig ingenting i den här världen.",
        "En bra gimmick är en bra gimmick, men på en tråkig person fungerar det bara inte. Det handlar om talang.",
        "Antingen utvecklas du eller så försvinner du.",
        "Fröet måste växa, oavsett att det är planterat i sten.",
        "Oavsett hur svårt det blir, sträck ut bröstet, håll huvudet högt och hantera det.",
        "Gör alltid ditt bästa, låt inte pressen få dig att få panik.",
        "Du vet aldrig hur eller när du gör intryck, eller hur viktigt ditt exempel kan vara för någon annan.",
        "Gör det du måste göra för att göra det du vill göra.",
        "Sträva inte efter att tjäna pengar, sträva efter att göra skillnad.",
        "Man måste vara den man är i denna värld, oavsett vad.",
        "Om du har en fiende, lär dig då och förstå din fiende, var inte bara arg på honom eller henne.",
        "Jag strävar efter att vara som de största människorna som någonsin levt.",
        "Där jag utmärker mig är löjligt, sjukt hög arbetsmoral. Medan den andra sover arbetar jag.",
        "Livet levs på kanten.",
        "Att vara realistisk är den vanligaste vägen till medelmåttighet.",
        "Det första steget är att du måste säga att du kan.",
        "Världen kan inte berätta vem du är, du måste ta reda på vem du är och vara det på gott och ont.",
        "Du kommer att behöva inse dina misslyckanden. Du kommer att behöva omfamna dem och lista ut hur du övervinner dem.",
        "Min far sa till mig: Nämn ditt pris i början. Om det någonsin blir dyrare än priset du nämner, gå därifrån.",
        "Skulle du tro på det du tror på om du var den enda som trodde det?",
        "Jag bryr mig inte om vad folk tycker, för folk tänker inte.",
        "Jag var aldrig riktigt bra på något förutom förmågan att lära.",
        "Bästa känslan i världen är att se fördelarna och belöningarna av hårt arbete.",
        "Mina mål är så höga att jag inte har tid att slappna av på något sätt.",
        "Livet är för kort för att oroa sig för vad andra säger om dig.",
        "Bakom varje framgångsrik person gömmer sig en flock avundsjuka.",
        "Du kan göra något av ditt liv, det beror bara på din drivkraft.",
        "Har du fiender? Bra, det betyder att du faktiskt stod upp för något.",
        "All framgång börjar med självdisciplin, den börjar med dig.",
        "Med drivkraft och lite talang kan du flytta berg.",
        "Misslyckande är inte ett alternativ, det är bara ett steg.",
        "Framgång kommer inte över natten, det är när du varje dag blir lite bättre än dagen innan; allt läggs ihop.",
        "När livet sätter dig i tuffa situationer, säg inte 'varför jag', säg bara 'testa mig'.",
        "Framgång i allt handlar alltid om detta: fokus och ansträngning. Och vi kontrollerar båda.",
        "Jag hörde en gång en vis man säga att det inte finns perfekta människor, bara perfekta avsikter.",
        "Väldigt ofta stannar du och säger 'jag är trött på att klättra uppför den här backen, jag kommer aldrig till toppen', och du är bara två steg från toppen.",
        "Utmana dig själv, det är den enda vägen som leder till tillväxt.",
        "Du kan inte ta åt dig äran för talang, du kan bara ta åt dig äran för att använda den.",
        "Det bästa sättet att garantera en förlust är att ge upp.",
        "Jag kunde antingen titta på när det hände eller vara en del av det.",
        "När något är tillräckligt viktigt gör du det, även om oddsen inte är till din fördel.",
        "Om du vaknar på morgonen och tänker att framtiden kommer att bli bättre, är det en ljus dag, annars är det inte det.",
        "Det är okej att ha alla ägg i en korg, så länge du kontrollerar vad som händer med den korgen.",
        "Om du bara gör saker där du vet svaret i förväg försvinner ditt företag.",
        "Du måste vara villig att bli missförstådd om du ska vara innovativ.",
        "Det finns aldrig en dålig tid att vara innovativ.",
        "Att skapa möjligheter innebär att titta där andra inte gör det.",
        "Svettkapital är det mest värdefulla kapitalet som finns.",
        "Vi lever i ett samhälle där hårt arbete nästan alltid belönas.",
        "Universum har ingen skyldighet att vara begripligt för dig.",
        "Det finns ingen bättre utbildning än den som är självdriven.",
        "Ingen som är nyfiken är dum.",
        "Jag känner inte till någon tid i mänsklighetens historia där okunnighet var bättre än kunskap.",
        "Träna dig själv att inte ta något personligt.",
        "En man kan göra vad han vill av sig själv om han verkligen tror det, men han måste vara redo för hårt arbete och många sorger.",
        "Vad var och en av oss måste inse är att vår avsikt alltid lyser igenom.",
        "Vi kan inte ignorera det vi verkligen vill skapa.",
        "Bara du och du ensam kan förändra din situation.",
        "Var tacksam för de svåra tiderna, för de har format dig.",
        "För att ansluta dig till toppen en procent måste du göra det som 99 procent inte vill göra.",
        "Jag skapar min egen väg, den var rak och smal. Jag såg det så här: du var antingen i min väg eller ur den.",
        "Vi har alla självtvivel. Du förnekar det inte, men du ger inte heller efter för det. Du omfamnar det.",
        "Många ledare misslyckas, för de saknar modet att beröra den nerven eller slå den strängen.",
        "Det ögonblick du ger upp är det ögonblick du låter någon annan vinna.",
        "Om du är rädd för att misslyckas kommer du förmodligen att misslyckas.",
        "Jag insåg att skrämsel inte riktigt existerade, om man är i rätt sinnesläge.",
        "Det här är ögonblicket jag accepterar att de mest utmanande tiderna alltid kommer att vara bakom mig och framför mig.",
        "Ingen vet att de kommer att bli mästare, man måste arbeta för att komma dit.",
        "Min tro är starkare än ditt tvivel.",
        "Framgång innebär att vara nöjd med det du gör varje dag. Det är att vara stolt över den bättre person du håller på att bli.",
        "Om du vill vara framgångsrik måste du vara villig att använda varje kontakt du har.",
        "Talang räcker aldrig. Med få undantag är de bästa spelarna de flitigaste.",
        "Ge inte upp, var vän med människor som hjälper dig arbeta hårt.",
        "Fira bara livet du hade, inte livet du kunde ha haft.",
        "Jag växte upp fattig, men jag hade inte fattiga drömmar.",
        "Du är den enda som kan göra skillnad. Vad din dröm än är, gå för den.",
        "Livet stannar inte för att något händer dig.",
        "I livet kommer både vinst och förlust att hända, det som aldrig är acceptabelt är att ge upp.",
        "Vet ni hur många gånger jag har fått nej i mitt liv? Att bli told hur många gånger att jag inte kunde åstadkomma något?",
        "Ofta finner jag att de som är välsignade med mest talang aldrig utvecklar den attityden. Och de som inte är välsignade på det sättet är mest tävlingsinriktade och har störst hjärta.",
        "Jag trodde att jag aldrig skulle få en chans att spela, tills en gång jag fick det, för jag var förberedd och möjligheten infann sig.",
        "Jag älskar bara tävlandet och jag älskar att försöka bli bättre.",
        "Alltför ofta händer något i livet och vi skyller på andra för att vi inte är lyckliga eller nöjda.",
        "Ditt liv kommer att bli vad du gör av det.",
        "Jag tänker inte bli upprörd för att någon sa något dåligt om mig.",
        "Du kan inte sitta på sidlinjen i livet.",
        "Mitt budskap är enkelt: ta kontroll över ditt liv.",
        "När du är en av ledarna i laget finns det inga lediga dagar.",
        "Lita inte på andra. Du kommer att ha bra stöd från många människor. Men ingen kommer att ge dig något.",
        "Saker rättar inte sig själva; du måste gå ut och arbeta hårt för att rätta dem.",
        "Om du inte spelar för att vinna, spela inte alls.",
        "Om du inte tror på dig själv, varför skulle någon annan göra det?",
        "Ibland i livet blir de största utmaningarna det bästa som händer i ditt liv.",
        "Jag älskar bara att arbeta hårt.",
        "De verkliga tävlingsmänniskorna är de som alltid spelar för att vinna.",
        "Jaga inte pengarna, jaga drömmen.",
        "Om du vill flyga måste du ge upp det som tynger dig.",
        "Jag vill inte att du ska drömma, jag vill att du ska göra.",
        "Alla som vill vara någon kommer att arbeta så hårt de kan för att uppfylla den drömmen.",
        "Jag har aldrig försökt dölja det faktum att det är min avsikt att bli bäst.",
        "Om du inte tror att du är bäst kommer du aldrig att uppnå allt du är kapabel till.",
        "Idag finns det möjligheter som ingen vet om de kommer tillbaka i framtiden.",
        "Talang utan hårt arbete är ingenting.",
        "Jag bryr mig inte om att folk hatar mig, för det driver mig framåt.",
        "Talang är inte allt. Du kan ha den från vaggan, men det är nödvändigt att lära sig yrket för att bli bäst.",
        "Jag känner ett oändligt behov av att lära, förbättra, utvecklas, för att känna mig nöjd med mig själv.",
        "Din kärlek gör mig stark. Ditt hat gör mig ostoppbar.",
        "Du kan övervinna vad som helst om du bara älskar något tillräckligt mycket.",
        "Jag är framgångsrik för att jag gjort uppoffringar för framgången.",
        "Min ambition är att alltid bli bättre och bättre.",
        "Jag börjar tidigt och stannar sent. Dag efter dag, år efter år, det tog mig 17 år och 114 dagar att bli en succé över natten.",
        "Personen som höll mig tillbaka från lycka var jag.",
        "Den enkla handlingen att vara uppmärksam kan ta dig långt.",
        "Förväxla inte sanningen med massornas åsikt. Dessa är nästan aldrig ens i närheten av varandra.",
        "Det finns en skillnad mellan att känna till vägen och att gå den.",
        "Jag har ingen tid att ligga vaken hela natten och oroa mig för vad någon som inte älskar mig har att säga om mig.",
        "Du kan inte vara tveksam om vem du är.",
        "Det finns alltid saker att arbeta med, du är aldrig färdig.",
        "Jag vill vara vad jag alltid velat vara: dominant.",
        "Jag försöker bara vara den bästa jag kan och hoppas att det är den bästa någonsin.",
        "Jag vill inte bli lika bra som jag en gång var, jag vill bli bättre.",
        "Mitt sinne är min största tillgång. Jag förväntar mig att vinna varje turnering jag spelar.",
        "De som verkligen kontrollerar sina känslor är de som kommer att vinna.",
        "Oavsett hur bra du blir kan du alltid bli bättre, och det är det spännande.",
        "För att kunna hjälpa andra måste du först lära dig att hjälpa dig själv.",
        "Inget av värde kommer till en utan hårt arbete som resultat.",
        "Jag ska inte låta någon förminska min själ genom att få mig att hata honom.",
        "Du kan inte hålla en man nere utan att stanna nere med honom.",
        "Karaktär, inte omständigheter, skapar mannen.",
        "Det finns två sätt att använda sin styrka: det ena är att trycka ner, det andra är att lyfta upp.",
        "Jag har misslyckats långt fler gånger än jag har lyckats.",
        "Jag gör idag det folk inte vill, så att jag kan uppnå imorgon det folk inte kan.",
        "Även om du förlorar, förlora inte läxan.",
        "Det enklaste att sälja är sanningen.",
        "Vänta inte på den perfekta tiden, du kommer att vänta för evigt. Utnyttja alltid den tid du har och gör den perfekt.",
        "Du kan bara göra ett begränsat antal saker riktigt bra, och du bör strunta i allt annat.",
        "Livet är bräckligt. Vi har ingen garanti för en morgondag, så ge allt du har.",
        "Jag är inte rädd för att göra bort mig.",
        "Respekt motiverar mig, inte framgång.",
        "När du är över kullen är det då du ökar farten.",
        "Excellens är inte en handling, det är en vana.",
        "Du kan inte få ett A om du är rädd för att få ett F.",
        "Du gör dina misstag för att lära dig hur du når det goda.",
        "En hjälte är någon som frivilligt kliver in i det okända.",
        "Det finns miljontals överlevare där ute. Gör det till en miljon och en.",
        "Ge aldrig upp, för du vet aldrig vad tidvattnet för med sig nästa dag.",
        "Om det inte var svårt skulle alla göra det. Det är det svåra som gör det storslaget.",
        "Om du bara spelar säkert med dina val växer du inte.",
        "Jag gillar att göra något jag fruktar.",
        "Processen är den vackraste delen.",
        "Det är lätt att lura ögat, men svårt att lura hjärtat.",
        "Bli aldrig för upprymd, bli aldrig för nedstämd. Ta det dag för dag och fortsätt att lära.",
        "Ansträngning kommer aldrig att ifrågasättas.",
        "Hoppas inte att någon ger dig ett tillfälle: skapa ett för dig själv.",
        "När folk sa att jag aldrig skulle klara det lyssnade jag på den enda person som sa att jag kunde: mig.",
        "Det finns en anledning till att det kallas att jaga sina drömmar och inte att promenera efter dem.",
        "För att ha det du verkligen vill ha måste du först vara den du verkligen är.",
        "Låt inte det förflutna hemsöka dig. För det du gör i nuet kan hemsöka din framtid, var vis. Det du gör nu eller i framtiden kan aldrig dölja ditt förflutna, men det betyder inte att du ska låta det förflutna kontrollera dig.",
        "Det där \"tänk om\" är ett sår som aldrig läker.",
        "Om det var lätt hade det inte varit värt det.",
        "Du förtjänar ingenting, du förtjänar det du jobbar för.",
        "Perfektion är inte intressant, att komma ut på toppen trots prövningar av motgång: det är vad som imponerar på mig.",
        "Delta inte i \"tycka-synd-om-mig\"-olympiaden; vi tävlar inte i den.",
        "När du vill ha något tar du terrängen som följer med, oavsett vilken terräng det är.",
        "Sann vision är när ditt sinne är starkare än det som ligger framför dina ögon.",
        "Vissa händelser kommer att driva dig framåt, vissa kommer att göra tvärtom, verkar det som. De motsatserna är läromöjligheter som kommer att visa sig användbara i framtiden.",
        "Betala kostnaden för att vara chefen eller betala kostnaden som följer av ånger.",
        "Andras åsikt om dig behöver inte bli din verklighet.",
        "Du får inte det du önskar dig, du får det du arbetar för.",
        "Självdisciplin börjar med att bemästra dina tankar. Om du inte kontrollerar vad du tänker kan du inte kontrollera vad du gör. Enkelt uttryckt möjliggör självdisciplin att du tänker först och handlar efteråt.",
        "Vad är nederlag? Inget annat än utbildning; inget annat än det första steget mot något bättre.",
        "Det är inte vad som händer dig, utan hur du reagerar på det som spelar roll.",
        "Kontrollera din ilska. Om du har ilska mot andra kontrollerar de dig.",
        "Din största utmaning är att dyka upp när ditt sinne hittar de bästa ursäkterna.",
        "Du kan antingen uppleva disciplinens smärta eller ångerns smärta. Valet är ditt.",
        "Allt som gör dig svag fysiskt, intellektuellt och andligt; avvisa som gift.",
        "Svettas mer under fred, blöd mindre under krig.",
        "Med modet att börja och disciplinen att uthärda blir seger en fråga om tid.",
        "En bra ledare är en person som tar lite mer än sin del av skulden och lite mindre än sin del av äran.",
        "Var stark, men inte oförskämd. Var snäll, men inte svag. Var modig, men mobba inte. Var ödmjuk, men inte blyg. Var stolt, men inte arrogant.",
        "Tålamod är bittert, men dess frukt är söt.",
        "Tålamod är inte passivitet, tvärtom; det är aktivt. Det är koncentrerad styrka.",
        "Ingenting är omöjligt för den som vill försöka.",
        "Intelligens är inte förmågan att lagra information, utan att veta var man hittar den.",
        "Först är det en avsikt. Sedan ett beteende. Sedan en vana. Sedan en praxis. Sedan en andra natur. Sedan är det helt enkelt den du är.",
        "Vad du än vill göra, gör det nu. Det finns bara ett begränsat antal morgondagar.",
        "Människor som säger att det inte kan göras bör inte avbryta dem som gör det.",
        "Det finns bara en hörna av universum du kan vara säker på att förbättra, och det är du själv.",
        "Dåren tror sig vara vis, men den vise vet att han är en dåre.",
        "Smärta kan förändra dig, men det behöver inte vara en dålig förändring. Ta den smärtan och förvandla den till visdom.",
        "Tid är verkligen det enda kapital som varje människa har, och det enda hon inte har råd att förlora.",
        "Följ din egen väg, oavsett vad folk säger.",
        "Gör något. Om det fungerar, gör mer av det. Om det inte gör det, gör något annat.",
        "Lärande är det enda sinnet aldrig tröttar på, aldrig fruktar och aldrig ångrar.",
        "En vinnare är en drömmare som aldrig ger upp.",
        "Om du inte kämpar för det du vill ha, gråt inte över det du förlorade.",
        "När du väl accepterat dina brister kan ingen använda dem mot dig.",
        "När vi lärt oss tillräckligt om universum kommer vi att erkänna för oss själva att vi aldrig kommer att veta allt.",
        "Att oroa sig är som att betala en skuld du inte är skyldig.",
        "Du kan inte lära någon något, bara få dem att inse att svaren redan finns inom dem.",
        "Tankens kraft kan orsaka antingen sjukdom eller tillfrisknande.",
        "Om du vill se ett mirakel, var ett mirakel.",
        "Det finns tre klasser av människor: de som ser, de som ser när de visas, de som inte ser.",
        "Dina största rädslor skapas av din fantasi.",
        "Det största bedrägeri människor lider av är deras egna åsikter.",
        "När du har uttömt alla möjligheter, kom ihåg: det har du inte.",
        "Älska den hand som ödet delar ut åt dig och spela den som din egen.",
        "Om två personer är överens om allt är en av dem onödig.",
        "Den största tävlingen är den du har med dig själv.",
        "När vi är trötta attackeras vi av idéer vi besegrat för länge sedan.",
        "Jag är inte vad som hände mig. Jag är det jag väljer att bli.",
        "Den viktigaste faktorn för överlevnad är varken intelligens eller styrka, utan anpassningsförmåga.",
        "Tro och rädsla kräver båda att du tror på något du inte kan se. Du väljer.",
        "Genom att klaga berättar du för folk hur svag du är.",
        "För att få det du älskar måste du först ha tålamod med det du hatar.",
        "När allt verkar gå emot dig, kom ihåg att flygplanet lyfter mot vinden, inte med den.",
        "Du kommer att skratta åt dina rädslor när du upptäcker vem du verkligen är.",
        "Frid hittas inte i en lugnare storm, den hittas i en bättre båt.",
        "Du kan ignorera verkligheten, men du kan inte ignorera konsekvenserna av att ignorera verkligheten.",
        "Ingen man är olyckligare än den som aldrig möter motgång. Ty han tillåts inte att bevisa sig själv.",
        "En bra plan våldsamt genomförd nu är bättre än en perfekt plan genomförd nästa vecka.",
        "Att studera och inte tänka är slöseri. Att tänka och inte studera är farligt.",
        "Rädsla är en reaktion. Mod är ett beslut.",
        "Oberoende tillhör de allra få; det är ett privilegium för de starka.",
        "Det tar halva livet innan du upptäcker att livet är ett gör-det-själv-projekt.",
        "Spela din roll med ära.",
        "Oro är ett missbruk av fantasin.",
        "Bron mellan kunskap och färdighet är övning. Bron mellan färdighet och mästerskap är tid.",
        "Ju mer jag lär mig, desto mer inser jag hur mycket jag fortfarande har att lära.",
        "Om du inte förlorar kan du inte njuta av segrarna. Så jag måste acceptera båda sakerna.",
        "Vi lär oss lite av seger, mycket av nederlag.",
        "Den som talar ödmjukt men ökar sina förberedelser kommer att avancera. Den som talar krigiskt och rycker fram hastigt kommer att retirera.",
        "Vårt liv är vad våra tankar gör det till.",
        "Det finns egentligen inget svårt, om du inte bestämmer att det är svårt. Annars är det bara nästa sak du ska lista ut.",
        "Oavsett situation, låt aldrig dina känslor övertrumfa din intelligens.",
        "Bestäm dig för vilken typ av person du vill vara och håll fast vid det, oavsett om du är ensam eller i sällskap.",
        "Om något är fel, åtgärda det om du kan. Men träna dig att inte oroa dig. Oro löser aldrig någonting.",
        "Livet handlar inte om att ha bra kort, utan om att spela en dålig hand väl.",
        "Det är en ojämn väg som leder till storhetens höjder.",
        "Den dag en man blir överlägsen njutning, kommer han också att vara överlägsen smärta.",
        "Lär dig kontinuerligt, det finns alltid en sak till att lära sig.",
        "Vi kan klaga på att rosenbuskar har taggar, eller glädjas åt att taggbuskar har rosor.",
        "Var tålmodig och stark; en dag kommer denna smärta att vara till nytta för dig.",
        "Misslyckande är framgång under arbete.",
        "Den som slutar lära sig är gammal, oavsett om man är tjugo eller åttio.",
        "Om du styrs av sinnet är du en kung; om av kroppen, en slav.",
        "Stolthet är inte motsatsen till skam, utan dess källa. Sann ödmjukhet är det enda motgiftet mot skam.",
        "När du börjar förbättra dig själv är ensamhet priset du betalar.",
        "Du bedöms inte efter höjden du nått, utan efter djupet du klättrat från.",
        "En man är stor inte för att han inte misslyckats; en man är stor för att misslyckande inte stoppat honom.",
        "En man utan en vision är en man utan en framtid. En man utan en framtid kommer alltid att återvända till sitt förflutna.",
        "Hellre misslyckas med heder än lyckas genom bedrägeri.",
        "Alla strider vinns eller förloras först i sinnet.",
        "Människors känslor väcks snabbare än människors intelligens.",
        "Den som köper det han inte behöver stjäl från sig själv.",
        "Den som har tålamod kan få vad han vill.",
        "Krigarens väg är livslång, och mästerskap är ofta bara att stanna på vägen.",
        "Drakar stiger högst mot vinden, inte med den.",
        "Om folk visste hur hårt jag fick arbeta för att nå min skicklighet skulle det inte verka så underbart alls.",
        "Somna aldrig utan en begäran till ditt undermedvetna.",
        "Välkomna händelser på det sätt de inträffar: detta är vägen till frid.",
        "Öva även det som verkar omöjligt.",
        "Den man som jagar två kaniner fångar ingen av dem.",
        "Du kommer att klara det, men det kommer alltid att kännas som om du inte gör det.",
        "Planera för det som är svårt medan det är lätt, gör det som är stort medan det är litet.",
        "Uthållighet räcker inte. Man måste bestämma om man ska uthärda som en lidande eller som en krigare.",
        "Den nivå av skärpa och disciplin som krävs för att nå de höjder du drömmer om är egentligen enkel, den är bara inte lätt.",
        "Den största fienden finns inte på utsidan. Förstörelse kommer ofta inifrån.",
        "Alla visste att det var omöjligt, tills en dåre som inte visste det kom och gjorde det.",
        "Du kan inte göra en svag man stark genom att göra en stark man svag.",
        "Du har makt över ditt sinne, inte yttre händelser. Inse detta och du finner styrka.",
        "En diamant är bara en kolbit som höll fast vid sitt jobb.",
        "Den största risken är att inte ta någon risk.",
        "Om du definierar problemet korrekt har du nästan lösningen.",
        "Det förflutna är i ditt huvud, framtiden är i dina händer.",
        "Livet är ganska enkelt. Du gör lite saker. Det mesta misslyckas. Något fungerar. Du gör mer av det som fungerar.",
        "Må din pliktmedvetenhet överskugga en atmosfär av rädsla och tendensen att skjuta upp ambitioner.",
        "Allt du någonsin velat ha finns på andra sidan rädslan.",
        "Disciplin är att välja mellan det du vill nu och det du vill mest.",
        "Konformitet är den fantasilösas sista tillflykt.",
        "En diamant är en kolbit som höll fast vid jobbet.",
        "Det finns ingen större skada för människan än bortkastad tid.",
        "Förstör inte det du har genom att begära det du inte har; kom ihåg att det du nu har en gång var bland de saker du bara hoppades på.",
        "En man som behärskar tålamod behärskar allt annat.",
        "Sätt aldrig passion framför princip, även om du vinner förlorar du.",
        "Vissa vill att det ska hända, vissa önskar att det ska hända, andra gör att det händer.",
        "Vi når inte nivån av våra förväntningar, vi faller till nivån av vår träning.",
        "Det är lättare att hitta män som frivilligt dör än att hitta dem som är villiga att uthärda smärta med tålamod.",
        "Du kan inte förvänta dig att nå pallen om du inte deltar i loppet.",
        "Den som faller och reser sig är starkare än den som aldrig försökte.",
        "Dåliga nyheter: Du kommer inte att passa in med alla. Goda nyheter: De stora gör aldrig det.",
        "Jag har aldrig varit talangfull, jag är bara bra på att aldrig ge upp.",
        "Lycka är inte frånvaron av problem, det är förmågan att hantera dem.",
        "Om du gör det som är lätt blir ditt liv svårt.",
        "Du kan inte gå tillbaka och ändra början, men du kan börja där du är och ändra slutet.",
        "Mer fångas upp än undervisas.",
        "De som aldrig gör misstag arbetar för dem av oss som gör det.",
        "En ny idé ska inte bedömas efter sina omedelbara resultat.",
        "Du är aldrig redo för det du måste göra. Du gör det bara. Det gör dig redo.",
        "Ta risker: om du vinner blir du lycklig; om du förlorar blir du vis.",
        "Ett folk som värdesätter sina privilegier högre än sina principer förlorar snart båda.",
        "Den snabbaste vägen till mening och framgång: välj en sak och satsa allt.",
        "Var inte rädd för att börja om. Den här gången börjar du inte från noll. Du börjar från erfarenhet.",
        "Det finns inget ädelt i att vara överlägsen sin medmänniska; sann adelskap är att vara överlägsen sitt tidigare jag.",
        "Du förtjänar allas respekt om du börjar med att förtjäna din egen respekt.",
        "Skapa en vision av den du vill vara och lev sedan in i den bilden som om den redan vore sann.",
        "Priset för excellens är disciplin. Kostnaden för medelmåttighet är besvikelse.",
        "Svårigheter stärker sinnet, liksom arbete stärker kroppen.",
        "Du kan inte hoppas på framsteg inom områden där du inte har vidtagit någon åtgärd.",
        "Ingen mängd ångest gör någon skillnad för något som ska hända.",
        "Visa mig en man med genomsnittlig förmåga men extraordinär önskan och jag visar dig en vinnare varje gång.",
        "Det snabbaste sättet att lyckas är att börja nu och lista ut det längs vägen.",
        "Människor bestämmer inte sina framtider, de bestämmer sina vanor och deras vanor bestämmer deras framtider.",
        "Lär dina barn tidigt det du lärde dig sent.",
        "Om du lägger 100 timmar om året på vilken disciplin som helst, vilket bara är 18 minuter om dagen, kommer du att vara bättre än 95 procent av världen i den disciplinen.",
        "Uppgiften är inte att se vad ingen annan har sett, utan att tänka det som ingen har tänkt om det som alla ser.",
        "Om du irriteras av varje gnidning, hur ska då din spegel poleras?",
        "Rädsla är bara så djup som sinnet tillåter.",
        "Svårighet är det som väcker geniet.",
        "Det som ska ge ljus måste uthärda att brinna.",
        "Jag har lärt mig att framgång inte bör mätas efter den position man nått i livet utan efter de hinder man övervunnit medan man försökte lyckas.",
        "Bekvämlighet är det värsta beroendet.",
        "Du blir det du ger din uppmärksamhet till.",
        "Omständigheter skapar inte mannen, de avslöjar bara honom för sig själv.",
        "Slösa inte mer tid på att argumentera om vad en god man borde vara. Var en.",
        "Låt den som vill flytta världen först flytta sig själv.",
        "Mellan stimulus och respons finns ett utrymme. I det utrymmet finns vår kraft att välja vår respons. I vår respons ligger vår tillväxt och vår frihet.",
        "Det finns inget utanför dig själv som någonsin kan göra dig bättre, starkare, rikare, snabbare eller smartare. Allt finns inom dig. Allt existerar. Sök inget utanför dig själv.",
        "Var tolerant mot andra och sträng mot dig själv.",
        "Två saker definierar dig: Ditt tålamod när du inte har något och din attityd när du har allt.",
        "Du vaknar inte bara upp och blir fjärilen.",
        "Seghet är förmågan att hålla fast när att släppa taget verkar mest lockande.",
        "Det finns risker och kostnader med handling. Men de är långt mindre än de långsiktiga riskerna med bekväm passivitet.",
        "För att uppnå stora saker behövs två saker: en plan och inte riktigt tillräckligt med tid.",
        "Tvivel kan bara avlägsnas genom handling.",
        "Om dina handlingar inspirerar andra att drömma mer, lära mer, göra mer och bli mer, är du en ledare.",
        "Det handlar inte om att ha ett fläckfritt meritblad. Det handlar om att lära sig av fläckarna på det.",
        "Var modig nog att vara dålig på något nytt.",
        "Gå till sängs klokare än när du vaknade.",
        "Långsam framgång bygger karaktär, snabb framgång bygger ego.",
        "Bara för att någon snubblar och tappar sin väg betyder det inte att de är förlorade för alltid.",
        "Men vi kan inte bara sitta och stirra på våra sår för evigt.",
        "Och nu när du inte behöver vara perfekt kan du vara bra.",
        "Framgång kommer från hänsynslös tillämpning av grunderna.",
        "Det krävs mycket hårt arbete för att göra något enkelt.",
        "Alla tänker på att förändra världen, men ingen tänker på att förändra sig själv.",
        "De trångsynta behöver sin konst matad med sked.",
        "Gör något istället för att döda tid. För tiden dödar dig.",
        "Låt varje beslut vara i linje med din vision.",
        "Om du vill göra något större än genomsnittet kan du inte ge efter för rädslan att vara en utanförstående.",
        "Det som spelar mest roll är hur väl du går genom elden.",
        "Du är ett beslut ifrån ett helt annorlunda liv.",
        "Om du lever för morgondagen kommer du alltid att ligga en dag efter.",
        "Gör det bästa av dig själv, för det är allt som finns av dig.",
        "Ögon är onödiga när sinnet är blint.",
        "I det långa loppet träffar människor bara det de siktar på. Även om de skulle misslyckas direkt bör de hellre sikta på något högt.",
        "Den som har en anledning att leva kan uthärda nästan vad som helst.",
        "Människor kan delas in i två grupper: den som går framåt och åstadkommer något, och den som kommer efter och kritiserar.",
        "En dålig attityd är som ett platt däck. Du kan inte ta dig någonstans förrän du byter det.",
        "Ingen fågel flyger för högt om den flyger med sina egna vingar.",
        "Lös problemet eller lämna problemet. Lev inte med problemet.",
        "Agera enligt dina principer, inte ditt humör.",
        "De som inte binder sig till något distraheras av allt.",
        "När vi strävar efter att bli bättre än vi är, blir allt omkring oss bättre också.",
        "Det finns ingen passion i att nöja sig med ett liv som är mindre än det du är kapabel att leva.",
        "En kreativ man drivs av viljan att uppnå, inte av viljan att slå andra.",
        "Livet är en lång förberedelse för något som aldrig händer.",
        "Jag lyssnar inte längre på vad folk säger, jag tittar bara på vad de gör. Beteende ljuger aldrig.",
        "Intelligenta individer lär sig av allt och alla; mediokra människor, av sina erfarenheter. De dumma har redan alla svaren.",
        "Den första regeln är att behålla ett orubbligt sinne. Den andra är att se saker som de verkligen är.",
        "Det är alltid en kamp att lyfta tyngre vikt.",
        "En man som fruktar lidande lider redan av det han fruktar.",
        "Om en man inte vet till vilken hamn han seglar är ingen vind gynnsam.",
        "Jag gör alltid det jag inte kan göra, för att lära mig hur man gör det.",
        "Du bygger på misslyckande. Du använder det som ett trappsteg. Stäng dörren till det förflutna. Du försöker inte glömma misstagen, men du dväljs inte vid dem. Du låter dem inte ta någon av din energi, eller någon av din tid, eller något av ditt utrymme.",
        "Innehållet i din karaktär är ditt val. Dag efter dag, det du väljer, det du tänker och det du gör är vem du blir.",
        "De fega startade aldrig och de svaga dog längs vägen.",
        "När du vaknar på morgonen, tänk på vilket dyrbart privilegium det är att vara vid liv, att andas, att tänka, att njuta, att älska.",
        "Hemligheten bakom framgång är fokus på målet.",
        "Det enda som är farligare än okunnighet är arrogans.",
        "Vi är vad vi gör upprepade gånger. Excellens är då inte en handling, utan en vana.",
        "Medan vi väntar på livet passerar livet.",
        "Framgång är inget annat än några enkla discipliner, utövade varje dag.",
        "Ju mer han vet desto mer medveten blir han om sin okunnighet.",
        "Hindret för handling driver handlingen framåt. Det som står i vägen blir vägen.",
        "Vår största svaghet ligger i att ge upp. Det säkraste sättet att lyckas är att alltid försöka en gång till.",
        "En ädelsten kan inte poleras utan friktion, inte heller en människa fullkomnas utan prövningar.",
        "Ditt värde består i vad du är och inte i vad du har.",
        "Förövaren är olyckligare än den förfördelade.",
        "Ett av de sannaste testen på integritet är dess raka vägran att kompromissas.",
        "Gud ger inget till dem som håller armarna i kors.",
        "Att veta hur man tänker ger dig långt större makt än de som bara vet vad de ska tänka.",
        "Om du planerar att vara något mindre än du är kapabel till kommer du förmodligen att vara olycklig hela livet.",
        "Det finns inget bättre än motgångar. Varje nederlag, varje hjärtesorg, varje förlust innehåller sitt eget frö, sin egen lektion om hur du förbättrar din prestation nästa gång.",
        "Lär dig att älska hatet. Omfamna det. Njut av det. Du har förtjänat det. Alla har rätt till sin egen åsikt och alla borde ha en om dig. Hatare är ett bra problem att ha. Ingen hatar de bra. De hatar de fantastiska.",
        "Acceptera din oförmåga att kontrollera allt. Acceptera ansvar för allt under din kontroll. Acceptera att interna och externa hinder existerar. Acceptera att du är utrustad att navigera dem alla.",
        "Erfarenhet är den hårdaste sortens lärare. Den ger dig testet först och läxan efteråt.",
        "Vi mognar med skadorna, inte med åren.",
        "Om du är deprimerad lever du i det förflutna. Om du är orolig lever du i framtiden. Om du har frid lever du i nuet.",
        "Om du tror att vi inte kan förändra världen betyder det bara att du inte är en av dem som kommer att göra det.",
        "Kanske handlar det inte om ett lyckligt slut. Kanske handlar det om berättelsen.",
        "Vissa människor sprider glädje vart de än går, och andra sprider glädje när de går.",
        "Observera ständigt att alla ting sker genom förändring, och vänja dig vid att tänka att universums natur älskar inget så mycket som att förändra.",
        "Att vara alltför god kan vara ointressant.",
        "Alltför ofta njuter vi av åsiktens bekvämlighet utan tankens obehag.",
        "Studier utan tanke är fåfängt; tanke utan studier är farligt.",
        "En man med övertygelse kommer att övervinna hundra som bara har åsikter.",
        "Dårar förökar sig när visa män tiger.",
        "Var redo att revidera varje system, kassera varje metod, överge varje teori om arbetets framgång kräver det.",
        "Att hjälpa andra att utvecklas och lyckas i livet är en belöning i sig och har bara värde när inget förväntas i gengäld.",
        "Nu är inte tid att tänka på det du inte har. Tänk på vad du kan göra med det som finns.",
        "Jag skulle säga att jag är ett pågående arbete, men det skulle antyda att jag en dag inte kommer att vara det.",
        "Ge inte upp. Vanligtvis är det den sista nyckeln på ringen som öppnar dörren.",
        "Livet är en komedi för dem som tänker, en tragedi för dem som känner.",
        "Takt är förmågan att säga åt någon att dra åt helvete på ett sådant sätt att de ser fram emot resan.",
        "Lämna det orätta som en annan gjort där det orätta uppstod.",
        "Störa inte dig själv genom att föreställa dig hela ditt liv på en gång. Tänk inte alltid på vilka lidanden, och hur många, som möjligen kan drabba dig.",
        "Varje gång jag tror att jag vet allt visar det sig att \"allt\" har lite mer volym än jag antog.",
        "Skillnaden mellan dumhet och genialitet är att genialitet har sina gränser.",
        "Det är bättre att vara en krigare i en trädgård än en trädgårdsmästare i ett krig.",
        "Stor framgång kommer alltid med risk för enormt misslyckande.",
        "Framgång kommer av nyfikenhet, koncentration, uthållighet och självkritik.",
        "Det är tecknet på ett utbildat sinne att kunna underhålla en tanke utan att acceptera den.",
        "Tiotusen personers åsikt saknar värde om ingen av dem vet något om ämnet.",
        "Ju mer vi värdesätter saker utanför vår kontroll, desto mindre kontroll har vi.",
        "Gör resor. Försök dem. Det finns inget annat.",
        "Ursprung bör aldrig vara ett hinder för framgång. En blygsam start i livet kan vara mer till hjälp än hinder.",
        "Låt inte en annans brister få dig att komma till korta.",
        "Vår avund varar alltid längre än lyckan hos dem vi avundas.",
        "Inget kommer av inget.",
        "Svaga människor hämnas. Starka människor förlåter. Intelligenta människor ignorerar.",
        "Jag kontrollerar inte vinden; jag studerar den bara.",
        "Heder kanske inte vinner makt, men den vinner respekt. Och respekt ger makt.",
        "Det slutliga vapnet är hjärnan, allt annat är kompletterande.",
        "Om du inte övervinner din benägenhet att ge upp lätt leder ditt liv till ingenting.",
        "Träning är som att sopa golvet. Bara för att vi gjort det en gång betyder det inte att golvet är rent för evigt.",
        "Kom ihåg att det är vi som plågar oss, vi som skapar svårigheter för oss själva, det vill säga våra åsikter gör det. Vad betyder det till exempel att bli förolämpad? Stå vid en sten och förolämpa den, vad har du åstadkommit? Om någon reagerar på förolämpning som en sten, vad har den som förolämpar vunnit?",
        "I frånvaro av syfte blir livet en ändlös resa till ingenstans.",
        "Bara de döda har sett slutet på kriget.",
        "Att förebygga är bättre än att bota.",
        "Inget som lärs ut med tvång stannar i själen.",
        "Allt som existerar i ditt liv gör det på grund av två saker: något du gjorde eller något du inte gjorde.",
        "En man utan etik är ett vilt djur släppt lös i denna värld.",
        "Att tänka är svårt, det är därför de flesta dömer.",
        "Du hittar inte viljestyrka, du skapar den.",
        "Ordet lycka skulle förlora sin mening om det inte balanserades av sorg.",
        "Be inte om ett lätt liv. Be om styrkan att uthärda ett svårt liv.",
        "Du är inte allt du kunde vara, och du vet det.",
        "Kom ihåg att leva medan du är upptagen med att överleva.",
        "Planer är ingenting, planering är allt.",
        "En man som vågar slösa en timme av sin tid har inte upptäckt livets värde.",
        "Du måste bestämma vem du är och tvinga världen att hantera dig, inte sin idé om dig.",
        "Konsten att leva liknar mer brottning än dans, i det att den står redo mot det tillfälliga och oförutsedda och inte är benägen att falla.",
        "Ju äldre jag blir, desto mindre uppmärksamhet ägnar jag åt vad människor säger. Jag tittar bara på vad de gör.",
        "Jag drar åt svångremmen innan jag ber om hjälp.",
        "Ingen är skapad som du, du formade dig själv.",
        "Ingen man har rätt att vara amatör i fråga om fysisk träning. Det är en skam för en man att åldras utan att se skönheten och styrkan som hans kropp är kapabel till.",
        "Ju närmare en man kommer ett lugnt sinne, desto närmare är han styrka.",
        "Här är en regel att komma ihåg i framtiden, när något frestar dig att känna bitterhet: inte \"Detta är otur\", utan \"Att bära detta värdigt är lycka.\"",
        "När du är bra på något berättar du det för alla. När du är fantastisk på något berättar de det för dig.",
        "Först ignorerar de dig. Sedan förlöjligar de dig. Sedan attackerar de dig och vill bränna dig. Och sedan reser de monument åt dig.",
        "Frihet innebär ansvar. Det är därför de flesta fruktar den.",
        "Om du talar sanning behöver du inte komma ihåg något.",
        "Din tid kommer om du fortsätter.",
        "Det är inte döden en man bör frukta, utan han bör frukta att aldrig börja leva.",
        "Dagens rutiner är morgondagens resultat. Om du kan förälska dig i dagens rutiner kommer du att älska morgondagens resultat.",
        "Hela mänsklighetens problem härstammar från människans oförmåga att sitta stilla i ett rum ensam.",
        "Låt aldrig framtiden störa dig. Du kommer att möta den, om du måste, med samma förnuftets vapen som idag beväpnar dig mot nuet.",
        "En man mognar genom smärta, misslyckande, avvisning, förlust, respektlöshet och hjärtesorg, inte genom ålder.",
        "Vi smider de kedjor vi bär i livet.",
        "För att göra något på hög nivå måste det vara en besatthet.",
        "Om du vill förbättras, var beredd på att betraktas som dum och löjlig med avseende på yttre ting.",
        "Våld är den inkompetentes sista tillflykt.",
        "Rädsla är precis som eld, den kan vara till hjälp om du vet hur du använder den. Om inte, bränner du dig.",
        "För att lyckas stort måste du vara beredd att misslyckas stort. Om du inte klarar båda har du ett problem.",
        "Vi pratar alltid om att någon ogillar oss utan anledning, men folk gillar dig utan anledning också. Så lägg inte för stor vikt vid någondera sidan.",
        "Fega dör många gånger före sin död; de tappra smakar döden bara en gång.",
        "Ingenting är svårare, och därför mer värdefullt, än att kunna bestämma sig.",
        "Gå en enda väg, bli varken högmodig av seger eller bruten av nederlag, utan att glömma försiktighet när allt är lugnt eller bli skrämd när fara hotar.",
        "Själen färgas av sina tankars färg.",
        "Jag ber inte om en lättare börda. Utan om bredare axlar.",
        "Förhandla inte med dig själv. Instruera dig själv.",
        "Du kan inte önska dig både stark karaktär och ett lätt liv.",
        "Mod är inte att ha styrkan att gå vidare, det är att gå vidare när du inte har styrka.",
        "Livet händer inte dig, det händer med dig inblandat.",
        "Det är ödesdigert att gå in i ett krig utan viljan att vinna det.",
        "Du vet aldrig hur stark du är förrän att vara stark är ditt enda alternativ.",
        "Man kan inte göra alla nöjda, ibland måste man agera och låta alla andra reagera.",
        "Det finns inget \"om\", det är bara en fråga om när, när du är beslutsam om uppdraget.",
        "Hur länge tänker du vänta innan du kräver det bästa för dig själv?",
        "Världen utlovar bekvämlighet, men du skapades inte för bekvämlighet. Du skapades för storhet.",
        "Integritet är inte den snabbaste vägen, men det är en säker väg.",
        "Var ditt eget största fan, din egen största tro, och lägg det på din rygg och bär vikten.",
        "Säg först för dig själv vad du vill vara; och gör sedan det du måste göra.",
        "Jag fruktar den dag då teknologin överträffar mänsklig interaktion. Världen kommer att ha en generation av idioter.",
        "Det spelar ingen roll vad du bär, utan hur du bär det.",
        "Avvisa din känsla av oförrätt och oförrätten själv försvinner.",
        "Gör inga små planer. De har ingen magi att röra upp blodet och kommer förmodligen aldrig att förverkligas. Gör stora planer; sikta högt i hopp och arbete, och kom ihåg att ett ädelt, logiskt diagram en gång nedtecknat aldrig kommer att dö, utan länge efter oss kommer det att vara en levande kraft.",
        "Svårigheter förbereder ofta vanliga människor för ett extraordinärt öde.",
        "När du vill förändra saker kan du inte göra alla nöjda. Om du gör alla nöjda gör du inte tillräckliga framsteg.",
        "Förhandla inte med dig själv, instruera dig själv.",
        "Framgång är inte slutgiltig, misslyckande är inte ödesdigert: det är modet att fortsätta som räknas.",
        "Om det inte är rätt, gör det inte; om det inte är sant, säg det inte.",
        "Så kallade njutningar, när de överskrider en viss gräns, är bara bestraffningar.",
        "Om du inte offrar för det du vill ha blir det du vill ha offret.",
        "Din största fiende är ditt okontrollerade sinne.",
        "Lär dig att kämpa så att du aldrig behöver kämpa.",
        "När en person inte kan finna en djup känsla av mening distraherar de sig med njutning.",
        "Ingenting är permanent i denna onda värld, inte ens våra problem.",
        "Låt dem ha fel om dig. Det finns inget att bevisa för dem.",
        "Om du vill att nuet ska vara annorlunda än det förflutna, studera det förflutna.",
        "Om du vill leva ett lyckligt liv, bind det till ett mål, inte till människor eller föremål.",
        "Det finns inga hemligheter, det finns bara information du har upptäckt och information du inte har upptäckt.",
        "Du behöver motivation för att agera. Du behöver information för att veta vad du ska agera på. Du behöver nyfikenhet för att skaffa underrättelser som korrekt styr dessa motiverade handlingar. Så var nyfiken.",
        "En vinnare är bara en förlorare som försökte en gång till.",
        "Vi behandlar kroppen strängt så att den inte ska vara olydig mot sinnet.",
        "De villiga leds av ödet, de motvilliga dras.",
        "Den man som fruktar döden kommer aldrig att göra något värdigt en man som lever.",
        "En befälhavare sätter aldrig sådan tillit till fred att han misslyckas med att förbereda sig för krig.",
        "Var inte rädd. Du kommer att klara det, men det kommer alltid att kännas som om du inte gör det.",
        "Konsekvens kanske låter som tråkigt, men vad trodde du annars att storhet var? Tur?",
        "Håll alltid ansiktet mot solskenet så faller skuggorna bakom dig.",
        "Det tyngsta straffet för att vägra styra är att styras av någon sämre än dig själv.",
        "Gräv inåt. Inuti finns godhetens källa; och den är alltid redo att bubbla upp, om du bara gräver.",
        "Du är vad du gör, inte vad du säger att du ska göra.",
        "Att gå fel på sitt eget sätt är bättre än att gå rätt på någon annans.",
        "En stor man är hård mot sig själv, en svag man är hård mot andra.",
        "Att älska sig själv är början på en livslång romans.",
        "Bry dig om vad andra tycker, och du kommer alltid att vara deras fånge.",
        "Människan oroar sig inte så mycket av verkliga problem som av sina inbillade farhågor om verkliga problem.",
        "Den lyckliga mannen är nöjd med sin nuvarande situation, oavsett vad den är.",
        "Den första och största segern är att besegra sig själv.",
        "För att kontrollera mig själv måste jag först acceptera mig själv genom att gå med och inte mot min natur.",
        "Låt människor se, låt dem veta en riktig man som lever som han var menad att leva.",
        "Den som inte kan lyda sig själv kommer att befallas.",
        "När du fruktar något, lär dig så mycket om det som du kan. Kunskap besegrar rädsla.",
        "Jag trodde alltid att det var jag mot världen, och en dag insåg jag att det bara är jag mot mig.",
        "En man som saknar syfte distraherar sig med nöje.",
        "Det är svårt att acceptera att alla inte förstår det, men det är därför det inte är till för alla andra. Det är en grej för dig.",
        "Ju större svårigheten, desto mer ära i att övervinna den.",
        "Vi gläds åt fjärilens skönhet, men erkänner sällan de förändringar den genomgått för att uppnå den skönheten.",
        "Låt mig falla om jag måste falla. Den jag håller på att bli kommer att fånga mig.",
        "Bakom en man som förlåter allt finns en man som känner vikten av sina egna synder.",
        "Försöket att fly från smärta skapar mer smärta.",
        "Sann utveckling respekterar inte bekvämlighet.",
        "Så vitt vi kan urskilja är det enda syftet med mänsklig existens att tända ett ljus av mening i mörkret av blott tillvaro.",
        "Dagen du planterar fröet är inte dagen du äter frukten.",
        "Sanningen förändras inte för att den tros eller inte tros av en majoritet av människorna.",
        "En riddare i glänsande rustning har inget bevisat värde. Ge mig en stridsprövad riddare med sliten rustning från möten med mänsklighetens värsta.",
        "Måttet på intelligens är förmågan att förändras.",
        "Det finns ingen skörd utan hunger.",
        "Det är sinnet självt som leder sinnet vilse. Var inte sinnesfrånvarande.",
        "Du kan inte drömma dig till en karaktär; du måste hamra och smida dig en.",
        "Mycket kommer att gå fel innan allt blir rätt.",
        "Vi lever bara nu. Allt annat har antingen passerat eller är okänt.",
        "Du kommer inte att straffas för din ilska, du kommer att straffas av din ilska.",
        "Du lär dig inte simma genom att läsa om vatten.",
        "De svåraste valen kräver de starkaste viljorna.",
        "Framför allt, ljug inte för dig själv.",
        "Din kropp klarar nästan allt; det är sinnet du måste övertyga.",
        "Livet är av förstapersonsgenren. Behandla det som sådant.",
        "Bra ledare hittar inte ursäkter. Istället hittar de ett sätt att få det gjort.",
        "Bara för att det tog dig längre tid än andra betyder det inte att du misslyckades.",
        "Ju mer du känner dig själv desto mindre behöver du andras godkännande.",
        "Att känna sig själv är början på all visdom.",
        "Det är inte storleken på en man utan storleken på hans hjärta som spelar roll.",
        "Det är osannolikt att du byter nivå utan tårar.",
        "Du plöjer med den plog du har.",
    ]
}
