// QuotesLang_de.swift
// Spike AI — Bundled quote translations
import Foundation
enum QuotesLang_de {
    static let quotes: [String] = [
        "Was auch immer du konsequent in deinem Geist festhältst, genau das wirst du im Leben erfahren.",
        "Wir zielen über das Ziel hinaus, um das Ziel zu treffen.",
        "Das Schlimmste, was ich sein kann, ist wie alle anderen – das hasse ich.",
        "Nur wer es wagt, zu weit zu gehen, kann herausfinden, wie weit man gehen kann.",
        "Spring, und das Netz wird erscheinen.",
        "Ein Schiff im Hafen ist sicher, aber dafür werden Schiffe nicht gebaut.",
        "Mach dir keine Sorgen über Misserfolge – sorge dich um die Chancen, die du verpasst, wenn du es nicht einmal versuchst.",
        "Wer es wagt, kläglich zu scheitern, kann Großes erreichen.",
        "Der Weg anzufangen ist, aufzuhören zu reden und anzufangen zu handeln.",
        "Wir mögen vielen Niederlagen begegnen, aber wir dürfen uns nicht besiegen lassen.",
        "Das wahre Maß eines Menschen ist, wie er jemanden behandelt, der ihm absolut nichts nützen kann.",
        "Sei vorsichtig, wenn du nicht weißt, wohin du gehst, denn du könntest dort nicht ankommen.",
        "Du musst Großes von dir selbst erwarten, bevor du es tun kannst.",
        "Lass niemals deine vergangenen Entscheidungen dein zukünftiges Ergebnis bestimmen.",
        "Abkürzungen verursachen lange Verzögerungen.",
        "Niemand kann dir deine Ziele geben. Das ist deine Reise.",
        "Die Welt ist das, was du von ihr denkst – also denke anders darüber, und deine Welt wird sich verändern.",
        "Die Zukunft gehört denen, die sich heute darauf vorbereiten.",
        "Gib nicht das auf, was du am meisten willst, für das, was du jetzt willst.",
        "Erzähl mir nicht, wie talentiert du bist – erzähl mir, wie hart du arbeitest.",
        "Wie du denkst, wenn du verlierst, bestimmt, wie lange es dauert, bis du gewinnst.",
        "Sobald jemand entscheidet, dass Erfolg erreicht ist, hört der Fortschritt auf.",
        "Kein Problem kann dem Ansturm beharrlichen Denkens standhalten.",
        "Glück ist, wenn eine Gelegenheit kommt und du darauf vorbereitet bist.",
        "Das Geheimnis, voranzukommen, ist anzufangen.",
        "Die beste Zeit, einen Baum zu pflanzen, war vor 20 Jahren. Die zweitbeste Zeit ist jetzt.",
        "Es ist schwer, jemanden zu schlagen, der niemals aufgibt.",
        "Schreib es. Film es. Veröffentliche es. Häkle es, brate es. Was auch immer – erschaffe!",
        "Was auch immer du bist, sei ein guter.",
        "Glück ist nichts Fertiges – es entsteht aus deinen eigenen Handlungen.",
        "Kluge Menschen lernen von allem und jedem.",
        "Unmöglich ist nur eine Meinung.",
        "Deine Leidenschaft wartet darauf, dass dein Mut aufholt.",
        "Menschen, die sich fragen, ob das Glas halb leer oder halb voll ist, verfehlen den Punkt. Das Glas ist nachfüllbar.",
        "Eines Tages oder Tag eins – du entscheidest.",
        "Dinge mögen zu denen kommen, die warten, aber nur die Dinge, die von denen übrig gelassen wurden, die sich anstrengen.",
        "Alles kommt zu dem, der sich anstrengt, während er wartet.",
        "Arbeite so, als ob jemand 24 Stunden am Tag daran arbeitet, es dir wegzunehmen.",
        "Niemand hat je einen Unterschied gemacht, indem er wie alle anderen war.",
        "Du wirst schlechte Zeiten haben, aber sie werden dich immer für die guten Dinge aufwecken, denen du keine Beachtung geschenkt hast.",
        "Sei eine erstklassige Version deiner selbst, nicht eine zweitklassige Version von jemand anderem.",
        "Lerne aus den Fehlern anderer. Du kannst nicht lange genug leben, um sie alle selbst zu machen.",
        "Wenn du müde bist, dann tu es müde.",
        "Ein Mann ist nicht am Ende, wenn er besiegt wird – er ist am Ende, wenn er aufgibt.",
        "Die Welt wird durch dein Beispiel verändert, nicht durch deine Meinung.",
        "Das Leben ist wie Fahrradfahren. Um das Gleichgewicht zu halten, musst du in Bewegung bleiben.",
        "Denke über das Leben nach: Keine Menge an Schuld kann die Vergangenheit ändern, keine Menge an Angst kann die Zukunft ändern.",
        "Ein negativer Geist wird dir niemals ein positives Leben geben.",
        "Alles ist schwer, bevor es leicht wird.",
        "Geh das Risiko ein oder verliere die Chance.",
        "Hör niemals auf zu lernen, denn das Leben hört niemals auf zu lehren.",
        "Der Mann, der nicht liest, hat keinen Vorteil gegenüber dem Mann, der nicht lesen kann.",
        "Ein Mensch, der nie einen Fehler gemacht hat, hat nie etwas Neues ausprobiert.",
        "Der häufigste Weg, wie Menschen ihre Macht aufgeben, ist zu denken, dass sie keine haben.",
        "Sei dankbar für das, was du hast – du wirst am Ende mehr haben. Konzentriere dich auf das, was du nicht hast, und du wirst nie genug haben.",
        "Das Schwierigste ist die Entscheidung zu handeln – der Rest ist bloße Beharrlichkeit.",
        "Viele Misserfolge im Leben sind Menschen, die nicht erkannt haben, wie nah sie dran waren, als sie aufgaben.",
        "Es geht nicht darum, ob du zu Boden gehst – es geht darum, ob du wieder aufstehst.",
        "Der Pessimist sieht in jeder Chance eine Schwierigkeit. Der Optimist sieht in jeder Schwierigkeit eine Chance.",
        "Unser größter Ruhm liegt nicht darin, niemals zu fallen, sondern jedes Mal wieder aufzustehen.",
        "Lass dich nicht von den Ängsten in deinem Kopf herumschubsen – lass dich von den Träumen in deinem Herzen leiten.",
        "Wenn du weißt, was du willst, und es dringend genug willst, wirst du einen Weg finden, es zu bekommen.",
        "Beginne damit, das Notwendige zu tun, dann das Mögliche, und plötzlich tust du das Unmögliche.",
        "Ohne Leidenschaft hast du keine Energie, ohne Energie hast du nichts.",
        "Du musst nicht großartig sein, um anzufangen, aber du musst anfangen, um großartig zu werden.",
        "Stärke kommt nicht von körperlicher Leistungsfähigkeit – sie kommt von einem unbeugsamen Willen.",
        "Niemand auf dieser Welt ist nutzlos, der die Last eines anderen erleichtert.",
        "Indem wir das Unmögliche fordern, erlangen wir das Mögliche.",
        "Es ist besser, einen Tag lang ein Löwe zu sein als ein ganzes Leben lang ein Schaf.",
        "Das Leben ist zu wichtig, um ernst genommen zu werden.",
        "Der Anfang ist die Hälfte jeder Handlung.",
        "Unendliche Geduld bringt sofortige Ergebnisse.",
        "Fast alle Menschen sterben an ihren Heilmitteln und nicht an ihren Krankheiten.",
        "Sie können, weil sie glauben, dass sie können.",
        "Fantasie ist wichtiger als Wissen.",
        "Beharrliche Menschen beginnen ihren Erfolg dort, wo andere im Scheitern enden.",
        "Es gibt keine klaren Wege. Nur Fallgruben, Stolperdrähte und Dunkelheit.",
        "Ein Fehler beweist, dass jemand lange genug aufgehört hat zu reden, um etwas zu tun.",
        "Was auch immer es wert ist, getan zu werden, ist es wert, gut getan zu werden.",
        "Am mächtigsten ist, wer sich selbst in seiner Gewalt hat.",
        "Ein Gelehrter, der die Liebe zur Bequemlichkeit hegt, ist nicht würdig, ein Gelehrter genannt zu werden.",
        "Wohlstand hängt mehr davon ab, zu wollen, was du hast, als zu haben, was du willst.",
        "Jeder Tag bringt seine eigenen Geschenke mit sich – löse die Schleifen.",
        "Erfolg ist niemals dauerhaft und Misserfolg ist niemals endgültig.",
        "Nichts dauert ewig – nicht einmal deine Probleme.",
        "Harte Arbeit garantiert keinen Erfolg, aber sie verbessert seine Chancen.",
        "Frieden kann nicht durch Gewalt erhalten werden. Er kann nur durch Verständigung erreicht werden.",
        "Wer nichts wagt, hat kein Glück.",
        "Sage nicht: Wenn ich Muße habe, werde ich lernen – du wirst vielleicht keine Muße haben.",
        "Wer den Glauben verliert, verliert alles.",
        "Der eigene Gedanke ist die eigene Welt. Was ein Mensch denkt, das wird er.",
        "Das Abenteuer liegt nicht außerhalb des Menschen, es liegt in ihm.",
        "Im Spiel des Lebens geht es nicht so sehr darum, gute Karten zu halten, als eine schlechte Hand gut zu spielen.",
        "Sauer, süß, bitter, scharf – alles muss probiert werden.",
        "Lass niemals das Gefühl vergangenen Scheiterns deinen nächsten Schritt besiegen.",
        "Wenn du nicht ehrgeizig bist, machst du keine Fortschritte.",
        "Die Zukunft gehört denen, die es wagen.",
        "Tatsachen hören nicht auf zu existieren, weil sie ignoriert werden.",
        "Wir dürfen niemals annehmen, was nicht bewiesen werden kann.",
        "Eine laute Stimme kann nicht mit einer klaren Stimme konkurrieren, selbst wenn es ein Flüstern ist.",
        "Handle so, als ob du erwartest, in die Endzone zu kommen.",
        "Glück ist die natürliche Blüte der Pflicht.",
        "\"Nein\" bedeutet einfach, auf einer höheren Ebene von vorne zu beginnen.",
        "Begeisterung bewegt die Welt.",
        "Ein Champion ist jemand, der aufsteht, wenn er nicht kann.",
        "Hindernisse sind der Preis der Größe.",
        "Die Frage ist nicht, wer mich lässt – die Frage ist, wer mich aufhalten wird.",
        "Ich war nicht dort, um mitzumachen – ich war dort, um zu gewinnen.",
        "Hör auf zu jammern, fang an zu arbeiten.",
        "Aus Schwierigkeiten wachsen Wunder.",
        "Ich habe keine Angst – ich wurde dafür geboren.",
        "Beuge niemals deinen Kopf. Halte ihn hoch. Schau der Welt geradewegs ins Auge.",
        "Tu, was du tun musst, bis du tun kannst, was du tun willst.",
        "Wenn du gestern hingefallen bist, steh heute auf.",
        "Mach jeden Tag zu deinem Meisterwerk.",
        "Blut, Schweiß und Respekt. Die ersten beiden gibst du, den letzten verdienst du dir.",
        "Sei so gut, dass sie dich nicht ignorieren können.",
        "Zeig der Welt, wie sehr du für den Siegerkreis kämpfst.",
        "Wenn du nicht deinen eigenen Lebensplan entwirfst, wirst du wahrscheinlich in den Plan eines anderen fallen. Was haben sie für dich geplant? Nicht viel.",
        "Die einzige Person, zu der du bestimmt bist zu werden, ist die Person, die du beschließt zu sein.",
        "Warte nicht, bis das Eisen heiß ist, um zuzuschlagen – mach es heiß durch Zuschlagen.",
        "Ich kann nicht glauben, dass Gott uns auf diese Erde gesetzt hat, um gewöhnlich zu sein.",
        "Ich will, dass die Welt besser ist, weil ich hier war.",
        "Die Gewohnheit der Beharrlichkeit ist die Gewohnheit des Sieges.",
        "Hab keine Angst, das Gute aufzugeben, um nach dem Großartigen zu streben.",
        "Tu deine Pflicht und ein bisschen mehr, und die Zukunft wird sich von selbst regeln.",
        "Das Leben hat eine Art, den Willen eines Menschen zu testen – entweder passiert gar nichts oder alles auf einmal.",
        "Ein weiser Mann ist immer allein zu finden. Ein schwacher Mann ist immer in einer Menge zu finden.",
        "Zu wagen heißt, vorübergehend den Halt zu verlieren. Nicht zu wagen heißt, sich selbst zu verlieren.",
        "Angst besiegt mehr Menschen als irgendeine andere Sache auf der Welt.",
        "Die mächtigsten Worte im Universum sind die, die du benutzt, um mit dir selbst zu sprechen.",
        "Das Einzige, was einem schlafenden Mann kommt, sind Träume.",
        "Wenn du dich nicht selbst besiegst, wirst du von dir selbst besiegt werden.",
        "Ein Held ist jemand, der weiß, wie man eine Minute länger durchhält.",
        "Geh so weit, wie du sehen kannst – wenn du dort ankommst, wirst du weiter sehen können.",
        "Du entdeckst deinen Platz in der Welt nicht, du erschaffst ihn.",
        "Gewinner konzentrieren sich auf das Gewinnen. Verlierer konzentrieren sich auf Gewinner.",
        "Misserfolg wird mich niemals einholen, wenn meine Entschlossenheit, erfolgreich zu sein, stark genug ist.",
        "Was leicht kommt, hält nicht lange. Was lange hält, kommt nicht leicht.",
        "Um Kritik zu vermeiden: Sage nichts, tue nichts, sei nichts.",
        "Der Mann, der mehr tut, als er bezahlt wird, wird bald für mehr bezahlt, als er tut.",
        "Genie beginnt große Werke, Arbeit allein vollendet sie.",
        "Selbst wenn du auf dem richtigen Weg bist, wirst du überfahren, wenn du dort sitzen bleibst.",
        "Wenn Dinge nicht scheitern, bist du nicht innovativ genug.",
        "Du holst das Beste aus anderen heraus, wenn du das Beste von dir selbst gibst.",
        "Führung ist eine Handlung, keine Position.",
        "Unsere Arbeit ist die Darstellung unserer Fähigkeiten.",
        "Alle meine Probleme verneigen sich vor meiner Sturheit.",
        "Trage dein Scheitern als Ehrenzeichen.",
        "Wir werden nicht durch unsere Fähigkeiten begrenzt, sondern durch unsere Vorstellungskraft.",
        "Wenn du müde wirst, lerne zu ruhen, nicht aufzugeben.",
        "Hinfallen ist ein Unfall, liegen bleiben ist eine Entscheidung.",
        "Wage es nicht, dieses Leben aufzugeben. Nicht heute Nacht. Nicht morgen. Niemals.",
        "Lass dich niemals von Personen oder Ereignissen niederdrücken.",
        "Manche Menschen träumen vom Erfolg, während andere aufwachen und hart dafür arbeiten.",
        "Selbstvertrauen kommt aus Erfahrung. Erfahrung kommt aus Versuchen, Scheitern und erneutem Versuchen – diesmal besser.",
        "Die Zeit, die zur Meisterschaft führt, hängt von der Intensität unserer Konzentration ab.",
        "Erfolg kommt nur zu denen, die es wagen zu versuchen.",
        "Ein wichtiger Schlüssel zum Erfolg ist Selbstvertrauen. Ein wichtiger Schlüssel zum Selbstvertrauen ist Vorbereitung.",
        "Zweifel töten mehr Träume als Misserfolg es je wird.",
        "Der Sieg ist immer möglich für den, der sich weigert, aufzuhören zu kämpfen.",
        "Du wirst dein Leben nie verändern, bis du etwas änderst, was du täglich tust.",
        "Um erfolgreich zu sein, muss dein Fokus so intensiv sein, dass andere denken, du bist verrückt.",
        "Hindernisse sind die erschreckenden Dinge, die du siehst, wenn du deine Augen von deinem Ziel abwendest.",
        "Eine Gelegenheit zu finden ist eine Frage des Glaubens, dass sie da ist.",
        "Ziele zu setzen ist der erste Schritt, das Unsichtbare sichtbar zu machen.",
        "Wenn du nichts riskierst, riskierst du alles.",
        "Wenn du deine Situation nicht ändern kannst, ändere deine Einstellung.",
        "Egal wie schwer die Vergangenheit war, du kannst immer von vorne beginnen.",
        "Wenn du es nicht wagst, hast du am Ende des Tages nichts gewonnen.",
        "Sehr oft braucht man mehr eine Veränderung seiner selbst als eine Veränderung der Umgebung.",
        "Angst ist die größte Behinderung von allen und wird dich lähmen.",
        "Was gefährlich ist, ist sich nicht weiterzuentwickeln.",
        "So oder so werde ich einen Weg finden oder einen schaffen.",
        "Der einzige Weg, alle zum Schweigen zu bringen, ist zu gewinnen.",
        "Lass niemals zu, dass gut genug gut genug ist.",
        "Auf lange Sicht treffen wir nur das, worauf wir zielen.",
        "Kontinuierliche Verbesserung ist besser als verspätete Perfektion.",
        "Wenn du es in deinem Geist siehst, wirst du es in deiner Hand halten.",
        "Heute werde ich tun, was andere nicht tun, damit ich morgen tun kann, was andere nicht können.",
        "Exzellenz ist eine Kunst, die durch Training und Gewöhnung gewonnen wird.",
        "Das nächste Jahr wird vergehen, ob du etwas für dein Leben tust oder nicht.",
        "Hör nicht auf, wenn du müde bist – hör auf, wenn du fertig bist.",
        "Du bist nur ein Training von guter Laune entfernt.",
        "Tu das Richtige, nicht das Einfache oder das Beliebte.",
        "Nichts Großes kam jemals so einfach.",
        "Ohne Kampf kann es keinen Fortschritt geben.",
        "Erfolgreiche Menschen stellen bessere Fragen und bekommen dadurch bessere Antworten.",
        "Ich habe keine besonderen Talente – ich bin nur leidenschaftlich neugierig.",
        "Die beste Lektion, die ich im Leben gelernt habe, kam aus dem schlimmsten Gefühl, das ich im Leben hatte.",
        "Herausforderungen machen das Leben interessant. Sie zu überwinden macht das Leben bedeutsam.",
        "Lerne, mit dem endlosen Ansatz von Versuchen, Scheitern und Lernen glücklich zu sein.",
        "Wenn du die Tür zu allen Fehlern verschließt, wird die Wahrheit ausgesperrt.",
        "Vergiss den Fehler, erinnere dich an die Lektion.",
        "Wenn du nur tun kannst, was du kannst, wirst du nie mehr sein als du jetzt bist.",
        "Wer ist weise? Der, der von jedem lernt.",
        "Nur ich kann mein Leben ändern, niemand kann es für mich tun.",
        "Beharrlichkeit bedeutet, 19 Mal zu scheitern und beim 20. Mal erfolgreich zu sein.",
        "Ich führe meinen Erfolg darauf zurück: Ich habe nie eine Entschuldigung gegeben oder angenommen.",
        "Ich bin kein Produkt meiner Umstände. Ich bin ein Produkt meiner Entscheidungen.",
        "Unsere Taten bestimmen uns ebenso, wie wir unsere Taten bestimmen.",
        "Nur die extrem Unwissenden oder extrem Intelligenten können Veränderung widerstehen.",
        "Der Mann, der Vertrauen in sich selbst hat, gewinnt das Vertrauen anderer.",
        "Was du suchst, sucht auch dich.",
        "Mach dir keine Sorgen über Misserfolg. Du musst nur einmal richtig liegen.",
        "Sicherheit ist größtenteils Aberglaube. Das Leben ist entweder ein gewagtes Abenteuer oder nichts.",
        "Wir werden zu dem, woran wir die meiste Zeit denken, und das ist das seltsamste Geheimnis.",
        "Der Weg anzufangen ist, aufzuhören zu reden und anzufangen zu handeln.",
        "Mach jeden Tag zu deinem Meisterwerk.",
        "Egal wie viele Fehler du machst oder wie langsam du vorankommst, du bist immer noch weit vor jedem, der es nicht versucht.",
        "Es ist unsere Einstellung zu Beginn einer schwierigen Aufgabe, die mehr als alles andere ihren erfolgreichen Ausgang beeinflusst.",
        "Die einzige wahre Sicherheit, die ein Mensch in dieser Welt hat, ist ein Vorrat an Wissen, Erfahrung und Fähigkeit.",
        "Was du heute tust, kann alle Morgen deines Lebens verändern.",
        "Dein Leben wird nicht durch Zufall besser – es wird durch Veränderung besser.",
        "Ein Traum wird nicht durch Magie Wirklichkeit – es braucht Schweiß, Entschlossenheit und harte Arbeit.",
        "Wissen ist zu wissen, dass eine Tomate eine Frucht ist. Weisheit ist, sie nicht in einen Obstsalat zu tun.",
        "Egal was die Situation ist, erinnere dich: Ich habe eine Wahl.",
        "Beherrsche deinen Geist, oder er wird dich beherrschen.",
        "Einige haben Erfolg, weil es ihnen bestimmt ist, aber die meisten haben Erfolg, weil sie entschlossen sind.",
        "Große Gelegenheiten werden nicht mit den Augen gesehen, sie werden mit dem Verstand gesehen.",
        "Wer nicht mutig genug ist, Risiken einzugehen, wird im Leben nichts erreichen.",
        "Wissen ist nicht genug, wir müssen anwenden. Wollen ist nicht genug, wir müssen tun.",
        "Ehrgeiz ist der Weg zum Erfolg, Beharrlichkeit ist das Fahrzeug, in dem du ankommst.",
        "Der Schlüssel zum Leben ist, Herausforderungen anzunehmen. Sobald jemand damit aufhört, ist er tot.",
        "Engagement ist das, was ein Versprechen in Realität verwandelt.",
        "Selbstvertrauen ist die Erinnerung an Erfolg.",
        "Ohne Selbstvertrauen sind wir wie Säuglinge in einer Wiege.",
        "Wage zu träumen, aber noch wichtiger – wage es, deine Träume in die Tat umzusetzen.",
        "Ehrlichkeit ist das erste Kapitel im Buch der Weisheit.",
        "Exzellenz ist ein kontinuierlicher Prozess und kein Zufall.",
        "Hoffnung ist die Fähigkeit zu sehen, dass es trotz aller Dunkelheit Licht gibt.",
        "Wir müssen endliche Enttäuschung akzeptieren, aber niemals die unendliche Hoffnung verlieren.",
        "Das wahre Zeichen von Intelligenz ist nicht Wissen, sondern Vorstellungskraft.",
        "Werde süchtig nach ständiger und nie endender Selbstverbesserung.",
        "Genie ist ein Prozent Inspiration und neunundneunzig Prozent Transpiration.",
        "Du kannst nicht auf Inspiration warten – du musst mit einem Knüppel hinter ihr her.",
        "Hab Geduld. Alle Dinge sind schwierig, bevor sie einfach werden.",
        "Die Person, die sagt, es könne nicht getan werden, sollte die Person, die es tut, nicht unterbrechen.",
        "Beharrlichkeit ist die harte Arbeit, die du verrichtest, nachdem du müde bist von der harten Arbeit, die du bereits geleistet hast.",
        "Ein weiser Mann kann mehr von einer dummen Frage lernen als ein Dummer von einer weisen Antwort.",
        "Durch beständige Selbstdisziplin und Selbstkontrolle kannst du Größe des Charakters entwickeln.",
        "Emotionale Selbstkontrolle ist das Ergebnis harter Arbeit, keine angeborene Fähigkeit.",
        "Zu lernen, wie man lernt, ist die wichtigste Fähigkeit des Lebens.",
        "Lass nicht zu, dass das, was du nicht kannst, dich davon abhält, das zu tun, was du kannst.",
        "Auf dem Weg zum Erfolg passierst du immer den Misserfolg.",
        "Niemand ist perfekt – deshalb haben Bleistifte Radiergummis.",
        "Lass dich niemals von den Chancen davon abhalten, das zu tun, wovon du in deinem Herzen weißt, dass es deine Bestimmung ist.",
        "Wenn du genau hinschaust, haben die meisten Übernachterfolge sehr lange gedauert.",
        "Alles ist möglich. Alles kann sein.",
        "Nichts ist besonders schwer, wenn du es in kleine Aufgaben zerlegst.",
        "Das Geheimnis des Erfolgs ist, gewöhnliche Dinge ungewöhnlich gut zu tun.",
        "Handle so, als ob das, was du tust, einen Unterschied macht – denn das tut es.",
        "Was du durch das Erreichen deiner Ziele gewinnst, ist nicht so wichtig wie das, was du durch das Erreichen deiner Ziele wirst.",
        "Das Leben ist wie Fahrradfahren – um das Gleichgewicht zu halten, musst du in Bewegung bleiben.",
        "Begrenze deine \"Immer\" und \"Niemals\".",
        "Du bist nie zu alt, um ein neues Ziel zu setzen oder einen neuen Traum zu träumen.",
        "Du findest das glückliche Leben nicht, du erschaffst es.",
        "Die schlechte Nachricht ist: Die Zeit fliegt. Die gute Nachricht ist: Du bist der Pilot.",
        "Halte dein Gesicht immer dem Sonnenschein zugewandt, und die Schatten fallen hinter dich.",
        "Der Unterschied zwischen dem Unmöglichen und dem Möglichen liegt in der Entschlossenheit eines Menschen.",
        "Goldmedaillen bestehen nicht wirklich aus Gold. Sie bestehen aus Schweiß, Entschlossenheit und einer schwer zu findenden Legierung namens Mut.",
        "Unterschätze nicht die Entschlossenheit eines ruhigen Mannes.",
        "Sag mir nicht, woran du glaubst. Ich beobachte, wie du dich verhältst, und bilde mir meine eigene Meinung.",
        "Ich hasse es einfach zu verlieren, und das gibt dir eine zusätzliche Motivation, härter zu arbeiten.",
        "Die Entschlossenheit zu gewinnen ist der bessere Teil des Gewinnens.",
        "Du kannst das ganze Talent der Welt haben, aber ohne Entschlossenheit wirst du nicht weit kommen.",
        "Sieg ist das Kind von Vorbereitung und Entschlossenheit.",
        "Der junge Mann kennt die Regeln, aber der alte Mann kennt die Ausnahmen.",
        "Der Pessimist beklagt den Wind, der Optimist erwartet, dass er sich ändert, der Realist richtet die Segel aus.",
        "Wissen hat keinen Wert, wenn du es nicht in die Praxis umsetzt.",
        "Ich würde lieber die Dinge bereuen, die ich getan habe, als die Dinge, die ich nicht getan habe.",
        "Es erfordert Weisheit, um Weisheit zu verstehen. Die Musik ist nichts, wenn das Publikum taub ist.",
        "Die größere Gefahr für die meisten von uns liegt nicht darin, zu hoch zu zielen und zu kurz zu kommen, sondern zu niedrig zu zielen und unser Ziel zu erreichen.",
        "Bei jedem Spaziergang in der Natur empfängt man weit mehr, als man sucht.",
        "Ich werde nicht dahin folgen, wohin der Weg führt, sondern ich werde dorthin gehen, wo es keinen Weg gibt, und eine Spur hinterlassen.",
        "Die mächtige Eiche von heute ist nur die gestrige Nuss, die standgehalten hat.",
        "Völlig ehrlich zu sich selbst zu sein, ist eine gute Übung.",
        "Wir können nicht werden, was wir sein müssen, indem wir bleiben, was wir sind.",
        "Richte deinen Kurs nach den Sternen, nicht nach den Lichtern jedes vorbeifahrenden Schiffes.",
        "Wenn du nicht weißt, wohin du gehst, bringt dich jeder Weg dorthin.",
        "Du wirst immer zwei Möglichkeiten haben: dein Engagement gegen deine Angst.",
        "Gesegnet sind jene, die geben, ohne sich zu erinnern, und nehmen, ohne zu vergessen.",
        "Was passiert, ist nicht so wichtig wie die Art und Weise, wie du darauf reagierst.",
        "Beginne mit dem, was richtig ist, statt mit dem, was akzeptabel ist.",
        "Der überlegene Mensch gibt sich selbst die Schuld. Der unterlegene Mensch gibt anderen die Schuld.",
        "Die kleinste Tat ist besser als die größten Absichten.",
        "Das größte Hindernis für Entdeckungen ist nicht Unwissenheit – es ist die Illusion von Wissen.",
        "Hüte dich vor falschem Wissen – es ist gefährlicher als Unwissenheit.",
        "Der beste Weg, die Zukunft vorherzusagen, ist, sie zu erfinden.",
        "Ohne Risiko zu gewinnen heißt, ohne Ruhm zu triumphieren.",
        "Unser Charakter ist das, was wir tun, wenn wir glauben, dass niemand zusieht.",
        "Alles, was uns an anderen irritiert, kann uns zu einem Verständnis unserer selbst führen.",
        "Die Kunst, weise zu sein, ist die Kunst zu wissen, was man übersehen sollte.",
        "Sag es mir und ich vergesse. Lehre mich und ich erinnere mich. Bezieh mich ein und ich lerne.",
        "Du hast das Gehirn in deinem Kopf. Du hast die Füße in deinen Schuhen. Du kannst dich in jede Richtung lenken, die du wählst.",
        "In drei Worten kann ich alles zusammenfassen, was ich über das Leben gelernt habe: Es geht weiter.",
        "Das Leben besteht darin, Dinge auszuprobieren, um zu sehen, ob sie funktionieren.",
        "Erfolg kommt gewöhnlich zu denen, die zu beschäftigt sind, um ihn zu suchen.",
        "Ich habe nicht versagt – ich habe nur 10.000 Wege gefunden, die nicht funktionieren.",
        "Ich habe meinen Weg zum Erfolg durch Scheitern gefunden.",
        "Wenn du dich nicht selbst programmierst, wird das Leben dich programmieren.",
        "Ich habe keine Zeit, mich selbst zu bemitleiden. Ich habe keine Zeit zu klagen. Ich werde weitermachen.",
        "Wenn du nicht bereit bist, das Übliche zu riskieren, musst du dich mit dem Gewöhnlichen zufriedengeben.",
        "Erfolg wurde definiert als die Fähigkeit, von Misserfolg zu Misserfolg zu gehen, ohne die Begeisterung zu verlieren.",
        "Alle unsere Träume können wahr werden, wenn wir den Mut haben, ihnen zu folgen.",
        "Gelegenheiten passieren nicht einfach – du erschaffst sie.",
        "Ich habe nie vom Erfolg geträumt, ich habe dafür gearbeitet.",
        "Lass nicht zu, dass das, was du nicht tun kannst, das stört, was du tun kannst.",
        "Heute ist der einzige Tag, gestern ist vorbei.",
        "Dinge laufen am besten für die, die das Beste aus dem machen, wie die Dinge laufen.",
        "Wenn du durch die Hölle gehst, geh weiter.",
        "Du siehst nur die öffentlichen Triumphe – niemals die privaten Opfer, die dorthin geführt haben.",
        "Wenn du deine Zeit nicht wertschätzt, werden es andere auch nicht tun.",
        "Niemand kann dir das Gefühl geben, minderwertig zu sein, ohne deine Zustimmung.",
        "Ein erfolgreicher Mann ist einer, der mit den Steinen, die andere auf ihn geworfen haben, ein festes Fundament bauen kann.",
        "Was uns als bittere Prüfungen erscheint, sind oft verkleidete Segnungen.",
        "Nichts auf der Welt ist häufiger als erfolglose Menschen mit Talent.",
        "Versuche nicht, ein Mensch des Erfolgs zu werden, sondern ein Mensch von Wert.",
        "Wenn du es nicht einfach erklären kannst, verstehst du es nicht gut genug.",
        "Du scheiterst nie, bis du aufhörst es zu versuchen.",
        "Wissen ist, sich bewusst zu sein, was man tun kann. Weisheit ist zu wissen, wann man es nicht tun sollte.",
        "Im Leben geht es nicht darum, sich selbst zu finden. Im Leben geht es darum, sich selbst zu erschaffen.",
        "Das Problem ist nicht das Problem – das Problem ist deine Einstellung zum Problem.",
        "Kein Meisterwerk wurde je von einem faulen Künstler geschaffen.",
        "Der Weg zum Erfolg und der Weg zum Misserfolg sind fast genau gleich.",
        "Es geht nicht darum, was du anschaust – es geht darum, was du siehst.",
        "Mut ist Widerstand gegen die Angst – Beherrschung der Angst, nicht Abwesenheit von Angst.",
        "Ich finde, dass ich umso mehr Glück zu haben scheine, je härter ich arbeite.",
        "Das Leuchten eines einzigen warmen Gedankens ist mir mehr wert als Geld.",
        "Aller Fortschritt findet außerhalb der Komfortzone statt.",
        "Denken sollte dein Kapital werden, egal welche Höhen und Tiefen dir im Leben begegnen.",
        "Erfolg ist die Summe kleiner Anstrengungen, die Tag für Tag wiederholt werden.",
        "Der erfolgreiche Krieger ist der durchschnittliche Mann mit laserartigem Fokus.",
        "Erfolg besteht nicht darin, nie Fehler zu machen, sondern darin, denselben Fehler nie ein zweites Mal zu machen.",
        "Lass nicht zu, dass die Angst vor dem Verlieren größer ist als die Aufregung des Gewinnens.",
        "Der erste Schritt ist, wenn du dich weigerst, ein Gefangener deiner Umgebung zu sein.",
        "Es gibt keinen Stau auf der Extra-Meile.",
        "Wann immer du dich auf der Seite der Mehrheit befindest, ist es Zeit, innezuhalten und nachzudenken.",
        "Erfolg ist, sich selbst zu mögen, zu mögen, was man tut, und zu mögen, wie man es tut.",
        "Ein Ziel ist nicht immer dazu da, erreicht zu werden – es dient oft einfach als etwas, worauf man zielen kann.",
        "Es ist besser, in Originalität zu scheitern, als in Nachahmung erfolgreich zu sein.",
        "Motivation ist das, was dich in Gang bringt – Gewohnheit ist das, was dich am Laufen hält.",
        "Du musst jeden Morgen mit Entschlossenheit aufstehen, wenn du mit Zufriedenheit ins Bett gehen willst.",
        "Du musst Großes von dir selbst erwarten, bevor du es tun kannst.",
        "Echte Schwierigkeiten können überwunden werden – nur die eingebildeten sind unbesiegbar.",
        "Menschen haben selten Erfolg, wenn sie keinen Spaß an dem haben, was sie tun.",
        "In unseren dunkelsten Momenten müssen wir uns konzentrieren, um das Licht zu sehen.",
        "Misserfolg ist das Gewürz, das dem Erfolg seinen Geschmack verleiht.",
        "Gewöhnliche Geister werden durch Unglück gezähmt und unterworfen, aber große Geister erheben sich darüber.",
        "Vielleicht musst du eine Schlacht mehr als einmal kämpfen, um sie zu gewinnen.",
        "Was würdest du tun, wenn du keine Angst hättest?",
        "Gute Dinge kommen zu denen, die warten, aber bessere Dinge kommen zu denen, die hinausgehen und sie sich holen.",
        "Gib immer dein Bestes, auch wenn die Chancen gegen dich stehen.",
        "Warte nicht darauf, dass sich deine Gefühle ändern, bevor du handelst – handle und deine Gefühle werden sich ändern.",
        "Handeln bringt nicht immer Glück, aber es gibt kein Glück ohne Handeln.",
        "Perfektion ist langweilig – besser zu werden ist der ganze Spaß.",
        "Es ist schwer, jemanden zu schlagen, der niemals aufgibt.",
        "Der Unterschied zwischen einem Stolperstein und einem Trittstein ist, wie hoch du deinen Fuß hebst.",
        "Gib niemals auf, denn genau dort und dann wird sich das Blatt wenden.",
        "Manchmal ist es ein wunderbarer Glücksfall, nicht zu bekommen, was du willst.",
        "Ich kann die Windrichtung nicht ändern, aber ich kann meine Segel so einstellen, dass ich immer mein Ziel erreiche.",
        "Vorwärts. Halte nicht an, verweile nicht auf deiner Reise, sondern strebe nach dem Ziel, das vor dir liegt.",
        "Wenn du etwas wirklich willst, warte nicht darauf – lehre dich selbst, ungeduldig zu sein.",
        "Manchmal gewinnst du, manchmal lernst du.",
        "Zwei Arten von Menschen auf dieser Welt: die, die Dinge erledigen wollen, und die, die keine Fehler machen wollen.",
        "Sorge dafür, dass dein schlimmster Feind nicht zwischen deinen eigenen zwei Ohren lebt.",
        "Denke immer daran, dass du absolut einzigartig bist – genau wie alle anderen.",
        "Wenn du alles unter Kontrolle hast, bewegst du dich nicht schnell genug.",
        "Ein Weg, den Schwung aufrechtzuerhalten, ist, ständig größere Ziele zu haben.",
        "Du musst nicht die ganze Treppe sehen – mach einfach den ersten Schritt.",
        "Was uns als bittere Prüfungen erscheint, sind oft verkleidete Segnungen.",
        "Zwei Optionen beim Engagement: Du bist entweder dabei oder nicht – es gibt kein Leben dazwischen.",
        "Wenn du etwas willst, verschwört sich das ganze Universum, dir zu helfen, es zu erreichen.",
        "Glück ist nichts Fertiges – es entsteht durch deine eigenen Handlungen.",
        "Was auch immer du bist, sei ein guter.",
        "Schmerz ist unvermeidlich, Leiden ist optional.",
        "Talent trifft ein Ziel, das kein anderer treffen kann; Genie trifft ein Ziel, das kein anderer sehen kann.",
        "Der Geist ist sein eigener Ort und kann in sich selbst einen Himmel aus der Hölle oder eine Hölle aus dem Himmel machen.",
        "Ich hasste das Training, aber ich sagte mir: Gib nicht auf – leide jetzt und lebe den Rest deines Lebens als Champion.",
        "Es sind nicht die Berge vor dir, die dich erschöpfen – es ist der Stein in deinem Schuh.",
        "Was wir denken, werden wir.",
        "Jemand sitzt heute im Schatten, weil jemand vor langer Zeit einen Baum gepflanzt hat.",
        "Ein einziger Sonnenstrahl reicht aus, um viele Schatten zu vertreiben.",
        "Dem Geist, der still ist, ergibt sich das ganze Universum.",
        "Mit Selbstdisziplin ist fast alles möglich.",
        "Der beste Ausweg führt immer hindurch.",
        "Deine große Chance könnte genau dort sein, wo du jetzt bist.",
        "Nichts ist mehr wert als dieser Tag.",
        "Die einzige Reise ist die nach innen.",
        "Die Umstände bestimmen nicht, wohin du gehen kannst – sie bestimmen nur, wo du anfängst.",
        "Der Glaube schafft die tatsächliche Realität.",
        "Was die Wüste schön macht, ist, dass sie irgendwo einen Brunnen verbirgt.",
        "Wenn die Tore der Wahrnehmung gereinigt würden, erschiene dem Menschen alles, wie es ist: unendlich.",
        "Ändere deine Gedanken und du änderst deine Welt.",
        "Der Vogel wird durch sein eigenes Leben und seine Motivation angetrieben.",
        "Gib Licht, und die Menschen werden den Weg finden.",
        "Die beste Vorbereitung auf morgen ist, heute dein Bestes zu geben.",
        "Ideen formen den Lauf der Geschichte.",
        "Nicht an einem einzigen Faden sind alle Juwelen des Lebens aufgereiht.",
        "Was wir innerlich erreichen, wird die äußere Realität verändern.",
        "Deine eigene Entschlossenheit zum Erfolg ist wichtiger als alles andere.",
        "Du weißt, dass du auf dem Weg zum Erfolg bist, wenn du deine Arbeit auch ohne Bezahlung tun würdest.",
        "Du wirst zu dem, woran du glaubst.",
        "Wenn du Exzellenz erreichen willst, kannst du heute damit beginnen. Ab dieser Sekunde hör auf, weniger als exzellente Arbeit zu leisten.",
        "Wenn du nicht bereit bist, das Übliche zu riskieren, musst du dich mit dem Gewöhnlichen zufriedengeben.",
        "Vor allem anderen ist Vorbereitung der Schlüssel zum Erfolg.",
        "Ich habe über die Jahre gelernt: Wenn man sich einmal entschieden hat, verringert das die Angst.",
        "Das Leben besteht aus immer so vielen Abschieden, die zusammengeschweißt sind.",
        "Gewinnen ist nicht alles, aber gewinnen wollen schon.",
        "Du magst enttäuscht sein, wenn du scheiterst, aber du bist verloren, wenn du es nicht versuchst.",
        "Fehler sind eine Tatsache des Lebens – es ist die Reaktion auf den Fehler, die zählt.",
        "Wenn dir der Weg nicht gefällt, den du gehst, beginne einen neuen zu pflastern.",
        "Taten sprechen lauter als Worte, und das gilt besonders für deine Kinder.",
        "Ein Diamant ist ein Stück Kohle, das gut unter Druck war.",
        "Schwierige Wege führen oft zu wunderschönen Zielen.",
        "Manchmal wirst du den Wert eines Moments nie kennen, bis er zu einer Erinnerung wird.",
        "Nichts kann das Licht trüben, das von innen strahlt.",
        "Um im Leben erfolgreich zu sein, brauchst du drei Dinge: einen Wunschknochen, ein Rückgrat und einen Sinn für Humor.",
        "Die, die nicht an Magie glauben, werden sie niemals finden.",
        "Ich habe beschlossen, dass ich niemanden bezahlen kann, um die Zeit zurückzudrehen, also kann ich genauso gut darüber hinwegkommen.",
        "Alles hat seinen Preis – die Frage ist nur, was du bereit bist dafür zu zahlen.",
        "Ich bin am meisten gewachsen – nicht durch Siege, sondern durch Rückschläge.",
        "Ich habe Glück, dass mein Wunsch zu gewinnen immer stärker ist als jede Angst in mir.",
        "Du musst an dich selbst glauben, wenn es sonst niemand tut.",
        "Hab keine Angst vor dem Scheitern – das ist der Weg zum Erfolg.",
        "Ich mag Kritik – sie macht dich stark.",
        "Ich weiß, dass ich immer mein Bestes geben will.",
        "Jeder, den ich getroffen habe, der erfolgreich ist, ist ein Workaholic.",
        "Ich habe nie mit jemandem konkurriert außer mit mir selbst.",
        "Der Glaube an sich selbst und zu wissen, wer man ist – das ist das Fundament für alles Große.",
        "Ich habe Angst, es nicht zu versuchen.",
        "Der Weg, deine Vergangenheit zu erlösen, ist nicht vor ihr wegzulaufen, sondern sie zu verstehen und als Fundament zum Wachsen zu nutzen.",
        "Sicherheit bringt dir in dieser Welt gar nichts.",
        "Ein großartiger Auftritt ist ein großartiger Auftritt, aber bei einer Niete funktioniert er einfach nicht. Es kommt auf das Talent an.",
        "Entweder du entwickelst dich weiter, oder du verschwindest.",
        "Der Same muss wachsen, ungeachtet der Tatsache, dass er in Stein gepflanzt wurde.",
        "Egal wie schwer es wird – Brust raus, Kopf hoch und damit umgehen.",
        "Gib immer dein Bestes, lass dich nicht vom Druck in Panik versetzen.",
        "Du weißt nie, wie oder wann du Einfluss haben wirst, oder wie wichtig dein Beispiel für jemand anderen sein kann.",
        "Tu, was du tun musst, um das zu tun, was du tun willst.",
        "Strebe nicht danach, deinen Lebensunterhalt zu verdienen – strebe danach, einen Unterschied zu machen.",
        "Man muss in dieser Welt sein, wer man ist – egal was.",
        "Wenn du einen Feind hast, dann lerne ihn kennen – sei nicht einfach nur wütend auf ihn.",
        "Ich strebe danach, wie die größten Menschen zu sein, die je gelebt haben.",
        "Wo ich herausrage, ist eine lächerliche, krankhafte Arbeitsmoral. Weißt du, während der andere schläft? Arbeite ich.",
        "Das Leben wird am Rand gelebt.",
        "Realistisch zu sein ist der am häufigsten begangene Weg zur Mittelmäßigkeit.",
        "Der erste Schritt ist, dass du sagen musst, dass du es kannst.",
        "Die Welt kann dir nicht sagen, wer du bist – du musst herausfinden, wer du bist, und dazu stehen, im Guten wie im Schlechten.",
        "Du wirst deine Misserfolge erkennen müssen. Du wirst sie annehmen und herausfinden müssen, wie du sie überwindest.",
        "Mein Vater sagte mir: Nenne deinen Preis am Anfang. Wenn es jemals teurer wird als der Preis, den du nennst, geh dort weg.",
        "Würdest du an das glauben, woran du glaubst, wenn du der Einzige wärst, der daran glaubt?",
        "Es ist mir egal, was die Leute denken, denn die Leute denken nicht.",
        "Ich war nie wirklich gut in irgendetwas, außer in der Fähigkeit zu lernen.",
        "Das beste Gefühl der Welt ist, die Vorteile und Belohnungen harter Arbeit zu sehen.",
        "Meine Ziele sind so hoch, dass ich keine Zeit habe, mich in irgendeiner Weise zu entspannen.",
        "Das Leben ist zu kurz, um sich Sorgen darüber zu machen, was andere über dich sagen.",
        "Hinter jeder erfolgreichen Person steckt ein Rudel von Neidern.",
        "Du kannst etwas aus deinem Leben machen – es hängt nur von deinem Antrieb ab.",
        "Du hast Feinde? Gut – das bedeutet, dass du tatsächlich für etwas eingestanden bist.",
        "Aller Erfolg beginnt mit Selbstdisziplin – es beginnt bei dir.",
        "Mit Antrieb und ein bisschen Talent kannst du Berge versetzen.",
        "Scheitern ist keine Option – es ist nur eine Stufe.",
        "Erfolg kommt nicht über Nacht – es ist, wenn du jeden Tag ein bisschen besser wirst als am Tag zuvor; das summiert sich.",
        "Wenn das Leben dich in schwierige Situationen bringt, sag nicht \"warum ich\" – sag einfach \"versuch es mit mir\".",
        "Erfolg in allem kommt immer auf dies hinaus: Fokus und Einsatz. Und beides kontrollieren wir.",
        "Ich habe einmal einen weisen Mann sagen hören, es gibt keine perfekten Menschen, nur perfekte Absichten.",
        "Sehr oft hört man auf zu gehen, weil man sagt: Ich bin es leid, diesen Hügel zu erklimmen. Ich werde nie den Gipfel erreichen – und man ist nur zwei Schritte entfernt.",
        "Fordere dich selbst heraus – das ist der einzige Weg, der zu Wachstum führt.",
        "Du kannst dir Talent nicht anrechnen – du kannst dir nur anrechnen, es genutzt zu haben.",
        "Der beste Weg, eine Niederlage zu garantieren, ist aufzugeben.",
        "Ich könnte es entweder geschehen lassen beobachten oder ein Teil davon sein.",
        "Wenn etwas wichtig genug ist, tust du es, selbst wenn die Chancen nicht zu deinen Gunsten stehen.",
        "Wenn du morgens aufstehst und denkst, dass die Zukunft besser wird, ist es ein heller Tag – sonst nicht.",
        "Es ist in Ordnung, alle Eier in einen Korb zu legen, solange du kontrollierst, was mit dem Korb passiert.",
        "Wenn du nur Dinge tust, bei denen du die Antwort schon vorher kennst, verschwindet dein Unternehmen.",
        "Du musst bereit sein, missverstanden zu werden, wenn du innovativ sein willst.",
        "Es gibt keinen schlechten Zeitpunkt für Innovation.",
        "Chancen zu schaffen bedeutet, dort hinzuschauen, wo andere es nicht tun.",
        "Schweiß-Eigenkapital ist das wertvollste Eigenkapital, das es gibt.",
        "Wir leben in einer Gesellschaft, in der harte Arbeit fast immer belohnt wird.",
        "Das Universum ist nicht verpflichtet, für dich Sinn zu ergeben.",
        "Es gibt keine größere Bildung als die, die selbst angetrieben ist.",
        "Niemand ist dumm, der neugierig ist.",
        "Ich kenne keine Zeit in der Menschheitsgeschichte, in der Unwissenheit besser war als Wissen.",
        "Trainiere dich darin, nichts persönlich zu nehmen.",
        "Ein Mann kann aus sich machen, was er will, wenn er wirklich daran glaubt – er muss bereit sein für harte Arbeit und viele Enttäuschungen.",
        "Jeder von uns muss erkennen, dass unsere Absicht immer durchscheint.",
        "Wir können nicht ignorieren, was wir wirklich erschaffen wollen.",
        "Nur du und du allein kannst deine Situation verändern.",
        "Sei dankbar für die schweren Zeiten, denn sie haben dich geformt.",
        "Um zu den oberen 1% zu gehören, musst du tun, was die 99% nicht tun.",
        "Ich schaffe meinen eigenen Weg – er war gerade und schmal. Ich sah es so: Du warst entweder in meinem Weg oder nicht.",
        "Wir alle haben Selbstzweifel. Du leugnest sie nicht, aber du kapitulierst auch nicht vor ihnen. Du nimmst sie an.",
        "Viele Führungskräfte scheitern, weil sie nicht den Mut haben, den Nerv zu treffen oder die richtige Saite anzuschlagen.",
        "Der Moment, in dem du aufgibst, ist der Moment, in dem du jemand anderen gewinnen lässt.",
        "Wenn du Angst vor dem Scheitern hast, wirst du wahrscheinlich scheitern.",
        "Ich erkannte, dass Einschüchterung nicht wirklich existiert, wenn man die richtige Einstellung hat.",
        "Dies ist der Moment, in dem ich akzeptiere, dass die herausforderndsten Zeiten immer hinter mir und vor mir liegen werden.",
        "Niemand weiß, dass er Champion wird – man muss arbeiten, um dorthin zu gelangen.",
        "Mein Glaube ist stärker als dein Zweifel.",
        "Erfolg bedeutet, zufrieden zu sein mit dem, was du jeden Tag tust. Es bedeutet, stolz auf den besseren Menschen zu sein, der du wirst.",
        "Wenn du erfolgreich sein willst, musst du bereit sein, jede Verbindung zu nutzen, die du hast.",
        "Talent ist nie genug. Bis auf wenige Ausnahmen sind die besten Spieler die härtesten Arbeiter.",
        "Gib nicht auf – freunde dich mit Menschen an, die dir helfen, hart zu arbeiten.",
        "Feiere einfach das Leben, das du hattest, nicht das Leben, das du hättest haben können.",
        "Ich bin arm aufgewachsen, aber ich hatte keine armen Träume.",
        "Du bist der Einzige, der den Unterschied machen kann. Was auch immer dein Traum ist, geh ihm nach.",
        "Das Leben hört nicht auf, weil dir etwas passiert.",
        "Im Leben werden sowohl Gewinnen als auch Verlieren passieren – was niemals akzeptabel ist, ist Aufgeben.",
        "Wisst ihr, wie oft ich in meinem Leben abgelehnt wurde? Wie oft mir gesagt wurde, dass ich etwas nicht schaffen kann?",
        "Oft stelle ich fest, dass Menschen, die mit dem meisten Talent gesegnet sind, nie diese Einstellung entwickeln. Und die, die nicht so gesegnet sind, sind die wettbewerbsfähigsten und haben das größte Herz.",
        "Ich dachte, ich würde nie eine Chance bekommen zu spielen, bis ich eines Tages eine bekam – weil ich vorbereitet war und sich die Gelegenheit bot.",
        "Ich liebe einfach den Wettbewerb und ich liebe es, mich zu verbessern.",
        "Zu oft passiert etwas im Leben, und wir geben anderen die Schuld dafür, dass wir nicht glücklich oder zufrieden oder erfüllt sind.",
        "Dein Leben wird das sein, was du daraus machst.",
        "Ich werde mich nicht aufregen, weil jemand etwas Schlechtes über mich gesagt hat.",
        "Du kannst nicht an der Seitenlinie des Lebens sitzen.",
        "Meine Botschaft ist einfach: Übernimm die Kontrolle über dein Leben.",
        "Wenn du einer der Anführer des Teams bist, gibt es keine freien Tage.",
        "Verlasse dich nicht auf andere. Du wirst großartige Unterstützung von vielen Menschen haben. Aber niemand wird dir etwas einfach so geben.",
        "Dinge korrigieren sich nicht von selbst – du musst rausgehen und hart arbeiten, um sie zu korrigieren.",
        "Wenn du nicht spielst, um zu gewinnen, spiele gar nicht.",
        "Wenn du nicht an dich selbst glaubst, warum sollte es dann jemand anderes tun.",
        "Manchmal werden im Leben die größten Herausforderungen zu den besten Dingen, die dir passieren.",
        "Ich liebe einfach harte Arbeit.",
        "Die wahren Wettkämpfer sind die, die immer spielen, um zu gewinnen.",
        "Jage nicht dem Geld hinterher – jage dem Traum hinterher.",
        "Wenn du fliegen willst, musst du die Dinge loslassen, die dich herunterziehen.",
        "Ich will nicht, dass du träumst – ich will, dass du es tust.",
        "Jeder, der jemand sein will, wird so hart arbeiten, wie er kann, um diesen Traum zu erfüllen.",
        "Ich habe nie versucht, die Tatsache zu verbergen, dass es meine Absicht ist, der Beste zu werden.",
        "Wenn du nicht glaubst, dass du der Beste bist, wirst du nie alles erreichen, wozu du fähig bist.",
        "Heute gibt es Gelegenheiten, von denen niemand weiß, ob sie in der Zukunft wiederkommen.",
        "Talent ohne harte Arbeit ist nichts.",
        "Es macht mir nichts aus, wenn die Leute mich hassen, denn es treibt mich an.",
        "Talent ist nicht alles. Man kann es von der Wiege an haben, aber man muss das Handwerk lernen, um der Beste zu sein.",
        "Ich fühle ein endloses Bedürfnis zu lernen, mich zu verbessern, mich weiterzuentwickeln – um mit mir selbst zufrieden zu sein.",
        "Deine Liebe macht mich stark. Dein Hass macht mich unaufhaltsam.",
        "Du kannst alles überwinden, wenn du nur etwas genug liebst.",
        "Ich bin erfolgreich, weil ich Opfer für den Erfolg gebracht habe.",
        "Mein Ehrgeiz ist es, immer besser und besser zu werden.",
        "Ich fange früh an und bleibe lange. Tag für Tag, Jahr für Jahr – es hat 17 Jahre und 114 Tage gedauert, um ein Übernachterfolg zu werden.",
        "Die Person, die mich vom Glücklichsein abgehalten hat, war ich selbst.",
        "Die einfache Handlung, aufmerksam zu sein, kann dich weit bringen.",
        "Verwechsle nicht die Wahrheit mit der Meinung der Masse. Diese sind fast nie auch nur annähernd ähnlich.",
        "Es gibt einen Unterschied zwischen dem Weg zu kennen und den Weg zu gehen.",
        "Ich habe keine Zeit, die ganze Nacht wach zu liegen und mir Sorgen darüber zu machen, was jemand, der mich nicht liebt, über mich zu sagen hat.",
        "Du darfst nicht zögerlich sein, was du bist.",
        "Es gibt immer etwas zu verbessern – du bist nie am Ziel.",
        "Ich will das sein, was ich immer sein wollte: dominant.",
        "Ich versuche einfach, so gut zu sein, wie ich kann, und hoffe, dass es das Beste aller Zeiten ist.",
        "Ich will nicht so gut werden, wie ich einmal war – ich will besser werden.",
        "Mein Verstand ist mein größtes Kapital. Ich erwarte, jedes Turnier zu gewinnen, an dem ich teilnehme.",
        "Die Jungs, die ihre Emotionen wirklich kontrollieren, werden gewinnen.",
        "Egal wie gut du bist, du kannst immer besser werden – und das ist das Aufregende daran.",
        "Um anderen zu helfen, musst du zuerst lernen, dir selbst zu helfen.",
        "Nichts von Wert kommt jemals zu jemandem, außer als Ergebnis harter Arbeit.",
        "Ich werde keinem Mann erlauben, meine Seele zu erniedrigen, indem er mich dazu bringt, ihn zu hassen.",
        "Du kannst keinen Mann niederhalten, ohne mit ihm unten zu bleiben.",
        "Der Charakter, nicht die Umstände, macht den Mann.",
        "Es gibt zwei Wege, seine Stärke auszuüben: einer ist niederdrücken, der andere ist hochziehen.",
        "Ich bin viel öfter gescheitert als ich erfolgreich war.",
        "Ich tue heute, was andere nicht tun, damit ich morgen erreichen kann, was andere nicht können.",
        "Selbst wenn du verlierst, verliere nicht die Lektion.",
        "Das Einfachste, was man verkaufen kann, ist die Wahrheit.",
        "Warte nicht auf den perfekten Zeitpunkt – du wirst ewig warten. Nutze immer die Zeit, die du hast, und mache sie perfekt.",
        "Du kannst nur so viele Dinge großartig machen – alles andere solltest du beiseite legen.",
        "Das Leben ist zerbrechlich. Uns ist kein Morgen garantiert, also gib alles, was du hast.",
        "Ich habe keine Angst davor, mich zum Narren zu machen.",
        "Respekt motiviert mich, nicht Erfolg.",
        "Wenn du über den Berg bist, nimmst du erst richtig Fahrt auf.",
        "Exzellenz ist keine Handlung – sie ist eine Gewohnheit.",
        "Du kannst keine Eins bekommen, wenn du Angst hast, eine Sechs zu bekommen.",
        "Du machst deine Fehler, um zu lernen, wie du an das Gute herankommst.",
        "Ein Held ist jemand, der freiwillig ins Unbekannte geht.",
        "Es gibt Millionen von Überlebenden da draußen. Mach es eine Million und eins.",
        "Gib niemals auf, denn du weißt nie, was die Flut am nächsten Tag bringt.",
        "Wenn es nicht schwer wäre, würde es jeder tun. Das Schwere macht es großartig.",
        "Wenn du nur sichere Entscheidungen triffst, wächst du nicht.",
        "Ich mache gerne etwas, wovor ich mich fürchte.",
        "Der Prozess ist der schönste Teil.",
        "Es ist leicht, das Auge zu täuschen, aber es ist schwer, das Herz zu täuschen.",
        "Werde nie zu euphorisch, werde nie zu niedergeschlagen. Nimm es Tag für Tag und lerne einfach weiter.",
        "Einsatz wird niemals infrage gestellt.",
        "Hoffe nicht darauf, dass dir jemand eine Chance gibt – schaffe dir selbst eine.",
        "Als die Leute mir sagten, ich würde es nie schaffen, hörte ich auf die eine Person, die sagte, ich könnte: mich.",
        "Es gibt einen Grund, warum man es Träume jagen nennt und nicht ihnen hinterhergehen.",
        "Um das zu haben, was du wirklich willst, musst du zuerst sein, wer du wirklich bist.",
        "Lass nicht zu, dass die Vergangenheit dich verfolgt. Denn was du in der Gegenwart tust, könnte deine Zukunft verfolgen – sei weise. Was du jetzt oder in der Zukunft tust, kann die Vergangenheit nie verbergen, aber das bedeutet nicht, dass sie dich kontrollieren darf.",
        "Dieses \"Was wäre wenn\" ist eine Wunde, die nie heilt.",
        "Wenn es einfach wäre, wäre es nicht wert.",
        "Du verdienst nichts geschenkt – du verdienst es dir.",
        "Perfektion ist nicht interessant – trotz der Widrigkeiten obenauf zu kommen: das beeindruckt mich.",
        "Nimm nicht an den \"Hab-Mitleid-mit-mir\"-Olympischen Spielen teil – darin treten wir nicht an.",
        "Wenn du etwas willst, nimmst du das Gelände, das dazugehört, egal wie es aussieht.",
        "Wahre Vision ist, wenn dein Verstand mächtiger ist als das, was vor deinen Augen liegt.",
        "Bestimmte Ereignisse bringen dich voran, bestimmte Ereignisse bewirken das Gegenteil – so scheint es. Diese Gegensätze sind Lernmöglichkeiten, die sich in der Zukunft als nützlich erweisen werden.",
        "Zahle den Preis, um der Boss zu sein, oder zahle den Preis, der mit dem Bedauern kommt.",
        "Die Meinung anderer über dich muss nicht deine Realität werden.",
        "Du bekommst nicht, was du dir wünschst, sondern was du dir erarbeitest.",
        "Selbstdisziplin beginnt mit der Beherrschung deiner Gedanken. Wenn du nicht kontrollierst, was du denkst, kannst du nicht kontrollieren, was du tust. Einfach gesagt: Selbstdisziplin ermöglicht es dir, zuerst zu denken und danach zu handeln.",
        "Was ist eine Niederlage? Nichts als Bildung; nichts als der erste Schritt zu etwas Besserem.",
        "Es kommt nicht darauf an, was dir passiert, sondern wie du darauf reagierst.",
        "Kontrolliere deinen Zorn. Wenn du Zorn gegenüber anderen hegst, kontrollieren sie dich.",
        "Deine größte Herausforderung ist, aufzutauchen, wenn dein Verstand die besten Ausreden macht.",
        "Du kannst entweder den Schmerz der Disziplin erleben oder den Schmerz des Bedauerns. Die Wahl liegt bei dir.",
        "Alles, was dich körperlich, intellektuell und geistig schwach macht – weise es als Gift zurück.",
        "Schwitze mehr im Frieden, blute weniger im Krieg.",
        "Mit dem Mut zu beginnen und der Disziplin durchzuhalten, wird der Sieg nur eine Frage der Zeit.",
        "Ein guter Anführer ist jemand, der etwas mehr als seinen Anteil an der Schuld und etwas weniger als seinen Anteil an der Anerkennung übernimmt.",
        "Sei stark, aber nicht unhöflich. Sei freundlich, aber nicht schwach. Sei mutig, aber schikaniere nicht. Sei bescheiden, aber nicht schüchtern. Sei stolz, aber nicht arrogant.",
        "Geduld ist bitter, aber ihre Frucht ist süß.",
        "Geduld ist nicht passiv – im Gegenteil, sie ist aktiv. Sie ist gesammelte Stärke.",
        "Es gibt nichts Unmögliches für den, der es versucht.",
        "Intelligenz ist nicht die Fähigkeit, Informationen zu speichern, sondern zu wissen, wo man sie findet.",
        "Zuerst ist es eine Absicht. Dann ein Verhalten. Dann eine Gewohnheit. Dann eine Praxis. Dann eine zweite Natur. Dann ist es einfach, wer du bist.",
        "Was auch immer du tun willst, tu es jetzt. Es gibt nur so viele Morgen.",
        "Leute, die sagen, es könne nicht getan werden, sollten die nicht unterbrechen, die es gerade tun.",
        "Es gibt nur eine Ecke des Universums, die du mit Sicherheit verbessern kannst – und das ist dein eigenes Selbst.",
        "Der Narr hält sich für weise, aber der Weise weiß, dass er ein Narr ist.",
        "Schmerz kann dich verändern, aber das muss keine schlechte Veränderung sein. Nimm den Schmerz und verwandle ihn in Weisheit.",
        "Zeit ist wirklich das einzige Kapital, das ein Mensch hat, und das Einzige, was er sich nicht leisten kann zu verlieren.",
        "Folge deinem eigenen Weg, egal was die Leute sagen.",
        "Tu etwas. Wenn es funktioniert, tu mehr davon. Wenn nicht, tu etwas anderes.",
        "Lernen ist das Einzige, was der Geist nie erschöpft, nie fürchtet und nie bereut.",
        "Ein Gewinner ist ein Träumer, der niemals aufgibt.",
        "Wenn du nicht für das kämpfst, was du willst, weine nicht über das, was du verloren hast.",
        "Sobald du deine Fehler akzeptiert hast, kann sie niemand mehr gegen dich verwenden.",
        "Sobald wir genug über das Universum gelernt haben, werden wir uns eingestehen, dass wir nie alles wissen werden.",
        "Sich Sorgen zu machen ist wie eine Schuld zu bezahlen, die du nicht schuldest.",
        "Du kannst niemandem etwas beibringen – du kannst ihn nur dazu bringen, zu erkennen, dass die Antworten bereits in ihm sind.",
        "Die Kraft der Gedanken kann entweder Krankheit oder Genesung verursachen.",
        "Wenn du ein Wunder sehen willst, sei ein Wunder.",
        "Es gibt drei Klassen von Menschen: die, die sehen; die, die sehen, wenn man es ihnen zeigt; die, die nicht sehen.",
        "Deine größten Ängste werden von deiner Vorstellungskraft geschaffen.",
        "Die größte Täuschung, unter der die Menschen leiden, kommt von ihren eigenen Meinungen.",
        "Wenn du alle Möglichkeiten erschöpft hast, erinnere dich: Das hast du nicht.",
        "Liebe die Hand, die das Schicksal dir austeilt, und spiele sie als deine eigene.",
        "Wenn zwei Menschen in allem übereinstimmen, ist einer von ihnen überflüssig.",
        "Der größte Wettbewerb ist der, den du mit dir selbst hast.",
        "Wenn wir müde sind, werden wir von Ideen angegriffen, die wir längst besiegt hatten.",
        "Ich bin nicht das, was mir widerfahren ist. Ich bin das, was ich zu werden beschließe.",
        "Der wichtigste Faktor für das Überleben ist weder Intelligenz noch Stärke, sondern Anpassungsfähigkeit.",
        "Glaube und Angst verlangen beide, dass du an etwas glaubst, das du nicht sehen kannst. Du wählst.",
        "Indem du dich beschwerst, zeigst du den Leuten, wie schwach du bist.",
        "Um das zu bekommen, was du liebst, musst du zuerst geduldig mit dem sein, was du hasst.",
        "Wenn alles gegen dich zu laufen scheint, denke daran, dass das Flugzeug gegen den Wind abhebt, nicht mit ihm.",
        "Du wirst über deine Ängste lachen, wenn du herausfindest, wer du wirklich bist.",
        "Frieden findet man nicht in einem ruhigeren Sturm – man findet ihn in einem besseren Boot.",
        "Du kannst die Realität ignorieren, aber du kannst die Konsequenzen des Ignorierens dieser Realität nicht ignorieren.",
        "Kein Mensch ist unglücklicher als der, der nie Widrigkeiten begegnet. Denn ihm ist es nicht erlaubt, sich zu beweisen.",
        "Ein guter Plan, der jetzt energisch umgesetzt wird, ist besser als ein perfekter Plan nächste Woche.",
        "Zu lernen und nicht zu denken ist Verschwendung. Zu denken und nicht zu lernen ist gefährlich.",
        "Angst ist eine Reaktion. Mut ist eine Entscheidung.",
        "Unabhängigkeit ist für die ganz Wenigen; sie ist ein Privileg der Starken.",
        "Es dauert das halbe Leben, bevor man entdeckt, dass das Leben ein Selbermach-Projekt ist.",
        "Spiele deine Rolle mit Ehre.",
        "Sorge ist ein Missbrauch der Vorstellungskraft.",
        "Die Brücke zwischen Wissen und Können ist Übung. Die Brücke zwischen Können und Meisterschaft ist Zeit.",
        "Je mehr ich lerne, desto mehr erkenne ich, wie viel ich noch zu lernen habe.",
        "Wenn du nicht verlierst, kannst du die Siege nicht genießen. Also muss ich beides akzeptieren.",
        "Aus dem Sieg lernen wir wenig, aus der Niederlage viel.",
        "Wer respektvoll spricht, aber seine Vorbereitungen verstärkt, wird voranschreiten. Wer kriegerisch spricht und hastig vorrückt, wird sich zurückziehen.",
        "Unser Leben ist das, was unsere Gedanken daraus machen.",
        "Es gibt eigentlich keine schwierige Sache, es sei denn, du entscheidest, dass es eine schwierige Sache ist. Ansonsten ist es einfach das Nächste, das du herausfindest.",
        "Egal in welcher Situation – lass niemals deine Emotionen deine Intelligenz überwältigen.",
        "Entscheide dich für die Art von Person, die du sein willst, und halte daran fest – ob allein oder in Gesellschaft.",
        "Wenn etwas falsch ist, repariere es, wenn du kannst. Aber gewöhne dir an, dir keine Sorgen zu machen. Sorgen haben noch nie etwas repariert.",
        "Das Leben ist keine Frage guter Karten, sondern des guten Spielens einer schlechten Hand.",
        "Es ist ein rauer Weg, der zu den Höhen der Größe führt.",
        "An dem Tag, an dem ein Mensch über das Vergnügen erhaben wird, wird er auch über den Schmerz erhaben sein.",
        "Lerne ständig weiter – es gibt immer noch etwas zu lernen.",
        "Wir können uns beschweren, dass Rosenbüsche Dornen haben, oder uns freuen, dass Dornenbüsche Rosen tragen.",
        "Sei geduldig und stark; eines Tages wird dieser Schmerz dir nützlich sein.",
        "Scheitern ist Erfolg in Arbeit.",
        "Jeder, der aufhört zu lernen, ist alt – egal ob mit zwanzig oder achtzig.",
        "Wenn du vom Verstand beherrscht wirst, bist du ein König; wenn vom Körper, ein Sklave.",
        "Stolz ist nicht das Gegenteil von Scham, sondern ihre Quelle. Wahre Demut ist das einzige Gegenmittel gegen Scham.",
        "Wenn du anfängst, dich zu verbessern, ist Einsamkeit der Preis, den du zahlst.",
        "Du wirst nicht nach der Höhe beurteilt, die du erreicht hast, sondern nach der Tiefe, aus der du geklettert bist.",
        "Ein Mann ist nicht groß, weil er nie gescheitert ist; ein Mann ist groß, weil das Scheitern ihn nicht aufgehalten hat.",
        "Ein Mann ohne Vision ist ein Mann ohne Zukunft. Ein Mann ohne Zukunft wird immer zu seiner Vergangenheit zurückkehren.",
        "Lieber mit Ehre scheitern als durch Betrug Erfolg haben.",
        "Alle Schlachten werden zuerst im Geist gewonnen oder verloren.",
        "Die Gefühle des Menschen werden schneller erregt als die Intelligenz des Menschen.",
        "Wer kauft, was er nicht braucht, bestiehlt sich selbst.",
        "Wer Geduld hat, kann haben, was er will.",
        "Der Weg des Kriegers ist lebenslang, und Meisterschaft bedeutet oft einfach, auf dem Weg zu bleiben.",
        "Drachen steigen am höchsten gegen den Wind, nicht mit ihm.",
        "Wenn die Leute wüssten, wie hart ich arbeiten musste, um meine Meisterschaft zu erlangen, würde es gar nicht so wunderbar erscheinen.",
        "Geh niemals schlafen, ohne eine Bitte an dein Unterbewusstsein gestellt zu haben.",
        "Begrüße Ereignisse, wie auch immer sie eintreten – das ist der Weg zum Frieden.",
        "Übe auch das, was unmöglich scheint.",
        "Der Mann, der zwei Hasen jagt, fängt keinen.",
        "Du wirst es schaffen, aber es wird sich immer so anfühlen, als ob du es nicht schaffst.",
        "Plane, was schwierig ist, solange es leicht ist; tu, was groß ist, solange es klein ist.",
        "Beharrlichkeit allein reicht nicht. Man muss entscheiden, ob man als Leidender oder als Krieger beharrt.",
        "Das Maß an Schärfe und Disziplin, das dich zu den Höhen bringt, von denen du träumst, ist wirklich einfach – es ist nur nicht leicht.",
        "Der größte Feind liegt nicht im Außen. Zerstörung kommt oft von innen.",
        "Alle wussten, dass es unmöglich war – bis ein Narr kam, der das nicht wusste, und es tat.",
        "Man kann keinen schwachen Mann stark machen, indem man einen starken Mann schwach macht.",
        "Du hast Macht über deinen Geist – nicht über äußere Ereignisse. Erkenne das, und du wirst Stärke finden.",
        "Ein Diamant ist nur ein Stück Kohle, das bei seiner Aufgabe geblieben ist.",
        "Das größte Risiko ist, kein Risiko einzugehen.",
        "Wenn du das Problem richtig definierst, hast du fast schon die Lösung.",
        "Die Vergangenheit ist in deinem Kopf, die Zukunft ist in deinen Händen.",
        "Das Leben ist ziemlich einfach. Du machst ein paar Sachen. Das meiste scheitert. Einiges funktioniert. Du machst mehr von dem, was funktioniert.",
        "Möge dein Pflichtgefühl eine Atmosphäre der Angst und die Neigung, Bestrebungen aufzuschieben, überschatten.",
        "Alles, was du dir je gewünscht hast, liegt auf der anderen Seite der Angst.",
        "Disziplin ist die Wahl zwischen dem, was du jetzt willst, und dem, was du am meisten willst.",
        "Konformität ist die letzte Zuflucht der Einfallslosen.",
        "Ein Diamant ist ein Stück Kohle, das bei der Arbeit geblieben ist.",
        "Es gibt keinen größeren Schaden für den Menschen als vergeudete Zeit.",
        "Verderbe nicht, was du hast, indem du dir wünschst, was du nicht hast; denke daran, dass das, was du jetzt hast, einst zu den Dingen gehörte, auf die du nur gehofft hast.",
        "Ein Mann, der ein Meister der Geduld ist, ist Meister von allem anderen.",
        "Stelle niemals Leidenschaft vor Prinzipien – selbst wenn du gewinnst, wirst du verlieren.",
        "Manche wollen, dass es passiert, manche wünschen, es würde passieren, andere machen es möglich.",
        "Wir steigen nicht auf das Niveau unserer Erwartungen – wir fallen auf das Niveau unseres Trainings.",
        "Es ist leichter, Männer zu finden, die freiwillig sterben, als solche, die bereit sind, Schmerz mit Geduld zu ertragen.",
        "Du kannst kein Podium erwarten, wenn du nicht am Rennen teilnimmst.",
        "Der, der fällt und aufsteht, ist stärker als der, der es nie versucht hat.",
        "Schlechte Nachricht: Du wirst nicht zu jedem passen. Gute Nachricht: Die Großen tun das nie.",
        "Ich war nie talentiert – ich bin nur gut darin, nie aufzugeben.",
        "Glück ist nicht die Abwesenheit von Problemen – es ist die Fähigkeit, mit ihnen umzugehen.",
        "Wenn du tust, was einfach ist, wird dein Leben schwer sein.",
        "Du kannst nicht zurückgehen und den Anfang ändern, aber du kannst dort beginnen, wo du bist, und das Ende ändern.",
        "Mehr wird aufgefangen als gelehrt.",
        "Die, die nie Fehler machen, arbeiten für die von uns, die es tun.",
        "Eine neue Idee darf nicht nach ihren unmittelbaren Ergebnissen beurteilt werden.",
        "Du bist nie bereit für das, was du tun musst. Du tust es einfach. Das macht dich bereit.",
        "Geh Risiken ein: Wenn du gewinnst, wirst du glücklich sein; wenn du verlierst, wirst du weise sein.",
        "Ein Volk, das seine Privilegien über seine Prinzipien stellt, verliert bald beides.",
        "Der schnellste Weg zu Sinn und Erfolg: Wähle eine Sache und geh voll darauf ein.",
        "Hab keine Angst, von vorne anzufangen. Diesmal fängst du nicht bei null an – du fängst mit Erfahrung an.",
        "Es gibt nichts Edleres, als seinem Mitmenschen überlegen zu sein; wahre Vornehmheit ist, seinem früheren Selbst überlegen zu sein.",
        "Du wirst den Respekt aller verdienen, wenn du damit beginnst, den Respekt vor dir selbst zu verdienen.",
        "Erschaffe eine Vision davon, wer du sein willst, und lebe dann in dieses Bild hinein, als wäre es bereits wahr.",
        "Der Preis der Exzellenz ist Disziplin. Die Kosten der Mittelmäßigkeit sind Enttäuschung.",
        "Schwierigkeiten stärken den Geist, wie Arbeit den Körper stärkt.",
        "Du kannst nicht hoffen, in Bereichen Fortschritte zu machen, in denen du keine Maßnahmen ergriffen hast.",
        "Keine Menge an Angst macht irgendeinen Unterschied bei dem, was passieren wird.",
        "Zeige mir einen Mann mit durchschnittlicher Fähigkeit, aber außergewöhnlichem Verlangen, und ich zeige dir jedes Mal einen Gewinner.",
        "Der schnellste Weg zum Erfolg ist, jetzt zu beginnen und es unterwegs herauszufinden.",
        "Menschen entscheiden nicht über ihre Zukunft – sie entscheiden über ihre Gewohnheiten, und ihre Gewohnheiten entscheiden über ihre Zukunft.",
        "Lehre deine Kinder früh, was du spät gelernt hast.",
        "Wenn du 100 Stunden pro Jahr in eine Disziplin investierst (das sind nur 18 Minuten am Tag), wirst du besser sein als 95% der Welt in dieser Disziplin.",
        "Die Aufgabe ist nicht so sehr, zu sehen, was noch niemand gesehen hat, sondern über das, was jeder sieht, zu denken, was noch niemand gedacht hat.",
        "Wenn dich jede Reibung irritiert, wie soll dann dein Spiegel poliert werden?",
        "Angst ist nur so tief, wie der Geist es zulässt.",
        "Schwierigkeit ist das, was das Genie weckt.",
        "Was Licht geben soll, muss Brennen ertragen.",
        "Ich habe gelernt, dass Erfolg nicht so sehr an der Position gemessen werden sollte, die man im Leben erreicht hat, sondern an den Hindernissen, die man beim Versuch, erfolgreich zu sein, überwunden hat.",
        "Bequemlichkeit ist die schlimmste Sucht.",
        "Du wirst zu dem, dem du deine Aufmerksamkeit schenkst.",
        "Die Umstände machen den Menschen nicht – sie offenbaren ihn nur sich selbst.",
        "Verschwende keine Zeit mehr mit dem Streit darüber, was ein guter Mensch sein sollte. Sei einer.",
        "Wer die Welt bewegen will, bewege zuerst sich selbst.",
        "Zwischen Reiz und Reaktion liegt ein Raum. In diesem Raum liegt unsere Macht, unsere Reaktion zu wählen. In unserer Reaktion liegen unser Wachstum und unsere Freiheit.",
        "Es gibt nichts außerhalb von dir selbst, das dich jemals befähigen kann, besser, stärker, reicher, schneller oder klüger zu werden. Alles ist in dir. Alles existiert. Suche nichts außerhalb deiner selbst.",
        "Sei tolerant gegenüber anderen und streng mit dir selbst.",
        "Zwei Dinge definieren dich: Deine Geduld, wenn du nichts hast, und deine Haltung, wenn du alles hast.",
        "Du wachst nicht einfach auf und bist der Schmetterling.",
        "Zähigkeit ist die Fähigkeit, festzuhalten, wenn Loslassen am attraktivsten erscheint.",
        "Es gibt Risiken und Kosten beim Handeln. Aber sie sind weit geringer als die langfristigen Risiken bequemen Nichtstuns.",
        "Um große Dinge zu erreichen, braucht man zwei Dinge: einen Plan und nicht ganz genug Zeit.",
        "Zweifel kann nur durch Handeln beseitigt werden.",
        "Wenn deine Handlungen andere dazu inspirieren, mehr zu träumen, mehr zu lernen, mehr zu tun und mehr zu werden, bist du ein Anführer.",
        "Es geht nicht darum, eine makellose Bilanz zu haben. Es geht darum, aus den Makeln in deiner Bilanz zu lernen.",
        "Sei mutig genug, bei etwas Neuem schlecht zu sein.",
        "Geh klüger ins Bett als du aufgewacht bist.",
        "Langsamer Erfolg baut Charakter auf, schneller Erfolg baut Ego auf.",
        "Nur weil jemand stolpert und seinen Weg verliert, heißt das nicht, dass er für immer verloren ist.",
        "Aber wir können nicht einfach dasitzen und unsere Wunden ewig anstarren.",
        "Und jetzt, da du nicht perfekt sein musst, kannst du gut sein.",
        "Erfolg kommt von der gnadenlosen Umsetzung der Grundlagen.",
        "Es braucht viel harte Arbeit, um etwas einfach zu machen.",
        "Jeder denkt daran, die Welt zu verändern, aber niemand denkt daran, sich selbst zu verändern.",
        "Die Engstirnigen brauchen ihre Kunst mundgerecht serviert.",
        "Tu etwas, statt die Zeit totzuschlagen. Denn die Zeit schlägt dich tot.",
        "Lass jede Entscheidung im Einklang mit deiner Vision sein.",
        "Wenn du etwas Größeres als den Durchschnitt tun willst, kannst du die Angst, ein Außenseiter zu sein, nicht zugestehen.",
        "Was am meisten zählt, ist, wie gut du durch das Feuer gehst.",
        "Du bist eine Entscheidung von einem völlig anderen Leben entfernt.",
        "Wenn du für morgen lebst, wirst du immer einen Tag hinterher sein.",
        "Mach das Beste aus dir, denn das ist alles, was du hast.",
        "Augen sind nutzlos, wenn der Geist blind ist.",
        "Auf lange Sicht treffen Menschen nur das, worauf sie zielen. Daher sollten sie, auch wenn sie sofort scheitern, lieber auf etwas Hohes zielen.",
        "Wer ein Warum zu leben hat, erträgt fast jedes Wie.",
        "Menschen lassen sich in 2 Gruppen einteilen: die eine geht voran und erreicht etwas, die andere kommt danach und kritisiert.",
        "Eine schlechte Einstellung ist wie ein platter Reifen. Du kommst nirgendwohin, bis du ihn wechselst.",
        "Kein Vogel fliegt zu hoch, wenn er mit seinen eigenen Flügeln fliegt.",
        "Löse das Problem oder verlasse das Problem. Lebe nicht mit dem Problem.",
        "Handle nach deinen Prinzipien, nicht nach deiner Stimmung.",
        "Wer sich an nichts bindet, wird von allem abgelenkt.",
        "Wenn wir danach streben, besser zu werden als wir sind, wird alles um uns herum auch besser.",
        "Es gibt keine Leidenschaft in einem Leben, das weniger ist als das, wozu du fähig bist.",
        "Ein kreativer Mensch wird vom Wunsch zu erreichen motiviert, nicht vom Wunsch, andere zu schlagen.",
        "Das Leben ist eine lange Vorbereitung auf etwas, das nie passiert.",
        "Ich höre nicht mehr darauf, was die Leute sagen – ich schaue nur noch, was sie tun. Verhalten lügt nie.",
        "Intelligente Menschen lernen von allem und jedem; durchschnittliche von ihren Erfahrungen. Die Dummen haben bereits alle Antworten.",
        "Die erste Regel ist, einen ungetrübten Geist zu bewahren. Die zweite ist, die Dinge ins Auge zu fassen und sie für das zu erkennen, was sie sind.",
        "Es ist immer ein Kampf, schwereres Gewicht zu heben.",
        "Ein Mann, der das Leiden fürchtet, leidet bereits an dem, was er fürchtet.",
        "Wenn ein Mann nicht weiß, zu welchem Hafen er segelt, ist kein Wind günstig.",
        "Ich tue immer das, was ich nicht kann, um zu lernen, wie es geht.",
        "Du baust auf Misserfolg auf. Du benutzt ihn als Sprungbrett. Schließ die Tür zur Vergangenheit. Du versuchst nicht, die Fehler zu vergessen, aber du verweilst nicht dabei. Du lässt nicht zu, dass sie deine Energie, deine Zeit oder deinen Raum einnehmen.",
        "Der Inhalt deines Charakters ist deine Wahl. Tag für Tag wird das, was du wählst, denkst und tust, zu dem, wer du wirst.",
        "Die Feiglinge fingen nie an und die Schwachen starben unterwegs.",
        "Wenn du morgens aufstehst, denke daran, was für ein kostbares Privileg es ist, am Leben zu sein – zu atmen, zu denken, zu genießen, zu lieben.",
        "Das Geheimnis des Erfolgs ist Konzentration auf das Ziel.",
        "Das Einzige, was gefährlicher ist als Unwissenheit, ist Arroganz.",
        "Wir sind, was wir wiederholt tun. Exzellenz ist daher keine Handlung, sondern eine Gewohnheit.",
        "Während wir auf das Leben warten, vergeht das Leben.",
        "Erfolg ist nichts anderes als einige wenige einfache Disziplinen, die jeden Tag praktiziert werden.",
        "Je mehr er weiß, desto bewusster wird er sich seiner Unwissenheit.",
        "Das Hindernis für die Handlung fördert die Handlung. Was im Weg steht, wird zum Weg.",
        "Unsere größte Schwäche liegt im Aufgeben. Der sicherste Weg zum Erfolg ist, es immer noch einmal zu versuchen.",
        "Ein Edelstein kann nicht ohne Reibung poliert werden, noch ein Mensch ohne Prüfungen vervollkommnet werden.",
        "Dein Wert besteht in dem, was du bist, nicht in dem, was du hast.",
        "Der Übeltäter ist unglücklicher als der, dem Unrecht geschieht.",
        "Einer der wahrsten Tests für Integrität ist ihre kompromisslose Weigerung, kompromittiert zu werden.",
        "Gott gibt denen nichts, die die Arme verschränkt halten.",
        "Zu wissen, wie man denkt, befähigt dich weit mehr als die, die nur wissen, was sie denken sollen.",
        "Wenn du planst, weniger zu sein, als du fähig bist, wirst du wahrscheinlich alle Tage deines Lebens unglücklich sein.",
        "Es gibt nichts Besseres als Widrigkeiten. Jede Niederlage, jeder Herzschmerz, jeder Verlust enthält seinen eigenen Samen, seine eigene Lektion, wie du deine Leistung beim nächsten Mal verbessern kannst.",
        "Lerne, den Hass zu lieben. Nimm ihn an. Genieße ihn. Du hast ihn dir verdient. Jeder hat ein Recht auf seine eigene Meinung, und jeder sollte eine über dich haben. Hasser sind ein gutes Problem. Niemand hasst die Guten. Sie hassen die Großartigen.",
        "Akzeptiere deine Unfähigkeit, alles zu kontrollieren. Übernimm Verantwortung für alles, was unter deiner Kontrolle steht. Akzeptiere, dass innere und äußere Hindernisse existieren. Akzeptiere, dass du ausgestattet bist, sie alle zu bewältigen.",
        "Erfahrung ist die härteste Art von Lehrer. Sie gibt dir zuerst den Test und danach die Lektion.",
        "Wir reifen durch den Schaden, nicht durch die Jahre.",
        "Wenn du deprimiert bist, lebst du in der Vergangenheit. Wenn du ängstlich bist, lebst du in der Zukunft. Wenn du in Frieden bist, lebst du in der Gegenwart.",
        "Wenn du denkst, wir können die Welt nicht verändern, bedeutet das nur, dass du nicht einer von denen bist, die es tun werden.",
        "Vielleicht geht es nicht um ein glückliches Ende. Vielleicht geht es um die Geschichte.",
        "Manche Menschen bringen Freude, wohin sie auch gehen, und manche bringen Freude, wann immer sie gehen.",
        "Beobachte ständig, dass alle Dinge durch Veränderung geschehen, und gewöhne dich daran zu bedenken, dass die Natur des Universums nichts so sehr liebt wie die Veränderung.",
        "Zu gut zu sein ist leicht langweilig.",
        "Zu oft genießen wir den Komfort der Meinung ohne das Unbehagen des Denkens.",
        "Lernen ohne Denken ist vergeblich; Denken ohne Lernen ist gefährlich.",
        "Ein Mann mit Überzeugung wird hundert überwältigen, die nur Meinungen haben.",
        "Narren vermehren sich, wenn weise Männer schweigen.",
        "Sei bereit, jedes System zu überarbeiten, jede Methode zu verwerfen, jede Theorie aufzugeben, wenn der Erfolg der Aufgabe es erfordert.",
        "Anderen bei ihrer Entwicklung und ihrem Erfolg im Leben zu helfen, ist eine Belohnung an sich und hat nur Wert, wenn nichts dafür erwartet wird.",
        "Jetzt ist keine Zeit, darüber nachzudenken, was du nicht hast. Denke darüber nach, was du mit dem, was da ist, tun kannst.",
        "Ich würde sagen, ich bin ein Werk in Arbeit, aber das würde nahelegen, dass ich eines Tages kein Werk in Arbeit mehr sein werde.",
        "Gib nicht auf. Normalerweise ist es der letzte Schlüssel am Bund, der die Tür öffnet.",
        "Das Leben ist eine Komödie für die, die denken, eine Tragödie für die, die fühlen.",
        "Taktgefühl ist die Fähigkeit, jemandem zu sagen, er solle zur Hölle fahren, und zwar so, dass er sich auf die Reise freut.",
        "Lass das Unrecht, das ein anderer getan hat, dort, wo es entstand.",
        "Beunruhige dich nicht, indem du dir dein ganzes Leben auf einmal vorstellst. Denke nicht immer darüber nach, welche Leiden und wie viele dich möglicherweise treffen könnten.",
        "Jedes Mal, wenn ich denke, ich wüsste alles, stellt sich heraus, dass \"alles\" ein bisschen mehr Volumen hat, als ich angenommen habe.",
        "Der Unterschied zwischen Dummheit und Genie ist, dass Genie seine Grenzen hat.",
        "Es ist besser, ein Krieger in einem Garten zu sein als ein Gärtner in einem Krieg.",
        "Großer Erfolg kommt immer mit dem Risiko enormen Scheiterns.",
        "Erfolg kommt von Neugier, Konzentration, Beharrlichkeit und Selbstkritik.",
        "Es ist das Zeichen eines gebildeten Geistes, einen Gedanken unterhalten zu können, ohne ihn zu akzeptieren.",
        "Die Meinung von 10.000 Menschen hat keinen Wert, wenn keiner von ihnen etwas über das Thema weiß.",
        "Je mehr wir Dinge außerhalb unserer Kontrolle schätzen, desto weniger Kontrolle haben wir.",
        "Mach Reisen. Versuche sie. Es gibt nichts anderes.",
        "Die Herkunft sollte niemals ein Hindernis für den Erfolg sein. Ein bescheidener Start im Leben kann mehr Hilfe als Hindernis sein.",
        "Lass nicht zu, dass die Unzulänglichkeiten eines anderen dich zu kurz kommen lassen.",
        "Unser Neid dauert immer länger als das Glück derer, die wir beneiden.",
        "Aus nichts wird nichts.",
        "Schwache Menschen rächen sich. Starke Menschen vergeben. Intelligente Menschen ignorieren.",
        "Ich kontrolliere den Wind nicht; ich studiere ihn nur.",
        "Ehre bringt vielleicht keine Macht, aber sie bringt Respekt. Und Respekt verdient Macht.",
        "Die endgültige Waffe ist das Gehirn – alles andere ist ergänzend.",
        "Wenn du deine Neigung, leicht aufzugeben, nicht überwindest, führt dein Leben zu nichts.",
        "Training ist wie Bodenfegen. Nur weil wir es einmal gemacht haben, heißt das nicht, dass der Boden für immer sauber ist.",
        "Denke daran, dass wir es sind, die quälen, wir, die Schwierigkeiten schaffen – das heißt, unsere Meinungen. Was bedeutet es zum Beispiel, beleidigt zu werden? Stell dich neben einen Felsen und beleidige ihn – was hast du erreicht? Wenn jemand auf eine Beleidigung wie ein Felsen reagiert, was hat der Beleidiger mit seiner Schmähung gewonnen?",
        "In Abwesenheit eines Zwecks wird das Leben zu einer endlosen Reise ins Nirgendwo.",
        "Nur die Toten haben das Ende des Krieges gesehen.",
        "Vorbeugen ist besser als heilen.",
        "Nichts, was durch Zwang gelehrt wird, bleibt in der Seele.",
        "Alles, was in deinem Leben existiert, tut dies aus zwei Gründen: etwas, das du getan hast, oder etwas, das du nicht getan hast.",
        "Ein Mensch ohne Ethik ist ein wildes Tier, das auf diese Welt losgelassen wurde.",
        "Denken ist schwierig – deshalb urteilen die meisten Menschen.",
        "Du findest keine Willenskraft – du erschaffst sie.",
        "Das Wort glücklich würde seine Bedeutung verlieren, wenn es nicht durch Traurigkeit ausgeglichen würde.",
        "Bete nicht um ein einfaches Leben. Bete um die Stärke, ein schwieriges zu ertragen.",
        "Du bist nicht alles, was du sein könntest, und du weißt es.",
        "Denke daran zu leben, während du damit beschäftigt bist zu überleben.",
        "Pläne sind nichts, Planung ist alles.",
        "Ein Mann, der es wagt, eine Stunde seiner Zeit zu verschwenden, hat den Wert des Lebens nicht entdeckt.",
        "Du musst entscheiden, wer du bist, und die Welt zwingen, mit dir umzugehen – nicht mit ihrer Vorstellung von dir.",
        "Die Kunst des Lebens gleicht mehr dem Ringen als dem Tanzen, insofern sie bereit steht gegen das Zufällige und Unvorhergesehene und nicht leicht zu Fall kommt.",
        "Mit zunehmendem Alter achte ich weniger auf das, was Menschen sagen. Ich schaue nur, was sie tun.",
        "Ich schnalle den Gürtel enger, bevor ich um Hilfe bitte.",
        "Niemand ist so gebaut wie du – du hast dich selbst entworfen.",
        "Kein Mann hat das Recht, ein Amateur in Sachen körperliches Training zu sein. Es ist eine Schande für einen Mann, alt zu werden, ohne die Schönheit und Stärke zu sehen, zu der sein Körper fähig ist.",
        "Je näher ein Mensch einem ruhigen Geist kommt, desto näher ist er der Stärke.",
        "Hier ist eine Regel, die du dir für die Zukunft merken solltest, wenn dich etwas versucht, bitter zu werden: nicht \"Das ist Unglück\", sondern \"Dies würdig zu ertragen ist Glück\".",
        "Wenn du in etwas gut bist, wirst du es jedem erzählen. Wenn du in etwas großartig bist, werden sie es dir sagen.",
        "Zuerst ignorieren sie dich. Dann verspotten sie dich. Dann greifen sie dich an und wollen dich verbrennen. Und dann bauen sie dir Denkmäler.",
        "Freiheit bedeutet Verantwortung. Deshalb scheuen die meisten Menschen sie.",
        "Wenn du die Wahrheit sagst, musst du dir nichts merken.",
        "Deine Zeit kommt, wenn du weitermachst.",
        "Nicht den Tod sollte ein Mensch fürchten, sondern er sollte fürchten, nie angefangen zu haben zu leben.",
        "Die heutigen Abläufe sind die morgigen Ergebnisse. Wenn du dich in die heutigen Abläufe verlieben kannst, wirst du die morgigen Ergebnisse lieben.",
        "Alle Probleme der Menschheit rühren von der Unfähigkeit des Menschen her, ruhig allein in einem Zimmer zu sitzen.",
        "Lass dich niemals von der Zukunft beunruhigen. Du wirst ihr begegnen, wenn es sein muss, mit denselben Waffen der Vernunft, die dich heute gegen die Gegenwart wappnen.",
        "Ein Mann reift durch Schmerz, Misserfolg, Ablehnung, Verlust, Respektlosigkeit und Herzschmerz – nicht durch Alter.",
        "Wir schmieden die Ketten, die wir im Leben tragen.",
        "Um etwas auf hohem Niveau zu tun, muss es eine Besessenheit sein.",
        "Wenn du dich verbessern willst, sei zufrieden damit, für töricht und dumm gehalten zu werden in Bezug auf äußere Dinge.",
        "Gewalt ist die letzte Zuflucht der Unfähigen.",
        "Angst ist wie Feuer – sie kann hilfreich sein, wenn du weißt, wie man sie einsetzt. Wenn nicht, wirst du verbrannt.",
        "Um großartig erfolgreich zu sein, musst du bereit sein, großartig zu scheitern. Wenn du beides nicht kannst, hast du ein Problem.",
        "Wir reden immer davon, dass jemand uns \"grundlos\" nicht mag, aber Menschen werden dich auch \"grundlos\" mögen. Also lege nicht zu viel Gewicht auf eine der beiden Seiten.",
        "Feiglinge sterben viele Male vor ihrem Tod; die Tapferen schmecken den Tod nur einmal.",
        "Nichts ist schwieriger, und deshalb kostbarer, als die Fähigkeit zu entscheiden.",
        "Gehe einen einzigen Pfad, werde weder übermütig durch den Sieg noch gebrochen durch die Niederlage, ohne Vorsicht zu vergessen, wenn alles ruhig ist, oder ängstlich zu werden, wenn Gefahr droht.",
        "Die Seele wird in der Farbe ihrer Gedanken gefärbt.",
        "Ich bitte nicht um eine leichtere Last, sondern um breitere Schultern.",
        "Verhandle nicht mit dir selbst. Weis dich an.",
        "Du kannst nicht gleichzeitig starken Charakter und ein einfaches Leben wollen.",
        "Mut ist nicht, die Kraft zu haben weiterzugehen – es ist weiterzugehen, wenn du keine Kraft hast.",
        "Das Leben passiert dir nicht, es passiert unter deiner Beteiligung.",
        "Es ist tödlich, in einen Krieg einzutreten, ohne den Willen, ihn zu gewinnen.",
        "Du weißt nie, wie stark du bist, bis Starksein deine einzige Option ist.",
        "Man kann es nicht allen recht machen – manchmal musst du handeln und alle anderen reagieren lassen.",
        "Es gibt keine Frage des \"Ob\", es gibt nur die Frage des Wann – wenn du entschlossen bist an der Mission.",
        "Wie lange wirst du noch warten, bevor du das Beste für dich selbst verlangst?",
        "Die Welt verspricht dir Bequemlichkeit, aber du wurdest nicht für Bequemlichkeit gemacht. Du wurdest für Größe gemacht.",
        "Integrität ist kein schneller Weg, aber ein sicherer Weg.",
        "Sei dein eigener größter Fan, dein eigener größter Gläubiger, und trage es auf deinem Rücken.",
        "Sage dir zuerst, was du sein willst; und dann tu, was du tun musst.",
        "Ich fürchte den Tag, an dem die Technologie unsere menschliche Interaktion übertrifft. Die Welt wird eine Generation von Idioten hervorbringen.",
        "Es kommt nicht darauf an, was du trägst, sondern wie du es trägst.",
        "Weise dein Gefühl der Verletzung zurück, und die Verletzung selbst verschwindet.",
        "Mache keine kleinen Pläne. Sie haben nicht die Magie, das Blut der Menschen zu bewegen, und werden wahrscheinlich selbst nicht verwirklicht. Mache große Pläne; ziele hoch in Hoffnung und Arbeit, im Wissen, dass ein edles, logisches Diagramm, einmal festgehalten, nie sterben wird, sondern noch lange nachdem wir gegangen sind ein lebendiges Ding sein wird, das sich mit wachsender Beharrlichkeit durchsetzt.",
        "Schwierigkeiten bereiten gewöhnliche Menschen oft auf ein außergewöhnliches Schicksal vor.",
        "Wenn du Dinge verändern willst, kannst du nicht jedem gefallen. Wenn du jedem gefällst, machst du nicht genug Fortschritt.",
        "Verhandle nicht mit dir selbst, weis dich an.",
        "Erfolg ist nicht endgültig, Misserfolg ist nicht tödlich: Es ist der Mut weiterzumachen, der zählt.",
        "Wenn es nicht richtig ist, tu es nicht; wenn es nicht wahr ist, sag es nicht.",
        "Sogenannte Vergnügen sind, wenn sie ein gewisses Maß überschreiten, nichts als Strafen.",
        "Wenn du nicht für das opferst, was du willst, wird das, was du willst, zum Opfer.",
        "Dein größter Feind ist dein unkontrollierter Geist.",
        "Lerne zu kämpfen, damit du nie kämpfen musst.",
        "Wenn ein Mensch keinen tiefen Sinn finden kann, lenkt er sich mit Vergnügen ab.",
        "Nichts ist dauerhaft in dieser bösen Welt, nicht einmal unsere Probleme.",
        "Lass sie falsch über dich denken. Es gibt nichts zu beweisen.",
        "Wenn du willst, dass die Gegenwart anders ist als die Vergangenheit, studiere die Vergangenheit.",
        "Wenn du ein glückliches Leben leben willst, binde es an ein Ziel, nicht an Menschen oder Dinge.",
        "Es gibt keine Geheimnisse – es gibt nur die Informationen, die du entdeckt hast, und die Informationen, die du noch nicht entdeckt hast.",
        "Du brauchst Motivation zum Handeln. Du brauchst Informationen, um zu wissen, worauf du handeln sollst. Du brauchst Neugier, um Erkenntnisse zu gewinnen, die diese motivierten Handlungen richtig lenken. Also sei neugierig.",
        "Ein Gewinner ist nur ein Verlierer, der es noch einmal versucht hat.",
        "Wir behandeln den Körper streng, damit er dem Geist nicht ungehorsam wird.",
        "Die Willigen werden vom Schicksal geführt, die Widerwilligen werden geschleift.",
        "Der Mann, der den Tod fürchtet, wird nie etwas tun, das eines lebenden Mannes würdig ist.",
        "Ein Befehlshaber setzt niemals so viel Vertrauen in den Frieden, dass er sich nicht auf einen Krieg vorbereitet.",
        "Hab keine Angst. Du wirst es schaffen, aber es wird sich immer so anfühlen, als ob nicht.",
        "Beständigkeit mag sehr nach langweilig klingen, aber was hast du gedacht, was Großsein ist? Glück?",
        "Halte dein Gesicht immer dem Sonnenschein zugewandt, und die Schatten fallen hinter dich.",
        "Die schwerste Strafe dafür, das Herrschen abzulehnen, ist, von jemandem regiert zu werden, der dir unterlegen ist.",
        "Grabe in dir. In dir ist die Quelle des Guten; und sie ist immer bereit hervorzusprudeln, wenn du nur gräbst.",
        "Du bist, was du tust, nicht was du sagst, dass du tun wirst.",
        "Auf seine eigene Weise irrezugehen ist besser, als auf die Weise eines anderen recht zu haben.",
        "Ein großer Mann ist hart zu sich selbst, ein schwacher Mann ist hart zu anderen.",
        "Sich selbst zu lieben ist der Beginn einer lebenslangen Romanze.",
        "Kümmere dich darum, was andere denken, und du wirst immer ihr Gefangener sein.",
        "Der Mensch wird nicht so sehr von wirklichen Problemen beunruhigt als von seinen eingebildeten Ängsten über wirkliche Probleme.",
        "Der glückliche Mensch ist zufrieden mit seiner gegenwärtigen Situation, egal wie sie aussieht.",
        "Der erste und größte Sieg ist, sich selbst zu besiegen.",
        "Um mich selbst zu kontrollieren, muss ich mich zuerst akzeptieren, indem ich mit meiner Natur gehe und nicht gegen sie.",
        "Lasst die Menschen sehen, lasst sie einen echten Mann kennen, der lebt, wie er leben sollte.",
        "Wer sich selbst nicht gehorchen kann, wird kommandiert.",
        "Wenn du etwas fürchtest, lerne so viel wie möglich darüber. Wissen besiegt die Angst.",
        "Ich dachte immer, es wäre ich gegen die Welt, und dann erkannte ich eines Tages, dass es nur ich gegen mich bin.",
        "Ein Mann ohne Sinn lenkt sich mit Vergnügen ab.",
        "Es ist schwer zu akzeptieren, dass nicht jeder es \"verstehen\" wird – aber deshalb ist es auch nicht für alle anderen. Es ist deine Sache.",
        "Je größer die Schwierigkeit, desto mehr Ruhm liegt in ihrer Überwindung.",
        "Wir erfreuen uns an der Schönheit des Schmetterlings, aber geben selten zu, welche Veränderungen er durchgemacht hat, um diese Schönheit zu erreichen.",
        "Lass mich fallen, wenn ich fallen muss. Der, zu dem ich werde, wird mich auffangen.",
        "Hinter einem Mann, der alles vergibt, steht ein Mann, der das Gewicht seiner eigenen Sünden kennt.",
        "Der Versuch, dem Schmerz zu entkommen, erzeugt mehr Schmerz.",
        "Wahre Entwicklung respektiert Bequemlichkeit nicht.",
        "Soweit wir erkennen können, ist der einzige Zweck der menschlichen Existenz, ein Licht der Bedeutung in der Dunkelheit des bloßen Seins zu entzünden.",
        "Der Tag, an dem du den Samen pflanzt, ist nicht der Tag, an dem du die Frucht isst.",
        "Die Wahrheit ändert sich nicht, weil sie von einer Mehrheit der Menschen geglaubt oder nicht geglaubt wird.",
        "Ein Ritter in glänzender Rüstung hat keinen bewiesenen Wert. Gib mir einen kampferprobten Ritter mit strapazierten Rüstung von Begegnungen mit dem Abschaum der Menschheit.",
        "Das Maß der Intelligenz ist die Fähigkeit zur Veränderung.",
        "Es gibt keine Ernte ohne Hunger.",
        "Es ist der Geist selbst, der den Geist in die Irre führt. Vom Geist sei nicht geistlos.",
        "Du kannst dich nicht in einen Charakter hineinträumen; du musst dir einen schmieden und hämmern.",
        "Vieles wird schiefgehen, bevor alles richtig wird.",
        "Wir leben nur jetzt. Alles andere ist entweder vergangen oder unbekannt.",
        "Du wirst nicht für deinen Zorn bestraft werden – du wirst durch deinen Zorn bestraft werden.",
        "Du lernst nicht schwimmen, indem du über Wasser liest.",
        "Die schwierigsten Entscheidungen erfordern den stärksten Willen.",
        "Vor allem anderen: Belüge dich nicht selbst.",
        "Dein Körper kann fast alles bewältigen; es ist der Geist, den du überzeugen musst.",
        "Das Leben ist ein Ego-Shooter-Genre. Behandle es als solches.",
        "Gute Anführer machen keine Ausreden. Stattdessen finden sie einen Weg, es zu erledigen.",
        "Nur weil es bei dir länger gedauert hat als bei anderen, heißt das nicht, dass du gescheitert bist.",
        "Je mehr du dich selbst kennst, desto weniger brauchst du die Zustimmung anderer.",
        "Sich selbst zu kennen ist der Anfang aller Weisheit.",
        "Es ist nicht die Größe eines Mannes, sondern die Größe seines Herzens, die zählt.",
        "Es ist unwahrscheinlich, dass du ohne Tränen die Stufen wechselst.",
        "Du harkst mit dem Pflug, den du hast.",
    ]
}
