// QuotesLang_es.swift
// Spike AI — Bundled quote translations
import Foundation
enum QuotesLang_es {
    static let quotes: [String] = [
        "Lo que mantengas en tu mente de manera constante es exactamente lo que experimentarás en la vida.",
        "Apuntamos por encima del blanco para dar en el blanco.",
        "Lo peor que puedo ser es igual que todos los demás, detesto eso.",
        "Solo aquellos que se arriesguen a ir demasiado lejos pueden descubrir hasta dónde se puede llegar.",
        "Salta y la red aparecerá.",
        "Un barco en el puerto está seguro, pero no es para eso que se construyen los barcos.",
        "No te preocupes por los fracasos, preocúpate por las oportunidades que pierdes cuando ni siquiera lo intentas.",
        "Quienes se atreven a fracasar estrepitosamente pueden lograr grandes cosas.",
        "La forma de empezar es dejar de hablar y comenzar a hacer.",
        "Podemos encontrar muchas derrotas, pero no debemos dejarnos vencer.",
        "La verdadera medida de un hombre es cómo trata a alguien que no puede hacerle ningún bien.",
        "Tienes que tener cuidado si no sabes adónde vas, porque podrías no llegar.",
        "Debes esperar grandes cosas de ti mismo antes de poder lograrlas.",
        "Nunca dejes que tus decisiones pasadas determinen tu resultado futuro.",
        "Los atajos causan largos retrasos.",
        "Nadie puede darte tus metas. Este es tu camino.",
        "El mundo es lo que piensas de él, así que piénsalo diferente y tu mundo cambiará.",
        "El futuro pertenece a quienes se preparan para él hoy.",
        "No renuncies a lo que más deseas por lo que quieres ahora.",
        "No me digas lo talentoso que eres, dime lo duro que trabajas.",
        "Cómo piensas cuando pierdes determina cuánto tardarás en ganar.",
        "Siempre que una persona decide que ha alcanzado el éxito, el progreso se detiene.",
        "Ningún problema puede resistir el asalto del pensamiento sostenido.",
        "La suerte es cuando una oportunidad se presenta y estás preparado para ella.",
        "El secreto para avanzar es empezar.",
        "El mejor momento para plantar un árbol fue hace 20 años. El segundo mejor momento es ahora.",
        "Es difícil vencer a una persona que nunca se rinde.",
        "Escríbelo. Grábalo. Publícalo. Téjelo, saltéalo. Lo que sea, ¡crea!",
        "Seas lo que seas, sé uno bueno.",
        "La felicidad no es algo ya hecho, proviene de tus propias acciones.",
        "Las personas inteligentes aprenden de todo y de todos.",
        "Imposible es solo una opinión.",
        "Tu pasión está esperando a que tu valentía la alcance.",
        "Las personas que se preguntan si el vaso está medio vacío o lleno no entienden el punto. El vaso es rellenable.",
        "Un día o el día uno; tú decides.",
        "Las cosas pueden llegar a quienes esperan, pero solo las que dejan quienes se esfuerzan.",
        "Todo llega para quien trabaja mientras espera.",
        "Trabaja como si alguien estuviera trabajando 24 horas al día para quitártelo.",
        "Nadie ha hecho una diferencia siendo como todos los demás.",
        "Tendrás malos momentos, pero siempre te despertarán a las cosas buenas a las que no estabas prestando atención.",
        "Sé una versión de primera de ti mismo, no una versión de segunda de alguien más.",
        "Aprende de los errores de otros. No puedes vivir lo suficiente para cometerlos todos tú mismo.",
        "Si estás cansado, entonces hazlo cansado.",
        "Un hombre no está acabado cuando es derrotado, está acabado cuando se rinde.",
        "El mundo se cambia con tu ejemplo, no con tu opinión.",
        "La vida es como andar en bicicleta. Para mantener el equilibrio debes seguir avanzando.",
        "Pensando en la vida: ninguna cantidad de culpa puede cambiar el pasado, ninguna cantidad de ansiedad puede cambiar el futuro.",
        "Una mente negativa nunca te dará una vida positiva.",
        "Todo es difícil antes de ser fácil.",
        "Asume el riesgo o pierde la oportunidad.",
        "Nunca dejes de aprender, porque la vida nunca deja de enseñar.",
        "El hombre que no lee no tiene ventaja sobre el que no sabe leer.",
        "Una persona que nunca cometió un error nunca intentó nada nuevo.",
        "La forma más común en que la gente renuncia a su poder es pensando que no tiene ninguno.",
        "Agradece lo que tienes; terminarás teniendo más. Concéntrate en lo que no tienes y nunca tendrás suficiente.",
        "Lo más difícil es la decisión de actuar, el resto es simplemente tenacidad.",
        "Muchos de los fracasos en la vida son personas que no se dieron cuenta de lo cerca que estaban cuando se rindieron.",
        "No se trata de si te derriban, se trata de si te levantas.",
        "El pesimista ve dificultad en cada oportunidad. El optimista ve oportunidad en cada dificultad.",
        "Nuestra mayor gloria no está en no caer nunca, sino en levantarnos cada vez que caemos.",
        "No te dejes empujar por los miedos en tu mente; déjate guiar por los sueños en tu corazón.",
        "Cuando sabes lo que quieres y lo deseas con suficiente fuerza, encontrarás la manera de conseguirlo.",
        "Empieza haciendo lo necesario, luego haz lo posible, y de repente estarás haciendo lo imposible.",
        "Sin pasión no tienes energía, sin energía no tienes nada.",
        "No tienes que ser grande para empezar, pero tienes que empezar para ser grande.",
        "La fuerza no proviene de la capacidad física, proviene de una voluntad indomable.",
        "Nadie es inútil en este mundo si aligera las cargas de otro.",
        "Pidiendo lo imposible obtenemos lo posible.",
        "Es mejor ser león por un día que oveja toda la vida.",
        "La vida es demasiado importante para tomársela en serio.",
        "El comienzo es la mitad de toda acción.",
        "La paciencia infinita produce resultados inmediatos.",
        "Casi todos los hombres mueren de sus remedios y no de sus enfermedades.",
        "Son capaces, porque creen que son capaces.",
        "La imaginación es más importante que el conocimiento.",
        "Las personas persistentes comienzan su éxito donde otros terminan en fracaso.",
        "No hay caminos claros. Solo trampas, alambres y oscuridad.",
        "Un error demuestra que alguien dejó de hablar lo suficiente para hacer algo.",
        "Lo que vale la pena hacer, vale la pena hacerlo bien.",
        "Más poderoso es quien se tiene a sí mismo en su poder.",
        "Un erudito que aprecia el amor por la comodidad no es digno de ser llamado erudito.",
        "La prosperidad depende más de querer lo que tienes que de tener lo que quieres.",
        "Cada día llega con sus propios regalos, desata las cintas.",
        "El éxito nunca es permanente y el fracaso nunca es definitivo.",
        "Nada dura para siempre, ni siquiera tus problemas.",
        "El trabajo duro no garantiza el éxito, pero mejora sus posibilidades.",
        "La paz no se puede mantener por la fuerza. Solo se puede lograr con comprensión.",
        "Quien no se aventura no tiene suerte.",
        "No digas cuando tenga tiempo libre estudiaré, puede que no tengas tiempo libre.",
        "Quien pierde la fe lo pierde todo.",
        "El pensamiento de uno es su mundo. Lo que una persona piensa es en lo que se convierte.",
        "La aventura no está fuera del hombre, está dentro.",
        "El juego de la vida no consiste tanto en tener una buena mano, sino en jugar bien una mala mano.",
        "Agrio, dulce, amargo, picante; todo debe probarse.",
        "Nunca dejes que la sensación de fracaso pasado derrote tu próximo paso.",
        "A menos que seas ambicioso, no progresas.",
        "El futuro pertenece a quienes se atreven.",
        "Los hechos no dejan de existir porque se ignoren.",
        "Nunca debemos asumir aquello que es incapaz de ser probado.",
        "Una voz fuerte no puede competir con una voz clara, incluso si es un susurro.",
        "Actúa como si esperaras llegar a la zona de anotación.",
        "La felicidad es la flor natural del deber.",
        "\"No\" simplemente significa empezar de nuevo en un nivel más alto.",
        "El entusiasmo mueve el mundo.",
        "Un campeón es alguien que se levanta cuando no puede.",
        "Los obstáculos son el costo de la grandeza.",
        "La pregunta no es quién me va a dejar, es quién me va a detener.",
        "No estaba ahí para competir, estaba ahí para ganar.",
        "Deja de quejarte, empieza a trabajar duro.",
        "De las dificultades crecen los milagros.",
        "No tengo miedo, nací para hacer esto.",
        "Nunca agaches la cabeza. Mantenla en alto. Mira al mundo directamente a los ojos.",
        "Haz lo que tengas que hacer hasta que puedas hacer lo que quieras hacer.",
        "Si caíste ayer, levántate hoy.",
        "Haz de cada día tu obra maestra.",
        "Sangre, sudor y respeto. Los dos primeros los das, el último te lo ganas.",
        "Sé tan bueno que no puedan ignorarte.",
        "Muéstrale al mundo cuánto lucharás por el círculo de ganadores.",
        "Si no diseñas tu propio plan de vida, es probable que caigas en el plan de alguien más. ¿Qué tienen planeado para ti? No mucho.",
        "La única persona en la que estás destinado a convertirte es la persona que decides ser.",
        "No esperes a que el hierro esté caliente para golpear; caliéntalo golpeando.",
        "No puedo creer que Dios nos puso en esta tierra para ser ordinarios.",
        "Quiero que el mundo sea mejor porque yo estuve aquí.",
        "El hábito de la persistencia es el hábito de la victoria.",
        "No tengas miedo de dejar lo bueno para ir por lo grandioso.",
        "Haz tu deber y un poco más, y el futuro se cuidará solo.",
        "La vida tiene una forma de poner a prueba la voluntad de una persona, ya sea porque no pasa nada o porque todo pasa a la vez.",
        "Un hombre sabio siempre puede encontrarse solo. Un hombre débil siempre puede encontrarse en una multitud.",
        "Atreverse es perder el equilibrio momentáneamente. No atreverse es perderse a sí mismo.",
        "El miedo derrota a más personas que cualquier otra cosa en el mundo.",
        "Las palabras más poderosas del universo son las que usas para hablar contigo mismo.",
        "Lo único que le llega a un hombre dormido son sueños.",
        "Si no te conquistas a ti mismo, serás conquistado por ti mismo.",
        "Un héroe es aquel que sabe aguantar un minuto más.",
        "Ve tan lejos como puedas ver, cuando llegues allí podrás ver más lejos.",
        "No descubres tu lugar en el mundo, lo labras.",
        "Los ganadores se enfocan en ganar. Los perdedores se enfocan en los ganadores.",
        "El fracaso nunca me alcanzará si mi determinación de triunfar es lo suficientemente fuerte.",
        "Lo que viene fácil no dura. Lo que dura no viene fácil.",
        "Para evitar la crítica: no digas nada, no hagas nada, no seas nada.",
        "El hombre que hace más de lo que le pagan pronto recibirá más de lo que hace.",
        "El genio comienza grandes obras, solo el trabajo las termina.",
        "Incluso si estás en el camino correcto, te atropellarán si te quedas sentado.",
        "Si las cosas no están fallando, no estás innovando lo suficiente.",
        "Obtienes lo mejor de los demás cuando das lo mejor de ti mismo.",
        "El liderazgo es una acción, no una posición.",
        "Nuestro trabajo es la presentación de nuestras capacidades.",
        "Todos mis problemas se inclinan ante mi terquedad.",
        "Usa tu fracaso como una insignia de honor.",
        "Estamos limitados no por nuestras habilidades, sino por nuestra visión.",
        "Si te cansas, aprende a descansar, no a renunciar.",
        "Caer es un accidente, quedarse abajo es una elección.",
        "No te atrevas a rendirte en esta vida. No esta noche. No mañana. Nunca.",
        "Nunca te dejes abatir por personas o por eventos.",
        "Algunas personas sueñan con el éxito mientras otras se despiertan y trabajan duro por él.",
        "La confianza viene de la experiencia. Las experiencias vienen de intentar, fracasar e intentar de nuevo, esta vez mejor.",
        "El tiempo que lleva a la maestría depende de la intensidad de nuestro enfoque.",
        "El éxito solo llega a quienes se atreven a intentarlo.",
        "Una clave importante para el éxito es la autoconfianza. Una clave importante para la autoconfianza es la preparación.",
        "La duda mata más sueños que el fracaso.",
        "La victoria siempre es posible para la persona que se niega a dejar de luchar.",
        "Nunca cambiarás tu vida hasta que cambies algo que haces a diario.",
        "Para tener éxito, tu enfoque tiene que ser tan intenso que otros piensen que estás loco.",
        "Los obstáculos son esas cosas aterradoras que ves cuando apartas los ojos de tu meta.",
        "Encontrar una oportunidad es cuestión de creer que está ahí.",
        "Establecer metas es el primer paso para convertir lo invisible en visible.",
        "Si no arriesgas nada, lo arriesgas todo.",
        "Si no puedes cambiar tu situación, cambia tu mentalidad.",
        "No importa lo difícil que haya sido el pasado, siempre puedes empezar de nuevo.",
        "Si no te atreves a nada, cuando el día termine, nada será todo lo que habrás ganado.",
        "Muy a menudo se necesita más un cambio de uno mismo que un cambio de escenario.",
        "El miedo es la mayor discapacidad de todas y te paralizará.",
        "Lo peligroso es no evolucionar.",
        "De una forma u otra encontraré un camino o lo crearé.",
        "La única forma de callar a todo el mundo es ganar.",
        "Nunca dejes que lo suficientemente bueno sea suficientemente bueno.",
        "A la larga solo le damos a lo que apuntamos.",
        "La mejora continua es mejor que la perfección retrasada.",
        "Si lo ves en tu mente, lo sostendrás en tu mano.",
        "Hoy haré lo que otros no harán, para que mañana pueda hacer lo que otros no pueden.",
        "La excelencia es un arte ganado por el entrenamiento y la habituación.",
        "El próximo año va a pasar ya sea que estés haciendo algo con tu vida o no.",
        "No te detengas cuando estés cansado, detente cuando hayas terminado.",
        "Estás a solo un entrenamiento de un buen estado de ánimo.",
        "Haz lo correcto, no lo fácil ni lo popular.",
        "Nada grandioso jamás vino fácilmente.",
        "Sin lucha no puede haber progreso.",
        "Las personas exitosas hacen mejores preguntas y como resultado obtienen mejores respuestas.",
        "No tengo talentos especiales, solo soy apasionadamente curioso.",
        "La mejor lección que he aprendido en la vida vino del peor sentimiento que he sentido.",
        "Los desafíos son lo que hacen la vida interesante. Superarlos es lo que le da sentido.",
        "Aprende a ser feliz con el enfoque interminable de intentar, fracasar y aprender.",
        "Si cierras la puerta a todos los errores, la verdad quedará fuera.",
        "Olvida el error, recuerda la lección.",
        "Si solo puedes hacer lo que ya puedes hacer, nunca serás más de lo que eres ahora.",
        "¿Quién es sabio? Aquel que aprende de todos.",
        "Solo yo puedo cambiar mi vida, nadie puede hacerlo por mí.",
        "La perseverancia es fracasar 19 veces y tener éxito la vigésima.",
        "Atribuyo mi éxito a esto: nunca di ni acepté ninguna excusa.",
        "No soy producto de mis circunstancias. Soy producto de mis decisiones.",
        "Nuestros actos nos determinan tanto como nosotros determinamos nuestros actos.",
        "Solo los extremadamente ignorantes o los extremadamente inteligentes pueden resistir el cambio.",
        "El hombre que confía en sí mismo gana la confianza de los demás.",
        "Lo que buscas te está buscando.",
        "No te preocupes por el fracaso. Solo tienes que acertar una vez.",
        "La seguridad es mayormente una superstición. La vida es una aventura atrevida o no es nada.",
        "Nos convertimos en lo que pensamos la mayor parte del tiempo, y ese es el secreto más extraño.",
        "La forma de empezar es dejar de hablar y comenzar a hacer.",
        "Haz de cada día tu obra maestra.",
        "No importa cuántos errores cometas o lo lento que progreses, sigues estando muy por delante de todos los que no lo intentan.",
        "Es nuestra actitud al comienzo de una tarea difícil la que, más que cualquier otra cosa, afectará su resultado exitoso.",
        "La única seguridad real que un hombre tendrá en este mundo es una reserva de conocimiento, experiencia y habilidad.",
        "Lo que haces hoy puede cambiar todos los mañanas de tu vida.",
        "Tu vida no mejora por casualidad, mejora por cambio.",
        "Un sueño no se convierte en realidad por arte de magia, requiere sudor, determinación y trabajo duro.",
        "El conocimiento es saber que un tomate es una fruta. La sabiduría es no ponerlo en una ensalada de frutas.",
        "No importa cuál sea la situación, recuérdate: \"Tengo una opción\".",
        "Domina tu mente o ella te dominará a ti.",
        "Algunos triunfan porque están destinados a ello, pero la mayoría triunfa porque están decididos a hacerlo.",
        "Las grandes oportunidades no se ven con los ojos, se ven con la mente.",
        "Quien no tiene el valor de arriesgarse no logrará nada en la vida.",
        "Saber no es suficiente, debemos aplicar. Querer no es suficiente, debemos hacer.",
        "La ambición es el camino hacia el éxito, la persistencia es el vehículo en el que llegas.",
        "La clave de la vida es aceptar desafíos. Cuando alguien deja de hacerlo, está muerto.",
        "El compromiso es lo que transforma una promesa en realidad.",
        "La autoconfianza es la memoria del éxito.",
        "Sin autoconfianza somos como bebés en una cuna.",
        "Atrévete a soñar, pero más importante aún, atrévete a poner acción detrás de tus sueños.",
        "La honestidad es el primer capítulo en el libro de la sabiduría.",
        "La excelencia es un proceso continuo y no un accidente.",
        "La esperanza es poder ver que hay luz a pesar de toda la oscuridad.",
        "Debemos aceptar una decepción finita, pero nunca perder la esperanza infinita.",
        "El verdadero signo de la inteligencia no es el conocimiento, sino la imaginación.",
        "Hazte adicto a la mejora constante e interminable de ti mismo.",
        "El genio es un uno por ciento de inspiración y un noventa y nueve por ciento de transpiración.",
        "No puedes esperar la inspiración, tienes que ir tras ella con un garrote.",
        "Ten paciencia. Todas las cosas son difíciles antes de ser fáciles.",
        "La persona que dice que no se puede hacer no debería interrumpir a la persona que lo está haciendo.",
        "La perseverancia es el trabajo duro que haces después de cansarte del trabajo duro que ya hiciste.",
        "Un hombre sabio puede aprender más de una pregunta tonta que un tonto de una respuesta sabia.",
        "Mediante la autodisciplina y el autocontrol constantes puedes desarrollar grandeza de carácter.",
        "El autocontrol emocional es resultado del trabajo duro, no una habilidad innata.",
        "Aprender a aprender es la habilidad más importante de la vida.",
        "No dejes que lo que no puedes hacer te impida hacer lo que sí puedes.",
        "Siempre pasas por el fracaso camino al éxito.",
        "Nadie es perfecto, por eso los lápices tienen borrador.",
        "Nunca dejes que las probabilidades te impidan hacer lo que sabes en tu corazón que estabas destinado a hacer.",
        "Si realmente observas de cerca, la mayoría de los éxitos de la noche a la mañana tardaron mucho tiempo.",
        "Todo es posible. Todo puede ser.",
        "Nada es particularmente difícil si lo divides en tareas pequeñas.",
        "El secreto del éxito es hacer las cosas comunes extraordinariamente bien.",
        "Actúa como si lo que haces marca una diferencia, porque la marca.",
        "Lo que obtienes al alcanzar tus metas no es tan importante como en lo que te conviertes al alcanzarlas.",
        "La vida es como andar en bicicleta; para mantener el equilibrio debes seguir avanzando.",
        "Limita tus \"siempre\" y tus \"nunca\".",
        "Nunca eres demasiado viejo para establecer otra meta o soñar un nuevo sueño.",
        "No encuentras la vida feliz, la creas.",
        "La mala noticia es que el tiempo vuela. La buena noticia es que tú eres el piloto.",
        "Mantén tu rostro siempre hacia el sol y las sombras caerán detrás de ti.",
        "La diferencia entre lo imposible y lo posible radica en la determinación de un hombre.",
        "Las medallas de oro no están realmente hechas de oro. Están hechas de sudor, determinación y una aleación difícil de encontrar llamada agallas.",
        "No subestimes la determinación de un hombre tranquilo.",
        "No me digas en qué crees. Observaré cómo te comportas y sacaré mis propias conclusiones.",
        "Simplemente odio perder y eso te da una determinación extra para trabajar más duro.",
        "La determinación de ganar es la mejor parte de ganar.",
        "Puedes tener todo el talento del mundo, pero sin determinación no llegarás muy lejos.",
        "La victoria es hija de la preparación y la determinación.",
        "El joven conoce las reglas, pero el viejo conoce las excepciones.",
        "El pesimista se queja del viento, el optimista espera que cambie, el realista ajusta las velas.",
        "El conocimiento no tiene valor a menos que lo pongas en práctica.",
        "Prefiero arrepentirme de las cosas que he hecho que arrepentirme de las que no he hecho.",
        "Se necesita sabiduría para entender la sabiduría. La música no es nada si la audiencia es sorda.",
        "El mayor peligro para la mayoría de nosotros no es que nuestro objetivo sea demasiado alto y no lo alcancemos, sino que sea demasiado bajo y lo logremos.",
        "En cada paseo con la naturaleza uno recibe mucho más de lo que busca.",
        "No seguiré donde el camino pueda llevar, iré donde no hay camino y dejaré un rastro.",
        "El poderoso roble de hoy es solo la nuez de ayer que mantuvo su posición.",
        "Ser completamente honesto con uno mismo es un buen ejercicio.",
        "No podemos convertirnos en lo que necesitamos ser si seguimos siendo lo que somos.",
        "Fija tu rumbo por las estrellas, no por las luces de cada barco que pasa.",
        "Si no sabes adónde vas, cualquier camino te llevará allí.",
        "Siempre tendrás dos opciones: tu compromiso o tu miedo.",
        "Benditos sean los que dan sin recordar y reciben sin olvidar.",
        "Lo que sucede no es tan importante como cómo reaccionas a lo que sucede.",
        "Empieza con lo que es correcto en lugar de lo que es aceptable.",
        "El hombre superior se culpa a sí mismo. El hombre inferior culpa a los demás.",
        "La acción más pequeña es mejor que la mayor intención.",
        "El mayor obstáculo para el descubrimiento no es la ignorancia, es la ilusión de conocimiento.",
        "Cuidado con el conocimiento falso, es más peligroso que la ignorancia.",
        "La mejor manera de predecir el futuro es inventarlo.",
        "Ganar sin riesgo es triunfar sin gloria.",
        "Nuestro carácter es lo que hacemos cuando creemos que nadie nos está mirando.",
        "Todo lo que nos irrita de otros puede llevarnos a comprendernos a nosotros mismos.",
        "El arte de ser sabio es el arte de saber qué pasar por alto.",
        "Dime y lo olvido. Enséñame y lo recuerdo. Involúcrame y aprendo.",
        "Tienes cerebro en tu cabeza. Tienes pies en tus zapatos. Puedes dirigirte en cualquier dirección que elijas.",
        "En tres palabras puedo resumir todo lo que he aprendido sobre la vida: la vida continúa.",
        "La vida es probar cosas para ver si funcionan.",
        "El éxito generalmente llega a quienes están demasiado ocupados para buscarlo.",
        "No he fracasado, simplemente he encontrado 10,000 maneras que no funcionan.",
        "Fracasé mi camino hacia el éxito.",
        "Si no te programas a ti mismo, la vida te programará.",
        "No tengo tiempo para sentir lástima por mí mismo. No tengo tiempo para quejarme. Voy a seguir adelante.",
        "Si no estás dispuesto a arriesgar lo habitual, tendrás que conformarte con lo ordinario.",
        "El éxito se ha definido como la capacidad de ir de fracaso en fracaso sin perder el entusiasmo.",
        "Todos nuestros sueños pueden hacerse realidad si tenemos el coraje de perseguirlos.",
        "Las oportunidades no suceden, tú las creas.",
        "Nunca soñé con el éxito, trabajé por él.",
        "No dejes que lo que no puedes hacer interfiera con lo que sí puedes hacer.",
        "Hoy es el único día, ayer se fue.",
        "Las cosas funcionan mejor para quienes sacan lo mejor de cómo funcionan las cosas.",
        "Si estás pasando por el infierno, sigue avanzando.",
        "Solo ves las glorias públicas, nunca los sacrificios privados para alcanzarlas.",
        "Si no valoras tu tiempo, los demás tampoco lo harán.",
        "Nadie puede hacerte sentir inferior sin tu consentimiento.",
        "Un hombre exitoso es aquel que puede construir una base firme con los ladrillos que otros le han lanzado.",
        "Lo que nos parece una prueba amarga a menudo es una bendición disfrazada.",
        "Nada en el mundo es más común que personas sin éxito con talento.",
        "No intentes convertirte en una persona de éxito, sino en una persona de valor.",
        "Si no puedes explicarlo simplemente, no lo entiendes lo suficientemente bien.",
        "Nunca fracasas hasta que dejas de intentarlo.",
        "El conocimiento es saber lo que puedes hacer. La sabiduría es saber cuándo no hacerlo.",
        "La vida no se trata de encontrarte a ti mismo. La vida se trata de crearte a ti mismo.",
        "El problema no es el problema, el problema es tu actitud sobre el problema.",
        "Ninguna obra maestra fue creada jamás por un artista perezoso.",
        "El camino al éxito y el camino al fracaso son casi exactamente iguales.",
        "No es lo que miras lo que importa, es lo que ves.",
        "El valor es resistencia al miedo, dominio del miedo, no ausencia de miedo.",
        "Encuentro que cuanto más duro trabajo, más suerte parezco tener.",
        "El resplandor de un pensamiento cálido vale más para mí que el dinero.",
        "Todo progreso ocurre fuera de la zona de confort.",
        "El pensamiento debería convertirse en tu activo principal sin importar los altibajos que encuentres en la vida.",
        "El éxito es la suma de pequeños esfuerzos repetidos día tras día.",
        "El guerrero exitoso es el hombre promedio con un enfoque de láser.",
        "El éxito no consiste en nunca cometer errores, sino en no cometer el mismo una segunda vez.",
        "No dejes que el miedo a perder sea mayor que la emoción de ganar.",
        "El primer paso es cuando te niegas a ser cautivo de tu entorno.",
        "No hay embotellamiento en el kilómetro extra.",
        "Siempre que te encuentres del lado de la mayoría, es hora de hacer una pausa y reflexionar.",
        "El éxito es gustarte a ti mismo, gustar lo que haces y gustar cómo lo haces.",
        "Una meta no siempre está destinada a ser alcanzada, a menudo sirve simplemente como algo a lo que apuntar.",
        "Es mejor fracasar en la originalidad que tener éxito en la imitación.",
        "La motivación es lo que te hace empezar, el hábito es lo que te mantiene en marcha.",
        "Tienes que levantarte cada mañana con determinación si quieres irte a la cama con satisfacción.",
        "Debes esperar grandes cosas de ti mismo antes de poder lograrlas.",
        "Las dificultades reales pueden ser superadas, solo las imaginarias son invencibles.",
        "La gente rara vez tiene éxito a menos que se divierta en lo que hace.",
        "Es durante nuestros momentos más oscuros cuando debemos enfocarnos para ver la luz.",
        "El fracaso es el condimento que le da sabor al éxito.",
        "Las mentes son domadas y sometidas por la desgracia, pero las grandes mentes se elevan por encima de ella.",
        "Puede que tengas que librar una batalla más de una vez para ganarla.",
        "¿Qué harías si no tuvieras miedo?",
        "Las cosas buenas llegan a quienes esperan, pero las mejores llegan a quienes salen a buscarlas.",
        "Siempre haz un esfuerzo total, incluso cuando las probabilidades estén en tu contra.",
        "No esperes a que tus sentimientos cambien para actuar, actúa y tus sentimientos cambiarán.",
        "La acción no siempre trae felicidad, pero no hay felicidad sin acción.",
        "La perfección es aburrida, mejorar es donde está toda la diversión.",
        "Es difícil vencer a una persona que nunca se rinde.",
        "La diferencia entre un obstáculo y un escalón es lo alto que levantas el pie.",
        "Nunca te rindas porque ese es justo el lugar y momento en que la marea cambiará.",
        "A veces no obtener lo que quieres es un maravilloso golpe de suerte.",
        "No puedo cambiar la dirección del viento, pero puedo ajustar mis velas para siempre llegar a mi destino.",
        "Sigue adelante. No te detengas, no te demores en tu viaje, sino esfuérzate por la meta establecida ante ti.",
        "Si genuinamente quieres algo, no lo esperes, enséñate a ser impaciente.",
        "A veces ganas, a veces aprendes.",
        "Dos tipos de personas en este mundo: las que quieren hacer las cosas y las que no quieren cometer errores.",
        "Asegúrate de que tu peor enemigo no viva entre tus propias dos orejas.",
        "Recuerda siempre que eres absolutamente único, igual que todos los demás.",
        "Si tienes todo bajo control, no te estás moviendo lo suficientemente rápido.",
        "Una forma de mantener el impulso es tener metas constantemente mayores.",
        "No tienes que ver toda la escalera, solo da el primer paso.",
        "Lo que nos parece una prueba amarga a menudo es una bendición disfrazada.",
        "Dos opciones respecto al compromiso: o estás dentro o estás fuera, no existe tal cosa como vivir a medias.",
        "Cuando deseas algo, todo el universo conspira para ayudarte a lograrlo.",
        "La felicidad no es algo ya hecho, proviene de tus propias acciones.",
        "Seas lo que seas, sé uno bueno.",
        "El dolor es inevitable, el sufrimiento es opcional.",
        "El talento da en un blanco que nadie más puede alcanzar; el genio da en un blanco que nadie más puede ver.",
        "La mente es su propio lugar y en sí misma puede hacer un cielo del infierno o un infierno del cielo.",
        "Odiaba entrenar, pero me dije \"no te rindas\": sufre ahora y vive el resto de tu vida como campeón.",
        "No son las montañas que tienes que escalar las que te agotan, es la piedra en tu zapato.",
        "Lo que pensamos, nos convertimos.",
        "Alguien está sentado a la sombra hoy porque alguien plantó un árbol hace mucho tiempo.",
        "Un solo rayo de sol es suficiente para ahuyentar muchas sombras.",
        "Para la mente que está quieta, todo el universo se rinde.",
        "Con autodisciplina, casi todo es posible.",
        "La mejor salida es siempre a través.",
        "Tu gran oportunidad puede estar justo donde estás ahora.",
        "Nada vale más que este día.",
        "El único viaje es el que está dentro.",
        "Las circunstancias no determinan adónde puedes ir, simplemente determinan dónde empiezas.",
        "La creencia crea el hecho real.",
        "Lo que hace hermoso al desierto es que en algún lugar esconde un pozo.",
        "Si las puertas de la percepción fueran limpiadas, todo aparecería al hombre tal como es: infinito.",
        "Cambia tus pensamientos y cambiarás tu mundo.",
        "El pájaro es impulsado por su propia vida y por su motivación.",
        "Da luz y las personas encontrarán el camino.",
        "La mejor preparación para mañana es hacer lo mejor hoy.",
        "Las ideas moldean el curso de la historia.",
        "No en un solo hilo están ensartadas todas las joyas de la vida.",
        "Lo que logramos internamente cambiará la realidad exterior.",
        "Tu propia resolución hacia el éxito es más importante que cualquier otra cosa.",
        "Sabes que estás en el camino del éxito si harías tu trabajo sin que te pagaran.",
        "Te conviertes en lo que crees.",
        "Si quieres lograr la excelencia, puedes conseguirlo hoy. A partir de este segundo, deja de hacer un trabajo menos que excelente.",
        "Si no estás dispuesto a arriesgar lo habitual, tendrás que conformarte con lo ordinario.",
        "Antes que nada, la preparación es la clave del éxito.",
        "He aprendido a lo largo de los años que cuando uno tiene la mente decidida, el miedo disminuye.",
        "La vida está hecha de muchas despedidas soldadas entre sí.",
        "Ganar no lo es todo, pero querer ganar sí lo es.",
        "Puedes sentirte decepcionado si fracasas, pero estás condenado si no lo intentas.",
        "Los errores son un hecho de la vida, lo que cuenta es la respuesta al error.",
        "Si no te gusta el camino que recorres, empieza a pavimentar uno nuevo.",
        "Las acciones hablan más que las palabras, y eso no es más cierto que con tus hijos.",
        "Un diamante es un trozo de carbón que lo hizo bien bajo presión.",
        "Los caminos difíciles a menudo conducen a destinos hermosos.",
        "A veces nunca sabrás el valor de un momento hasta que se convierte en recuerdo.",
        "Nada puede apagar la luz que brilla desde dentro.",
        "Para tener éxito en la vida necesitas tres cosas: un hueso de la suerte, una columna vertebral y un hueso de la risa.",
        "Los que no creen en la magia nunca la encontrarán.",
        "Decidí que no puedo pagarle a alguien para rebobinar el tiempo, así que mejor lo supero.",
        "Todo tiene un costo, ¿cuánto estás dispuesto a pagar por ello?",
        "He crecido más no por las victorias, sino por los reveses.",
        "Tengo la suerte de que cualquier miedo que tenga dentro de mí, mi deseo de ganar siempre es más fuerte.",
        "Tienes que creer en ti mismo cuando nadie más lo hace.",
        "No tengas miedo al fracaso, este es el camino para triunfar.",
        "Me gusta la crítica, te hace fuerte.",
        "Sé que siempre quiero hacer lo mejor que pueda.",
        "Todos los que he conocido que son exitosos son adictos al trabajo.",
        "Nunca he competido con nadie más que conmigo mismo.",
        "Creer en uno mismo y saber quién eres, esa es la base de todo lo grande.",
        "Tengo miedo de no intentarlo.",
        "La forma de redimir tu pasado no es huir de él, sino tratar de entenderlo y usarlo como base para crecer.",
        "Jugar a lo seguro no te va a dar nada en este mundo.",
        "Un gran truco es un gran truco, pero en alguien sin talento simplemente no funciona. Todo se reduce al talento.",
        "O evolucionas o desapareces.",
        "La semilla debe crecer, sin importar que esté plantada en piedra.",
        "No importa lo difícil que se ponga, saca el pecho, mantén la cabeza en alto y manéjalo.",
        "Siempre da lo mejor de ti, no dejes que la presión te haga entrar en pánico.",
        "Nunca sabes cómo o cuándo tendrás un impacto, o lo importante que tu ejemplo puede ser para alguien más.",
        "Haz lo que tengas que hacer, para hacer lo que quieras hacer.",
        "No aspires a ganarte la vida, aspira a hacer una diferencia.",
        "Tienes que ser quien eres en este mundo, sin importar qué.",
        "Si tienes un enemigo, entonces aprende y conoce a tu enemigo, no solo te enojes con él o ella.",
        "Me esfuerzo por ser como las personas más grandes que han existido.",
        "Donde yo destaco es en una ética de trabajo ridícula y enfermiza. Mientras el otro duerme, yo estoy trabajando.",
        "La vida se vive al límite.",
        "Ser realista es el camino más común hacia la mediocridad.",
        "El primer paso es decirte a ti mismo que puedes.",
        "El mundo no puede decirte quién eres, tú tienes que descubrir quién eres y ser eso para bien o para mal.",
        "Vas a tener que reconocer tus fracasos. Vas a tener que aceptarlos y descubrir cómo superarlos.",
        "Mi padre me dijo: Pon tu precio desde el principio. Si alguna vez se vuelve más caro de lo que nombraste, sal de ahí.",
        "¿Creerías en lo que crees si fueras el único que lo creyera?",
        "No me importa lo que piense la gente, porque la gente no piensa.",
        "Nunca fui realmente bueno en nada excepto en la capacidad de aprender.",
        "La mejor sensación del mundo es ver los beneficios y recompensas del trabajo duro.",
        "Mis metas son tan altas que no tengo tiempo para relajarme de ninguna manera.",
        "La vida es muy corta para preocuparte por lo que otros dicen de ti.",
        "Detrás de cada persona exitosa hay una manada de envidiosos.",
        "Puedes hacer algo de tu vida, solo depende de tu impulso.",
        "¿Tienes enemigos? Bien, eso significa que realmente defendiste algo.",
        "Todo éxito comienza con la autodisciplina, empieza contigo.",
        "Con impulso y un poco de talento puedes mover montañas.",
        "El fracaso no es una opción, es solo un paso.",
        "El éxito no es de la noche a la mañana, es cuando cada día mejoras un poco más que el día anterior; todo se acumula.",
        "Cuando la vida te pone en situaciones difíciles no digas \"por qué a mí\", simplemente di \"inténtalo conmigo\".",
        "El éxito en cualquier cosa siempre se reduce a esto: enfoque y esfuerzo. Y controlamos ambos.",
        "Una vez escuché a un hombre sabio decir que no hay hombres perfectos, solo intenciones perfectas.",
        "Muy a menudo dejas de caminar porque dices \"estoy cansado de subir esta colina, nunca voy a llegar a la cima\" y estás a solo dos pasos de la cima.",
        "Desafíate a ti mismo, es el único camino que lleva al crecimiento.",
        "No puedes atribuirte el talento, solo puedes atribuirte el usarlo.",
        "La mejor manera de garantizar una derrota es rendirse.",
        "Podía observar cómo sucedía o ser parte de ello.",
        "Cuando algo es lo suficientemente importante, lo haces, incluso si las probabilidades no están a tu favor.",
        "Si te levantas por la mañana y piensas que el futuro va a ser mejor, es un día brillante; de lo contrario, no lo es.",
        "Está bien tener todos los huevos en una canasta, siempre y cuando controles lo que pasa con esa canasta.",
        "Si solo haces cosas donde sabes la respuesta de antemano, tu empresa desaparece.",
        "Tienes que estar dispuesto a ser malinterpretado si vas a innovar.",
        "No hay mal momento para innovar.",
        "Crear oportunidades significa mirar donde otros no miran.",
        "El capital de sudor es el capital más valioso que existe.",
        "Vivimos en una sociedad donde, casi siempre, el trabajo duro es recompensado.",
        "El universo no tiene ninguna obligación de tener sentido para ti.",
        "No hay mayor educación que la autodirigida.",
        "Nadie es tonto si es curioso.",
        "No conozco ningún momento en la historia humana en que la ignorancia fuera mejor que el conocimiento.",
        "Entrénate para no tomarte nada de manera personal.",
        "Un hombre puede hacer de sí mismo lo que quiera si realmente lo cree, pero debe estar listo para el trabajo duro y muchos desengaños.",
        "Lo que cada uno de nosotros debe comprender es que nuestra intención siempre se manifiesta.",
        "No podemos ignorar lo que realmente queremos crear.",
        "Solo tú y solo tú puedes cambiar tu situación.",
        "Agradece los tiempos difíciles, porque te han formado.",
        "Para unirte al 1% más alto tienes que hacer lo que el 99% no hará.",
        "Yo creo mi propio camino, era recto y estrecho. Lo veía así: o estabas en mi camino o fuera de él.",
        "Todos tenemos dudas sobre nosotros mismos. No lo niegas, pero tampoco capitulas ante ello. Lo aceptas.",
        "Muchos líderes fracasan porque no tienen la valentía de tocar ese nervio o esa cuerda.",
        "El momento en que te rindes es el momento en que dejas que alguien más gane.",
        "Si tienes miedo de fracasar, probablemente vas a fracasar.",
        "Me di cuenta de que la intimidación realmente no existía, si estás en el estado mental correcto.",
        "Este es el momento en que acepto que los tiempos más desafiantes siempre estarán detrás y delante de mí.",
        "Nadie sabe que van a ser campeones; tienes que trabajar para llegar ahí.",
        "Mi creencia es más fuerte que tu duda.",
        "El éxito significa estar satisfecho con lo que haces todos los días. Es estar orgulloso de la mejor persona en la que te estás convirtiendo.",
        "Si quieres tener éxito, tienes que estar dispuesto a usar cada conexión que tengas.",
        "El talento nunca es suficiente. Con pocas excepciones, los mejores jugadores son los que más trabajan.",
        "No te rindas, sé amigo de personas que te ayuden a trabajar duro.",
        "Simplemente celebra la vida que tuviste, no la vida que podrías haber tenido.",
        "Crecí pobre, pero no tuve sueños pobres.",
        "Eres el único que puede marcar la diferencia. Sea cual sea tu sueño, ve por él.",
        "La vida no se detiene porque algo te sucede.",
        "En la vida, ganar y perder sucederán, lo que nunca es aceptable es rendirse.",
        "¿Saben cuántas veces me han rechazado en mi vida? ¿Cuántas veces me dijeron que no podía lograr algo?",
        "Muchas veces encuentro que las personas bendecidas con más talento nunca desarrollan esa actitud. Y las que no son bendecidas de esa manera son las más competitivas y tienen el corazón más grande.",
        "Pensé que nunca tendría oportunidad de jugar, hasta que un día la tuve, porque estaba preparado y la oportunidad se presentó.",
        "Simplemente amo la competencia y amo intentar mejorar.",
        "Muy a menudo en la vida sucede algo y culpamos a otros por no ser felices o estar satisfechos o realizados.",
        "Tu vida será lo que hagas de ella.",
        "No me voy a molestar porque alguien dijo algo malo de mí.",
        "No puedes quedarte en la banca de la vida.",
        "Mi mensaje es simple: toma el control de tu vida.",
        "Cuando eres uno de los líderes del equipo, no hay días libres.",
        "No dependas de otros. Tendrás gran apoyo de mucha gente, aun así. Pero nadie te va a dar nada en bandeja.",
        "Las cosas no se corrigen solas; tienes que salir a trabajar duro para corregirlas.",
        "Si no juegas para ganar, no juegues en absoluto.",
        "Si no crees en ti mismo, ¿por qué va a creer alguien más en ti?",
        "A veces en la vida los mayores desafíos terminan siendo las mejores cosas que te suceden.",
        "Simplemente amo trabajar duro.",
        "Los verdaderos competidores son los que siempre juegan para ganar.",
        "No persigas el dinero, persigue el sueño.",
        "Si quieres volar tienes que soltar las cosas que te pesan.",
        "No quiero que sueñes, quiero que hagas.",
        "Cualquiera que quiera ser alguien va a trabajar tan duro como pueda para cumplir ese sueño.",
        "Nunca he intentado ocultar que mi intención es convertirme en el mejor.",
        "Si no crees que eres el mejor, nunca alcanzarás todo lo que eres capaz de lograr.",
        "Hoy hay oportunidades que nadie sabe si volverán en el futuro.",
        "El talento sin trabajo duro no es nada.",
        "No me importa que la gente me odie, porque eso me empuja.",
        "El talento no lo es todo. Puedes tenerlo desde la cuna, pero es necesario aprender el oficio para ser el mejor.",
        "Siento una necesidad infinita de aprender, mejorar, evolucionar, para sentirme satisfecho conmigo mismo.",
        "Tu amor me hace fuerte. Tu odio me hace imparable.",
        "Puedes superar cualquier cosa si y solo si amas algo lo suficiente.",
        "Soy exitoso porque hice sacrificios por el éxito.",
        "Mi ambición es siempre mejorar cada vez más.",
        "Empiezo temprano y me quedo hasta tarde. Día tras día, año tras año, me tomó 17 años y 114 días convertirme en un éxito de la noche a la mañana.",
        "La persona que me impedía ser feliz era yo.",
        "El simple acto de prestar atención puede llevarte muy lejos.",
        "No confundas la verdad con la opinión de las masas. Estas casi nunca son ni remotamente similares.",
        "Hay una diferencia entre conocer el camino y recorrer el camino.",
        "No tengo tiempo para quedarme despierta toda la noche preocupándome por lo que alguien que no me ama tenga que decir sobre mí.",
        "No puedes dudar de quién eres.",
        "Siempre hay cosas en las que trabajar, nunca llegas ahí del todo.",
        "Quiero ser lo que siempre he querido ser: dominante.",
        "Solo intento ser lo mejor que puedo y espero que sea lo mejor de todos los tiempos.",
        "No quiero ser tan bueno como lo fui una vez, quiero ser mejor.",
        "Mi mente es mi mayor activo. Espero ganar cada torneo en el que juego.",
        "Los tipos que realmente controlan sus emociones son los que van a ganar.",
        "No importa lo bueno que seas, siempre puedes ser mejor, y esa es la parte emocionante.",
        "Para poder ayudar a los demás, primero tienes que aprender a ayudarte a ti mismo.",
        "Nada que valga la pena llega a uno, excepto como resultado del trabajo duro.",
        "No permitiré que ningún hombre empequeñezca mi alma haciéndome odiarlo.",
        "No puedes mantener a un hombre abajo sin quedarte abajo con él.",
        "El carácter, no las circunstancias, hace al hombre.",
        "Hay dos formas de ejercer la fuerza de uno: empujar hacia abajo o tirar hacia arriba.",
        "He fracasado mucho más de lo que he tenido éxito.",
        "Hoy hago lo que la gente no hará, para poder lograr mañana lo que la gente no puede.",
        "Incluso si pierdes, no pierdas la lección.",
        "Lo más fácil de vender es la verdad.",
        "No esperes el momento perfecto, esperarás para siempre. Siempre aprovecha el tiempo que tienes y hazlo perfecto.",
        "Solo puedes hacer unas pocas cosas de manera grandiosa, y deberías dejar de lado todo lo demás.",
        "La vida es frágil. No tenemos garantizado un mañana, así que da todo lo que tienes.",
        "No tengo miedo de hacer el ridículo.",
        "El respeto me motiva, no el éxito.",
        "Cuando pasas la cima, es cuando empiezas a tomar velocidad.",
        "La excelencia no es un acto, es un hábito.",
        "No puedes sacar una \"A\" si tienes miedo de sacar una \"F\".",
        "Cometes tus errores para aprender cómo llegar a lo bueno.",
        "Un héroe es alguien que voluntariamente camina hacia lo desconocido.",
        "Hay millones de sobrevivientes ahí fuera. Haz que sea un millón y uno.",
        "Nunca te rindas, porque nunca sabes lo que la marea traerá al día siguiente.",
        "Si no fuera difícil, todos lo harían. Es la dificultad lo que lo hace grandioso.",
        "Si solo juegas a lo seguro con tus elecciones, no creces.",
        "Me gusta hacer algo que me da miedo.",
        "El proceso es la parte más hermosa.",
        "Es fácil engañar al ojo, pero es difícil engañar al corazón.",
        "Nunca te eleves demasiado, nunca te hundas demasiado. Tómalo día a día y solo sigue aprendiendo.",
        "El esfuerzo nunca será cuestionado.",
        "No esperes que alguien te dé una oportunidad: crea una para ti mismo.",
        "Cuando la gente me decía que nunca lo lograría, escuché a la única persona que dijo que sí podía: yo.",
        "Hay una razón por la que lo llaman perseguir tus sueños y no caminar tras ellos.",
        "Para tener lo que realmente quieres, primero debes ser quien realmente eres.",
        "No dejes que el pasado te persiga. Porque lo que haces en el presente podría perseguir tu futuro, sé sabio. Lo que hagas ahora o en el futuro nunca podrá ocultar tu pasado, pero eso no significa que dejes que el pasado te controle.",
        "Ese \"y si\" es una herida que nunca sana.",
        "Si fuera fácil, no valdría la pena.",
        "No mereces nada, te lo ganas.",
        "La perfección no es interesante, salir victorioso a pesar de las pruebas de la adversidad: eso es lo que me impresiona.",
        "No participes en las Olimpiadas de \"siente pena por mí\"; nosotros no competimos en eso.",
        "Cuando quieres algo, aceptas el terreno que viene con ello, sea cual sea ese terreno.",
        "La verdadera visión es cuando tu mente es más poderosa que lo que está frente a tus ojos.",
        "Ciertos eventos te harán progresar, ciertos eventos harán lo contrario, así parece. Esos contrarios son oportunidades de aprendizaje que serán útiles en el futuro.",
        "Paga el precio de ser el jefe o paga el precio del arrepentimiento.",
        "La opinión de otras personas sobre ti no tiene que convertirse en tu realidad.",
        "No obtienes lo que deseas, obtienes aquello por lo que trabajas.",
        "La autodisciplina comienza con el dominio de tus pensamientos. Si no controlas lo que piensas, no puedes controlar lo que haces. Simplemente, la autodisciplina te permite pensar primero y actuar después.",
        "¿Qué es la derrota? Nada más que educación; nada más que el primer paso hacia algo mejor.",
        "No es lo que te sucede, sino cómo reaccionas ante ello lo que importa.",
        "Controla tu ira. Si sientes ira hacia otros, ellos te controlan.",
        "Tu mayor desafío es presentarte cuando tu mente está fabricando las mejores excusas.",
        "Puedes experimentar el dolor de la disciplina o el dolor del arrepentimiento. La elección es tuya.",
        "Todo lo que te debilite física, intelectual y espiritualmente, recházalo como veneno.",
        "Suda más durante la paz, sangra menos durante la guerra.",
        "Con el coraje de empezar y la disciplina de resistir, la victoria se convierte en cuestión de tiempo.",
        "Un buen líder es una persona que asume un poco más de culpa y un poco menos de crédito del que le corresponde.",
        "Sé fuerte, pero no rudo. Sé amable, pero no débil. Sé audaz, pero no abusivo. Sé humilde, pero no tímido. Sé orgulloso, pero no arrogante.",
        "La paciencia es amarga, pero su fruto es dulce.",
        "La paciencia no es pasiva, al contrario; es activa. Es fuerza concentrada.",
        "No hay nada imposible para quien quiera intentarlo.",
        "La inteligencia no es la capacidad de almacenar información, sino de saber dónde encontrarla.",
        "Primero es una intención. Luego un comportamiento. Luego un hábito. Luego una práctica. Luego una segunda naturaleza. Luego es simplemente quien eres.",
        "Lo que quieras hacer, hazlo ahora. Solo hay un número limitado de mañanas.",
        "Las personas que dicen que no se puede hacer no deberían interrumpir a quienes lo están haciendo.",
        "Solo hay un rincón del universo que puedes estar seguro de mejorar, y ese es tu propio ser.",
        "El tonto cree que es sabio, pero el sabio se sabe tonto.",
        "El dolor puede cambiarte, pero eso no significa que tenga que ser un cambio malo. Toma ese dolor y conviértelo en sabiduría.",
        "El tiempo es realmente el único capital que cualquier ser humano tiene, y lo único que no puede permitirse perder.",
        "Sigue tu propio camino, sin importar lo que diga la gente.",
        "Haz algo. Si funciona, haz más. Si no funciona, haz algo diferente.",
        "Aprender es lo único que la mente nunca agota, nunca teme y nunca lamenta.",
        "Un ganador es un soñador que nunca se rinde.",
        "Si no luchas por lo que quieres, no llores por lo que perdiste.",
        "Una vez que has aceptado tus defectos, nadie puede usarlos en tu contra.",
        "Una vez que hayamos aprendido lo suficiente sobre el universo, admitiremos que nunca lo sabremos todo.",
        "Preocuparse es como pagar una deuda que no debes.",
        "No puedes enseñarle nada a nadie, solo hacerles darse cuenta de que las respuestas ya están dentro de ellos.",
        "El poder de los pensamientos puede causarte enfermedad o recuperación.",
        "Si quieres ver un milagro, sé un milagro.",
        "Hay tres clases de personas: las que ven, las que ven cuando se les muestra, y las que no ven.",
        "Tus mayores miedos son creados por tu imaginación.",
        "El mayor engaño que sufren los hombres proviene de sus propias opiniones.",
        "Cuando hayas agotado todas las posibilidades, recuerda esto: no las has agotado.",
        "Ama la mano que el destino te reparte y juégala como si fuera tuya.",
        "Si dos personas están de acuerdo en todo, una de ellas es innecesaria.",
        "La mayor competencia es la que tienes contigo mismo.",
        "Cuando estamos cansados, nos atacan ideas que conquistamos hace mucho tiempo.",
        "No soy lo que me sucedió. Soy lo que elijo ser.",
        "El factor más importante en la supervivencia no es la inteligencia ni la fuerza, sino la adaptabilidad.",
        "La fe y el miedo exigen que creas en algo que no puedes ver. Tú eliges.",
        "Al quejarte, le dices a la gente lo débil que eres.",
        "Para obtener lo que amas, primero debes ser paciente con lo que odias.",
        "Cuando todo parece ir en tu contra, recuerda que el avión despega contra el viento, no a favor de él.",
        "Te reirás de tus miedos cuando descubras quién realmente eres.",
        "La paz no se encuentra en una tormenta más calmada, se encuentra en un mejor barco.",
        "Puedes ignorar la realidad, pero no puedes ignorar las consecuencias de ignorar esa realidad.",
        "Ningún hombre es más infeliz que el que nunca enfrenta la adversidad. Porque no se le permite probarse a sí mismo.",
        "Un buen plan ejecutado violentamente ahora es mejor que un plan perfecto ejecutado la próxima semana.",
        "Estudiar y no pensar es un desperdicio. Pensar y no estudiar es peligroso.",
        "El miedo es una reacción. El coraje es una decisión.",
        "La independencia es para muy pocos; es un privilegio de los fuertes.",
        "Te toma la mitad de la vida descubrir que la vida es un proyecto de hágalo usted mismo.",
        "Actúa tu papel con honor.",
        "La preocupación es un mal uso de la imaginación.",
        "El puente entre el conocimiento y la habilidad es la práctica. El puente entre la habilidad y la maestría es el tiempo.",
        "Cuanto más aprendo, más me doy cuenta de cuánto me falta por aprender.",
        "Si no pierdes, no puedes disfrutar las victorias. Así que tengo que aceptar ambas cosas.",
        "Aprendemos poco de la victoria, mucho de la derrota.",
        "Quien habla con deferencia pero aumenta sus preparativos avanzará. Quien habla con belicosidad y avanza apresuradamente retrocederá.",
        "Nuestra vida es lo que nuestros pensamientos hacen de ella.",
        "Realmente no hay una cosa difícil a menos que decidas que es difícil. De lo contrario, es solo lo próximo que estás resolviendo.",
        "Sin importar la situación, nunca dejes que tus emociones superen tu inteligencia.",
        "Decide el tipo de persona que quieres ser y mantenlo, ya sea solo o en compañía.",
        "Si algo está mal, arréglalo si puedes. Pero entrénate para no preocuparte. La preocupación nunca arregla nada.",
        "La vida no es cuestión de tener buenas cartas, sino de jugar bien una mala mano.",
        "Es un camino áspero el que conduce a las alturas de la grandeza.",
        "El día que un hombre se vuelve superior al placer, también será superior al dolor.",
        "Aprende continuamente, siempre hay \"una cosa más\" que aprender.",
        "Podemos quejarnos de que los rosales tienen espinas, o alegrarnos de que los espinos tienen rosas.",
        "Sé paciente y fuerte; algún día este dolor te será útil.",
        "El fracaso es el éxito en progreso.",
        "Cualquiera que deja de aprender es viejo, ya sea a los veinte o a los ochenta.",
        "Si eres gobernado por la mente eres un rey; si por el cuerpo, un esclavo.",
        "El orgullo no es lo opuesto a la vergüenza, sino su fuente. La verdadera humildad es el único antídoto contra la vergüenza.",
        "Cuando empiezas a mejorarte a ti mismo, la soledad es el precio que pagas.",
        "No se te juzga por la altura a la que has ascendido, sino por la profundidad desde la que has subido.",
        "Un hombre no es grande porque no haya fracasado; un hombre es grande porque el fracaso no lo ha detenido.",
        "Un hombre sin visión es un hombre sin futuro. Un hombre sin futuro siempre regresará a su pasado.",
        "Mejor fracasar con honor que triunfar con fraude.",
        "Todas las batallas se ganan o se pierden primero en la mente.",
        "Las emociones del hombre se agitan más rápido que su inteligencia.",
        "Quien compra lo que no necesita se roba a sí mismo.",
        "Quien tiene paciencia puede tener lo que quiera.",
        "El camino del guerrero es de por vida, y la maestría es a menudo simplemente mantenerse en el camino.",
        "Las cometas se elevan más alto contra el viento, no a favor de él.",
        "Si la gente supiera lo duro que tuve que trabajar para lograr mi maestría, no les parecería tan maravilloso.",
        "Nunca te vayas a dormir sin una petición a tu subconsciente.",
        "Acepta los eventos de la forma en que sucedan: este es el camino hacia la paz.",
        "Practica incluso lo que parece imposible.",
        "El hombre que persigue dos conejos no atrapa ninguno.",
        "Lo vas a lograr, pero siempre va a sentirse como si no fueras a lograrlo.",
        "Planea lo difícil mientras es fácil, haz lo grande mientras es pequeño.",
        "La persistencia no es suficiente. Uno debe decidir si persistir como un sufridor o como un guerrero.",
        "El nivel de agudeza y disciplina que se necesita para llevarte a las alturas que sueñas es realmente simple, solo que no es fácil.",
        "El mayor enemigo no se encuentra afuera. La destrucción a menudo viene de dentro.",
        "Todos sabían que era imposible, hasta que un tonto que no lo sabía llegó y lo hizo.",
        "No puedes hacer fuerte a un hombre débil haciendo débil a un hombre fuerte.",
        "Tienes poder sobre tu mente, no sobre los eventos externos. Comprende esto y encontrarás fortaleza.",
        "Un diamante es solo un trozo de carbón que se mantuvo en su trabajo.",
        "El mayor riesgo es no tomar ningún riesgo.",
        "Si defines el problema correctamente, casi tienes la solución.",
        "El pasado está en tu cabeza, el futuro está en tus manos.",
        "La vida es bastante simple. Haces algunas cosas. La mayoría falla. Algunas funcionan. Haces más de lo que funciona.",
        "Que tu sentido del deber supere una atmósfera de miedo y la tendencia a posponer aspiraciones.",
        "Todo lo que siempre has querido está al otro lado del miedo.",
        "La disciplina es elegir entre lo que quieres ahora y lo que más quieres.",
        "La conformidad es el último refugio del falto de imaginación.",
        "Un diamante es un trozo de carbón que se mantuvo en el trabajo.",
        "No hay mayor daño para el hombre que el tiempo desperdiciado.",
        "No eches a perder lo que tienes deseando lo que no tienes; recuerda que lo que ahora tienes fue alguna vez algo que solo esperabas.",
        "Un hombre que es maestro de la paciencia es maestro de todo lo demás.",
        "Nunca pongas la pasión por delante del principio, incluso si ganas, perderás.",
        "Algunas personas quieren que suceda, algunas desean que suceda, otras hacen que suceda.",
        "No nos elevamos al nivel de nuestras expectativas, caemos al nivel de nuestro entrenamiento.",
        "Es más fácil encontrar hombres que se ofrezcan a morir, que encontrar aquellos dispuestos a soportar el dolor con paciencia.",
        "No puedes esperar subir al podio si no participas en la carrera.",
        "El que se cae y se levanta es más fuerte que el que nunca lo intentó.",
        "Malas noticias: No vas a \"encajar\" con todos. Buenas noticias: Los grandes nunca lo hacen.",
        "Nunca he sido talentoso, solo soy bueno para nunca rendirme.",
        "La felicidad no es la ausencia de problemas, es la capacidad de lidiar con ellos.",
        "Si haces lo que es fácil, tu vida será difícil.",
        "No puedes volver atrás y cambiar el principio, pero puedes empezar donde estás y cambiar el final.",
        "Se aprende más observando que escuchando.",
        "Los que nunca cometen errores trabajan para los que sí los cometemos.",
        "Una idea nueva no debe juzgarse por sus resultados inmediatos.",
        "Nunca estás listo para lo que tienes que hacer. Simplemente lo haces. Eso te hace estar listo.",
        "Asume riesgos: si ganas, serás feliz; si pierdes, serás sabio.",
        "Un pueblo que valora sus privilegios por encima de sus principios pronto pierde ambos.",
        "El camino más rápido hacia el significado y el éxito: elige una cosa y da todo.",
        "No tengas miedo de empezar de nuevo. Esta vez no empiezas desde cero. Empiezas desde la experiencia.",
        "No hay nada noble en ser superior a tu prójimo; la verdadera nobleza es ser superior a tu yo anterior.",
        "Te ganarás el respeto de todos si empiezas por ganarte el respeto de ti mismo.",
        "Crea una visión de quién quieres ser, y luego vive esa imagen como si ya fuera verdad.",
        "El precio de la excelencia es la disciplina. El costo de la mediocridad es la decepción.",
        "Las dificultades fortalecen la mente, como el trabajo fortalece el cuerpo.",
        "No puedes esperar progresar en áreas donde no has tomado acción.",
        "Ninguna cantidad de ansiedad cambia nada de lo que va a suceder.",
        "Muéstrame un hombre de habilidad promedio pero deseo extraordinario y te mostraré un ganador siempre.",
        "La forma más rápida de tener éxito es empezar ahora y resolverlo sobre la marcha.",
        "Las personas no deciden sus futuros, deciden sus hábitos y sus hábitos deciden sus futuros.",
        "Enséñales temprano a tus hijos lo que aprendiste tarde.",
        "Si dedicas 100 horas al año a cualquier disciplina, que son solo 18 minutos al día, serás mejor que el 95% del mundo en esa disciplina.",
        "La tarea no es tanto ver lo que nadie ha visto aún, sino pensar lo que nadie ha pensado todavía sobre aquello que todos ven.",
        "Si te irrita cada roce, ¿cómo se pulirá tu espejo?",
        "El miedo es solo tan profundo como la mente lo permite.",
        "La dificultad es lo que despierta al genio.",
        "Lo que ha de dar luz debe soportar el arder.",
        "He aprendido que el éxito no se mide tanto por la posición que uno ha alcanzado en la vida como por los obstáculos que ha superado mientras intentaba triunfar.",
        "La comodidad es la peor adicción.",
        "Te conviertes en aquello a lo que le das tu atención.",
        "Las circunstancias no hacen al hombre, solo lo revelan ante sí mismo.",
        "No pierdas más tiempo discutiendo lo que debería ser un buen hombre. Sé uno.",
        "Que aquel que quiera mover el mundo primero se mueva a sí mismo.",
        "Entre el estímulo y la respuesta hay un espacio. En ese espacio está nuestro poder de elegir nuestra respuesta. En nuestra respuesta está nuestro crecimiento y nuestra libertad.",
        "No hay nada fuera de ti que pueda hacerte mejor, más fuerte, más rico, más rápido o más inteligente. Todo está dentro. Todo existe. No busques nada fuera de ti mismo.",
        "Sé tolerante con los demás y estricto contigo mismo.",
        "Dos cosas te definen: tu paciencia cuando no tienes nada y tu actitud cuando lo tienes todo.",
        "No solo te despiertas y te conviertes en mariposa.",
        "La tenacidad es la capacidad de aguantar cuando soltar parece lo más atractivo.",
        "Hay riesgos y costos en la acción. Pero son mucho menores que los riesgos a largo plazo de la cómoda inacción.",
        "Para lograr grandes cosas se necesitan dos cosas: un plan y no suficiente tiempo.",
        "La duda solo puede ser eliminada por la acción.",
        "Si tus acciones inspiran a otros a soñar más, aprender más, hacer más y ser más, eres un líder.",
        "No se trata de tener un historial impecable. Se trata de aprender de las imperfecciones en tu historial.",
        "Sé lo suficientemente valiente para ser malo en algo nuevo.",
        "Acuéstate más inteligente de lo que te despertaste.",
        "El éxito lento construye carácter, el éxito rápido construye ego.",
        "Solo porque alguien tropiece y pierda su camino no significa que esté perdido para siempre.",
        "Pero no podemos simplemente sentarnos y mirar nuestras heridas para siempre.",
        "Y ahora que no tienes que ser perfecto, puedes ser bueno.",
        "El éxito viene de la ejecución despiadada de lo básico.",
        "Se necesita mucho trabajo duro para hacer algo simple.",
        "Todos piensan en cambiar el mundo, pero nadie piensa en cambiarse a sí mismo.",
        "Los de mente cerrada necesitan que les den el arte con cuchara.",
        "Haz algo en lugar de matar el tiempo. Porque el tiempo te está matando a ti.",
        "Deja que cada decisión esté en línea con tu visión.",
        "Si quieres hacer algo más grande que el promedio, no puedes ceder al miedo de ser un marginado.",
        "Lo que más importa es lo bien que caminas a través del fuego.",
        "Estás a una decisión de distancia de una vida completamente diferente.",
        "Si estás viviendo para mañana, siempre estarás un día atrás.",
        "Saca lo mejor de ti mismo, porque eso es todo lo que hay de ti.",
        "Los ojos son inútiles cuando la mente está ciega.",
        "A la larga, los hombres solo dan en aquello a lo que apuntan. Por lo tanto, aunque fallen de inmediato, es mejor que apunten a algo alto.",
        "Quien tiene un por qué para vivir puede soportar casi cualquier cómo.",
        "Los hombres pueden dividirse en 2 grupos: uno que avanza y logra algo, y otro que viene después y critica.",
        "Una mala actitud es como un neumático pinchado. No puedes ir a ningún lado hasta que lo cambies.",
        "Ningún pájaro vuela demasiado alto si vuela con sus propias alas.",
        "Resuelve el problema o abandona el problema. No vivas con el problema.",
        "Actúa según tus principios, no según tu estado de ánimo.",
        "Los que no se comprometen con nada se distraen con todo.",
        "Cuando nos esforzamos por ser mejores de lo que somos, todo a nuestro alrededor también mejora.",
        "No hay pasión en conformarse con una vida inferior a la que eres capaz de vivir.",
        "Un hombre creativo es motivado por el deseo de lograr, no por el deseo de superar a otros.",
        "La vida es una larga preparación para algo que nunca sucede.",
        "Ya no escucho lo que la gente dice, solo observo lo que hacen. El comportamiento nunca miente.",
        "Las personas inteligentes aprenden de todo y de todos; las personas promedio, de sus experiencias. Los tontos ya tienen todas las respuestas.",
        "La primera regla es mantener un espíritu tranquilo. La segunda es mirar las cosas de frente y conocerlas por lo que son.",
        "Siempre es una lucha levantar un peso más grande.",
        "Un hombre que teme al sufrimiento ya está sufriendo por lo que teme.",
        "Si un hombre no sabe a qué puerto navega, ningún viento le es favorable.",
        "Siempre estoy haciendo lo que no puedo hacer, para poder aprender cómo hacerlo.",
        "Construyes sobre el fracaso. Lo usas como escalón. Cierra la puerta al pasado. No intentas olvidar los errores, pero no te quedas pensando en ellos. No dejas que tengan tu energía, ni tu tiempo, ni tu espacio.",
        "El contenido de tu carácter es tu elección. Día a día, lo que eliges, lo que piensas y lo que haces es en lo que te conviertes.",
        "Los cobardes nunca empezaron y los débiles murieron en el camino.",
        "Cuando te levantas por la mañana, piensa en qué precioso privilegio es estar vivo: respirar, pensar, disfrutar, amar.",
        "El secreto del éxito es el enfoque en el propósito.",
        "Lo único más peligroso que la ignorancia es la arrogancia.",
        "Somos lo que hacemos repetidamente. La excelencia, entonces, no es un acto, sino un hábito.",
        "Mientras esperamos la vida, la vida pasa.",
        "El éxito no es más que unas pocas disciplinas simples, practicadas todos los días.",
        "Cuanto más sabe, más consciente será de su ignorancia.",
        "El impedimento para la acción hace avanzar la acción. Lo que se interpone en el camino se convierte en el camino.",
        "Nuestra mayor debilidad radica en rendirnos. La forma más segura de tener éxito es siempre intentar una vez más.",
        "Una gema no puede pulirse sin fricción, ni un hombre perfeccionarse sin pruebas.",
        "Tu valor consiste en lo que eres y no en lo que tienes.",
        "El que hace el mal es más desafortunado que el que lo sufre.",
        "Una de las pruebas más verdaderas de la integridad es su rotunda negativa a ser comprometida.",
        "Dios no da nada a quienes mantienen los brazos cruzados.",
        "Saber cómo pensar te empodera mucho más allá de quienes solo saben qué pensar.",
        "Si planeas ser algo menos de lo que eres capaz de ser, probablemente serás infeliz todos los días de tu vida.",
        "No hay nada mejor que la adversidad. Cada derrota, cada desamor, cada pérdida contiene su propia semilla, su propia lección sobre cómo mejorar tu rendimiento la próxima vez.",
        "Aprende a amar el odio. Acéptalo. Disfrútalo. Te lo ganaste. Todos tienen derecho a su propia opinión y todos deberían tener una sobre ti. Los que te odian son un buen problema. Nadie odia a los buenos. Odian a los grandes.",
        "Acepta tu incapacidad de controlar todas las cosas. Acepta la responsabilidad de todo lo que está bajo tu control. Acepta que existen obstáculos internos y externos. Acepta que estás equipado para navegar por todos ellos.",
        "La experiencia es el tipo de maestro más duro. Te da el examen primero y la lección después.",
        "Maduramos con el daño, no con los años.",
        "Si estás deprimido, estás viviendo en el pasado. Si estás ansioso, estás viviendo en el futuro. Si estás en paz, estás viviendo en el presente.",
        "Si crees que no podemos cambiar el mundo, simplemente significa que no eres uno de los que lo harán.",
        "Quizás no se trata de un final feliz. Quizás se trata de la historia.",
        "Algunas personas llevan alegría dondequiera que van, y otras llevan alegría cuando se van.",
        "Observa constantemente que todas las cosas ocurren por cambio, y acostúmbrate a considerar que la naturaleza del universo no ama nada tanto como cambiar.",
        "Ser demasiado bueno tiende a ser poco interesante.",
        "Muy a menudo disfrutamos la comodidad de la opinión sin la incomodidad del pensamiento.",
        "Estudiar sin pensar es vano; pensar sin estudiar es peligroso.",
        "Un hombre con convicción abrumará a cien que solo tienen opiniones.",
        "Los tontos se multiplican cuando los sabios callan.",
        "Prepárate para revisar cualquier sistema, descartar cualquier método, abandonar cualquier teoría si el éxito del trabajo lo requiere.",
        "Ayudar a otros a desarrollarse y tener éxito en la vida es una recompensa en sí misma y solo tiene valor cuando no se espera nada a cambio.",
        "Ahora no es momento de pensar en lo que no tienes. Piensa en lo que puedes hacer con lo que hay.",
        "Diría que soy un trabajo en progreso, pero eso sugeriría que algún día dejaré de ser un trabajo en progreso.",
        "No te rindas. Normalmente es la última llave del llavero la que abre la puerta.",
        "La vida es una comedia para los que piensan, una tragedia para los que sienten.",
        "El tacto es la habilidad de decirle a alguien que se vaya al infierno de tal manera que espere con ganas el viaje.",
        "Deja el mal hecho por otro donde surgió el mal.",
        "No te perturbes imaginando toda tu vida de una vez. No siempre estés pensando en qué sufrimientos, y cuántos, podrían posiblemente caer sobre ti.",
        "Cada vez que creo saberlo todo, resulta que \"todo\" tiene un poco más de volumen del que asumí.",
        "La diferencia entre la estupidez y el genio es que el genio tiene sus límites.",
        "Es mejor ser un guerrero en un jardín que un jardinero en una guerra.",
        "El gran éxito siempre viene con el riesgo de un enorme fracaso.",
        "El éxito viene de la curiosidad, la concentración, la perseverancia y la autocrítica.",
        "Es la marca de una mente educada ser capaz de considerar una idea sin aceptarla.",
        "La opinión de 10,000 personas no tiene valor si ninguna de ellas sabe algo sobre el tema.",
        "Cuanto más valoramos cosas fuera de nuestro control, menos control tenemos.",
        "Haz viajes. Inténtalos. No hay nada más.",
        "Los orígenes nunca deberían ser una barrera para el éxito. Un comienzo modesto en la vida puede ser más una ayuda que un obstáculo.",
        "No dejes que las deficiencias de otro te hagan quedar corto.",
        "Nuestra envidia siempre dura más que la felicidad de aquellos a quienes envidiamos.",
        "Nada vendrá de la nada.",
        "Las personas débiles se vengan. Las personas fuertes perdonan. Las personas inteligentes ignoran.",
        "No controlo el viento; solo lo estudio.",
        "El honor puede no ganar poder, pero gana respeto. Y el respeto gana poder.",
        "El arma final es el cerebro, todo lo demás es suplementario.",
        "Si no superas tu tendencia a rendirte fácilmente, tu vida no lleva a nada.",
        "Entrenar es como barrer el suelo. Solo porque lo hayamos hecho una vez no significa que el suelo estará limpio para siempre.",
        "Recuerda que somos nosotros quienes nos atormentamos, quienes nos creamos dificultades, es decir, nuestras opiniones. ¿Qué significa, por ejemplo, ser insultado? Párate junto a una roca e insúltala, ¿qué has logrado? Si alguien responde al insulto como una roca, ¿qué ha ganado el ofensor con su invectiva?",
        "En ausencia de propósito, la vida se convierte en un viaje interminable hacia ninguna parte.",
        "Solo los muertos han visto el fin de la guerra.",
        "Prevenir es mejor que curar.",
        "Nada enseñado por la fuerza permanece en el alma.",
        "Todo lo que existe en tu vida, existe por dos cosas: algo que hiciste o algo que no hiciste.",
        "Un hombre sin ética es una bestia salvaje suelta en este mundo.",
        "Pensar es difícil, por eso la mayoría de las personas juzgan.",
        "No encuentras la fuerza de voluntad, la creas.",
        "La palabra feliz perdería su significado si no estuviera equilibrada por la tristeza.",
        "No reces por una vida fácil. Reza por la fuerza para soportar una difícil.",
        "No eres todo lo que podrías ser, y lo sabes.",
        "Recuerda vivir mientras estás ocupado sobreviviendo.",
        "Los planes no son nada, planificar lo es todo.",
        "Un hombre que se atreve a desperdiciar una hora de tiempo no ha descubierto el valor de la vida.",
        "Tienes que decidir quién eres y forzar al mundo a lidiar contigo, no con su idea de ti.",
        "El arte de vivir se parece más a la lucha que a la danza, en cuanto se mantiene firme contra lo accidental y lo imprevisto, y no es propenso a caer.",
        "A medida que envejezco, presto menos atención a lo que los hombres dicen. Solo observo lo que hacen.",
        "Apretaré mi cinturón antes de pedir ayuda.",
        "Nadie está hecho como tú, tú te diseñaste a ti mismo.",
        "Ningún hombre tiene derecho a ser un aficionado en materia de entrenamiento físico. Es una vergüenza que un hombre envejezca sin ver la belleza y la fuerza de la que su cuerpo es capaz.",
        "Cuanto más cerca está un hombre de una mente tranquila, más cerca está de la fuerza.",
        "Aquí hay una regla para recordar en el futuro, cuando algo te tienta a sentir amargura: no \"esto es una desgracia\", sino \"soportar esto dignamente es buena fortuna\".",
        "Cuando eres bueno en algo, se lo dirás a todos. Cuando eres grandioso en algo, ellos te lo dirán.",
        "Primero te ignoran. Luego se burlan de ti. Luego te atacan y quieren quemarte. Y luego te construyen monumentos.",
        "La libertad significa responsabilidad. Por eso la mayoría de los hombres la temen.",
        "Si dices la verdad, no tienes que recordar nada.",
        "Tu momento está llegando si sigues avanzando.",
        "No es la muerte lo que un hombre debe temer, sino que debe temer no haber comenzado nunca a vivir.",
        "Los procedimientos de hoy son los resultados de mañana. Si puedes enamorarte de los procedimientos de hoy, amarás los resultados de mañana.",
        "Todos los problemas de la humanidad provienen de la incapacidad del hombre de sentarse tranquilamente en una habitación solo.",
        "Nunca dejes que el futuro te perturbe. Lo enfrentarás, si es necesario, con las mismas armas de razón que hoy te arman contra el presente.",
        "El hombre madura a través del dolor, el fracaso, el rechazo, la pérdida, la falta de respeto y el desamor, no a través de la edad.",
        "Forjamos las cadenas que llevamos en la vida.",
        "Para hacer cualquier cosa a un alto nivel, tiene que ser una obsesión.",
        "Si quieres mejorar, conténtate con que te consideren tonto e ignorante respecto a las cosas externas.",
        "La violencia es el último refugio del incompetente.",
        "El miedo es como el fuego, puede ser útil si sabes cómo usarlo. Si no, te quemarás.",
        "Para tener un gran éxito, tienes que estar preparado para fracasar en grande. Si no puedes hacer ambas cosas, tienes un problema.",
        "Siempre hablamos de que alguien nos tiene antipatía \"sin razón\", pero la gente también te querrá \"sin razón\". Así que no le des demasiada importancia a ninguno de los dos lados.",
        "Los cobardes mueren muchas veces antes de su muerte; los valientes nunca prueban la muerte más que una vez.",
        "Nada es más difícil, y por lo tanto más precioso, que ser capaz de decidir.",
        "Camina por un solo sendero, sin volverte arrogante con la victoria ni destrozado con la derrota, sin olvidar la cautela cuando todo está tranquilo ni asustarte cuando el peligro amenaza.",
        "El alma se tiñe con el color de sus pensamientos.",
        "No pido una carga más ligera. Sino hombros más anchos.",
        "No negocies contigo mismo. Instrúyete a ti mismo.",
        "No puedes desear tanto un carácter fuerte como una vida fácil.",
        "El coraje no es tener la fuerza para seguir adelante, es seguir adelante cuando no tienes fuerza.",
        "La vida no te sucede a ti, sucede involucrándote.",
        "Es fatal entrar en una guerra sin la voluntad de ganarla.",
        "Nunca sabes lo fuerte que eres hasta que ser fuerte es tu única opción.",
        "No puedes complacer a todos, a veces tienes que actuar y dejar que todos los demás reaccionen.",
        "No hay cuestión de \"si\", la cuestión es solo cuándo, cuando estás decidido sobre la misión.",
        "¿Cuánto tiempo vas a esperar antes de exigir lo mejor para ti mismo?",
        "El mundo te promete comodidad, pero no fuiste hecho para la comodidad. Fuiste hecho para la grandeza.",
        "La integridad no es una ruta rápida, pero es una ruta segura.",
        "Sé tu propio mayor fan, tu propio mayor creyente, y cárgalo en tu espalda y lleva el peso.",
        "Primero dite a ti mismo lo que quieres ser; y luego haz lo que tengas que hacer.",
        "Temo el día en que la tecnología supere nuestra interacción humana. El mundo tendrá una generación de idiotas.",
        "No importa lo que soportes, sino cómo lo soportas.",
        "Rechaza tu sentimiento de agravio y el agravio mismo desaparece.",
        "No hagas planes pequeños. No tienen magia para agitar la sangre de los hombres y probablemente no se realizarán. Haz grandes planes; apunta alto en esperanza y trabajo, recordando que un diagrama noble y lógico, una vez registrado, nunca morirá, sino que mucho después de que nos hayamos ido será algo vivo, afirmándose con insistencia cada vez mayor.",
        "Las dificultades a menudo preparan a personas ordinarias para un destino extraordinario.",
        "Cuando quieres cambiar las cosas, no puedes complacer a todos. Si complaces a todos, no estás progresando lo suficiente.",
        "No negocies contigo mismo, instrúyete.",
        "El éxito no es definitivo, el fracaso no es fatal: lo que cuenta es el coraje para continuar.",
        "Si no es correcto no lo hagas; si no es verdad no lo digas.",
        "Los llamados placeres, cuando sobrepasan cierto límite, no son más que castigos.",
        "Si no sacrificas por lo que quieres, lo que quieres se convierte en el sacrificio.",
        "Tu mayor enemigo es tu mente descontrolada.",
        "Aprende a luchar para nunca tener que luchar.",
        "Cuando una persona no puede encontrar un sentido profundo de significado, se distrae con el placer.",
        "Nada es permanente en este mundo cruel, ni siquiera nuestros problemas.",
        "Deja que se equivoquen sobre ti. No hay nada que demostrarles.",
        "Si quieres que el presente sea diferente del pasado, estudia el pasado.",
        "Si quieres vivir una vida feliz, átala a una meta, no a personas u objetos.",
        "No hay secretos, solo hay información que has descubierto e información que no has descubierto.",
        "Necesitas motivación para actuar. Necesitas información para saber sobre qué actuar. Necesitas curiosidad para obtener inteligencia que pilote apropiadamente estos actos motivados. Así que sé curioso.",
        "Un ganador es solo un perdedor que lo intentó una vez más.",
        "Tratamos el cuerpo rigurosamente para que no sea desobediente a la mente.",
        "Los dispuestos son guiados por el destino, los reacios son arrastrados.",
        "El hombre que teme la muerte nunca hará nada digno de un hombre que está vivo.",
        "Un comandante nunca deposita tanta confianza en la paz como para no prepararse para la guerra.",
        "No tengas miedo. Lo vas a lograr, pero siempre va a sentirse como si no fueras a lograrlo.",
        "La consistencia puede sonar mucho como aburrido, pero ¿qué otra cosa pensarías que es ser grandioso? ¿Suerte?",
        "Mantén tu rostro siempre hacia el sol y las sombras caerán detrás de ti.",
        "La pena más pesada por negarse a gobernar es ser gobernado por alguien inferior a ti.",
        "Excava dentro. Dentro está el manantial del Bien; y siempre está listo para brotar, si solo excavas.",
        "Eres lo que haces, no lo que dices que harás.",
        "Equivocarse a la propia manera es mejor que acertar a la manera de otro.",
        "Un gran hombre es duro consigo mismo, un hombre débil es duro con los demás.",
        "Amarse a uno mismo es el comienzo de un romance de toda la vida.",
        "Preocúpate por lo que piensan los demás y siempre serás su prisionero.",
        "El hombre no está preocupado tanto por los problemas reales como por sus ansiedades imaginadas sobre los problemas reales.",
        "El hombre feliz está satisfecho con su situación presente, sin importar cuál sea.",
        "La primera y más grande victoria es conquistarse a uno mismo.",
        "Para poder controlarme, primero debo aceptarme yendo con mi naturaleza y no contra ella.",
        "Que los hombres vean, que sepan que hay un hombre real que vive como estaba destinado a vivir.",
        "Quien no puede obedecerse a sí mismo será mandado.",
        "Cuando temes algo, aprende todo lo que puedas sobre ello. El conocimiento conquista el miedo.",
        "Siempre pensé que era yo contra el mundo y luego un día me di cuenta de que es solo yo contra mí.",
        "Un hombre que carece de propósito se distrae con el placer.",
        "Es difícil aceptar que no todos lo van a \"entender\", pero por eso no es para todos los demás. Es algo tuyo.",
        "Cuanto mayor es la dificultad, más gloria hay en superarla.",
        "Nos deleitamos con la belleza de la mariposa, pero rara vez admitimos los cambios por los que ha pasado para lograr esa belleza.",
        "Déjame caer si debo caer. El que estoy llegando a ser me atrapará.",
        "Detrás de un hombre que perdona todo, hay un hombre que conoce el peso de sus propios pecados.",
        "El intento de escapar del dolor crea más dolor.",
        "El verdadero desarrollo no respeta la comodidad.",
        "Hasta donde podemos discernir, el único propósito de la existencia humana es encender una luz de significado en la oscuridad del mero ser.",
        "El día que plantas la semilla no es el día que comes el fruto.",
        "La verdad no cambia porque sea o no sea creída por la mayoría de las personas.",
        "Un caballero con armadura reluciente no tiene valor probado. Dame un caballero probado en batalla con armadura maltratada de encuentros con los deplorables de la humanidad.",
        "La medida de la inteligencia es la capacidad de cambiar.",
        "No hay cosecha sin hambre.",
        "Es la mente misma la que extravía a la mente. De la mente, no seas descuidado.",
        "No puedes soñarte un carácter; debes forjarte y martillarte uno.",
        "Mucho saldrá mal antes de que todo salga bien.",
        "Vivimos solo ahora. Todo lo demás ya pasó o es desconocido.",
        "No serás castigado por tu ira, serás castigado por tu ira.",
        "No aprendes a nadar leyendo sobre el agua.",
        "Las decisiones más difíciles requieren las voluntades más fuertes.",
        "Sobre todo, no te mientas a ti mismo.",
        "Tu cuerpo puede soportar casi todo; es a la mente a la que tienes que convencer.",
        "La vida es del género en primera persona. Trátala como tal.",
        "Los buenos líderes no ponen excusas. En cambio, encuentran la manera de hacerlo.",
        "Solo porque te tomó más tiempo que a otros no significa que hayas fracasado.",
        "Cuanto más te conoces a ti mismo, menos necesitas la aprobación de otros.",
        "Conocerte a ti mismo es el principio de toda sabiduría.",
        "No es el tamaño del hombre sino el tamaño de su corazón lo que importa.",
        "Es poco probable que cambies de nivel sin lágrimas.",
        "Trabajas con el arado que tienes.",
    ]
}
